"use client";

import { useState } from "react";

type Profile={id:number,name:string,nameAr:string,initials:string,relation:string,relationAr:string,age:number,status:string,statusAr:string,color:string,access:string,accessAr:string,next?:string,nextAr?:string};
const profiles:Profile[]=[
  {id:1,name:"Mariam Ahmed",nameAr:"مريم أحمد",initials:"MA",relation:"Account owner",relationAr:"صاحبة الحساب",age:34,status:"Verified",statusAr:"موثّق",color:"teal",access:"Full access",accessAr:"وصول كامل",next:"Sun, 2 Aug · 4:30 PM",nextAr:"الأحد، ٢ أغسطس · ٤:٣٠ م"},
  {id:2,name:"Yousef Ahmed",nameAr:"يوسف أحمد",initials:"YA",relation:"Son",relationAr:"الابن",age:8,status:"Guardian managed",statusAr:"بإدارة ولي الأمر",color:"blue",access:"Full guardian access",accessAr:"وصول كامل لولي الأمر",next:"Tue, 11 Aug · 10:00 AM",nextAr:"الثلاثاء، ١١ أغسطس · ١٠:٠٠ ص"},
  {id:3,name:"Noura Ahmed",nameAr:"نورة أحمد",initials:"NA",relation:"Daughter",relationAr:"الابنة",age:15,status:"Transition review",statusAr:"مراجعة انتقالية",color:"gold",access:"Age-aware shared access",accessAr:"وصول مشترك حسب العمر"},
  {id:4,name:"Fatima Ali",nameAr:"فاطمة علي",initials:"FA",relation:"Mother",relationAr:"الأم",age:67,status:"Consent granted",statusAr:"بموافقة صريحة",color:"rose",access:"Appointments only",accessAr:"المواعيد فقط"},
];

export default function Family(){
  const [lang,setLang]=useState<"en"|"ar">("en");const [selected,setSelected]=useState(profiles[0]);const [tab,setTab]=useState<"overview"|"access"|"activity">("overview");const [adding,setAdding]=useState(false);const [notice,setNotice]=useState("");const [permissions,setPermissions]=useState({appointments:true,wallet:false,documents:false,notifications:true});const ar=lang==="ar";
  const select=(p:Profile)=>{setSelected(p);setTab("overview")};
  return <main className={`family-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <header className="family-header"><a className="brand" href="/"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav><a href="/providers">{ar?"ابحث عن رعاية":"Find care"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a><a href="/wallet">{ar?"المحفظة الصحية":"Health wallet"}</a><a className="active" href="/family">{ar?"العائلة":"Family"}</a></nav><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a href="/notifications">●</a><span>MA</span></div></header>
    <section className="family-hero"><div><p>{ar?"الرعاية معاً، بخصوصية":"CARE TOGETHER, WITH PRIVACY"}</p><h1>{ar?"العائلة والمعالون":"Family & dependants"}</h1><span>{ar?"ساعد عائلتك في الوصول إلى الرعاية، مع حدود واضحة للموافقة والخصوصية في كل مرحلة عمرية.":"Help your family access care with clear consent and privacy boundaries at every age."}</span></div><button onClick={()=>setAdding(true)}>＋ {ar?"إضافة فرد من العائلة":"Add family member"}</button></section>
    <section className="family-workspace"><div className="family-note"><span>♙</span><p><b>{ar?"كل ملف مستقل":"Every profile remains separate"}</b>{ar?"لا تمنح العلاقة العائلية وصولاً تلقائياً للسجلات الصحية. يعتمد الوصول على العمر والوصاية والموافقة والغرض.":"A family relationship never grants automatic health-record access. Access depends on age, guardianship, consent, and purpose."}</p></div>
      <div className="family-layout"><aside className="profile-list"><div><h2>{ar?"ملفات العائلة":"Family profiles"}</h2><span>{profiles.length}</span></div>{profiles.map(p=><button className={selected.id===p.id?"active":""} key={p.id} onClick={()=>select(p)}><span className={p.color}>{p.initials}</span><div><b>{ar?p.nameAr:p.name}</b><small>{ar?p.relationAr:p.relation} · {p.age} {ar?"سنة":"years"}</small></div><i>›</i></button>)}<button className="add-profile" onClick={()=>setAdding(true)}>＋ {ar?"إضافة ملف":"Add profile"}</button></aside>
        <section className="family-profile"><div className="family-profile-head"><span className={selected.color}>{selected.initials}</span><div><p>{ar?selected.relationAr:selected.relation}</p><h2>{ar?selected.nameAr:selected.name}</h2><small>{selected.age} {ar?"سنة":"years old"}</small></div><i className={selected.status.includes("Transition")?"warning":"safe"}>✓ {ar?selected.statusAr:selected.status}</i></div>
          {selected.status.includes("Transition")&&<div className="age-transition"><span>!</span><p><b>{ar?"مراجعة الخصوصية المرتبطة بالعمر":"Age-based privacy review"}</b>{ar?"مع اقتراب نورة من مرحلة الاستقلال، راجعوا معاً ما يمكن مشاركته ومن يمكنه رؤية معلوماتها.":"As Noura approaches independent consent, review together what is shared and who can see it."}</p><button onClick={()=>setTab("access")}>{ar?"مراجعة الوصول":"Review access"}</button></div>}
          <div className="family-tabs"><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}>{ar?"نظرة عامة":"Overview"}</button><button className={tab==="access"?"active":""} onClick={()=>setTab("access")}>{ar?"الوصول والموافقة":"Access & consent"}</button><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}>{ar?"النشاط":"Activity"}</button></div>
          {tab==="overview"&&<div className="family-overview"><div className="family-stats"><article><span>◎</span><div><b>{selected.next||"—"}</b><small>{ar?"الموعد القادم":"Next appointment"}</small></div></article><article><span>Q</span><div><b>{selected.id===2?"QAR 1,420":selected.id===3?"QAR 980":"QAR 2,150"}</b><small>{ar?"رصيد المزايا":"Benefits balance"}</small></div></article><article><span>▤</span><div><b>{selected.id===1?"5":"2"}</b><small>{ar?"مستندات المحفظة":"Wallet documents"}</small></div></article></div><section className="family-actions"><h3>{ar?"إجراءات سريعة":"Quick actions"}</h3><div><a href="/providers"><span>＋</span><b>{ar?"حجز موعد":"Book appointment"}</b><small>{ar?"ابحث عن مقدم رعاية موثّق":"Find a verified provider"}</small></a><a href="/appointments"><span>◎</span><b>{ar?"إدارة المواعيد":"Manage appointments"}</b><small>{ar?"عرض أو إعادة جدولة":"View or reschedule"}</small></a><a href="/wallet"><span>▤</span><b>{ar?"فتح المحفظة":"Open wallet"}</b><small>{ar?"عرض المعلومات المسموح بها":"View permitted information"}</small></a></div></section><section className="family-upcoming"><div><h3>{ar?"الموعد القادم":"Upcoming appointment"}</h3><a href="/appointments">{ar?"عرض الكل":"View all"} →</a></div>{selected.next?<article><time><b>{selected.next.split(" · ")[0]}</b><span>{selected.next.split(" · ")[1]}</span></time><div><p>{ar?"طب الأسرة":"Family Medicine"}</p><b>{ar?"د. ليلى الكواري":"Dr. Laila Al-Kuwari"}</b><small>{ar?"مركز النور الطبي · في العيادة":"Al Noor Medical Center · In person"}</small></div><i>{ar?"مؤكد":"Confirmed"}</i></article>:<p className="empty-family">{ar?"لا توجد مواعيد قادمة.":"No upcoming appointments."}</p>}</section></div>}
          {tab==="access"&&<div className="family-access"><div className="access-summary"><span>♙</span><div><b>{ar?selected.accessAr:selected.access}</b><p>{selected.id===1?(ar?"أنت صاحب هذا الملف.":"You own this profile."):selected.id===2?(ar?"تدير هذا الملف بصفتك ولي أمر موثّقاً.":"You manage this profile as a verified guardian."):selected.id===3?(ar?"تتغير بعض الصلاحيات حسب العمر والموافقة.":"Some permissions change with age and consent."):(ar?"منحت فاطمة وصولاً محدوداً وقابلاً للإلغاء.":"Fatima granted limited, revocable access.")}</p></div></div><h3>{ar?"ما الذي يمكنك إدارته":"What you can manage"}</h3>{Object.entries(permissions).map(([key,value])=><div className="family-permission" key={key}><span>{key==="appointments"?"◎":key==="wallet"?"Q":key==="documents"?"▤":"●"}</span><div><b>{key==="appointments"?(ar?"المواعيد":"Appointments"):key==="wallet"?(ar?"رصيد المزايا":"Benefits balance"):key==="documents"?(ar?"مستندات صحية محددة":"Selected health documents"):(ar?"الإشعارات":"Notifications")}</b><small>{key==="documents"?(ar?"يتطلب موافقة صريحة ومحددة":"Requires explicit, specific consent"):(ar?"يمكن تغييره في أي وقت":"Can be changed anytime")}</small></div><button className={value?"toggle on":"toggle"} disabled={selected.id===1||key==="appointments"} onClick={()=>setPermissions(v=>({...v,[key]:!v[key as keyof typeof v]}))}><span/></button></div>)}<div className="access-audit"><b>{ar?"سجل الوصول محفوظ":"Access history is recorded"}</b><p>{ar?"يُسجل من رأى ماذا ومتى ولماذا. يمكن إلغاء الوصول المشترك فوراً.":"Who viewed what, when, and why is logged. Shared access can be revoked immediately."}</p><button onClick={()=>setTab("activity")}>{ar?"عرض سجل النشاط":"View activity log"} →</button></div></div>}
          {tab==="activity"&&<div className="family-activity"><h3>{ar?"النشاط الأخير":"Recent activity"}</h3>{[["Today, 10:14 AM","Appointment viewed","Mariam · iPhone"],["31 Jul, 6:20 PM","Benefits balance checked","Mariam · Safari"],["29 Jul, 2:05 PM","Access permission updated","Consent reference CNS-••48"]].map((a,i)=><article key={a[0]}><span>{i===2?"♙":"✓"}</span><div><b>{a[1]}</b><small>{a[0]} · {a[2]}</small></div></article>)}<p>{ar?"هذا سجل تجريبي ببيانات اصطناعية. في المنتج الحقيقي سيكون السجل غير قابل للتعديل.":"Synthetic prototype activity. Production history would be immutable."}</p></div>}
        </section></div>
    </section>
    {adding&&<div className="family-modal-layer" onMouseDown={e=>e.target===e.currentTarget&&setAdding(false)}><section className="family-modal"><button className="drawer-close" onClick={()=>setAdding(false)}>×</button><p>{ar?"إضافة علاقة موثّقة":"ADD A VERIFIED RELATIONSHIP"}</p><h2>{ar?"إضافة فرد من العائلة":"Add a family member"}</h2><span>{ar?"لن يؤدي هذا تلقائياً إلى مشاركة السجلات الصحية.":"This does not automatically share health records."}</span><div className="relationship-options">{[["♡",ar?"طفل أو معال":"Child or dependant",ar?"يتطلب إثبات الوصاية":"Guardian evidence required"],["◇",ar?"شخص بالغ":"Adult family member",ar?"يتطلب موافقته الصريحة":"Requires their explicit consent"],["◎",ar?"مقدم رعاية":"Caregiver",ar?"صلاحيات محدودة زمنياً وغرضاً":"Time- and purpose-limited access"]].map((r,i)=><button key={r[1]} className={i===0?"active":""}><span>{r[0]}</span><div><b>{r[1]}</b><small>{r[2]}</small></div><i>{i===0?"✓":""}</i></button>)}</div><label>{ar?"الاسم الكامل التجريبي":"Synthetic full name"}<input defaultValue={ar?"سلمان أحمد":"Salman Ahmed"}/></label><label>{ar?"تاريخ الميلاد":"Date of birth"}<input defaultValue="18 June 2021"/></label><div className="relationship-warning"><span>♙</span><p>{ar?"سيتم التحقق من العلاقة قبل تفعيل الوصول. سيحدد العمر والموافقة نطاق ما يمكنك إدارته.":"The relationship is verified before access begins. Age and consent determine what you can manage."}</p></div><button className="family-primary" onClick={()=>{setAdding(false);setNotice(ar?"تم إنشاء طلب التحقق التجريبي":"Prototype verification request created")}}>{ar?"بدء التحقق من العلاقة":"Start relationship verification"}</button></section></div>}
    {notice&&<div className="family-toast"><span>✓</span>{notice}<button onClick={()=>setNotice("")}>×</button></div>}
  </main>
}
