"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "../../encounter-follow-up/encounter-continuity.module.css";

type Rehearsal={id:string;rehearsalVersion:string;scenarioCount:number;passedScenarios:number;failedScenarios:number;amendmentsCreated:number;notesOverwritten:number;tasksCreated:number;externalMessagesSent:number;result:string;executedAt:string};
type Data={role:string;metrics:{amendments:number;pendingAuthorizations:number;followUpRecommendations:number;patientAcknowledgements:number};rehearsals:Rehearsal[];contentVisibility:string};
async function api(init?:RequestInit){const response=await fetch("/api/admin/encounter-continuity",{cache:"no-store",credentials:"same-origin",...init});if(response.status===401){location.assign("/sign-in?redirect_url=/admin/encounter-continuity");throw Error("Authentication required")}const payload=await response.json().catch(()=>({}));if(!response.ok||payload.data===undefined)throw Error(payload.message||payload.error||"Encounter governance is unavailable");return payload.data as Data}
function date(value:string){return new Intl.DateTimeFormat("en-QA",{timeZone:"Asia/Qatar",dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
export default function AdminEncounterContinuityPage(){const[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const load=useCallback(async()=>setData(await api()),[]);useEffect(()=>{queueMicrotask(()=>void load().catch(e=>setError(e.message)))},[load]);async function rehearse(){setBusy(true);setError("");try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"run_rehearsal"})});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to run rehearsal")}finally{setBusy(false)}}
return <main className={styles.providerLayout} id="main-content"><aside className={styles.side}><a href="/admin"><img src="/brand/qivaya-logo-reversed.png" alt="Qivaya"/></a><nav><a href="/admin">Admin overview</a><a className={styles.active} href="/admin/encounter-continuity">Encounter governance</a><a href="/admin/audit">Audit</a><a href="/admin/operations">System health</a></nav></aside><section className={styles.content}><header className={styles.heading}><div><p className={styles.eyebrow}>AGGREGATE ENCOUNTER GOVERNANCE</p><h1>Protect the original while governing every linked update.</h1><p className={styles.muted}>{data?.contentVisibility||"Loading aggregate controls…"}</p></div><span className={styles.pill}>{data?.role?.replaceAll("_"," ")||"Authorizing role"}</span></header>{error&&<p className={`${styles.notice} ${styles.error}`}>{error}</p>}<section className={styles.metrics}>{data&&Object.entries(data.metrics).map(([key,value])=><article className={styles.metric} key={key}><b>{value}</b><span className={styles.muted}>{key.replaceAll(/([A-Z])/g," $1").toLowerCase()}</span></article>)}</section><section className={styles.grid}><article className={styles.section}><p className={styles.eyebrow}>CONTROL BOUNDARY</p><h2>Append-only by design</h2><p className={styles.muted}>Finalized notes remain immutable. Direct amendments require provider attestation. Correction and void entries require a structured request, an optimistic version check, and a second explicit authorization action.</p><p className={styles.notice}>Governance exposes counts and lifecycle states only. Patient identity, clinical text, instructions, and free-text reasons stay outside this surface.</p></article><article className={styles.section}><p className={styles.eyebrow}>SYNTHETIC REHEARSAL</p><h2>Twelve safety scenarios, zero effects</h2><p className={styles.muted}>Covers finalized-only eligibility, provider ownership, append-only history, structured reasons, attestation, authorization, concurrency, patient read boundary, acknowledgement scope, audit minimization, notification minimization, and aggregate governance.</p><button className={styles.button} disabled={busy||data?.role!=="platform_admin"} onClick={()=>void rehearse()}>{busy?"Running complete rehearsal…":"Run complete rehearsal"}</button></article></section><section className={styles.section}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>REHEARSAL LEDGER</p><h2>Non-destructive evidence</h2></div></div><div className={styles.ledger}>{data?.rehearsals.map(item=><div className={styles.ledgerRow} key={item.id}><b>{item.result.toUpperCase()}</b><span>{item.passedScenarios}/{item.scenarioCount} scenarios</span><span>0 amendments · 0 overwritten notes · 0 tasks · 0 external</span><small>{date(item.executedAt)}</small></div>)}{data&&!data.rehearsals.length&&<p className={styles.muted}>No rehearsal has been run yet.</p>}</div></section></section></main>}
