"use client";

import { useCallback, useEffect, useState } from "react";
type SharedDocument = { shareId: string; documentId: string; patientName: string; category: string; verificationStatus: string; contentType: string; sizeBytes: number; pageCount: number | null; capturedAt: string | null; purpose: string; expiresAt: string };
function label(value: string) { return value.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()); }
function date(value: string | null) { return value ? new Intl.DateTimeFormat("en-QA", { timeZone: "Asia/Qatar", dateStyle: "medium" }).format(new Date(value)) : "Not recorded"; }

export default function ProviderDocumentsPage() {
  const [documents, setDocuments] = useState<SharedDocument[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(""); try { const response = await fetch("/api/provider/documents", { cache: "no-store", signal }); if (response.status === 401) { window.location.assign("/signin-with-chatgpt?return_to=/provider/documents"); return; } const payload = await response.json().catch(() => ({})) as { data?: { documents: SharedDocument[] }; error?: string }; if (!response.ok || !payload.data) throw new Error(response.status === 403 ? "A verified provider profile is required." : "Shared documents are temporarily unavailable."); setDocuments(payload.data.documents); } catch (caught) { if (caught instanceof DOMException && caught.name === "AbortError") return; setError(caught instanceof Error ? caught.message : "Shared documents are temporarily unavailable."); } finally { if (!signal?.aborted) setLoading(false); } }, []);
  useEffect(() => { const controller = new AbortController(); queueMicrotask(() => void load(controller.signal)); return () => controller.abort(); }, [load]);
  return <main className="provider-shell provider-live-shell" id="main-content"><aside className="provider-sidebar"><a href="/provider" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>Provider console</span></a><div className="facility-chip"><span>RC</span><div><b>Provider workspace</b><small>Verified access required</small></div></div><nav className="provider-nav"><a className="provider-nav-link" href="/provider"><span>◫</span>Appointments</a><a className="provider-nav-link" href="/provider/patients"><span>♙</span>Patients</a><a className="provider-nav-link active" href="/provider/documents"><span>▤</span>Shared documents</a><a className="provider-nav-link" href="/provider/services"><span>◇</span>Services</a><a className="provider-nav-link" href="/provider/settings"><span>⚙</span>Settings</a></nav><div className="sidebar-bottom"><a href="/">← Patient experience</a><p>Role-scoped provider operations</p></div></aside><section className="provider-main"><header className="provider-topbar"><div className="provider-context"><span>▤</span><div><b>Shared medical documents</b><small>Consent-scoped metadata</small></div></div><div className="provider-actions"><a href="/notifications">Notifications</a><span className="provider-avatar">PR</span></div></header><div className="provider-workspace provider-documents-workspace"><div className="provider-welcome"><div><p>Patient-authorized access</p><h1>Shared documents</h1><span>See only active, time-limited document metadata granted by appointment-linked patients.</span></div><button onClick={() => void load()}>Refresh</button></div><div className="provider-document-boundary"><span>i</span><div><b>Document content is not available.</b><p>This foundation exposes metadata only. Protected file delivery remains disabled until storage and scanning controls are approved.</p></div></div>{error && <div className="provider-live-error"><span>{error}</span><button onClick={() => void load()}>Try again</button></div>}{loading ? <div className="provider-live-state"><span>◌</span><h2>Loading active access grants</h2><p>Checking expiry, consent, and provider scope.</p></div> : documents.length === 0 ? <div className="provider-live-card provider-live-state"><span>▤</span><h2>No documents shared with you</h2><p>Patient-approved document metadata will appear here while its access grant is active.</p></div> : <section className="provider-shared-documents">{documents.map((document) => <article key={document.shareId}><span className="document-icon">▤</span><div><p>{label(document.category)}</p><h2>{document.patientName}</h2><span>{document.pageCount ? `${document.pageCount} pages · ` : ""}{label(document.verificationStatus)} · Captured {date(document.capturedAt)}</span><small>{label(document.purpose)} · Access expires {date(document.expiresAt)}</small></div><span className="documents-status ready">Metadata only</span></article>)}</section>}</div></section></main>;
}
