"use client";

import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./emergency-profile.module.css";

type Allergy={substance:string;reaction:string;severity:"unknown"|"mild"|"moderate"|"severe"};
type Condition={name:string;note:string};
type Medicine={name:string;dose:string;schedule:string};
type Contact={name:string;relationship:string;phone:string};
type Profile={id:string;bloodGroup:string|null;allergies:Allergy[];conditions:Condition[];medicines:Medicine[];emergencyContact:Contact|null;visibility:"private"|"emergency_summary";consentStatus:string;version:number;updatedAt:string;source:{label:string;verification:string}};
type Workspace={profile:Profile|null;guidance:string;emergency:{number:string;instruction:string}};

const blankContact:Contact={name:"",relationship:"",phone:""};

export default function EmergencyProfilePage(){
  const[lang,setLang]=useReyatiLocale(),ar=lang==="ar";
  const[data,setData]=useState<Workspace|null>(null),[bloodGroup,setBloodGroup]=useState(""),[allergies,setAllergies]=useState<Allergy[]>([]),[conditions,setConditions]=useState<Condition[]>([]),[medicines,setMedicines]=useState<Medicine[]>([]),[contact,setContact]=useState<Contact>(blankContact),[visibility,setVisibility]=useState<"private"|"emergency_summary">("private"),[consent,setConsent]=useState(false),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const populate=useCallback((workspace:Workspace)=>{const profile=workspace.profile;setData(workspace);setBloodGroup(profile?.bloodGroup??"");setAllergies(profile?.allergies??[]);setConditions(profile?.conditions.map(item=>({...item,note:item.note??""}))??[]);setMedicines(profile?.medicines.map(item=>({...item,dose:item.dose??"",schedule:item.schedule??""}))??[]);setContact(profile?.emergencyContact??blankContact);setVisibility(profile?.visibility??"private");setConsent(profile?.consentStatus==="granted");setVersion(profile?.version??0)},[]);
  const load=useCallback(async(signal?:AbortSignal)=>{try{setError("");const response=await fetch("/api/emergency-profile",{cache:"no-store",signal});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error);populate(payload.data)}catch(reason){if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(ar?"تعذر تحميل ملف الطوارئ.":"Your emergency profile could not be loaded.")}},[ar,populate]);
  useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)void load(controller.signal)});return()=>controller.abort()},[load]);
  async function save(){setBusy(true);setError("");setMessage("");try{const emergencyContact=contact.name||contact.relationship||contact.phone?contact:null;const response=await fetch("/api/emergency-profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_profile",version,bloodGroup:bloodGroup||null,allergies,conditions,medicines,emergencyContact,visibility,consentGranted:consent})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.error);await load();setMessage(ar?"تم حفظ ملف الطوارئ بأمان.":"Your emergency profile has been saved securely.")}catch(reason){setError(reason instanceof Error?reason.message:(ar?"تعذر حفظ الملف.":"The profile could not be saved."))}finally{setBusy(false)}}
  const updateAllergy=(index:number,field:keyof Allergy,value:string)=>setAllergies(current=>current.map((item,i)=>i===index?{...item,[field]:value}:item));
  const updateCondition=(index:number,field:keyof Condition,value:string)=>setConditions(current=>current.map((item,i)=>i===index?{...item,[field]:value}:item));
  const updateMedicine=(index:number,field:keyof Medicine,value:string)=>setMedicines(current=>current.map((item,i)=>i===index?{...item,[field]:value}:item));
  const lastUpdated=data?.profile?.updatedAt?new Date(data.profile.updatedAt).toLocaleDateString(lang==="ar"?"ar-QA":"en-QA"):null;
  return <main className={styles.shell} dir={ar?"rtl":"ltr"}>
    <header className={styles.top}><a href="/"><img src="/brand/reyati-logo-primary.svg" alt="Reyati"/></a><nav><a href="/documents">{ar?"السجلات الصحية":"Health records"}</a><a href="/family">{ar?"وصول العائلة":"Family access"}</a><button type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></nav></header>
    <section className={styles.hero}><span className={styles.eyebrow}>{ar?"معلوماتك • تحت سيطرتك":"Your information • your control"}</span><h1>{ar?"ملف طوارئ واضح عندما تكون كل ثانية مهمة":"A clear emergency profile when every second matters"}</h1><p>{ar?"احتفظ بملخص منظم للمعلومات الحرجة التي تدخلها بنفسك. هذه المعلومات غير موثقة سريرياً ولا تُشارك تلقائياً.":"Keep a structured summary of critical information you enter yourself. It is not clinically verified and is never shared automatically."}</p></section>
    <div className={styles.content}>
      <section className={styles.emergency} aria-label={ar?"تعليمات الطوارئ":"Emergency instruction"}><div><strong>{ar?"هل هذه حالة طارئة الآن؟":"Is this an emergency right now?"}</strong><p>{ar?"اتصل بخدمات الطوارئ في قطر فوراً. ريّاتي لا يرسل سيارة إسعاف ولا يتتبع الاستجابة.":"Call Qatar emergency services immediately. Reyati does not dispatch an ambulance or track the response."}</p></div><span className={styles.number}>999</span></section>
      <section className={styles.source}><div><strong>{ar?"المصدر: أدخلته أنت":"Source: entered by you"}</strong><small>{ar?"غير موثق — لم يراجعه طبيب. يجب على مختصي الرعاية التحقق منه بشكل مستقل.":"Unverified — not reviewed by a clinician. Care professionals must verify it independently."}</small></div><span className={styles.badge}>{ar?"غير موثق":"UNVERIFIED"}</span></section>
      {message&&<p className={styles.status} role="status">{message}</p>}{error&&<p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
      <div className={styles.layout}><div>
        <section className={styles.panel}><div className={styles.panelHead}><div><h2>{ar?"المعلومات الصحية الحرجة":"Critical health information"}</h2><p className={styles.muted}>{ar?"أضف فقط ما تعرفه. جميع الحقول اختيارية ويمكنك تحديثها في أي وقت.":"Add only what you know. Every field is optional and can be updated at any time."}</p></div>{lastUpdated&&<small className={styles.muted}>{ar?"آخر تحديث":"Updated"}: {lastUpdated}</small>}</div>
          <label className={`${styles.label} ${styles.blood}`}>{ar?"فصيلة الدم (اختياري)":"Blood group (optional)"}<select className={styles.select} value={bloodGroup} onChange={event=>setBloodGroup(event.target.value)}><option value="">{ar?"غير محدد":"Not specified"}</option>{["A+","A-","B+","B-","AB+","AB-","O+","O-"].map(group=><option key={group}>{group}</option>)}</select></label>
          <div className={styles.panelHead}><div><h2>{ar?"الحساسيات":"Allergies"}</h2><p className={styles.muted}>{ar?"حتى 12 حساسية":"Up to 12 allergies"}</p></div><button className={styles.add} type="button" disabled={allergies.length>=12} onClick={()=>setAllergies(current=>[...current,{substance:"",reaction:"",severity:"unknown"}])}>＋ {ar?"إضافة":"Add"}</button></div>
          <div className={styles.list}>{allergies.map((item,index)=><div className={styles.row} key={`allergy-${index}`}><label className={styles.label}>{ar?"المادة":"Substance"}<input className={styles.input} maxLength={80} value={item.substance} onChange={event=>updateAllergy(index,"substance",event.target.value)}/></label><label className={styles.label}>{ar?"رد الفعل":"Reaction"}<input className={styles.input} maxLength={120} value={item.reaction} onChange={event=>updateAllergy(index,"reaction",event.target.value)}/></label><label className={styles.label}>{ar?"الشدة":"Severity"}<select className={styles.select} value={item.severity} onChange={event=>updateAllergy(index,"severity",event.target.value)}><option value="unknown">{ar?"غير معروف":"Unknown"}</option><option value="mild">{ar?"خفيف":"Mild"}</option><option value="moderate">{ar?"متوسط":"Moderate"}</option><option value="severe">{ar?"شديد":"Severe"}</option></select></label><button className={styles.remove} type="button" aria-label={ar?"إزالة الحساسية":"Remove allergy"} onClick={()=>setAllergies(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div>
          <div className={styles.divider}/><div className={styles.panelHead}><div><h2>{ar?"الحالات الصحية":"Health conditions"}</h2><p className={styles.muted}>{ar?"أسماء مختصرة وملاحظات اختيارية":"Short names with optional notes"}</p></div><button className={styles.add} type="button" disabled={conditions.length>=12} onClick={()=>setConditions(current=>[...current,{name:"",note:""}])}>＋ {ar?"إضافة":"Add"}</button></div>
          <div className={styles.list}>{conditions.map((item,index)=><div className={`${styles.row} ${styles.two}`} key={`condition-${index}`}><label className={styles.label}>{ar?"الحالة":"Condition"}<input className={styles.input} maxLength={100} value={item.name} onChange={event=>updateCondition(index,"name",event.target.value)}/></label><label className={styles.label}>{ar?"ملاحظة اختيارية":"Optional note"}<input className={styles.input} maxLength={160} value={item.note} onChange={event=>updateCondition(index,"note",event.target.value)}/></label><button className={styles.remove} type="button" aria-label={ar?"إزالة الحالة":"Remove condition"} onClick={()=>setConditions(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div>
          <div className={styles.divider}/><div className={styles.panelHead}><div><h2>{ar?"الأدوية الحالية":"Current medicines"}</h2><p className={styles.muted}>{ar?"الاسم والجرعة والجدول كما تعرفها":"Name, dose and schedule as you know them"}</p></div><button className={styles.add} type="button" disabled={medicines.length>=12} onClick={()=>setMedicines(current=>[...current,{name:"",dose:"",schedule:""}])}>＋ {ar?"إضافة":"Add"}</button></div>
          <div className={styles.list}>{medicines.map((item,index)=><div className={`${styles.row} ${styles.three}`} key={`medicine-${index}`}><label className={styles.label}>{ar?"الدواء":"Medicine"}<input className={styles.input} maxLength={100} value={item.name} onChange={event=>updateMedicine(index,"name",event.target.value)}/></label><label className={styles.label}>{ar?"الجرعة":"Dose"}<input className={styles.input} maxLength={60} value={item.dose} onChange={event=>updateMedicine(index,"dose",event.target.value)}/></label><label className={styles.label}>{ar?"الجدول":"Schedule"}<input className={styles.input} maxLength={100} value={item.schedule} onChange={event=>updateMedicine(index,"schedule",event.target.value)}/></label><button className={styles.remove} type="button" aria-label={ar?"إزالة الدواء":"Remove medicine"} onClick={()=>setMedicines(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div>
        </section>
        <section className={styles.panel}><div className={styles.panelHead}><div><h2>{ar?"جهة اتصال للطوارئ":"Emergency contact"}</h2><p className={styles.muted}>{ar?"اختياري. لا تتصل ريّاتي بهذا الشخص تلقائياً.":"Optional. Reyati never contacts this person automatically."}</p></div></div><div className={styles.contact}><label className={styles.label}>{ar?"الاسم":"Name"}<input className={styles.input} maxLength={100} value={contact.name} onChange={event=>setContact(current=>({...current,name:event.target.value}))}/></label><label className={styles.label}>{ar?"صلة القرابة":"Relationship"}<input className={styles.input} maxLength={60} value={contact.relationship} onChange={event=>setContact(current=>({...current,relationship:event.target.value}))}/></label><label className={styles.label}>{ar?"رقم قطر":"Qatar number"}<input className={styles.input} inputMode="tel" placeholder="+974 5XXX XXXX" maxLength={24} value={contact.phone} onChange={event=>setContact(current=>({...current,phone:event.target.value}))}/></label></div></section>
      </div><aside>
        <section className={styles.panel}><h2>{ar?"الخصوصية والظهور":"Privacy and visibility"}</h2><p className={styles.muted}>{ar?"لا يملك مقدمو الرعاية أو الشركاء وصولاً إلى هذا الملف.":"Providers and partners do not have access to this profile."}</p><div className={styles.visibility}><label className={styles.choice}><input type="radio" name="visibility" checked={visibility==="private"} onChange={()=>{setVisibility("private");setConsent(false)}}/><span><strong>{ar?"خاص بحسابي":"Private to my account"}</strong><small>{ar?"أراه أنا فقط داخل ريّاتي.":"Only I can see it inside Reyati."}</small></span></label><label className={styles.choice}><input type="radio" name="visibility" checked={visibility==="emergency_summary"} onChange={()=>setVisibility("emergency_summary")}/><span><strong>{ar?"جاهز للعرض بواسطتي":"Ready for me to show"}</strong><small>{ar?"ينظم الملخص لكي تعرضه بنفسك. لا تتم مشاركته أو إرساله.":"Formats the summary for you to show yourself. It is not shared or sent."}</small></span></label></div>{visibility==="emergency_summary"&&<label className={styles.consent}><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>{ar?"أوافق صراحةً على تجهيز هذا الملخص للعرض بواسطتي، وأفهم أنه غير موثق ولا يُستخدم سريرياً بشكل تلقائي.":"I explicitly consent to preparing this summary for me to show, and understand it is unverified and never used automatically for clinical care."}</span></label>}<div className={styles.actions}><button className={`${styles.button} ${styles.primary}`} type="button" disabled={busy||(visibility==="emergency_summary"&&!consent)} onClick={()=>void save()}>{busy?(ar?"جارٍ الحفظ…":"Saving…"):(ar?"حفظ الملف":"Save profile")}</button></div></section>
        <section className={styles.panel}><h2>{ar?"حدود واضحة":"Clear boundaries"}</h2><div className={styles.sideList}><div className={styles.sideItem}><span className={styles.icon}>✓</span><div><strong>{ar?"أنت المصدر":"You are the source"}</strong><p>{ar?"كل معلومة تحمل وسم غير موثق.":"Every item remains labelled unverified."}</p></div></div><div className={styles.sideItem}><span className={styles.icon}>0</span><div><strong>{ar?"لا مشاركة تلقائية":"No automatic sharing"}</strong><p>{ar?"لا إرسال خارجي ولا وصول لمقدم الرعاية.":"No external sending and no provider access."}</p></div></div><div className={styles.sideItem}><span className={styles.icon}>999</span><div><strong>{ar?"ليس نظام استجابة":"Not a response system"}</strong><p>{ar?"لا زر ذعر، ولا إسعاف، ولا سعة طوارئ مباشرة.":"No panic button, ambulance dispatch, or live ER capacity."}</p></div></div></div></section>
      </aside></div>
    </div>
  </main>
}
