/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.uat.jsonc --include-runtime=false` (hash: c0c1cf7bbca3b4ab532dd30475493127)
interface __BaseEnv_Env {
	DB: D1Database;
	PLATFORM_BOOTSTRAP_EMAIL: "admin.test@reyati.local";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PLATFORM_BOOTSTRAP_EMAIL">> {}
}
