"use client";

import { FormEvent, useEffect, useState } from "react";

type RoleRow = { userId: string; role: string; status: string; name: string; email: string; updatedAt: string };
type Invitation = { id: string; email: string; role: string; status: string; expiresAt: string };
type AccessData = { roles: RoleRow[]; invitations: Invitation[] };

async function api(init?: RequestInit) {
  const response = await fetch("/api/admin/platform-access", init); const payload = await response.json() as { data?: unknown; message?: string; error?: string };
  if (response.status === 401) { const returnTo = `${window.location.pathname}${window.location.search}`; window.location.assign(`/signin-with-chatgpt?return_to=${encodeURIComponent(returnTo)}`); throw new Error("Authentication required"); }
  if (!response.ok) { const error = new Error(payload.message || payload.error || "Request failed"); (error as Error & { status?: number }).status = response.status; throw error; }
  return payload.data;
}

function label(value: string) { return value.replaceAll("_", " "); }

export default function PlatformAccessPage() {
  const [data, setData] = useState<AccessData | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [forbidden, setForbidden] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [inviteLink, setInviteLink] = useState(""); const [acceptedRole, setAcceptedRole] = useState("");
  async function load() { try { setError(""); const next = await api() as AccessData; setData(next); setForbidden(false); } catch (caught) { if ((caught as Error & { status?: number }).status === 403) setForbidden(true); else setError(caught instanceof Error ? caught.message : "Platform access unavailable"); } finally { setLoading(false); } }
  useEffect(() => {
    let active = true; const token = new URLSearchParams(window.location.search).get("invitation");
    const operation = token
      ? api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "accept", token }) }).then((result) => { if (active) { setAcceptedRole((result as { role: string }).role); window.history.replaceState({}, "", "/admin/access"); } })
      : api().then((result) => { if (active) setData(result as AccessData); });
    operation.catch((caught) => { if (!active) return; if ((caught as Error & { status?: number }).status === 403) setForbidden(true); else setError(caught instanceof Error ? caught.message : "Platform access unavailable"); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);

  async function invite(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget);
    try { const created = await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "invite", email: form.get("email"), role: form.get("role") }) }) as { acceptPath: string }; setInviteLink(`${window.location.origin}${created.acceptPath}`); setNotice("Secure platform invitation created"); event.currentTarget.reset(); await load(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Invitation could not be created"); } finally { setSaving(false); }
  }
  async function update(row: RoleRow) { setSaving(true); setError(""); try { await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: row.status === "active" ? "suspend_role" : "reactivate_role", userId: row.userId, role: row.role }) }); setNotice(row.status === "active" ? "Platform role suspended" : "Platform role reactivated"); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Role could not be updated"); } finally { setSaving(false); } }
  async function revoke(invitationId: string) { setSaving(true); setError(""); try { await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "revoke_invitation", invitationId }) }); setNotice("Invitation revoked"); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Invitation could not be revoked"); } finally { setSaving(false); } }

  return <main className="accessops-shell" id="main-content"><aside className="accessops-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>Platform operations</span></a><nav><a href="/admin">Overview</a><a href="/admin/organizations">Organizations</a><a className="active" href="/admin/access">Platform access</a><a href="/admin/verification">Verification</a><a href="/admin/audit">Audit</a></nav><div><b>Least-privilege access</b><p>Invitations are email-bound, expire after seven days, and are recorded in the audit ledger.</p></div></aside><section className="accessops-main"><header><div><small>IDENTITY &amp; ACCESS</small><b>Protected operations</b></div><a href="/notifications">●</a></header><div className="accessops-content"><div className="accessops-heading"><div><p>PLATFORM GOVERNANCE</p><h1>Platform team access</h1><span>Invite independent reviewers and auditors, manage active roles, and protect administrator continuity.</span></div>{data && <button onClick={() => void load()}>Refresh</button>}</div>
    {loading && <div className="accessops-state"><span>◇</span><h2>Checking protected access…</h2></div>}{error && <div className="accessops-alert">{error}<button onClick={() => setError("")}>×</button></div>}{acceptedRole && <section className="accessops-accepted"><span>✓</span><h2>Platform invitation accepted</h2><p>Your <b>{label(acceptedRole)}</b> role is active. Access remains limited to the permissions assigned to that role.</p><a href={acceptedRole === "security_auditor" ? "/admin/audit" : acceptedRole === "verification_reviewer" ? "/admin/verification" : "/admin/organizations"}>Open workspace</a></section>}{!loading && forbidden && !acceptedRole && <div className="accessops-state"><span>♙</span><h2>Platform administrator access required</h2><p>Only active platform administrators can invite or manage platform roles.</p></div>}
    {data && !acceptedRole && <><section className="accessops-grid"><form onSubmit={invite}><p>SECURE INVITATION</p><h2>Add a platform team member</h2><label>Email address<input name="email" type="email" required maxLength={254}/></label><label>Platform role<select name="role" defaultValue="verification_reviewer"><option value="verification_reviewer">Verification reviewer</option><option value="security_auditor">Security auditor</option><option value="platform_admin">Platform administrator</option></select></label><div className="accessops-note"><b>Separation of duties</b><p>Reviewer and auditor roles receive only their dedicated workspace. Administrator access should be assigned sparingly.</p></div><button disabled={saving}>{saving ? "Creating…" : "Create invitation"}</button></form><aside><span>▣</span><h2>Continuity controls</h2><ul><li>Signed-in email must exactly match the invitation</li><li>Tokens are stored only as SHA-256 hashes</li><li>Administrators cannot suspend themselves</li><li>The final active administrator cannot be disabled</li></ul></aside></section>{inviteLink && <div className="accessops-link"><div><b>Invitation link created</b><p>Shown once. Send it only to the invited email owner.</p></div><input readOnly value={inviteLink} onFocus={(event) => event.currentTarget.select()}/><button onClick={() => void navigator.clipboard.writeText(inviteLink)}>Copy</button><button onClick={() => setInviteLink("")}>Dismiss</button></div>}<section className="accessops-panel"><div className="accessops-panel-head"><div><p>ACTIVE DIRECTORY</p><h2>Assigned platform roles</h2></div><span>{data.roles.filter((role) => role.status === "active").length} active</span></div>{data.roles.length === 0 ? <div className="accessops-empty">No platform roles assigned.</div> : data.roles.map((row) => <article key={`${row.userId}:${row.role}`}><span>{row.name.split(" ").map((part) => part[0]).join("").slice(0,2)}</span><div><b>{row.name}</b><small>{row.email}</small></div><strong>{label(row.role)}</strong><i className={row.status}>{row.status}</i><button disabled={saving} onClick={() => void update(row)}>{row.status === "active" ? "Suspend" : "Reactivate"}</button></article>)}</section><section className="accessops-panel"><div className="accessops-panel-head"><div><p>PENDING CONTROL</p><h2>Platform invitations</h2></div><span>{data.invitations.filter((item) => item.status === "pending").length} pending</span></div>{data.invitations.length === 0 ? <div className="accessops-empty">No pending or revoked invitations.</div> : data.invitations.map((item) => <article key={item.id}><span>✉</span><div><b>{item.email}</b><small>Expires {new Date(item.expiresAt).toLocaleDateString()}</small></div><strong>{label(item.role)}</strong><i className={item.status}>{item.status}</i>{item.status === "pending" ? <button disabled={saving} onClick={() => void revoke(item.id)}>Revoke</button> : <span/>}</article>)}</section></>}
  </div></section>{notice && <div className="accessops-toast">✓ {notice}<button onClick={() => setNotice("")}>×</button></div>}</main>;
}
