"use client";
/* eslint-disable react-hooks/set-state-in-effect -- initial request resolves asynchronously */
import { useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./facilities.module.css";
type Facility = { id:string; organizationName:string; nameEn:string; nameAr:string; descriptionEn:string; descriptionAr:string; addressEn:string; addressAr:string; area:string|null; departments:string[]; openingHours:{day:number;open:string;close:string}[]; accessibility:string[]; parkingEn:string; parkingAr:string; contactPhone:string; contactEmail:string; services:string[]; modes:string[]; sourceLabel:string; freshness:"current"|"stale"; sourceUpdatedAt:string };
const daysEn=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"], daysAr=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
export default function FacilitiesPage(){const[lang,setLang]=useReyatiLocale(),ar=lang==="ar",[items,setItems]=useState<Facility[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
async function load(q=""){try{setLoading(true);setError("");const response=await fetch(`/api/facilities?q=${encodeURIComponent(q)}`,{cache:"no-store"});if(response.status===401){window.location.assign("/signin-with-chatgpt?return_to=/facilities");return}const payload=await response.json() as {data?:{facilities:Facility[]};message?:string};if(!response.ok||!payload.data)throw new Error(payload.message||"Directory unavailable");setItems(payload.data.facilities)}catch(e){setError(e instanceof Error?e.message:"Directory unavailable")}finally{setLoading(false)}}
useEffect(()=>{void load()},[]);return <main className={styles.shell} dir={ar?"rtl":"ltr"}><header className={styles.header}><a href="/"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav aria-label={ar?"التنقل الرئيسي":"Main navigation"}><a href="/providers">{ar?"الأطباء":"Doctors"}</a><a className={styles.active} href="/facilities" aria-current="page">{ar?"المنشآت":"Facilities"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a></nav><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></header>
<section className={styles.hero}><div><span>{ar?"دليل معلومات موثقة يدوياً":"HUMAN-REVIEWED FACTUAL DIRECTORY"}</span><h1>{ar?"ابحث عن منشأة رعاية":"Find a care facility"}</h1><p>{ar?"اطّلع على المواقع والخدمات وساعات العمل ومعلومات الوصول المنشورة. لا نعرض ترتيباً مدفوعاً أو تقييماً للجودة السريرية.":"Explore published locations, services, opening hours and access information. No sponsored placement or clinical-quality ranking."}</p><form onSubmit={(e)=>{e.preventDefault();void load(query)}}><label className={styles.srOnly} htmlFor="facility-search">{ar?"ابحث عن منشأة أو خدمة":"Search facility or service"}</label><input id="facility-search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={80} placeholder={ar?"اسم المنشأة أو المنطقة أو الخدمة":"Facility, area, department or service"}/><button>{ar?"بحث":"Search"}</button></form></div></section>
<section className={styles.content}>{error&&<div className={styles.error} role="alert"><span>{error}</span><button onClick={()=>void load(query)}>{ar?"إعادة المحاولة":"Try again"}</button></div>}{loading?<div className={styles.loading} aria-live="polite">{ar?"جارٍ تحميل الدليل…":"Loading the directory…"}</div>:!items.length?<div className={styles.empty}><b>{ar?"لا توجد منشآت منشورة مطابقة":"No matching published facilities"}</b><p>{ar?"جرّب عبارة بحث أخرى. لا نعرض المسودات أو الملفات غير النشطة.":"Try another search. Draft, inactive, and unreviewed profiles are never shown."}</p></div>:<div className={styles.grid}>{items.map(item=><article className={styles.card} key={item.id}><div className={styles.cardTop}><div><small>{item.organizationName}{item.area?` · ${item.area}`:""}</small><h2>{ar?item.nameAr:item.nameEn}</h2><p>{ar?item.descriptionAr:item.descriptionEn}</p></div><span className={item.freshness==="current"?styles.current:styles.stale}>{item.freshness==="current"?(ar?"محدّث":"Current"):(ar?"يحتاج تأكيداً":"Needs reconfirmation")}</span></div><address>{ar?item.addressAr:item.addressEn}</address><div className={styles.tags}>{item.services.map(v=><span key={v}>{v}</span>)}{item.modes.map(v=><span key={v}>{v.replaceAll("_"," ")}</span>)}</div><div className={styles.details}><section><b>{ar?"الأقسام":"Departments"}</b><p>{item.departments.length?item.departments.join(" · "):(ar?"لم تُنشر أقسام":"No departments published")}</p></section><section><b>{ar?"ساعات العمل":"Opening hours"}</b>{item.openingHours.length?<ul>{item.openingHours.map(v=><li key={v.day}>{(ar?daysAr:daysEn)[v.day]}: {v.open}–{v.close}</li>)}</ul>:<p>{ar?"اتصل بالمنشأة لتأكيد الساعات":"Contact the facility to confirm hours"}</p>}</section><section><b>{ar?"الوصول ومواقف السيارات":"Access & parking"}</b><p>{item.accessibility.length?item.accessibility.join(" · "):(ar?"لم تُنشر تفاصيل الوصول":"No access details published")}</p><p>{ar?item.parkingAr:item.parkingEn}</p></section><section><b>{ar?"الاتصال":"Contact"}</b><a href={`tel:${item.contactPhone}`}>{item.contactPhone}</a><a href={`mailto:${item.contactEmail}`}>{item.contactEmail}</a></section></div><footer><span>{ar?"المصدر: مقدم من المنشأة وراجعته المنصة":"Source: facility supplied, platform reviewed"}</span><time>{ar?"آخر تحديث للمصدر":"Source updated"}: {new Date(item.sourceUpdatedAt).toLocaleDateString(ar?"ar-QA":"en-QA")}</time></footer>{item.freshness==="stale"&&<div className={styles.staleNote}>{ar?"قد تكون بعض التفاصيل قديمة. اتصل بالمنشأة قبل السفر.":"Some details may be outdated. Contact the facility before travelling."}</div>}</article>)}</div>}</section></main>}
