"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/ReyatiLocaleProvider";
import { reyatiDate } from "@/lib/reyati-i18n";

type Visit = { appointmentId: string; providerName: string; specialty: string; scheduledStart: string; scheduledEnd: string; appointmentStatus: string; sessionId: string | null; sessionStatus: string | null; patientReadinessStatus: string | null; fallbackStatus: string | null; fallbackReasonCode: string | null; version: number | null; canEnterWaitingRoom: boolean; mediaJoinAvailable: boolean };
type Data = { appointments: Visit[]; runtime: { mediaRuntime: boolean; externalFallback: boolean; clinicalProtocol: boolean } };
async function request(init?: RequestInit) { const response = await fetch("/api/virtual-care", { cache: "no-store", credentials: "same-origin", ...init }); const payload = await response.json().catch(() => ({})) as { data?: unknown; message?: string; error?: string }; if (response.status === 401) { window.location.assign("/signin-with-chatgpt?return_to=/virtual-care"); throw new Error("Authentication required"); } if (!response.ok || payload.data === undefined) throw new Error(payload.message || payload.error || "Virtual care is unavailable"); return payload.data; }

export default function VirtualCarePage() {
  const { lang, setLang } = useReyatiLocale(), ar = lang === "ar", [data, setData] = useState<Data | null>(null), [selectedId, setSelectedId] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { const next = await request() as Data; setData(next); setSelectedId(current => current || next.appointments.find(item => ["pending", "confirmed"].includes(item.appointmentStatus))?.appointmentId || next.appointments[0]?.appointmentId || ""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load virtual care"); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const selected = useMemo(() => data?.appointments.find(item => item.appointmentId === selectedId) || null, [data, selectedId]);
  async function readiness(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); setBusy(true); setError(""); setNotice(""); try { const result = await request({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "submit_readiness", appointmentId: selected.appointmentId, cameraReady: form.get("camera") === "on", microphoneReady: form.get("microphone") === "on", connectionReady: form.get("connection") === "on", privateSpaceReady: form.get("privateSpace") === "on", emergencyBoundaryAcknowledged: form.get("emergency") === "on", locale: lang }) }) as { readinessStatus: string }; setNotice(result.readinessStatus === "ready" ? (ar ? "اكتمل فحص الجاهزية." : "Readiness check completed.") : (ar ? "تحتاج بعض عناصر الجاهزية إلى انتباهك." : "Some readiness items need attention.")); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save readiness"); } finally { setBusy(false); } }
  async function enter() { if (!selected) return; setBusy(true); setError(""); try { await request({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "enter_waiting_room", appointmentId: selected.appointmentId }) }); setNotice(ar ? "أنت الآن في غرفة الانتظار الآمنة." : "You are now in the secure waiting room."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to enter waiting room"); } finally { setBusy(false); } }
  return <main className="virtual-shell specialist-patient-shell virtual-care-experience" dir={ar ? "rtl" : "ltr"} id="main-content">
    <header className="virtual-header"><a href="/" className="brand"><img src="/brand/reyati-logo.svg" alt="Reyati" /></a><nav><a href="/appointments">{ar ? "المواعيد" : "Appointments"}</a><a className="active" href="/virtual-care">{ar ? "الرعاية الافتراضية" : "Virtual care"}</a><a href="/wallet">{ar ? "السجلات" : "Health records"}</a><a href="/support">{ar ? "الدعم" : "Support"}</a></nav><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></header>
    <section className="virtual-hero"><div><p>{ar ? "استعد قبل موعدك" : "PREPARE BEFORE YOUR VISIT"}</p><h1>{ar ? "الرعاية الافتراضية" : "Virtual care, clearly prepared"}</h1><span>{ar ? "تحقق من جهازك وخصوصيتك وحدود الطوارئ قبل دخول غرفة الانتظار." : "Check your device, privacy, and emergency boundary before entering the waiting room."}</span></div><aside><b>{ar ? "الفيديو غير مُفعّل بعد" : "Video is not activated yet"}</b><p>{ar ? "لا تنشئ هذه المساحة رابط فيديو أو جلسة وسائط حتى تتم الموافقة على مزود الاتصال والبروتوكول السريري." : "This workspace creates no video link or media session until the communications provider and clinical protocol are approved."}</p><a href="tel:999">{ar ? "للطوارئ اتصل بـ 999" : "For emergencies call 999"}</a></aside></section>
    <section className="virtual-workspace">
      {error && <div className="virtual-alert error" role="alert">{error}</div>}{notice && <div className="virtual-alert success" role="status">{notice}</div>}
      <aside className="virtual-visit-list"><div><p>{ar ? "مواعيد الفيديو" : "VIDEO APPOINTMENTS"}</p><b>{data?.appointments.length ?? 0}</b></div>{data?.appointments.map(item => <button type="button" className={item.appointmentId === selectedId ? "selected" : ""} key={item.appointmentId} onClick={() => setSelectedId(item.appointmentId)}><span>{new Date(item.scheduledStart).getDate()}</span><div><b>{item.providerName}</b><small>{reyatiDate(item.scheduledStart, lang, { dateStyle: "medium", timeStyle: "short" })}</small></div><i>{item.patientReadinessStatus || "not started"}</i></button>)}{data && !data.appointments.length && <section className="virtual-empty"><b>{ar ? "لا يوجد موعد فيديو" : "No video appointment"}</b><p>{ar ? "اختر خدمة فيديو منشورة من مقدم رعاية موثّق." : "Choose a published video service from a verified provider."}</p><a href="/providers">{ar ? "ابحث عن رعاية" : "Find care"}</a></section>}</aside>
      <section className="virtual-panel">{selected ? <><div className="virtual-panel-head"><div><p>{ar ? "موعد قادم" : "UPCOMING SESSION"}</p><h2>{selected.providerName}</h2><span>{selected.specialty} · {reyatiDate(selected.scheduledStart, lang, { dateStyle: "full", timeStyle: "short" })}</span></div><i>{selected.appointmentStatus}</i></div>
        <form onSubmit={readiness} className="virtual-checklist"><h3>{ar ? "فحص الجاهزية" : "Readiness checklist"}</h3><p>{ar ? "أكد كل عنصر بصدق. يمكنك إعادة الفحص قبل الموعد." : "Confirm each item accurately. You can repeat the check before your visit."}</p>{[["camera", "Camera can be used", "يمكن استخدام الكاميرا"], ["microphone", "Microphone can be used", "يمكن استخدام الميكروفون"], ["connection", "Connection is stable", "الاتصال مستقر"], ["privateSpace", "I have a private space", "لدي مساحة خاصة"], ["emergency", "I understand this is not emergency care", "أفهم أن هذه ليست رعاية طارئة"]].map(([name, en, arabic]) => <label key={name}><input type="checkbox" name={name} defaultChecked={selected.patientReadinessStatus === "ready"} /><span>✓</span><b>{ar ? arabic : en}</b></label>)}<button disabled={busy}>{busy ? (ar ? "جارٍ الحفظ…" : "Saving…") : (ar ? "حفظ فحص الجاهزية" : "Save readiness check")}</button></form>
        <section className="virtual-waiting"><div><span>◷</span><div><h3>{ar ? "غرفة الانتظار" : "Waiting room"}</h3><p>{selected.sessionStatus === "patient_waiting" ? (ar ? "تم تسجيل وصولك. ابقَ في هذه الصفحة وتابع تعليمات مقدم الرعاية." : "Your arrival is recorded. Stay on this page and follow your provider’s instructions.") : (ar ? "تفتح قبل الموعد بـ 30 دقيقة بعد اكتمال فحص الجاهزية." : "Opens 30 minutes before the visit after readiness is complete.")}</p></div></div><button type="button" disabled={busy || !selected.canEnterWaitingRoom || selected.sessionStatus === "patient_waiting"} onClick={() => void enter()}>{selected.sessionStatus === "patient_waiting" ? (ar ? "تم تسجيل الوصول" : "Checked in") : (ar ? "دخول غرفة الانتظار" : "Enter waiting room")}</button></section>
        {selected.fallbackStatus === "required" && <div className="virtual-fallback"><b>{ar ? "تم تسجيل مسار بديل" : "Fallback recorded"}</b><p>{ar ? "سيتابع مقدم الرعاية وفق إجراءات المنشأة. لم يتم إنشاء حجز أو رسالة خارجية تلقائياً." : "Your provider will follow the facility procedure. No replacement booking or external message was created automatically."}</p></div>}
      </> : <div className="virtual-empty large"><b>{ar ? "اختر موعداً" : "Choose an appointment"}</b></div>}</section>
    </section>
  </main>;
}
