"use client";

import { useState } from "react";

type View="overview"|"verification"|"finance"|"cases"|"moderation"|"audit";
type Item={id:string,title:string,subtitle:string,type:string,priority:string,status:string};

const queues:Record<Exclude<View,"overview">,Item[]>={
  verification:[{id:"VER-1842",title:"Dr. Hana Al-Sulaiti",subtitle:"Pediatrics · Al Rayyan Family Clinic",type:"Practitioner renewal",priority:"High",status:"Evidence review"},{id:"VER-1841",title:"Seaside Medical Center",subtitle:"Facility · Lusail",type:"New facility",priority:"Normal",status:"Source check"},{id:"VER-1839",title:"Dr. Faisal Noor",subtitle:"Cardiology · West Bay Clinic",type:"Affiliation change",priority:"Normal",status:"Clarification"}],
  finance:[{id:"RFD-8814",title:"QAR 250 refund",subtitle:"Booking RYT-••1042 · Patient M•••• A••••",type:"Cancellation refund",priority:"Normal",status:"Approved"},{id:"RFD-8808",title:"QAR 600 refund",subtitle:"Booking RYT-••0981 · Patient N•••• H••••",type:"Manual review",priority:"High",status:"Eligibility review"},{id:"REC-4201",title:"Settlement mismatch",subtitle:"Al Noor Medical Center · 31 July",type:"Reconciliation",priority:"High",status:"Action required"}],
  cases:[{id:"SUP-184",title:"Appointment support",subtitle:"Patient M•••• A•••• · Booking RYT-••1042",type:"Operational support",priority:"Normal",status:"New"},{id:"PRV-092",title:"Data export request",subtitle:"Patient N•••• M•••• · Identity assurance pending",type:"Privacy",priority:"High",status:"Action required"},{id:"SAF-031",title:"Service safety concern",subtitle:"Restricted details · Assigned safety team",type:"Clinical safety",priority:"Critical",status:"Escalated"}],
  moderation:[{id:"REV-770",title:"Review may contain health information",subtitle:"Pearl Health Clinic · Dermatology",type:"Privacy flag",priority:"High",status:"Human review"},{id:"REV-769",title:"Potential abusive language",subtitle:"Al Noor Medical Center · Reception",type:"Conduct flag",priority:"Normal",status:"Human review"},{id:"REV-766",title:"Duplicate review pattern",subtitle:"West Bay Clinic · Internal Medicine",type:"Integrity flag",priority:"Normal",status:"Evidence review"}],
  audit:[{id:"AUD-9201",title:"Sensitive support view opened",subtitle:"Case PRV-092 · Operator OPS-••18",type:"Privileged access",priority:"High",status:"Logged"},{id:"AUD-9198",title:"Verification state changed",subtitle:"VER-1842 · Reviewer VER-••04",type:"State transition",priority:"Normal",status:"Logged"},{id:"AUD-9192",title:"Refund approved",subtitle:"RFD-8814 · Finance FIN-••11",type:"Financial action",priority:"Normal",status:"Logged"}],
};

export default function Admin(){
  const [view,setView]=useState<View>("overview");const [selected,setSelected]=useState<Item|null>(null);const [lang,setLang]=useState<"en"|"ar">("en");const ar=lang==="ar";
  const [masked,setMasked]=useState(true);const [decision,setDecision]=useState<string|null>(null);
  const nav:[View,string,string][]=[["overview","Overview","نظرة عامة"],["verification","Verification","التحقق"],["finance","Finance","المالية"],["cases","Cases","الحالات"],["moderation","Moderation","الإشراف"],["audit","Audit","التدقيق"]];
  const open=(item:Item)=>{setSelected(item);setDecision(null);setMasked(true)};
  return <main className={`admin-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <aside className="admin-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar?"عمليات المنصة":"Platform operations"}</span></a><div className="admin-role"><span>OA</span><div><b>{ar?"مشغل العمليات":"Operations operator"}</b><small>{ar?"نطاق محدود · تحقق بخطوتين":"Scoped role · MFA verified"}</small></div></div><nav>{nav.map(([id,en,arabic])=><button className={view===id?"active":""} onClick={()=>setView(id)} key={id}><span>{id==="overview"?"◫":id==="verification"?"✓":id==="finance"?"Q":id==="cases"?"◇":id==="moderation"?"◉":"▤"}</span>{ar?arabic:en}{id!=="overview"&&<em>{queues[id as Exclude<View,"overview">].length}</em>}</button>)}<a className="admin-verification-link" href="/admin/verification"><span>▣</span>{ar?"مساحة التحقق":"Verification workspace"}<em>12</em></a></nav><div className="admin-sidebar-foot"><a href="/journeys">◇ {ar?"جميع المسارات":"All journeys"}</a><a href="/partner">← {ar?"بوابة الشركاء":"Partner portal"}</a><a href="/provider">← {ar?"بوابة مقدمي الرعاية":"Provider console"}</a><p>{ar?"بيانات اصطناعية · لا توجد صلاحيات حقيقية":"Synthetic data · No live privileges"}</p></div></aside>
    <section className="admin-main"><header className="admin-topbar"><div><button className="mobile-menu">☰</button><span className="environment">{ar?"بيئة النموذج":"PROTOTYPE ENVIRONMENT"}</span><b>{ar?"جميع الإجراءات محلية وتجريبية":"All actions are local and synthetic"}</b></div><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><button className="admin-alert">●<i>3</i></button><span className="provider-avatar">OA</span></div></header>
      {view==="overview"?<div className="admin-workspace"><div className="admin-heading"><div><p>{ar?"السبت، ١ أغسطس ٢٠٢٦":"Saturday, 1 August 2026"}</p><h1>{ar?"صباح الخير، فريق العمليات":"Good morning, Operations"}</h1><span>{ar?"قائمة واحدة للانتباه، مع فصل الصلاحيات حسب الدور.":"One attention queue, with permissions separated by role."}</span></div><button>⌕ {ar?"بحث تشغيلي":"Operational search"}</button></div><div className="admin-security-note"><span>▣</span><p><b>{ar?"البيانات الشخصية مخفية افتراضياً":"Personal data is masked by default"}</b>{ar?" ولا يمكن كشفها إلا داخل حالة معتمدة، لغرض محدد، ولفترة مؤقتة مسجلة.":" and may be revealed only within an approved case, for a specific purpose, with temporary logged access."}</p></div><div className="admin-metrics">{[["12",ar?"تحقق يحتاج مراجعة":"Verification reviews","verification"],["4",ar?"استردادات معلقة":"Pending refunds","finance"],["9",ar?"حالات مفتوحة":"Open cases","cases"],["3",ar?"تنبيهات عالية الأولوية":"High-priority alerts","audit"]].map(([n,label,target],i)=><button onClick={()=>setView(target as View)} key={label}><span className={`admin-metric-icon a${i}`}>{i===0?"✓":i===1?"Q":i===2?"◇":"!"}</span><div><b>{n}</b><p>{label}</p><small>{ar?"عرض القائمة":"Open queue"} →</small></div></button>)}</div><div className="admin-dashboard-grid"><section className="admin-panel"><div className="admin-panel-head"><div><h2>{ar?"تحتاج إلى انتباه":"Needs attention"}</h2><p>{ar?"مرتبة حسب المخاطر والوقت":"Ordered by risk and time"}</p></div></div>{[queues.cases[2],queues.finance[2],queues.verification[0],queues.moderation[0]].map(item=><button className="attention-row" onClick={()=>open(item)} key={item.id}><span className={`priority-symbol ${item.priority.toLowerCase()}`}>{item.priority==="Critical"?"!":item.priority==="High"?"↑":"·"}</span><div><b>{item.title}</b><p>{item.subtitle}</p></div><i>{item.id}</i><em>{item.status}</em><strong>›</strong></button>)}</section><aside className="admin-panel system-health"><div className="admin-panel-head"><div><h2>{ar?"حالة التشغيل":"Operational status"}</h2><p>{ar?"حالة اصطناعية للنموذج":"Synthetic prototype status"}</p></div></div>{[["Booking","Operational"],["Payments","Provider decision pending"],["Notifications","Operational"],["Document scanning","Simulation only"]].map(([service,status],i)=><div key={service}><span className={i===1||i===3?"warning":"ok"}/><b>{service}</b><small>{status}</small></div>)}</aside></div></div>:<QueueView view={view} items={queues[view]} ar={ar} open={open}/>} 
    </section>
    {selected&&<div className="admin-drawer-layer" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="admin-drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p>{selected.type}</p><h2>{selected.title}</h2><div className="admin-case-meta"><span className={`priority-pill ${selected.priority.toLowerCase()}`}>{selected.priority}</span><i>{selected.status}</i><b>{selected.id}</b></div><div className="admin-mask-banner"><span>▣</span><div><b>{masked?(ar?"البيانات الشخصية مخفية":"Personal data masked"):(ar?"كشف مؤقت مسجل":"Temporary logged reveal")}</b><p>{masked?(ar?"يتطلب الكشف حالة وغرضاً ومصادقة إضافية.":"Reveal requires a case, purpose, and step-up authentication."):(ar?"ينتهي هذا الوصول بعد ١٠ دقائق.":"This access expires in 10 minutes.")}</p></div><button onClick={()=>setMasked(!masked)}>{masked?(ar?"طلب الكشف":"Request reveal"):(ar?"إعادة الإخفاء":"Mask now")}</button></div>{decision?<div className="admin-decision-success"><span>✓</span><h3>{decision}</h3><p>{ar?"تم تسجيل القرار والسبب والفاعل والوقت في سجل تدقيق غير قابل للتعديل.":"The decision, reason, actor, and timestamp were added to the immutable audit history."}</p></div>:<><section className="admin-detail-section"><h3>{ar?"ملخص الحالة":"Case summary"}</h3><dl><div><dt>{ar?"المعرّف":"Reference"}</dt><dd>{selected.id}</dd></div><div><dt>{ar?"الفئة":"Category"}</dt><dd>{selected.type}</dd></div><div><dt>{ar?"الجهة":"Subject"}</dt><dd>{selected.subtitle}</dd></div><div><dt>{ar?"المالك":"Owner"}</dt><dd>{selected.type.includes("Safety")?"Safety team":"Operations queue"}</dd></div></dl></section><section className="admin-detail-section"><h3>{ar?"الأدلة والضوابط":"Evidence & controls"}</h3><div className="evidence-item"><span>▤</span><div><b>{ar?"حزمة أدلة اصطناعية":"Synthetic evidence package"}</b><small>{ar?"عرض مقيد حسب الدور · الفحص ناجح":"Role-restricted view · Scan passed"}</small></div><button>{ar?"مراجعة":"Review"}</button></div><label className="admin-reason">{ar?"سبب القرار":"Decision reason"}<textarea placeholder={ar?"اكتب سبباً واضحاً وقابلاً للتدقيق...":"Enter a clear, auditable reason..."}/></label></section><div className="admin-drawer-actions">{selected.type.includes("Safety")?<button onClick={()=>setDecision(ar?"تمت إحالة الحالة إلى فريق السلامة":"Escalated to the safety team")} className="danger-action">{ar?"تأكيد الإحالة":"Confirm escalation"}</button>:<><button className="secondary" onClick={()=>setDecision(ar?"تم طلب معلومات إضافية":"Clarification requested")}>{ar?"طلب توضيح":"Request clarification"}</button><button className="primary" onClick={()=>setDecision(ar?"تم تسجيل القرار":"Decision recorded")}>{ar?"تسجيل القرار":"Record decision"}</button></>}</div></>}</aside></div>}
  </main>;
}

function QueueView({view,items,ar,open}:{view:View,items:Item[],ar:boolean,open:(i:Item)=>void}){
  const title:Record<string,[string,string]>={verification:["Verification queue","قائمة التحقق"],finance:["Finance operations","العمليات المالية"],cases:["Cases & escalations","الحالات والتصعيدات"],moderation:["Review moderation","إشراف التقييمات"],audit:["Audit monitoring","مراقبة التدقيق"]};
  return <div className="admin-workspace"><div className="admin-heading"><div><p>{ar?"مساحة عمل محدودة الصلاحيات":"Permission-scoped workspace"}</p><h1>{ar?title[view][1]:title[view][0]}</h1><span>{ar?"الحقول المعروضة مقيدة بالدور والغرض.":"Visible fields are restricted by role and purpose."}</span></div><button>＋ {ar?"تصفية القائمة":"Filter queue"}</button></div><div className="queue-toolbar"><div><button className="active">{ar?"الكل":"All"} <span>{items.length}</span></button><button>{ar?"أولوية عالية":"High priority"}</button><button>{ar?"مُسندة إليّ":"Assigned to me"}</button></div><label>⌕<input placeholder={ar?"بحث بالمرجع أو الحقول المسموحة":"Search reference or approved fields"}/></label></div><section className="queue-table"><div className="queue-table-head"><span>{ar?"المرجع":"Reference"}</span><span>{ar?"الموضوع":"Subject"}</span><span>{ar?"النوع":"Type"}</span><span>{ar?"الأولوية":"Priority"}</span><span>{ar?"الحالة":"Status"}</span><span/></div>{items.map(item=><button onClick={()=>open(item)} key={item.id}><code>{item.id}</code><div><b>{item.title}</b><small>{item.subtitle}</small></div><span>{item.type}</span><i className={`priority-pill ${item.priority.toLowerCase()}`}>{item.priority}</i><em>{item.status}</em><strong>›</strong></button>)}</section></div>;
}
