"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
type Case={id:string;reference:string;requesterName:string;category:string;subject:string;description:string;relatedReference:string|null;privacyRequestType:string|null;priority:string;status:string;version:number;assignedToUserId:string|null;createdAt:string;updatedAt:string};
type Message={id:string;caseId:string;authorKind:string;body:string;createdAt:string};
async function api(init?:RequestInit){const response=await fetch("/api/admin/cases",init);const payload=await response.json().catch(()=>({})) as {data?:unknown;message?:string;error?:string};if(response.status===401){window.location.assign(`/signin-with-chatgpt?return_to=${encodeURIComponent("/admin/cases")}`);throw new Error("Authentication required");}if(!response.ok||payload.data===undefined){const error=new Error(payload.message||payload.error||"Case queue unavailable");(error as Error&{status?:number}).status=response.status;throw error;}return payload.data;}
function label(value:string,ar=false){const labels:Record<string,string>={all:"الكل",open:"مفتوحة",critical:"حرجة",waiting_requester:"بانتظار مقدم الطلب",resolved:"محلولة",closed:"مغلقة",in_progress:"قيد المعالجة",booking:"الحجوزات",payment:"المدفوعات",complaint:"الشكاوى",privacy:"الخصوصية",safety:"السلامة"};return ar?labels[value]||value.replaceAll("_"," "):value.replaceAll("_"," ").replace(/^./,(letter)=>letter.toUpperCase());}
export default function CasesWorkspace(){
  const [lang,setLang]=useReyatiLocale();const ar=lang==="ar";
  const [cases,setCases]=useState<Case[]>([]);const [messages,setMessages]=useState<Message[]>([]);const [selected,setSelected]=useState<Case|null>(null);const [filter,setFilter]=useState("all");const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [forbidden,setForbidden]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const rows=useMemo(()=>cases.filter((item)=>(filter==="all"||item.status===filter||item.priority===filter)&&`${item.reference} ${item.subject} ${item.category}`.toLowerCase().includes(query.toLowerCase())),[cases,filter,query]);const thread=messages.filter((item)=>item.caseId===selected?.id);
  async function load(){const data=await api() as {cases:Case[];messages:Message[]};setCases(data.cases);setMessages(data.messages);setSelected((current)=>current?data.cases.find((item)=>item.id===current.id)||null:data.cases[0]||null);}
  useEffect(()=>{let active=true;api().then((value)=>{if(active){const data=value as {cases:Case[];messages:Message[]};setCases(data.cases);setMessages(data.messages);setSelected(data.cases[0]||null);}}).catch((caught)=>{if(!active)return;if((caught as Error&{status?:number}).status===403)setForbidden(true);else setError(caught instanceof Error?caught.message:"Queue unavailable");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[]);
  async function mutate(action:string,extra:Record<string,unknown>={}){if(!selected)return;setSaving(true);setError("");try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,caseId:selected.id,version:selected.version,...extra})});setNotice("Support case updated and requester notified");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Case could not be updated");}finally{setSaving(false);}}
  async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await mutate("reply",{message:form.get("message")});event.currentTarget.reset();}
  return <main className={`cases-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"} id="main-content"><aside className="cases-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar?"عمليات المنصة":"Platform operations"}</span></a><nav><a href="/admin">{ar?"نظرة عامة":"Overview"}</a><a href="/admin/verification">{ar?"التحقق":"Verification"}</a><a href="/admin/finance">{ar?"المالية":"Finance"}</a><a className="active" href="/admin/cases">{ar?"الحالات":"Cases"}</a><a href="/admin/audit">{ar?"التدقيق":"Audit"}</a></nav><div className="cases-side-note"><span>♙</span><p><b>{ar?"وصول مرتبط بالغرض":"Purpose-bound access"}</b>{ar?"يمكن فقط لوكلاء الدعم النشطين ومديري المنصة الوصول إلى قائمة الانتظار. تخضع كل عملية للتدقيق.":"Only active support agents and platform administrators can access this queue. Every mutation is audited."}</p></div></aside>
    <section className="cases-main"><header className="cases-top"><div><span>{ar?"عمليات الدعم المباشرة":"LIVE SUPPORT OPERATIONS"}</span><b>{ar?"تُحجب البيانات الشخصية افتراضياً؛ ولا تظهر هوية مقدم الطلب إلا لموظفي الحالة المصرح لهم":"Personal data masked by default; requester identity is shown only to authorized case staff"}</b></div><div><button className="lang" type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a href="/notifications">●</a></div></header><div className="cases-workspace"><div className="cases-heading"><div><p>{ar?"الدعم والمساءلة":"SUPPORT & ACCOUNTABILITY"}</p><h1>{ar?"الحالات والتصعيدات":"Cases & escalations"}</h1><span>{ar?"افرز طلبات المرضى الدائمة وأسند المسؤولية وقدم تحديثات قابلة للمساءلة.":"Triage durable patient requests, assign responsibility, and provide accountable updates."}</span></div><button onClick={()=>void load()}>{ar?"تحديث القائمة":"Refresh queue"}</button></div>
      <div className="cases-banner"><span>▣</span><p><b>{ar?"الوصول الحساس مضبوط":"Sensitive access is controlled"}</b>{ar?"يتطلب وصول الدعم دوراً نشطاً في المنصة. تُسجل الردود والإسنادات وتغييرات الحالة في سجل التدقيق.":"Support access requires an active platform role. Replies, assignments, and status changes are recorded in the audit ledger."}</p><i>{ar?"مسجل بالكامل":"FULLY LOGGED"}</i></div>
      {loading&&<div className="appointment-live-state">{ar?"جارٍ تحميل قائمة الحالات المحمية…":"Loading protected case queue…"}</div>}{forbidden&&<div className="appointment-live-state"><h2>{ar?"يلزم دور دعم":"Support role required"}</h2><p>{ar?"اطلب من مدير المنصة منح دور وكيل دعم نشط.":"Ask a platform administrator to grant an active support agent role."}</p></div>}{error&&<div className="family-live-alert error"><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}{notice&&<div className="family-live-alert success"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
      {!loading&&!forbidden&&<><section className="cases-metrics">{[[cases.filter((item)=>!["resolved","closed"].includes(item.status)).length,ar?"حالات مفتوحة":"Open cases","◇"],[cases.filter((item)=>item.priority==="critical"&&!["resolved","closed"].includes(item.status)).length,ar?"حرجة":"Critical","!"],[cases.filter((item)=>item.status==="waiting_requester").length,ar?"بانتظار مقدم الطلب":"Waiting for requester","◷"],[cases.filter((item)=>item.status==="resolved").length,ar?"محلولة":"Resolved","✓"]].map((item)=><article key={String(item[1])}><span>{item[2]}</span><div><b>{item[0]}</b><p>{item[1]}</p></div></article>)}</section>
      <section className="cases-layout"><div className="case-queue"><div className="case-tools"><div>{["all","open","critical","waiting_requester","resolved"].map((item)=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{label(item,ar)}</button>)}</div><label>⌕<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={ar?"البحث في الحالات":"Search cases"}/></label></div><div className="case-table"><header><span>{ar?"الحالة":"Case"}</span><span>{ar?"الفئة":"Category"}</span><span>{ar?"الأولوية":"Priority"}</span><span>{ar?"مقدم الطلب":"Requester"}</span><span>{ar?"آخر تحديث":"Updated"}</span><span>{ar?"الوضع":"Status"}</span><span/></header>{rows.map((item)=><button key={item.id} className={selected?.id===item.id?"selected":""} onClick={()=>setSelected(item)}><div><b>{item.subject}</b><small>{item.reference}</small></div><span>{label(item.category,ar)}</span><i className={item.priority}>{label(item.priority,ar)}</i><span>{item.requesterName}</span><strong>{new Date(item.updatedAt).toLocaleDateString(ar?"ar-QA":"en-QA")}</strong><em>{label(item.status,ar)}</em><span>›</span></button>)}</div></div>
        {selected&&<aside className="case-detail"><div className="case-detail-head"><div><p>{label(selected.category,ar)}</p><h2>{selected.subject}</h2><span>{selected.reference}</span></div><i className={selected.priority}>{label(selected.priority,ar)}</i></div><section className="case-person"><span>{selected.requesterName.split(" ").map((part)=>part[0]).join("").slice(0,2)}</span><div><b>{selected.requesterName}</b><p>{ar?"مقدم طلب موثق":"Authenticated requester"}</p></div>{!selected.assignedToUserId&&<button disabled={saving} onClick={()=>void mutate("claim")}>{ar?"استلام الحالة":"Claim case"}</button>}</section><section className="case-facts"><h3>{ar?"ملخص الحالة":"Case summary"}</h3><p>{selected.description}</p><dl><div><dt>{ar?"مرجع ذو صلة":"Related reference"}</dt><dd>{selected.relatedReference||(ar?"لم يقدم":"None provided")}</dd></div><div><dt>{ar?"طلب الخصوصية":"Privacy request"}</dt><dd>{selected.privacyRequestType||(ar?"لا ينطبق":"Not applicable")}</dd></div><div><dt>{ar?"تاريخ الإنشاء":"Created"}</dt><dd>{new Date(selected.createdAt).toLocaleString(ar?"ar-QA":"en-QA")}</dd></div></dl></section><div className="case-thread">{thread.map((message)=><article className={message.authorKind==="agent"?"mine":""} key={message.id}><span>{message.authorKind==="agent"?(ar?"أنت":"YOU"):"PT"}</span><div><b>{message.authorKind==="agent"?(ar?"فريق الدعم":"Support team"):(ar?"مقدم الطلب":"Requester")}<small>{new Date(message.createdAt).toLocaleString(ar?"ar-QA":"en-QA")}</small></b><p>{message.body}</p></div></article>)}</div>{!["resolved","closed"].includes(selected.status)&&<><form className="case-reply" onSubmit={reply}><textarea name="message" required maxLength={4000} placeholder={ar?"اكتب رداً يظهر للحساب…":"Write an account-visible reply…"}/><button type="submit" disabled={saving}>{ar?"إرسال الرد":"Send reply"}</button></form><div className="case-actions"><button disabled={saving} onClick={()=>void mutate("set_status",{status:"in_progress"})}>{ar?"قيد المعالجة":"In progress"}</button><button disabled={saving} onClick={()=>void mutate("set_status",{status:"resolved"})}>{ar?"حل الحالة":"Resolve case"}</button></div></>}</aside>}</section></>}
    </div></section></main>;
}
