"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
type Case={id:string;reference:string;requesterName:string;category:string;subject:string;description:string;relatedReference:string|null;privacyRequestType:string|null;priority:string;status:string;version:number;assignedToUserId:string|null;createdAt:string;updatedAt:string};
type Message={id:string;caseId:string;authorKind:string;body:string;createdAt:string};
async function api(init?:RequestInit){const response=await fetch("/api/admin/cases",init);const payload=await response.json() as {data?:unknown;message?:string;error?:string};if(response.status===401){window.location.assign(`/signin-with-chatgpt?return_to=${encodeURIComponent("/admin/cases")}`);throw new Error("Authentication required");}if(!response.ok){const error=new Error(payload.message||payload.error||"Case queue unavailable");(error as Error&{status?:number}).status=response.status;throw error;}return payload.data;}
function label(value:string){return value.replaceAll("_"," ").replace(/^./,(letter)=>letter.toUpperCase());}
export default function CasesWorkspace(){
  const [cases,setCases]=useState<Case[]>([]);const [messages,setMessages]=useState<Message[]>([]);const [selected,setSelected]=useState<Case|null>(null);const [filter,setFilter]=useState("all");const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [forbidden,setForbidden]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const rows=useMemo(()=>cases.filter((item)=>(filter==="all"||item.status===filter||item.priority===filter)&&`${item.reference} ${item.subject} ${item.category}`.toLowerCase().includes(query.toLowerCase())),[cases,filter,query]);const thread=messages.filter((item)=>item.caseId===selected?.id);
  async function load(){const data=await api() as {cases:Case[];messages:Message[]};setCases(data.cases);setMessages(data.messages);setSelected((current)=>current?data.cases.find((item)=>item.id===current.id)||null:data.cases[0]||null);}
  useEffect(()=>{let active=true;api().then((value)=>{if(active){const data=value as {cases:Case[];messages:Message[]};setCases(data.cases);setMessages(data.messages);setSelected(data.cases[0]||null);}}).catch((caught)=>{if(!active)return;if((caught as Error&{status?:number}).status===403)setForbidden(true);else setError(caught instanceof Error?caught.message:"Queue unavailable");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[]);
  async function mutate(action:string,extra:Record<string,unknown>={}){if(!selected)return;setSaving(true);setError("");try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,caseId:selected.id,version:selected.version,...extra})});setNotice("Support case updated and requester notified");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Case could not be updated");}finally{setSaving(false);}}
  async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await mutate("reply",{message:form.get("message")});event.currentTarget.reset();}
  return <main className="cases-shell" id="main-content"><aside className="cases-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>Platform operations</span></a><nav><a href="/admin">Overview</a><a href="/admin/verification">Verification</a><a href="/admin/finance">Finance</a><a className="active" href="/admin/cases">Cases</a><a href="/admin/audit">Audit</a></nav><div className="cases-side-note"><span>♙</span><p><b>Purpose-bound access</b>Only active support agents and platform administrators can access this queue. Every mutation is audited.</p></div></aside>
    <section className="cases-main"><header className="cases-top"><div><span>LIVE SUPPORT OPERATIONS</span><b>Personal data masked by default; requester identity is shown only to authorized case staff</b></div><a href="/notifications">●</a></header><div className="cases-workspace"><div className="cases-heading"><div><p>SUPPORT & ACCOUNTABILITY</p><h1>Cases & escalations</h1><span>Triage durable patient requests, assign responsibility, and provide accountable updates.</span></div><button onClick={()=>void load()}>Refresh queue</button></div>
      <div className="cases-banner"><span>▣</span><p><b>Sensitive access is controlled</b>Support access requires an active platform role. Replies, assignments, and status changes are recorded in the audit ledger.</p><i>FULLY LOGGED</i></div>
      {loading&&<div className="appointment-live-state">Loading protected case queue…</div>}{forbidden&&<div className="appointment-live-state"><h2>Support role required</h2><p>Ask a platform administrator to grant an active support agent role.</p></div>}{error&&<div className="family-live-alert error"><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}{notice&&<div className="family-live-alert success"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
      {!loading&&!forbidden&&<><section className="cases-metrics">{[[cases.filter((item)=>!["resolved","closed"].includes(item.status)).length,"Open cases","◇"],[cases.filter((item)=>item.priority==="critical"&&!["resolved","closed"].includes(item.status)).length,"Critical","!"],[cases.filter((item)=>item.status==="waiting_requester").length,"Waiting for requester","◷"],[cases.filter((item)=>item.status==="resolved").length,"Resolved","✓"]].map((item)=><article key={String(item[1])}><span>{item[2]}</span><div><b>{item[0]}</b><p>{item[1]}</p></div></article>)}</section>
      <section className="cases-layout"><div className="case-queue"><div className="case-tools"><div>{["all","open","critical","waiting_requester","resolved"].map((item)=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{label(item)}</button>)}</div><label>⌕<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search cases"/></label></div><div className="case-table"><header><span>Case</span><span>Category</span><span>Priority</span><span>Requester</span><span>Updated</span><span>Status</span><span/></header>{rows.map((item)=><button key={item.id} className={selected?.id===item.id?"selected":""} onClick={()=>setSelected(item)}><div><b>{item.subject}</b><small>{item.reference}</small></div><span>{label(item.category)}</span><i className={item.priority}>{label(item.priority)}</i><span>{item.requesterName}</span><strong>{new Date(item.updatedAt).toLocaleDateString()}</strong><em>{label(item.status)}</em><span>›</span></button>)}</div></div>
        {selected&&<aside className="case-detail"><div className="case-detail-head"><div><p>{label(selected.category)}</p><h2>{selected.subject}</h2><span>{selected.reference}</span></div><i className={selected.priority}>{label(selected.priority)}</i></div><section className="case-person"><span>{selected.requesterName.split(" ").map((part)=>part[0]).join("").slice(0,2)}</span><div><b>{selected.requesterName}</b><p>Authenticated requester</p></div>{!selected.assignedToUserId&&<button disabled={saving} onClick={()=>void mutate("claim")}>Claim case</button>}</section><section className="case-facts"><h3>Case summary</h3><p>{selected.description}</p><dl><div><dt>Related reference</dt><dd>{selected.relatedReference||"None provided"}</dd></div><div><dt>Privacy request</dt><dd>{selected.privacyRequestType||"Not applicable"}</dd></div><div><dt>Created</dt><dd>{new Date(selected.createdAt).toLocaleString()}</dd></div></dl></section><div className="case-thread">{thread.map((message)=><article className={message.authorKind==="agent"?"mine":""} key={message.id}><span>{message.authorKind==="agent"?"YOU":"PT"}</span><div><b>{message.authorKind==="agent"?"Support team":"Requester"}<small>{new Date(message.createdAt).toLocaleString()}</small></b><p>{message.body}</p></div></article>)}</div>{!["resolved","closed"].includes(selected.status)&&<><form className="case-reply" onSubmit={reply}><textarea name="message" required maxLength={4000} placeholder="Write an account-visible reply…"/><button type="submit" disabled={saving}>Send reply</button></form><div className="case-actions"><button disabled={saving} onClick={()=>void mutate("set_status",{status:"in_progress"})}>In progress</button><button disabled={saving} onClick={()=>void mutate("set_status",{status:"resolved"})}>Resolve case</button></div></>}</aside>}</section></>}
    </div></section></main>;
}
