"use client";

import { useEffect, useMemo, useState } from "react";

type Case={id:string,title:string,party:string,category:string,priority:"Critical"|"High"|"Normal",status:string,owner:string,sla:string,channel:string};
const cases:Case[]=[
  {id:"SAF-031",title:"Service safety concern",party:"Patient M•••• A••••",category:"Clinical safety",priority:"Critical",status:"Escalated",owner:"Safety team",sla:"42m",channel:"Support"},
  {id:"PRV-092",title:"Data export request",party:"Patient N•••• M••••",category:"Privacy",priority:"High",status:"Action required",owner:"A. Rahman",sla:"3h 12m",channel:"Privacy form"},
  {id:"SUP-184",title:"Appointment support",party:"Booking RYT-••1042",category:"Operational support",priority:"Normal",status:"New",owner:"Unassigned",sla:"5h 28m",channel:"Chat"},
  {id:"PAY-077",title:"Payment reversed but booking active",party:"Booking RYT-••0981",category:"Payment",priority:"High",status:"Investigating",owner:"M. Saleh",sla:"7h 04m",channel:"Support"},
  {id:"PRV-088",title:"Consent withdrawal confirmation",party:"Patient H•••• R••••",category:"Privacy",priority:"Normal",status:"Waiting",owner:"A. Rahman",sla:"1d 2h",channel:"Email"},
  {id:"PRO-041",title:"Provider profile correction",party:"Al Waha Dental Centre",category:"Provider support",priority:"Normal",status:"In progress",owner:"L. Omar",sla:"1d 5h",channel:"Portal"},
];

export default function CasesWorkspace(){
  const [lang,setLang]=useState<"en"|"ar">("en");const [filter,setFilter]=useState("All");const [query,setQuery]=useState("");const [selected,setSelected]=useState<Case|null>(cases[0]);const [note,setNote]=useState("");const [notice,setNotice]=useState("");const [resolved,setResolved]=useState(false);const ar=lang==="ar";
  useEffect(()=>{document.querySelector<HTMLTextAreaElement>(".case-collab textarea")?.setAttribute("aria-label",ar?"ملاحظة داخلية":"Internal note");document.querySelector<HTMLSelectElement>(".case-collab select")?.setAttribute("aria-label",ar?"مالك الحالة":"Case owner");document.querySelector<HTMLAnchorElement>('.cases-top a[href="/notifications"]')?.setAttribute("aria-label",ar?"الإشعارات":"Notifications")},[ar,selected]);
  const rows=useMemo(()=>cases.filter(c=>(filter==="All"||c.priority===filter||c.status===filter)&&`${c.id} ${c.title} ${c.party}`.toLowerCase().includes(query.toLowerCase())),[filter,query]);const flash=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),2500)};
  return <main className={`cases-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <aside className="cases-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar?"عمليات المنصة":"Platform operations"}</span></a><div className="cases-role"><span>CS</span><div><b>{ar?"أخصائي الحالات":"Case specialist"}</b><small>{ar?"نطاق الدعم · مصادقة متعددة":"Support scope · MFA"}</small></div></div><nav><a href="/admin"><span>◫</span>{ar?"نظرة عامة":"Overview"}</a><a href="/admin/verification"><span>✓</span>{ar?"التحقق":"Verification"}</a><a href="/admin/finance"><span>Q</span>{ar?"المالية":"Finance"}</a><a className="active" href="/admin/cases"><span>◇</span>{ar?"الحالات":"Cases"}<i>9</i></a><a href="/admin"><span>◉</span>{ar?"الإشراف":"Moderation"}</a><a href="/admin"><span>▤</span>{ar?"التدقيق":"Audit"}</a></nav><div className="cases-side-note"><span>♙</span><p><b>{ar?"الكشف لسبب محدد":"Purpose-bound access"}</b>{ar?"تظل البيانات الشخصية مخفية حتى يطلبها وكيل مخول لحالة محددة.":"Personal data stays masked until an authorized agent requests it for a specific case."}</p></div><div className="cases-links"><a href="/journeys">◇ {ar?"جميع المسارات":"All journeys"}</a><a href="/admin">← {ar?"لوحة العمليات":"Operations dashboard"}</a></div></aside>
    <section className="cases-main"><header className="cases-top"><div><span>{ar?"بيئة النموذج":"PROTOTYPE ENVIRONMENT"}</span><b>{ar?"معلومات شخصية مخفية افتراضياً":"Personal information masked by default"}</b></div><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a href="/notifications">●</a><span>CS</span></div></header><div className="cases-workspace">
      <div className="cases-heading"><div><p>{ar?"الدعم والمساءلة":"SUPPORT & ACCOUNTABILITY"}</p><h1>{ar?"الحالات والتصعيدات":"Cases & escalations"}</h1><span>{ar?"فرز الحالات وتعيين المسؤولية وحماية الخصوصية حتى الحل.":"Triage work, assign ownership, protect privacy, and drive every case to resolution."}</span></div><button onClick={()=>flash(ar?"تم إنشاء مسودة حالة":"Prototype case draft created")}>＋ {ar?"حالة جديدة":"New case"}</button></div>
      <div className="cases-banner"><span>▣</span><p><b>{ar?"وصول حساس خاضع للرقابة":"Sensitive access is controlled"}</b>{ar?"أي كشف مؤقت يتطلب سبباً ومصادقة إضافية ويسجل في سجل التدقيق.":"Every temporary reveal requires a reason, step-up authentication, and an audit record."}</p><i>{ar?"تسجيل كامل":"FULLY LOGGED"}</i></div>
      <section className="cases-metrics">{[["9",ar?"حالات مفتوحة":"Open cases","◇"],["1",ar?"حالة حرجة":"Critical case","!"],["92%",ar?"ضمن وقت الخدمة":"Within SLA","◷"],["14m",ar?"متوسط أول رد":"First response","↗"]].map(x=><article key={x[1]}><span>{x[2]}</span><div><b>{x[0]}</b><p>{x[1]}</p></div></article>)}</section>
      <section className="cases-layout"><div className="case-queue"><div className="case-tools"><div>{["All","Critical","High","Normal","New"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?"البحث عن حالة":"Search cases"}/></label></div><div className="case-table"><header><span>{ar?"الحالة":"Case"}</span><span>{ar?"الفئة":"Category"}</span><span>{ar?"الأولوية":"Priority"}</span><span>{ar?"المالك":"Owner"}</span><span>{ar?"وقت الخدمة":"SLA"}</span><span>{ar?"الوضع":"Status"}</span><span/></header>{rows.map(c=><button key={c.id} className={selected?.id===c.id?"selected":""} onClick={()=>{setSelected(c);setResolved(false)}}><div><b>{c.title}</b><small>{c.id} · {c.party}</small></div><span>{c.category}</span><i className={c.priority.toLowerCase()}>{c.priority}</i><span>{c.owner}</span><strong>{c.sla}</strong><em>{c.status}</em><span>›</span></button>)}</div></div>
        {selected&&<aside className="case-detail"><div className="case-detail-head"><div><p>{selected.category}</p><h2>{selected.title}</h2><span>{selected.id} · {selected.channel}</span></div><i className={selected.priority.toLowerCase()}>{selected.priority}</i></div>{resolved?<div className="case-resolved"><span>✓</span><h3>{ar?"تم حل الحالة التجريبية":"Prototype case resolved"}</h3><p>{ar?"تم تسجيل القرار والسبب والوقت وإشعار القنوات ذات الصلة.":"The decision, reason, time, and notification events were logged."}</p><button onClick={()=>setResolved(false)}>{ar?"عرض سجل الحالة":"View case history"}</button></div>:<><div className="sla-card"><span>◷</span><div><b>{selected.sla}</b><p>{ar?"متبقي قبل هدف الحل":"remaining to resolution target"}</p></div><i>{selected.priority==="Critical"?(ar?"تصعيد نشط":"ESCALATED"):(ar?"ضمن الوقت":"ON TRACK")}</i></div><section className="case-person"><span>{selected.party.slice(0,2)}</span><div><b>{selected.party}</b><p>{ar?"البيانات الشخصية مخفية":"Personal data masked"}</p></div><button onClick={()=>flash(ar?"تم تسجيل طلب كشف مؤقت":"Temporary reveal request logged")}>▣ {ar?"طلب الكشف":"Request reveal"}</button></section><section className="case-facts"><h3>{ar?"ملخص الحالة":"Case summary"}</h3><dl><div><dt>{ar?"المصدر":"Source"}</dt><dd>{selected.channel}</dd></div><div><dt>{ar?"المالك":"Owner"}</dt><dd>{selected.owner}</dd></div><div><dt>{ar?"تاريخ الإنشاء":"Created"}</dt><dd>1 Aug 2026 · 08:42</dd></div><div><dt>{ar?"نطاق البيانات":"Data scope"}</dt><dd>{selected.category==="Privacy"?"Privacy case":"Operational only"}</dd></div></dl></section><section className="case-timeline"><h3>{ar?"الجدول الزمني":"Activity timeline"}</h3>{[["08:42","Case created","Automated routing"],["08:44","Acknowledgement sent","Notification service"],["09:05","Assigned to queue",selected.owner],["09:18","Evidence reviewed","CS-••12"]].map((x,i)=><article key={x[0]}><span className={i===3?"current":"done"}>{i===3?"●":"✓"}</span><div><b>{x[1]}</b><small>{x[0]} · {x[2]}</small></div></article>)}</section><section className="case-collab"><h3>{ar?"ملاحظة داخلية":"Internal note"}</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={ar?"أضف ملاحظة مرئية للفريق المخول فقط...":"Add a note visible only to the authorized team..."}/><div><select defaultValue={selected.owner}><option>{selected.owner}</option><option>Safety team</option><option>Privacy team</option><option>Finance team</option></select><button onClick={()=>{flash(ar?"تمت إضافة الملاحظة":"Internal note added");setNote("")}}>{ar?"إضافة ملاحظة":"Add note"}</button></div></section><div className="case-actions"><button onClick={()=>flash(ar?"تم طلب معلومات إضافية":"Additional information requested")}>{ar?"طلب معلومات":"Request info"}</button><button onClick={()=>flash(ar?"تم تصعيد الحالة التجريبية":"Prototype case escalated")}>↑ {ar?"تصعيد":"Escalate"}</button><button onClick={()=>setResolved(true)}>✓ {ar?"حل الحالة":"Resolve case"}</button></div></>}</aside>}
      </section><footer className="cases-footer"><span>ⓘ</span><p>{ar?"كل البيانات والحالات اصطناعية لأغراض تخطيط المنتج فقط.":"All data and cases are synthetic and for product planning only."}</p><a href="/admin">{ar?"سجل التدقيق":"Audit log"}</a></footer>
    </div></section>{notice&&<div className="cases-toast"><span>✓</span>{notice}</div>}
  </main>
}
