"use client";
import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "@/app/appointment-journey.module.css";

type MetricRow={status:string;value:number};type Data={aggregateOnly:boolean;metrics:{intakes:MetricRow[];guides:MetricRow[];accommodations:MetricRow[];actions:MetricRow[];timelineEntries:number};rehearsals:{id:string;scenarioCount:number;passedScenarios:number;result:string;executedAt:string}[]};
export default function Page(){const[lang,setLang]=useReyatiLocale();const ar=lang==="ar";const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");
const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/admin/appointment-journeys",{cache:"no-store"});if(r.status===401){location.assign("/signin-with-chatgpt?return_to=/admin/appointment-journeys");return}const p=await r.json().catch(()=>({}))as{data?:Data;message?:string};if(!r.ok||!p.data)throw new Error(p.message||"Unable to load governance");setData(p.data)}catch(e){setError(e instanceof Error?e.message:"Unable to load governance")}finally{setLoading(false)}},[]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);
async function rehearse(){setError("");const r=await fetch("/api/admin/appointment-journeys",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"rehearse"})});if(!r.ok){setError(ar?"تعذر تشغيل الاختبار.":"The rehearsal could not run.");return}setNotice(ar?"اكتمل اختبار 45 سيناريو دون آثار تشغيلية.":"45-scenario rehearsal passed with zero operational effects.");await load()}
const cards=data?[{name:ar?"بيانات ما قبل الزيارة":"Pre-visit intake",rows:data.metrics.intakes},{name:ar?"إرشادات الاستعداد":"Preparation guides",rows:data.metrics.guides},{name:ar?"طلبات التسهيلات":"Accommodation requests",rows:data.metrics.accommodations},{name:ar?"إجراءات ما بعد الزيارة":"Post-visit actions",rows:data.metrics.actions},{name:ar?"أحداث الخط الزمني":"Timeline entries",rows:[{status:"recorded",value:data.metrics.timelineEntries}]}]:[];
return <main className={styles.shell} dir={ar?"rtl":"ltr"}><header className={styles.top}><a href="/admin"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya"/></a><div className={styles.topActions}><button type="button" className={styles.lang} onClick={()=>setLang(ar?"en":"ar")}>{ar?"EN":"العربية"}</button><a href="/admin">{ar?"العمليات":"Operations"}</a></div></header><section className={styles.hero}><span>{ar?"حوكمة رحلة الموعد":"APPOINTMENT JOURNEY GOVERNANCE"}</span><h1>{ar?"سلامة الرحلة من البداية إلى المتابعة":"Journey safety from intake to follow-up"}</h1><p>{ar?"مقاييس مجمعة فقط وخمس وحدات محكومة دون كشف سرد المريض.":"Aggregate-only oversight across five controlled modules without patient narrative disclosure."}</p></section><section className={styles.boundary}><b>{ar?"حدود صارمة":"Strict boundaries"}</b><span>{ar?"لا قرارات سريرية آلية، ولا تعديل للمواعيد، ولا إرسال خارجي، ولا كشف للسجلات.":"No automated clinical decisions, appointment mutation, external delivery, or record disclosure."}</span></section>{error&&<div className={styles.error}>{error}<button type="button" onClick={()=>void load()}>{ar?"إعادة المحاولة":"Retry"}</button></div>}{notice&&<div className={styles.notice}>{notice}</div>}<div className={styles.grid}><section className={`${styles.panel} ${styles.wide}`}><div className={styles.panelHead}><div><small>{ar?"حالة الوحدات":"MODULE POSTURE"}</small><h2>{ar?"مقاييس مجمعة":"Aggregate metrics"}</h2></div><button type="button" onClick={()=>void rehearse()}>{ar?"تشغيل اختبار اصطناعي":"Run synthetic rehearsal"}</button></div>{loading?<div className={styles.empty}>{ar?"جارٍ التحميل…":"Loading…"}</div>:<div className={styles.list}>{cards.map(card=><article key={card.name}><div className={styles.cardTop}><b>{card.name}</b><span>{card.rows.reduce((sum,row)=>sum+Number(row.value),0)}</span></div><p>{card.rows.map(row=>`${row.status.replaceAll("_"," ")}: ${row.value}`).join(" · ")|| (ar?"لا توجد سجلات":"No records")}</p></article>)}</div>}</section><section className={`${styles.panel} ${styles.wide}`}><div className={styles.panelHead}><div><small>{ar?"اختبارات عدم الأثر":"ZERO-EFFECT REHEARSALS"}</small><h2>{ar?"آخر الأدلة":"Latest evidence"}</h2></div></div>{!data?.rehearsals.length?<div className={styles.empty}>{ar?"لم يتم تشغيل اختبار بعد.":"No rehearsal has run yet."}</div>:<div className={styles.list}>{data.rehearsals.map(row=><article key={row.id}><div className={styles.cardTop}><b>{row.scenarioCount} {ar?"سيناريو":"scenarios"}</b><span>{row.result}</span></div><p>{row.passedScenarios}/{row.scenarioCount} {ar?"ناجح":"passed"}</p></article>)}</div>}</section></div></main>}
