"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./document-change-control-workspace.module.css";

export type DocumentChangeControlMode = "prepare" | "review" | "observe" | "rollback";
type Window = { id: string; reference: string; preparedByUserId: string; evidenceReference: string; windowStartsAt: string; windowEndsAt: string; changeOwner: string; monitoringOwner: string; rollbackOwner: string; status: string; reviewNote: string | null; openedByUserId: string | null; version: number; canReview?: boolean; canOpen?: boolean; canObserve?: boolean; canVerify?: boolean; canRequestRollback?: boolean; canVerifyRollback?: boolean };
type Event = { id: string; windowId: string; eventCode: string; previousStatus: string | null; nextStatus: string; createdAt: string };
type Data = { currentUserId: string; role: string; workflowVersion: string; stage: string; nextHref: string; windows: Window[]; events: Event[]; readiness: { preActivationReady: boolean }; posture: { allRuntimeControlsEnabled: boolean; scanDispatchEnabled: boolean; scanPollingEnabled: boolean; retentionExecutionEnabled: boolean; deletionProcessorEnabled: boolean } };

const steps = [
  { mode: "prepare", href: "/admin/document-change-window", number: "01", label: ["Prepare window", "إعداد النافذة"] },
  { mode: "review", href: "/admin/document-change-review", number: "02", label: ["Independent review", "مراجعة مستقلة"] },
  { mode: "observe", href: "/admin/document-change-observation", number: "03", label: ["Observe & verify", "المراقبة والتحقق"] },
  { mode: "rollback", href: "/admin/document-rollback-control", number: "04", label: ["Rollback control", "التحكم بالتراجع"] },
] as const;

const config = {
  prepare: { endpoint: "/api/admin/document-change-window", eyebrow: ["PRODUCTION CHANGE CONTROL", "التحكم بتغيير الإنتاج"], title: ["Prepare a bounded activation window.", "أعد نافذة تفعيل محددة."], detail: ["Name distinct operators, fix the time boundary, and submit coded evidence for independent review.", "حدد مشغلين مختلفين وحدوداً زمنية وأرسل دليلاً مشفراً لمراجعة مستقلة."] },
  review: { endpoint: "/api/admin/document-change-review", eyebrow: ["INDEPENDENT DECISION", "قرار مستقل"], title: ["Review before production access.", "راجع قبل الوصول للإنتاج."], detail: ["A different authorized operator approves or returns the exact prepared window.", "يعتمد مشغل مخول مختلف النافذة المعدة نفسها أو يعيدها."] },
  observe: { endpoint: "/api/admin/document-change-observation", eyebrow: ["LIVE POSTURE EVIDENCE", "دليل وضع التشغيل"], title: ["Open, observe, then verify.", "افتح وراقب ثم تحقق."], detail: ["The console records safe posture evidence; it never changes Vercel, scanner, or storage configuration.", "تسجل المنصة دليل الوضع الآمن ولا تغير إعدادات Vercel أو الماسح أو التخزين."] },
  rollback: { endpoint: "/api/admin/document-rollback-control", eyebrow: ["FAIL-CLOSED CONTAINMENT", "احتواء مغلق افتراضياً"], title: ["Control rollback without ambiguity.", "تحكم بالتراجع دون غموض."], detail: ["Request containment during an active change and require an independent operator to verify hazardous controls are disabled.", "اطلب الاحتواء أثناء التغيير النشط واشترط مشغلاً مستقلاً للتحقق من تعطيل الضوابط الخطرة."] },
} as const;

async function api(endpoint: string, init?: RequestInit) {
  const response = await fetch(endpoint, { cache: "no-store", credentials: "same-origin", ...init });
  const payload = await response.json().catch(() => ({})) as { data?: Data | Window; error?: string; message?: string };
  if (response.status === 401) { window.location.assign(`/sign-in?redirect_url=${encodeURIComponent(location.pathname)}`); throw new Error("Authentication required"); }
  if (!response.ok || !payload.data) throw new Error(payload.message || payload.error || "Production change control is unavailable");
  return payload.data;
}

function formatStamp(value: string, ar: boolean) { return new Intl.DateTimeFormat(ar ? "ar-QA" : "en-QA", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Qatar" }).format(new Date(value)); }
function status(value: string) { return value.replaceAll("_", " "); }

export default function DocumentChangeControlWorkspace({ mode }: { mode: DocumentChangeControlMode }) {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar"; const selectedConfig = config[mode];
  const [data, setData] = useState<Data | null>(null); const [selectedId, setSelectedId] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const copy = (value: readonly [string, string]) => ar ? value[1] : value[0];
  const load = useCallback(async () => { try { const next = await api(selectedConfig.endpoint) as Data; setData(next); setSelectedId((current) => next.windows.some((item) => item.id === current) ? current : next.windows[0]?.id ?? ""); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Production change control is unavailable"); } finally { setLoading(false); } }, [selectedConfig.endpoint]);
  useEffect(() => { let active = true; queueMicrotask(() => { if (active) void load(); }); return () => { active = false; }; }, [load]);

  async function mutate(body: Record<string, unknown>) { setBusy(true); setError(""); setNotice(""); try { await api(selectedConfig.endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setNotice(ar ? "تم تسجيل الخطوة في سجل التحكم وتحديث مساحة العمل." : "The control step was recorded and the workspace refreshed."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The control step failed"); } finally { setBusy(false); } }
  function prepare(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void mutate({ clientRequestId: crypto.randomUUID(), evidenceReference: form.get("evidenceReference"), windowStartsAt: form.get("windowStartsAt"), windowEndsAt: form.get("windowEndsAt"), changeOwner: form.get("changeOwner"), monitoringOwner: form.get("monitoringOwner"), rollbackOwner: form.get("rollbackOwner") }); }

  const selected = data?.windows.find((item) => item.id === selectedId) ?? data?.windows[0];
  const events = data?.events.filter((item) => item.windowId === selected?.id) ?? [];
  const common = selected ? { windowId: selected.id, version: selected.version } : null;
  const contained = Boolean(data && !data.posture.scanDispatchEnabled && !data.posture.scanPollingEnabled && !data.posture.retentionExecutionEnabled && !data.posture.deletionProcessorEnabled);

  return <main className={styles.shell} dir={ar ? "rtl" : "ltr"} id="main-content">
    <aside className={styles.side}><a href="/admin"><Image src="/brand/qivaya-logo-reversed.png" alt="Qivaya" width={142} height={53}/></a><p>{ar ? "التحكم بتغيير المستندات" : "DOCUMENT CHANGE CONTROL"}</p><nav aria-label={ar ? "مراحل التحكم بالتغيير" : "Change-control stages"}>{steps.map((step) => <a key={step.mode} className={mode === step.mode ? styles.active : ""} href={step.href}><span>{step.number}</span>{copy(step.label)}</a>)}</nav><div className={styles.boundary}><b>{ar ? "تغيير يدوي، دليل دائم" : "Manual change, durable evidence"}</b><span>{ar ? "لا تنشر هذه المساحات رمزاً أو تغير إعداداً أو تعرض بيانات اعتماد." : "These workspaces deploy no code, change no configuration, and expose no credential."}</span></div></aside>
    <section className={styles.workspace}><header className={styles.top}><a href="/admin/document-activation-preflight">← {ar ? "فحص التفعيل" : "Activation preflight"}</a><div><span data-ready={data?.readiness.preActivationReady}>{data?.readiness.preActivationReady ? (ar ? "المتطلبات جاهزة" : "PREREQUISITES READY") : (ar ? "مغلق افتراضياً" : "FAIL-CLOSED")}</span><button type="button" onClick={() => void load()}>{ar ? "تحديث" : "Refresh"}</button><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "EN" : "العربية"}</button></div></header>
      <div className={styles.content}><section className={styles.hero}><span>{steps.find((step) => step.mode === mode)?.number}</span><div><p>{copy(selectedConfig.eyebrow)}</p><h1>{copy(selectedConfig.title)}</h1><strong>{copy(selectedConfig.detail)}</strong></div><i data-ready={mode === "rollback" ? contained : data?.posture.allRuntimeControlsEnabled}>{mode === "rollback" ? (contained ? "CONTAINED" : "ACTION") : data?.posture.allRuntimeControlsEnabled ? "TARGET" : "GATED"}</i></section>
        {error ? <div className={styles.alert} data-kind="error" role="alert">{error}<button type="button" onClick={() => setError("")}>×</button></div> : null}{notice ? <div className={styles.alert} data-kind="success" role="status">✓ {notice}<button type="button" onClick={() => setNotice("")}>×</button></div> : null}
        {mode === "prepare" ? <PreparationForm ar={ar} busy={busy} ready={Boolean(data?.readiness.preActivationReady)} submit={prepare}/> : null}
        {loading ? <div className={styles.state}>{ar ? "جارٍ قراءة سجل التغيير…" : "Reading the production change ledger…"}</div> : null}
        {!loading && !data?.windows.length ? <div className={styles.empty}><b>✓</b><h2>{ar ? "لا توجد عناصر في هذه المرحلة" : "Nothing is waiting at this stage"}</h2><p>{ar ? "تابع المرحلة السابقة أو افتح سجل التفعيل الكامل." : "Continue from the preceding stage or open the complete activation ledger."}</p><a href="/admin/document-activation">{ar ? "فتح السجل الكامل" : "Open complete ledger"} →</a></div> : null}
        {data?.windows.length ? <section className={styles.control}><aside className={styles.queue}><header><p>{ar ? "قائمة المرحلة" : "STAGE QUEUE"}</p><b>{data.windows.length}</b></header>{data.windows.map((item) => <button type="button" key={item.id} data-selected={item.id === selected?.id} onClick={() => setSelectedId(item.id)}><i data-status={item.status}>{item.status === "verified" ? "✓" : item.status === "rolled_back" ? "↻" : "•"}</i><span><b>{item.reference}</b><small>{status(item.status)} · {formatStamp(item.windowStartsAt, ar)}</small></span></button>)}</aside><article className={styles.detail}>{selected ? <><header><div><p>{selected.evidenceReference}</p><h2>{status(selected.status)}</h2><span>{formatStamp(selected.windowStartsAt, ar)} — {formatStamp(selected.windowEndsAt, ar)}</span></div><em>v{selected.version}</em></header><div className={styles.owners}><span><small>{ar ? "التغيير" : "CHANGE"}</small><b>{selected.changeOwner}</b></span><span><small>{ar ? "المراقبة" : "MONITOR"}</small><b>{selected.monitoringOwner}</b></span><span><small>{ar ? "التراجع" : "ROLLBACK"}</small><b>{selected.rollbackOwner}</b></span></div><StageActions mode={mode} ar={ar} busy={busy} window={selected} common={common} mutate={mutate}/><div className={styles.timeline}><h3>{ar ? "أثر تحكمي غير قابل للتعديل" : "Immutable control trail"}</h3>{events.map((item) => <div key={item.id}><i>•</i><span><b>{status(item.eventCode)}</b><small>{item.previousStatus ? `${status(item.previousStatus)} → ` : ""}{status(item.nextStatus)} · {formatStamp(item.createdAt, ar)}</small></span></div>)}</div></> : null}</article></section> : null}
      </div>
    </section>
  </main>;
}

function PreparationForm({ ar, busy, ready, submit }: { ar: boolean; busy: boolean; ready: boolean; submit: (event: FormEvent<HTMLFormElement>) => void }) { return <section className={styles.formPanel}><div><p>{ar ? "حزمة التغيير" : "CHANGE PACKAGE"}</p><h2>{ar ? "حدود واضحة وثلاثة ملاك مختلفين" : "Clear bounds and three distinct owners"}</h2><span>{ar ? "يبقى التفعيل مغلقاً حتى تكتمل المتطلبات وتعتمد المراجعة المستقلة." : "Activation remains locked until prerequisites pass and independent review approves the window."}</span></div><form onSubmit={submit}><label>{ar ? "مرجع الدليل المشفر" : "Coded evidence reference"}<input name="evidenceReference" placeholder="MDA-CHANGE-20260825-A1" pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{5,159}" required/></label><label>{ar ? "بداية النافذة" : "Window starts"}<input type="datetime-local" name="windowStartsAt" required/></label><label>{ar ? "نهاية النافذة" : "Window ends"}<input type="datetime-local" name="windowEndsAt" required/></label><label>{ar ? "مالك التغيير" : "Change owner"}<input name="changeOwner" minLength={2} maxLength={160} required/></label><label>{ar ? "مالك المراقبة" : "Monitoring owner"}<input name="monitoringOwner" minLength={2} maxLength={160} required/></label><label>{ar ? "مالك التراجع" : "Rollback owner"}<input name="rollbackOwner" minLength={2} maxLength={160} required/></label><button disabled={busy || !ready}>{busy ? (ar ? "جارٍ الإرسال…" : "Submitting…") : ready ? (ar ? "إرسال للمراجعة" : "Send for independent review") : (ar ? "أكمل المتطلبات أولاً" : "Complete prerequisites first")}</button></form></section>; }

function StageActions({ mode, ar, busy, window, common, mutate }: { mode: DocumentChangeControlMode; ar: boolean; busy: boolean; window: Window; common: { windowId: string; version: number } | null; mutate: (body: Record<string, unknown>) => Promise<void> }) {
  if (!common) return null;
  if (mode === "review") return <div className={styles.actions}><button className={styles.secondary} disabled={busy || !window.canReview} onClick={() => void mutate({ ...common, decision: "return", reviewNote: "Returned after independent review of the coded change package and operating boundaries." })}>{ar ? "إرجاع للتعديل" : "Return for revision"}</button><button disabled={busy || !window.canReview} onClick={() => void mutate({ ...common, decision: "approve", reviewNote: "Independently reviewed the coded evidence, distinct owners, bounded window, and rollback procedure." })}>{ar ? "اعتماد النافذة" : "Approve window"}</button></div>;
  if (mode === "observe") return <div className={styles.actions}>{window.status === "approved" ? <button disabled={busy || !window.canOpen} onClick={() => void mutate({ ...common, action: "open" })}>{ar ? "فتح النافذة المعتمدة" : "Open approved window"}</button> : null}{window.status === "in_progress" ? <button disabled={busy || !window.canObserve} onClick={() => void mutate({ ...common, action: "observe" })}>{ar ? "التقاط وضع الخادم" : "Observe server posture"}</button> : null}{window.status === "verification_pending" ? <button disabled={busy || !window.canVerify} onClick={() => void mutate({ ...common, action: "verify", verificationNote: "Independently revalidated the complete production posture and current governance evidence." })}>{ar ? "توثيق التفعيل" : "Verify activation"}</button> : null}{window.status === "verified" ? <a href="/admin/data-lifecycle-acceptance">{ar ? "متابعة قبول دورة الحياة" : "Continue to lifecycle acceptance"} →</a> : null}</div>;
  if (mode === "rollback") return <div className={styles.actions}>{["in_progress", "verification_pending"].includes(window.status) ? <button className={styles.danger} disabled={busy || !window.canRequestRollback} onClick={() => void mutate({ ...common, action: "request_rollback" })}>{ar ? "طلب احتواء التراجع" : "Request rollback containment"}</button> : null}{window.status === "rollback_required" ? <button disabled={busy || !window.canVerifyRollback} onClick={() => void mutate({ ...common, action: "verify_rollback" })}>{ar ? "التحقق المستقل من الاحتواء" : "Independently verify containment"}</button> : null}{window.status === "rolled_back" ? <a href="/admin/document-incidents">{ar ? "فتح قيادة الحوادث" : "Open incident command"} →</a> : null}</div>;
  return <div className={styles.actions}><a href="/admin/document-change-review">{ar ? "فتح المراجعة المستقلة" : "Open independent review"} →</a></div>;
}
