"use client";

import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import type { DocumentOperationsStage } from "@/lib/document-production-operations";
import styles from "./document-change-control-workspace.module.css";

type Metric = { id: string; label: string; labelAr: string; value: string; detail: string; detailAr: string; state: "ready" | "attention" | "info"; href: string };
type Certificate = { id: string; reference: string; effectiveStatus: string; releaseStartsAt: string; releaseEndsAt: string; releaseOwnerName: string; monitoringOwnerName: string; stopAuthorityName: string };
type Data = { stage: DocumentOperationsStage; role: string; generatedAt: string; workflowVersion: string; focus: Metric[]; summary: { ready: boolean; passedChecks: number; totalChecks: number; activeCertificates: number; scheduledCertificates: number; attentionTotal: number }; recentCertificates: Certificate[] };

const stages = [
  { mode: "runtime_controls", route: "document-runtime-controls", number: "01", label: ["Runtime controls", "ضوابط التشغيل"] },
  { mode: "storage_watch", route: "document-storage-watch", number: "02", label: ["Storage posture", "وضع التخزين"] },
  { mode: "scanner_watch", route: "document-scanner-watch", number: "03", label: ["Scanner posture", "وضع الماسح"] },
  { mode: "queue_watch", route: "document-queue-watch", number: "04", label: ["Queue watch", "مراقبة القوائم"] },
  { mode: "retention_watch", route: "document-retention-watch", number: "05", label: ["Retention watch", "مراقبة الاحتفاظ"] },
  { mode: "deletion_watch", route: "document-deletion-watch", number: "06", label: ["Deletion watch", "مراقبة الحذف"] },
  { mode: "legal_hold_watch", route: "document-legal-hold-watch", number: "07", label: ["Legal-hold watch", "مراقبة الحجز"] },
  { mode: "incident_watch", route: "document-incident-watch", number: "08", label: ["Incident watch", "مراقبة الحوادث"] },
  { mode: "evidence_renewal", route: "document-evidence-renewal", number: "09", label: ["Evidence renewal", "تجديد الدليل"] },
  { mode: "operations_handoff", route: "document-operations-handoff", number: "10", label: ["Operations handoff", "تسليم العمليات"] },
] as const;

const config = {
  runtime_controls: { eyebrow: ["PROTECTED RUNTIME", "التشغيل المحمي"], title: ["See every production control in one view.", "اعرض كل ضابط إنتاج في شاشة واحدة."], detail: ["Observe the six document controls, production boundary, and active release coverage without exposing a secret or changing a setting.", "راقب ضوابط المستندات الستة وحدود الإنتاج وتغطية الإطلاق النشطة دون كشف سر أو تغيير إعداد."] },
  storage_watch: { eyebrow: ["PRIVATE STORAGE POSTURE", "وضع التخزين الخاص"], title: ["Keep protected storage evidence current.", "أبقِ دليل التخزين المحمي حديثاً."], detail: ["Join private R2 configuration, quarantine counts, and fresh synthetic safety evidence without listing an object.", "اجمع إعداد R2 الخاص وأعداد العزل ودليل السلامة الاصطناعي الحديث دون سرد أي كائن."] },
  scanner_watch: { eyebrow: ["PRIVATE PROCESSING POSTURE", "وضع المعالجة الخاصة"], title: ["Watch the complete scanner lifecycle.", "راقب دورة حياة الماسح الكاملة."], detail: ["Confirm private processing, dispatch, polling, and aggregate failure signals without sending a medical file.", "أكد المعالجة الخاصة والإرسال والاستطلاع وإشارات الفشل المجمعة دون إرسال ملف طبي."] },
  queue_watch: { eyebrow: ["DOCUMENT QUEUE HEALTH", "صحة قوائم المستندات"], title: ["Surface stuck work before it becomes an incident.", "أظهر العمل العالق قبل أن يصبح حادثة."], detail: ["Track stale scan jobs, failed jobs, and quarantine pressure using counts only.", "تتبّع مهام الفحص المتأخرة والفاشلة وضغط العزل باستخدام الأعداد فقط."] },
  retention_watch: { eyebrow: ["RETENTION EXECUTION WATCH", "مراقبة تنفيذ الاحتفاظ"], title: ["Connect policy approval to runtime health.", "اربط اعتماد السياسة بصحة التشغيل."], detail: ["Observe the approved plan, execution control, and failed-run signal without running retention.", "راقب الخطة المعتمدة وضابط التنفيذ وإشارة العمليات الفاشلة دون تشغيل الاحتفاظ."] },
  deletion_watch: { eyebrow: ["DELETION SAFETY WATCH", "مراقبة سلامة الحذف"], title: ["Keep deletion fail-closed and explainable.", "أبقِ الحذف مغلقاً افتراضياً وقابلاً للتفسير."], detail: ["Join processor posture, failed jobs, and legal-hold conflicts without creating or executing deletion work.", "اجمع وضع المعالج والمهام الفاشلة وتعارضات الحجز القانوني دون إنشاء أو تنفيذ عمل حذف."] },
  legal_hold_watch: { eyebrow: ["LEGAL-HOLD SAFETY", "سلامة الحجز القانوني"], title: ["Expose overdue review and deletion conflict pressure.", "أظهر ضغط المراجعات المتأخرة وتعارضات الحذف."], detail: ["This read-only view never creates, renews, approves, or releases a hold.", "هذه الشاشة للقراءة فقط ولا تنشئ حجزاً ولا تجدده أو تعتمده أو تفرج عنه."] },
  incident_watch: { eyebrow: ["INCIDENT ESCALATION", "تصعيد الحوادث"], title: ["Turn aggregate warning signals into a clear handoff.", "حوّل إشارات التحذير المجمعة إلى تسليم واضح."], detail: ["See active incidents, combined exception pressure, and the separate named stop route.", "اعرض الحوادث النشطة وضغط الاستثناءات المجمع ومسار الإيقاف المسمى المنفصل."] },
  evidence_renewal: { eyebrow: ["EVIDENCE FRESHNESS", "حداثة الدليل"], title: ["Renew evidence before authorization expires.", "جدّد الدليل قبل انتهاء التفويض."], detail: ["Track the age of acceptance, activation, and assurance evidence against the thirty-day production window.", "تتبّع عمر أدلة القبول والتفعيل والتأكيد مقابل نافذة الإنتاج ذات الثلاثين يوماً."] },
  operations_handoff: { eyebrow: ["ACCOUNTABLE HANDOFF", "تسليم خاضع للمساءلة"], title: ["Hand one live operating picture to the next shift.", "سلّم صورة تشغيلية مباشرة واحدة إلى الوردية التالية."], detail: ["Combine current checks, operator coverage, release windows, and every attention signal into one read-only handoff.", "اجمع الفحوص الحالية وتغطية المشغلين ونوافذ الإطلاق وكل إشارات الانتباه في تسليم واحد للقراءة فقط."] },
} as const;

function endpoint(stage: DocumentOperationsStage) { const found = stages.find((item) => item.mode === stage); return `/api/admin/${found?.route ?? "document-operations-handoff"}`; }
function stamp(value: string, ar: boolean) { return new Intl.DateTimeFormat(ar ? "ar-QA" : "en-QA", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Qatar" }).format(new Date(value)); }
function words(value: string) { return value.replaceAll("_", " "); }

export default function DocumentProductionOperationsWorkspace({ stage }: { stage: DocumentOperationsStage }) {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar"; const selectedConfig = config[stage]; const step = stages.find((item) => item.mode === stage);
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const copy = (value: readonly [string, string]) => ar ? value[1] : value[0];
  const load = useCallback(async () => { try { const response = await fetch(endpoint(stage), { cache: "no-store", credentials: "same-origin" }); const payload = await response.json().catch(() => ({})) as { data?: Data; error?: string }; if (response.status === 401) { window.location.assign(`/sign-in?redirect_url=${encodeURIComponent(location.pathname)}`); return; } if (!response.ok || !payload.data) throw new Error(payload.error || "Production operations evidence is unavailable"); setData(payload.data); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Production operations evidence is unavailable"); } finally { setLoading(false); } }, [stage]);
  useEffect(() => { let active = true; queueMicrotask(() => { if (active) void load(); }); return () => { active = false; }; }, [load]);
  const ready = Boolean(data?.summary.ready && data.summary.attentionTotal === 0);
  return <main className={styles.shell} dir={ar ? "rtl" : "ltr"} id="main-content"><aside className={styles.side}><a href="/admin"><Image src="/brand/qivaya-logo-reversed.png" alt="Qivaya" width={142} height={53}/></a><p>{ar ? "ضمان عمليات الإنتاج" : "PRODUCTION OPERATIONS ASSURANCE"}</p><nav aria-label={ar ? "وحدات ضمان عمليات المستندات" : "Document operations assurance modules"}>{stages.map((item) => <a key={item.mode} className={stage === item.mode ? styles.active : ""} href={`/admin/${item.route}`}><span>{item.number}</span>{copy(item.label)}</a>)}</nav><div className={styles.boundary}><b>{ar ? "رؤية مجمعة دون تشغيل" : "Aggregate visibility, zero operation"}</b><span>{ar ? "لا تقرأ الوحدات ملفات المرضى أو كائنات R2 ولا تغيّر التحكم أو الحجز أو الحوادث." : "These modules read no patient file or R2 object and change no control, hold, or incident."}</span></div></aside><section className={styles.workspace}><header className={styles.top}><a href="/admin/document-release-monitoring">← {ar ? "مراقبة الإطلاق" : "Release monitoring"}</a><div><span data-ready={ready}>{ready ? (ar ? "الوضع مستقر" : "POSTURE CLEAR") : (ar ? "يتطلب الانتباه" : "ATTENTION REQUIRED")}</span><button type="button" onClick={() => void load()}>{ar ? "تحديث" : "Refresh"}</button><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "EN" : "العربية"}</button></div></header><div className={styles.content}><section className={styles.hero}><span>{step?.number}</span><div><p>{copy(selectedConfig.eyebrow)}</p><h1>{copy(selectedConfig.title)}</h1><strong>{copy(selectedConfig.detail)}</strong></div><i data-ready={ready}>{ready ? "CLEAR" : "WATCH"}</i></section>{error ? <div className={styles.alert} data-kind="error" role="alert">{error}<button type="button" onClick={() => setError("")}>×</button></div> : null}{loading ? <div className={styles.state}>{ar ? "جارٍ قراءة الإشارات المجمعة…" : "Reading aggregate production signals…"}</div> : null}{data ? <><OperationsSummary ar={ar} data={data}/><section className={styles.control}><article className={styles.detail}><FocusMetrics ar={ar} metrics={data.focus}/></article><aside className={styles.queue}><CertificateRegister ar={ar} certificates={data.recentCertificates}/></aside></section><div className={styles.state}>{ar ? `تم التحديث ${stamp(data.generatedAt, ar)} · لا توجد عمليات مستندات منفذة من هذه الوحدة.` : `Updated ${stamp(data.generatedAt, ar)} · no document operation is executed from this module.`}</div></> : null}</div></section></main>;
}

function OperationsSummary({ ar, data }: { ar: boolean; data: Data }) { return <div className={styles.owners}><span><small>{ar ? "فحوص الإطلاق" : "RELEASE CHECKS"}</small><b>{data.summary.passedChecks}/{data.summary.totalChecks}</b></span><span><small>{ar ? "شهادات نشطة" : "ACTIVE CERTIFICATES"}</small><b>{data.summary.activeCertificates}</b></span><span><small>{ar ? "عناصر انتباه" : "ATTENTION ITEMS"}</small><b>{data.summary.attentionTotal}</b></span></div>; }

function FocusMetrics({ ar, metrics }: { ar: boolean; metrics: Metric[] }) { return <><header><div><p>{ar ? "أدلة الوحدة الحالية" : "CURRENT MODULE EVIDENCE"}</p><h2>{ar ? "الإشارات المباشرة" : "Live signals"}</h2><span>{ar ? "تُحسب كل حالة من الأدلة الحالية من جهة الخادم." : "Every state is derived from current server-side evidence."}</span></div><em>{metrics.length}</em></header><div className={styles.timeline}>{metrics.map((item) => <div key={item.id}><i aria-hidden="true">{item.state === "ready" ? "✓" : item.state === "attention" ? "!" : "i"}</i><span><b>{ar ? item.labelAr : item.label}: {item.value}</b><small>{ar ? item.detailAr : item.detail}</small><a href={item.href}>{ar ? "فتح مساحة التحكم" : "Open control workspace"} →</a></span></div>)}</div></>; }

function CertificateRegister({ ar, certificates }: { ar: boolean; certificates: Certificate[] }) { return <><header><p>{ar ? "الشهادات الحديثة" : "RECENT CERTIFICATES"}</p><b>{certificates.length}</b></header>{certificates.length ? certificates.map((item) => <button type="button" key={item.id} disabled><i data-status={item.effectiveStatus}>{item.effectiveStatus === "active" ? "✓" : "•"}</i><span><b>{item.reference}</b><small>{words(item.effectiveStatus)} · {stamp(item.releaseStartsAt, ar)}<br/>{ar ? "الإطلاق" : "Release"}: {item.releaseOwnerName}<br/>{ar ? "المراقبة" : "Monitor"}: {item.monitoringOwnerName}<br/>{ar ? "الإيقاف" : "Stop"}: {item.stopAuthorityName}</small></span></button>) : <div className={styles.state}>{ar ? "لا توجد شهادة إصدار بعد." : "No release certificate has been recorded yet."}</div>}</>; }
