"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./document-change-control-workspace.module.css";

export type DocumentAcceptanceMode = "assurance_collection" | "assurance_review" | "acceptance_submission" | "acceptance_review";
type Check = { id: string; title: string; titleAr: string; detail: string; detailAr: string; passed: boolean };
type AssuranceRun = { id: string; collectedByUserId: string; evidenceReference: string; observationWindowMinutes: number; collectedAt: string; result: string; decision: string; passedChecks: number; checkCount: number; version: number; checks: Check[]; canReview?: boolean; reviewNote: string | null };
type Activation = { id: string; reference: string; verifiedAt: string | null };
type AcceptanceRun = { id: string; reference: string; preparedByUserId: string; preparedByName: string; reviewerName: string | null; evidenceReference: string; status: string; version: number; createdAt: string; approvedPolicyCount: number; approvedRetentionPlan: boolean; safetyScenarioCount: number; overdueLegalHoldCount: number; customerRecordsTouched: number; externalSystemsContacted: number; canReview?: boolean; reviewNote: string | null };
type Prerequisites = { approvedPolicyCount: number; requiredPolicyCount: number; approvedRetentionPlan: boolean; freshSafetyRehearsal: boolean; safetyScenarioCount: number; overdueLegalHoldCount: number; activeDocumentIncidentCount: number; activationWindowVerified: boolean; stabilityAssuranceVerified: boolean; prerequisitesReady: boolean; posture: { protectedStorageConfigured: boolean; privateScannerConfigured: boolean; allRuntimeControlsEnabled: boolean } };
type Data = { currentUserId: string; role: string; frameworkVersion?: string; eligibleActivations?: Activation[]; runs: Array<AssuranceRun | AcceptanceRun>; prerequisites?: Prerequisites; posture?: { allRuntimeControlsEnabled: boolean }; signals?: { activeIncidentCount: number; quarantinedDocuments: number; stuckScanJobs: number; failedScanJobs: number; failedDeletionJobs: number; legalHoldConflicts: number; failedRetentionRuns: number } };

const steps = [
  { mode: "assurance_collection", href: "/admin/document-assurance-collection", number: "01", label: ["Collect assurance", "جمع التأكيد"] },
  { mode: "assurance_review", href: "/admin/document-assurance-review", number: "02", label: ["Review stability", "مراجعة الاستقرار"] },
  { mode: "acceptance_submission", href: "/admin/lifecycle-acceptance-submission", number: "03", label: ["Submit acceptance", "إرسال القبول"] },
  { mode: "acceptance_review", href: "/admin/lifecycle-acceptance-review", number: "04", label: ["Decide acceptance", "قرار القبول"] },
] as const;

const config = {
  assurance_collection: { endpoint: "/api/admin/document-assurance-collection", eyebrow: ["POST-ACTIVATION EVIDENCE", "دليل ما بعد التفعيل"], title: ["Collect a complete stability snapshot.", "اجمع لقطة استقرار كاملة."], detail: ["Evaluate fourteen aggregate-only checks after the approved observation period, without reading a patient file or R2 object.", "قيّم أربعة عشر فحصاً مجمعاً بعد فترة الرصد دون قراءة ملف مريض أو كائن R2."] },
  assurance_review: { endpoint: "/api/admin/document-assurance-review", eyebrow: ["INDEPENDENT STABILITY DECISION", "قرار استقرار مستقل"], title: ["Verify the observed production posture.", "تحقق من وضع الإنتاج المرصود."], detail: ["A different operator revalidates every live check before declaring the activation stabilized.", "يعيد مشغل مختلف التحقق من كل فحص مباشر قبل إعلان استقرار التفعيل."] },
  acceptance_submission: { endpoint: "/api/admin/lifecycle-acceptance-submission", eyebrow: ["PRODUCTION EVIDENCE PACKAGE", "حزمة دليل الإنتاج"], title: ["Join every lifecycle control into one package.", "اجمع كل ضوابط دورة الحياة في حزمة واحدة."], detail: ["Submit current policy, legal-hold, runtime, activation, stability, scheduling, and synthetic storage evidence.", "أرسل أدلة السياسات والحجز والتشغيل والتفعيل والاستقرار والجدولة والتخزين الاصطناعي الحالية."] },
  acceptance_review: { endpoint: "/api/admin/lifecycle-acceptance-review", eyebrow: ["FINAL INDEPENDENT ACCEPTANCE", "القبول المستقل النهائي"], title: ["Make the evidence decision explicit.", "اجعل قرار الدليل صريحاً."], detail: ["The reviewer must differ from the preparer and the server revalidates the complete current posture before verification.", "يجب أن يختلف المراجع عن المُعد ويعيد الخادم التحقق من الوضع الحالي الكامل قبل الاعتماد."] },
} as const;

async function api(endpoint: string, init?: RequestInit) {
  const response = await fetch(endpoint, { cache: "no-store", credentials: "same-origin", ...init });
  const payload = await response.json().catch(() => ({})) as { data?: Data | object; error?: string; message?: string };
  if (response.status === 401) { window.location.assign(`/sign-in?redirect_url=${encodeURIComponent(location.pathname)}`); throw new Error("Authentication required"); }
  if (!response.ok || !payload.data) throw new Error(payload.message || payload.error || "Production acceptance workflow is unavailable");
  return payload.data;
}

function isAssurance(run: AssuranceRun | AcceptanceRun): run is AssuranceRun { return "decision" in run; }
function stamp(value: string | null, ar: boolean) { return value ? new Intl.DateTimeFormat(ar ? "ar-QA" : "en-QA", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Qatar" }).format(new Date(value)) : "—"; }
function words(value: string) { return value.replaceAll("_", " "); }

export default function DocumentAcceptanceWorkspace({ mode }: { mode: DocumentAcceptanceMode }) {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar"; const selectedConfig = config[mode];
  const [data, setData] = useState<Data | null>(null); const [selectedId, setSelectedId] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const copy = (value: readonly [string, string]) => ar ? value[1] : value[0];
  const load = useCallback(async () => { try { const next = await api(selectedConfig.endpoint) as Data; setData(next); setSelectedId((current) => next.runs.some((run) => run.id === current) ? current : next.runs[0]?.id ?? ""); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Production acceptance workflow is unavailable"); } finally { setLoading(false); } }, [selectedConfig.endpoint]);
  useEffect(() => { let active = true; queueMicrotask(() => { if (active) void load(); }); return () => { active = false; }; }, [load]);
  async function mutate(body: Record<string, unknown>) { setBusy(true); setError(""); setNotice(""); try { await api(selectedConfig.endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setNotice(ar ? "تم تسجيل الدليل وتحديث المرحلة التالية." : "Evidence recorded and the next stage refreshed."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The evidence action failed"); } finally { setBusy(false); } }
  function collect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void mutate({ clientRequestId: crypto.randomUUID(), activationWindowId: form.get("activationWindowId"), evidenceReference: form.get("evidenceReference"), observationWindowMinutes: Number(form.get("observationWindowMinutes")) }); }
  function submitAcceptance(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void mutate({ evidenceReference: form.get("evidenceReference"), scheduledMaintenanceObserved: form.get("scheduledMaintenanceObserved") === "on", isolatedStorageRehearsalPassed: form.get("isolatedStorageRehearsalPassed") === "on" }); }
  const selected = data?.runs.find((run) => run.id === selectedId); const readiness = data?.prerequisites?.prerequisitesReady ?? Boolean(data?.posture?.allRuntimeControlsEnabled); const step = steps.find((item) => item.mode === mode);
  return <main className={styles.shell} dir={ar ? "rtl" : "ltr"} id="main-content"><aside className={styles.side}><a href="/admin"><Image src="/brand/qivaya-logo-reversed.png" alt="Qivaya" width={142} height={53}/></a><p>{ar ? "ضمان وقبول الإنتاج" : "PRODUCTION ASSURANCE & ACCEPTANCE"}</p><nav aria-label={ar ? "مراحل الضمان والقبول" : "Assurance and acceptance stages"}>{steps.map((item) => <a key={item.mode} className={mode === item.mode ? styles.active : ""} href={item.href}><span>{item.number}</span>{copy(item.label)}</a>)}</nav><div className={styles.boundary}><b>{ar ? "دليل مجمع فقط" : "Aggregate evidence only"}</b><span>{ar ? "لا تقرأ هذه المساحات ملفات المرضى أو كائنات R2 ولا تغير ضوابط التشغيل." : "These workspaces read no patient file or R2 object and change no runtime control."}</span></div></aside><section className={styles.workspace}><header className={styles.top}><a href="/admin/document-change-observation">← {ar ? "التحقق من التفعيل" : "Activation verification"}</a><div><span data-ready={readiness}>{readiness ? (ar ? "الدليل جاهز" : "EVIDENCE READY") : (ar ? "مغلق افتراضياً" : "FAIL-CLOSED")}</span><button type="button" onClick={() => void load()}>{ar ? "تحديث" : "Refresh"}</button><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "EN" : "العربية"}</button></div></header><div className={styles.content}><section className={styles.hero}><span>{step?.number}</span><div><p>{copy(selectedConfig.eyebrow)}</p><h1>{copy(selectedConfig.title)}</h1><strong>{copy(selectedConfig.detail)}</strong></div><i data-ready={readiness}>{readiness ? "READY" : "GATED"}</i></section>{error ? <div className={styles.alert} data-kind="error" role="alert">{error}<button type="button" onClick={() => setError("")}>×</button></div> : null}{notice ? <div className={styles.alert} data-kind="success" role="status">✓ {notice}<button type="button" onClick={() => setNotice("")}>×</button></div> : null}
      {mode === "assurance_collection" ? <AssuranceCollection ar={ar} data={data} busy={busy} submit={collect}/> : null}{mode === "acceptance_submission" ? <AcceptanceSubmission ar={ar} data={data} busy={busy} submit={submitAcceptance}/> : null}{loading ? <div className={styles.state}>{ar ? "جارٍ قراءة سجل الدليل…" : "Reading the protected evidence register…"}</div> : null}{!loading && !data?.runs.length ? <div className={styles.empty}><b>✓</b><h2>{ar ? "لا يوجد دليل في هذه المرحلة" : "No evidence has reached this stage"}</h2><p>{ar ? "أكمل المرحلة السابقة لبدء السجل." : "Complete the preceding stage to begin this register."}</p></div> : null}{data?.runs.length ? <section className={styles.control}><aside className={styles.queue}><header><p>{ar ? "سجل المرحلة" : "STAGE REGISTER"}</p><b>{data.runs.length}</b></header>{data.runs.map((run) => { const state = isAssurance(run) ? run.decision : run.status; const reference = isAssurance(run) ? run.evidenceReference : run.reference; const created = isAssurance(run) ? run.collectedAt : run.createdAt; return <button type="button" key={run.id} data-selected={run.id === selected?.id} onClick={() => setSelectedId(run.id)}><i data-status={state}>{["stabilized","verified"].includes(state) ? "✓" : "•"}</i><span><b>{reference}</b><small>{words(state)} · {stamp(created, ar)}</small></span></button>; })}</aside><article className={styles.detail}>{selected ? <EvidenceDetail mode={mode} ar={ar} run={selected} busy={busy} mutate={mutate}/> : null}</article></section> : null}</div></section></main>;
}

function AssuranceCollection({ ar, data, busy, submit }: { ar: boolean; data: Data | null; busy: boolean; submit: (event: FormEvent<HTMLFormElement>) => void }) { return <section className={styles.formPanel}><div><p>{ar ? "لقطة استقرار" : "STABILITY SNAPSHOT"}</p><h2>{ar ? "14 فحصاً بعد فترة الرصد" : "14 checks after observation"}</h2><span>{ar ? "يجب أن يكون التفعيل متحققاً وأن تنقضي فترة الرصد المحددة." : "The activation must be verified and the selected observation period must have elapsed."}</span></div><form onSubmit={submit}><label>{ar ? "التفعيل المتحقق" : "Verified activation"}<select name="activationWindowId" required defaultValue=""><option value="" disabled>{ar ? "اختر التفعيل" : "Select activation"}</option>{data?.eligibleActivations?.map((item) => <option key={item.id} value={item.id}>{item.reference} · {stamp(item.verifiedAt, ar)}</option>)}</select></label><label>{ar ? "مرجع الدليل" : "Evidence reference"}<input name="evidenceReference" pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{5,159}" placeholder="DOC-STABILITY-2026-A1" required/></label><label>{ar ? "دقائق الرصد" : "Observation minutes"}<input name="observationWindowMinutes" type="number" min={15} max={240} defaultValue={30} required/></label><button disabled={busy || data?.role !== "platform_admin" || !data?.eligibleActivations?.length}>{busy ? (ar ? "جارٍ الجمع…" : "Collecting…") : (ar ? "جمع لقطة الاستقرار" : "Collect stability snapshot")}</button></form></section>; }

function AcceptanceSubmission({ ar, data, busy, submit }: { ar: boolean; data: Data | null; busy: boolean; submit: (event: FormEvent<HTMLFormElement>) => void }) { const p = data?.prerequisites; const summary = p ? `${p.approvedPolicyCount}/${p.requiredPolicyCount} policies · ${p.safetyScenarioCount}/22 safety · ${p.activeDocumentIncidentCount} incidents` : "—"; return <section className={styles.formPanel}><div><p>{ar ? "حزمة القبول" : "ACCEPTANCE PACKAGE"}</p><h2>{ar ? "تأكيد الدليل الحالي" : "Confirm current evidence"}</h2><span>{summary}</span></div><form onSubmit={submit}><label>{ar ? "مرجع الدليل المشفر" : "Coded evidence reference"}<input name="evidenceReference" pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{5,159}" placeholder="DLC-EVIDENCE-2026-A1" required/></label><label><input name="scheduledMaintenanceObserved" type="checkbox" required/>{ar ? "تمت مراقبة الصيانة المجدولة" : "Scheduled maintenance was observed"}</label><label><input name="isolatedStorageRehearsalPassed" type="checkbox" required/>{ar ? "نجحت بروفة التخزين الاصطناعية المعزولة" : "Isolated synthetic storage rehearsal passed"}</label><button disabled={busy || data?.role !== "platform_admin" || !p?.prerequisitesReady}>{busy ? (ar ? "جارٍ الإرسال…" : "Submitting…") : p?.prerequisitesReady ? (ar ? "إرسال للمراجعة" : "Submit for independent review") : (ar ? "أكمل المتطلبات" : "Complete prerequisites")}</button></form></section>; }

function EvidenceDetail({ mode, ar, run, busy, mutate }: { mode: DocumentAcceptanceMode; ar: boolean; run: AssuranceRun | AcceptanceRun; busy: boolean; mutate: (body: Record<string, unknown>) => Promise<void> }) {
  if (isAssurance(run)) return <><header><div><p>{run.evidenceReference}</p><h2>{words(run.decision)}</h2><span>{run.passedChecks}/{run.checkCount} {ar ? "فحوص ناجحة" : "checks passed"} · {run.observationWindowMinutes} min</span></div><em>v{run.version}</em></header><div className={styles.timeline}><h3>{ar ? "فحوص الاستقرار" : "Stability checks"}</h3>{run.checks.map((check) => <div key={check.id}><i>{check.passed ? "✓" : "!"}</i><span><b>{ar ? check.titleAr : check.title}</b><small>{ar ? check.detailAr : check.detail}</small></span></div>)}</div>{mode === "assurance_review" && run.decision === "pending" ? <div className={styles.actions}><button className={styles.secondary} type="button" disabled={busy || !run.canReview} onClick={() => void mutate({ runId: run.id, version: run.version, decision: "rejected", reviewNote: "Independent review found that the aggregate stability evidence requires remediation and recollection." })}>{ar ? "رفض الدليل" : "Reject evidence"}</button><button type="button" disabled={busy || !run.canReview || run.result !== "pass"} onClick={() => void mutate({ runId: run.id, version: run.version, decision: "stabilized", reviewNote: "Independently revalidated all stored and current aggregate stability checks." })}>{ar ? "توثيق الاستقرار" : "Verify stabilized"}</button></div> : null}</>;
  return <><header><div><p>{run.evidenceReference}</p><h2>{words(run.status)}</h2><span>{run.preparedByName} · {run.approvedPolicyCount}/5 policies · {run.safetyScenarioCount}/22 safety</span></div><em>v{run.version}</em></header><div className={styles.owners}><span><small>{ar ? "سجلات العملاء" : "CUSTOMER RECORDS"}</small><b>{run.customerRecordsTouched}</b></span><span><small>{ar ? "اتصالات خارجية" : "EXTERNAL CALLS"}</small><b>{run.externalSystemsContacted}</b></span><span><small>{ar ? "مراجعات حجز متأخرة" : "OVERDUE HOLDS"}</small><b>{run.overdueLegalHoldCount}</b></span></div>{mode === "acceptance_review" && run.status === "pending_review" ? <div className={styles.actions}><button className={styles.secondary} type="button" disabled={busy || !run.canReview} onClick={() => void mutate({ runId: run.id, version: run.version, action: "reject", note: "Independent review found that the lifecycle evidence package requires remediation and resubmission." })}>{ar ? "رفض الحزمة" : "Reject package"}</button><button type="button" disabled={busy || !run.canReview} onClick={() => void mutate({ runId: run.id, version: run.version, action: "verify", note: "Independently reviewed current policy, legal-hold, runtime, activation, stability, scheduling, and synthetic storage evidence." })}>{ar ? "توثيق القبول" : "Verify acceptance"}</button></div> : null}{run.status === "verified" ? <div className={styles.actions}><a href="/admin/document-release-preparation">{ar ? "متابعة إلى إعداد شهادة الإطلاق" : "Continue to release preparation"} →</a></div> : null}</>;
}
