"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "@/app/appointment-journey.module.css";

type Module = "api_clients" | "webhook_endpoints" | "partner_conformance" | "terminology_sets" | "patient_match_exceptions";
type RecordRow = Record<string, unknown>;
type Workspace = { records: RecordRow[]; notice: string };
const config = {
  api_clients: { path: "api-clients", en: "API client governance", ar: "حوكمة عملاء واجهة البرمجة" },
  webhook_endpoints: { path: "webhook-endpoints", en: "Webhook endpoint governance", ar: "حوكمة نقاط استقبال الأحداث" },
  partner_conformance: { path: "partner-conformance", en: "Partner conformance", ar: "مطابقة الشركاء" },
  terminology_sets: { path: "terminology-sets", en: "Terminology governance", ar: "حوكمة المصطلحات" },
  patient_match_exceptions: { path: "patient-match-exceptions", en: "Patient-match exceptions", ar: "استثناءات مطابقة المرضى" },
} as const;
const options = (values: string[]) => values.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>);
function name(row: RecordRow) { return String(row.clientReference ?? row.endpointReference ?? row.certificateReference ?? row.setReference ?? row.exceptionReference ?? "Record").replaceAll("_", " "); }
function details(row: RecordRow) { return [row.organizationReference, row.workloadClass, row.scopeProfile, row.credentialState, row.connectionReference, row.eventFamily, row.signatureProfile, row.verificationState, row.partnerReference, row.contractProfile, row.testBand, row.evidenceState, row.terminologySystem, row.clinicalDomain, row.reviewState, row.exceptionBand, row.sourceReference, row.ambiguityCode, row.riskBand, row.reviewDisposition].filter(Boolean).join(" · "); }

export default function IntegrationAssuranceWorkspace({ module }: { module: Module }) {
  const current = config[module], [locale, setLocale] = useReyatiLocale(), arabic = locale === "ar", [data, setData] = useState<Workspace | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), endpoint = `/api/admin/${current.path}`;
  const load = useCallback(async () => { setError(""); try { const response = await fetch(endpoint, { cache: "no-store" }), payload = await response.json().catch(() => ({})) as { data?: Workspace; message?: string }; if (!response.ok || !payload.data) throw Error(payload.message ?? "Unable to load records"); setData(payload.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unavailable"); } }, [endpoint]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function send(body: RecordRow) { setBusy(true); setError(""); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), payload = await response.json().catch(() => ({})) as { message?: string }; if (!response.ok) throw Error(payload.message ?? "Unable to save"); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save"); } finally { setBusy(false); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; await send({ action: "create", ...Object.fromEntries(new FormData(form).entries()) }); form.reset(); }
  return <main className={styles.shell} dir={arabic ? "rtl" : "ltr"}>
    <header className={styles.top}><a href="/admin"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya" /></a><button className={styles.lang} onClick={() => setLocale(arabic ? "en" : "ar")}>{arabic ? "EN" : "العربية"}</button></header>
    <section className={styles.hero}><span>INTEGRATION ASSURANCE</span><h1>{arabic ? current.ar : current.en}</h1><p>{arabic ? "أدلة ومراجعة بشرية مستقلة دون تشغيل أي اتصال خارجي." : "Evidence and independent human review without activating an external connection."}</p></section>
    <section className={styles.boundary}><b>{arabic ? "لا توجد آثار تشغيلية" : "No runtime side effects"}</b><span>{arabic ? "لا يتم إصدار بيانات اعتماد أو تشغيل استقبال أحداث أو نشر مصطلحات أو دمج سجلات مرضى." : "No credential issuance, webhook activation, partner certification, terminology publication, patient linking, or record merge."}</span></section>
    {error && <div className={styles.error}>{error}<button onClick={() => void load()}>{arabic ? "إعادة المحاولة" : "Retry"}</button></div>}
    <div className={styles.grid}><form className={styles.panel} onSubmit={create}><div className={styles.panelHead}><h2>{arabic ? "إضافة مسودة أدلة" : "Add evidence draft"}</h2></div>
      {module === "api_clients" && <><label>Client reference<input name="clientReference" required maxLength={160} /></label><label>Organization reference<input name="organizationReference" required maxLength={160} /></label><label>Workload<select name="workloadClass">{options(["server_to_server", "partner_console", "scheduled_batch"])}</select></label><label>Scope profile<select name="scopeProfile">{options(["directory_read", "appointments_limited", "results_limited", "fulfilment_limited"])}</select></label><label>Credential state<select name="credentialState">{options(["not_requested", "design_review", "issuance_blocked"])}</select></label></>}
      {module === "webhook_endpoints" && <><label>Endpoint reference<input name="endpointReference" required maxLength={160} /></label><label>Connection reference<input name="connectionReference" required maxLength={160} /></label><label>Event family<select name="eventFamily">{options(["appointment_status", "payment_status", "fulfilment_status", "result_status", "notification_status"])}</select></label><label>Signature profile<select name="signatureProfile">{options(["hmac_sha256", "asymmetric_jws", "mtls_bound"])}</select></label><label>Verification<select name="verificationState">{options(["not_tested", "synthetic_verified", "exceptions_present"])}</select></label></>}
      {module === "partner_conformance" && <><label>Certificate reference<input name="certificateReference" required maxLength={160} /></label><label>Partner reference<input name="partnerReference" required maxLength={160} /></label><label>Contract profile<select name="contractProfile">{options(["fhir_r4_profile", "rest_json_v1", "hl7_v2_profile", "dicomweb_profile"])}</select></label><label>Test band<select name="testBand">{options(["schema", "contract", "security_and_replay", "end_to_end_sandbox"])}</select></label><label>Evidence<select name="evidenceState">{options(["not_started", "partial", "complete_not_approved"])}</select></label></>}
      {module === "terminology_sets" && <><label>Set reference<input name="setReference" required maxLength={160} /></label><label>Terminology system<select name="terminologySystem">{options(["snomed_ct", "loinc", "icd_10", "ucum", "local_bounded"])}</select></label><label>Clinical domain<select name="clinicalDomain">{options(["conditions", "observations", "medications", "procedures", "diagnostics"])}</select></label><label>Review state<select name="reviewState">{options(["draft", "clinical_review", "informatics_review"])}</select></label><label>Exceptions<select name="exceptionBand">{options(["none", "bounded", "unresolved"])}</select></label></>}
      {module === "patient_match_exceptions" && <><label>Exception reference<input name="exceptionReference" required maxLength={160} /></label><label>Source reference<input name="sourceReference" required maxLength={160} /></label><label>Ambiguity<select name="ambiguityCode">{options(["multiple_candidates", "insufficient_identifiers", "conflicting_identifiers", "source_duplicate", "manual_hold"])}</select></label><label>Risk band<select name="riskBand">{options(["low", "medium", "high", "critical"])}</select></label><label>Disposition<select name="reviewDisposition">{options(["queued", "needs_source_confirmation", "manual_no_match", "manual_link_evidence"])}</select></label></>}
      <button disabled={busy}>{busy ? (arabic ? "جارٍ الحفظ…" : "Saving…") : (arabic ? "حفظ المسودة" : "Save draft")}</button>
    </form><section className={styles.panel}><div className={styles.panelHead}><h2>{arabic ? current.ar : current.en}</h2><span>{data?.records.length ?? 0}</span></div><p>{data?.notice}</p>
      {!data?.records.length ? <div className={styles.empty}><b>{arabic ? "لا توجد سجلات بعد" : "No records yet"}</b><span>{arabic ? "ستظهر مسودات الأدلة هنا." : "Evidence drafts will appear here."}</span></div> : <div className={styles.list}>{data.records.map((row) => <article key={String(row.id)}><div className={styles.cardTop}><b>{name(row)}</b><span>{String(row.status)}</span></div><p>{details(row)}</p><div>{row.status === "draft" && <button disabled={busy} onClick={() => void send({ action: "submit", recordId: row.id, version: row.version })}>{arabic ? "إرسال للمراجعة" : "Submit for review"}</button>}{row.status === "submitted" && <><button disabled={busy} onClick={() => void send({ action: "review", decisionCode: "evidence_reviewed", recordId: row.id, version: row.version })}>{arabic ? "اعتماد الأدلة" : "Review evidence"}</button><button disabled={busy} onClick={() => void send({ action: "review", decisionCode: "returned", recordId: row.id, version: row.version })}>{arabic ? "إعادة" : "Return"}</button></>}</div></article>)}</div>}
    </section></div>
  </main>;
}
