"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "@/app/tenant-configuration.module.css";

type Membership = { organizationId: string; organizationName: string; role: string };
type Configuration = { id: string; organizationId: string; locale: string; timezone: string; bookingHorizonDays: number; cancellationWindowReference: string; reminderPolicyReference: string; supportContactAlias: string; facilityDisplayDefault: string; moduleVisibilityRequests: string[]; rationale: string; status: string; version: number; preparedByUserId: string; reviewedByUserId: string | null; reviewReasonCode: string | null; independentReview?: boolean; updatedAt: string; runtimeApplied: false };
type ProviderData = { memberships: Membership[]; configurations: Configuration[]; options: { locales: string[]; timezones: string[]; facilityDisplayDefaults: string[]; modules: string[] }; boundaries: Record<string, boolean>; approvalEffect: string };
type AdminData = { role: string; visibility: string; metrics: Record<string, number>; configurations: Configuration[]; rehearsals: Array<{ id: string; result: string; scenarioCount: number; executedAt: string }>; boundaries: Record<string, boolean>; approvalEffect: string };
type Draft = { organizationId: string; locale: string; timezone: string; bookingHorizonDays: number; cancellationWindowReference: string; reminderPolicyReference: string; supportContactAlias: string; facilityDisplayDefault: string; moduleVisibilityRequests: string[]; rationale: string };
const blank = (): Draft => ({ organizationId: "", locale: "bilingual", timezone: "Asia/Qatar", bookingHorizonDays: 90, cancellationWindowReference: "standard_cancellation_v1", reminderPolicyReference: "standard_reminders_v1", supportContactAlias: "organization.support", facilityDisplayDefault: "alphabetical", moduleVisibilityRequests: ["appointments", "facilities"], rationale: "Align the organization workspace with the approved operating model." });

export default function TenantConfigurationWorkspace({ mode }: { mode: "provider" | "admin" }) {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar", endpoint = mode === "provider" ? "/api/provider/organization-settings" : "/api/admin/tenant-configuration";
  const [providerData, setProviderData] = useState<ProviderData | null>(null), [adminData, setAdminData] = useState<AdminData | null>(null), [draft, setDraft] = useState<Draft>(blank), [editing, setEditing] = useState<{ id: string; version: number } | null>(null);
  const [reasons, setReasons] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { setError(""); try { const response = await fetch(endpoint, { cache: "no-store" }), payload = await response.json(); if (!response.ok) throw new Error(payload.message ?? payload.error ?? "Unable to load the workspace"); if (mode === "provider") { const data = payload.data as ProviderData; setProviderData(data); setDraft((value) => ({ ...value, organizationId: value.organizationId || data.memberships[0]?.organizationId || "" })); } else setAdminData(payload.data as AdminData); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load the workspace"); } }, [endpoint, mode]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function action(body: Record<string, unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), payload = await response.json(); if (!response.ok) throw new Error(payload.message ?? payload.error ?? "Action could not be completed"); setMessage(success); setEditing(null); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Action could not be completed"); } finally { setBusy(false); } }
  async function save(event: FormEvent) { event.preventDefault(); await action({ action: "save_draft", ...draft, configurationId: editing?.id, version: editing?.version }, ar ? "حُفظت مسودة الإعداد كدليل خاص." : "Configuration draft saved as private evidence."); }
  const rows = useMemo(() => providerData?.configurations ?? adminData?.configurations ?? [], [providerData, adminData]), isAuditor = adminData?.role === "security_auditor";
  const statusLabel = (status: string) => ar ? ({ draft: "مسودة", pending_review: "قيد المراجعة", approved: "دليل معتمد", returned: "مُعاد", retired: "متقاعد" }[status] ?? status) : status.replaceAll("_", " ");
  const startEdit = (item: Configuration) => { setEditing({ id: item.id, version: item.version }); setDraft({ organizationId: item.organizationId, locale: item.locale, timezone: item.timezone, bookingHorizonDays: item.bookingHorizonDays, cancellationWindowReference: item.cancellationWindowReference, reminderPolicyReference: item.reminderPolicyReference, supportContactAlias: item.supportContactAlias, facilityDisplayDefault: item.facilityDisplayDefault, moduleVisibilityRequests: item.moduleVisibilityRequests, rationale: item.rationale }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const aggregate = useMemo(() => adminData?.metrics ?? { total: rows.length, pendingReview: rows.filter((item) => item.status === "pending_review").length, approvedEvidence: rows.filter((item) => item.status === "approved").length }, [adminData, rows]);
  const options = providerData?.options;

  return <main className={styles.shell} dir={ar ? "rtl" : "ltr"}>
    <aside className={styles.sidebar}><a className={styles.logo} href={mode === "provider" ? "/provider" : "/admin"}><img src="/brand/qivaya-logo-reversed.png" alt="Qivaya" /></a><span className={styles.sideEyebrow}>{mode === "provider" ? (ar ? "مساحة المؤسسة" : "Organization workspace") : (ar ? "حوكمة المنصة" : "Platform governance")}</span><nav aria-label={ar ? "التنقل" : "Workspace navigation"}><a href={mode === "provider" ? "/provider" : "/admin"}>{ar ? "نظرة عامة" : "Overview"}</a><a className={styles.active} aria-current="page" href={mode === "provider" ? "/provider/organization-settings" : "/admin/tenant-configuration"}>{ar ? "إعدادات المؤسسة" : "Tenant configuration"}</a><a href={mode === "provider" ? "/provider/settings" : "/admin/audit"}>{mode === "provider" ? (ar ? "إعدادات الحساب" : "Account settings") : (ar ? "سجل التدقيق" : "Audit ledger")}</a></nav><div className={styles.sideNote}><b>{ar ? "دليل فقط" : "Evidence only"}</b><span>{ar ? "لا تغيير في التشغيل أو الخصائص أو السياسات." : "No runtime, feature, or policy changes."}</span></div></aside>
    <div className={styles.workspace}><header className={styles.topbar}><div><span className={styles.eyebrow}>{ar ? "إعدادات محكومة ومحددة النطاق" : "Governed, tenant-scoped settings"}</span><h1>{mode === "provider" ? (ar ? "تفضيلات المؤسسة" : "Organization preferences") : (ar ? "حوكمة إعدادات المؤسسات" : "Tenant configuration governance")}</h1><p>{mode === "provider" ? (ar ? "اقترح تفضيلات تشغيلية للمراجعة المستقلة دون تطبيقها على المنصة." : "Propose operational preferences for independent review without applying them to the platform.") : (ar ? "راجع أدلة الإعدادات مع فصل واضح بين الاعتماد والتطبيق." : "Review configuration evidence with a hard separation between approval and application.")}</p></div><button className={styles.locale} type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></header>
      <section className={styles.boundary}><span aria-hidden="true">✓</span><div><b>{ar ? "الاعتماد لا يطبّق الإعداد" : "Approval does not apply configuration"}</b><p>{ar ? "لا تغيّر هذه الوحدة خصائص التشغيل أو الرسوم أو السياسات أو متغيرات البيئة أو الأسرار ولا تتصل بنظام خارجي." : "This module never changes runtime flags, fees, real policies, environment variables, secrets, or an external system."}</p></div></section>
      {message && <div className={styles.success} role="status">{message}</div>}{error && <div className={styles.error} role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>{ar ? "إعادة المحاولة" : "Try again"}</button></div>}
      {!providerData && !adminData && !error ? <div className={styles.loading} aria-live="polite"><span />{ar ? "جارٍ تحميل مساحة الإعدادات الخاصة…" : "Loading the private configuration workspace…"}</div> : <>
        <section className={styles.metrics} aria-label={ar ? "مقاييس مجمعة" : "Aggregate metrics"}>{Object.entries(aggregate).map(([key, value]) => <article key={key}><b>{value}</b><span>{key.replaceAll(/([A-Z])/g, " $1")}</span></article>)}</section>
        {mode === "provider" && providerData && <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{editing ? (ar ? "نسخة منقحة" : "Revision") : (ar ? "مسودة جديدة" : "New draft")}</span><h2>{ar ? "اقتراح إعدادات المؤسسة" : "Propose organization settings"}</h2></div><span className={styles.role}>organization_owner / admin</span></div><form className={styles.form} onSubmit={save}>
          <label>{ar ? "المؤسسة" : "Organization"}<select value={draft.organizationId} onChange={(e) => setDraft({ ...draft, organizationId: e.target.value })}>{providerData.memberships.map((item) => <option key={item.organizationId} value={item.organizationId}>{item.organizationName}</option>)}</select></label>
          <label>{ar ? "اللغة الافتراضية" : "Default locale"}<select value={draft.locale} onChange={(e) => setDraft({ ...draft, locale: e.target.value })}>{options?.locales.map((item) => <option key={item}>{item}</option>)}</select></label>
          <label>{ar ? "المنطقة الزمنية" : "Timezone"}<select value={draft.timezone} onChange={(e) => setDraft({ ...draft, timezone: e.target.value })}>{options?.timezones.map((item) => <option key={item}>{item}</option>)}</select></label>
          <label>{ar ? "أفق الحجز بالأيام" : "Booking horizon (days)"}<input type="number" min="1" max="365" required value={draft.bookingHorizonDays} onChange={(e) => setDraft({ ...draft, bookingHorizonDays: Number(e.target.value) })} /></label>
          <label>{ar ? "مرجع نافذة الإلغاء" : "Cancellation-window reference"}<input required minLength={2} maxLength={96} value={draft.cancellationWindowReference} onChange={(e) => setDraft({ ...draft, cancellationWindowReference: e.target.value })} /></label>
          <label>{ar ? "مرجع سياسة التذكير" : "Reminder-policy reference"}<input required minLength={2} maxLength={96} value={draft.reminderPolicyReference} onChange={(e) => setDraft({ ...draft, reminderPolicyReference: e.target.value })} /></label>
          <label>{ar ? "اسم جهة الدعم" : "Support contact alias"}<input required minLength={2} maxLength={80} value={draft.supportContactAlias} onChange={(e) => setDraft({ ...draft, supportContactAlias: e.target.value })} /></label>
          <label>{ar ? "عرض المرافق الافتراضي" : "Facility display default"}<select value={draft.facilityDisplayDefault} onChange={(e) => setDraft({ ...draft, facilityDisplayDefault: e.target.value })}>{options?.facilityDisplayDefaults.map((item) => <option key={item}>{item}</option>)}</select></label>
          <fieldset className={styles.modules}><legend>{ar ? "طلبات إظهار الوحدات" : "Module visibility requests"}</legend>{options?.modules.map((item) => <label key={item}><input type="checkbox" checked={draft.moduleVisibilityRequests.includes(item)} onChange={(e) => setDraft({ ...draft, moduleVisibilityRequests: e.target.checked ? [...draft.moduleVisibilityRequests, item] : draft.moduleVisibilityRequests.filter((value) => value !== item) })} />{item.replaceAll("_", " ")}</label>)}</fieldset>
          <label className={styles.wide}>{ar ? "المبرر" : "Rationale"}<textarea required minLength={12} maxLength={1200} value={draft.rationale} onChange={(e) => setDraft({ ...draft, rationale: e.target.value })} /></label>
          <div className={styles.actions}>{editing && <button className={styles.secondary} type="button" onClick={() => { setEditing(null); setDraft({ ...blank(), organizationId: providerData.memberships[0]?.organizationId ?? "" }); }}>{ar ? "إلغاء" : "Cancel"}</button>}<button className={styles.primary} disabled={busy} type="submit">{editing ? (ar ? "حفظ النسخة" : "Save revision") : (ar ? "حفظ المسودة" : "Save draft")}</button></div>
        </form></section>}
        <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "دورة حياة صريحة" : "Explicit evidence lifecycle"}</span><h2>{ar ? "سجل الإعدادات" : "Configuration register"}</h2></div>{mode === "admin" && <span className={styles.role}>{adminData?.visibility}</span>}</div>
          {isAuditor ? <div className={styles.empty}><b>{ar ? "عرض المراجع مجمّع فقط" : "Auditor view is aggregate only"}</b><p>{ar ? "قيم إعدادات المؤسسات غير معروضة لهذا الدور." : "Tenant configuration values are hidden from this role."}</p></div> : !rows.length ? <div className={styles.empty}><b>{ar ? "لا توجد إعدادات بعد" : "No configurations yet"}</b><p>{ar ? "ستظهر المسودات والقرارات هنا." : "Drafts and review decisions will appear here."}</p></div> : <div className={styles.cards}>{rows.map((item) => { const reason = reasons[item.id] ?? ""; return <article className={styles.card} key={item.id}><header><div><span className={styles.eyebrow}>{item.locale} · {item.timezone}</span><h3>{ar ? "إعداد المؤسسة" : "Tenant configuration"} · v{item.version}</h3></div><span className={`${styles.status} ${styles[item.status]}`}>{statusLabel(item.status)}</span></header><dl><div><dt>{ar ? "أفق الحجز" : "Booking horizon"}</dt><dd>{item.bookingHorizonDays} {ar ? "يوم" : "days"}</dd></div><div><dt>{ar ? "عرض المرافق" : "Facility display"}</dt><dd>{item.facilityDisplayDefault}</dd></div><div><dt>{ar ? "مرجع الإلغاء" : "Cancellation reference"}</dt><dd>{item.cancellationWindowReference}</dd></div><div><dt>{ar ? "مرجع التذكير" : "Reminder reference"}</dt><dd>{item.reminderPolicyReference}</dd></div><div><dt>{ar ? "جهة الدعم" : "Support alias"}</dt><dd>{item.supportContactAlias}</dd></div><div><dt>{ar ? "الوحدات المطلوبة" : "Requested modules"}</dt><dd>{item.moduleVisibilityRequests.join(", ") || "—"}</dd></div></dl><p className={styles.rationale}>{item.rationale}</p><div className={styles.meta}><span>{ar ? "مطبق في التشغيل" : "Runtime applied"}: 0</span><span>{new Date(item.updatedAt).toLocaleString()}</span>{mode === "admin" && <span>{ar ? "مراجعة مستقلة" : "Independent review"}: {item.independentReview ? "✓" : "—"}</span>}</div>
            <div className={styles.actions}>{mode === "provider" && ["draft", "returned"].includes(item.status) && <><button className={styles.secondary} type="button" disabled={busy} onClick={() => startEdit(item)}>{ar ? "تعديل" : "Edit"}</button><button className={styles.primary} type="button" disabled={busy} onClick={() => void action({ action: "submit", configurationId: item.id, version: item.version }, ar ? "أُرسلت للمراجعة المستقلة." : "Submitted for independent review.")}>{ar ? "إرسال للمراجعة" : "Submit for review"}</button></>}{mode === "admin" && item.status === "pending_review" && <><input className={styles.reason} aria-label={ar ? "رمز السبب" : "Reason code"} placeholder="configuration_reviewed" value={reason} onChange={(e) => setReasons({ ...reasons, [item.id]: e.target.value })} /><button className={styles.primary} type="button" disabled={busy} onClick={() => void action({ action: "review", decision: "approve", reasonCode: reason || "configuration_reviewed", configurationId: item.id, version: item.version }, ar ? "اعتُمد الدليل فقط؛ لم يُطبق شيء." : "Evidence approved; nothing was applied.")}>{ar ? "اعتماد كدليل" : "Approve evidence"}</button><button className={styles.secondary} type="button" disabled={busy || !reason} onClick={() => void action({ action: "review", decision: "return", reasonCode: reason, configurationId: item.id, version: item.version }, ar ? "أُعيدت للمؤسسة." : "Returned to the organization.")}>{ar ? "إعادة" : "Return"}</button></>}{mode === "admin" && item.status === "approved" && <><input className={styles.reason} aria-label={ar ? "رمز التقاعد" : "Retirement reason"} placeholder="superseded" value={reason} onChange={(e) => setReasons({ ...reasons, [item.id]: e.target.value })} /><button className={styles.secondary} type="button" disabled={busy || !reason} onClick={() => void action({ action: "retire", reasonCode: reason, configurationId: item.id, version: item.version }, ar ? "تقاعد الدليل دون تغيير التشغيل." : "Evidence retired without a runtime change.")}>{ar ? "تقاعد الدليل" : "Retire evidence"}</button></>}</div>
          </article>; })}</div>}
        </section>
        {mode === "admin" && <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "ضمان اصطناعي" : "Synthetic assurance"}</span><h2>{ar ? "اختبار بلا آثار جانبية" : "Zero-side-effect rehearsal"}</h2><p>{ar ? "خمسة وعشرون سيناريو تتحقق من الحدود والنطاق والإصدارات دون تطبيق إعداد." : "Twenty-five scenarios verify boundaries, scope, and versioning without applying configuration."}</p></div><button className={styles.primary} disabled={busy} type="button" onClick={() => void action({ action: "run_rehearsal" }, ar ? "اكتمل الاختبار دون آثار تشغيلية." : "Rehearsal completed with zero operational side effects.")}>{ar ? "تشغيل الاختبار" : "Run rehearsal"}</button></div></section>}
      </>}
    </div>
  </main>;
}
