"use client";

import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./saved-care.module.css";

type Fact = { id:string;name:string;specialty:string;gender:string|null;languages:string[];yearsExperience:number|null;modes:string[];facilities:string[];areas:string[];feeRangeQar:{minimum:number;maximum:number}|null;source:string };
type Favourite = { id:string;version:number;currentlyPublished:boolean;provider:Fact|null };
type Comparison = { id:string;version:number;providers:Fact[];staleProviderCount:number };
type Workspace = { favourites:Favourite[];comparison:Comparison|null;catalog:Fact[];guidance:string };

export default function SavedCarePage(){
  const [lang,setLang]=useReyatiLocale(), ar=lang==="ar";
  const [data,setData]=useState<Workspace|null>(null),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const load=useCallback(async(signal?:AbortSignal)=>{try{setError("");const response=await fetch("/api/saved-care",{cache:"no-store",signal});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"unavailable");setData(payload.data)}catch(reason){if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(ar?"تعذر تحميل الرعاية المحفوظة.":"Saved care could not be loaded.")}},[ar]);
  useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)void load(controller.signal)});return()=>controller.abort()},[load]);
  async function act(body:Record<string,unknown>,success:string){setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/saved-care",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.error);setMessage(success);setSelected([]);await load()}catch(reason){setError(reason instanceof Error?reason.message:(ar?"تعذر إكمال الطلب.":"The request could not be completed."))}finally{setBusy(false)}}
  const savedIds=new Set(data?.favourites.map(item=>item.provider?.id).filter(Boolean));
  const money=(fact:Fact)=>fact.feeRangeQar?fact.feeRangeQar.minimum===fact.feeRangeQar.maximum?`${fact.feeRangeQar.minimum} QAR`:`${fact.feeRangeQar.minimum}–${fact.feeRangeQar.maximum} QAR`:(ar?"غير منشور":"Not published");
  const choose=(providerId:string)=>setSelected(current=>current.includes(providerId)?current.filter(id=>id!==providerId):current.length<3?[...current,providerId]:current);
  return <main className={styles.shell} dir={ar?"rtl":"ltr"}>
    <header className={styles.top}><a href="/"><img src="/brand/reyati-logo-primary.svg" alt="Reyati"/></a><nav><a href="/providers">{ar?"استكشاف مقدمي الرعاية":"Find care"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a><button type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></nav></header>
    <section className={styles.hero}><span className={styles.eyebrow}>{ar?"اختيارك، بشفافية":"Your choice, transparently"}</span><h1>{ar?"الرعاية المحفوظة ومقارنة مقدمي الرعاية":"Saved care and provider comparison"}</h1><p>{ar?"احفظ مقدمي الرعاية الموثقين وقارن بين اثنين أو ثلاثة باستخدام حقائق منشورة ومتسقة فقط.":"Save verified providers and compare two or three using consistent, currently published facts only."}</p></section>
    <div className={styles.content}><div className={styles.notice}><b>{ar?"لا يوجد ترتيب للجودة السريرية":"No clinical-quality ranking"}</b><br/>{ar?"لا توصي ريّاتي بمقدم رعاية هنا، ولا يؤثر المحتوى المدفوع في المقارنة، ولا يعرف مقدم الرعاية من قام بحفظ ملفه.":"Reyati does not recommend a provider here, sponsored content cannot influence comparison, and providers cannot see who saved their profile."}</div>
      {message&&<p className={styles.status} role="status">{message}</p>}{error&&<p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
      <section className={styles.panel}><h2>{ar?"مقدمو الرعاية المحفوظون":"Saved providers"}</h2><p className={styles.muted}>{ar?"تظل القائمة خاصة بحسابك.":"This list remains private to your account."}</p>
        {!data?<div className={styles.empty}>{ar?"جارٍ التحميل…":"Loading…"}</div>:data.favourites.length===0?<div className={styles.empty}>{ar?"لم تحفظ أي مقدم رعاية بعد.":"You have not saved a provider yet."}</div>:<div className={styles.grid}>{data.favourites.map(item=><article className={styles.card} key={item.id}><h3>{item.provider?.name??(ar?"ملف لم يعد منشوراً":"Profile no longer published")}</h3><p>{item.provider?.specialty??(ar?"غير متاح للمقارنة":"Unavailable for comparison")}</p>{item.provider&&<div className={styles.facts}><span>{item.provider.facilities.join(", ")||"—"}</span><span>{money(item.provider)}</span></div>}<button className={styles.secondary} type="button" disabled={busy} onClick={()=>void act({action:"remove_provider",id:item.id,version:item.version},ar?"تمت الإزالة.":"Removed from saved care.")}>{ar?"إزالة":"Remove"}</button></article>)}</div>}
      </section>
      <section className={styles.panel}><h2>{ar?"اختر للمقارنة":"Choose providers to compare"}</h2><p className={styles.muted}>{ar?"اختر اثنين أو ثلاثة. الحقول متطابقة ولا يوجد ترتيب تلقائي.":"Select two or three. Fields are identical and no automatic ranking is applied."}</p>
        <div className={styles.grid}>{data?.catalog.map(provider=><article className={styles.card} key={provider.id}><h3>{provider.name}</h3><p>{provider.specialty}</p><div className={styles.facts}><span>{provider.languages.join(", ")||"—"}</span><span>{money(provider)}</span><span>{provider.modes.join(" · ")}</span></div><div className={styles.actions}><button className={styles.secondary} type="button" disabled={busy||savedIds.has(provider.id)} onClick={()=>void act({action:"save_provider",providerId:provider.id},ar?"تم الحفظ بشكل خاص.":"Provider saved privately.")}>{savedIds.has(provider.id)?(ar?"محفوظ":"Saved"):(ar?"حفظ":"Save")}</button><label><input type="checkbox" checked={selected.includes(provider.id)} onChange={()=>choose(provider.id)} disabled={!selected.includes(provider.id)&&selected.length>=3}/> {ar?"مقارنة":"Compare"}</label></div></article>)}</div>
        <div className={styles.actions} style={{marginTop:18}}><button className={styles.primary} type="button" disabled={busy||selected.length<2} onClick={()=>void act({action:"create_comparison",providerIds:selected,locale:lang},ar?"تم إنشاء المقارنة.":"Comparison created.")}>{ar?`مقارنة (${selected.length})`:`Compare (${selected.length})`}</button><span className={styles.muted}>{ar?"الحد الأقصى 3":"Maximum 3"}</span></div>
      </section>
      <section className={styles.panel}><h2>{ar?"المقارنة الحالية":"Current comparison"}</h2>{!data?.comparison?<div className={styles.empty}>{ar?"اختر مقدمين على الأقل لبدء مقارنة.":"Choose at least two providers to start a comparison."}</div>:<><div className={styles.compare}>{data.comparison.providers.map(provider=><article className={styles.column} key={provider.id}><h3>{provider.name}</h3><p>{provider.specialty}</p><dl><div><dt>{ar?"الخبرة المنشورة":"Published experience"}</dt><dd>{provider.yearsExperience??"—"}</dd></div><div><dt>{ar?"اللغات":"Languages"}</dt><dd>{provider.languages.join(", ")||"—"}</dd></div><div><dt>{ar?"طرق الزيارة":"Visit modes"}</dt><dd>{provider.modes.join(", ")}</dd></div><div><dt>{ar?"المرافق":"Facilities"}</dt><dd>{provider.facilities.join(", ")||"—"}</dd></div><div><dt>{ar?"الرسوم المنشورة":"Published fees"}</dt><dd>{money(provider)}</dd></div></dl><a className={styles.primary} href={`/providers?providerId=${encodeURIComponent(provider.id)}`}>{ar?"عرض والحجز":"View and book"}</a></article>)}</div><p className={styles.muted}>{data.guidance}</p><button className={styles.secondary} type="button" disabled={busy} onClick={()=>void act({action:"archive_comparison",id:data.comparison!.id,version:data.comparison!.version},ar?"تم إغلاق المقارنة.":"Comparison closed.")}>{ar?"إغلاق المقارنة":"Close comparison"}</button></>}
      </section>
    </div>
  </main>
}
