"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./notification-preferences.module.css";

type Category = "appointment" | "medication" | "follow_up" | "account_security" | "support_service" | "marketing";
type Channel = "in_app" | "email" | "sms" | "push";
type Preference = { category: Category; channel: Channel; enabled: boolean; mandatory: boolean; mandatoryReasonCode: string | null; version: number; updatedAt: string };
type Workspace = {
  profile: { preferredLocale: "en" | "ar"; timezone: string; quietHoursEnabled: boolean; quietHoursStart: string; quietHoursEnd: string; version: number };
  preferences: Preference[];
  history: Array<{ id: string; action: string; category: Category | null; channel: Channel | null; nextEnabled: boolean | null; occurredAt: string }>;
  boundaries: { actualDelivery: boolean };
  delivery: {
    channels: Record<Channel, boolean>;
    email: {
      contact: { email: string; status: string; independentlyVerified: boolean } | null;
      masterEnabled: boolean;
      activity: Array<{ id: string; templateId: string; status: string; reason: string | null; createdAt: string; sentAt: string | null }>;
    };
  };
  guidance: string;
};

const categories: Category[] = ["appointment", "medication", "follow_up", "account_security", "support_service", "marketing"];
const channels: Channel[] = ["in_app", "email", "sms", "push"];
const labels = {
  appointment: { en: "Appointments", ar: "المواعيد", textEn: "Bookings, changes and reminders", textAr: "الحجوزات والتغييرات والتذكيرات", icon: "01" },
  medication: { en: "Medication", ar: "الأدوية", textEn: "Reminder preferences you explicitly choose", textAr: "تفضيلات التذكير التي تختارها بوضوح", icon: "02" },
  follow_up: { en: "Follow-up", ar: "المتابعة", textEn: "Care follow-up notices", textAr: "إشعارات متابعة الرعاية", icon: "03" },
  account_security: { en: "Account & security", ar: "الحساب والأمان", textEn: "Essential account and security activity", textAr: "نشاط الحساب والأمان الأساسي", icon: "04" },
  support_service: { en: "Support & service", ar: "الدعم والخدمة", textEn: "Responses and service updates", textAr: "الردود وتحديثات الخدمة", icon: "05" },
  marketing: { en: "Marketing", ar: "التسويق", textEn: "Optional news and offers", textAr: "أخبار وعروض اختيارية", icon: "06" },
} as const;
const channelLabels = { in_app: { en: "In app", ar: "داخل التطبيق" }, email: { en: "Email", ar: "البريد الإلكتروني" }, sms: { en: "SMS", ar: "رسائل نصية" }, push: { en: "Push", ar: "إشعارات فورية" } } as const;

export default function NotificationPreferencesPage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Workspace | null>(null), [busyKey, setBusyKey] = useState(""), [savingProfile, setSavingProfile] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [settings, setSettings] = useState({ preferredLocale: "en", timezone: "Asia/Qatar", quietHoursEnabled: false, quietHoursStart: "22:00", quietHoursEnd: "07:00" });
  const load = useCallback(async () => { try { const response = await fetch("/api/notification-preferences", { cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setData(payload.data); setSettings(payload.data.profile); setError(""); } catch { setError(ar ? "تعذر تحميل تفضيلاتك. حاول مرة أخرى." : "Your preferences could not be loaded. Please try again."); } }, [ar]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const byKey = useMemo(() => new Map(data?.preferences.map((item) => [`${item.category}:${item.channel}`, item]) ?? []), [data]);
  async function mutate(body: Record<string, unknown>, key: string, success: string) { setBusyKey(key); setError(""); setMessage(""); try { const response = await fetch("/api/notification-preferences", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); await load(); setMessage(success); } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? "تعذر حفظ التغيير." : "The change could not be saved.")); } finally { setBusyKey(""); } }
  function toggle(preference: Preference) { if (preference.mandatory) return; void mutate({ action: "update_preference", category: preference.category, channel: preference.channel, enabled: !preference.enabled, version: preference.version }, `${preference.category}:${preference.channel}`, ar ? "تم حفظ اختيارك." : "Your choice was saved."); }
  function toggleEmailMaster() { if (!data?.delivery.email.contact?.independentlyVerified) return; void mutate({ action: "update_email_master", enabled: !data.delivery.email.masterEnabled }, "email-master", ar ? "تم تحديث تسليم البريد." : "Email delivery preference updated."); }
  async function saveSettings() { if (!data) return; setSavingProfile(true); await mutate({ action: "update_profile", version: data.profile.version, ...settings }, "profile", ar ? "تم حفظ إعدادات اللغة والوقت الهادئ." : "Language and quiet-time settings saved."); setSavingProfile(false); }
  return <main className={`${styles.shell} trust-center-shell notification-preferences-experience`} dir={ar ? "rtl" : "ltr"}>
    <header className={styles.top}><a href="/"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya" /></a><nav aria-label={ar ? "التنقل الرئيسي" : "Primary navigation"}><a href="/notifications">{ar ? "الإشعارات" : "Notifications"}</a><a href="/settings/communications">{ar ? "الاتصالات" : "Communications"}</a><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></nav></header>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{ar ? "اختيارات واضحة تحت سيطرتك" : "Clear choices, under your control"}</span><h1>{ar ? "تفضيلات الإشعارات" : "Notification preferences"}</h1><p>{ar ? "اختر نوع التحديثات والقنوات المناسبة لك. تبقى الإشعارات الأساسية داخل التطبيق مفعلة لحماية حسابك وإتمام معاملاتك." : "Choose the updates and channels that suit you. Essential in-app notices stay enabled to protect your account and complete your transactions."}</p></div><div className={styles.heroBadge}><span aria-hidden="true">✓</span><b>{ar ? "تحكم صريح" : "Explicit control"}</b><small>{ar ? "لا موافقة مستنتجة" : "No inferred consent"}</small></div></section>
    <div className={styles.content}>
      <section className={styles.boundary}><div><b>{data?.boundaries.actualDelivery ? (ar ? "تسليم البريد الإلكتروني للمعاملات نشط" : "Transactional email delivery is active") : (ar ? "البريد الإلكتروني غير متاح مؤقتاً" : "Email delivery is temporarily unavailable")}</b><p>{data?.guidance ?? (ar ? "تبقى إشعارات التطبيق القناة الأساسية." : "In-app notifications remain authoritative.")}</p></div><span>{data?.boundaries.actualDelivery ? (ar ? "البريد نشط" : "EMAIL LIVE") : (ar ? "داخل التطبيق" : "IN-APP ONLY")}</span></section>
      {message && <p className={styles.success} role="status">{message}</p>}{error && <div className={styles.error} role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>{ar ? "إعادة المحاولة" : "Try again"}</button></div>}
      {!data && !error ? <div className={styles.loading} role="status" aria-live="polite"><span /><p>{ar ? "جارٍ تحميل تفضيلاتك…" : "Loading your preferences…"}</p></div> : data && <>
        <section className={styles.panel} aria-label={ar ? "جاهزية تسليم البريد" : "Email delivery readiness"}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "جهة الاتصال المؤكدة" : "Verified delivery contact"}</span><h2>{data.delivery.email.contact?.email ?? (ar ? "لا يتوفر بريد إلكتروني" : "No email is available")}</h2><p>{!data.delivery.email.contact?.independentlyVerified ? (ar ? "تحقق من البريد قبل أن تتمكن كيفايا من إرسال التحديثات." : "Verify this address before Qivaya can deliver updates.") : data.delivery.email.masterEnabled ? (ar ? "تسليم البريد نشط للفئات التي فعّلتها." : "Email delivery is active for the categories you enabled.") : (ar ? "تم إيقاف البريد مؤقتاً. يمكنك تشغيله دون تغيير اختيارات الفئات." : "Email is paused. You can resume it without changing category choices.")}</p></div><div><span className={styles.eyebrow}>{!data.delivery.email.contact?.independentlyVerified ? (ar ? "بانتظار التحقق" : "Verification needed") : data.delivery.email.masterEnabled ? (ar ? "التسليم نشط" : "Delivery on") : (ar ? "التسليم متوقف" : "Delivery paused")}</span><p><a href="/settings/communications">{ar ? "إدارة البريد" : "Manage email"}</a></p>{data.delivery.email.contact?.independentlyVerified && <button type="button" className={`${styles.switch} ${data.delivery.email.masterEnabled ? styles.switchOn : ""}`} role="switch" aria-checked={data.delivery.email.masterEnabled} aria-label={ar ? "تسليم البريد الإلكتروني" : "Email delivery"} disabled={busyKey === "email-master"} onClick={toggleEmailMaster}><i /></button>}</div></div></section>
        <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "الفئات والقنوات" : "Categories & channels"}</span><h2>{ar ? "اختر أين تريد تلقي التحديثات" : "Choose where you want updates"}</h2></div><p>{ar ? "القفل يعني إشعاراً أساسياً لا يمكن تعطيله." : "A lock marks an essential notice that cannot be disabled."}</p></div>
          <div className={styles.matrix} role="table" aria-label={ar ? "مصفوفة تفضيلات الإشعارات" : "Notification preference matrix"}>
            <div className={styles.matrixHead} role="row"><span role="columnheader">{ar ? "الفئة" : "Category"}</span>{channels.map((channel) => <span role="columnheader" key={channel}>{ar ? channelLabels[channel].ar : channelLabels[channel].en}</span>)}</div>
            {categories.map((category) => <div className={styles.matrixRow} role="row" key={category}><div className={styles.category} role="rowheader"><i>{labels[category].icon}</i><div><b>{ar ? labels[category].ar : labels[category].en}</b><small>{ar ? labels[category].textAr : labels[category].textEn}</small></div></div>{channels.map((channel) => { const preference = byKey.get(`${category}:${channel}`); if (!preference) return <span key={channel}>—</span>; const key = `${category}:${channel}`, available = data.delivery.channels[channel]; return <button key={channel} type="button" className={`${styles.switch} ${preference.enabled ? styles.switchOn : ""} ${preference.mandatory ? styles.locked : ""}`} role="switch" aria-checked={preference.enabled} aria-label={`${ar ? labels[category].ar : labels[category].en}: ${ar ? channelLabels[channel].ar : channelLabels[channel].en}${preference.mandatory ? (ar ? "، أساسي" : ", essential") : ""}${available ? "" : (ar ? "، غير متاح" : ", unavailable")}`} title={!available ? (ar ? "هذه القناة غير متاحة بعد" : "This channel is not available yet") : preference.mandatory ? (ar ? "أساسي لمعاملة أو أمان الحساب" : "Essential transaction or account-security notice") : ""} disabled={busyKey === key || preference.mandatory || !available} onClick={() => toggle(preference)}><span>{preference.mandatory ? "◆" : !available ? "×" : ""}</span><i /></button>; })}</div>)}
          </div>
        </section>
        <section className={styles.settingsGrid}><div className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "اللغة والمنطقة الزمنية" : "Language & timezone"}</span><h2>{ar ? "تنسيق تفضيلاتك" : "Preference formatting"}</h2></div></div><div className={styles.formGrid}><label>{ar ? "اللغة المفضلة" : "Preferred language"}<select value={settings.preferredLocale} onChange={(event) => setSettings((current) => ({ ...current, preferredLocale: event.target.value }))}><option value="en">English</option><option value="ar">العربية</option></select></label><label>{ar ? "المنطقة الزمنية" : "Timezone"}<select value={settings.timezone} onChange={(event) => setSettings((current) => ({ ...current, timezone: event.target.value }))}><option value="Asia/Qatar">Asia/Qatar</option><option value="Asia/Riyadh">Asia/Riyadh</option><option value="Asia/Dubai">Asia/Dubai</option><option value="UTC">UTC</option></select></label></div></div>
          <div className={styles.panel}><div className={styles.quietHead}><div><span className={styles.eyebrow}>{ar ? "تفضيل الوقت الهادئ" : "Quiet-hours preference"}</span><h2>{ar ? "قلل المقاطعات" : "Reduce interruptions"}</h2></div><button type="button" className={`${styles.switch} ${settings.quietHoursEnabled ? styles.switchOn : ""}`} role="switch" aria-checked={settings.quietHoursEnabled} onClick={() => setSettings((current) => ({ ...current, quietHoursEnabled: !current.quietHoursEnabled }))}><i /></button></div><div className={styles.formGrid}><label>{ar ? "يبدأ" : "Starts"}<input type="time" value={settings.quietHoursStart} disabled={!settings.quietHoursEnabled} onChange={(event) => setSettings((current) => ({ ...current, quietHoursStart: event.target.value }))} /></label><label>{ar ? "ينتهي" : "Ends"}<input type="time" value={settings.quietHoursEnd} disabled={!settings.quietHoursEnabled} onChange={(event) => setSettings((current) => ({ ...current, quietHoursEnd: event.target.value }))} /></label></div><p className={styles.note}>{ar ? "قد تتجاوز إشعارات الحساب أو المعاملات الأساسية هذا التفضيل. لا يوجد ضمان للتطبيق." : "Essential account or transaction notices may override this preference. Enforcement is not guaranteed."}</p></div>
        </section>
        <div className={styles.saveBar}><div><b>{ar ? "اختياراتك تخص حسابك فقط" : "Your choices belong to your account only"}</b><small>{ar ? "لا مزامنة خارجية أو تخصيص سريري." : "No external sync or clinical personalization."}</small></div><button type="button" disabled={savingProfile || busyKey === "profile"} onClick={() => void saveSettings()}>{savingProfile ? (ar ? "جارٍ الحفظ…" : "Saving…") : (ar ? "حفظ إعدادات الوقت واللغة" : "Save time & language settings")}</button></div>
        <section className={styles.history}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "حالة التسليم" : "Delivery status"}</span><h2>{ar ? "آخر رسائل البريد للمعاملات" : "Recent transactional email"}</h2></div><p>{ar ? "لا نعرض عنوان المستلم أو محتوى الرسالة هنا." : "Recipient addresses and message content are not shown here."}</p></div>{data.delivery.email.activity.length === 0 ? <p className={styles.empty}>{ar ? "لا يوجد نشاط بريد بعد." : "No email activity yet."}</p> : <ul>{data.delivery.email.activity.slice(0, 8).map((item) => <li key={item.id}><span>{item.templateId.replaceAll("_", " ")}</span><b>{item.status === "sent" ? (ar ? "قُبل للإرسال" : "Accepted") : item.status === "suppressed" ? (ar ? "لم يُرسل" : "Not sent") : item.status}</b><time>{new Date(item.sentAt ?? item.createdAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</time></li>)}</ul>}</section>
        <section className={styles.history}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "سجل غير قابل للتعديل" : "Immutable history"}</span><h2>{ar ? "آخر تغييراتك" : "Your recent changes"}</h2></div></div>{data.history.length === 0 ? <p className={styles.empty}>{ar ? "لا توجد تغييرات مسجلة بعد." : "No preference changes recorded yet."}</p> : <ul>{data.history.slice(0, 8).map((item) => <li key={item.id}><span>{item.category ? `${ar ? labels[item.category].ar : labels[item.category].en} · ${item.channel ? (ar ? channelLabels[item.channel].ar : channelLabels[item.channel].en) : ""}` : (ar ? "إعدادات اللغة والوقت" : "Language and time settings")}</span><b>{item.nextEnabled == null ? (ar ? "تم التحديث" : "Updated") : item.nextEnabled ? (ar ? "مفعّل" : "Enabled") : (ar ? "متوقف" : "Disabled")}</b><time>{new Date(item.occurredAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</time></li>)}</ul>}</section>
      </>}
    </div>
  </main>;
}
