"use client";

import { useMemo, useState } from "react";

type Role="patient"|"provider"|"partner";
type Filter="all"|"unread"|"action";
type Notice={id:number,role:Role,title:string,titleAr:string,body:string,bodyAr:string,time:string,timeAr:string,kind:string,kindAr:string,icon:string,unread:boolean,action?:string,actionAr?:string,href?:string};

const seed:Notice[]=[
  {id:1,role:"patient",title:"Appointment confirmed",titleAr:"تم تأكيد الموعد",body:"Your visit with Dr. Laila is confirmed for Sunday at 4:30 PM.",bodyAr:"تم تأكيد زيارتك مع د. ليلى يوم الأحد الساعة ٤:٣٠ مساءً.",time:"10 min ago",timeAr:"منذ ١٠ دقائق",kind:"Appointment",kindAr:"موعد",icon:"✓",unread:true,action:"View appointment",actionAr:"عرض الموعد",href:"/appointments"},
  {id:2,role:"patient",title:"A document was added to your wallet",titleAr:"تمت إضافة مستند إلى محفظتك",body:"A verified visit summary is ready. Sensitive details stay hidden in notifications.",bodyAr:"ملخص زيارة موثّق جاهز. تبقى التفاصيل الحساسة مخفية في الإشعارات.",time:"2 hours ago",timeAr:"منذ ساعتين",kind:"Health wallet",kindAr:"المحفظة الصحية",icon:"▤",unread:true,action:"Open wallet",actionAr:"فتح المحفظة",href:"/wallet"},
  {id:3,role:"patient",title:"Prepare for your upcoming visit",titleAr:"استعد لزيارتك القادمة",body:"Review arrival instructions and confirm who will attend.",bodyAr:"راجع تعليمات الوصول وأكد الشخص الذي سيحضر.",time:"Yesterday",timeAr:"أمس",kind:"Reminder",kindAr:"تذكير",icon:"◎",unread:false,action:"Review details",actionAr:"مراجعة التفاصيل",href:"/appointments"},
  {id:4,role:"patient",title:"Benefits balance updated",titleAr:"تم تحديث رصيد المزايا",body:"Your available sponsored balance has changed. No employer received care details.",bodyAr:"تم تحديث رصيد المزايا المتاح. لم يتلقَ صاحب العمل أي تفاصيل رعاية.",time:"31 Jul",timeAr:"٣١ يوليو",kind:"Benefits",kindAr:"المزايا",icon:"Q",unread:false,href:"/wallet"},
  {id:5,role:"provider",title:"New booking needs acknowledgement",titleAr:"حجز جديد يحتاج إلى تأكيد",body:"A new patient appointment was added to Monday’s schedule.",bodyAr:"تمت إضافة موعد مريض جديد إلى جدول يوم الاثنين.",time:"5 min ago",timeAr:"منذ ٥ دقائق",kind:"Schedule",kindAr:"الجدول",icon:"+",unread:true,action:"Review booking",actionAr:"مراجعة الحجز",href:"/provider"},
  {id:6,role:"provider",title:"Encounter summary awaiting approval",titleAr:"ملخص زيارة بانتظار الاعتماد",body:"A draft summary must be reviewed before it can be shared with the patient.",bodyAr:"يجب مراجعة مسودة الملخص قبل مشاركتها مع المريض.",time:"38 min ago",timeAr:"منذ ٣٨ دقيقة",kind:"Clinical task",kindAr:"مهمة سريرية",icon:"◇",unread:true,action:"Open encounter",actionAr:"فتح الزيارة",href:"/provider/encounter"},
  {id:7,role:"provider",title:"Tomorrow’s schedule changed",titleAr:"تم تغيير جدول الغد",body:"Two appointments were rescheduled by patients.",bodyAr:"أعاد مريضان جدولة موعديهما.",time:"3 hours ago",timeAr:"منذ ٣ ساعات",kind:"Schedule",kindAr:"الجدول",icon:"◎",unread:false,href:"/provider"},
  {id:8,role:"partner",title:"Six eligibility records need review",titleAr:"ستة سجلات أهلية تحتاج إلى مراجعة",body:"Resolve pending records before the payroll roster closes.",bodyAr:"عالج السجلات المعلقة قبل إغلاق قائمة الرواتب.",time:"12 min ago",timeAr:"منذ ١٢ دقيقة",kind:"Eligibility",kindAr:"الأهلية",icon:"!",unread:true,action:"Review members",actionAr:"مراجعة الأعضاء",href:"/partner"},
  {id:9,role:"partner",title:"August invoice is ready",titleAr:"فاتورة أغسطس جاهزة",body:"QAR 18,420 is due on 14 August. The invoice contains aggregate billing only.",bodyAr:"يستحق مبلغ ١٨٬٤٢٠ ر.ق في ١٤ أغسطس. تتضمن الفاتورة بيانات مالية مجمعة فقط.",time:"Today, 8:00 AM",timeAr:"اليوم، ٨:٠٠ ص",kind:"Invoice",kindAr:"فاتورة",icon:"▤",unread:true,action:"View invoice",actionAr:"عرض الفاتورة",href:"/partner"},
  {id:10,role:"partner",title:"Monthly funding allocation received",titleAr:"تم استلام التمويل الشهري",body:"QAR 75,000 was added to your organisation’s benefits balance.",bodyAr:"تمت إضافة ٧٥٬٠٠٠ ر.ق إلى رصيد مزايا المؤسسة.",time:"1 Aug",timeAr:"١ أغسطس",kind:"Funding",kindAr:"التمويل",icon:"Q",unread:false,href:"/partner"},
];

export default function Notifications(){
  const [role,setRole]=useState<Role>("patient");const [filter,setFilter]=useState<Filter>("all");const [lang,setLang]=useState<"en"|"ar">("en");const [items,setItems]=useState(seed);const [prefs,setPrefs]=useState(false);const [toast,setToast]=useState("");
  const [channels,setChannels]=useState({essential:true,reminders:true,wallet:true,benefits:true,product:false,sms:true,email:true,push:true});const ar=lang==="ar";
  const visible=useMemo(()=>items.filter(n=>n.role===role&&(filter==="all"||(filter==="unread"&&n.unread)||(filter==="action"&&n.action))),[items,role,filter]);
  const unread=items.filter(n=>n.role===role&&n.unread).length;
  const mark=(id:number)=>setItems(v=>v.map(n=>n.id===id?{...n,unread:false}:n));
  const markAll=()=>{setItems(v=>v.map(n=>n.role===role?{...n,unread:false}:n));setToast(ar?"تم تحديد الكل كمقروء":"All notifications marked as read")};
  const roleName={patient:ar?"المريض":"Patient",provider:ar?"مقدم الرعاية":"Provider",partner:ar?"الشريك":"Partner"};
  return <main className={`notification-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <header className="notification-header"><a href="/" className="brand"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav><a href="/">{ar?"الرئيسية":"Home"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a><a href="/wallet">{ar?"المحفظة الصحية":"Health wallet"}</a></nav><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><button className="notification-settings" onClick={()=>setPrefs(true)}>⚙ <span>{ar?"التفضيلات":"Preferences"}</span></button><span className="notification-avatar">MA</span></div></header>
    <section className="notification-hero"><div><p>{ar?"مركز التواصل":"COMMUNICATION CENTRE"}</p><h1>{ar?"الإشعارات":"Notifications"}</h1><span>{ar?"كل التحديثات المهمة في مكان واحد، دون كشف معلومات حساسة في المعاينة.":"Important updates in one place, without exposing sensitive information in previews."}</span></div><button onClick={()=>setPrefs(true)}>⚙ {ar?"إدارة التفضيلات":"Manage preferences"}</button></section>
    <section className="notification-content">
      <div className="notification-privacy"><span>♙</span><p><b>{ar?"معاينات تحمي الخصوصية":"Privacy-safe previews"}</b>{ar?"لن تعرض الإشعارات التشخيصات أو نتائج الفحوصات أو الملاحظات السريرية. افتح المساحة الآمنة لرؤية التفاصيل المصرّح بها.":"Notifications never show diagnoses, test results, or clinical notes. Open the secure workspace to view permitted details."}</p></div>
      <div className="notification-layout"><aside className="notification-roles"><h2>{ar?"عرض كـ":"View as"}</h2>{(["patient","provider","partner"] as Role[]).map((r,i)=><button className={role===r?"active":""} onClick={()=>{setRole(r);setFilter("all")}} key={r}><span>{i===0?"♡":i===1?"✚":"◇"}</span><div><b>{roleName[r]}</b><small>{r==="patient"?(ar?"الرعاية والمواعيد":"Care & appointments"):r==="provider"?(ar?"الجدول والمهام":"Schedule & tasks"):(ar?"المزايا والفواتير":"Benefits & billing")}</small></div><i>{items.filter(n=>n.role===r&&n.unread).length}</i></button>)}<div className="notification-boundary"><b>{ar?"مساحات منفصلة":"Separated contexts"}</b><p>{ar?"تبديل العرض هنا للتوضيح فقط. في المنتج الحقيقي تحدد صلاحية الحساب ما يمكن الوصول إليه.":"Role switching is for demonstration. Production access is determined by account permissions."}</p></div></aside>
        <section className="notification-inbox"><div className="inbox-head"><div><h2>{roleName[role]} {ar?"الوارد":"inbox"}</h2><p>{unread} {ar?"غير مقروء":"unread"}</p></div>{unread>0&&<button onClick={markAll}>✓ {ar?"تحديد الكل كمقروء":"Mark all as read"}</button>}</div><div className="inbox-tabs"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>{ar?"الكل":"All"} <span>{items.filter(n=>n.role===role).length}</span></button><button className={filter==="unread"?"active":""} onClick={()=>setFilter("unread")}>{ar?"غير مقروء":"Unread"} <span>{unread}</span></button><button className={filter==="action"?"active":""} onClick={()=>setFilter("action")}>{ar?"يحتاج إجراء":"Needs action"}</button></div><div className="notice-list">{visible.length?visible.map(n=><article className={n.unread?"unread":""} key={n.id} onClick={()=>mark(n.id)}><span className={`notice-icon k${n.id%4}`}>{n.icon}</span><div className="notice-copy"><div><i>{ar?n.kindAr:n.kind}</i><time>{ar?n.timeAr:n.time}</time></div><h3>{ar?n.titleAr:n.title}</h3><p>{ar?n.bodyAr:n.body}</p>{n.action&&<a href={n.href} onClick={e=>e.stopPropagation()}>{ar?n.actionAr:n.action} →</a>}</div>{n.unread&&<b className="unread-dot"/>}</article>):<div className="empty-inbox"><span>✓</span><h3>{ar?"لا توجد إشعارات هنا":"Nothing waiting here"}</h3><p>{ar?"أنت مطلع على كل شيء في هذا العرض.":"You’re up to date in this view."}</p></div>}</div></section>
      </div>
    </section>
    {prefs&&<div className="preference-layer" onMouseDown={e=>e.target===e.currentTarget&&setPrefs(false)}><aside className="preference-drawer"><button className="drawer-close" onClick={()=>setPrefs(false)}>×</button><p>{ar?"التحكم بالتواصل":"COMMUNICATION CONTROL"}</p><h2>{ar?"تفضيلات الإشعارات":"Notification preferences"}</h2><span>{ar?"اختر ما تريد استلامه وكيف. تبقى التنبيهات الأساسية مفعلة لحماية حسابك ورحلة الرعاية.":"Choose what you receive and how. Essential alerts remain enabled to protect your account and care journey."}</span><section><h3>{ar?"أنواع الإشعارات":"Notification types"}</h3><Toggle label={ar?"الأمان والتغييرات الأساسية":"Security & essential changes"} text={ar?"تسجيل الدخول، تغيير الوصول، الإلغاء والمدفوعات":"Sign-in, access changes, cancellations, and payments"} value={channels.essential} locked onChange={()=>{}}/><Toggle label={ar?"المواعيد والتذكيرات":"Appointments & reminders"} text={ar?"التأكيدات، التغييرات وتعليمات الاستعداد":"Confirmations, changes, and preparation"} value={channels.reminders} onChange={()=>setChannels(v=>({...v,reminders:!v.reminders}))}/><Toggle label={ar?"تحديثات المحفظة الصحية":"Health wallet updates"} text={ar?"عند إضافة مستند موثّق أو تغيير مشاركة":"Verified documents and sharing changes"} value={channels.wallet} onChange={()=>setChannels(v=>({...v,wallet:!v.wallet}))}/><Toggle label={ar?"المزايا والتمويل":"Benefits & funding"} text={ar?"الأهلية والرصيد والفواتير":"Eligibility, balances, and invoices"} value={channels.benefits} onChange={()=>setChannels(v=>({...v,benefits:!v.benefits}))}/><Toggle label={ar?"أخبار رعايتي":"Reyati news"} text={ar?"تحديثات اختيارية للمنتج والخدمات":"Optional product and service updates"} value={channels.product} onChange={()=>setChannels(v=>({...v,product:!v.product}))}/></section><section><h3>{ar?"قنوات التوصيل":"Delivery channels"}</h3><div className="channel-grid"><Toggle label={ar?"إشعارات التطبيق":"Push"} text={ar?"على هذا الجهاز":"On this device"} value={channels.push} onChange={()=>setChannels(v=>({...v,push:!v.push}))}/><Toggle label={ar?"رسائل نصية":"SMS"} text="+974 •••• 4821" value={channels.sms} onChange={()=>setChannels(v=>({...v,sms:!v.sms}))}/><Toggle label={ar?"البريد الإلكتروني":"Email"} text="m•••••@example.test" value={channels.email} onChange={()=>setChannels(v=>({...v,email:!v.email}))}/></div></section><div className="quiet-hours"><span>☾</span><div><b>{ar?"ساعات الهدوء":"Quiet hours"}</b><p>{ar?"١٠:٠٠ م – ٧:٠٠ ص · التنبيهات العاجلة فقط":"10:00 PM – 7:00 AM · urgent alerts only"}</p></div><button>{ar?"تعديل":"Edit"}</button></div><button className="save-preferences" onClick={()=>{setPrefs(false);setToast(ar?"تم حفظ التفضيلات محلياً في النموذج":"Prototype preferences saved locally")}}>{ar?"حفظ التفضيلات":"Save preferences"}</button><small className="preference-note">{ar?"هذه التغييرات تجريبية ولا يتم حفظها بعد مغادرة الصفحة.":"Prototype only. Changes are not retained after leaving this page."}</small></aside></div>}
    {toast&&<div className="notification-toast"><span>✓</span>{toast}<button onClick={()=>setToast("")}>×</button></div>}
  </main>
}

function Toggle({label,text,value,onChange,locked=false}:{label:string,text:string,value:boolean,onChange:()=>void,locked?:boolean}){return <div className="preference-row"><div><b>{label}</b><small>{text}</small></div><button className={value?"toggle on":"toggle"} onClick={onChange} disabled={locked} aria-pressed={value}><span/></button>{locked&&<i>Required</i>}</div>}
