import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
const schema=read("db/health-content-schema.ts"),service=read("lib/health-content.ts"),publicPage=read("app/health-library/page.tsx"),adminPage=read("app/admin/health-content/page.tsx"),publicApi=read("app/api/health-library/route.ts"),adminApi=read("app/api/admin/health-content/route.ts"),flags=read("lib/foundation-flags.ts");

test("articles versions sources events and rehearsals are durable and indexed",()=>{for(const name of ["healthContentArticles","healthContentVersions","healthContentSources","healthContentEvents","healthContentRehearsals"])assert.match(schema,new RegExp(`export const ${name}`));assert.match(schema,/uniqueIndex\("idx_health_content_articles_slug"/);assert.match(schema,/idx_health_content_versions_article_number/);assert.match(schema,/idx_health_content_versions_review_due/);});
test("public library exposes published current versions only",()=>{assert.match(service,/inArray\(healthContentArticles\.status, \["published", "retirement_requested"\]\)/);assert.match(service,/eq\(healthContentVersions\.status, "published"\)/);assert.match(service,/eq\(healthContentArticles\.currentVersionId, healthContentVersions\.id\)/);assert.doesNotMatch(publicApi,/getOrCreateCurrentUser/);assert.match(publicApi,/public, max-age=60/);});
test("content is bilingual attributable medically reviewed and source linked",()=>{for(const pattern of [/titleEn/,/titleAr/,/bodyEn/,/bodyAr/,/authorCredentials/,/medicalReviewerCredentials/,/evidenceReviewedThrough/,/nextReviewDueAt/])assert.match(schema,pattern);assert.match(service,/Every source must use a valid HTTPS URL/);assert.match(publicPage,/Trusted sources/);assert.match(publicPage,/Medically reviewed/);});
test("strict maker checker separates author reviewer publisher and retirement approver",()=>{assert.match(service,/row\.content\.authorUserId === userId/);assert.match(service,/row\.content\.medicalReviewerUserId === userId/);assert.match(service,/Author, medical reviewer, and publisher must be different people/);assert.match(service,/retirementRequestedByUserId === userId/);assert.match(adminPage,/Author ≠ reviewer ≠ publisher/);});
test("publication correction and retirement lifecycle is explicit and versioned",()=>{for(const status of ["draft","under_review","changes_requested","medically_reviewed","published","superseded","retirement_requested","retired"])assert.match(service,new RegExp(`"${status}"`));assert.match(service,/correctionNoticeEn/);assert.match(service,/articleRemainsPublished: true/);assert.match(service,/remainsPublicPendingApproval: true/);assert.match(service,/version: version \+ 1/);});
test("diagnosis personalization AI and syndication are centrally disabled",()=>{for(const flag of ["healthContentAiGeneration","healthContentClinicalPersonalization","healthContentDiagnosis","healthContentExternalSyndication"]){assert.match(flags,new RegExp(`${flag}: false`));assert.match(service,new RegExp(`foundationFlags\\.${flag}`));}assert.match(publicPage,/not a diagnosis or personal advice/);});
test("audit trail is privacy safe and excludes content and source URLs",()=>{assert.match(service,/articleTextIncluded: false/);assert.match(service,/sourceUrlsIncluded: false/);assert.match(service,/reviewerNotesIncluded: false/);assert.match(service,/healthDataIncluded: false/);assert.match(service,/externalSideEffect: false/);});
test("admin API is authenticated role gated rate limited and action bounded",()=>{assert.match(adminApi,/getOrCreateCurrentUser/);assert.match(adminApi,/private, no-store/);assert.match(adminApi,/enforceWriteRateLimit/);for(const action of ["create_draft","submit_review","medical_review","publish","create_correction","request_retirement","approve_retirement","run_rehearsal"])assert.match(adminApi,new RegExp(action));assert.match(service,/requirePlatformRole\(userId, \["platform_admin"\]\)/);});
test("governance aggregates lifecycle readiness and uses a zero-effect rehearsal",()=>{for(const metric of ["published","inReview","awaitingPublication","reviewDueWithin30Days","retired"])assert.match(service,new RegExp(metric));for(const pattern of [/scenarioCount: 20/,/articlesCreated: 0/,/articlesPublished: 0/,/externalRequestsSent: 0/,/zeroOperationalSideEffects: true/])assert.match(service,pattern);assert.match(adminPage,/Zero-side-effect rehearsal/);});
test("public and editorial experiences are polished bilingual and recovery safe",()=>{assert.match(publicPage,/useReyatiLocale/);assert.match(adminPage,/useReyatiLocale/);assert.match(publicPage,/role="alert"/);assert.match(adminPage,/role="alert"/);assert.match(publicPage,/Qivaya health library/);assert.match(adminPage,/Trusted health content centre/);});
