import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read = path => readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("scheduler suites, scenarios, runs, and review events are durable, indexed, and expand-only", async () => { const [schema, foundationMigration, reviewMigration] = await Promise.all([read("db/schema.ts"), read("drizzle/0047_free_stingray.sql"), read("drizzle/0048_curved_viper.sql")]); for (const name of ["medicationReminderSchedulerSuites", "medicationReminderSchedulerScenarios", "medicationReminderSchedulerRuns", "medicationReminderSchedulerRunEvents"]) assert.match(schema, new RegExp(name)); assert.match(schema, /idx_med_reminder_scheduler_scenarios_suite_key/); assert.match(schema, /idx_med_reminder_scheduler_runs_status_executed/); assert.match(foundationMigration, /PRAGMA optimize/); assert.match(reviewMigration, /PRAGMA optimize/); assert.doesNotMatch(reviewMigration, /DROP (TABLE|COLUMN|INDEX)/); });
test("the standard suite covers timing, lifecycle, boundaries, duplicates, and prohibited sources", async () => { const service = await read("lib/medication-reminder-readiness.ts"); for (const key of ["en-due-once", "ar-due-evening", "en-duplicate-tick", "en-not-due", "en-paused", "ar-archived", "en-before-start", "en-after-end", "en-ocr-source-blocked"]) assert.match(service, new RegExp(key)); });
test("Qatar conversion and occurrence keys are deterministic and duplicate-safe", async () => { const service = await read("lib/medication-reminder-readiness.ts"); assert.match(service, /timestamp \+ 3 \* 60 \* 60 \* 1000/); assert.match(service, /const occurrenceKeys = \[\.\.\.new Set\(candidateKeys\)\]/); assert.match(service, /Asia\/Qatar/); });
test("unapproved sources and inactive lifecycle states block before materialization", async () => { const service = await read("lib/medication-reminder-readiness.ts"); assert.match(service, /sourceType !== "patient_entered"/); assert.match(service, /source_not_allowed/); assert.match(service, /status !== "configured"/); assert.match(service, /occurrenceMaterializationEnabled: false/); });
test("evaluation requires zero failures, duplicates, invalid sources, and delivery attempts", async () => { const service = await read("lib/medication-reminder-readiness.ts"); assert.match(service, /failures\.length === 0 && duplicateOccurrences === 0 && invalidSourceOccurrences === 0 && deliveryAttempts === 0/); assert.match(service, /clinicalContentIncluded: false/); });
test("independent review is distinct, pass-only, optimistic, and activation-free", async () => { const service = await read("lib/medication-reminder-readiness.ts"); assert.match(service, /requirePlatformRole\(userId, \["security_auditor"\]\)/); assert.match(service, /run\.executedByUserId === userId/); assert.match(service, /run\.result !== "pass"/); assert.match(service, /eq\(medicationReminderSchedulerRuns\.version, version\)/); assert.match(service, /independentReviewer: true/); assert.match(service, /occurrenceMaterializationEnabled: false/); });
test("the protected bilingual workspace exposes the evidence without activating runtime", async () => { const [page, route, flags, adr] = await Promise.all([read("app/admin/reminder-readiness/page.tsx"), read("app/api/admin/reminder-readiness/route.ts"), read("lib/foundation-flags.ts"), read("docs/adr/ADR-030-medication-reminder-scheduler-readiness.md")]); assert.match(page, /Medication Reminder Readiness/); assert.match(page, /جاهزية تذكيرات الدواء/); assert.match(route, /private, no-store/); assert.match(route, /enforceWriteRateLimit/); assert.match(flags, /medicationReminderOccurrenceMaterialization: false/); assert.match(adr, /does not read patient reminder plans/); });
