import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const source = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");
const schema = await source("db/schema.ts"); const service = await source("lib/monitoring-acceptance.ts"); const posture = await source("lib/monitoring-posture.ts"); const route = await source("app/api/admin/monitoring-acceptance/route.ts"); const page = await source("app/admin/monitoring-acceptance/page.tsx"); const health = await source("lib/operations-health.ts"); const layout = await source("app/layout.tsx");

test("monitoring acceptance evidence and append-only events are durable and indexed", () => { for (const value of ["monitoring_acceptance_runs", "monitoring_acceptance_events", "idx_monitoring_acceptance_reference", "idx_monitoring_acceptance_status_created"]) assert.match(schema, new RegExp(value)); assert.match(schema, /preparedByUserId/); assert.match(schema, /reviewerUserId/); });
test("runtime posture uses non-secret Vercel system state and registered first-party instrumentation", () => { assert.match(posture, /env\.VERCEL === "1"/); assert.match(posture, /env\.VERCEL_ENV === "production"/); assert.match(posture, /externalTelemetryExportEnabled: false/); assert.match(layout, /<Analytics \/>/); assert.match(layout, /<SpeedInsights \/>/); });
test("acceptance fails closed on production, prerequisites, redaction, and separation of duties", () => { assert.match(service, /Production Vercel runtime evidence can only be submitted/); assert.match(service, /approvedPolicyCount !== readiness\.requiredPolicyCount/); assert.match(service, /prohibitedFieldsDetected: 0/); assert.match(service, /externalSystemsContacted: 0/); assert.match(service, /preparer cannot independently review/); assert.match(service, /pending_review/); });
test("monitoring API is protected, no-store, rate-limited, conflict-safe, and privacy-safe on failure", () => { assert.match(route, /private, no-store/); assert.match(route, /enforceWriteRateLimit/); assert.match(route, /status: 409/); assert.match(route, /reportOperationalError\("admin\.monitoring_acceptance\.failed"/); });
test("operator workspace exposes prerequisites, coded references, explicit attestations, and independent review", () => { assert.match(page, /approvedPolicyCount/); assert.match(page, /Coded evidence reference/); assert.match(page, /runtimeLogsObserved/); assert.match(page, /securityAlertRouteObserved/); assert.match(page, /Submit for independent review/); assert.match(page, /Verify evidence/); });
test("operations readiness is derived from fresh verified monitoring evidence", () => { assert.match(health, /monitoringAcceptanceRuns/); assert.match(health, /monitoringEvidenceReady/); assert.match(health, /monitoring_coverage/); assert.doesNotMatch(health, /id: "monitoring_coverage"[^\n]*status: "blocked" as const/); });
