import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("pharmacy module owns durable indexed profiles, orders, fulfilments, refills, events, and rehearsals",async()=>{const s=await read("db/pharmacy-fulfilment-schema.ts");for(const name of["pharmacyProfiles","pharmacyPrescriptionOrders","pharmacyFulfilments","pharmacyRefillRequests","pharmacyWorkflowEvents","pharmacyRehearsals","idx_pharmacy_orders_patient_status_updated","idx_pharmacy_fulfilments_org_status_updated","idx_pharmacy_refills_provider_status_updated","idx_pharmacy_events_resource_created"])assert.match(s,new RegExp(name))});
test("only verified provider-issued and attested appointments create prescriptions",async()=>{const s=await read("lib/pharmacy-fulfilment.ts");for(const pattern of[/requireActiveProvider\(userId\)/,/eq\(appointments\.providerId, provider\.id\)/,/signedAttestation !== true/,/PHARMACY_ATTESTATION_VERSION/,/source: "provider_issued"/,/approvalStatus: "approved"/,/ocrDerived: false/])assert.match(s,pattern)});
test("patient explicitly selects an approved pharmacy and only configured pickup or delivery",async()=>{const s=await read("lib/pharmacy-fulfilment.ts");for(const pattern of[/consentAccepted !== true/,/PHARMACY_CONSENT_VERSION/,/eq\(organizations\.type, "pharmacy"\)/,/eq\(pharmacyProfiles\.approvalStatus, "approved"\)/,/method === "pickup" && !pharmacy\.profile\.pickupEnabled/,/method === "delivery" && !pharmacy\.profile\.deliveryEnabled/])assert.match(s,pattern)});
test("partner transitions are role bound, optimistic, and prescription source checked",async()=>{const s=await read("lib/pharmacy-fulfilment.ts");for(const pattern of[/requireOrganizationRole\(/,/request\.order\.source !== "provider_issued"/,/request\.order\.approvalStatus !== "approved"/,/eq\(pharmacyFulfilments\.version, version\)/,/accept: "accepted"/,/clarify: "clarification_requested"/,/prepare: "preparing"/,/ready: "ready"/,/collect: "collected"/,/complete: "completed"/,/cancel: "cancelled"/])assert.match(s,pattern)});
test("refill and renewal requests always enter explicit provider review",async()=>{const s=await read("lib/pharmacy-fulfilment.ts");for(const pattern of[/status: "pending_provider_review"/,/automaticApproval: false/,/action === "review_refill"/,/humanProviderDecision: true/,/provider-approved refill review is required/,/eq\(pharmacyRefillRequests\.status, "provider_approved"\)/,/repeatsRemaining: repeatOrder\.repeatsRemaining - 1/])assert.match(s,pattern)});
test("OCR medication actions and unsupported integration claims are denied",async()=>{const[s,p,a,f]=await Promise.all([read("lib/pharmacy-fulfilment.ts"),read("app/pharmacy/page.tsx"),read("app/admin/pharmacy/page.tsx"),read("lib/foundation-flags.ts")]);for(const name of["pharmacyUncertainOcrActions","pharmacyInventoryIntegration","pharmacyControlledDrugSystem","pharmacyPaymentIntegration","pharmacyCourierTracking","pharmacyExternalIntegration"]){assert.match(s,new RegExp(`foundationFlags\\.${name}`));assert.match(f,new RegExp(`${name}: false`))}assert.match(s,/body\.source === "ocr"/);assert.match(p,/does not infer medication actions from OCR/);assert.match(a,/every external integration remain disabled/)});
test("patient, provider, partner, and admin APIs are private, role checked, and rate limited",async()=>{const files=await Promise.all([read("app/api/pharmacy/route.ts"),read("app/api/provider/pharmacy/route.ts"),read("app/api/partner/pharmacy/route.ts"),read("app/api/admin/pharmacy/route.ts")]);for(const file of files){assert.match(file,/private, no-store/);assert.match(file,/enforceWriteRateLimit/);assert.match(file,/getOrCreateCurrentUser/)}});
test("aggregate rehearsal is synthetic and creates no operational records or external calls",async()=>{const s=await read("lib/pharmacy-fulfilment.ts");for(const pattern of[/scenarioCount: 14/,/ordersCreated: 0/,/fulfilmentsCreated: 0/,/refillsApproved: 0/,/externalRequestsSent: 0/,/dataMode: "synthetic_only"/,/visibility: "aggregate_only"/])assert.match(s,pattern)});
