import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("day-zero sessions and checks are durable, package-bound, unique, and indexed", async () => { const schema = await read("db/schema.ts"); const migration = await read("drizzle/0041_complex_quicksilver.sql"); assert.match(schema, /pilotCommandSessions/); assert.match(schema, /pilotCommandChecks/); assert.match(schema, /idx_pilot_command_sessions_package_reference/); assert.match(migration, /pilot_command_sessions/); assert.match(migration, /PRAGMA optimize/); });
test("command sessions capture readiness, bound shifts, and distinct active stop authority", async () => { const source = await read("lib/pilot-command-centre.ts"); assert.match(source, /readinessSnapshotJson: JSON\.stringify\(snapshot\)/); assert.match(source, /Command shift must be within the activation window/); assert.match(source, /Distinct active commander and stop authority are required/); assert.match(source, /synthetic_rehearsal/); });
test("all ten checks and independent review are mandatory", async () => { const source = await read("lib/pilot-command-centre.ts"); for (const key of ["identity_access", "provider_roster", "published_services", "scheduling_capacity", "participant_support", "consent_versions", "communications_fallback", "incident_contacts", "rollback_access", "monitoring_recovery"]) assert.match(source, new RegExp(key)); assert.match(source, /verifiedCheckCount !== session\.totalCheckCount/); assert.match(source, /session\.preparedByUserId === userId/); assert.match(source, /all\.some\(\(item\) => item\.status !== "verified"\)/); });
test("activation fails closed without current command evidence", async () => { const [pilot, command, flags] = await Promise.all([read("lib/controlled-pilot.ts"), read("lib/pilot-command-centre.ts"), read("lib/foundation-flags.ts")]); assert.match(pilot, /assertPilotCommandReady/); assert.match(pilot, /dayZeroCommandReady/); assert.match(command, /pilotActivated: false/); assert.match(flags, /pilotCommandRuntime: false/); });
test("command centre is protected, bilingual, and honest about its runtime", async () => { const [page, route, adr] = await Promise.all([read("app/admin/pilot-command/page.tsx"), read("app/api/admin/pilot-command/route.ts"), read("docs/adr/ADR-024-pilot-command-day-zero.md")]); assert.match(page, /Pilot Command Centre/); assert.match(page, /مركز قيادة البرنامج/); assert.match(page, /Live runtime is disabled/); assert.match(route, /getOrCreateCurrentUser/); assert.match(route, /enforceWriteRateLimit/); assert.match(route, /private, no-store/); assert.match(adr, /cannot activate the pilot/); });
