"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "../../diagnostic-imaging/diagnostic-imaging.module.css";
type Data={appointmentOptions:Array<{id:string;patientName:string;scheduledStart:string}>;partnerOptions:Array<{id:string;name:string}>;orders:Array<{id:string;studyType:string;bodyRegion:string;status:string;priority:string;signedAt:string}>;attestationVersion:string};
async function api(init?:RequestInit){const response=await fetch("/api/provider/diagnostic-imaging",{cache:"no-store",...init});const payload=await response.json();if(response.status===401){location.assign("/signin-with-chatgpt?return_to=/provider/diagnostic-imaging");throw new Error("Sign in required")}if(!response.ok)throw new Error(payload.message||payload.error||"Imaging workflow unavailable");return payload.data}
export default function ProviderDiagnosticImaging(){
  const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const load=useCallback(()=>api().then(setData).catch(reason=>setError(reason.message)),[]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form);setBusy(true);setError("");try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({appointmentId:values.get("appointment"),imagingOrganizationId:values.get("organization"),studyType:values.get("studyType"),bodyRegion:values.get("bodyRegion"),clinicalIndication:values.get("indication"),preparationInstructions:values.get("preparation"),priority:values.get("priority"),authorizedToOrder:values.get("authorized")==="on",signedAttestation:values.get("signed")==="on",attestationVersion:data?.attestationVersion})});form.reset();setNotice("Signed imaging order issued to the patient and selected organization.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to issue order")}finally{setBusy(false)}}
  return <main className={styles.shell}><header className={styles.top}><a href="/provider"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><a href="/provider">Provider console</a></header><section className={styles.hero}><small>CONTROLLED DIAGNOSTIC ORDERING</small><h1>Issue a signed, appointment-bound imaging order.</h1><p>Choose an active approved imaging organization. Reyati sends no PACS, RIS, or DICOM request and offers no automated interpretation.</p></section><section className={styles.panel}>{error&&<p className={styles.error}>{error}</p>}{notice&&<p className={styles.success}>{notice}</p>}<form className={styles.form} onSubmit={submit}><label>Patient appointment<select name="appointment" required defaultValue=""><option value="" disabled>Choose eligible appointment</option>{data?.appointmentOptions.map(option=><option key={option.id} value={option.id}>{option.patientName} · {new Date(option.scheduledStart).toLocaleDateString()}</option>)}</select></label><label>Approved imaging organization<select name="organization" required defaultValue=""><option value="" disabled>Choose imaging organization</option>{data?.partnerOptions.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label>Study type<input name="studyType" required placeholder="MRI without contrast"/></label><label>Body region<input name="bodyRegion" required placeholder="Right knee"/></label><label>Minimum necessary clinical indication<textarea name="indication" required minLength={5} maxLength={800}/></label><label>Patient preparation instructions<textarea name="preparation" required minLength={5} maxLength={800}/></label><label>Priority<select name="priority"><option value="routine">Routine</option><option value="urgent">Urgent</option></select></label><label className={styles.check}><input type="checkbox" name="authorized" required/>I am authorized to order this study for this patient.</label><label className={styles.check}><input type="checkbox" name="signed" required/>I sign this order and confirm the content is accurate and minimum necessary.</label><button className={styles.button} disabled={busy}>Issue signed order</button></form></section><section className={styles.panel}><h2>Issued orders</h2><div className={styles.grid}>{data?.orders.map(order=><article className={styles.card} key={order.id}><span className={`${styles.pill} ${order.priority==="urgent"?styles.urgent:""}`}>{order.priority} · {order.status}</span><h3>{order.studyType} · {order.bodyRegion}</h3><p>Signed {new Date(order.signedAt).toLocaleDateString()}</p></article>)}</div></section></main>;
}
