"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/ReyatiLocaleProvider";
import { reyatiDate } from "@/lib/reyati-i18n";
import s from "./home-care.module.css";

type Catalog = { id:string; organizationName:string; nameEn:string; nameAr:string; descriptionEn:string; descriptionAr:string; durationMinutes:number; feeQar:number };
type Worker = { displayName:string; roleLabelEn:string; roleLabelAr:string; credentialType:string; credentialReference:string; credentialStatus:string };
type RequestItem = { id:string; organizationName:string; serviceNameEn:string; serviceNameAr:string; status:string; version:number; requestedWindowStart:string; requestedWindowEnd:string; arrivalWindowStart?:string; arrivalWindowEnd?:string; area:string; completionSummary?:string; completionEvidenceReference?:string; paymentStatus:string; feedbackStatus:string; assignedWorker?:Worker|null; concerns:Array<{id:string;kind:string;status:string}> };
type Data = { patient:{displayName:string}; catalog:Catalog[]; requests:RequestItem[]; safetyNotice:string };
async function api(init?:RequestInit){const response=await fetch("/api/home-care",{cache:"no-store",credentials:"same-origin",...init}),payload=await response.json().catch(()=>({})) as {data?:unknown;message?:string;error?:string};if(response.status===401){location.assign("/signin-with-chatgpt?return_to=/home-care");throw Error("Authentication required")}if(!response.ok||payload.data===undefined)throw Error(payload.message||payload.error||"Home care is unavailable");return payload.data}

export default function HomeCarePage(){
  const {lang,setLang}=useReyatiLocale(),ar=lang==="ar",[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{setData(await api() as Data);setError("")}catch(e){setError(e instanceof Error?e.message:"Unavailable")}},[]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,value=new FormData(form);setBusy(true);try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"request",serviceId:value.get("serviceId"),addressLine:value.get("addressLine"),area:value.get("area"),windowStart:new Date(String(value.get("windowStart"))).toISOString(),windowEnd:new Date(String(value.get("windowEnd"))).toISOString(),accessInstructions:value.get("accessInstructions"),accessibilityNeeds:value.get("accessibilityNeeds"),mobilitySupport:value.get("mobilitySupport")==="on",infectionPrecautions:value.get("infectionPrecautions")==="on",petsPresent:value.get("petsPresent")==="on",clinicalNotes:value.get("clinicalNotes")})});form.reset();setNotice(ar?"تم إرسال طلب الرعاية المنزلية.":"Your home-care request was sent.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to request care")}finally{setBusy(false)}}
  async function act(item:RequestItem,action:string,extra:Record<string,unknown>={}){setBusy(true);try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,requestId:item.id,version:item.version,...extra})});setNotice(action==="raise_concern"?(ar?"تم إيقاف الزيارة وتصعيد البلاغ.":"The visit was placed on safety hold and escalated."):(ar?"تم تحديث الطلب.":"Request updated."));await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update request")}finally{setBusy(false)}}
  return <main className={`${s.shell} specialist-patient-shell clinical-module-experience home-care-experience`} dir={ar?"rtl":"ltr"} id="main-content"><header className={s.top}><a href="/"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav><a href="/providers">{ar?"ابحث عن رعاية":"Find care"}</a><a className={s.active} href="/home-care">{ar?"الرعاية المنزلية":"Home care"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a></nav><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></header>
    <section className={s.hero}><span className={s.eyebrow}>VERIFIED CARE, AT HOME</span><h1>{ar?"رعاية موثوقة تصل إلى بابك.":"Trusted care, brought to your door."}</h1><p>{ar?"اختر فقط من المؤسسات والخدمات المعتمدة. ستعرف من سيصل ومتى، ويمكنك إيقاف الزيارة والإبلاغ فوراً.":"Choose only from approved organizations and services. Know who is arriving and when, with an immediate safety hold if something feels wrong."}</p></section>
    <section className={s.body}>{error&&<div className={s.alert}>{error}</div>}{notice&&<div className={`${s.alert} ${s.success}`}>{notice}</div>}<div className={s.grid}><article className={s.card}><span className={s.eyebrow}>REQUEST HOME CARE</span><h2>{ar?"ما الذي تحتاجه؟":"What do you need?"}</h2><form className={s.form} onSubmit={create}><label>{ar?"المريض":"Patient"}<input value={data?.patient.displayName??""} disabled/></label><label>{ar?"خدمة معتمدة":"Approved service"}<select name="serviceId" required defaultValue=""><option value="" disabled>{ar?"اختر خدمة":"Choose a service"}</option>{data?.catalog.map(item=><option key={item.id} value={item.id}>{item.organizationName} · {ar?item.nameAr:item.nameEn} · QAR {item.feeQar}</option>)}</select></label><div className={s.row}><label>{ar?"العنوان":"Address"}<input name="addressLine" required maxLength={300}/></label><label>{ar?"المنطقة":"Area"}<input name="area" required maxLength={120}/></label></div><div className={s.row}><label>{ar?"بداية النافذة":"Window starts"}<input name="windowStart" type="datetime-local" required/></label><label>{ar?"نهاية النافذة":"Window ends"}<input name="windowEnd" type="datetime-local" required/></label></div><label>{ar?"احتياجات سهولة الوصول":"Accessibility needs"}<textarea name="accessibilityNeeds" maxLength={500}/></label><label>{ar?"تعليمات الدخول":"Access instructions"}<textarea name="accessInstructions" maxLength={500}/></label><label className={s.check}><input name="mobilitySupport" type="checkbox"/>{ar?"مطلوب دعم الحركة":"Mobility support needed"}</label><label className={s.check}><input name="infectionPrecautions" type="checkbox"/>{ar?"احتياطات العدوى":"Infection precautions"}</label><label className={s.check}><input name="petsPresent" type="checkbox"/>{ar?"يوجد حيوان أليف":"Pet present"}</label><label>{ar?"ملاحظات آمنة للفريق":"Safe intake notes"}<textarea name="clinicalNotes" maxLength={800}/></label><button className={s.primary} disabled={busy||!data?.catalog.length}>{ar?"إرسال الطلب":"Request home care"}</button>{data&&!data.catalog.length&&<small>{ar?"لا توجد خدمات منزلية معتمدة متاحة حالياً.":"No approved home-care services are available right now."}</small>}</form></article>
      <section className={s.list}><h2>{ar?"زياراتي المنزلية":"My home visits"}</h2>{data?.requests.map(item=><article className={s.request} key={item.id}><header><div><b>{ar?item.serviceNameAr:item.serviceNameEn}</b><span>{item.organizationName} · {item.area}</span></div><i className={s.status}>{item.status.replaceAll("_"," ")}</i></header><div className={s.details}><div><small>{ar?"الوقت المطلوب":"Requested window"}</small><b>{reyatiDate(item.requestedWindowStart,lang,{dateStyle:"medium",timeStyle:"short"})}</b></div><div><small>{ar?"نافذة الوصول":"Arrival window"}</small><b>{item.arrivalWindowStart?`${reyatiDate(item.arrivalWindowStart,lang,{timeStyle:"short"})} – ${reyatiDate(item.arrivalWindowEnd!,lang,{timeStyle:"short"})}`:(ar?"بانتظار التأكيد":"Pending confirmation")}</b></div><div><small>{ar?"الدفع":"Payment"}</small><b>{item.paymentStatus.replaceAll("_"," ")}</b></div><div><small>{ar?"التقييم":"Feedback"}</small><b>{item.feedbackStatus.replaceAll("_"," ")}</b></div></div>{item.assignedWorker&&<div className={s.worker}><b>{item.assignedWorker.displayName}</b><small>{ar?item.assignedWorker.roleLabelAr:item.assignedWorker.roleLabelEn} · {item.assignedWorker.credentialType} {item.assignedWorker.credentialReference} · {item.assignedWorker.credentialStatus}</small></div>}<p className={s.safety}>{data.safetyNotice}</p>{item.completionSummary&&<p><b>{ar?"ملخص الإكمال: ":"Completion summary: "}</b>{item.completionSummary}{item.completionEvidenceReference&&<> · <span>{ar?"مرجع الإثبات":"Evidence reference"}: {item.completionEvidenceReference}</span></>}</p>}<div className={s.actions}>{["requested","accepted","assigned"].includes(item.status)&&<button className={s.quiet} disabled={busy} onClick={()=>void act(item,"cancel")}>{ar?"إلغاء الطلب":"Cancel request"}</button>}</div>{!["rejected","cancelled"].includes(item.status)&&<form className={`${s.form} ${s.compact}`} onSubmit={event=>{event.preventDefault();const value=new FormData(event.currentTarget);void act(item,"raise_concern",{kind:value.get("kind"),summary:value.get("summary")});event.currentTarget.reset()}}><label>{ar?"مشكلة عاجلة":"Urgent issue"}<select name="kind"><option value="identity_mismatch">Identity mismatch</option><option value="safety_concern">Safety concern</option><option value="missed_visit">Missed visit</option></select></label><label>{ar?"ما الذي حدث؟":"What happened?"}<input name="summary" required maxLength={800}/></label><button className={s.danger} disabled={busy}>{ar?"إيقاف وتصعيد":"Hold & escalate"}</button></form>}</article>)}{data&&!data.requests.length&&<div className={s.empty}>{ar?"لا توجد طلبات رعاية منزلية بعد.":"No home-care requests yet."}</div>}</section></div></section></main>}
