"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "../../benefits/benefits.module.css";

type Programme = { id: string; nameEn: string; nameAr: string; descriptionEn: string; descriptionAr: string; currency: string; memberLimitMinor: number; startsAt: string; endsAt: string; eligibilityMode: string; status: string; rosterSummary: Record<string, number>; fundingBalanceMinor: number; fundingEntries: Array<{ id: string; entryType: string; direction: string; amountMinor: number; sourceReference: string }> };
type Data = { partner: { organizationName: string; role: string }; programmes: Programme[]; boundaries: Record<string, boolean> };
async function api(init?: RequestInit) { const response = await fetch("/api/partner/benefits", { cache: "no-store", ...init }); const payload = await response.json(); if (response.status === 401) { location.assign("/sign-in?redirect_url=/partner/benefits"); throw new Error("Sign in required"); } if (!response.ok) throw new Error(payload.message || payload.error || "Benefits workspace unavailable"); return payload.data as Data; }
const qar = (minor: number, ar: boolean) => new Intl.NumberFormat(ar ? "ar-QA" : "en-QA", { style: "currency", currency: "QAR" }).format(minor / 100);

export default function PartnerBenefitsPage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(() => api().then(setData), []); useEffect(() => { queueMicrotask(() => void load().catch((reason) => setError(reason.message))); }, [load]);
  async function submit(e: FormEvent<HTMLFormElement>, action: string, programmeId?: string) { e.preventDefault(); const form = e.currentTarget, values = new FormData(form), body = Object.fromEntries(values.entries()) as Record<string, unknown>; if (body.memberLimitQar) body.memberLimitMinor = Math.round(Number(body.memberLimitQar) * 100); if (body.benefitLimitQar) body.benefitLimitMinor = Math.round(Number(body.benefitLimitQar) * 100); if (body.amountQar) body.amountMinor = Math.round(Number(body.amountQar) * 100); if (action === "append_funding_entry") body.idempotencyKey = crypto.randomUUID(); setBusy(true); setError(""); setNotice(""); try { await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, action, programmeId }) }); form.reset(); setNotice(ar ? "تمت إضافة السجل المنضبط." : "Controlled record added."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save"); } finally { setBusy(false); } }
  return <main className={styles.shell} dir={ar ? "rtl" : "ltr"}><header className={styles.top}><a href="/partner"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya" /></a><nav><a href="/partner">{ar ? "مساحة الشركاء" : "Partner home"}</a><button onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></nav></header>
    <section className={styles.hero}><small>{ar ? "برنامج مزايا منضبط" : "BOUNDED BENEFIT PROGRAMMES"}</small><h1>{ar ? "الأهلية دون كشف الصحة." : "Eligibility without health visibility."}</h1><p>{ar ? "أنشئ مسودات برامج محدودة، وأضف أهلية اصطناعية أو مرتبطة بدعوة، وسجّل التمويل في دفتر غير قابل للتعديل. لا توجد حركة أموال خارجية." : "Create bounded draft programmes, add synthetic or invitation-bound eligibility, and record funding in an immutable ledger. No external money movement occurs."}</p></section>
    <section className={styles.body}>{error && <p className={styles.error}>{error}</p>}{notice && <p className={styles.notice}>{notice}</p>}<div className={styles.partnerGrid}><aside className={styles.panel}><h2>{ar ? "مسودة برنامج جديد" : "New programme draft"}</h2><p className={styles.boundary}>{ar ? "لا يمكن نشر المسودات أو استخدامها للمطالبات أو الدفع." : "Drafts cannot be published or used for claims or payments."}</p><form className={styles.form} onSubmit={(e) => void submit(e, "create_programme")}><label>English name<input name="nameEn" required maxLength={100} /></label><label>الاسم بالعربية<input name="nameAr" required maxLength={100} dir="rtl" /></label><label>English description<textarea name="descriptionEn" required maxLength={500} /></label><label>الوصف بالعربية<textarea name="descriptionAr" required maxLength={500} dir="rtl" /></label><label>{ar ? "حد العضو (ر.ق)" : "Member limit (QAR)"}<input name="memberLimitQar" type="number" min="1" max="1000000" step="0.01" required /></label><div className={styles.row}><label>{ar ? "البداية" : "Starts"}<input name="startsAt" type="date" required /></label><label>{ar ? "النهاية" : "Ends"}<input name="endsAt" type="date" required /></label></div><label>{ar ? "وضع الأهلية" : "Eligibility mode"}<select name="eligibilityMode"><option value="invitation_bound">Invitation bound</option><option value="synthetic">Synthetic rehearsal</option></select></label><button className={styles.primary} disabled={busy}>{ar ? "إنشاء مسودة" : "Create draft"}</button></form></aside>
      <section className={styles.list}>{data?.programmes.map((programme) => <article className={styles.card} key={programme.id}><header><div><small>{data.partner.organizationName}</small><h2>{ar ? programme.nameAr : programme.nameEn}</h2></div><em>{programme.status}</em></header><p>{ar ? programme.descriptionAr : programme.descriptionEn}</p><div className={styles.summary}><div><small>{ar ? "المعروض" : "Offered"}</small><b>{programme.rosterSummary.offered}</b></div><div><small>{ar ? "المقبول" : "Accepted"}</small><b>{programme.rosterSummary.accepted}</b></div><div><small>{ar ? "رصيد التمويل" : "Funding ledger"}</small><b>{qar(programme.fundingBalanceMinor, ar)}</b></div></div><div className={styles.partnerForms}><form className={styles.form} onSubmit={(e) => void submit(e, "add_eligibility", programme.id)}><h3>{ar ? "إضافة أهلية" : "Add eligibility"}</h3>{programme.eligibilityMode === "synthetic" ? <label>{ar ? "مرجع اصطناعي" : "Synthetic reference"}<input name="syntheticReference" required maxLength={80} /></label> : <label>{ar ? "بريد الدعوة" : "Invitation email"}<input name="invitationEmail" type="email" required maxLength={254} /></label>}<label>{ar ? "حد الميزة (ر.ق)" : "Benefit limit (QAR)"}<input name="benefitLimitQar" type="number" min="1" max={programme.memberLimitMinor / 100} step="0.01" required /></label><button className={styles.primary} disabled={busy}>{ar ? "إضافة للسجل" : "Add to roster"}</button></form><form className={styles.form} onSubmit={(e) => void submit(e, "append_funding_entry", programme.id)}><h3>{ar ? "إضافة قيد تمويل" : "Append funding entry"}</h3><div className={styles.row}><label>{ar ? "النوع" : "Type"}<select name="entryType"><option value="programme_allocation">Allocation</option><option value="programme_adjustment">Adjustment</option></select></label><label>{ar ? "الاتجاه" : "Direction"}<select name="direction"><option value="credit">Credit</option><option value="debit">Debit</option></select></label></div><label>{ar ? "المبلغ (ر.ق)" : "Amount (QAR)"}<input name="amountQar" type="number" min="0.01" max="1000000" step="0.01" required /></label><label>{ar ? "مرجع المصدر" : "Source reference"}<input name="sourceReference" required maxLength={120} /></label><button disabled={busy}>{ar ? "إضافة قيد ثابت" : "Append immutable entry"}</button></form></div></article>)}{data && !data.programmes.length && <div className={styles.empty}><h2>{ar ? "لا توجد مسودات" : "No programme drafts"}</h2><p>{ar ? "ابدأ بمسودة محدودة من اللوحة." : "Start with a bounded draft from the panel."}</p></div>}</section></div></section>
  </main>;
}
