"use client";

import { useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";

type Health = {
  operatorName: string; role: string; generatedAt: string; databaseReachable: boolean;
  metrics: { authFailures24h: number; blockedOrFailedActions24h: number; openSupport: number; criticalSupport: number; staleSupport: number; expiredPendingAppointments: number; communicationAttention: number; failedWebhookReceipts: number; activeRateLimitedBuckets: number; documentUploadCleanupBacklog: number; documentScanBacklog: number; documentScanStalled: number; documentDeletionAttention: number };
  controls: { id: string; name: string; status: "implemented" | "documented" | "partial" | "blocked"; note: string }[];
  pilotReadiness: { decision: "not_ready"; cleared: number; total: number; gates: { id: string; name: string; status: "cleared" | "blocked"; evidence: string; ownerNeeded: boolean }[] };
  communicationStatuses: { status: string; count: number }[];
  recentSignals: { source: string; event: string; context: string; outcome: string; createdAt: string }[];
};

function words(value: string, ar = false) { const labels: Record<string, string> = { implemented: "مطبق", documented: "موثق", partial: "جزئي", blocked: "محظور", platform_admin: "مدير المنصة", security_auditor: "مدقق أمني", success: "ناجح", failed: "فشل" }; return ar ? labels[value] || value.replaceAll("_", " ").replaceAll(".", " · ") : value.replaceAll("_", " ").replaceAll(".", " · ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function initials(value: string) { return value.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "OP"; }

async function readHealth() {
  const response = await fetch("/api/admin/operations", { credentials: "same-origin" });
  if (response.status === 401) throw new Error("auth");
  if (response.status === 403) throw new Error("forbidden");
  const payload = await response.json().catch(() => ({})) as { data?: Health };
  if (!response.ok || !payload.data) throw new Error("unavailable");
  return payload.data;
}

export default function OperationsHealthPage() {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar";
  const [data, setData] = useState<Health | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  function load() { setLoading(true); setError(""); readHealth().then(setData).catch((caught: Error) => setError(caught.message)).finally(() => setLoading(false)); }
  useEffect(() => { let active = true; readHealth().then((next) => { if (active) setData(next); }).catch((caught: Error) => { if (active) setError(caught.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const avatar = initials(data?.operatorName ?? "Operations");
  const blockers = data?.controls.filter((control) => control.status === "blocked").length ?? 0;
  const metrics = data ? [
    [ar ? "إشارات المصادقة" : "Authentication signals", data.metrics.authFailures24h, ar ? "نتائج غير ناجحة خلال 24 ساعة" : "Non-success outcomes in 24 hours", "/admin/audit"],
    [ar ? "الإجراءات المحظورة" : "Blocked actions", data.metrics.blockedOrFailedActions24h, ar ? "مسجلة خلال آخر 24 ساعة" : "Recorded in the last 24 hours", "/admin/audit"],
    [ar ? "الدعم الذي يحتاج انتباهاً" : "Support attention", data.metrics.openSupport, ar ? `${data.metrics.criticalSupport} حرجة · ${data.metrics.staleSupport} قديمة` : `${data.metrics.criticalSupport} critical · ${data.metrics.staleSupport} stale`, "/admin/cases"],
    [ar ? "الاتصالات التي تحتاج انتباهاً" : "Communication attention", data.metrics.communicationAttention, data.communicationStatuses.map((row) => `${words(row.status, ar)} ${row.count}`).join(" · ") || (ar ? "لا توجد حالات إعادة محاولة أو فشل" : "No retry or failure states"), "/admin/communications"],
  ] as const : [];

  return <main className={`ops-health-shell ${ar ? "arabic" : ""}`} dir={ar ? "rtl" : "ltr"} id="main-content"><aside className="ops-health-side"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar ? "عمليات المنصة" : "Platform operations"}</span></a><div className="ops-health-role"><span>{avatar}</span><div><b>{data?.operatorName ?? (ar ? "مراجع العمليات" : "Operations reviewer")}</b><small>{data ? words(data.role, ar) : ar ? "جارٍ التحقق من الوصول المحمي" : "Checking protected access"}</small></div></div><nav><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a className="active" href="/admin/operations">{ar ? "صحة النظام" : "System health"}</a><a href="/admin/communications">{ar ? "الاتصالات" : "Communications"}</a><a href="/admin/cases">{ar ? "حالات الدعم" : "Support cases"}</a><a href="/admin/audit">{ar ? "سجل التدقيق" : "Audit ledger"}</a></nav><div className="ops-health-privacy"><span>▣</span><p><b>{ar ? "بيانات تشغيلية فقط" : "Operational metadata only"}</b>{ar ? "لا تظهر هنا هوية المريض أو المحتوى السريري أو تفاصيل المستلم أو بيانات التدقيق." : "No patient identity, clinical content, support descriptions, recipient details, or audit payloads appear here."}</p></div></aside>
    <section className="ops-health-main"><header className="ops-health-top"><div><span>{ar ? "عمليات البرنامج التجريبي" : "PILOT OPERATIONS"}</span><b>{ar ? "جاهزية نظام آمنة للخصوصية" : "Privacy-safe system readiness"}</b></div><div><button className="lang" type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button><a href="/notifications" aria-label={ar ? "الإشعارات" : "Notifications"}>●</a><span>{avatar}</span></div></header><div className="ops-health-workspace">
      <div className="ops-health-heading"><div><p>{ar ? "الموثوقية والأمن" : "RELIABILITY & SECURITY"}</p><h1>{ar ? "مركز صحة النظام" : "System health centre"}</h1><span>{ar ? "إشارات تشغيلية مباشرة وضوابط جاهزية واضحة للبرنامج التجريبي المنضبط." : "Live operational signals and honest readiness controls for the controlled-pilot foundation."}</span></div><button type="button" disabled={loading} onClick={load}>↻ {loading ? (ar ? "جارٍ التحديث…" : "Refreshing…") : (ar ? "تحديث" : "Refresh")}</button></div>
      <div className="ops-health-banner"><span>{data?.databaseReachable ? "✓" : "!"}</span><div><b>{data?.databaseReachable ? (ar ? "استجابت قاعدة البيانات الأساسية" : "Core database responded") : (ar ? "حالة الصحة غير متاحة" : "Health status unavailable")}</b><p>{ar ? "يؤكد هذا قراءة محمية فقط، ولا يمثل ادعاءً باكتمال المراقبة أو جاهزية البرنامج التجريبي." : "This confirms a protected read only. It is not a claim of full monitoring coverage or pilot readiness."}</p></div><i>{blockers} {ar ? "عوائق تجريبية" : "PILOT BLOCKERS"}</i></div>
      {error && <section className="ops-health-state" role="alert"><span>!</span><h2>{error === "auth" ? "Sign in required" : error === "forbidden" ? "Operations access required" : "System health is unavailable"}</h2><p>{error === "forbidden" ? "A platform administrator or security-auditor role is required." : "Try again or use the support workspace if the problem continues."}</p></section>}
      {!error && loading && !data && <section className="ops-health-state" aria-live="polite"><span>◌</span><h2>{ar ? "جارٍ تحميل إشارات الصحة المحمية" : "Loading protected health signals"}</h2></section>}
      {data && <><section className="ops-health-metrics">{metrics.map(([name, value, note, href]) => <a href={href} key={name}><span>{value}</span><div><b>{name}</b><p>{note}</p></div><i>→</i></a>)}</section>
        <section className="pilot-readiness"><div className="pilot-readiness-head"><div><p>{ar ? "قرار الإطلاق المنضبط" : "CONTROLLED-PILOT DECISION"}</p><h2>{ar ? "غير جاهز للإطلاق التجريبي بعد" : "Not yet cleared for pilot launch"}</h2><span>{ar ? "يعرض هذا القرار الضوابط المثبتة والعوائق البشرية أو الخارجية المتبقية. لا يمكن تجاوز العوائق من هذه الشاشة." : "This decision separates evidenced controls from remaining human or external blockers. Blockers cannot be overridden from this screen."}</span></div><strong><b>{data.pilotReadiness.cleared}/{data.pilotReadiness.total}</b>{ar ? "بوابات مكتملة" : "gates cleared"}</strong></div><div className="pilot-readiness-gates">{data.pilotReadiness.gates.map((gate) => <article key={gate.id}><span className={gate.status}>{gate.status === "cleared" ? "✓" : "!"}</span><div><b>{ar ? ({ application_safety: "خط أساس سلامة التطبيق", incident_ownership: "ملكية الحوادث والتصعيد", monitoring_coverage: "المراقبة والتنبيه الأمني", recovery_evidence: "دليل الاسترداد المستضاف", data_lifecycle: "دورة حياة البيانات السريرية" }[gate.id] || gate.name) : gate.name}</b><p>{gate.evidence}</p></div><i className={gate.status}>{gate.status === "cleared" ? (ar ? "مكتملة" : "CLEARED") : (ar ? "عائق" : "BLOCKED")}</i></article>)}</div><footer><span>i</span><p>{ar ? "يتطلب قرار الانطلاق أسماء مالكي الضوابط وأدلة التشغيل، وليس تغيير حالة برمجية فقط." : "A launch decision requires named control owners and operating evidence—not only a software status change."}</p></footer></section>
        <section className="ops-health-grid"><article className="ops-health-panel"><div className="ops-health-panel-head"><div><h2>{ar ? "حالة ضوابط الإنتاج" : "Production control status"}</h2><p>{ar ? "ضوابط مطبقة وموثقة وجزئية ومحظورة خارجياً." : "Implemented, documented, partial, and externally blocked controls."}</p></div><b>{data.controls.filter((control) => control.status === "implemented").length}/{data.controls.length}</b></div><div className="ops-health-controls">{data.controls.map((control) => <div key={control.id}><span className={control.status}>{control.status === "implemented" ? "✓" : control.status === "blocked" ? "—" : "i"}</span><div><b>{control.name}</b><p>{control.note}</p></div><i className={control.status}>{words(control.status, ar)}</i></div>)}</div></article>
          <article className="ops-health-panel"><div className="ops-health-panel-head"><div><h2>{ar ? "إشارات الأمن الأخيرة" : "Recent security signals"}</h2><p>{ar ? "أحداث غير ناجحة محدودة دون أشخاص أو معرفات سجلات أو بيانات." : "Bounded non-success events without people, record IDs, or payloads."}</p></div><time>{new Date(data.generatedAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</time></div><div className="ops-health-signals">{data.recentSignals.length ? data.recentSignals.map((signal, index) => <div key={`${signal.createdAt}:${signal.event}:${index}`}><span className={signal.source}/><div><b>{words(signal.event, ar)}</b><p>{words(signal.source, ar)} · {words(signal.context, ar)}</p></div><i>{words(signal.outcome, ar)}</i><time>{new Date(signal.createdAt).toLocaleString(ar ? "ar-QA" : "en-QA", { dateStyle: "short", timeStyle: "short" })}</time></div>) : <div className="empty"><span>✓</span><b>{ar ? "لا توجد إشارات غير ناجحة مسجلة" : "No non-success signals recorded"}</b><p>{ar ? "يعني ذلك عدم وجودها في السجل الحالي؛ المراقبة الخارجية لم تُربط بعد." : "This means none are present in the current ledger; external monitoring is still not connected."}</p></div>}</div></article></section>
        <section className="ops-health-foot"><div><b>{ar ? "حاويات الحد النشط" : "Active rate-limited buckets"}</b><span>{data.metrics.activeRateLimitedBuckets}</span><p>{ar ? "حاويات كتابة مجزأة تجاوزت حدها المسموح حالياً." : "Hashed write buckets currently over their permitted threshold."}</p></div><div><b>{ar ? "عمليات رفع تحتاج تنظيفاً" : "Upload cleanup backlog"}</b><span>{data.metrics.documentUploadCleanupBacklog}</span><p>{ar ? "جلسات رفع منتهية أو فاشلة مؤهلة للمصالحة الآمنة." : "Expired or failed upload sessions eligible for safe reconciliation."}</p></div><div><b>{ar ? "مستندات بانتظار الفحص" : "Scan backlog"}</b><span>{data.metrics.documentScanBacklog}</span><p>{ar ? `${data.metrics.documentScanStalled} متوقفة وتحتاج استرداداً` : `${data.metrics.documentScanStalled} stalled and eligible for recovery`}</p></div><div><b>{ar ? "حذف يحتاج انتباهاً" : "Deletion attention"}</b><span>{data.metrics.documentDeletionAttention}</span><p>{ar ? "مهام حذف معاد محاولتها أو فاشلة أو محظورة." : "Deletion jobs currently retrying, failed, or blocked."}</p></div><div><b>{ar ? "إيصالات Webhook فاشلة" : "Failed webhook receipts"}</b><span>{data.metrics.failedWebhookReceipts}</span><p>{ar ? "سجلات إيصالات متحقق منها وموسومة بالفشل." : "Verified receipt records currently marked failed."}</p></div><a href="/admin/audit">{ar ? "فتح سجل التدقيق الكامل ←" : "Open complete audit ledger →"}</a></section></>}
    </div></section></main>;
}
