"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import styles from "../../payment-support/finance-controls.module.css";

type FinanceCase={id:string;patientName:string;ledgerAmountQar:number;ledgerCurrency:string;ledgerStatus:string;requestType:string;reasonCode:string;patientSummary:string;requestedAmountQar:number|null;status:string;patientStatusNote:string;version:number;updatedAt:string};
type Decision={id:string;caseId:string;makerUserId:string;decisionType:string;approvedAmountQar:number|null;status:string;preparedAt:string};
type Adjustment={id:string;caseId:string;adjustmentType:string;amountQar:number;executionStatus:string};
type RefundExecution={id:string;caseId:string;adjustmentId:string;providerRefundId:string|null;status:string;createdAt:string};
type Data={cases:FinanceCase[];pendingDecisions:Decision[];adjustments:Adjustment[];refundExecutions:RefundExecution[];refundProvider:{refundsReady:boolean;mode:"test"|"live"|null};metrics:Record<string,number>;rehearsals:Array<{id:string;result:string;scenarioCount:number;executedAt:string}>;boundaries:Record<string,unknown>;governanceVisibility:string};
async function api(init?:RequestInit){const response=await fetch("/api/admin/finance-controls",{cache:"no-store",...init});const payload=await response.json();if(response.status===401){location.assign("/sign-in?redirect_url=%2Fadmin%2Ffinance-controls");throw new Error("Sign in required")}if(!response.ok)throw new Error(payload.message||payload.error||"Finance controls unavailable");return payload.data}

export default function FinanceControlsAdmin(){
  const[data,setData]=useState<Data|null>(null),[selected,setSelected]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(()=>api().then((next:Data)=>{setData(next);setSelected(current=>current||next.cases[0]?.id||"")}),[]);useEffect(()=>{queueMicrotask(()=>void load().catch(e=>setError(e.message)))},[load]);
  const item=useMemo(()=>data?.cases.find(row=>row.id===selected),[data,selected]);const pending=data?.pendingDecisions.find(row=>row.caseId===selected);const adjustment=data?.adjustments.find(row=>row.caseId===selected);const refundExecution=adjustment?data?.refundExecutions.find(row=>row.adjustmentId===adjustment.id):undefined;
  async function action(payload:Record<string,unknown>){setBusy(true);setError("");try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});await load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
  async function prepare(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!item)return;const values=new FormData(event.currentTarget);await action({action:"prepare_decision",caseId:item.id,version:item.version,decisionType:values.get("decision"),reasonCode:values.get("reason"),approvedAmountQar:values.get("amount"),makerNote:values.get("note")})}
  async function executeRefund(){if(!item||!adjustment)return;setBusy(true);setError("");try{const response=await fetch("/api/admin/finance-controls/refunds",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({caseId:item.id,adjustmentId:adjustment.id,version:item.version})});const payload=await response.json();if(!response.ok)throw new Error(payload.message||payload.error||"Refund request failed");await load()}catch(e){setError(e instanceof Error?e.message:"Refund request failed")}finally{setBusy(false)}}
  return <main className={styles.console}><aside className={styles.side}><img src="/brand/qivaya-logo-reversed.png" alt="Qivaya"/><a href="/admin">Operations</a><a className={styles.active} href="/admin/finance-controls">Finance controls</a><a href="/admin/finance">Finance overview</a><p>Operational case access is role-scoped. Governance metrics and rehearsal results are aggregate only.<br/>الوصول للحالات مقيّد حسب الدور.</p></aside><section className={styles.work}><header><b>Finance control plane · منصة الضوابط المالية</b><a href="/admin">Admin home</a></header><div className={styles.content}><span className={styles.eyebrow}>MAKER–CHECKER · FOUR-EYES CONTROL</span><h1>Review, approve, reconcile.</h1><p>Every financial resolution requires an independent checker. Approved adjustments are append-only records—not gateway instructions or money movement.</p>{error&&<p className={styles.error}>{error}</p>}
    <div className={styles.metrics}>{Object.entries(data?.metrics||{}).map(([key,value])=><article key={key}><b>{value}</b><span>{key.replaceAll("_"," ")}</span></article>)}</div>
    <div className={styles.adminGrid}><section className={styles.caseRail}><h2>Case queue · قائمة الحالات</h2>{data?.cases.map(row=><button className={`${styles.caseButton} ${selected===row.id?styles.selected:""}`} key={row.id} onClick={()=>setSelected(row.id)}><span><b>{row.patientName}</b><small>{row.requestType.replaceAll("_"," ")} · {row.ledgerAmountQar} {row.ledgerCurrency}</small></span><em>{row.status.replaceAll("_"," ")}</em></button>)}</section>
      <section className={styles.caseWork}>{item?<><header className={styles.caseHeader}><div><span className={styles.eyebrow}>{item.reasonCode.replaceAll("_"," ")}</span><h2>{item.patientName}</h2></div><em className={styles.status}>{item.status.replaceAll("_"," ")}</em></header><div className={styles.caseFacts}><span>Ledger: {item.ledgerAmountQar} {item.ledgerCurrency}</span><span>Ledger status: {item.ledgerStatus}</span><span>Requested: {item.requestedAmountQar??"Review only"}</span></div><p className={styles.patientText}>{item.patientSummary}</p>
        {item.status==="submitted"&&<button className={styles.primary} disabled={busy} onClick={()=>void action({action:"triage",caseId:item.id,version:item.version,triageCode:"standard_review"})}>Triage case · فرز الحالة</button>}
        {["submitted","triaged"].includes(item.status)&&<form className={styles.form} onSubmit={prepare}><h3>Maker proposal · اقتراح المُعد</h3><div className={styles.row}><label>Decision<select name="decision"><option value="approve_refund">Record refund approval</option><option value="approve_adjustment">Record adjustment approval</option><option value="decline">Decline request</option><option value="request_information">Request information</option></select></label><label>Amount QAR<input name="amount" type="number" min="1" max={item.ledgerAmountQar}/></label></div><label>Reason code<input name="reason" required maxLength={80} defaultValue="review_completed"/></label><label>Maker note<textarea name="note" required maxLength={1000}/></label><button className={styles.primary} disabled={busy}>Send to independent checker</button></form>}
        {item.status==="pending_checker"&&pending&&<div className={styles.checker}><h3>Checker review · مراجعة المدقق</h3><p>{pending.decisionType.replaceAll("_"," ")} · {pending.approvedAmountQar??"No financial adjustment"} QAR</p><label>Checker note<textarea id="checker-note" maxLength={1000}/></label><div className={styles.actions}><button className={styles.primary} disabled={busy} onClick={()=>void action({action:"check_decision",caseId:item.id,decisionId:pending.id,version:item.version,checkerAction:"approve",checkerNote:(document.getElementById("checker-note") as HTMLTextAreaElement)?.value})}>Approve as checker</button><button className={styles.danger} disabled={busy} onClick={()=>void action({action:"check_decision",caseId:item.id,decisionId:pending.id,version:item.version,checkerAction:"reject",checkerNote:(document.getElementById("checker-note") as HTMLTextAreaElement)?.value})}>Return to maker</button></div></div>}
        {item.status==="approved_recorded"&&adjustment?.adjustmentType==="refund_record"&&<div className={styles.checker}><h3>Provider refund execution · تنفيذ الاسترداد</h3>{refundExecution?<p><b>{refundExecution.status.replaceAll("_"," ")}</b>{refundExecution.providerRefundId?` · ${refundExecution.providerRefundId}`:""}<br/>The ledger changes only after a signed Stripe webhook confirms the refund.</p>:data?.refundProvider.refundsReady?<><p>This executes the independently approved full refund through Stripe. It is not automatic and cannot exceed the captured amount.</p><button className={styles.primary} disabled={busy} onClick={()=>void executeRefund()}>Execute approved refund</button></>:<p>Stripe refund execution is locked. Set the dedicated refund activation gate only after checkout and signed webhooks are operational.</p>}</div>}
        {item.status==="approved_recorded"&&(adjustment?.adjustmentType!=="refund_record"||refundExecution?.status==="confirmed")&&<div className={styles.checker}><h3>Append reconciliation evidence</h3><p>Use a reference only. Never paste card details, bank credentials, or patient documents.</p><div className={styles.row}><input id="evidence-type" placeholder="Evidence type" defaultValue={refundExecution?.status==="confirmed"?"stripe_refund_confirmation":""}/><input id="evidence-reference" placeholder="Reference-only identifier" defaultValue={refundExecution?.providerRefundId??""}/></div><button className={styles.primary} disabled={busy} onClick={()=>void action({action:"add_reconciliation_evidence",caseId:item.id,version:item.version,evidenceType:(document.getElementById("evidence-type") as HTMLInputElement)?.value,evidenceReference:(document.getElementById("evidence-reference") as HTMLInputElement)?.value})}>Record evidence</button></div>}
        {["declined","reconciled"].includes(item.status)&&<button className={styles.quiet} disabled={busy} onClick={()=>void action({action:"close_case",caseId:item.id,version:item.version,resolutionCode:"controlled_review_complete",patientStatusNote:item.status==="declined"?"Your request was reviewed and declined.":"Your finance review and reconciliation are complete."})}>Close with transparent status</button>}
      </>:<div className={styles.empty}>Select a finance case.</div>}</section></div>
    <section className={styles.governance}><article><h2>Hard boundaries · حدود ثابتة</h2><ul><li>No automatic refunds, settlements, or payouts</li><li>Provider refunds require an approved full-value adjustment and separate executor</li><li>The ledger changes only after a signed provider webhook</li><li>No card storage</li></ul><button className={styles.primary} disabled={busy} onClick={()=>void action({action:"run_rehearsal"})}>Run 18-scenario zero-side-effect rehearsal</button></article><article><h2>Aggregate assurance</h2>{data?.rehearsals.map(row=><p className={styles.rehearsal} key={row.id}><b>{row.result} · {row.scenarioCount} scenarios</b><small>{new Date(row.executedAt).toLocaleString()} · zero provider calls · zero money movements</small></p>)}{data&&!data.rehearsals.length&&<p>No rehearsals recorded.</p>}</article></section>
  </div></section></main>;
}
