"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import { reyatiDate, reyatiNumber } from "@/lib/reyati-i18n";
type Operator = { userId: string; displayName: string; role: string };
type PolicyEvent = { id: string; action: string; note: string; actorName: string; createdAt: string };
type Policy = { id: string; recordClass: string; retentionMonths: number; retentionTrigger: string; disposition: string; legalBasisReference: string; evidenceReference: string; ownerUserId: string; ownerName: string; status: string; reviewerName: string | null; version: number; events: PolicyEvent[] };
type Data = { role: string; currentUserId: string; recordClasses: string[]; retentionTriggers: string[]; dispositions: string[]; operators: Operator[]; policies: Policy[] };
const labels: Record<string, { en: string; ar: string }> = {
  finalized_encounters: { en: "Finalized encounter records", ar: "سجلات الزيارات النهائية" }, medical_documents: { en: "Medical documents", ar: "المستندات الطبية" }, appointment_records: { en: "Appointment records", ar: "سجلات المواعيد" }, audit_security_events: { en: "Audit and security events", ar: "أحداث التدقيق والأمن" }, communications_metadata: { en: "Communications metadata", ar: "بيانات الاتصالات الوصفية" }, record_created: { en: "Record created", ar: "إنشاء السجل" }, encounter_finalized: { en: "Encounter finalized", ar: "إتمام الزيارة" }, appointment_completed: { en: "Appointment completed", ar: "إكمال الموعد" }, account_closed: { en: "Account closed", ar: "إغلاق الحساب" }, event_recorded: { en: "Event recorded", ar: "تسجيل الحدث" }, review_then_delete: { en: "Review, then delete", ar: "مراجعة ثم حذف" }, archive_then_review: { en: "Archive, then review", ar: "أرشفة ثم مراجعة" }, retain_under_healthcare_rule: { en: "Retain under healthcare rule", ar: "احتفاظ بموجب قاعدة صحية" }, draft: { en: "Draft", ar: "مسودة" }, pending_review: { en: "Pending review", ar: "بانتظار المراجعة" }, approved: { en: "Approved", ar: "معتمد" }, rejected: { en: "Rejected", ar: "مرفوض" }, retired: { en: "Retired", ar: "متقاعد" },
};
async function api(init?: RequestInit) { const response = await fetch("/api/admin/data-lifecycle", { credentials: "same-origin", ...init }); const payload = await response.json().catch(() => ({})) as { data?: unknown; message?: string; error?: string }; if (response.status === 401) { window.location.assign(`/signin-with-chatgpt?return_to=${encodeURIComponent("/admin/data-lifecycle")}`); throw new Error("Authentication required"); } if (!response.ok || payload.data === undefined) throw new Error(payload.message || payload.error || "Data lifecycle workspace unavailable"); return payload.data; }
export default function DataLifecycleCentre() {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar"; const [data, setData] = useState<Data | null>(null); const [selectedClass, setSelectedClass] = useState("finalized_encounters"); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setData(await api() as Data); }
  useEffect(() => { let active = true; api().then((value) => { if (active) setData(value as Data); }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "Workspace unavailable"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const policies = useMemo(() => new Map((data?.policies ?? []).map((item) => [item.recordClass, item])), [data]); const selected = policies.get(selectedClass); const approved = data?.policies.filter((item) => item.status === "approved").length ?? 0; const copy = (value: string) => labels[value]?.[ar ? "ar" : "en"] ?? value.replaceAll("_", " ");
  async function submit(body: Record<string, unknown>) { setBusy(true); setError(""); try { await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setNotice(ar ? "تم تسجيل سياسة دورة الحياة وتحديث سجل الأدلة." : "Lifecycle policy recorded and evidence trail updated."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Change could not be saved"); } finally { setBusy(false); } }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ operation: "save", recordClass: selectedClass, version: selected?.version, retentionMonths: Number(form.get("retentionMonths")), retentionTrigger: form.get("retentionTrigger"), disposition: form.get("disposition"), legalBasisReference: form.get("legalBasisReference"), evidenceReference: form.get("evidenceReference"), ownerUserId: form.get("ownerUserId") }); }
  function transition(action: string, event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; void submit({ operation: "transition", policyId: selected.id, version: selected.version, action, note: new FormData(event.currentTarget).get("note") }); }
  return <main className={`lifecycle-shell ${ar ? "arabic" : ""}`} dir={ar ? "rtl" : "ltr"} id="main-content">
    <aside className="lifecycle-side"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar ? "عمليات المنصة" : "Platform operations"}</span></a><nav><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a href="/admin/operations">{ar ? "جاهزية البرنامج" : "Pilot readiness"}</a><a href="/admin/ownership">{ar ? "الملكية" : "Ownership"}</a><a href="/admin/incidents">{ar ? "الحوادث" : "Incidents"}</a><a href="/admin/recovery">{ar ? "الاستعادة" : "Recovery"}</a><a className="active" href="/admin/data-lifecycle">{ar ? "دورة حياة البيانات" : "Data lifecycle"}</a><a href="/admin/audit">{ar ? "سجل التدقيق" : "Audit ledger"}</a></nav><div><b>{ar ? "الحذف يبقى معطلاً" : "Deletion remains disabled"}</b><p>{ar ? "اعتماد سياسة لا يشغّل جدولة الحذف أو يتجاوز الحجز القانوني أو يثبت الامتثال القانوني." : "Approving a policy does not activate deletion schedules, bypass legal holds, or establish legal compliance."}</p></div></aside>
    <section className="lifecycle-main"><header><div><small>{ar ? "حوكمة المعلومات" : "INFORMATION GOVERNANCE"}</small><b>{ar ? "سياسات محمية ومراجعة مستقلة" : "Protected policies and independent review"}</b></div><div><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button><a href="/notifications" aria-label={ar ? "الإشعارات" : "Notifications"}>●</a></div></header><div className="lifecycle-workspace">
      <div className="lifecycle-heading"><div><p>{ar ? "الاحتفاظ والتصرف" : "RETENTION & DISPOSITION"}</p><h1>{ar ? "مركز دورة حياة البيانات" : "Data Lifecycle Centre"}</h1><span>{ar ? "حدد مدة الاحتفاظ ونقطة البدء وطريقة التصرف والمرجع القانوني مع مراجعة مستقلة لكل فئة سجل." : "Define retention duration, trigger, disposition, and legal reference with independent review for every record class."}</span></div><button type="button" onClick={() => void load()}>↻ {ar ? "تحديث" : "Refresh"}</button></div>
      <section className="lifecycle-summary"><article><b>{reyatiNumber(approved, lang)}/5</b><span>{ar ? "سياسات معتمدة" : "policies approved"}</span></article><div><b>{approved === 5 ? (ar ? "اكتملت تغطية السياسات" : "Policy coverage complete") : (ar ? "التغطية ما زالت غير مكتملة" : "Policy coverage remains incomplete")}</b><p>{ar ? "حتى بعد اعتماد السياسات، تبقى جدولة الحذف والحجز القانوني وتشغيل الماسح وموافقة الإطلاق بوابات مستقلة." : "Even after policy approval, deletion scheduling, legal-hold operations, scanner activation, and launch approval remain independent gates."}</p></div></section>
      {loading && <div className="lifecycle-state">{ar ? "جارٍ تحميل السياسات…" : "Loading protected policies…"}</div>}{error && <div className="lifecycle-alert error"><span>{error}</span><button type="button" onClick={() => setError("")}>×</button></div>}{notice && <div className="lifecycle-alert success"><span>✓ {notice}</span><button type="button" onClick={() => setNotice("")}>×</button></div>}
      {data && <section className="lifecycle-grid"><div className="lifecycle-classes">{data.recordClasses.map((item) => { const policy = policies.get(item); return <button type="button" key={item} className={selectedClass === item ? "active" : ""} onClick={() => setSelectedClass(item)}><span>{policy?.status === "approved" ? "✓" : "⌛"}</span><div><b>{copy(item)}</b><small>{policy ? `${policy.retentionMonths} ${ar ? "شهراً" : "months"} · ${policy.ownerName}` : (ar ? "لا توجد سياسة" : "No policy")}</small></div><i className={policy?.status ?? "missing"}>{policy ? copy(policy.status) : (ar ? "مفقود" : "MISSING")}</i></button>; })}</div><aside className="lifecycle-editor"><div className="lifecycle-editor-head"><p>{ar ? "فئة السجل" : "RECORD CLASS"}</p><h2>{copy(selectedClass)}</h2><span>{ar ? "القيم المقترحة ليست نصيحة قانونية ويجب أن تشير إلى قرار معتمد خارج النظام." : "Proposed values are not legal advice and must reference an approved decision outside the system."}</span></div>
        {data.role === "platform_admin" && (!selected || ["draft", "rejected"].includes(selected.status)) ? <PolicyEditor ar={ar} busy={busy} data={data} selected={selected} copy={copy} onSubmit={save}/> : selected ? <><dl><div><dt>{ar ? "الاحتفاظ" : "Retention"}</dt><dd>{selected.retentionMonths} {ar ? "شهراً" : "months"} · {copy(selected.retentionTrigger)}</dd></div><div><dt>{ar ? "التصرف" : "Disposition"}</dt><dd>{copy(selected.disposition)}</dd></div><div><dt>{ar ? "المالك" : "Owner"}</dt><dd>{selected.ownerName}</dd></div><div><dt>{ar ? "المرجع القانوني" : "Legal reference"}</dt><dd>{selected.legalBasisReference}</dd></div></dl>{selected.status === "draft" && data.role === "platform_admin" && <PolicyAction label={ar ? "إرسال للمراجعة" : "Submit for review"} noteLabel={ar ? "ملاحظة الإرسال" : "Submission note"} busy={busy} onSubmit={(event) => transition("submit", event)}/>} {selected.status === "pending_review" && selected.ownerUserId !== data.currentUserId && <div className="lifecycle-review"><PolicyAction label={ar ? "اعتماد السياسة" : "Approve policy"} noteLabel={ar ? "ملاحظة المراجع" : "Reviewer note"} busy={busy} onSubmit={(event) => transition("approve", event)}/><PolicyAction danger label={ar ? "رفض السياسة" : "Reject policy"} noteLabel={ar ? "سبب الرفض" : "Rejection reason"} busy={busy} onSubmit={(event) => transition("reject", event)}/></div>} {selected.status === "approved" && data.role === "platform_admin" && <PolicyAction danger label={ar ? "تقاعد السياسة" : "Retire policy"} noteLabel={ar ? "سبب التقاعد" : "Retirement reason"} busy={busy} onSubmit={(event) => transition("retire", event)}/>}<section className="lifecycle-timeline"><h3>{ar ? "سجل أدلة غير قابل للتغيير" : "Immutable evidence trail"}</h3>{selected.events.map((item) => <article key={item.id}><span>•</span><div><b>{item.action}</b><p>{item.note}</p><small>{item.actorName} · {reyatiDate(item.createdAt, lang, { dateStyle: "medium", timeStyle: "short" })}</small></div></article>)}</section></> : <div className="lifecycle-state">{ar ? "لم يتم إنشاء سياسة بعد." : "No policy has been created yet."}</div>}
      </aside></section>}
    </div></section>
  </main>;
}
function PolicyEditor({ ar, busy, data, selected, copy, onSubmit }: { ar: boolean; busy: boolean; data: Data; selected?: Policy; copy: (value: string) => string; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form key={`${selected?.recordClass ?? "new"}:${selected?.version ?? 0}`} onSubmit={onSubmit}><div className="lifecycle-pair"><label>{ar ? "مدة الاحتفاظ بالأشهر" : "Retention · months"}<input name="retentionMonths" type="number" min={1} max={1200} required defaultValue={selected?.retentionMonths ?? 12}/></label><label>{ar ? "بداية المدة" : "Retention trigger"}<select name="retentionTrigger" defaultValue={selected?.retentionTrigger ?? "record_created"}>{data.retentionTriggers.map((item) => <option key={item} value={item}>{copy(item)}</option>)}</select></label></div><label>{ar ? "طريقة التصرف" : "Disposition"}<select name="disposition" defaultValue={selected?.disposition ?? "review_then_delete"}>{data.dispositions.map((item) => <option key={item} value={item}>{copy(item)}</option>)}</select></label><label>{ar ? "المالك المسؤول" : "Accountable owner"}<select name="ownerUserId" required defaultValue={selected?.ownerUserId ?? ""}><option value="" disabled>{ar ? "اختر مالكاً" : "Select an owner"}</option>{data.operators.map((operator) => <option key={`${operator.userId}:${operator.role}`} value={operator.userId}>{operator.displayName} · {operator.role.replaceAll("_", " ")}</option>)}</select></label><label>{ar ? "مرجع الأساس القانوني" : "Legal-basis reference"}<input name="legalBasisReference" minLength={6} maxLength={240} required defaultValue={selected?.legalBasisReference ?? ""}/></label><label>{ar ? "مرجع دليل الاعتماد" : "Approval evidence reference"}<input name="evidenceReference" minLength={6} maxLength={240} required defaultValue={selected?.evidenceReference ?? ""}/></label><button disabled={busy}>{busy ? (ar ? "جارٍ الحفظ…" : "Saving…") : (ar ? "حفظ المسودة" : "Save draft")}</button></form>; }
function PolicyAction({ label, noteLabel, busy, danger = false, onSubmit }: { label: string; noteLabel: string; busy: boolean; danger?: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><label>{noteLabel}<textarea name="note" minLength={10} maxLength={1200} required/></label><button className={danger ? "danger" : ""} disabled={busy}>{label}</button></form>; }
