"use client";

import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./benefits.module.css";

type Offer = { id: string; status: string; visibilityStatus: string; version: number; sponsorName: string; programme: { nameEn: string; nameAr: string; descriptionEn?: string; descriptionAr?: string; currency: string; memberLimitMinor?: number; startsAt?: string; endsAt?: string }; ledger: Array<{ id: string; entryType: string; direction: string; amountMinor: number; currency: string; createdAt: string }>; balanceMinor: number | null };
type Data = { consentVersion: string; offers: Offer[]; boundaries: Record<string, boolean> };
async function api(init?: RequestInit) { const response = await fetch("/api/benefits", { cache: "no-store", ...init }); const payload = await response.json(); if (response.status === 401) { location.assign("/sign-in?redirect_url=/benefits"); throw new Error("Sign in required"); } if (!response.ok) throw new Error(payload.message || payload.error || "Benefits are unavailable"); return payload.data as Data; }
const money = (value: number | null, currency: string, ar: boolean) => value == null ? "—" : new Intl.NumberFormat(ar ? "ar-QA" : "en-QA", { style: "currency", currency }).format(value / 100);

export default function EmployerBenefitsPage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(() => api().then(setData), []);
  useEffect(() => { queueMicrotask(() => void load().catch((reason) => setError(reason.message))); }, [load]);
  async function act(offer: Offer, action: string, extra: Record<string, unknown> = {}) { setBusy(true); setError(""); setNotice(""); try { await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, eligibilityId: offer.id, version: offer.version, ...extra }) }); setNotice(ar ? "تم حفظ اختيارك بأمان." : "Your choice was saved securely."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update benefit"); } finally { setBusy(false); } }
  return <main className={`${styles.shell} trust-center-shell benefits-experience`} dir={ar ? "rtl" : "ltr"}>
    <header className={styles.top}><a href="/"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya" /></a><nav><a href="/wallet">{ar ? "المحفظة الصحية" : "Health wallet"}</a><a href="/support">{ar ? "الدعم" : "Support"}</a><button onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></nav></header>
    <section className={styles.hero}><small>{ar ? "المزايا برضاك" : "BENEFITS, ON YOUR TERMS"}</small><h1>{ar ? "أنت تقرر ما يظهر لك." : "You decide what becomes visible."}</h1><p>{ar ? "راجع دعوة المزايا، وافق عليها صراحة، وتحكم في ظهورها. لا يستطيع صاحب العمل رؤية مواعيدك أو تشخيصاتك أو مقدمي الرعاية." : "Review a benefit invitation, consent explicitly, and control its visibility. Your employer cannot see appointments, diagnoses, providers, or clinical activity."}</p></section>
    <section className={styles.body}>{error && <p className={styles.error}>{error}</p>}{notice && <p className={styles.notice}>{notice}</p>}
      <div className={styles.privacy}><span>♙</span><div><b>{ar ? "فصل صحي صارم" : "Strict health-data separation"}</b><p>{ar ? "لا تُستخدم البيانات الصحية لتحديد الأهلية، ولا تكشف ريّاتي نشاطك الصحي لصاحب العمل." : "Health data never determines eligibility, and Qivaya never exposes your health activity to the sponsor."}</p></div></div>
      <div className={styles.list}>{data?.offers.map((offer) => { const accepted = offer.status === "accepted"; return <article className={styles.card} key={offer.id}><header><div><small>{offer.sponsorName}</small><h2>{ar ? offer.programme.nameAr : offer.programme.nameEn}</h2></div><em>{accepted ? (ar ? "مقبولة" : "ACCEPTED") : (ar ? "بانتظار اختيارك" : "YOUR CHOICE")}</em></header>{accepted ? <><p>{ar ? offer.programme.descriptionAr : offer.programme.descriptionEn}</p><div className={styles.summary}><div><small>{ar ? "الحد المسجل" : "Recorded limit"}</small><b>{money(offer.programme.memberLimitMinor ?? null, offer.programme.currency, ar)}</b></div><div><small>{ar ? "الرصيد الدفتري" : "Ledger balance"}</small><b>{money(offer.balanceMinor, offer.programme.currency, ar)}</b></div><div><small>{ar ? "الظهور" : "Visibility"}</small><b>{offer.visibilityStatus === "visible" ? (ar ? "ظاهر لك" : "Visible to you") : (ar ? "مخفي" : "Hidden")}</b></div></div><div className={styles.ledger}><h3>{ar ? "سجل مزايا غير قابل للتعديل" : "Immutable benefit ledger"}</h3>{offer.ledger.map((entry) => <p key={entry.id}><span>{entry.entryType.replaceAll("_", " ")}</span><b>{entry.direction === "debit" ? "−" : "+"}{money(entry.amountMinor, entry.currency, ar)}</b></p>)}</div><div className={styles.actions}><button disabled={busy} onClick={() => void act(offer, "set_visibility", { visible: offer.visibilityStatus !== "visible" })}>{offer.visibilityStatus === "visible" ? (ar ? "إخفاء الميزة" : "Hide benefit") : (ar ? "إظهار الميزة" : "Show benefit")}</button><button className={styles.danger} disabled={busy} onClick={() => void act(offer, "withdraw")}>{ar ? "سحب الموافقة" : "Withdraw consent"}</button></div></> : <><p>{ar ? "هناك دعوة مزايا مرتبطة ببريد حسابك. لن تُربط بملفك أو تظهر تفاصيلها قبل موافقتك الصريحة." : "A benefit invitation is bound to your account email. It will not link to your profile or reveal full details until you explicitly consent."}</p><label className={styles.consent}><input type="checkbox" id={`consent-${offer.id}`} />{ar ? "أوافق على ربط دعوة المزايا هذه بحساب ريّاتي وعرضها لي." : "I consent to link this benefit invitation to my Qivaya account and display it to me."}</label><button className={styles.primary} disabled={busy} onClick={() => { const checked = (document.getElementById(`consent-${offer.id}`) as HTMLInputElement | null)?.checked; if (!checked) { setError(ar ? "يرجى تأكيد الموافقة أولاً." : "Confirm consent first."); return; } void act(offer, "accept_offer", { explicitConsent: true, consentVersion: data?.consentVersion }); }}>{ar ? "قبول وعرض الميزة" : "Accept and show benefit"}</button></>}</article>; })}{data && !data.offers.length && <div className={styles.empty}><span>◇</span><h2>{ar ? "لا توجد دعوات مزايا" : "No benefit invitations"}</h2><p>{ar ? "ستظهر الدعوة هنا فقط إذا كانت مرتبطة ببريد حسابك." : "An invitation appears here only when it is bound to your account email."}</p></div>}</div>
    </section>
  </main>;
}
