"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./policy-templates.module.css";

type Item = { id:string; templateCode:string; purpose:string; edition:number; titleEn:string; titleAr:string; bodyEn:string; bodyAr:string; effectiveAt:string; expiresAt:string|null; status:string; version:number; placeholderCodes:string[]; makerCheckerSatisfied:boolean };
type Data = { role:string; visibility:string; purposes:string[]; allowedPlaceholders:string[]; metrics:Record<string,number>; items:Item[]; rehearsals:Array<{id:string;result:string;scenarioCount:number;executedAt:string}> };
const initial = { templateCode:"", purpose:"appointment_preparation", edition:"1", titleEn:"", titleAr:"", bodyEn:"", bodyAr:"", effectiveAt:"", expiresAt:"" };

export default function PolicyTemplatesPage() {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar";
  const [data,setData]=useState<Data|null>(null),[draft,setDraft]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[reasons,setReasons]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{setError("");try{const response=await fetch("/api/admin/policy-templates",{cache:"no-store"});const payload=await response.json() as {data?:Data;message?:string};if(!response.ok||!payload.data)throw new Error(payload.message??"Unable to load template governance.");setData(payload.data);}catch(value){setError(value instanceof Error?value.message:"Unable to load template governance.");}},[]);
  useEffect(()=>{queueMicrotask(()=>void load());},[load]);
  const post=async(body:Record<string,unknown>,success:string)=>{setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/admin/policy-templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json() as {message?:string};if(!response.ok)throw new Error(payload.message??"The action could not be completed.");setMessage(success);await load();}catch(value){setError(value instanceof Error?value.message:"The action could not be completed.");}finally{setBusy(false);}};
  const create=async(event:FormEvent)=>{event.preventDefault();await post({action:"create_draft",...draft,edition:Number(draft.edition),effectiveAt:new Date(draft.effectiveAt).toISOString(),expiresAt:draft.expiresAt?new Date(draft.expiresAt).toISOString():null},ar?"حُفظت المسودة الخاصة.":"Private draft saved.");setDraft(initial);};
  const label=(value:string)=>value.replaceAll("_"," "); const isAuditor=data?.visibility==="aggregate_only";
  const expiring=useMemo(()=>data?.metrics.expiring??0,[data]);
  return <main className={styles.shell} dir={ar?"rtl":"ltr"}>
    <aside className={styles.sidebar}><a className={styles.brand} href="/admin"><img src="/brand/qivaya-logo-reversed.png" alt="Qivaya" /></a><p>{ar?"حوكمة الاتصالات":"Communication governance"}</p><nav aria-label={ar?"التنقل الإداري":"Administration navigation"}><a href="/admin">{ar?"نظرة عامة":"Overview"}</a><a className={styles.active} href="/admin/policy-templates" aria-current="page">{ar?"قوالب السياسات":"Policy templates"}</a><a href="/admin/audit">{ar?"سجل التدقيق":"Audit ledger"}</a></nav><div className={styles.sideNote}>{ar?"صياغة ومراجعة وتفعيل يدوي. هذه المساحة لا ترسل أي رسالة.":"Author, review, and activate manually. This workspace sends no messages."}</div></aside>
    <div className={styles.workspace}><header className={styles.topbar}><div><span className={styles.eyebrow}>{ar?"نسخ تشغيلية محكومة":"Governed operational copy"}</span><h1>{ar?"قوالب السياسات والاتصال":"Policy & communication templates"}</h1><p>{ar?"إصدارات ثنائية اللغة مع فصل الأدوار وتكافؤ المتغيرات وجدولة واضحة.":"Bilingual editions with separated duties, placeholder parity, and explicit scheduling."}</p></div><button className={styles.locale} type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></header>
      <section className={styles.boundary}><span aria-hidden="true">i</span><div><b>{ar?"حدود تشغيلية صريحة":"Explicit operational boundaries"}</b><p>{ar?"لا إرسال، ولا أثر قانوني، ولا تعليمات سريرية، ولا ترجمة أو نشر تلقائي، ولا مزامنة خارجية.":"No delivery, legal effect, clinical instructions, automatic translation or publishing, or external synchronization."}</p></div></section>
      {message&&<div className={styles.success} role="status">{message}</div>}{error&&<div className={styles.error} role="alert"><span>{error}</span><button type="button" onClick={()=>void load()}>{ar?"إعادة المحاولة":"Try again"}</button></div>}
      {!data&&!error?<section className={styles.loading} aria-live="polite">{ar?"جارٍ تحميل السجل الخاص…":"Loading the private register…"}</section>:data&&<>
        <section className={styles.metrics} aria-label={ar?"المقاييس المجمعة":"Aggregate metrics"}>{Object.entries(data.metrics).map(([key,value])=><article key={key}><b>{value}</b><span>{label(key)}</span></article>)}</section>
        {expiring>0&&<div className={styles.notice} role="status">{ar?`${expiring} قالب ينتهي خلال 30 يوماً.`:`${expiring} template(s) expire within 30 days.`}</div>}
        {!isAuditor&&<section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar?"مساحة المُعدّ":"Maker workspace"}</span><h2>{ar?"إنشاء إصدار ثنائي اللغة":"Create a bilingual edition"}</h2></div><span className={styles.role}>platform_admin</span></div><form className={styles.form} onSubmit={create}>
          <label>{ar?"الغرض":"Purpose"}<select value={draft.purpose} onChange={e=>setDraft(v=>({...v,purpose:e.target.value}))}>{data.purposes.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
          <label>{ar?"رمز القالب":"Template code"}<input required pattern="[a-z][a-z0-9_]+" maxLength={64} value={draft.templateCode} onChange={e=>setDraft(v=>({...v,templateCode:e.target.value}))} /></label>
          <label>{ar?"رقم الإصدار":"Edition"}<input required type="number" min="1" max="9999" value={draft.edition} onChange={e=>setDraft(v=>({...v,edition:e.target.value}))}/></label>
          <label>{ar?"ساري من":"Effective from"}<input required type="datetime-local" value={draft.effectiveAt} onChange={e=>setDraft(v=>({...v,effectiveAt:e.target.value}))}/></label>
          <label>{ar?"ينتهي في (اختياري)":"Expires at (optional)"}<input type="datetime-local" value={draft.expiresAt} onChange={e=>setDraft(v=>({...v,expiresAt:e.target.value}))}/></label>
          <label>English title<input required minLength={3} maxLength={160} value={draft.titleEn} onChange={e=>setDraft(v=>({...v,titleEn:e.target.value}))}/></label>
          <label>العنوان العربي<input required dir="rtl" lang="ar" minLength={3} maxLength={160} value={draft.titleAr} onChange={e=>setDraft(v=>({...v,titleAr:e.target.value}))}/></label>
          <label className={styles.wide}>English body<textarea required minLength={12} maxLength={4000} value={draft.bodyEn} onChange={e=>setDraft(v=>({...v,bodyEn:e.target.value}))}/></label>
          <label className={styles.wide}>النص العربي<textarea required dir="rtl" lang="ar" minLength={12} maxLength={4000} value={draft.bodyAr} onChange={e=>setDraft(v=>({...v,bodyAr:e.target.value}))}/></label>
          <div className={styles.placeholders}><b>{ar?"المتغيرات المسموح بها":"Allowed placeholders"}</b><code>{data.allowedPlaceholders.map(v=>`{{${v}}}`).join(" · ")}</code><small>{ar?"يجب استخدام المتغيرات نفسها في النسختين.":"Both locales must use the same placeholders."}</small></div>
          <button className={styles.primary} disabled={busy} type="submit">{ar?"حفظ مسودة خاصة":"Save private draft"}</button>
        </form></section>}
        <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar?"دورة حياة محكومة":"Governed lifecycle"}</span><h2>{ar?"سجل القوالب":"Template register"}</h2></div></div>
          {isAuditor?<div className={styles.empty}><b>{ar?"عرض مجمّع فقط":"Aggregate-only view"}</b><p>{ar?"لا تظهر نصوص القوالب لدور المدقق.":"Template copy is not exposed to the auditor role."}</p></div>:!data.items.length?<div className={styles.empty}><b>{ar?"لا توجد قوالب بعد":"No templates yet"}</b><p>{ar?"أنشئ أول مسودة تشغيلية خاصة.":"Create the first private operational draft."}</p></div>:<div className={styles.register}>{data.items.map(item=><article className={styles.card} key={item.id}><header><div><span className={styles.eyebrow}>{label(item.purpose)} · v{item.edition}</span><h3>{ar?item.titleAr:item.titleEn}</h3><code>{item.templateCode}</code></div><span className={`${styles.status} ${styles[item.status]??""}`}>{label(item.status)}</span></header><div className={styles.bilingual}><div><b>{item.titleEn}</b><p>{item.bodyEn}</p></div><div dir="rtl"><b>{item.titleAr}</b><p>{item.bodyAr}</p></div></div><div className={styles.meta}><span>rev {item.version}</span><span>{ar?"تكافؤ اللغة":"Locale parity"}: ✓</span><span>{ar?"فصل الأدوار":"Maker-checker"}: {item.makerCheckerSatisfied?"✓":"—"}</span><span>{item.placeholderCodes.length} {ar?"متغيرات":"placeholders"}</span></div>
          {(["pending_review","active"].includes(item.status))&&<label className={styles.reason}>{ar?"رمز سبب الإرجاع أو التقاعد":"Return or retirement reason code"}<input maxLength={64} placeholder="copy_correction" value={reasons[item.id]??""} onChange={e=>setReasons(v=>({...v,[item.id]:e.target.value}))}/></label>}
          <div className={styles.actions}>{["draft","returned"].includes(item.status)&&<button className={styles.primary} disabled={busy} onClick={()=>void post({action:"submit_review",templateId:item.id,version:item.version},ar?"أُرسل للمراجعة.":"Submitted for review.")}>{ar?"إرسال للمراجعة":"Submit for review"}</button>}{item.status==="pending_review"&&<><button className={styles.primary} disabled={busy} onClick={()=>void post({action:"review",decision:"approve",templateId:item.id,version:item.version},ar?"اعتمده مراجع مستقل.":"Approved by independent checker.")}>{ar?"اعتماد كمراجع":"Approve as checker"}</button><button className={styles.secondary} disabled={busy||!reasons[item.id]} onClick={()=>void post({action:"review",decision:"return",reasonCode:reasons[item.id],templateId:item.id,version:item.version},ar?"أُعيد للمُعدّ.":"Returned to maker.")}>{ar?"إعادة للمُعدّ":"Return"}</button></>}{item.status==="approved"&&<button className={styles.primary} disabled={busy} onClick={()=>void post({action:"activate",templateId:item.id,version:item.version},ar?"فُعّل دون إرسال.":"Activated without delivery.")}>{ar?"تفعيل يدوي":"Activate manually"}</button>}{item.status==="active"&&<button className={styles.danger} disabled={busy||!reasons[item.id]} onClick={()=>void post({action:"retire",reasonCode:reasons[item.id],templateId:item.id,version:item.version},ar?"تقاعد القالب.":"Template retired.")}>{ar?"تقاعد":"Retire"}</button>}</div></article>)}</div>}
        </section>
        <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar?"ضمان اصطناعي":"Synthetic assurance"}</span><h2>{ar?"اختبار بلا آثار تشغيلية":"Zero-side-effect rehearsal"}</h2><p>{ar?"أربعة وعشرون سيناريو دون تغيير القوالب أو إرسال أي رسالة.":"Twenty-four scenarios without changing templates or sending messages."}</p></div><button className={styles.primary} disabled={busy} onClick={()=>void post({action:"run_rehearsal"},ar?"اكتمل الاختبار.":"Rehearsal completed.")}>{ar?"تشغيل 24 سيناريو":"Run 24 scenarios"}</button></div><div className={styles.rehearsals}>{!data.rehearsals.length?(ar?"لم تُشغّل اختبارات بعد.":"No rehearsal has run yet."):data.rehearsals.map(v=><span key={v.id}><b>{v.result}</b>{v.scenarioCount} · {new Date(v.executedAt).toLocaleString()}</span>)}</div></section>
      </>}
    </div></main>;
}
