"use client";
import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./service-status.module.css";

type Notice={id:string;component:string;severity:string;status:string;titleEn:string;titleAr:string;summaryEn:string;summaryAr:string;impactEn:string;impactAr:string;guidanceEn:string;guidanceAr:string;startedAt:string;nextUpdateAt:string|null;resolvedAt:string|null};
type Data={overallStatus:string;active:Notice[];history:Notice[];components:string[];checkedAt:string;source:string;disclaimer:string};
const label=(v:string)=>v.replaceAll("_"," ");
export default function ServiceStatusPage(){
  const [lang,setLang]=useReyatiLocale(),ar=lang==="ar"; const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");
  const load=useCallback(async()=>{setError("");try{const r=await fetch("/api/service-status",{cache:"no-store"}),p=await r.json() as {data?:Data};if(!r.ok||!p.data)throw new Error("Unable to load current service status.");setData(p.data);}catch(e){setError(e instanceof Error?e.message:"Unable to load current service status.");}},[]);
  useEffect(()=>{queueMicrotask(()=>void load());},[load]);
  return <main className={`${styles.shell} service-status-experience`} dir={ar?"rtl":"ltr"}><header className={styles.top}><a href="/"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav><a href="/">{ar?"الرئيسية":"Home"}</a><a href="/support">{ar?"الدعم":"Support"}</a><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></nav></header>
    <section className={styles.hero}><div><span>{ar?"شفافية تشغيلية":"Operational transparency"}</span><h1>{ar?"حالة خدمات ريـاتي":"Reyati service status"}</h1><p>{ar?"تحديثات بشرية المراجعة عن الحالات التشغيلية المعروفة دون كشف بيانات المرضى أو تفاصيل الأمان الداخلية.":"Human-reviewed updates about known operational conditions, without exposing patient data or internal security detail."}</p></div><div className={`${styles.overall} ${styles[data?.overallStatus??"loading"]}`}><i/><b>{data?label(data.overallStatus):ar?"جارٍ الفحص":"Checking"}</b><small>{ar?"الحالة العامة":"Overall status"}</small></div></section>
    <div className={styles.content}>{error&&<div className={styles.error} role="alert">{error}<button onClick={()=>void load()}>{ar?"إعادة المحاولة":"Try again"}</button></div>}{!data&&!error?<div className={styles.empty}>{ar?"جارٍ تحميل الحالة…":"Loading current status…"}</div>:data&&<><section className={styles.components}>{data.components.map(c=><span key={c}><i/>{label(c)}</span>)}</section><section className={styles.panel}><div className={styles.heading}><span>{ar?"الآن":"Right now"}</span><h2>{ar?"التحديثات النشطة":"Active updates"}</h2></div>{!data.active.length?<div className={styles.empty}><b>{ar?"جميع الخدمات تعمل بصورة طبيعية":"All services are operating normally"}</b><p>{ar?"لا توجد حالات تشغيلية منشورة حالياً.":"There are no published operational conditions right now."}</p></div>:<div className={styles.grid}>{data.active.map(n=><NoticeCard key={n.id} n={n} ar={ar}/>)}</div>}</section><section className={styles.panel}><div className={styles.heading}><span>{ar?"السجل":"History"}</span><h2>{ar?"الحالات المحلولة":"Resolved conditions"}</h2></div>{!data.history.length?<p className={styles.muted}>{ar?"لا يوجد سجل منشور بعد.":"No published history yet."}</p>:<div className={styles.grid}>{data.history.map(n=><NoticeCard key={n.id} n={n} ar={ar}/>)}</div>}</section><footer className={styles.note}><b>{ar?"المصدر والحدود":"Source and boundaries"}</b><p>{ar?"تحديثات تشغيلية راجعها فريق ريـاتي. هذه الصفحة لا تضمن التوفر المتواصل ولا تكشف معلومات المرضى أو تفاصيل الأمان الداخلية.":data.disclaimer}</p><small>{ar?"آخر فحص":"Last checked"}: {new Date(data.checkedAt).toLocaleString(ar?"ar-QA":"en-QA")}</small></footer></>}</div></main>;
}
function NoticeCard({n,ar}:{n:Notice;ar:boolean}){return <article className={styles.card}><header><span>{label(n.component)}</span><b className={styles.badge}>{label(n.severity)}</b></header><h3>{ar?n.titleAr:n.titleEn}</h3><p>{ar?n.summaryAr:n.summaryEn}</p><dl><div><dt>{ar?"الأثر":"Impact"}</dt><dd>{ar?n.impactAr:n.impactEn}</dd></div><div><dt>{ar?"ما يمكنك فعله":"What you can do"}</dt><dd>{ar?n.guidanceAr:n.guidanceEn}</dd></div></dl><footer><span>{ar?"بدأ":"Started"}: {new Date(n.startedAt).toLocaleString(ar?"ar-QA":"en-QA")}</span>{n.nextUpdateAt&&<span>{ar?"التحديث التالي":"Next update"}: {new Date(n.nextUpdateAt).toLocaleString(ar?"ar-QA":"en-QA")}</span>}{n.resolvedAt&&<span>{ar?"حُلّت":"Resolved"}: {new Date(n.resolvedAt).toLocaleString(ar?"ar-QA":"en-QA")}</span>}</footer></article>}
