import { chatGPTSignInPath, chatGPTSignOutPath, getChatGPTUser } from "@/app/chatgpt-auth";

export const dynamic = "force-dynamic";

export default async function AuthPage() {
  const user = await getChatGPTUser();
  return <main className="auth-shell" id="main-content">
    <section className="auth-story">
      <a href="/" className="auth-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/></a>
      <div className="auth-story-copy"><p>CARE, INTELLIGENTLY CONNECTED</p><h1>One verified identity. A clearer care journey.</h1><span>Reyati uses your authenticated ChatGPT identity for secure, account-owned appointments, records, delegated access, and support.</span><div className="auth-principles"><article><i>✓</i><div><b>No Reyati password to manage</b><small>Authentication is handled by the trusted sign-in service</small></div></article><article><i>♙</i><div><b>Server-enforced authorization</b><small>Provider and operations access depends on active assigned roles</small></div></article><article><i>◎</i><div><b>Account-owned activity</b><small>Bookings, records, notifications, and support stay attached to your identity</small></div></article></div></div>
      <div className="auth-weave"><span/><i/></div><small className="auth-legal">Reyati never asks for a password, SMS code, or payment credential on this page.</small>
    </section>
    <section className="auth-stage"><header><a href="/">← Back to Reyati</a><a href="/support">Help</a></header><div className="auth-card">
      {user ? <><div className="auth-success"><span>✓</span><p>AUTHENTICATED SESSION</p><h2>Welcome, {user.fullName || user.email}</h2><small>Your identity was verified by ChatGPT. Reyati uses the stable account identifier server-side and displays your verified contact email below.</small></div><div className="identity-card"><span className="avatar large">{(user.fullName || user.email).split(/\s+|@/).filter(Boolean).slice(0,2).map((part)=>part[0]).join("").toUpperCase()}</span><div><b>{user.fullName || "Signed-in Reyati account"}</b><small>{user.email}</small></div><i>Verified</i></div><div className="prototype-alert"><span>♙</span><p><b>Access is role-scoped</b>Signing in identifies you; it does not grant provider, organization, or platform permissions. Protected workspaces verify active roles on every request.</p></div><div className="role-picker detailed"><a href="/"><span>♡</span><div><b>Patient workspace</b><small>Appointments, records, payments, family access, and support</small></div><i>→</i></a><a href="/provider"><span>✚</span><div><b>Provider console</b><small>Requires an active provider profile and organization role</small></div><i>→</i></a><a href="/admin"><span>◇</span><div><b>Platform operations</b><small>Protected tools enforce the assigned platform role independently</small></div><i>→</i></a></div><div className="auth-actions"><a className="auth-passkey" href={chatGPTSignOutPath("/")}><span>↪</span>Sign out securely</a><a className="auth-primary" href="/">Continue to Reyati →</a></div></> : <><div className="auth-heading"><p>SECURE SIGN-IN</p><h2>Continue with ChatGPT</h2><span>Use the account identity already protected by ChatGPT. Reyati does not collect a separate password, phone number, or verification code.</span></div><div className="prototype-alert"><span>i</span><p><b>One real authentication path</b>The sign-in service returns only the stable account identity and verified contact details Reyati needs.</p></div><a className="auth-primary" href={chatGPTSignInPath("/auth")}>Sign in with ChatGPT →</a><p className="auth-switch">New Reyati users are provisioned securely after their first authenticated request.</p></>}
    </div><footer><span>© 2026 Reyati</span><a href="/support">Privacy and support</a></footer></section>
  </main>;
}
