"use client";

import { useState } from "react";

type Mode = "signin" | "create";
type Role = "patient" | "provider" | "partner";

const destinations: Record<Role,string> = {patient:"/",provider:"/provider",partner:"/partner"};

export default function AuthPage(){
  const [mode,setMode]=useState<Mode>("signin");
  const [role,setRole]=useState<Role>("patient");
  const [step,setStep]=useState(0);
  const [lang,setLang]=useState<"en"|"ar">("en");
  const [otp,setOtp]=useState(["2","4","8","1","6","0"]);
  const [accepted,setAccepted]=useState({terms:false,privacy:false,communications:true});
  const ar=lang==="ar";
  const reset=(next:Mode)=>{setMode(next);setStep(0);setRole("patient")};
  const finish=()=>{window.location.href=destinations[role]};
  const total=mode==="signin"?2:4;

  return <main className={`auth-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <section className="auth-story">
      <a href="/" className="auth-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/></a>
      <div className="auth-story-copy"><p>{ar?"رعاية متصلة بذكاء":"CARE, INTELLIGENTLY CONNECTED"}</p><h1>{ar?"حساب واحد. رحلة رعاية أوضح.":"One account. A clearer care journey."}</h1><span>{ar?"وصول آمن إلى المواعيد والمزايا والمعلومات التي تختار مشاركتها.":"Secure access to appointments, benefits, and the information you choose to share."}</span><div className="auth-principles"><article><i>✓</i><div><b>{ar?"خصوصية باختيارك":"Privacy by your choice"}</b><small>{ar?"تحكم واضح بالموافقة والمشاركة":"Clear consent and sharing controls"}</small></div></article><article><i>♙</i><div><b>{ar?"تحقق مناسب للمخاطر":"Risk-aware verification"}</b><small>{ar?"حماية إضافية عند الحاجة فقط":"Extra protection only when needed"}</small></div></article><article><i>◎</i><div><b>{ar?"حسابك تحت سيطرتك":"You stay in control"}</b><small>{ar?"أجهزة وجلسات ونشاط قابل للمراجعة":"Reviewable devices, sessions, and activity"}</small></div></article></div></div>
      <div className="auth-weave"><span/><i/></div><small className="auth-legal">{ar?"نموذج تفاعلي · لا تستخدم معلومات حقيقية":"Interactive prototype · Do not enter real information"}</small>
    </section>

    <section className="auth-stage">
      <header><a href="/">← {ar?"العودة إلى رعايتي":"Back to Reyati"}</a><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></header>
      <div className="auth-card">
        <div className="prototype-alert"><span>i</span><p><b>{ar?"تجربة آمنة للنموذج":"Safe prototype experience"}</b>{ar?"لا يتم إرسال أو حفظ أي رقم هاتف أو بريد إلكتروني أو رمز تحقق.":"No phone number, email, or verification code is sent or stored."}</p></div>
        {step<total&&<div className="auth-progress"><span style={{width:`${((step+1)/total)*100}%`}}/></div>}

        {mode==="signin"&&step===0&&<><div className="auth-heading"><p>{ar?"مرحباً بعودتك":"WELCOME BACK"}</p><h2>{ar?"تسجيل الدخول إلى رعايتي":"Sign in to Reyati"}</h2><span>{ar?"اختر مساحة عملك وأدخل وسيلة الاتصال التجريبية.":"Choose your workspace and enter a synthetic contact method."}</span></div><RolePicker role={role} setRole={setRole} ar={ar}/><label className="auth-field">{ar?"رقم الهاتف أو البريد الإلكتروني":"Mobile number or email"}<div><span>{role==="patient"?"+974":"@"}</span><input defaultValue={role==="patient"?"•••• 4821":role==="provider"?"doctor@example.test":"admin@atlas.test"} aria-label="Synthetic contact"/></div></label><button className="auth-primary" onClick={()=>setStep(1)}>{ar?"متابعة آمنة":"Continue securely"} →</button><div className="auth-divider"><span>{ar?"أو":"OR"}</span></div><button className="auth-passkey" onClick={()=>setStep(1)}><span>♙</span>{ar?"استخدام مفتاح مرور تجريبي":"Use a prototype passkey"}</button><p className="auth-switch">{ar?"جديد في رعايتي؟":"New to Reyati?"} <button onClick={()=>reset("create")}>{ar?"إنشاء حساب":"Create an account"}</button></p></>}

        {mode==="signin"&&step===1&&<Verification ar={ar} otp={otp} setOtp={setOtp} back={()=>setStep(0)} next={()=>setStep(2)}/>} 
        {mode==="signin"&&step===2&&<Success ar={ar} role={role} finish={finish}/>} 

        {mode==="create"&&step===0&&<><div className="auth-heading"><p>{ar?"ابدأ مع رعايتي":"GET STARTED"}</p><h2>{ar?"ما نوع الحساب؟":"Which account fits you?"}</h2><span>{ar?"سنخصص خطوات الإعداد وصلاحيات الوصول بناءً على اختيارك.":"We’ll tailor setup and access permissions to your selection."}</span></div><RolePicker role={role} setRole={setRole} ar={ar} detailed/><button className="auth-primary" onClick={()=>setStep(1)}>{ar?"متابعة":"Continue"} →</button><p className="auth-switch">{ar?"لديك حساب؟":"Already have an account?"} <button onClick={()=>reset("signin")}>{ar?"تسجيل الدخول":"Sign in"}</button></p></>}

        {mode==="create"&&step===1&&<><div className="auth-heading"><p>2 / 4 · {ar?"معلومات الحساب":"ACCOUNT DETAILS"}</p><h2>{role==="patient"?(ar?"أخبرنا عنك":"Tell us about you"):role==="provider"?(ar?"بيانات الممارس":"Practitioner details"):(ar?"بيانات المؤسسة":"Organisation details")}</h2><span>{ar?"استخدم بيانات تجريبية فقط في هذا النموذج.":"Use synthetic information only in this prototype."}</span></div><div className="auth-form-grid"><label className="auth-field">{role==="partner"?(ar?"اسم المؤسسة":"Organisation name"):(ar?"الاسم الكامل":"Full name")}<input defaultValue={role==="partner"?"Atlas Consulting":role==="provider"?"Dr. Hana Al-Sulaiti":"Mariam Ahmed"}/></label><label className="auth-field">{ar?"البريد الإلكتروني":"Email address"}<input defaultValue={role==="partner"?"admin@atlas.test":role==="provider"?"doctor@example.test":"mariam@example.test"}/></label><label className="auth-field">{ar?"رقم الهاتف":"Mobile number"}<input defaultValue="+974 •••• 4821"/></label><label className="auth-field">{role==="provider"?(ar?"رقم الترخيص":"Licence reference"):role==="partner"?(ar?"رقم السجل":"Registration reference"):(ar?"تاريخ الميلاد":"Date of birth")}<input defaultValue={role==="provider"?"DHP-P-••1048":role==="partner"?"CR-••8241":"14 March 1992"}/></label></div><div className="auth-actions"><button onClick={()=>setStep(0)}>{ar?"رجوع":"Back"}</button><button className="auth-primary" onClick={()=>setStep(2)}>{ar?"متابعة للتحقق":"Continue to verification"} →</button></div></>}

        {mode==="create"&&step===2&&<Verification ar={ar} otp={otp} setOtp={setOtp} back={()=>setStep(1)} next={()=>setStep(3)} create/>}
        {mode==="create"&&step===3&&<><div className="auth-heading"><p>4 / 4 · {ar?"الموافقة والتحكم":"CONSENT & CONTROL"}</p><h2>{ar?"راجع اختياراتك":"Review your choices"}</h2><span>{ar?"يمكنك تغيير الاتصالات الاختيارية في أي وقت. الشروط والخصوصية مطلوبة لإنشاء الحساب.":"Optional communications can change anytime. Terms and privacy are required to create the account."}</span></div><div className="consent-checks"><Check checked={accepted.terms} set={()=>setAccepted(v=>({...v,terms:!v.terms}))} title={ar?"أوافق على شروط الاستخدام":"I agree to the Terms of Use"} text={ar?"توضح القواعد والمسؤوليات لاستخدام رعايتي.":"The rules and responsibilities for using Reyati."}/><Check checked={accepted.privacy} set={()=>setAccepted(v=>({...v,privacy:!v.privacy}))} title={ar?"قرأت إشعار الخصوصية":"I have read the Privacy Notice"} text={ar?"يوضح البيانات المستخدمة والغرض وفترات الاحتفاظ والحقوق.":"How data is used, why, retention periods, and your rights."}/><Check checked={accepted.communications} set={()=>setAccepted(v=>({...v,communications:!v.communications}))} title={ar?"إرسال تحديثات مفيدة":"Send me helpful updates"} text={ar?"اختياري · لا يؤثر على رسائل الرعاية والخدمة الأساسية.":"Optional · does not affect essential care and service messages."}/></div><div className="consent-summary"><span>♙</span><p><b>{ar?"لن نبيع معلوماتك الشخصية":"We don’t sell personal information"}</b>{ar?"وستظل بيانات الرعاية خاضعة لموافقتك وصلاحيات الوصول المحددة.":"Care data remains governed by your consent and scoped access."}</p></div><div className="auth-actions"><button onClick={()=>setStep(2)}>{ar?"رجوع":"Back"}</button><button disabled={!accepted.terms||!accepted.privacy} className="auth-primary" onClick={()=>setStep(4)}>{ar?"إنشاء الحساب":"Create account"} →</button></div></>}
        {mode==="create"&&step===4&&<Success ar={ar} role={role} finish={finish} created/>}
      </div>
      <footer><span>© 2026 Reyati</span><a href="#">{ar?"الخصوصية":"Privacy"}</a><a href="#">{ar?"المساعدة":"Help"}</a></footer>
    </section>
  </main>
}

function RolePicker({role,setRole,ar,detailed=false}:{role:Role,setRole:(r:Role)=>void,ar:boolean,detailed?:boolean}){const roles:[Role,string,string,string,string][]=[["patient",ar?"مريض أو فرد":"Patient or individual",ar?"حجوزات ومحفظة صحية":"Bookings and health wallet","♡","/"],["provider",ar?"مقدم رعاية":"Care provider",ar?"جدول المواعيد ومساحة الزيارة":"Schedule and encounter workspace","✚","/provider"],["partner",ar?"صاحب عمل أو شريك":"Employer or partner",ar?"الأهلية والتمويل والفواتير":"Eligibility, funding, and invoices","◇","/partner"]];return <div className={`role-picker ${detailed?"detailed":""}`}>{roles.map(([id,title,text,icon])=><button key={id} onClick={()=>setRole(id)} className={role===id?"selected":""}><span>{icon}</span><div><b>{title}</b>{detailed&&<small>{text}</small>}</div><i>{role===id?"✓":""}</i></button>)}</div>}

function Verification({ar,otp,setOtp,back,next,create=false}:{ar:boolean,otp:string[],setOtp:(v:string[])=>void,back:()=>void,next:()=>void,create?:boolean}){return <><div className="auth-heading"><p>{create?"3 / 4 · ":"2 / 2 · "}{ar?"التحقق":"VERIFICATION"}</p><h2>{ar?"أدخل رمز التحقق":"Enter the verification code"}</h2><span>{ar?"في المنتج الحقيقي سنرسل رمزاً إلى وسيلة الاتصال التي تم التحقق منها. استخدم الرمز التجريبي الظاهر أدناه.":"In production, a code will go to the verified contact method. Use the visible prototype code below."}</span></div><div className="otp-note"><span>i</span><p>{ar?"رمز النموذج: ٢ ٤ ٨ ١ ٦ ٠":"Prototype code: 2 4 8 1 6 0"}</p></div><div className="otp-row">{otp.map((n,i)=><input key={i} value={n} maxLength={1} inputMode="numeric" aria-label={`Digit ${i+1}`} onChange={e=>{const copy=[...otp];copy[i]=e.target.value.replace(/\D/g,"");setOtp(copy)}}/>)}</div><p className="resend">{ar?"لم تستلم الرمز؟":"Didn’t receive the code?"} <button>{ar?"إعادة الإرسال":"Resend code"}</button></p><div className="stepup-note"><span>♙</span><p><b>{ar?"تحقق إضافي للإجراءات الحساسة":"Step-up checks for sensitive actions"}</b>{ar?"قد نطلب تحققاً جديداً قبل مشاركة سجل صحي أو اعتماد دفعة أو تغيير صلاحية.":"We may re-check identity before sharing a health record, approving funds, or changing permissions."}</p></div><div className="auth-actions"><button onClick={back}>{ar?"رجوع":"Back"}</button><button className="auth-primary" onClick={next}>{ar?"تحقق ومتابعة":"Verify & continue"} →</button></div></>}

function Check({checked,set,title,text}:{checked:boolean,set:()=>void,title:string,text:string}){return <button className={checked?"consent-check checked":"consent-check"} onClick={set}><span>{checked?"✓":""}</span><div><b>{title}</b><small>{text}</small></div></button>}

function Success({ar,role,finish,created=false}:{ar:boolean,role:Role,finish:()=>void,created?:boolean}){return <div className="auth-success"><span>✓</span><p>{created?(ar?"اكتمل الإعداد":"SETUP COMPLETE"):(ar?"تم التحقق":"VERIFIED")}</p><h2>{created?(ar?"حسابك جاهز":"Your account is ready"):(ar?"مرحباً بعودتك":"Welcome back")}</h2><small>{role==="patient"?(ar?"انتقل إلى تجربة المريض لإدارة مواعيدك ومحفظتك.":"Continue to your patient home to manage appointments and wallet."):role==="provider"?(ar?"انتقل إلى مساحة مقدم الرعاية.":"Continue to your provider workspace."):(ar?"انتقل إلى بوابة مزايا الشركاء.":"Continue to the partner benefits portal.")}</small><div className="success-security"><i>♙</i><p><b>{ar?"جلسة نموذجية فقط":"Prototype session only"}</b>{ar?"لم يتم إنشاء هوية أو جلسة حقيقية.":"No real identity or session has been created."}</p></div><button className="auth-primary" onClick={finish}>{ar?"الانتقال إلى مساحة العمل":"Continue to workspace"} →</button></div>}
