"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";

type User={displayName:string;email:string;status:string};
type Appointment={id:string;providerName:string;specialty:string;facilityName:string|null;scheduledStart:string;scheduledEnd:string;mode:string;status:string};

function initials(value:string){return value.split(/\s+|@/).filter(Boolean).slice(0,2).map((part)=>part[0]).join("").toUpperCase()||"RY";}
function formatVisit(value:string,lang:"en"|"ar"){return new Intl.DateTimeFormat(lang==="ar"?"ar-QA":"en-QA",{timeZone:"Asia/Qatar",dateStyle:"full",timeStyle:"short"}).format(new Date(value));}

export default function Home(){
  const [lang,setLang]=useReyatiLocale();const ar=lang==="ar";
  const [user,setUser]=useState<User|null>(null);const [appointments,setAppointments]=useState<Appointment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [referenceTime]=useState(()=>Date.now());
  const loadWorkspace=useCallback(async(signal?:AbortSignal)=>{
    setLoading(true);setError("");
    try{
      const [identityResponse,appointmentResponse]=await Promise.all([fetch("/api/me",{cache:"no-store",signal}),fetch("/api/appointments",{cache:"no-store",signal})]);
      if(identityResponse.status===401||appointmentResponse.status===401){window.location.assign(`/signin-with-chatgpt?return_to=${encodeURIComponent("/")}`);return;}
      const identity=await identityResponse.json().catch(()=>({})) as {user?:User;error?:string};const schedule=await appointmentResponse.json().catch(()=>({})) as {appointments?:Appointment[];error?:string};
      if(!identityResponse.ok)throw new Error(identity.error||"Your Reyati identity is temporarily unavailable");if(!appointmentResponse.ok)throw new Error(schedule.error||"Appointments are temporarily unavailable");
      setUser(identity.user||null);setAppointments(schedule.appointments||[]);
    }catch(caught){
      if(caught instanceof DOMException&&caught.name==="AbortError")return;
      setError(caught instanceof Error?caught.message:"Reyati is temporarily unavailable");
    }finally{if(!signal?.aborted)setLoading(false);}
  },[]);
  useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)void loadWorkspace(controller.signal);});return()=>controller.abort();},[loadWorkspace]);
  const nextAppointment=useMemo(()=>appointments.filter((item)=>["pending","confirmed"].includes(item.status)&&new Date(item.scheduledEnd).valueOf()>referenceTime).sort((a,b)=>new Date(a.scheduledStart).valueOf()-new Date(b.scheduledStart).valueOf())[0]||null,[appointments,referenceTime]);
  const displayName=user?.displayName||"Reyati member";
  return <main id="main-content" className={ar?"arabic":""} dir={ar?"rtl":"ltr"}>
    <header><a className="brand" href="/" aria-label={ar?"رعايتي الرئيسية":"Reyati home"}><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav><a className="active" href="/">{ar?"الرئيسية":"Home"}</a><a href="/navigator">{ar?"موجّه الرعاية":"Care Navigator"}</a><a href="/providers">{ar?"ابحث عن رعاية":"Find care"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a><a href="/wallet">{ar?"السجلات الصحية":"Health records"}</a><a href="/family">{ar?"وصول العائلة":"Family access"}</a><a href="/support">{ar?"الدعم":"Support"}</a></nav><div className="header-actions"><button className="lang" type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a className="bell" href="/notifications" aria-label={ar?"الإشعارات":"Notifications"}><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg></a><a className="account-trigger" href="/auth" aria-label={ar?"فتح الحساب الآمن":"Open secure account"}><span className="avatar">{initials(displayName)}</span><span className="profile">{ar?"الحساب":"Account"}</span></a></div></header>
    <section className="hero"><div className="hero-inner"><p className="eyebrow">{ar?"رعاية مترابطة بذكاء":"CARE, INTELLIGENTLY CONNECTED"}</p><h1>{loading?(ar?"مرحباً بك في رعايتي":"Welcome to Reyati"):(ar?`مرحباً، ${displayName}`:`Welcome, ${displayName}`)}</h1><p className="lead">{ar?"أدر مواعيدك الحقيقية ومعلومات الزيارات النهائية ووصول العائلة المحدد والدعم من حساب آمن واحد.":"Manage real appointments, finalized visit information, scoped family access, and support from one secure account."}</p><div className="home-hero-actions"><a className="search-button" href="/providers">{ar?"ابحث عن رعاية موثّقة":"Find verified care"}</a><a href="/appointments">{ar?"عرض المواعيد":"View appointments"}</a></div><p className="emergency"><span>＋</span>{ar?"لحالة طارئة تهدد الحياة في قطر، اتصل على 999.":"For a life-threatening emergency in Qatar, call 999."}</p></div><div className="hero-art" aria-hidden="true"><img src="/brand/care-conversation.webp" alt="" width="960" height="640" decoding="async" fetchPriority="high"/><span className="weave-path weave-cyan"/><span className="weave-path weave-white"/></div></section>
    <section className="content home-live-content">
      {error&&<div className="family-live-alert error"><span>{error}</span><button type="button" onClick={()=>void loadWorkspace()}>{ar?"حاول مرة أخرى":"Try again"}</button></div>}
      <div className="section-heading"><div><h2>{ar?"مساحة رعايتك":"Your care workspace"}</h2><p>{ar?"كل وجهة أدناه تستخدم بيانات موثقة ومملوكة لحسابك.":"Every destination below uses authenticated, account-owned data."}</p></div></div>
      <div className="categories home-live-actions"><a href="/navigator"><span>◇</span><b>{ar?"موجّه الرعاية":"Care Navigator"}</b><small>{ar?"نقطة بداية منظمة مع فحص الطوارئ أولاً":"A structured, emergency-first care starting point"}</small></a><a href="/providers"><span>⌕</span><b>{ar?"ابحث عن رعاية":"Find care"}</b><small>{ar?"مقدمو رعاية موثّقون وتوفر منشور":"Verified providers and published availability"}</small></a><a href="/appointments"><span>◎</span><b>{ar?"المواعيد":"Appointments"}</b><small>{ar?"احجز الزيارات أو راجعها أو ألغها بأمان":"Book, review, or safely cancel visits"}</small></a><a href="/queue"><span>⌁</span><b>{ar?"تسجيل الوصول":"Digital check-in"}</b><small>{ar?"حالة موثوقة فقط عندما يحدّثها المرفق":"Facility-owned status with freshness safeguards"}</small></a><a href="/laboratory"><span>△</span><b>{ar?"طلبات المختبر":"Laboratory orders"}</b><small>{ar?"الطلبات الموقعة والنتائج الصادرة":"Signed orders and issued results"}</small></a><a href="/home-care"><span>⌂</span><b>{ar?"الرعاية المنزلية":"Home care"}</b><small>{ar?"خدمات معتمدة وعاملون موثقون":"Approved services and verified workers"}</small></a><a href="/wallet"><span>▤</span><b>{ar?"السجلات الصحية":"Health records"}</b><small>{ar?"معلومات الزيارة النهائية المرئية للمريض":"Finalized patient-visible visit information"}</small></a><a href="/payments"><span>Q</span><b>{ar?"المدفوعات":"Payments"}</b><small>{ar?"حالة سجل المدفوعات المملوك للحساب":"Account-owned payment ledger status"}</small></a><a href="/family"><span>♧</span><b>{ar?"وصول العائلة":"Family access"}</b><small>{ar?"صلاحيات مفوضة صريحة وقابلة للإلغاء":"Explicit, revocable delegated permissions"}</small></a><a href="/support"><span>◇</span><b>{ar?"الدعم":"Support"}</b><small>{ar?"أنشئ طلبات دعم دائمة وتابعها":"Create and track durable support requests"}</small></a></div>
      <div className="categories home-live-actions"><a href="/pharmacy"><span>✚</span><b>{ar?"الصيدلية والتجديد":"Pharmacy & refills"}</b><small>{ar?"تنفيذ مضبوط ومراجعة بشرية للتجديد":"Controlled fulfilment and human refill review"}</small></a><a href="/sample-collection"><span>◌</span><b>{ar?"جمع العينات من المنزل":"Home sample collection"}</b><small>{ar?"طلب مختبر موقع وجامع عينات موثق":"Signed lab order and verified collector"}</small></a><a href="/encounter-follow-up"><span>↺</span><b>{ar?"تعديلات الزيارة والمتابعة":"Visit updates & follow-up"}</b><small>{ar?"السجل الأصلي مع كل تحديث مرتبط":"Original record with every linked update"}</small></a><a href="/benefits"><span>◇</span><b>{ar?"مزاياي":"My benefits"}</b><small>{ar?"أهلية مرتبطة بالموافقة من دون كشف نشاطك الصحي":"Consent-bound eligibility without employer health visibility"}</small></a><a href="/reviews"><span>☆</span><b>{ar?"مراجعاتي":"My reviews"}</b><small>{ar?"مراجعات موثقة مرتبطة بالمواعيد المكتملة":"Verified reviews from completed appointments"}</small></a><a href="/payment-support"><span>Q</span><b>{ar?"دعم المدفوعات":"Payment support"}</b><small>{ar?"تابع مشكلة دفع أو طلب استرداد مسجل":"Track a recorded payment issue or refund request"}</small></a></div>
      <div className="categories home-live-actions"><a href="/care-plan"><span>✓</span><b>{ar?"خطة الرعاية":"Care plan"}</b><small>{ar?"أهداف مشتركة وخطوات متابعة واضحة":"Shared goals and clear follow-up steps"}</small></a><a href="/diagnostic-imaging"><span>◈</span><b>{ar?"التصوير التشخيصي":"Diagnostic imaging"}</b><small>{ar?"الطلبات والمواعيد والتقارير النهائية":"Orders, schedules, and final reports"}</small></a><a href="/insurance"><span>▣</span><b>{ar?"التأمين والموافقات":"Insurance & authorization"}</b><small>{ar?"الأهلية وحالة الموافقات المسبقة":"Eligibility and prior-authorization status"}</small></a><a href="/saved-care"><span>♡</span><b>{ar?"الرعاية المحفوظة":"Saved care"}</b><small>{ar?"احفظ وقارن مقدمي الرعاية الموثقين بشفافية":"Save and transparently compare verified providers"}</small></a></div>
      <div className="categories home-live-actions"><a href="/privacy-rights"><span>◫</span><b>{ar?"حقوق الخصوصية":"Privacy rights"}</b><small>{ar?"طلبات التصدير والتصحيح وإغلاق الحساب":"Export, correction, and account-closure requests"}</small></a><a href="/health-library"><span>▤</span><b>{ar?"مكتبة الصحة":"Health library"}</b><small>{ar?"محتوى ثنائي اللغة بمراجعة طبية":"Medically reviewed bilingual content"}</small></a><a href="/emergency-profile"><span>✚</span><b>{ar?"ملف الطوارئ":"Emergency profile"}</b><small>{ar?"معلومات مهمة تدخلها أنت مع حدود واضحة":"User-entered critical information with clear boundaries"}</small></a></div>
      <div className="categories home-live-actions"><a href="/health-profile"><span>♡</span><b>{ar?"ملفي الصحي":"My health profile"}</b><small>{ar?"معلومات صحية تدخلها أنت مع مصدر واضح":"User-entered health information with clear provenance"}</small></a><a href="/consents"><span>✓</span><b>{ar?"مركز الموافقات":"Consent Center"}</b><small>{ar?"موافقات محددة الغرض وقابلة للسحب":"Purpose-specific, revocable consent"}</small></a><a href="/complaints"><span>!</span><b>{ar?"الشكاوى والسلامة":"Complaints & safety"}</b><small>{ar?"توجيه منفصل للخدمة والخصوصية والسلامة":"Separate service, privacy, and safety routing"}</small></a></div>
      <div className="categories home-live-actions"><a href="/account/security"><span>⌾</span><b>{ar?"أمان الحساب":"Account security"}</b><small>{ar?"راجع جلسات رعايتي وألغِ الصلاحيات المحلية":"Review Reyati sessions and revoke local authorization"}</small></a><a href="/notification-preferences"><span>◉</span><b>{ar?"تفضيلات الإشعارات":"Notification preferences"}</b><small>{ar?"تحكم واضح حسب الفئة والقناة":"Explicit controls by category and channel"}</small></a></div>
      <div className="categories home-live-actions"><a href="/facilities"><span>⌂</span><b>{ar?"دليل المنشآت":"Facility directory"}</b><small>{ar?"ملفات منشآت موثقة مع المصدر وحداثة المعلومات":"Verified profiles with source and freshness labels"}</small></a><a href="/settings/accessibility"><span>◐</span><b>{ar?"اللغة وإمكانية الوصول":"Language & accessibility"}</b><small>{ar?"تفضيلات صريحة لتجربة أوضح وأسهل":"Explicit preferences for a clearer experience"}</small></a></div>
      <div className="categories home-live-actions"><a href="/account/profile"><span>♙</span><b>{ar?"ملفي الشخصي":"My profile"}</b><small>{ar?"بيانات رعايتي مع حدود واضحة لهوية تسجيل الدخول":"Reyati details with clear sign-in identity boundaries"}</small></a><a href="/service-status"><span>●</span><b>{ar?"حالة الخدمات":"Service status"}</b><small>{ar?"تحديثات بشرية المراجعة عن الحالات التشغيلية المعروفة":"Human-reviewed updates about known operational conditions"}</small></a></div>
      <div className="section-heading providers-heading"><div><h2>{ar?"الموعد القادم":"Next appointment"}</h2><p>{ar?"محمّل من حساب المريض المسجّل.":"Loaded from your signed-in patient account."}</p></div><a href="/appointments">{ar?"كل المواعيد ←":"All appointments →"}</a></div>
      {loading?<div className="appointment-live-state"><span>◇</span><h2>{ar?"جارٍ تحميل مساحة رعايتك…":"Loading your care workspace…"}</h2></div>:error?<div className="appointment-live-state error"><span>!</span><h2>{ar?"حالة الموعد غير متاحة":"Appointment status unavailable"}</h2><p>{ar?"تعذر على رعايتي تأكيد أحدث جدول. حاول مرة أخرى قبل الاعتماد على هذا القسم.":"Reyati could not confirm your latest schedule. Try again before relying on this section."}</p></div>:nextAppointment?<section className="next-appt"><div className="date-block"><b>{new Date(nextAppointment.scheduledStart).toLocaleDateString(lang==="ar"?"ar-QA":"en-QA",{day:"2-digit"})}</b><span>{new Date(nextAppointment.scheduledStart).toLocaleDateString(lang==="ar"?"ar-QA":"en-QA",{month:"short"}).toUpperCase()}</span></div><div><p>{nextAppointment.status.replaceAll("_"," ")}</p><h3>{nextAppointment.providerName}</h3><span>{formatVisit(nextAppointment.scheduledStart,lang)} · {nextAppointment.mode.replaceAll("_"," ")}</span></div><div className="appt-location"><span>⌖</span><div><b>{nextAppointment.facilityName||(ar?"استشارة فيديو":"Video consultation")}</b><small>{nextAppointment.specialty}</small></div></div><a href="/appointments">{ar?"عرض التفاصيل":"View details"}</a></section>:<div className="home-empty-appointment"><span>◎</span><div><h3>{ar?"لا يوجد موعد قادم":"No upcoming appointment"}</h3><p>{ar?"اختر مقدم رعاية موثّقاً ووقتاً منشوراً عندما تكون مستعداً.":"Choose a verified provider and a currently published time whenever you are ready."}</p></div><a href="/providers">{ar?"ابحث عن رعاية":"Find care"}</a></div>}
      <section className="wallet-notice home-trust-note"><span>i</span><p><b>{ar?"لا توجد معلومات مخترعة في هذه الصفحة.":"No information is invented on this page."}</b> {ar?"تبقى الحالات الفارغة فارغة حتى يتم إنشاء نشاط عبر مسارات رعايتي الآمنة.":"Empty states remain empty until activity is created through the secure Reyati workflows."}</p></section>
    </section>
    <footer><img src="/brand/reyati-logo.svg" alt="Reyati"/><p>{ar?"رعاية مترابطة بذكاء.":"Care, intelligently connected."}</p><a href="/auth">{ar?"الحساب الآمن":"Secure account"}</a><small>{ar?"مساحة مريض موثقة":"Authenticated patient workspace"}</small></footer>
  </main>;
}
