"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./complaints.module.css";

type Context = { appointments: Array<{ id: string; status: string; scheduledStart: string }>; supportCases: Array<{ id: string; reference: string; status: string; category: string }> };
type Complaint = { id: string; reference: string; category: string; subject: string; narrative: string; desiredOutcome: string; status: string; severity: string; resolutionReasonCode: string | null; resolutionSummary: string | null; version: number; submittedAt: string; submissions: Array<{ id: string; kind: string; details: string; createdAt: string }>; events: Array<{ id: string; action: string; nextStatus: string; reasonCode: string | null; createdAt: string }> };
type Workspace = { complaints: Complaint[]; context: Context; emergencyBoundary: string };

const categoryCopy = {
  service: { en: "Service experience", ar: "تجربة الخدمة" },
  privacy: { en: "Privacy concern", ar: "ملاحظة حول الخصوصية" },
  clinical_safety: { en: "Clinical safety concern", ar: "ملاحظة حول السلامة السريرية" },
};

export default function ComplaintsPage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Workspace | null>(null), [category, setCategory] = useState("service"), [subject, setSubject] = useState(""), [narrative, setNarrative] = useState(""), [desiredOutcome, setDesiredOutcome] = useState(""), [contextKind, setContextKind] = useState("none"), [contextId, setContextId] = useState(""), [notEmergency, setNotEmergency] = useState(false), [attested, setAttested] = useState(false), [additional, setAdditional] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { try { const response = await fetch("/api/complaints", { cache: "no-store", signal }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error); setData(payload.data); setError(""); } catch (reason) { if (reason instanceof DOMException && reason.name === "AbortError") return; setError(ar ? "تعذر تحميل سجل الملاحظات الخاص بك." : "Your private concerns tracker could not be loaded."); } }, [ar]);
  useEffect(() => { const controller = new AbortController(); queueMicrotask(() => { if (!controller.signal.aborted) void load(controller.signal); }); return () => controller.abort(); }, [load]);
  async function act(body: Record<string, unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/complaints", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setMessage(success); setSubject(""); setNarrative(""); setDesiredOutcome(""); setContextKind("none"); setContextId(""); setNotEmergency(false); setAttested(false); setAdditional({}); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? "تعذر إكمال الطلب." : "The request could not be completed.")); } finally { setBusy(false); } }
  function submit(event: FormEvent) { event.preventDefault(); void act({ action: "create", category, subject, narrative, desiredOutcome, appointmentId: contextKind === "appointment" ? contextId : null, supportCaseId: contextKind === "support" ? contextId : null, notEmergencyAcknowledged: notEmergency, truthfulAccountAttested: attested }, ar ? "تم تسجيل ملاحظتك بأمان للمراجعة البشرية." : "Your concern was securely recorded for human review."); }
  const categoryLabel = (value: string) => categoryCopy[value as keyof typeof categoryCopy]?.[ar ? "ar" : "en"] ?? value.replaceAll("_", " ");
  const statusLabel = (value: string) => ({ submitted: ar ? "تم الإرسال" : "Submitted", under_review: ar ? "قيد المراجعة" : "Under review", information_required: ar ? "معلومات مطلوبة" : "Information required", resolved: ar ? "تم الحل" : "Resolved" }[value] ?? value);
  const contextOptions = contextKind === "appointment" ? data?.context.appointments.map((item) => ({ id: item.id, label: `${new Date(item.scheduledStart).toLocaleDateString(ar ? "ar-QA" : "en-QA")} · ${item.status}` })) : contextKind === "support" ? data?.context.supportCases.map((item) => ({ id: item.id, label: `${item.reference} · ${item.status}` })) : [];
  return <main className={`${styles.shell} trust-center-shell complaints-experience`} dir={ar ? "rtl" : "ltr"}>
    <header className={styles.top}><a href="/"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya" /></a><nav><a href="/support">{ar ? "الدعم" : "Support"}</a><a href="/notifications">{ar ? "الإشعارات" : "Notifications"}</a><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></nav></header>
    <section className={styles.hero}><span className={styles.eyebrow}>{ar ? "استماع موثّق ومساءلة واضحة" : "Accountable listening"}</span><h1>{ar ? "الملاحظات ومخاوف السلامة" : "Complaints & safety concerns"}</h1><p>{ar ? "شارك تجربة خدمة أو ملاحظة خصوصية أو مخاوف سلامة سريرية، وتابع الاستجابة البشرية في سجل خاص مرتبط بحسابك." : "Share a service experience, privacy concern, or clinical-safety concern and follow the accountable human response in a private tracker tied to your account."}</p></section>
    <div className={styles.workspace}>
      <div className={styles.emergency}><span className={styles.emergencyIcon}>999</span><div><b>{ar ? "ليست قناة للطوارئ" : "This is not an emergency channel"}</b><p>{ar ? "لا تتم مراقبة هذه النماذج للاستجابة الفورية. إذا كان هناك خطر يهدد الحياة في قطر، اتصل بالرقم 999 الآن." : "These submissions are not monitored for immediate response. For a life-threatening emergency in Qatar, call 999 now."}</p></div></div>
      {message && <p className={styles.status} role="status">{message}</p>}{error && <p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
      <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "ملاحظة جديدة" : "New concern"}</span><h2>{ar ? "أخبرنا بما حدث" : "Tell us what happened"}</h2></div><p className={styles.muted}>{ar ? "شارك فقط المعلومات اللازمة للمراجعة. سيتعامل معها شخص مخوّل." : "Share only what is necessary for review. An authorized person will handle it."}</p></div>
        <form className={styles.form} onSubmit={submit}>
          <label className={styles.field}>{ar ? "النوع" : "Category"}<select value={category} onChange={(event) => setCategory(event.target.value)}>{Object.entries(categoryCopy).map(([value, copy]) => <option value={value} key={value}>{copy[ar ? "ar" : "en"]}</option>)}</select></label>
          <label className={styles.field}>{ar ? "عنوان موجز" : "Short subject"}<input value={subject} onChange={(event) => setSubject(event.target.value)} maxLength={120} placeholder={ar ? "مثال: تأخر شرح الخطوات التالية" : "Example: delay explaining next steps"} /></label>
          <label className={`${styles.field} ${styles.wide}`}>{ar ? "ما الذي حدث؟" : "What happened?"}<textarea value={narrative} onChange={(event) => setNarrative(event.target.value)} maxLength={3000} placeholder={ar ? "اذكر الوقائع والتوقيت وما تتذكره بوضوح…" : "Describe the facts, timing, and what you remember clearly…"} /><span className={styles.counter}>{narrative.length}/3000</span></label>
          <label className={`${styles.field} ${styles.wide}`}>{ar ? "ما النتيجة التي تأملها؟" : "What outcome would help?"}<textarea className={styles.short} value={desiredOutcome} onChange={(event) => setDesiredOutcome(event.target.value)} maxLength={600} placeholder={ar ? "مثال: توضيح مكتوب ومراجعة الإجراء" : "Example: a written explanation and process review"} /></label>
          <label className={styles.field}>{ar ? "ربط بسياق اختياري" : "Optional related context"}<select value={contextKind} onChange={(event) => { setContextKind(event.target.value); setContextId(""); }}><option value="none">{ar ? "بدون ربط" : "No related context"}</option><option value="appointment">{ar ? "موعد من حسابي" : "An appointment from my account"}</option><option value="support">{ar ? "طلب دعم من حسابي" : "A support case from my account"}</option></select></label>
          {contextKind !== "none" && <label className={styles.field}>{ar ? "اختر السجل" : "Choose record"}<select value={contextId} onChange={(event) => setContextId(event.target.value)}><option value="">{ar ? "اختر…" : "Select…"}</option>{contextOptions?.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label>}
          <label className={`${styles.check} ${styles.wide}`}><input type="checkbox" checked={notEmergency} onChange={(event) => setNotEmergency(event.target.checked)} />{ar ? "أفهم أن هذه ليست قناة طوارئ، وسأتصل بالرقم 999 فوراً عند وجود خطر يهدد الحياة." : "I understand this is not an emergency channel and will call 999 now for a life-threatening danger."}</label>
          <label className={`${styles.check} ${styles.wide}`}><input type="checkbox" checked={attested} onChange={(event) => setAttested(event.target.checked)} />{ar ? "أؤكد أن هذا وصف صادق حسب أفضل معرفتي." : "I confirm this is a truthful account to the best of my knowledge."}</label>
          <div className={`${styles.actions} ${styles.wide}`}><button className={styles.primary} type="submit" disabled={busy || subject.trim().length < 5 || narrative.trim().length < 20 || desiredOutcome.trim().length < 5 || !notEmergency || !attested || (contextKind !== "none" && !contextId)}>{busy ? (ar ? "جارٍ التسجيل…" : "Recording…") : (ar ? "إرسال للمراجعة البشرية" : "Submit for human review")}</button><span className={styles.meta}>{ar ? "لا يتم الإرسال تلقائياً إلى مقدم الخدمة أو جهة تنظيمية." : "Nothing is automatically sent to a provider or regulator."}</span></div>
        </form>
      </section>
      <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "سجل خاص" : "Private tracker"}</span><h2>{ar ? "ملاحظاتك" : "Your concerns"}</h2></div><p className={styles.muted}>{ar ? "لا يمكن لأي مريض آخر رؤية هذه السجلات." : "No other patient can view these records."}</p></div>
        {!data ? <div className={styles.empty}>{ar ? "جارٍ التحميل…" : "Loading…"}</div> : data.complaints.length === 0 ? <div className={styles.empty}>{ar ? "لا توجد ملاحظات مسجلة حتى الآن." : "No concerns recorded yet."}</div> : <div className={styles.grid}>{data.complaints.map((item) => <article className={styles.card} key={item.id}><div className={styles.cardTop}><div><span className={styles.reference}>{item.reference}</span><h3>{item.subject}</h3><span className={styles.meta}>{categoryLabel(item.category)} · {new Date(item.submittedAt).toLocaleDateString(ar ? "ar-QA" : "en-QA")}</span></div><span className={styles.pill}>{statusLabel(item.status)}</span></div><p className={styles.narrative}>{item.narrative}</p><div className={styles.outcome}><b>{ar ? "النتيجة المطلوبة" : "Requested outcome"}</b><p>{item.desiredOutcome}</p></div><div className={styles.timeline}>{item.events.map((event) => <div key={event.id}><i /><p><b>{statusLabel(event.nextStatus)}</b>{event.reasonCode ? ` · ${event.reasonCode.replaceAll("_", " ")}` : ""}</p><time>{new Date(event.createdAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</time></div>)}</div>{item.resolutionSummary && <div className={styles.resolution}><b>{ar ? "ملخص الحل" : "Resolution summary"}</b><p>{item.resolutionSummary}</p></div>}{item.status === "information_required" && <div className={styles.supplement}><label className={styles.field}>{ar ? "المعلومات الإضافية المطلوبة" : "Requested additional information"}<textarea value={additional[item.id] ?? ""} onChange={(event) => setAdditional((current) => ({ ...current, [item.id]: event.target.value }))} maxLength={2000} /></label><button className={styles.primary} type="button" disabled={busy || (additional[item.id]?.trim().length ?? 0) < 12} onClick={() => void act({ action: "provide_information", complaintId: item.id, version: item.version, details: additional[item.id] }, ar ? "تمت إضافة المعلومات بأمان." : "Information was added securely.")}>{ar ? "إرسال المعلومات" : "Send information"}</button></div>}</article>)}</div>}
      </section>
    </div>
  </main>;
}
