"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./privacy-rights.module.css";

type Submission = { id: string; submissionType: string; details: string; createdAt: string };
type PrivacyRequest = { id: string; requestType: string; status: string; version: number; submittedAt: string; updatedAt: string; decisionCode: string | null; completionReference: string | null; submissions: Submission[] };
type Workspace = { requests: PrivacyRequest[]; guidance: string };

const typeCopy = {
  data_export: { en: "Access or export my data", ar: "الوصول إلى بياناتي أو تصديرها" },
  data_correction: { en: "Correct my information", ar: "تصحيح معلوماتي" },
  account_closure: { en: "Request account closure", ar: "طلب إغلاق الحساب" },
};

export default function PrivacyRightsPage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Workspace | null>(null), [requestType, setRequestType] = useState("data_export"), [details, setDetails] = useState(""), [attested, setAttested] = useState(false), [boundary, setBoundary] = useState(false), [supplements, setSupplements] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { try { const response = await fetch("/api/privacy-rights", { cache: "no-store", signal }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error); setData(payload.data); setError(""); } catch (reason) { if (reason instanceof DOMException && reason.name === "AbortError") return; setError(ar ? "تعذر تحميل مركز حقوق الخصوصية." : "The Privacy Rights Center could not be loaded."); } }, [ar]);
  useEffect(() => { const controller = new AbortController(); queueMicrotask(() => { if (!controller.signal.aborted) void load(controller.signal); }); return () => controller.abort(); }, [load]);
  async function act(body: Record<string, unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/privacy-rights", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setMessage(success); setDetails(""); setSupplements({}); setAttested(false); setBoundary(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? "تعذر إكمال الطلب." : "The request could not be completed.")); } finally { setBusy(false); } }
  function submit(event: FormEvent) { event.preventDefault(); void act({ action: "create", requestType, details, identityAttested: attested, boundaryAcknowledged: boundary }, ar ? "تم إرسال طلبك بأمان." : "Your request was submitted securely."); }
  const label = (value: string) => typeCopy[value as keyof typeof typeCopy]?.[ar ? "ar" : "en"] ?? value.replaceAll("_", " ");
  const statusLabel = (value: string) => ({ submitted: ar ? "تم الإرسال" : "Submitted", under_review: ar ? "قيد المراجعة" : "Under review", additional_information_required: ar ? "معلومات إضافية مطلوبة" : "Information required", approved_for_manual_fulfillment: ar ? "معتمد للتنفيذ اليدوي" : "Approved for manual fulfilment", completed: ar ? "اكتمل يدوياً" : "Manually completed", declined: ar ? "لم تتم الموافقة" : "Not approved", cancelled: ar ? "ملغي" : "Cancelled" }[value] ?? value);
  return <main className={`${styles.shell} trust-center-shell privacy-rights-experience`} dir={ar ? "rtl" : "ltr"}>
    <header className={styles.top}><a href="/"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya" /></a><nav><a href="/support">{ar ? "الدعم" : "Support"}</a><a href="/notifications">{ar ? "الإشعارات" : "Notifications"}</a><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></nav></header>
    <section className={styles.hero}><span className={styles.eyebrow}>{ar ? "الخصوصية تحت سيطرتك" : "Privacy under your control"}</span><h1>{ar ? "مركز حقوق الخصوصية" : "Privacy Rights Center"}</h1><p>{ar ? "أرسل طلباً منظماً للوصول إلى بياناتك أو تصحيحها أو إغلاق حسابك، وتابع كل خطوة من مكان واحد آمن." : "Submit a structured request to access your data, correct information, or close your account—and follow every step in one protected place."}</p></section>
    <div className={styles.workspace}><div className={styles.boundary}><span className={styles.boundaryIcon}>i</span><div><b>{ar ? "عملية موثقة، وليست تنفيذاً تلقائياً" : "A tracked process, not an automatic action"}</b><p>{ar ? "لا يؤدي الإرسال إلى تنزيل البيانات أو تعديل السجلات أو حذفها أو إغلاق الحساب فوراً. يراجع فريق مخول الطلب وينفذه يدوياً بعد التحقق." : "Submitting does not instantly download data, alter or delete records, or close an account. An authorized team reviews and manually fulfils approved requests after verification."}</p></div></div>
      {message && <p className={styles.status} role="status">{message}</p>}{error && <p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
      <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "طلب جديد" : "New request"}</span><h2>{ar ? "اختر الحق الذي تريد ممارسته" : "Choose the right you want to exercise"}</h2></div><p className={styles.muted}>{ar ? "اكتب الحد الأدنى اللازم لمعالجة طلبك." : "Share only what is necessary to process your request."}</p></div>
        <form className={styles.form} onSubmit={submit}><label className={styles.field}>{ar ? "نوع الطلب" : "Request type"}<select value={requestType} onChange={(event) => setRequestType(event.target.value)}>{Object.entries(typeCopy).map(([value, copy]) => <option key={value} value={value}>{copy[ar ? "ar" : "en"]}</option>)}</select></label><label className={styles.field}>{ar ? "ما الذي تريد منا مراجعته؟" : "What should we review?"}<textarea value={details} onChange={(event) => setDetails(event.target.value)} maxLength={2000} placeholder={ar ? "اذكر السجلات أو المعلومات ذات الصلة فقط…" : "Describe only the relevant records or information…"} /></label>
          <label className={`${styles.check} ${styles.wide}`}><input type="checkbox" checked={attested} onChange={(event) => setAttested(event.target.checked)} />{ar ? "أؤكد أنني أقدم هذا الطلب لحسابي الموثق." : "I confirm that I am making this request for my authenticated account."}</label><label className={`${styles.check} ${styles.wide}`}><input type="checkbox" checked={boundary} onChange={(event) => setBoundary(event.target.checked)} />{ar ? "أفهم أن التنفيذ يتم يدوياً بعد المراجعة والتحقق." : "I understand fulfilment is manual and occurs only after review and verification."}</label><div className={`${styles.actions} ${styles.wide}`}><button className={styles.primary} type="submit" disabled={busy || details.trim().length < 12 || !attested || !boundary}>{busy ? (ar ? "جارٍ الإرسال…" : "Submitting…") : (ar ? "إرسال الطلب" : "Submit request")}</button><span className={styles.meta}>{details.length}/2000</span></div></form>
      </section>
      <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "سجل محمي" : "Protected history"}</span><h2>{ar ? "طلباتك" : "Your requests"}</h2></div><p className={styles.muted}>{data?.guidance}</p></div>
        {!data ? <div className={styles.empty}>{ar ? "جارٍ التحميل…" : "Loading…"}</div> : data.requests.length === 0 ? <div className={styles.empty}>{ar ? "لا توجد طلبات خصوصية حتى الآن." : "No privacy requests yet."}</div> : <div className={styles.grid}>{data.requests.map((item) => <article className={styles.card} key={item.id}><div className={styles.cardTop}><div><h3>{label(item.requestType)}</h3><span className={styles.meta}>{new Date(item.submittedAt).toLocaleDateString(ar ? "ar-QA" : "en-QA")}</span></div><span className={styles.pill}>{statusLabel(item.status)}</span></div><div className={styles.timeline}>{item.submissions.map((submission) => <div key={submission.id}><p>{submission.details}</p><time>{submission.submissionType.replaceAll("_", " ")} · {new Date(submission.createdAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</time></div>)}</div>{item.status === "additional_information_required" && <label className={styles.field}>{ar ? "معلومات إضافية" : "Additional information"}<textarea value={supplements[item.id] ?? ""} onChange={(event) => setSupplements((current) => ({ ...current, [item.id]: event.target.value }))} maxLength={2000} /></label>}<div className={styles.actions}>{item.status === "additional_information_required" && <button className={styles.primary} type="button" disabled={busy || (supplements[item.id]?.trim().length ?? 0) < 12} onClick={() => void act({ action: "provide_information", requestId: item.id, version: item.version, details: supplements[item.id] }, ar ? "تمت إضافة المعلومات." : "Information added.")}>{ar ? "إرسال المعلومات" : "Send information"}</button>}{["submitted", "additional_information_required"].includes(item.status) && <button className={styles.danger} type="button" disabled={busy} onClick={() => void act({ action: "cancel", requestId: item.id, version: item.version }, ar ? "تم إلغاء الطلب." : "Request cancelled.")}>{ar ? "إلغاء الطلب" : "Cancel request"}</button>}</div></article>)}</div>}
      </section>
    </div>
  </main>;
}
