export type CapabilityStatus = "live" | "read_only" | "role_gated" | "inactive" | "foundation";
export type ReyatiEnvironment = "production" | "investor_demo" | "local";

export type CapabilityDefinition = {
  id: string;
  name: string;
  status: CapabilityStatus;
  supportedEnvironments: readonly ReyatiEnvironment[];
  permittedRoles: readonly string[];
  externalDependencies: readonly string[];
  responsibleOwner: string;
  knownLimitations: string;
  safetyRegulatoryGate: string | null;
  lastValidatedAt: string;
};

const validated = "2026-08-14";
const owner = "TBD — Product and Engineering";
const allEnvironments = ["production", "investor_demo", "local"] as const;

export const capabilityRegistry = [
  { id:"service_status_communications",name:"Service status and incident communications",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor","support_agent"],externalDependencies:["D1","Named incident communications owner","Independent reviewer"],responsibleOwner:owner,knownLimitations:"Patients can view human-reviewed bilingual availability notices and recovery history. Automatic incident disclosure or publishing, external status-provider synchronization, security-detail disclosure, and guaranteed-availability claims remain disabled.",safetyRegulatoryGate:"Incident communication policy, sanitization checklist, accountable roster, update cadence, accessibility review, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"patient_profile_management",name:"Patient profile and contact preferences",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Hosted identity context"],responsibleOwner:owner,knownLimitations:"Patients maintain bounded Reyati profile preferences while hosted identity fields remain read-only and distinctly labelled. Identity mutation, automatic verification, external synchronization, clinical inference, and administrative identity disclosure remain disabled.",safetyRegulatoryGate:"Profile field policy, contact verification architecture, emergency-contact handling, privacy review, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"tenant_configuration_governance",name:"Organization configuration governance",status:"foundation",supportedEnvironments:allEnvironments,permittedRoles:["organization_owner","organization_admin","platform_admin","security_auditor"],externalDependencies:["D1","Verified organization","Named configuration reviewer"],responsibleOwner:owner,knownLimitations:"Organization owners prepare bounded configuration proposals for independent review. Approval is evidence only and cannot change runtime flags, policies, fees, secrets, deployments, or cross-tenant configuration.",safetyRegulatoryGate:"Tenant configuration policy, runtime integration design, separation-of-duties roster, rollback validation, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"policy_template_governance",name:"Bilingual policy and communication templates",status:"foundation",supportedEnvironments:allEnvironments,permittedRoles:["platform_admin","security_auditor"],externalDependencies:["D1","Approved content owners","Independent reviewer"],responsibleOwner:owner,knownLimitations:"Authorized operators govern bilingual operational templates through maker-checker review and a bounded placeholder allowlist. Outbound delivery, legal effect, clinical-instruction generation, automatic translation, and external synchronization remain disabled.",safetyRegulatoryGate:"Content-owner roster, legal and clinical review boundaries, approved placeholders, channel rendering tests, Arabic linguistic review, and delivery activation decision.",lastValidatedAt:"2026-08-17" },
  { id:"language_accessibility_settings",name:"Language and accessibility settings",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Reyati locale and accessibility shell"],responsibleOwner:owner,knownLimitations:"Patients record explicit language and non-clinical accessibility preferences with immutable history. External synchronization, inferred needs, automatic clinical adjustment, identity disclosure, and third-party assistive telemetry remain disabled.",safetyRegulatoryGate:"Accessibility preference taxonomy, representative assistive-technology testing, Arabic linguistic review, privacy review, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"facility_directory_profiles",name:"Verified facility directory and profiles",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","organization_owner","organization_admin","platform_admin","security_auditor"],externalDependencies:["D1","Verified organization and facility records","Independent publication review"],responsibleOwner:owner,knownLimitations:"Patients discover only reviewed active facility profiles with factual source and freshness labels. External import, automated verification, sponsored ranking, live occupancy, and clinical-quality ranking remain disabled.",safetyRegulatoryGate:"Facility publication standard, source verification, accessibility data policy, stale-profile procedure, moderation ownership, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"platform_release_controls",name:"Platform release-control governance",status:"foundation",supportedEnvironments:allEnvironments,permittedRoles:["platform_admin","security_auditor"],externalDependencies:["D1","Capability registry","Named release owners"],responsibleOwner:owner,knownLimitations:"Authorized operators prepare and independently review bounded change proposals and rollback evidence. The module cannot modify compiled flags, environment variables, secrets, tenant runtime, deployments, or activate any capability.",safetyRegulatoryGate:"Approved change-management policy, release-owner roster, rollback validation, environment separation, and deployment-system integration review.",lastValidatedAt:"2026-08-17" },
  { id:"account_security_sessions",name:"Account security and session controls",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Hosted identity session context"],responsibleOwner:owner,knownLimitations:"Patients can review privacy-safe Reyati session records and revoke recorded local authorization. MFA enrollment, external identity-provider controls, precise location, automatic risk lockout, and termination of the hosted ChatGPT identity session remain disabled.",safetyRegulatoryGate:"Identity-provider decision, session-binding design, reauthentication policy, recovery testing, and independent security review.",lastValidatedAt:"2026-08-17" },
  { id:"notification_preference_center",name:"Category-level notification preferences",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Approved purpose and channel taxonomy"],responsibleOwner:owner,knownLimitations:"Patients manage explicit category and channel preferences with protected transactional and safety boundaries. External delivery and synchronization, inferred consent, clinical personalization, and guaranteed quiet-hour enforcement remain disabled.",safetyRegulatoryGate:"Approved notification taxonomy, mandatory-message policy, channel consent wording, delivery-provider activation, accessibility review, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"platform_catalogue_governance",name:"Bilingual platform catalogue governance",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["platform_admin","security_auditor"],externalDependencies:["D1","Named catalogue owners","Independent reviewer"],responsibleOwner:owner,knownLimitations:"Authorized operators govern versioned bilingual specialties, services, appointment types, document types, languages, and facility attributes through maker-checker review. Automatic taxonomy generation or publishing, external terminology synchronization, clinical-coding claims, and destructive bulk changes remain disabled.",safetyRegulatoryGate:"Catalogue ownership policy, clinical terminology review, dependency and retirement procedure, Arabic linguistic review, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"personal_health_profile",name:"Patient-maintained personal health profile",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Patient acknowledgement"],responsibleOwner:owner,knownLimitations:"Patients maintain bounded allergies, conditions, medicines, and accessibility needs with explicit user-entered and unverified provenance. Provider access, external sharing/import, diagnosis, recommendations, and automatic clinical use remain disabled.",safetyRegulatoryGate:"Clinical terminology review, provenance policy, patient warning, provider-access policy, retention decision, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"purpose_specific_consent_center",name:"Purpose-specific Consent Center",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Approved bilingual policy wording","Named policy owners"],responsibleOwner:owner,knownLimitations:"Patients grant and withdraw current versioned purpose-specific policies with immutable history. Blanket consent, silent renewal, provider override, external synchronization, and automatic downstream activation remain disabled.",safetyRegulatoryGate:"Approved consent taxonomy and wording, policy-owner roster, downstream enforcement mapping, expiry rules, accessibility review, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"complaints_safety_concerns",name:"Complaints and safety-concern operations",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor","support_agent"],externalDependencies:["D1","Named service, privacy, and clinical-safety owners","In-app notifications"],responsibleOwner:owner,knownLimitations:"Patients submit and privately track service, privacy, or clinical-safety concerns. Authorized humans route and resolve cases. Automatic clinical triage, emergency dispatch, regulator submission, provider notification, compensation/refunds, and external ticketing remain disabled.",safetyRegulatoryGate:"Approved classification and severity policy, emergency wording, accountable rosters, escalation SLA, regulator procedure, privacy handling, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"privacy_rights_center",name:"Privacy rights request center",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor","support_agent"],externalDependencies:["D1","Approved privacy operating procedure"],responsibleOwner:owner,knownLimitations:"Patients can submit and track export, correction, and account-closure requests through a human-controlled lifecycle. No automatic export delivery, deletion, account closure, or external-authority submission is enabled.",safetyRegulatoryGate:"Approved identity-verification standard, response-time policy, export and deletion procedure, retention/legal-hold handling, and accountable privacy roster.",lastValidatedAt:"2026-08-17" },
  { id:"trusted_health_content",name:"Trusted bilingual health content",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Named author","Independent medical reviewer","Approved source policy"],responsibleOwner:owner,knownLimitations:"Only independently reviewed, versioned bilingual articles can be published. No diagnosis, clinical personalization, AI generation, or external syndication is enabled.",safetyRegulatoryGate:"Editorial policy, medical-review roster, source standards, correction SLA, accessibility review, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"patient_emergency_profile",name:"Patient-maintained emergency profile",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Patient consent","Approved emergency wording"],responsibleOwner:owner,knownLimitations:"Patients can maintain bounded, explicitly user-entered emergency information with source and verification labels. No panic button, ambulance dispatch, tracking, live ER capacity, automatic clinical use, provider access, or external sharing is enabled.",safetyRegulatoryGate:"Emergency-content review, consent and visibility policy, data-quality warning, support procedure, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"saved_care_comparison",name:"Saved care and transparent provider comparison",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","platform_admin","security_auditor"],externalDependencies:["D1","Verified Reyati provider catalogue"],responsibleOwner:owner,knownLimitations:"Patients privately save verified providers and compare two or three using current factual catalogue fields. No algorithmic recommendation, clinical-quality ranking, sponsored influence, provider disclosure, or external profile import is enabled.",safetyRegulatoryGate:"Approved comparison-field policy, sponsored-content separation, stale-profile handling, accessibility review, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"collaborative_care_plans",name:"Collaborative care plans and goals",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","provider","platform_admin","security_auditor"],externalDependencies:["D1","Eligible appointment","Verified provider","In-app notifications"],responsibleOwner:owner,knownLimitations:"Verified providers author appointment-bound bilingual plans with immutable versions, goals, tasks, owners, due dates, and patient instructions. Patients can acknowledge, record bounded progress, and request review, but cannot change clinical instructions. Autonomous recommendations, device integration, external messaging, and clinical automation remain disabled.",safetyRegulatoryGate:"Care-plan authorship policy, patient progress boundaries, emergency wording, clinical owner, retention decision, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"diagnostic_imaging_coordination",name:"Diagnostic imaging orders and results",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","provider","organization_owner","organization_admin","practitioner","scheduler","platform_admin","security_auditor"],externalDependencies:["D1","Approved imaging organization","Signed provider order"],responsibleOwner:owner,knownLimitations:"Supports signed appointment-bound imaging orders, guarded partner workflow, scheduling, and text-only synthetic final reports. PACS, RIS, DICOM, image upload/viewing, automated interpretation, and automated urgent escalation remain disabled.",safetyRegulatoryGate:"Imaging partner agreement, order and signature policy, report-integrity controls, urgent-finding protocol, retention decision, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"insurance_eligibility_authorization",name:"Insurance eligibility and pre-authorization",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","provider","organization_owner","organization_admin","operations","finance","platform_admin","security_auditor"],externalDependencies:["D1","Approved payer organization","Patient consent","Reference-only policy identifier"],responsibleOwner:owner,knownLimitations:"Patients register a masked synthetic/reference-only policy with explicit consent, providers submit service-linked authorization requests, and authorized payer members manually record eligibility and decisions. No external payer API, claim adjudication, payment guarantee, premium collection, automated eligibility or authorization, clinical decision, or card storage is connected.",safetyRegulatoryGate:"Payer agreement, minimum-data policy, decision reason taxonomy, appeals process, coverage disclaimer, retention decision, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"encounter_amendments_follow_up",name:"Encounter amendments and follow-up",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","provider","platform_admin","security_auditor"],externalDependencies:["D1","Finalized encounter note","In-app notifications"],responsibleOwner:owner,knownLimitations:"Verified providers can append linked amendments and create appointment-bound follow-up recommendations. The original finalized note remains immutable; correction and void requests require a separate explicit authorization. Patients can acknowledge recommendations but cannot alter clinical content.",safetyRegulatoryGate:"Clinical amendment and correction policy, authorization ownership, retention rules, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"controlled_pharmacy_fulfilment",name:"Controlled pharmacy fulfilment and refill review",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","provider","organization_owner","organization_admin","practitioner","scheduler","platform_admin","security_auditor"],externalDependencies:["D1","Approved pharmacy organization","Provider-issued prescription","In-app notifications"],responsibleOwner:owner,knownLimitations:"Patients explicitly select an approved pharmacy and configured fulfilment mode. Pharmacy members use guarded states and refill requests always require provider review. Inventory, controlled-drug, payment, courier tracking, uncertain-OCR actions, and external integration remain disabled.",safetyRegulatoryGate:"Pharmacy partner agreement, prescription and refill policy, controlled-drug exclusion, fulfilment SOP, retention decision, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"home_sample_collection",name:"Home sample-collection coordination",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","organization_owner","organization_admin","practitioner","scheduler","platform_admin","security_auditor"],externalDependencies:["D1","Eligible signed laboratory order","Approved collection organization","Verified collector"],responsibleOwner:owner,knownLimitations:"Patients can request home collection for an eligible signed laboratory order. Approved partners assign verified collectors through guarded states. Live location tracking, external courier, automatic assignment, automatic result interpretation, and critical-result substitution remain disabled.",safetyRegulatoryGate:"Collection partner approval, collector credential policy, identity and missed-visit protocol, specimen-chain responsibility, safeguarding ownership, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"digital_check_in_queue",name:"Digital check-in and live queue",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","provider","organization_admin","platform_admin","security_auditor"],externalDependencies:["D1","Enabled facility queue source","Confirmed in-person appointment"],responsibleOwner:owner,knownLimitations:"Only explicitly enabled locations can accept digital check-in. Queue position and delay are shown only while facility-owned source data is fresh; stale data is replaced with neutral guidance.",safetyRegulatoryGate:"Facility operating procedure, reception ownership, freshness monitoring, patient communication, and controlled-pilot evidence before wider activation.",lastValidatedAt:"2026-08-17" },
  { id:"laboratory_orders_results",name:"Laboratory orders and results",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","provider","organization_owner","organization_admin","practitioner","scheduler","platform_admin","security_auditor"],externalDependencies:["D1","Approved laboratory organization","Signed provider order"],responsibleOwner:owner,knownLimitations:"Supports signed appointment-bound orders, controlled partner state changes, and synthetic text-only demonstration results. No external LIS, result upload, automated interpretation, or automated urgent escalation is connected.",safetyRegulatoryGate:"Laboratory partner agreement, order and signature policy, result-integrity controls, urgent-result protocol, retention decision, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"controlled_home_care",name:"Controlled home-care fulfilment",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","organization_owner","organization_admin","practitioner","scheduler","platform_admin","security_auditor"],externalDependencies:["D1","Approved home-care organization","Verified service workers"],responsibleOwner:owner,knownLimitations:"Patients can request approved services and partners can assign verified workers through guarded states. No freelancer marketplace, automatic assignment, external delivery, or live location tracking is enabled.",safetyRegulatoryGate:"Home-care partner approval, worker credential policy, missed-visit and identity-mismatch protocol, safeguarding ownership, and controlled-pilot evidence.",lastValidatedAt:"2026-08-17" },
  { id:"appointment_waitlist",name:"Appointment waitlist and availability offers",status:"role_gated",supportedEnvironments:allEnvironments,permittedRoles:["patient","provider","platform_admin","security_auditor"],externalDependencies:["D1","Published provider availability","In-app notifications"],responsibleOwner:owner,knownLimitations:"Patients can request an earlier appointment window; providers manually offer a published slot and patients explicitly accept. No automatic ranking, matching, booking, or external delivery occurs.",safetyRegulatoryGate:"Approved fairness policy, offer-expiry operations, capacity ownership, and controlled-pilot evidence before automated matching.",lastValidatedAt:"2026-08-17" },
  { id: "patient_experience_feedback", name: "Patient experience and quality feedback", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Completed or confirmed appointment"], responsibleOwner: owner, knownLimitations: "Patients can submit one structured pre-visit or post-visit response per eligible appointment and withdraw it. Providers and platform operators see privacy-thresholded aggregates only; no individual response, public rating, automated provider action, free-text clinical narrative, or external analytics export is exposed.", safetyRegulatoryGate: "Approved experience-measure definitions, privacy-threshold review, accountable quality-improvement process, retention decision, and controlled-pilot evidence before wider reporting.", lastValidatedAt: "2026-08-17" },
  { id: "referral_care_coordination", name: "Referral and care coordination", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Verified provider directory", "In-app notifications"], responsibleOwner: owner, knownLimitations: "Verified providers can initiate appointment-bound referrals; patients choose a matching verified provider and explicitly consent; receiving providers can accept or decline. No appointment is auto-booked, no record is transferred, and no external message or automated clinical routing occurs.", safetyRegulatoryGate: "Clinical referral policy, minimum-data review, response ownership, receiving-facility workflow, retention decision, and controlled-pilot evidence before external exchange.", lastValidatedAt: "2026-08-17" },
  { id: "secure_follow_up_messaging", name: "Secure follow-up messaging", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin", "security_auditor"], externalDependencies: ["D1", "In-app notifications", "Emergency boundary"], responsibleOwner: owner, knownLimitations: "Appointment-bound, time-limited in-app follow-up threads are implemented with explicit emergency redirection, provider closure, audit events, and aggregate-only governance. Attachments, external delivery, diagnosis, triage, and clinical automation remain disabled.", safetyRegulatoryGate: "Approved response-time policy, clinical communications policy, escalation ownership, retention decision, and controlled-pilot evidence before expanding beyond in-app follow-up.", lastValidatedAt: "2026-08-17" },
  { id: "virtual_care_foundation", name: "Virtual care operations foundation", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved secure media provider", "Clinical suitability protocol", "Fallback communications channel"], responsibleOwner: owner, knownLimitations: "Patient device/privacy readiness, a time-bounded waiting room, provider arrival and fallback operations, governance metrics, and an eight-scenario synthetic rehearsal are implemented. No video link, media session, external fallback message, or clinical protocol is activated.", safetyRegulatoryGate: "Licensed-facility pilot, secure media vendor approval, clinical suitability and emergency protocols, privacy review, fallback ownership, and separate runtime activation decisions.", lastValidatedAt: "2026-08-17" },
  { id: "medication_reminders", name: "Medication reminder planning", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved notification scheduler", "Clinical safety review"], responsibleOwner: owner, knownLimitations: "Patients can manage acknowledged patient-entered plans and a reversible future-delivery preference. Versioned consent history, synthetic delivery rehearsal, and an activation-readiness evidence dashboard are implemented. Plans remain unverified; policy activation, occurrence creation, and delivery are disabled.", safetyRegulatoryGate: "Hosted scheduler reliability, monitoring, approved delivery provider, pilot decision, and separate policy, occurrence, and delivery activation decisions.", lastValidatedAt: "2026-08-16" },
  { id: "report_reader", name: "Medical Report Reader foundation", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["provider", "platform_admin"], externalDependencies: ["D1", "Protected R2 storage", "Approved extraction vendor", "Clinical review"], responsibleOwner: owner, knownLimitations: "Only bilingual synthetic extraction and verified-provider review are active. Source-reported flags are displayed as provenance, never recalculated or interpreted. Diagnosis, recommendations, dispatch, and patient-record writes remain disabled.", safetyRegulatoryGate: "Secure document activation, vendor and model approval, report-type validation, bilingual clinical evaluation, qualified reviewer policy, and separate activation approval.", lastValidatedAt: "2026-08-16" },
  { id: "prescription_intelligence", name: "Prescription intelligence foundation", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["provider", "platform_admin"], externalDependencies: ["D1", "Protected R2 storage", "Approved OCR vendor", "Clinical review"], responsibleOwner: owner, knownLimitations: "Only a provenance-linked synthetic evaluation and verified-provider review workflow is active. OCR dispatch and every medication, reminder, order, or patient-record write remain disabled.", safetyRegulatoryGate: "Secure document activation, vendor and model approval, bilingual clinical evaluation, qualified human verification policy, and separate record-commit approval.", lastValidatedAt: "2026-08-16" },
  { id: "patient_home", name: "Patient home", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient"], externalDependencies: ["ChatGPT identity", "D1"], responsibleOwner: owner, knownLimitations: "Current platform identity only; independent public authentication is not active.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_discovery", name: "Provider discovery", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Search is limited to verified, published Reyati catalog records.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "care_navigator_rules", name: "Care Navigator safety foundation", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Verified provider catalog", "Clinical content review"], responsibleOwner: owner, knownLimitations: "Emergency-first structured rules only; no diagnosis, probability, treatment, free-text medical narrative, model assistance, or claim that a user is safe. Versioned governance, a bilingual synthetic safety suite, deterministic evaluation, zero-critical-failure thresholds, and independent evidence review are implemented. Routing content remains clinically unapproved and runtime activation is disabled.", safetyRegulatoryGate: "Independent clinical review, external bilingual validation, emergency-path evaluation, accountable clinical ownership, approved change control, and separate activation decision before controlled pilot use.", lastValidatedAt: "2026-08-16" },
  { id: "appointment_booking", name: "Appointment booking", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No external hospital scheduling integration is connected.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "health_records", name: "Health records", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Only finalized Reyati encounter records are exposed.", safetyRegulatoryGate: "Clinical documentation and retention approval before wider rollout.", lastValidatedAt: validated },
  { id: "medical_document_foundation", name: "Medical document vault", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider"], externalDependencies: ["D1", "Protected R2 storage", "Malware scanner", "Retention automation"], responsibleOwner: owner, knownLimitations: "Patient ownership, private R2, bounded upload completion, durable scan handoff, signed callbacks, timeout quarantine recovery, verified deletion, single-use audited delivery, and referenced-object-safe upload cleanup are implemented; provider dispatch, scheduled recovery, retention policy, file acceptance, active scanning, and content delivery remain disabled.", safetyRegulatoryGate: "Retention and legal-hold approval, scanner selection and dispatch, threat modelling, recovery exercises, and security activation review.", lastValidatedAt: validated },
  { id: "family_access", name: "Family access", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Adult delegation is active. Dependants are separate from adult accounts with email-bound additional-guardian nomination, reversible authority records, immutable evidence review, and synthetic age-of-majority transition rehearsal. All dependant care, emergency authority, and automatic transition remain disabled.", safetyRegulatoryGate: "Minor and legal-guardian policy, evidence standards, authority scopes, emergency-access controls, and age-of-majority transition approval.", lastValidatedAt: validated },
  { id: "payment_records", name: "Payment records and support", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Recorded payment ledger"], responsibleOwner: owner, knownLimitations: "Patients can raise an owned-ledger payment issue or refund request. Administrators use maker-checker decisions, append-only recorded adjustments, and reference-only reconciliation. No gateway, money movement, automatic refund, settlement, payout, or card storage is connected.", safetyRegulatoryGate: "Payment provider selection, finance operating model, dual-control roster, reconciliation SOP, and regulatory approval before executing money movement.", lastValidatedAt: "2026-08-17" },
  { id: "in_app_notifications", name: "In-app notifications", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Email and SMS delivery are not enabled.", safetyRegulatoryGate: "Approved templates, consent, and vendor data-processing review.", lastValidatedAt: validated },
  { id: "communication_preferences", name: "Communication preferences", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin"], externalDependencies: ["ChatGPT identity", "D1"], responsibleOwner: owner, knownLimitations: "Language and email opt-in are durable; email verification and delivery remain inactive.", safetyRegulatoryGate: "Verified contact and approved delivery service before outbound activation.", lastValidatedAt: validated },
  { id: "support_cases", name: "Support cases", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "support_agent", "platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No external ticketing integration or automated escalation.", safetyRegulatoryGate: "Incident ownership and escalation rota required for pilot.", lastValidatedAt: validated },
  { id: "provider_schedule", name: "Provider schedule", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Requires active provider and organization membership.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_patients", name: "Provider patient directory", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Minimum identity and appointment context only.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_catalog", name: "Provider services and availability", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["provider", "organization_owner"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Publishing requires verified provider and service-location records.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_insights", name: "Provider appointment insights", status: "read_only", supportedEnvironments: allEnvironments, permittedRoles: ["provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Privacy-thresholded operational aggregates only.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "organization_access", name: "Organization access", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["organization_owner", "organization_admin"], externalDependencies: ["ChatGPT identity", "D1"], responsibleOwner: owner, knownLimitations: "Invitation is bound to the verified account email.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "controlled_pilot_suspension", name: "Organization suspension and rollback", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin"], externalDependencies: ["D1", "Named pilot operations owner"], responsibleOwner: owner, knownLimitations: "Suspension immediately blocks organization publication, new bookings, and provider workspace access while preserving records; existing appointments are not automatically cancelled.", safetyRegulatoryGate: "Approved suspension SOP, named decision owner, patient-contact procedure, and rollback exercise before controlled pilot.", lastValidatedAt: validated },
  { id: "pilot_enrollment_evidence", name: "Pilot consent and agreement evidence", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved legal and clinical wording", "Participant invitation channel"], responsibleOwner: owner, knownLimitations: "Versioned patient-consent and provider-agreement artifacts can be prepared and independently approved; participant acceptance, invitation delivery, and pilot access remain disabled.", safetyRegulatoryGate: "Legal, privacy, clinical, and provider-contract approval plus identity-bound acceptance testing before controlled pilot.", lastValidatedAt: validated },
  { id: "pilot_invitation_safeguards", name: "Pilot invitation and acceptance safeguards", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved enrollment evidence", "Verified delivery channel", "Pilot activation approval"], responsibleOwner: owner, knownLimitations: "Identity-bound, single-use, hash-only invitation policies can be prepared and independently reviewed. No token is generated, no invitation is delivered, no acceptance is recorded, and no pilot access is granted.", safetyRegulatoryGate: "Threat model, verified contact, exact consent-version acceptance test, withdrawal exercise, delivery approval, and go decision before activation.", lastValidatedAt: validated },
  { id: "pilot_participation_withdrawal", name: "Pilot participation and withdrawal governance", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved invitation safeguards", "Access revocation runtime", "Named participant-support owner"], responsibleOwner: owner, knownLimitations: "Versioned participation policies and synthetic withdrawal rehearsals are independently reviewed. No real participant state changes, access revocation, acceptance, or reactivation are executed.", safetyRegulatoryGate: "Approved withdrawal wording, verified revocation path, support runbook, record-treatment review, successful rehearsals, and pilot activation decision.", lastValidatedAt: validated },
  { id: "pilot_launch_authorization", name: "Controlled-pilot launch authorization", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved Go decision", "Current readiness evidence", "Named primary and backup launch owners"], responsibleOwner: owner, knownLimitations: "Versioned launch packages capture immutable readiness snapshots and independently verified synthetic rollback rehearsals. Approval never activates the pilot; activation is revalidated server-side and remains unavailable while any dependency is blocked.", safetyRegulatoryGate: "Zero current readiness blockers, approved Go decision, current independently approved launch package, complete rollback evidence, and activation-window validation.", lastValidatedAt: validated },
  { id: "pilot_command_centre", name: "Pilot command centre and day-zero checklist", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor", "support_agent"], externalDependencies: ["D1", "Approved launch package", "Active launch commander", "Independent stop authority"], responsibleOwner: owner, knownLimitations: "Versioned synthetic day-zero sessions, ten evidence checks, handover, independent completion, and stop authority are implemented. The command runtime cannot launch a pilot, send messages, or grant access.", safetyRegulatoryGate: "Approved package, zero current and captured blockers, every check verified, independent review, and active shift window before controlled-pilot activation.", lastValidatedAt: validated },
  { id: "pilot_learning_governance", name: "Pilot feedback and success metrics", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor", "support_agent"], externalDependencies: ["D1", "Approved pilot measurement protocol", "Participant consent"], responsibleOwner: owner, knownLimitations: "Success metrics are versioned and independently reviewed; feedback intake is restricted to synthetic dry-run evidence. Real participant collection and outcome claims remain disabled.", safetyRegulatoryGate: "Approved metric definitions, privacy notice, participant consent, minimum sample rules, and statistical review before real-pilot reporting.", lastValidatedAt: validated },
  { id: "care_continuity_operations", name: "Care continuity operations", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "support_agent"], externalDependencies: ["D1", "In-app notifications", "Named care continuity owner"], responsibleOwner: owner, knownLimitations: "Affected future appointments are queued durably; rebooking remains a patient choice and outbound email remains gated.", safetyRegulatoryGate: "Approved patient-contact script, escalation ownership, response targets, and continuity rehearsal before controlled pilot.", lastValidatedAt: validated },
  { id: "encounter_notes", name: "Encounter notes", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Finalization is immutable. Later corrections and follow-up recommendations use separately audited linked records; the original note is never overwritten.", safetyRegulatoryGate: "Clinical documentation and amendment policy approval.", lastValidatedAt: "2026-08-17" },
  { id: "partner_workspace", name: "Employer workspace", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "organization_owner", "organization_admin", "finance", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Active employer organization", "Consent-bound eligibility"], responsibleOwner: owner, knownLimitations: "Employer members manage bounded draft programmes, invitation-bound or synthetic eligibility, and an append-only reference ledger. Employers receive aggregate roster information only and cannot see patient identity, appointments, providers, diagnoses, or clinical activity.", safetyRegulatoryGate: "Employment-health privacy separation, benefit governance, partner approval, consent wording, and controlled-pilot evidence.", lastValidatedAt: "2026-08-17" },
  { id: "partner_program", name: "Employer benefit programme", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "organization_owner", "organization_admin", "finance", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved employer organization", "Consent-bound eligibility"], responsibleOwner: owner, knownLimitations: "Draft-only QAR programmes, explicit patient visibility consent, hash-bound invitations, and append-only funding references are implemented. Claims, automatic eligibility, external money movement, invoices, and clinical-data access remain disabled.", safetyRegulatoryGate: "Benefit policy, finance controls, employment privacy review, roster retention, and controlled-pilot approval.", lastValidatedAt: "2026-08-17" },
  { id: "platform_overview", name: "Platform overview", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Operational aggregates only.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_verification", name: "Provider verification", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "verifier"], externalDependencies: ["D1", "Manual source verification"], responsibleOwner: owner, knownLimitations: "Verification remains a manual, auditable decision.", safetyRegulatoryGate: "Approved verification SOP and accountable verifier roster.", lastValidatedAt: validated },
  { id: "finance_ledger", name: "Finance ledger", status: "read_only", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No settlement, reconciliation, refund, or payout controls.", safetyRegulatoryGate: "Finance operating model and payment provider approval.", lastValidatedAt: validated },
  { id: "support_operations", name: "Support operations", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["support_agent", "platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No external ticketing integration.", safetyRegulatoryGate: "Named pilot owner and escalation rota.", lastValidatedAt: validated },
  { id: "review_moderation", name: "Verified patient reviews and moderation", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "moderator", "platform_admin", "security_auditor"], externalDependencies: ["D1", "Completed Reyati appointment"], responsibleOwner: owner, knownLimitations: "Appointment-bound structured reviews, human moderation, provider appeals, immutable revisions, and privacy-thresholded aggregates are implemented. Clinical claims, patient identity disclosure, below-threshold aggregates, automated moderation, and external publication remain disabled.", safetyRegulatoryGate: "Approved review and appeals policy, accountable moderator roster, clinical-claim rules, privacy threshold, and controlled-pilot evidence.", lastValidatedAt: "2026-08-17" },
  { id: "audit_ledger", name: "Audit ledger", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "auditor"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Application audit events are append-only; external SIEM export is not connected.", safetyRegulatoryGate: "Retention and incident-access policy approval.", lastValidatedAt: validated },
  { id: "platform_identity", name: "Secure account", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin"], externalDependencies: ["ChatGPT identity"], responsibleOwner: owner, knownLimitations: "Suitable for the hosted prototype; independent consumer sign-up and MFA are not active.", safetyRegulatoryGate: "Authentication architecture decision and independent security review before a public pilot.", lastValidatedAt: validated },
  { id: "independent_authentication", name: "Independent authentication", status: "foundation", supportedEnvironments: ["local"], permittedRoles: [], externalDependencies: ["Identity provider decision"], responsibleOwner: owner, knownLimitations: "Schema only; no sign-up, password, passkey, OTP, recovery, or session runtime is enabled.", safetyRegulatoryGate: "Architecture decision, threat model, security review, and recovery policy.", lastValidatedAt: validated },
  { id: "outbound_communications", name: "Outbound communications", status: "foundation", supportedEnvironments: ["local"], permittedRoles: [], externalDependencies: ["Email provider", "Scheduled trigger", "Approved templates"], responsibleOwner: owner, knownLimitations: "Resend adapter, leased retry processor, signed invitations, verified webhooks, and operations reporting are implemented; delivery and scheduling remain inactive.", safetyRegulatoryGate: "Domain, secrets, consent, templates, deliverability, scheduled-trigger, and incident activation review.", lastValidatedAt: validated },
  { id: "operational_observability", name: "Operational observability", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["Monitoring vendor", "Alert transport", "Named incident rota"], responsibleOwner: owner, knownLimitations: "Privacy-safe application signals, durable write limits, ownership controls, incident response, and independently reviewed recovery-rehearsal evidence are implemented; external error tracking, performance monitoring, automated alerting, and retention automation remain inactive.", safetyRegulatoryGate: "Telemetry classification, vendor review, named owners, alert thresholds, and successful hosted restore evidence.", lastValidatedAt: validated },
  { id: "arabic_localization", name: "Arabic and RTL experience", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin", "support_agent"], externalDependencies: ["Native Arabic linguistic review", "Arabic assistive-technology QA"], responsibleOwner: owner, knownLimitations: "Critical journeys use persisted Arabic, RTL layout, Qatar-localized dates and numbers, localized lifecycle terms, and bilingual sensitive confirmations; native clinical, legal, device, and screen-reader review remains outstanding.", safetyRegulatoryGate: "Native Arabic terminology review and representative accessibility validation before controlled pilot.", lastValidatedAt: validated },
] as const satisfies readonly CapabilityDefinition[];

export function getCapability(id: string) {
  return capabilityRegistry.find((capability) => capability.id === id);
}

export function publicCapabilityRegistry() {
  return capabilityRegistry.map(({ externalDependencies, ...capability }) => ({
    ...capability,
    dependencyCount: externalDependencies.length,
  }));
}
