export type CapabilityStatus = "live" | "read_only" | "role_gated" | "inactive" | "foundation";
export type ReyatiEnvironment = "production" | "investor_demo" | "local";

export type CapabilityDefinition = {
  id: string;
  name: string;
  status: CapabilityStatus;
  supportedEnvironments: readonly ReyatiEnvironment[];
  permittedRoles: readonly string[];
  externalDependencies: readonly string[];
  responsibleOwner: string;
  knownLimitations: string;
  safetyRegulatoryGate: string | null;
  lastValidatedAt: string;
};

const validated = "2026-08-14";
const owner = "TBD — Product and Engineering";
const allEnvironments = ["production", "investor_demo", "local"] as const;

export const capabilityRegistry = [
  { id: "patient_home", name: "Patient home", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient"], externalDependencies: ["ChatGPT identity", "D1"], responsibleOwner: owner, knownLimitations: "Current platform identity only; independent public authentication is not active.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_discovery", name: "Provider discovery", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Search is limited to verified, published Reyati catalog records.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "appointment_booking", name: "Appointment booking", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No external hospital scheduling integration is connected.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "health_records", name: "Health records", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Only finalized Reyati encounter records are exposed.", safetyRegulatoryGate: "Clinical documentation and retention approval before wider rollout.", lastValidatedAt: validated },
  { id: "medical_document_foundation", name: "Medical document vault", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider"], externalDependencies: ["D1", "Protected R2 storage", "Malware scanner", "Retention automation"], responsibleOwner: owner, knownLimitations: "Patient ownership, private R2, bounded upload completion, durable scan handoff, signed callbacks, timeout quarantine recovery, verified deletion, single-use audited delivery, and referenced-object-safe upload cleanup are implemented; provider dispatch, scheduled recovery, retention policy, file acceptance, active scanning, and content delivery remain disabled.", safetyRegulatoryGate: "Retention and legal-hold approval, scanner selection and dispatch, threat modelling, recovery exercises, and security activation review.", lastValidatedAt: validated },
  { id: "family_access", name: "Family access", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Explicit scoped delegation only; guardian workflows are not active.", safetyRegulatoryGate: "Minor and legal-guardian policy approval.", lastValidatedAt: validated },
  { id: "payment_records", name: "Payment records", status: "read_only", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No checkout, refund, settlement, or money movement.", safetyRegulatoryGate: "Payment provider, finance controls, and regulatory approval.", lastValidatedAt: validated },
  { id: "in_app_notifications", name: "In-app notifications", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Email and SMS delivery are not enabled.", safetyRegulatoryGate: "Approved templates, consent, and vendor data-processing review.", lastValidatedAt: validated },
  { id: "communication_preferences", name: "Communication preferences", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin"], externalDependencies: ["ChatGPT identity", "D1"], responsibleOwner: owner, knownLimitations: "Language and email opt-in are durable; email verification and delivery remain inactive.", safetyRegulatoryGate: "Verified contact and approved delivery service before outbound activation.", lastValidatedAt: validated },
  { id: "support_cases", name: "Support cases", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "support_agent", "platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No external ticketing integration or automated escalation.", safetyRegulatoryGate: "Incident ownership and escalation rota required for pilot.", lastValidatedAt: validated },
  { id: "provider_schedule", name: "Provider schedule", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Requires active provider and organization membership.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_patients", name: "Provider patient directory", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Minimum identity and appointment context only.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_catalog", name: "Provider services and availability", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["provider", "organization_owner"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Publishing requires verified provider and service-location records.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_insights", name: "Provider appointment insights", status: "read_only", supportedEnvironments: allEnvironments, permittedRoles: ["provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Privacy-thresholded operational aggregates only.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "organization_access", name: "Organization access", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["organization_owner", "organization_admin"], externalDependencies: ["ChatGPT identity", "D1"], responsibleOwner: owner, knownLimitations: "Invitation is bound to the verified account email.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "controlled_pilot_suspension", name: "Organization suspension and rollback", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin"], externalDependencies: ["D1", "Named pilot operations owner"], responsibleOwner: owner, knownLimitations: "Suspension immediately blocks organization publication, new bookings, and provider workspace access while preserving records; existing appointments are not automatically cancelled.", safetyRegulatoryGate: "Approved suspension SOP, named decision owner, patient-contact procedure, and rollback exercise before controlled pilot.", lastValidatedAt: validated },
  { id: "pilot_enrollment_evidence", name: "Pilot consent and agreement evidence", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved legal and clinical wording", "Participant invitation channel"], responsibleOwner: owner, knownLimitations: "Versioned patient-consent and provider-agreement artifacts can be prepared and independently approved; participant acceptance, invitation delivery, and pilot access remain disabled.", safetyRegulatoryGate: "Legal, privacy, clinical, and provider-contract approval plus identity-bound acceptance testing before controlled pilot.", lastValidatedAt: validated },
  { id: "pilot_invitation_safeguards", name: "Pilot invitation and acceptance safeguards", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved enrollment evidence", "Verified delivery channel", "Pilot activation approval"], responsibleOwner: owner, knownLimitations: "Identity-bound, single-use, hash-only invitation policies can be prepared and independently reviewed. No token is generated, no invitation is delivered, no acceptance is recorded, and no pilot access is granted.", safetyRegulatoryGate: "Threat model, verified contact, exact consent-version acceptance test, withdrawal exercise, delivery approval, and go decision before activation.", lastValidatedAt: validated },
  { id: "pilot_participation_withdrawal", name: "Pilot participation and withdrawal governance", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved invitation safeguards", "Access revocation runtime", "Named participant-support owner"], responsibleOwner: owner, knownLimitations: "Versioned participation policies and synthetic withdrawal rehearsals are independently reviewed. No real participant state changes, access revocation, acceptance, or reactivation are executed.", safetyRegulatoryGate: "Approved withdrawal wording, verified revocation path, support runbook, record-treatment review, successful rehearsals, and pilot activation decision.", lastValidatedAt: validated },
  { id: "pilot_launch_authorization", name: "Controlled-pilot launch authorization", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["D1", "Approved Go decision", "Current readiness evidence", "Named primary and backup launch owners"], responsibleOwner: owner, knownLimitations: "Versioned launch packages capture immutable readiness snapshots and independently verified synthetic rollback rehearsals. Approval never activates the pilot; activation is revalidated server-side and remains unavailable while any dependency is blocked.", safetyRegulatoryGate: "Zero current readiness blockers, approved Go decision, current independently approved launch package, complete rollback evidence, and activation-window validation.", lastValidatedAt: validated },
  { id: "pilot_learning_governance", name: "Pilot feedback and success metrics", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor", "support_agent"], externalDependencies: ["D1", "Approved pilot measurement protocol", "Participant consent"], responsibleOwner: owner, knownLimitations: "Success metrics are versioned and independently reviewed; feedback intake is restricted to synthetic dry-run evidence. Real participant collection and outcome claims remain disabled.", safetyRegulatoryGate: "Approved metric definitions, privacy notice, participant consent, minimum sample rules, and statistical review before real-pilot reporting.", lastValidatedAt: validated },
  { id: "care_continuity_operations", name: "Care continuity operations", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "support_agent"], externalDependencies: ["D1", "In-app notifications", "Named care continuity owner"], responsibleOwner: owner, knownLimitations: "Affected future appointments are queued durably; rebooking remains a patient choice and outbound email remains gated.", safetyRegulatoryGate: "Approved patient-contact script, escalation ownership, response targets, and continuity rehearsal before controlled pilot.", lastValidatedAt: validated },
  { id: "encounter_notes", name: "Encounter notes", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["provider"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Finalization is immutable; amendments are not yet implemented.", safetyRegulatoryGate: "Clinical documentation and amendment policy approval.", lastValidatedAt: validated },
  { id: "partner_workspace", name: "Employer workspace", status: "inactive", supportedEnvironments: allEnvironments, permittedRoles: ["partner_admin"], externalDependencies: ["Employer registry", "Eligibility roster", "Funding ledger"], responsibleOwner: owner, knownLimitations: "No employer, employee, benefit, funding, or invoice source is connected.", safetyRegulatoryGate: "Employment-health privacy separation and benefit governance approval.", lastValidatedAt: validated },
  { id: "partner_program", name: "Programme setup", status: "inactive", supportedEnvironments: allEnvironments, permittedRoles: ["partner_admin"], externalDependencies: ["Employer registry", "Eligibility roster", "Funding ledger"], responsibleOwner: owner, knownLimitations: "Programme creation and publication are deliberately unavailable.", safetyRegulatoryGate: "Benefit approval evidence and immutable funding controls.", lastValidatedAt: validated },
  { id: "platform_overview", name: "Platform overview", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Operational aggregates only.", safetyRegulatoryGate: null, lastValidatedAt: validated },
  { id: "provider_verification", name: "Provider verification", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "verifier"], externalDependencies: ["D1", "Manual source verification"], responsibleOwner: owner, knownLimitations: "Verification remains a manual, auditable decision.", safetyRegulatoryGate: "Approved verification SOP and accountable verifier roster.", lastValidatedAt: validated },
  { id: "finance_ledger", name: "Finance ledger", status: "read_only", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No settlement, reconciliation, refund, or payout controls.", safetyRegulatoryGate: "Finance operating model and payment provider approval.", lastValidatedAt: validated },
  { id: "support_operations", name: "Support operations", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["support_agent", "platform_admin"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "No external ticketing integration.", safetyRegulatoryGate: "Named pilot owner and escalation rota.", lastValidatedAt: validated },
  { id: "review_moderation", name: "Review moderation", status: "inactive", supportedEnvironments: allEnvironments, permittedRoles: ["moderator", "platform_admin"], externalDependencies: ["Review source"], responsibleOwner: owner, knownLimitations: "No patient review source is connected.", safetyRegulatoryGate: "Moderation policy, appeals, and accountable reviewer roster.", lastValidatedAt: validated },
  { id: "audit_ledger", name: "Audit ledger", status: "role_gated", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "auditor"], externalDependencies: ["D1"], responsibleOwner: owner, knownLimitations: "Application audit events are append-only; external SIEM export is not connected.", safetyRegulatoryGate: "Retention and incident-access policy approval.", lastValidatedAt: validated },
  { id: "platform_identity", name: "Secure account", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin"], externalDependencies: ["ChatGPT identity"], responsibleOwner: owner, knownLimitations: "Suitable for the hosted prototype; independent consumer sign-up and MFA are not active.", safetyRegulatoryGate: "Authentication architecture decision and independent security review before a public pilot.", lastValidatedAt: validated },
  { id: "independent_authentication", name: "Independent authentication", status: "foundation", supportedEnvironments: ["local"], permittedRoles: [], externalDependencies: ["Identity provider decision"], responsibleOwner: owner, knownLimitations: "Schema only; no sign-up, password, passkey, OTP, recovery, or session runtime is enabled.", safetyRegulatoryGate: "Architecture decision, threat model, security review, and recovery policy.", lastValidatedAt: validated },
  { id: "outbound_communications", name: "Outbound communications", status: "foundation", supportedEnvironments: ["local"], permittedRoles: [], externalDependencies: ["Email provider", "Scheduled trigger", "Approved templates"], responsibleOwner: owner, knownLimitations: "Resend adapter, leased retry processor, signed invitations, verified webhooks, and operations reporting are implemented; delivery and scheduling remain inactive.", safetyRegulatoryGate: "Domain, secrets, consent, templates, deliverability, scheduled-trigger, and incident activation review.", lastValidatedAt: validated },
  { id: "operational_observability", name: "Operational observability", status: "foundation", supportedEnvironments: allEnvironments, permittedRoles: ["platform_admin", "security_auditor"], externalDependencies: ["Monitoring vendor", "Alert transport", "Named incident rota"], responsibleOwner: owner, knownLimitations: "Privacy-safe application signals, durable write limits, ownership controls, incident response, and independently reviewed recovery-rehearsal evidence are implemented; external error tracking, performance monitoring, automated alerting, and retention automation remain inactive.", safetyRegulatoryGate: "Telemetry classification, vendor review, named owners, alert thresholds, and successful hosted restore evidence.", lastValidatedAt: validated },
  { id: "arabic_localization", name: "Arabic and RTL experience", status: "live", supportedEnvironments: allEnvironments, permittedRoles: ["patient", "provider", "platform_admin", "support_agent"], externalDependencies: ["Native Arabic linguistic review", "Arabic assistive-technology QA"], responsibleOwner: owner, knownLimitations: "Critical journeys use persisted Arabic, RTL layout, Qatar-localized dates and numbers, localized lifecycle terms, and bilingual sensitive confirmations; native clinical, legal, device, and screen-reader review remains outstanding.", safetyRegulatoryGate: "Native Arabic terminology review and representative accessibility validation before controlled pilot.", lastValidatedAt: validated },
] as const satisfies readonly CapabilityDefinition[];

export function getCapability(id: string) {
  return capabilityRegistry.find((capability) => capability.id === id);
}

export function publicCapabilityRegistry() {
  return capabilityRegistry.map(({ externalDependencies, ...capability }) => ({
    ...capability,
    dependencyCount: externalDependencies.length,
  }));
}
