import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, careNavigatorEvaluationRuns, careNavigatorEvaluationScenarios, careNavigatorRuleSetEvents, careNavigatorRuleSets, users } from "@/db/schema";
import { requirePlatformRole } from "@/lib/authorization";
import { evaluateCareNavigatorRules, NAVIGATOR_RULESET_VERSION, RED_FLAG_KEYS } from "@/lib/care-navigator";

export const NAVIGATOR_EVALUATION_SUITE_VERSION = "safety-suite-2026-08-16";
export class NavigatorGovernanceValidationError extends Error { constructor(message: string) { super(message); this.name = "NavigatorGovernanceValidationError"; } }
export class NavigatorGovernanceConflictError extends Error { constructor() { super("This governance record changed. Refresh and try again."); this.name = "NavigatorGovernanceConflictError"; } }

function text(value: unknown, name: string, min: number, max: number) { if (typeof value !== "string" || value.trim().length < min || value.trim().length > max) throw new NavigatorGovernanceValidationError(`${name} is invalid`); return value.trim(); }
function stableReference(value: unknown, name: string, max = 180) { const result = text(value, name, 3, max); if (!/^[A-Za-z0-9][A-Za-z0-9 _./:-]*$/.test(result)) throw new NavigatorGovernanceValidationError(`${name} must use stable reference characters`); return result; }
function expectedVersion(value: unknown) { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 1) throw new NavigatorGovernanceValidationError("version is invalid"); return parsed; }
const noFlags = Object.fromEntries(RED_FLAG_KEYS.map((key) => [key, false]));
const baseScenarios = [
  ...RED_FLAG_KEYS.map((key) => ({ key: `emergency-${key}`, riskClass: "emergency", input: { concernCategory: "general", durationBand: "today", ageGroup: "adult", careModePreference: "any", redFlags: { ...noFlags, [key]: true } }, outcome: "emergency", specialty: null })),
  { key: "route-general", riskClass: "routing", input: { concernCategory: "general", durationBand: "days", ageGroup: "adult", careModePreference: "any", redFlags: noFlags }, outcome: "routed", specialty: "General Medicine" },
  { key: "route-skin", riskClass: "routing", input: { concernCategory: "skin", durationBand: "weeks", ageGroup: "adult", careModePreference: "in_person", redFlags: noFlags }, outcome: "routed", specialty: "Dermatology" },
  { key: "route-child", riskClass: "routing", input: { concernCategory: "general", durationBand: "days", ageGroup: "child", careModePreference: "any", redFlags: noFlags }, outcome: "routed", specialty: "Pediatrics" },
  { key: "route-mental", riskClass: "routing", input: { concernCategory: "mental_wellbeing", durationBand: "months", ageGroup: "adult", careModePreference: "video", redFlags: noFlags }, outcome: "routed", specialty: "Mental Health" },
  { key: "route-eye-video", riskClass: "routing", input: { concernCategory: "eye", durationBand: "today", ageGroup: "older_adult", careModePreference: "video", redFlags: noFlags }, outcome: "routed", specialty: "Ophthalmology" },
  { key: "uncertainty-other", riskClass: "uncertainty", input: { concernCategory: "other", durationBand: "unsure", ageGroup: "prefer_not_to_say", careModePreference: "any", redFlags: noFlags }, outcome: "insufficient_information", specialty: null },
] as const;

export async function getNavigatorGovernanceCentre(userId: string) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const db = await getDb();
  const [ruleSets, scenarios, runs, events] = await Promise.all([
    db.select({ id: careNavigatorRuleSets.id, rulesetVersion: careNavigatorRuleSets.rulesetVersion, label: careNavigatorRuleSets.label, sourceReference: careNavigatorRuleSets.sourceReference, emergencyRuleCount: careNavigatorRuleSets.emergencyRuleCount, routeRuleCount: careNavigatorRuleSets.routeRuleCount, status: careNavigatorRuleSets.status, clinicalApprovalStatus: careNavigatorRuleSets.clinicalApprovalStatus, preparedByUserId: careNavigatorRuleSets.preparedByUserId, preparedByName: users.displayName, reviewerUserId: careNavigatorRuleSets.reviewerUserId, reviewedAt: careNavigatorRuleSets.reviewedAt, reviewNote: careNavigatorRuleSets.reviewNote, version: careNavigatorRuleSets.version, createdAt: careNavigatorRuleSets.createdAt }).from(careNavigatorRuleSets).innerJoin(users, eq(users.id, careNavigatorRuleSets.preparedByUserId)).orderBy(desc(careNavigatorRuleSets.createdAt)),
    db.select().from(careNavigatorEvaluationScenarios).orderBy(careNavigatorEvaluationScenarios.scenarioKey),
    db.select().from(careNavigatorEvaluationRuns).orderBy(desc(careNavigatorEvaluationRuns.executedAt)).limit(200),
    db.select({ id: careNavigatorRuleSetEvents.id, ruleSetId: careNavigatorRuleSetEvents.ruleSetId, action: careNavigatorRuleSetEvents.action, previousStatus: careNavigatorRuleSetEvents.previousStatus, nextStatus: careNavigatorRuleSetEvents.nextStatus, note: careNavigatorRuleSetEvents.note, actorName: users.displayName, createdAt: careNavigatorRuleSetEvents.createdAt }).from(careNavigatorRuleSetEvents).innerJoin(users, eq(users.id, careNavigatorRuleSetEvents.actorUserId)).orderBy(desc(careNavigatorRuleSetEvents.createdAt)).limit(300),
  ]);
  return { role: access.role, currentUserId: userId, runtimeActivationEnabled: false, clinicalApprovalEnabled: false, suiteVersion: NAVIGATOR_EVALUATION_SUITE_VERSION, thresholds: { minimumScenarios: baseScenarios.length * 2, emergencyRecallBps: 10000, routeAccuracyBps: 10000, bilingualParityBps: 10000, criticalFailures: 0 }, ruleSets: ruleSets.map((ruleSet) => ({ ...ruleSet, scenarios: scenarios.filter((item) => item.ruleSetId === ruleSet.id).map((item) => ({ ...item, input: JSON.parse(item.inputJson) })), runs: runs.filter((item) => item.ruleSetId === ruleSet.id).map((item) => ({ ...item, failures: JSON.parse(item.failuresJson) })), events: events.filter((item) => item.ruleSetId === ruleSet.id) })) };
}

export async function createNavigatorRuleSet(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const rulesetVersion = stableReference(body.rulesetVersion, "rulesetVersion", 60); if (rulesetVersion !== NAVIGATOR_RULESET_VERSION) throw new NavigatorGovernanceValidationError("Only the deployed foundation ruleset can be registered in this evaluation centre"); const label = text(body.label, "label", 8, 120); const sourceReference = stableReference(body.sourceReference, "sourceReference"); const db = await getDb(); const duplicate = (await db.select({ id: careNavigatorRuleSets.id }).from(careNavigatorRuleSets).where(eq(careNavigatorRuleSets.rulesetVersion, rulesetVersion)).limit(1))[0]; if (duplicate) throw new NavigatorGovernanceValidationError("This ruleset version is already registered"); const now = new Date(); const id = crypto.randomUUID();
  await db.batch([db.insert(careNavigatorRuleSets).values({ id, rulesetVersion, label, sourceReference, emergencyRuleCount: RED_FLAG_KEYS.length, routeRuleCount: 10, status: "draft", preparedByUserId: userId, clinicalApprovalStatus: "not_reviewed", version: 1, createdAt: now, updatedAt: now }), db.insert(careNavigatorRuleSetEvents).values({ id: crypto.randomUUID(), ruleSetId: id, actorUserId: userId, action: "create", previousStatus: null, nextStatus: "draft", note: "Deployed foundation ruleset registered for synthetic evaluation; no clinical approval claimed.", createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "navigator_governance.ruleset_created", resourceType: "care_navigator_rule_set", resourceId: id, outcome: "success", metadataJson: JSON.stringify({ rulesetVersion, clinicalApprovalStatus: "not_reviewed", runtimeActivationEnabled: false }), createdAt: now })]); return { id, status: "draft", version: 1 };
}

export async function seedNavigatorEvaluationSuite(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const ruleSetId = text(body.ruleSetId, "ruleSetId", 1, 128); const db = await getDb(); const ruleSet = (await db.select().from(careNavigatorRuleSets).where(eq(careNavigatorRuleSets.id, ruleSetId)).limit(1))[0]; if (!ruleSet || !["draft", "rejected"].includes(ruleSet.status)) throw new NavigatorGovernanceValidationError("A draft or rejected ruleset is required"); const existing = await db.select({ id: careNavigatorEvaluationScenarios.id }).from(careNavigatorEvaluationScenarios).where(eq(careNavigatorEvaluationScenarios.ruleSetId, ruleSetId)).limit(1); if (existing[0]) throw new NavigatorGovernanceValidationError("The standard evaluation suite is already present"); const now = new Date(); const values = baseScenarios.flatMap((scenario) => (["en", "ar"] as const).map((locale) => ({ id: crypto.randomUUID(), ruleSetId, scenarioKey: `${scenario.key}.${locale}`, locale, riskClass: scenario.riskClass, inputJson: JSON.stringify(scenario.input), expectedOutcome: scenario.outcome, expectedSpecialty: scenario.specialty, sourceReference: `${NAVIGATOR_EVALUATION_SUITE_VERSION}/${scenario.key}`, dataMode: "synthetic_only", createdByUserId: userId, createdAt: now })));
  await db.batch([db.insert(careNavigatorEvaluationScenarios).values(values.slice(0, 6)), db.insert(careNavigatorEvaluationScenarios).values(values.slice(6, 12)), db.insert(careNavigatorEvaluationScenarios).values(values.slice(12, 18)), db.insert(careNavigatorEvaluationScenarios).values(values.slice(18, 24)), db.insert(careNavigatorRuleSetEvents).values({ id: crypto.randomUUID(), ruleSetId, actorUserId: userId, action: "seed_suite", previousStatus: ruleSet.status, nextStatus: ruleSet.status, note: `${baseScenarios.length * 2} bilingual synthetic scenarios seeded from the standard safety suite.`, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "navigator_governance.suite_seeded", resourceType: "care_navigator_rule_set", resourceId: ruleSetId, outcome: "success", metadataJson: JSON.stringify({ suiteVersion: NAVIGATOR_EVALUATION_SUITE_VERSION, scenarioCount: baseScenarios.length * 2, dataMode: "synthetic_only" }), createdAt: now })]); return { ruleSetId, scenarioCount: baseScenarios.length * 2, dataMode: "synthetic_only" };
}

export async function runNavigatorEvaluation(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const ruleSetId = text(body.ruleSetId, "ruleSetId", 1, 128); const db = await getDb(); const ruleSet = (await db.select().from(careNavigatorRuleSets).where(eq(careNavigatorRuleSets.id, ruleSetId)).limit(1))[0]; if (!ruleSet || !["draft", "rejected"].includes(ruleSet.status)) throw new NavigatorGovernanceValidationError("A draft or rejected ruleset is required"); const scenarios = await db.select().from(careNavigatorEvaluationScenarios).where(eq(careNavigatorEvaluationScenarios.ruleSetId, ruleSetId)); if (scenarios.length < baseScenarios.length * 2) throw new NavigatorGovernanceValidationError("The complete standard bilingual suite is required");
  const results = scenarios.map((scenario) => { const actual = evaluateCareNavigatorRules(JSON.parse(scenario.inputJson) as Record<string, unknown>); const pass = actual.outcome === scenario.expectedOutcome && actual.specialty === scenario.expectedSpecialty && (actual.outcome !== "emergency" || (actual.specialty === null && actual.recommendedCareMode === null)); return { scenarioKey: scenario.scenarioKey, baseKey: scenario.scenarioKey.replace(/\.(en|ar)$/, ""), locale: scenario.locale, riskClass: scenario.riskClass, pass, expectedOutcome: scenario.expectedOutcome, actualOutcome: actual.outcome, expectedSpecialty: scenario.expectedSpecialty, actualSpecialty: actual.specialty }; });
  const emergency = results.filter((item) => item.riskClass === "emergency"); const routed = results.filter((item) => item.riskClass !== "emergency"); const emergencyRecallBps = Math.round(10000 * emergency.filter((item) => item.actualOutcome === "emergency").length / emergency.length); const routeAccuracyBps = Math.round(10000 * routed.filter((item) => item.pass).length / routed.length); const parityPairs = [...new Set(results.map((item) => item.baseKey))].map((baseKey) => results.filter((item) => item.baseKey === baseKey)); const bilingualParityBps = Math.round(10000 * parityPairs.filter((pair) => pair.length === 2 && pair[0].actualOutcome === pair[1].actualOutcome && pair[0].actualSpecialty === pair[1].actualSpecialty).length / parityPairs.length); const criticalFailures = emergency.filter((item) => !item.pass).length; const failures = results.filter((item) => !item.pass).map(({ scenarioKey, expectedOutcome, actualOutcome, expectedSpecialty, actualSpecialty }) => ({ scenarioKey, expectedOutcome, actualOutcome, expectedSpecialty, actualSpecialty })); const passedScenarios = results.length - failures.length; const result = failures.length === 0 && criticalFailures === 0 && emergencyRecallBps === 10000 && routeAccuracyBps === 10000 && bilingualParityBps === 10000 ? "pass" : "fail"; const now = new Date(); const id = crypto.randomUUID();
  await db.batch([db.insert(careNavigatorEvaluationRuns).values({ id, ruleSetId, suiteVersion: NAVIGATOR_EVALUATION_SUITE_VERSION, totalScenarios: results.length, passedScenarios, failedScenarios: failures.length, criticalFailures, emergencyRecallBps, routeAccuracyBps, bilingualParityBps, result, failuresJson: JSON.stringify(failures), dataMode: "synthetic_only", executedByUserId: userId, executedAt: now }), db.insert(careNavigatorRuleSetEvents).values({ id: crypto.randomUUID(), ruleSetId, actorUserId: userId, action: "evaluate", previousStatus: ruleSet.status, nextStatus: ruleSet.status, note: `Synthetic evaluation ${result}: ${passedScenarios}/${results.length} scenarios passed; ${criticalFailures} critical failures.`, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "navigator_governance.evaluation_run", resourceType: "care_navigator_evaluation_run", resourceId: id, outcome: result === "pass" ? "success" : "blocked", metadataJson: JSON.stringify({ ruleSetId, suiteVersion: NAVIGATOR_EVALUATION_SUITE_VERSION, totalScenarios: results.length, passedScenarios, criticalFailures, emergencyRecallBps, routeAccuracyBps, bilingualParityBps, dataMode: "synthetic_only" }), createdAt: now })]); return { id, ruleSetId, result, totalScenarios: results.length, passedScenarios, criticalFailures, emergencyRecallBps, routeAccuracyBps, bilingualParityBps, runtimeActivationEnabled: false, clinicallyApproved: false };
}

export async function transitionNavigatorRuleSet(userId: string, body: Record<string, unknown>) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const ruleSetId = text(body.ruleSetId, "ruleSetId", 1, 128); const action = text(body.action, "action", 3, 20); const note = text(body.note, "note", 20, 1200); const version = expectedVersion(body.version); const db = await getDb(); const current = (await db.select().from(careNavigatorRuleSets).where(eq(careNavigatorRuleSets.id, ruleSetId)).limit(1))[0]; if (!current) throw new NavigatorGovernanceValidationError("Ruleset was not found"); const latestRun = (await db.select().from(careNavigatorEvaluationRuns).where(eq(careNavigatorEvaluationRuns.ruleSetId, ruleSetId)).orderBy(desc(careNavigatorEvaluationRuns.executedAt)).limit(1))[0]; let nextStatus = current.status; let reviewerUserId = current.reviewerUserId; let reviewedAt = current.reviewedAt; let reviewNote = current.reviewNote;
  if (action === "submit" && access.role === "platform_admin" && ["draft", "rejected"].includes(current.status)) { if (!latestRun || latestRun.result !== "pass" || latestRun.criticalFailures !== 0 || latestRun.emergencyRecallBps !== 10000 || latestRun.routeAccuracyBps !== 10000 || latestRun.bilingualParityBps !== 10000) throw new NavigatorGovernanceValidationError("A current passing standard evaluation with zero critical failures is required"); nextStatus = "pending_review"; reviewerUserId = null; reviewedAt = null; reviewNote = null; }
  else if (action === "approve" && access.role === "security_auditor" && current.status === "pending_review") { if (current.preparedByUserId === userId) throw new NavigatorGovernanceValidationError("Independent governance review is required"); nextStatus = "governance_approved"; reviewerUserId = userId; reviewedAt = new Date(); reviewNote = note; }
  else if (action === "reject" && access.role === "security_auditor" && current.status === "pending_review") { if (current.preparedByUserId === userId) throw new NavigatorGovernanceValidationError("Independent governance review is required"); nextStatus = "rejected"; reviewerUserId = userId; reviewedAt = new Date(); reviewNote = note; }
  else throw new NavigatorGovernanceValidationError("Ruleset transition is invalid"); const now = new Date(); const changed = await db.update(careNavigatorRuleSets).set({ status: nextStatus, reviewerUserId, reviewedAt, reviewNote, clinicalApprovalStatus: "not_reviewed", version: current.version + 1, updatedAt: now }).where(and(eq(careNavigatorRuleSets.id, ruleSetId), eq(careNavigatorRuleSets.version, version), eq(careNavigatorRuleSets.status, current.status))).returning({ version: careNavigatorRuleSets.version }); if (!changed[0]) throw new NavigatorGovernanceConflictError(); await db.batch([db.insert(careNavigatorRuleSetEvents).values({ id: crypto.randomUUID(), ruleSetId, actorUserId: userId, action, previousStatus: current.status, nextStatus, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: `navigator_governance.ruleset_${action}`, resourceType: "care_navigator_rule_set", resourceId: ruleSetId, outcome: "success", metadataJson: JSON.stringify({ previousStatus: current.status, nextStatus, clinicalApprovalStatus: "not_reviewed", runtimeActivationEnabled: false }), createdAt: now })]); return { ruleSetId, status: nextStatus, version: changed[0].version, governanceApproved: nextStatus === "governance_approved", clinicallyApproved: false, runtimeActivationEnabled: false };
}
