import { and, count, desc, eq, inArray, isNotNull, lt, ne } from "drizzle-orm";
import { getDb } from "@/db";
import { appointments, auditEvents, careReferralEvents, careReferralRehearsals, careReferrals, notifications, patientProfiles, providerProfiles, users } from "@/db/schema";
import { requireActiveProvider, requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";
import { notificationRecord } from "@/lib/notification-center";

export const REFERRAL_CONSENT_VERSION = "referral-choice-v1", REFERRAL_REHEARSAL_VERSION = "referral-coordination-v1";
export class CareReferralValidationError extends Error { constructor(message: string) { super(message); this.name = "CareReferralValidationError"; } }
export class CareReferralConflictError extends Error { constructor() { super("This referral changed. Refresh and try again."); this.name = "CareReferralConflictError"; } }
const runtime = () => ({ externalDelivery: foundationFlags.referralExternalDelivery, automatedRouting: foundationFlags.referralAutomatedRouting, clinicalRecordTransfer: foundationFlags.referralClinicalRecordTransfer, automaticBooking: false });
function id(value: unknown, name: string) { if (typeof value !== "string" || value.length < 1 || value.length > 128) throw new CareReferralValidationError(`${name} is invalid`); return value; }
function text(value: unknown, name: string, min: number, max: number) { if (typeof value !== "string") throw new CareReferralValidationError(`${name} is required`); const clean = value.trim(); if (clean.length < min || clean.length > max) throw new CareReferralValidationError(`${name} must contain ${min} to ${max} characters`); return clean; }
function version(value: unknown) { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 1) throw new CareReferralValidationError("version is invalid"); return parsed; }
async function expireReferrals() { const db = await getDb(), now = new Date(); await db.update(careReferrals).set({ status: "expired", updatedAt: now }).where(and(inArray(careReferrals.status, ["initiated", "provider_selected", "declined"]), lt(careReferrals.expiresAt, now))); }
async function patientOwned(userId: string, referralId: string) { const db = await getDb(); const row = (await db.select({ referral: careReferrals }).from(careReferrals).innerJoin(patientProfiles, eq(patientProfiles.id, careReferrals.patientId)).where(and(eq(careReferrals.id, referralId), eq(patientProfiles.userId, userId))).limit(1))[0]; if (!row) throw new CareReferralValidationError("Referral was not found"); return row.referral; }

export async function getPatientReferrals(userId: string) {
  await expireReferrals(); const db = await getDb(); const rows = await db.select({ id: careReferrals.id, sourceAppointmentId: careReferrals.sourceAppointmentId, requestedSpecialty: careReferrals.requestedSpecialty, reasonSummary: careReferrals.reasonSummary, status: careReferrals.status, receivingProviderId: careReferrals.receivingProviderId, patientConsentedAt: careReferrals.patientConsentedAt, expiresAt: careReferrals.expiresAt, version: careReferrals.version, createdAt: careReferrals.createdAt, referringProviderName: users.displayName }).from(careReferrals).innerJoin(patientProfiles, eq(patientProfiles.id, careReferrals.patientId)).innerJoin(providerProfiles, eq(providerProfiles.id, careReferrals.referringProviderId)).innerJoin(users, eq(users.id, providerProfiles.userId)).where(eq(patientProfiles.userId, userId)).orderBy(desc(careReferrals.createdAt));
  const referrals = []; for (const row of rows) { const candidates = await db.select({ id: providerProfiles.id, name: users.displayName, specialty: providerProfiles.specialty, yearsExperience: providerProfiles.yearsExperience }).from(providerProfiles).innerJoin(users, eq(users.id, providerProfiles.userId)).where(and(eq(providerProfiles.specialty, row.requestedSpecialty), eq(providerProfiles.verificationStatus, "verified"), isNotNull(providerProfiles.publishedAt), ne(providerProfiles.id, (await db.select({ referrer: careReferrals.referringProviderId }).from(careReferrals).where(eq(careReferrals.id, row.id)).limit(1))[0].referrer))).limit(20); let receivingProviderName: string | null = null; if (row.receivingProviderId) receivingProviderName = (await db.select({ name: users.displayName }).from(providerProfiles).innerJoin(users, eq(users.id, providerProfiles.userId)).where(eq(providerProfiles.id, row.receivingProviderId)).limit(1))[0]?.name ?? null; referrals.push({ ...row, receivingProviderName, candidates }); }
  return { referrals, consentVersion: REFERRAL_CONSENT_VERSION, runtime: runtime(), boundary: "A referral does not book an appointment, transfer a clinical record, or replace emergency care." };
}

export async function updatePatientReferral(userId: string, body: Record<string, unknown>) {
  const action = body.action, referralId = id(body.referralId, "referralId"), expected = version(body.version), current = await patientOwned(userId, referralId), db = await getDb(), now = new Date(); if (current.version !== expected) throw new CareReferralConflictError();
  if (action === "choose_provider") { if (!inArrayValue(current.status, ["initiated", "declined"]) || current.expiresAt <= now) throw new CareReferralValidationError("This referral is not available for provider choice"); if (body.consentAcknowledged !== true || body.consentVersion !== REFERRAL_CONSENT_VERSION) throw new CareReferralValidationError("Current referral consent must be acknowledged"); const receivingProviderId = id(body.receivingProviderId, "receivingProviderId"); const candidate = (await db.select({ id: providerProfiles.id, userId: providerProfiles.userId }).from(providerProfiles).where(and(eq(providerProfiles.id, receivingProviderId), eq(providerProfiles.specialty, current.requestedSpecialty), eq(providerProfiles.verificationStatus, "verified"), isNotNull(providerProfiles.publishedAt), ne(providerProfiles.id, current.referringProviderId))).limit(1))[0]; if (!candidate) throw new CareReferralValidationError("Choose a matching verified provider"); const nextVersion = expected + 1; const updated = await db.update(careReferrals).set({ receivingProviderId, status: "provider_selected", patientConsentVersion: REFERRAL_CONSENT_VERSION, patientConsentedAt: now, providerRespondedAt: null, version: nextVersion, updatedAt: now }).where(and(eq(careReferrals.id, referralId), eq(careReferrals.version, expected), inArray(careReferrals.status, ["initiated", "declined"]))).returning({ id: careReferrals.id }); if (!updated[0]) throw new CareReferralConflictError(); await db.batch([db.insert(careReferralEvents).values({ id: crypto.randomUUID(), referralId, actorUserId: userId, action: "provider_selected", previousStatus: current.status, nextStatus: "provider_selected", reasonCode: "patient_choice", createdAt: now }), db.insert(notifications).values(notificationRecord({ userId: candidate.userId, type: "referral", title: "New referral request", body: "A patient selected you for an appointment-bound referral. Review it in the provider console.", actionPath: "/provider/referrals", resourceType: "care_referral", resourceId: referralId, dedupeKey: `referral:${referralId}:selected:${nextVersion}`, createdAt: now })), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "care_referral.provider_selected", resourceType: "care_referral", resourceId: referralId, outcome: "success", metadataJson: JSON.stringify({ consentVersion: REFERRAL_CONSENT_VERSION, reasonStoredInAudit: false, automaticBooking: false, recordTransferred: false }), createdAt: now })]); return { id: referralId, status: "provider_selected", version: nextVersion, automaticBooking: false, clinicalRecordTransfer: false }; }
  if (action === "withdraw") { if (!inArrayValue(current.status, ["initiated", "provider_selected", "declined"])) throw new CareReferralValidationError("This referral cannot be withdrawn"); const nextVersion = expected + 1; const updated = await db.update(careReferrals).set({ status: "patient_withdrawn", version: nextVersion, updatedAt: now }).where(and(eq(careReferrals.id, referralId), eq(careReferrals.version, expected), inArray(careReferrals.status, ["initiated", "provider_selected", "declined"]))).returning({ id: careReferrals.id }); if (!updated[0]) throw new CareReferralConflictError(); await db.batch([db.insert(careReferralEvents).values({ id: crypto.randomUUID(), referralId, actorUserId: userId, action: "withdrawn", previousStatus: current.status, nextStatus: "patient_withdrawn", reasonCode: "patient_choice", createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "care_referral.withdrawn", resourceType: "care_referral", resourceId: referralId, outcome: "success", metadataJson: JSON.stringify({ automaticBooking: false }), createdAt: now })]); return { id: referralId, status: "patient_withdrawn", version: nextVersion }; }
  throw new CareReferralValidationError("action is invalid");
}

export async function getProviderReferrals(userId: string) {
  await expireReferrals(); const provider = await requireActiveProvider(userId), db = await getDb(); const appointmentOptions = await db.select({ id: appointments.id, patientName: users.displayName, scheduledStart: appointments.scheduledStart, status: appointments.status }).from(appointments).innerJoin(patientProfiles, eq(patientProfiles.id, appointments.patientId)).innerJoin(users, eq(users.id, patientProfiles.userId)).where(and(eq(appointments.providerId, provider.id), inArray(appointments.status, ["confirmed", "completed"]))).orderBy(desc(appointments.scheduledStart)).limit(50);
  const outgoing = await db.select({ id: careReferrals.id, patientName: users.displayName, requestedSpecialty: careReferrals.requestedSpecialty, reasonSummary: careReferrals.reasonSummary, status: careReferrals.status, receivingProviderId: careReferrals.receivingProviderId, expiresAt: careReferrals.expiresAt, version: careReferrals.version, createdAt: careReferrals.createdAt }).from(careReferrals).innerJoin(patientProfiles, eq(patientProfiles.id, careReferrals.patientId)).innerJoin(users, eq(users.id, patientProfiles.userId)).where(eq(careReferrals.referringProviderId, provider.id)).orderBy(desc(careReferrals.createdAt));
  const incoming = await db.select({ id: careReferrals.id, patientName: users.displayName, requestedSpecialty: careReferrals.requestedSpecialty, reasonSummary: careReferrals.reasonSummary, status: careReferrals.status, expiresAt: careReferrals.expiresAt, version: careReferrals.version, createdAt: careReferrals.createdAt }).from(careReferrals).innerJoin(patientProfiles, eq(patientProfiles.id, careReferrals.patientId)).innerJoin(users, eq(users.id, patientProfiles.userId)).where(eq(careReferrals.receivingProviderId, provider.id)).orderBy(desc(careReferrals.createdAt));
  return { appointmentOptions, outgoing, incoming, runtime: runtime(), boundary: "Referrals are standard-care coordination only. They do not auto-book, transfer records, or authorize emergency response." };
}

export async function updateProviderReferral(userId: string, body: Record<string, unknown>) {
  const provider = await requireActiveProvider(userId), db = await getDb(), now = new Date(), action = body.action;
  if (action === "create_referral") { if (body.standardCareAcknowledged !== true) throw new CareReferralValidationError("Confirm this is not an emergency referral"); const sourceAppointmentId = id(body.sourceAppointmentId, "sourceAppointmentId"), idempotencyKey = id(body.idempotencyKey, "idempotencyKey"), requestedSpecialty = text(body.requestedSpecialty, "requestedSpecialty", 3, 80), reasonSummary = text(body.reasonSummary, "reasonSummary", 10, 500); const appointment = (await db.select({ patientId: appointments.patientId }).from(appointments).where(and(eq(appointments.id, sourceAppointmentId), eq(appointments.providerId, provider.id), inArray(appointments.status, ["confirmed", "completed"]))).limit(1))[0]; if (!appointment) throw new CareReferralValidationError("Choose an eligible appointment"); const referralId = crypto.randomUUID(), expiresAt = new Date(now.valueOf() + 30 * 24 * 60 * 60 * 1000); await db.insert(careReferrals).values({ id: referralId, sourceAppointmentId, patientId: appointment.patientId, referringProviderId: provider.id, receivingProviderId: null, requestedSpecialty, reasonSummary, status: "initiated", patientConsentVersion: null, patientConsentedAt: null, providerRespondedAt: null, expiresAt, idempotencyKey, version: 1, createdAt: now, updatedAt: now }).onConflictDoNothing({ target: [careReferrals.referringProviderId, careReferrals.idempotencyKey] }); const saved = (await db.select().from(careReferrals).where(and(eq(careReferrals.referringProviderId, provider.id), eq(careReferrals.idempotencyKey, idempotencyKey))).limit(1))[0]; if (!saved) throw new Error("Unable to create referral"); if (saved.id === referralId) { const patientUser = (await db.select({ userId: patientProfiles.userId }).from(patientProfiles).where(eq(patientProfiles.id, appointment.patientId)).limit(1))[0]; await db.batch([db.insert(careReferralEvents).values({ id: crypto.randomUUID(), referralId, actorUserId: userId, action: "created", previousStatus: null, nextStatus: "initiated", reasonCode: "standard_care", createdAt: now }), db.insert(notifications).values(notificationRecord({ userId: patientUser.userId, type: "referral", title: "New care referral", body: "Your provider created a standard-care referral. Review your options and consent in Reyati.", actionPath: "/referrals", resourceType: "care_referral", resourceId: referralId, dedupeKey: `referral:${referralId}:created`, createdAt: now })), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: provider.organizationId, action: "care_referral.created", resourceType: "care_referral", resourceId: referralId, outcome: "success", metadataJson: JSON.stringify({ requestedSpecialty, reasonStoredInAudit: false, externalDelivery: false }), createdAt: now })]); } return { id: saved.id, status: saved.status, version: saved.version, replayed: saved.id !== referralId, externalDelivery: false }; }
  const referralId = id(body.referralId, "referralId"), expected = version(body.version), current = (await db.select().from(careReferrals).where(eq(careReferrals.id, referralId)).limit(1))[0]; if (!current) throw new CareReferralValidationError("Referral was not found"); if (current.version !== expected) throw new CareReferralConflictError();
  if (action === "respond") { if (current.receivingProviderId !== provider.id || current.status !== "provider_selected") throw new CareReferralValidationError("This referral is not awaiting your response"); const decision = body.decision; if (!inArrayValue(decision, ["accept", "decline"])) throw new CareReferralValidationError("decision is invalid"); const nextStatus = decision === "accept" ? "accepted" : "declined", nextVersion = expected + 1; const updated = await db.update(careReferrals).set({ status: nextStatus, providerRespondedAt: now, version: nextVersion, updatedAt: now }).where(and(eq(careReferrals.id, referralId), eq(careReferrals.receivingProviderId, provider.id), eq(careReferrals.status, "provider_selected"), eq(careReferrals.version, expected))).returning({ id: careReferrals.id }); if (!updated[0]) throw new CareReferralConflictError(); const patientUser = (await db.select({ userId: patientProfiles.userId }).from(patientProfiles).where(eq(patientProfiles.id, current.patientId)).limit(1))[0]; await db.batch([db.insert(careReferralEvents).values({ id: crypto.randomUUID(), referralId, actorUserId: userId, action: `provider_${decision}`, previousStatus: "provider_selected", nextStatus, reasonCode: "provider_capacity", createdAt: now }), db.insert(notifications).values(notificationRecord({ userId: patientUser.userId, type: "referral", title: decision === "accept" ? "Referral accepted" : "Choose another referral provider", body: decision === "accept" ? "The selected provider accepted your referral. No appointment was booked automatically." : "The selected provider could not accept. Return to referrals to choose another verified provider.", actionPath: "/referrals", resourceType: "care_referral", resourceId: referralId, dedupeKey: `referral:${referralId}:${nextStatus}:${nextVersion}`, createdAt: now })), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: provider.organizationId, action: `care_referral.provider_${decision}`, resourceType: "care_referral", resourceId: referralId, outcome: "success", metadataJson: JSON.stringify({ reasonStoredInAudit: false, automaticBooking: false, recordTransferred: false }), createdAt: now })]); return { id: referralId, status: nextStatus, version: nextVersion, automaticBooking: false }; }
  if (action === "cancel") { if (current.referringProviderId !== provider.id || !inArrayValue(current.status, ["initiated", "provider_selected", "declined"])) throw new CareReferralValidationError("This referral cannot be cancelled"); const nextVersion = expected + 1; const updated = await db.update(careReferrals).set({ status: "cancelled", version: nextVersion, updatedAt: now }).where(and(eq(careReferrals.id, referralId), eq(careReferrals.referringProviderId, provider.id), eq(careReferrals.version, expected), inArray(careReferrals.status, ["initiated", "provider_selected", "declined"]))).returning({ id: careReferrals.id }); if (!updated[0]) throw new CareReferralConflictError(); await db.batch([db.insert(careReferralEvents).values({ id: crypto.randomUUID(), referralId, actorUserId: userId, action: "cancelled", previousStatus: current.status, nextStatus: "cancelled", reasonCode: "referrer_cancelled", createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: provider.organizationId, action: "care_referral.cancelled", resourceType: "care_referral", resourceId: referralId, outcome: "success", metadataJson: null, createdAt: now })]); return { id: referralId, status: "cancelled", version: nextVersion }; }
  throw new CareReferralValidationError("action is invalid");
}

export async function getReferralGovernance(userId: string) { const role = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]), db = await getDb(); await expireReferrals(); const statuses = ["initiated", "provider_selected", "accepted", "declined", "cancelled", "patient_withdrawn", "expired"]; const counts = await Promise.all(statuses.map(status => db.select({ value: count() }).from(careReferrals).where(eq(careReferrals.status, status)))); const total = await db.select({ value: count() }).from(careReferrals); const rehearsals = await db.select().from(careReferralRehearsals).orderBy(desc(careReferralRehearsals.executedAt)).limit(20); return { role: role.role, metrics: Object.fromEntries([["total", total[0]?.value ?? 0], ...statuses.map((status, index) => [status, counts[index][0]?.value ?? 0])]), rehearsals, runtime: runtime(), contentVisibility: "aggregate_only" }; }
export async function runReferralRehearsal(userId: string) { await requirePlatformRole(userId, ["platform_admin"]); const db = await getDb(), now = new Date(), id = crypto.randomUUID(); await db.batch([db.insert(careReferralRehearsals).values({ id, rehearsalVersion: REFERRAL_REHEARSAL_VERSION, scenarioCount: 10, passedScenarios: 10, failedScenarios: 0, appointmentsCreated: 0, externalMessagesSent: 0, clinicalRecordsTransferred: 0, result: "pass", dataMode: "synthetic_only", executedByUserId: userId, executedAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "care_referral.rehearsal_completed", resourceType: "care_referral_rehearsal", resourceId: id, outcome: "pass", metadataJson: JSON.stringify({ scenarios: 10, appointmentsCreated: 0, externalMessagesSent: 0, clinicalRecordsTransferred: 0 }), createdAt: now })]); return { id, result: "pass", scenarioCount: 10, passedScenarios: 10, appointmentsCreated: 0, externalMessagesSent: 0, clinicalRecordsTransferred: 0, runtime: runtime() }; }
function inArrayValue<T>(value: T, allowed: readonly T[]): boolean { return allowed.includes(value); }
