import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, careNavigatorAssessmentEvents, careNavigatorAssessments } from "@/db/schema";
import { getPublishedProviderCatalog } from "@/lib/provider-catalog";

export const NAVIGATOR_RULESET_VERSION = "rules-foundation-2026-08-16";
export const NAVIGATOR_CONSENT_VERSION = "navigator-purpose-v1";
export const RED_FLAG_KEYS = ["breathing_difficulty", "unconscious_or_confused", "stroke_signs", "uncontrolled_bleeding", "serious_injury", "immediate_harm_risk"] as const;
const categories = ["general", "skin", "muscle_joint", "womens_health", "child_health", "mental_wellbeing", "dental", "eye", "ear_nose_throat", "other"] as const;
const durations = ["today", "days", "weeks", "months", "unsure"] as const; const ages = ["child", "adult", "older_adult", "prefer_not_to_say"] as const; const modes = ["any", "in_person", "video"] as const;
const routes: Record<(typeof categories)[number], { specialty: string | null; aliases: string[]; rationale: string; mode: string }> = {
  general: { specialty: "General Medicine", aliases: ["general", "family", "primary"], rationale: "general_start", mode: "in_person" }, skin: { specialty: "Dermatology", aliases: ["dermatology", "skin"], rationale: "skin_start", mode: "in_person" }, muscle_joint: { specialty: "Orthopedics", aliases: ["orthopedic", "musculoskeletal"], rationale: "muscle_joint_start", mode: "in_person" }, womens_health: { specialty: "Obstetrics & Gynecology", aliases: ["gynecology", "gynaecology", "obstetrics"], rationale: "womens_health_start", mode: "in_person" }, child_health: { specialty: "Pediatrics", aliases: ["pediatric", "paediatric", "child"], rationale: "child_health_start", mode: "in_person" }, mental_wellbeing: { specialty: "Mental Health", aliases: ["psychiatry", "psychology", "mental"], rationale: "mental_wellbeing_start", mode: "video" }, dental: { specialty: "Dentistry", aliases: ["dental", "dentist"], rationale: "dental_start", mode: "in_person" }, eye: { specialty: "Ophthalmology", aliases: ["ophthalmology", "eye"], rationale: "eye_start", mode: "in_person" }, ear_nose_throat: { specialty: "ENT", aliases: ["ent", "ear nose", "otolaryngology"], rationale: "ent_start", mode: "in_person" }, other: { specialty: null, aliases: [], rationale: "insufficient_information", mode: "in_person" },
};
export class CareNavigatorValidationError extends Error { constructor(message: string) { super(message); this.name = "CareNavigatorValidationError"; } }
export class CareNavigatorConflictError extends Error { constructor() { super("This guidance record changed. Refresh and try again."); this.name = "CareNavigatorConflictError"; } }
function choice<T extends readonly string[]>(value: unknown, name: string, values: T): T[number] { if (typeof value !== "string" || !values.includes(value)) throw new CareNavigatorValidationError(`${name} is invalid`); return value as T[number]; }
function parseFlags(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new CareNavigatorValidationError("redFlags is invalid"); const raw = value as Record<string, unknown>; if (Object.keys(raw).some((key) => !(RED_FLAG_KEYS as readonly string[]).includes(key)) || RED_FLAG_KEYS.some((key) => typeof raw[key] !== "boolean")) throw new CareNavigatorValidationError("Every emergency red-flag question requires an explicit answer"); return Object.fromEntries(RED_FLAG_KEYS.map((key) => [key, raw[key]])) as Record<(typeof RED_FLAG_KEYS)[number], boolean>; }
function questions(category: string) { return ["timeline_changes", category === "mental_wellbeing" ? "support_and_safety" : "triggers_and_relief", "medicines_allergies", "questions_for_provider"]; }
export function evaluateCareNavigatorRules(body: Record<string, unknown>) { const concernCategory = choice(body.concernCategory, "concernCategory", categories); const durationBand = choice(body.durationBand, "durationBand", durations); const ageGroup = choice(body.ageGroup, "ageGroup", ages); const careModePreference = choice(body.careModePreference, "careModePreference", modes); const redFlags = parseFlags(body.redFlags); const emergency = RED_FLAG_KEYS.some((key) => redFlags[key]); const route = routes[ageGroup === "child" && concernCategory === "general" ? "child_health" : concernCategory]; const outcome = emergency ? "emergency" : route.specialty ? "routed" : "insufficient_information"; return { concernCategory, durationBand, ageGroup, careModePreference, redFlags, emergency, outcome, specialty: emergency ? null : route.specialty, recommendedCareMode: emergency ? null : careModePreference === "any" ? route.mode : careModePreference, rationaleCode: emergency ? "emergency_red_flag" : route.rationale, preparationQuestions: emergency ? [] : questions(concernCategory), aliases: route.aliases }; }
function safe(row: typeof careNavigatorAssessments.$inferSelect) { return { id: row.id, locale: row.locale, rulesetVersion: row.rulesetVersion, concernCategory: row.concernCategory, durationBand: row.durationBand, ageGroup: row.ageGroup, careModePreference: row.careModePreference, outcome: row.outcome, recommendedSpecialty: row.recommendedSpecialty, recommendedCareMode: row.recommendedCareMode, rationaleCode: row.rationaleCode, preparationQuestions: JSON.parse(row.preparationQuestionsJson) as string[], providerIds: JSON.parse(row.providerIdsJson) as string[], status: row.status, decision: row.decision, version: row.version, createdAt: row.createdAt } }

export async function getCareNavigatorWorkspace(userId: string) { const db = await getDb(); const history = await db.select().from(careNavigatorAssessments).where(eq(careNavigatorAssessments.userId, userId)).orderBy(desc(careNavigatorAssessments.createdAt)).limit(20); return { status: "foundation", clinicallyApproved: false, modelAssistanceEnabled: false, rulesetVersion: NAVIGATOR_RULESET_VERSION, consentVersion: NAVIGATOR_CONSENT_VERSION, emergency: { country: "Qatar", number: "999", source: "Qatar Ministry of Interior and Hamad Medical Corporation" }, redFlagKeys: RED_FLAG_KEYS, history: history.map(safe) }; }

export async function assessCareStartingPoint(userId: string, body: Record<string, unknown>) { if (body.consentAccepted !== true || body.consentVersion !== NAVIGATOR_CONSENT_VERSION) throw new CareNavigatorValidationError("Current purpose-specific consent is required"); const locale = choice(body.locale, "locale", ["en", "ar"] as const); const evaluation = evaluateCareNavigatorRules(body); const { concernCategory, durationBand, ageGroup, careModePreference, redFlags, emergency, outcome, specialty, recommendedCareMode, rationaleCode, preparationQuestions, aliases } = evaluation; let providerIds: string[] = []; let providers: Array<{ id: string; name: string; specialty: string; languages: string[] }> = [];
  if (outcome === "routed" && specialty) { const catalog = await getPublishedProviderCatalog(); providers = catalog.filter((provider) => aliases.some((alias) => provider.specialty.toLowerCase().includes(alias))).slice(0, 3).map(({ id, name, specialty: providerSpecialty, languages }) => ({ id, name, specialty: providerSpecialty, languages })); providerIds = providers.map((provider) => provider.id); }
  const db = await getDb(); const now = new Date(); const id = crypto.randomUUID(); await db.batch([db.insert(careNavigatorAssessments).values({ id, userId, locale, consentVersion: NAVIGATOR_CONSENT_VERSION, rulesetVersion: NAVIGATOR_RULESET_VERSION, concernCategory, durationBand, ageGroup, careModePreference, redFlagsJson: JSON.stringify(redFlags), outcome, recommendedSpecialty: specialty, recommendedCareMode, rationaleCode, preparationQuestionsJson: JSON.stringify(preparationQuestions), providerIdsJson: JSON.stringify(providerIds), status: "presented", version: 1, createdAt: now, updatedAt: now }), db.insert(careNavigatorAssessmentEvents).values({ id: crypto.randomUUID(), assessmentId: id, actorUserId: userId, action: "guidance_presented", previousStatus: null, nextStatus: "presented", decision: null, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "care_navigator.guidance_presented", resourceType: "care_navigator_assessment", resourceId: id, outcome: "success", metadataJson: JSON.stringify({ outcome, rulesetVersion: NAVIGATOR_RULESET_VERSION, locale, modelAssistanceEnabled: false }), createdAt: now })]); return { ...safe({ id, userId, locale, consentVersion: NAVIGATOR_CONSENT_VERSION, rulesetVersion: NAVIGATOR_RULESET_VERSION, concernCategory, durationBand, ageGroup, careModePreference, redFlagsJson: JSON.stringify(redFlags), outcome, recommendedSpecialty: specialty, recommendedCareMode, rationaleCode, preparationQuestionsJson: JSON.stringify(preparationQuestions), providerIdsJson: JSON.stringify(providerIds), status: "presented", decision: null, decidedAt: null, version: 1, createdAt: now, updatedAt: now }), providers, clinicallyApproved: false, modelAssistanceEnabled: false, emergencyNumber: emergency ? "999" : null };
}

export async function recordCareNavigatorDecision(userId: string, body: Record<string, unknown>) { const db = await getDb(); const assessmentId = typeof body.assessmentId === "string" && body.assessmentId.length <= 128 ? body.assessmentId : ""; const version = Number(body.version); const decision = choice(body.decision, "decision", ["view_providers", "contact_support", "seek_emergency_help", "dismissed"] as const); const current = (await db.select().from(careNavigatorAssessments).where(and(eq(careNavigatorAssessments.id, assessmentId), eq(careNavigatorAssessments.userId, userId))).limit(1))[0]; if (!current) throw new CareNavigatorValidationError("Guidance record was not found"); if (!Number.isSafeInteger(version) || version !== current.version || current.status !== "presented") throw new CareNavigatorConflictError(); const allowed = current.outcome === "emergency" ? ["seek_emergency_help", "dismissed"] : current.outcome === "routed" ? ["view_providers", "dismissed"] : ["contact_support", "dismissed"]; if (!allowed.includes(decision)) throw new CareNavigatorValidationError("decision is not allowed for this guidance state"); const now = new Date(); const changed = await db.update(careNavigatorAssessments).set({ status: "decision_recorded", decision, decidedAt: now, version: current.version + 1, updatedAt: now }).where(and(eq(careNavigatorAssessments.id, assessmentId), eq(careNavigatorAssessments.userId, userId), eq(careNavigatorAssessments.version, version), eq(careNavigatorAssessments.status, "presented"))).returning({ version: careNavigatorAssessments.version }); if (!changed[0]) throw new CareNavigatorConflictError(); await db.batch([db.insert(careNavigatorAssessmentEvents).values({ id: crypto.randomUUID(), assessmentId, actorUserId: userId, action: "decision_recorded", previousStatus: "presented", nextStatus: "decision_recorded", decision, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "care_navigator.decision_recorded", resourceType: "care_navigator_assessment", resourceId: assessmentId, outcome: "success", metadataJson: JSON.stringify({ decision }), createdAt: now })]); return { assessmentId, decision, status: "decision_recorded", version: changed[0].version }; }
