import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, dataLifecyclePolicies, dataLifecyclePolicyEvents, notifications, platformRoles, users } from "@/db/schema";
import { requirePlatformRole } from "@/lib/authorization";
import { notificationRecord } from "@/lib/notification-center";

export class LifecycleValidationError extends Error { constructor(message: string) { super(message); this.name = "LifecycleValidationError"; } }
export class LifecycleConflictError extends Error { constructor() { super("This policy changed. Refresh and try again."); this.name = "LifecycleConflictError"; } }
export const requiredRecordClasses = ["finalized_encounters", "medical_documents", "appointment_records", "audit_security_events", "communications_metadata"] as const;
export const retentionTriggers = ["record_created", "encounter_finalized", "appointment_completed", "account_closed", "event_recorded"] as const;
export const dispositions = ["review_then_delete", "archive_then_review", "retain_under_healthcare_rule"] as const;
function text(value: unknown, name: string, min: number, max: number) { if (typeof value !== "string" || value.trim().length < min || value.trim().length > max) throw new LifecycleValidationError(`${name} is invalid`); return value.trim(); }
function months(value: unknown) { const result = Number(value); if (!Number.isSafeInteger(result) || result < 1 || result > 1200) throw new LifecycleValidationError("retentionMonths is invalid"); return result; }
async function operators() { const db = await getDb(); return db.select({ userId: users.id, displayName: users.displayName, role: platformRoles.role }).from(platformRoles).innerJoin(users, eq(users.id, platformRoles.userId)).where(and(eq(platformRoles.status, "active"), inArray(platformRoles.role, ["platform_admin", "security_auditor"]))).orderBy(asc(users.displayName)); }

export async function getDataLifecycleCentre(userId: string) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const db = await getDb();
  const [policies, activeOperators, events] = await Promise.all([db.select().from(dataLifecyclePolicies).orderBy(asc(dataLifecyclePolicies.recordClass)), operators(), db.select({ id: dataLifecyclePolicyEvents.id, policyId: dataLifecyclePolicyEvents.policyId, action: dataLifecyclePolicyEvents.action, previousStatus: dataLifecyclePolicyEvents.previousStatus, nextStatus: dataLifecyclePolicyEvents.nextStatus, note: dataLifecyclePolicyEvents.note, createdAt: dataLifecyclePolicyEvents.createdAt, actorName: users.displayName }).from(dataLifecyclePolicyEvents).innerJoin(users, eq(users.id, dataLifecyclePolicyEvents.actorUserId)).orderBy(desc(dataLifecyclePolicyEvents.createdAt)).limit(300)]);
  const names = new Map(activeOperators.map((item) => [item.userId, item.displayName])); return { role: access.role, currentUserId: userId, recordClasses: requiredRecordClasses, retentionTriggers, dispositions, operators: activeOperators, policies: policies.map((policy) => ({ ...policy, ownerName: names.get(policy.ownerUserId) ?? "Unavailable owner", reviewerName: policy.reviewerUserId ? names.get(policy.reviewerUserId) ?? "Unavailable reviewer" : null, events: events.filter((event) => event.policyId === policy.id) })) };
}

export async function saveDataLifecyclePolicy(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const recordClass = text(body.recordClass, "recordClass", 1, 60); if (!requiredRecordClasses.includes(recordClass as typeof requiredRecordClasses[number])) throw new LifecycleValidationError("recordClass is invalid"); const retentionMonths = months(body.retentionMonths); const retentionTrigger = text(body.retentionTrigger, "retentionTrigger", 1, 60); if (!retentionTriggers.includes(retentionTrigger as typeof retentionTriggers[number])) throw new LifecycleValidationError("retentionTrigger is invalid"); const disposition = text(body.disposition, "disposition", 1, 60); if (!dispositions.includes(disposition as typeof dispositions[number])) throw new LifecycleValidationError("disposition is invalid"); const legalBasisReference = text(body.legalBasisReference, "legalBasisReference", 6, 240); const evidenceReference = text(body.evidenceReference, "evidenceReference", 6, 240); const ownerUserId = text(body.ownerUserId, "ownerUserId", 1, 128); const db = await getDb(); const validOwner = await db.select({ id: platformRoles.userId }).from(platformRoles).where(and(eq(platformRoles.userId, ownerUserId), eq(platformRoles.status, "active"), inArray(platformRoles.role, ["platform_admin", "security_auditor"]))).limit(1); if (!validOwner[0]) throw new LifecycleValidationError("ownerUserId is invalid"); const existing = await db.select().from(dataLifecyclePolicies).where(eq(dataLifecyclePolicies.recordClass, recordClass)).limit(1); const now = new Date(); const id = existing[0]?.id ?? crypto.randomUUID(); let version = 1; let previousStatus: string | null = null;
  if (existing[0]) { if (!Number.isSafeInteger(body.version) || Number(body.version) !== existing[0].version) throw new LifecycleConflictError(); if (!["draft", "rejected"].includes(existing[0].status)) throw new LifecycleValidationError("Only a draft or rejected policy can be edited"); previousStatus = existing[0].status; const updated = await db.update(dataLifecyclePolicies).set({ retentionMonths, retentionTrigger, disposition, legalBasisReference, evidenceReference, ownerUserId, status: "draft", reviewerUserId: null, reviewedAt: null, reviewNote: null, effectiveAt: null, version: existing[0].version + 1, updatedAt: now }).where(and(eq(dataLifecyclePolicies.id, id), eq(dataLifecyclePolicies.version, existing[0].version), eq(dataLifecyclePolicies.status, existing[0].status))).returning({ version: dataLifecyclePolicies.version }); if (!updated[0]) throw new LifecycleConflictError(); version = updated[0].version; }
  else { try { await db.insert(dataLifecyclePolicies).values({ id, recordClass, retentionMonths, retentionTrigger, disposition, legalBasisReference, evidenceReference, ownerUserId, status: "draft", version, createdAt: now, updatedAt: now }); } catch { throw new LifecycleConflictError(); } }
  await record(userId, { id, recordClass, ownerUserId, version }, "save", previousStatus, "draft", "Policy draft saved with bounded retention and evidence references.", now); return { id, recordClass, status: "draft", version };
}

export async function transitionDataLifecyclePolicy(userId: string, body: Record<string, unknown>) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const policyId = text(body.policyId, "policyId", 1, 128); const action = text(body.action, "action", 1, 20); const note = text(body.note, "note", 10, 1200); if (!Number.isSafeInteger(body.version) || Number(body.version) < 1) throw new LifecycleValidationError("version is invalid"); const db = await getDb(); const rows = await db.select().from(dataLifecyclePolicies).where(eq(dataLifecyclePolicies.id, policyId)).limit(1); const current = rows[0]; if (!current) throw new LifecycleValidationError("Policy was not found"); const now = new Date(); let nextStatus = current.status; let reviewerUserId = current.reviewerUserId; let reviewedAt = current.reviewedAt; let reviewNote = current.reviewNote; let effectiveAt = current.effectiveAt;
  if (action === "submit") { if (access.role !== "platform_admin" || !["draft", "rejected"].includes(current.status)) throw new LifecycleValidationError("This policy cannot be submitted"); nextStatus = "pending_review"; reviewerUserId = null; reviewedAt = null; reviewNote = null; effectiveAt = null; }
  else if (["approve", "reject"].includes(action)) { if (current.status !== "pending_review") throw new LifecycleValidationError("This policy cannot be reviewed"); if (current.ownerUserId === userId) throw new LifecycleValidationError("The policy owner cannot independently review their own policy"); nextStatus = action === "approve" ? "approved" : "rejected"; reviewerUserId = userId; reviewedAt = now; reviewNote = note; effectiveAt = action === "approve" ? now : null; }
  else if (action === "retire") { if (access.role !== "platform_admin" || current.status !== "approved") throw new LifecycleValidationError("This policy cannot be retired"); nextStatus = "retired"; }
  else throw new LifecycleValidationError("action is invalid");
  const updated = await db.update(dataLifecyclePolicies).set({ status: nextStatus, reviewerUserId, reviewedAt, reviewNote, effectiveAt, version: current.version + 1, updatedAt: now }).where(and(eq(dataLifecyclePolicies.id, policyId), eq(dataLifecyclePolicies.version, Number(body.version)), eq(dataLifecyclePolicies.status, current.status))).returning({ version: dataLifecyclePolicies.version }); if (!updated[0]) throw new LifecycleConflictError(); await record(userId, { id: policyId, recordClass: current.recordClass, ownerUserId: current.ownerUserId, version: updated[0].version }, action, current.status, nextStatus, note, now); return { policyId, status: nextStatus, version: updated[0].version };
}

async function record(actorUserId: string, policy: { id: string; recordClass: string; ownerUserId: string; version: number }, action: string, previousStatus: string | null, nextStatus: string, note: string, now: Date) { const db = await getDb(); await db.batch([db.insert(dataLifecyclePolicyEvents).values({ id: crypto.randomUUID(), policyId: policy.id, actorUserId, action, previousStatus, nextStatus, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId, organizationId: null, action: `data_lifecycle.${action}`, resourceType: "data_lifecycle_policy", resourceId: policy.id, outcome: "success", metadataJson: JSON.stringify({ recordClass: policy.recordClass, previousStatus, nextStatus }), createdAt: now }), db.insert(notifications).values(notificationRecord({ userId: policy.ownerUserId, type: "operations", title: `${policy.recordClass.replaceAll("_", " ")} policy updated`, body: `The lifecycle policy moved to ${nextStatus}. Open data lifecycle to review the evidence trail.`, actionPath: "/admin/data-lifecycle", resourceType: "data_lifecycle_policy", resourceId: policy.id, dedupeKey: `lifecycle:${policy.id}:${policy.version}:${action}`, createdAt: now }))]); }
