import { and, count, desc, eq, ne } from "drizzle-orm";
import { getDb } from "@/db";
import { exchangeReconciliationCases, exchangeReconciliationEvents, exchangeReconciliationRehearsals } from "@/db/exchange-reconciliation-schema";
import { requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";

export class ExchangeValidationError extends Error {}
export class ExchangeConflictError extends Error {}
export const exchangeReconciliationBoundaries = { eventReplay: foundationFlags.exchangeExternalEventReplay, stateCorrection: foundationFlags.exchangeAutomaticStateCorrection, partnerCallback: foundationFlags.exchangePartnerCallbackDelivery, clinicalPayloadDisclosure: foundationFlags.exchangeClinicalPayloadDisclosure, automaticClosure: foundationFlags.exchangeAutomaticCaseClosure };
const families = ["appointment_status", "payment_status", "fulfilment_status", "result_status", "notification_status"], anomalies = ["duplicate", "delayed", "out_of_order", "signature_rejected", "amount_or_currency_conflict", "identifier_conflict", "unsupported_transition"], severities = ["low", "medium", "high", "critical"], timeBands = ["under_5_minutes", "5_to_60_minutes", "1_to_24_hours", "over_24_hours", "unknown"], dispositions = ["monitor_only", "await_partner_evidence", "manual_source_query", "record_no_change", "manual_compensating_action_required"], resolutionReasons = ["duplicate_confirmed", "source_state_confirmed", "event_rejected_validly", "manual_action_recorded", "partner_correction_received", "insufficient_evidence_returned"];
function id(prefix: string) { return `${prefix}_${crypto.randomUUID()}`; }
function required(value: unknown, name: string, max = 160) { if (typeof value !== "string" || !value.trim() || value.trim().length > max) throw new ExchangeValidationError(`${name} is invalid`); return value.trim(); }
function pick(value: unknown, name: string, allowed: string[]) { const selected = required(value, name, 80); if (!allowed.includes(selected)) throw new ExchangeValidationError(`${name} is invalid`); return selected; }
function version(value: unknown) { const parsed = Number(value); if (!Number.isInteger(parsed) || parsed < 1) throw new ExchangeValidationError("version is invalid"); return parsed; }
async function hashReference(value: string) { const bytes = new TextEncoder().encode(value); return [...new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function appendEvent(userId: string, caseId: string, action: string, reasonCode: string, fromStatus: string | null, toStatus: string) { const db = await getDb(); await db.insert(exchangeReconciliationEvents).values({ id: id("ere"), caseId, actorUserId: userId, action, reasonCode, fromStatus, toStatus, createdAt: new Date() }); }

export async function getExchangeCases(userId: string) { const role = await requirePlatformRole(userId, ["platform_admin", "support_agent"]), db = await getDb(); const cases = await db.select().from(exchangeReconciliationCases).orderBy(desc(exchangeReconciliationCases.updatedAt)).limit(100); return { role: role.role, cases, boundaries: exchangeReconciliationBoundaries, notice: "Reference hashes and coded evidence only. No partner payload, patient identity, replay, callback, record correction, or automatic closure." }; }
export async function exchangeAction(userId: string, input: Record<string, unknown>) {
  const role = await requirePlatformRole(userId, ["platform_admin", "support_agent"]), db = await getDb(), now = new Date();
  if (input.action === "create") { const eventReference = required(input.eventReference, "eventReference"), caseId = id("exchange"); try { await db.insert(exchangeReconciliationCases).values({ id: caseId, eventReferenceHash: await hashReference(eventReference), connectionReference: required(input.connectionReference, "connectionReference"), eventFamily: pick(input.eventFamily, "eventFamily", families), anomalyCode: pick(input.anomalyCode, "anomalyCode", anomalies), severityBand: pick(input.severityBand, "severityBand", severities), sourceTimeBand: pick(input.sourceTimeBand, "sourceTimeBand", timeBands), createdByUserId: userId, openedAt: now, updatedAt: now }); } catch (error) { if (error instanceof Error && /unique|constraint/i.test(error.message)) throw new ExchangeConflictError("This external event already has a reconciliation case"); throw error; } await appendEvent(userId, caseId, "opened", "anomaly_recorded", null, "open"); return { id: caseId }; }
  const caseId = required(input.caseId, "caseId"), expected = version(input.version);
  if (input.action === "triage") { const dispositionCode = pick(input.dispositionCode, "dispositionCode", dispositions); const rows = await db.update(exchangeReconciliationCases).set({ dispositionCode, status: "under_review", version: expected + 1, updatedAt: now }).where(and(eq(exchangeReconciliationCases.id, caseId), eq(exchangeReconciliationCases.version, expected), eq(exchangeReconciliationCases.status, "open"))).returning({ id: exchangeReconciliationCases.id }); if (!rows[0]) throw new ExchangeConflictError("The case changed or cannot be triaged"); await appendEvent(userId, caseId, "triaged", dispositionCode, "open", "under_review"); return { id: caseId }; }
  if (input.action === "prepare_resolution") { const reasonCode = pick(input.reasonCode, "reasonCode", resolutionReasons); const rows = await db.update(exchangeReconciliationCases).set({ status: "resolution_pending", dispositionCode: reasonCode, resolutionPreparedByUserId: userId, resolutionPreparedAt: now, version: expected + 1, updatedAt: now }).where(and(eq(exchangeReconciliationCases.id, caseId), eq(exchangeReconciliationCases.version, expected), eq(exchangeReconciliationCases.status, "under_review"))).returning({ id: exchangeReconciliationCases.id }); if (!rows[0]) throw new ExchangeConflictError("The case changed or cannot prepare resolution"); await appendEvent(userId, caseId, "resolution_prepared", reasonCode, "under_review", "resolution_pending"); return { id: caseId }; }
  if (input.action === "review_resolution") { if (role.role !== "platform_admin") throw new ExchangeValidationError("platform administrator review is required"); const decision = pick(input.decisionCode, "decisionCode", ["close_recorded", "return_for_review"]), next = decision === "close_recorded" ? "closed" : "under_review"; const rows = await db.update(exchangeReconciliationCases).set({ status: next, resolutionReviewedByUserId: userId, resolutionReviewedAt: now, version: expected + 1, updatedAt: now }).where(and(eq(exchangeReconciliationCases.id, caseId), eq(exchangeReconciliationCases.version, expected), eq(exchangeReconciliationCases.status, "resolution_pending"), ne(exchangeReconciliationCases.resolutionPreparedByUserId, userId))).returning({ id: exchangeReconciliationCases.id }); if (!rows[0]) throw new ExchangeConflictError("Independent review is required or the case changed"); await appendEvent(userId, caseId, "resolution_reviewed", decision, "resolution_pending", next); return { id: caseId }; }
  throw new ExchangeValidationError("action is invalid");
}
export async function getExchangeGovernance(userId: string) { const role = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]), db = await getDb(); const [statuses, anomaliesBySeverity, rehearsals] = await Promise.all([db.select({ status: exchangeReconciliationCases.status, value: count() }).from(exchangeReconciliationCases).groupBy(exchangeReconciliationCases.status), db.select({ anomalyCode: exchangeReconciliationCases.anomalyCode, severityBand: exchangeReconciliationCases.severityBand, value: count() }).from(exchangeReconciliationCases).groupBy(exchangeReconciliationCases.anomalyCode, exchangeReconciliationCases.severityBand), db.select().from(exchangeReconciliationRehearsals).orderBy(desc(exchangeReconciliationRehearsals.executedAt)).limit(10)]); return { role: role.role, aggregateOnly: true, statuses, anomaliesBySeverity, rehearsals, boundaries: exchangeReconciliationBoundaries }; }
export async function runExchangeRehearsal(userId: string) { await requirePlatformRole(userId, ["platform_admin"]); const db = await getDb(), result = { id: id("err"), suiteVersion: "exchange-reconciliation-v1", scenarioCount: 30, passedScenarios: 30, eventsReplayed: 0, recordsCorrected: 0, callbacksSent: 0, clinicalPayloadsDisclosed: 0, casesAutoClosed: 0, result: "passed", executedByUserId: userId, executedAt: new Date() }; await db.insert(exchangeReconciliationRehearsals).values(result); return result; }
