import { AuthorizationDeniedError } from "@/lib/authorization";
import { AuthenticationRequiredError, getOrCreateCurrentUser } from "@/lib/identity";
import { ExchangeConflictError, exchangeAction, ExchangeValidationError, getExchangeCases, getExchangeGovernance, runExchangeRehearsal } from "@/lib/exchange-reconciliation";
import { reportOperationalError } from "@/lib/observability";
import { enforceWriteRateLimit, rateLimitResponse } from "@/lib/rate-limits";
const headers = { "Cache-Control": "private, no-store" };
async function userId() { const user = await getOrCreateCurrentUser(); if (user.status !== "active") throw new AuthorizationDeniedError(); return user.id; }
function failure(error: unknown) { const limited = rateLimitResponse(error, headers); if (limited) return limited; if (error instanceof AuthenticationRequiredError) return Response.json({ error: "authentication_required" }, { status: 401, headers }); if (error instanceof AuthorizationDeniedError) return Response.json({ error: "forbidden" }, { status: 403, headers }); if (error instanceof ExchangeValidationError) return Response.json({ error: "invalid_request", message: error.message }, { status: 400, headers }); if (error instanceof ExchangeConflictError) return Response.json({ error: "conflict", message: error.message }, { status: 409, headers }); reportOperationalError("exchange.reconciliation.failed", error); return Response.json({ error: "service_unavailable" }, { status: 503, headers: { ...headers, "Retry-After": "30" } }); }
export async function exchangeGet(request: Request) { try { const view = new URL(request.url).searchParams.get("view"); return Response.json({ data: view === "governance" ? await getExchangeGovernance(await userId()) : await getExchangeCases(await userId()) }, { headers }); } catch (error) { return failure(error); } }
export async function exchangePost(request: Request) { try { const id = await userId(); await enforceWriteRateLimit(id, "exchange.reconciliation", { limit: 20 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body) throw new ExchangeValidationError("A JSON object is required"); return Response.json({ data: body.action === "rehearse" ? await runExchangeRehearsal(id) : await exchangeAction(id, body) }, { headers }); } catch (error) { return failure(error); } }
