import { and, desc, eq, inArray, ne } from "drizzle-orm";
import { getDb } from "@/db";
import { facilityDirectoryEvents, facilityDirectoryProfiles, facilityDirectoryRehearsals } from "@/db/facility-directory-schema";
import { auditEvents, facilities, organizations, providerServiceLocations } from "@/db/schema";
import { AuthorizationDeniedError, getActiveMemberships, requireOrganizationRole, requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";

export const FACILITY_DIRECTORY_FLAGS = {
  facilityDirectoryExternalImport: foundationFlags.facilityDirectoryExternalImport,
  facilityDirectoryAutomatedVerification: foundationFlags.facilityDirectoryAutomatedVerification,
  facilityDirectorySponsoredRanking: foundationFlags.facilityDirectorySponsoredRanking,
  facilityDirectoryLiveOccupancy: foundationFlags.facilityDirectoryLiveOccupancy,
  facilityDirectoryClinicalQualityRanking: foundationFlags.facilityDirectoryClinicalQualityRanking,
} as const;
export const FACILITY_DIRECTORY_REHEARSAL_VERSION = "facility-directory-governance-v1";
const ownerRoles = ["organization_owner", "organization_admin"] as const;
const freshnessDays = 90;

export class FacilityDirectoryValidationError extends Error { constructor(message: string) { super(message); this.name = "FacilityDirectoryValidationError"; } }
export class FacilityDirectoryConflictError extends Error { constructor() { super("This facility profile changed. Refresh and try again."); this.name = "FacilityDirectoryConflictError"; } }
export class FacilityDirectoryMakerCheckerError extends Error { constructor(message = "An independent checker is required.") { super(message); this.name = "FacilityDirectoryMakerCheckerError"; } }

const clean = (value: unknown, name: string, max: number, min = 1) => { if (typeof value !== "string") throw new FacilityDirectoryValidationError(`${name} is required`); const result = value.trim(); if (result.length < min || result.length > max) throw new FacilityDirectoryValidationError(`${name} must be ${min}-${max} characters`); return result; };
const identifier = (value: unknown, name: string) => clean(value, name, 128);
const versionValue = (value: unknown) => { const result = Number(value); if (!Number.isSafeInteger(result) || result < 1) throw new FacilityDirectoryValidationError("version is invalid"); return result; };
const list = (value: unknown, name: string, maxItems = 20) => { if (!Array.isArray(value) || value.length > maxItems) throw new FacilityDirectoryValidationError(`${name} must contain at most ${maxItems} entries`); const result = value.map((item) => clean(item, name, 120, 2)); if (new Set(result.map((item) => item.toLowerCase())).size !== result.length) throw new FacilityDirectoryValidationError(`${name} entries must be unique`); return result; };
const modes = (value: unknown) => { const result = list(value, "modes", 3); if (result.some((item) => !["in_person", "video", "home_visit"].includes(item))) throw new FacilityDirectoryValidationError("mode is invalid"); return result; };
const hours = (value: unknown) => { if (!Array.isArray(value) || value.length > 7) throw new FacilityDirectoryValidationError("openingHours must contain at most seven entries"); return value.map((row) => { const item = row as Record<string, unknown>; const day = Number(item.day), open = clean(item.open, "open", 5, 5), close = clean(item.close, "close", 5, 5); if (!Number.isSafeInteger(day) || day < 0 || day > 6 || !/^\d{2}:\d{2}$/.test(open) || !/^\d{2}:\d{2}$/.test(close) || open >= close) throw new FacilityDirectoryValidationError("openingHours entry is invalid"); return { day, open, close }; }); };
const email = (value: unknown) => { const result = clean(value, "contactEmail", 160, 5).toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result)) throw new FacilityDirectoryValidationError("contactEmail is invalid"); return result; };
const reason = (value: unknown) => { const result = clean(value, "reasonCode", 64, 2).toLowerCase(); if (!/^[a-z][a-z0-9_]*$/.test(result)) throw new FacilityDirectoryValidationError("reasonCode is invalid"); return result; };
const parseList = (value: string) => { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } };

async function profile(profileId: string) { const db = await getDb(); const row = (await db.select().from(facilityDirectoryProfiles).where(eq(facilityDirectoryProfiles.id, profileId)).limit(1))[0]; if (!row) throw new FacilityDirectoryValidationError("Facility profile was not found"); return row; }
async function record(actorUserId: string, item: { id: string; organizationId: string }, actionCode: string, previousStatus: string | null, nextStatus: string, profileVersion: number, reasonCode: string | null = null) { const db = await getDb(), now = new Date(); await db.batch([
  db.insert(facilityDirectoryEvents).values({ id: crypto.randomUUID(), profileId: item.id, organizationId: item.organizationId, actorUserId, actionCode, previousStatus, nextStatus, reasonCode, profileVersion, createdAt: now }),
  db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId, organizationId: item.organizationId, action: `facility_directory.${actionCode}`, resourceType: "facility_directory_profile", resourceId: item.id, outcome: "success", metadataJson: JSON.stringify({ codedEventOnly: true, profileCopyIncluded: false, contactDetailsIncluded: false, clinicalDataIncluded: false, externalSideEffect: false }), createdAt: now }),
]); }

function validatedInput(body: Record<string, unknown>) { return {
  nameEn: clean(body.nameEn, "nameEn", 160, 2), nameAr: clean(body.nameAr, "nameAr", 160, 2),
  descriptionEn: clean(body.descriptionEn, "descriptionEn", 1000, 12), descriptionAr: clean(body.descriptionAr, "descriptionAr", 1000, 12),
  addressEn: clean(body.addressEn, "addressEn", 300, 5), addressAr: clean(body.addressAr, "addressAr", 300, 5),
  departmentsJson: JSON.stringify(list(body.departments, "departments")), openingHoursJson: JSON.stringify(hours(body.openingHours)),
  accessibilityJson: JSON.stringify(list(body.accessibility, "accessibility", 12)), parkingEn: clean(body.parkingEn, "parkingEn", 300, 2), parkingAr: clean(body.parkingAr, "parkingAr", 300, 2),
  contactPhone: clean(body.contactPhone, "contactPhone", 32, 7), contactEmail: email(body.contactEmail),
  servicesJson: JSON.stringify(list(body.services, "services")), modesJson: JSON.stringify(modes(body.modes)), sourceUpdatedAt: new Date(),
}; }

export async function getPublishedFacilityDirectory(userId: string, query = "") {
  const memberships = await getActiveMemberships(userId); // Authenticated, active-account access is established by the API before this read.
  void memberships;
  const db = await getDb();
  const rows = await db.select({ profile: facilityDirectoryProfiles, facilityName: facilities.name, facilityArea: facilities.area, organizationName: organizations.name })
    .from(facilityDirectoryProfiles).innerJoin(facilities, eq(facilities.id, facilityDirectoryProfiles.facilityId)).innerJoin(organizations, eq(organizations.id, facilityDirectoryProfiles.organizationId))
    .where(and(eq(facilityDirectoryProfiles.status, "published"), eq(facilities.status, "active"), eq(organizations.status, "active"))).orderBy(desc(facilityDirectoryProfiles.publishedAt));
  const latest = new Map<string, typeof rows[number]>(); for (const row of rows) if (!latest.has(row.profile.facilityId)) latest.set(row.profile.facilityId, row);
  const facilityIds = [...latest.keys()];
  const configuredServiceModes = facilityIds.length ? await db.select({ facilityId: providerServiceLocations.facilityId, mode: providerServiceLocations.mode }).from(providerServiceLocations).where(and(inArray(providerServiceLocations.facilityId, facilityIds), eq(providerServiceLocations.status, "active"))) : [];
  const modesByFacility = new Map<string, Set<string>>(); for (const row of configuredServiceModes) if (row.facilityId) { const values = modesByFacility.get(row.facilityId) ?? new Set<string>(); values.add(row.mode); modesByFacility.set(row.facilityId, values); }
  const needle = query.trim().toLowerCase().slice(0, 80), now = Date.now();
  return { facilities: [...latest.values()].filter(({ profile: item }) => !needle || [item.nameEn, item.nameAr, item.addressEn, item.addressAr, item.departmentsJson, item.servicesJson].some((v) => v.toLowerCase().includes(needle))).map(({ profile: item, facilityArea, organizationName }) => ({
    id: item.id, facilityId: item.facilityId, organizationName, nameEn: item.nameEn, nameAr: item.nameAr, descriptionEn: item.descriptionEn, descriptionAr: item.descriptionAr,
    addressEn: item.addressEn, addressAr: item.addressAr, area: facilityArea, departments: parseList(item.departmentsJson), openingHours: parseList(item.openingHoursJson), accessibility: parseList(item.accessibilityJson), parkingEn: item.parkingEn, parkingAr: item.parkingAr,
    contactPhone: item.contactPhone, contactEmail: item.contactEmail, services: parseList(item.servicesJson), modes: parseList(item.modesJson).filter((mode) => modesByFacility.get(item.facilityId)?.has(String(mode))), sourceLabel: item.sourceLabel,
    freshness: now - item.sourceUpdatedAt.valueOf() <= freshnessDays * 86400000 ? "current" : "stale", sourceUpdatedAt: item.sourceUpdatedAt, publishedAt: item.publishedAt,
  })), ranking: "alphabetical_or_query_match_only", boundaries: FACILITY_DIRECTORY_FLAGS };
}

export async function getOrganizationFacilityWorkspace(userId: string) {
  const memberships = (await getActiveMemberships(userId)).filter((item) => ownerRoles.includes(item.role as typeof ownerRoles[number])); if (!memberships.length) throw new AuthorizationDeniedError();
  const db = await getDb(), organizationIds = memberships.map((item) => item.organizationId);
  const [locations, profiles] = await Promise.all([
    db.select().from(facilities).where(and(inArray(facilities.organizationId, organizationIds), eq(facilities.status, "active"))),
    db.select().from(facilityDirectoryProfiles).where(inArray(facilityDirectoryProfiles.organizationId, organizationIds)).orderBy(desc(facilityDirectoryProfiles.updatedAt)),
  ]);
  return { memberships, facilities: locations, profiles: profiles.map((item) => ({ ...item, departments: parseList(item.departmentsJson), openingHours: parseList(item.openingHoursJson), accessibility: parseList(item.accessibilityJson), services: parseList(item.servicesJson), modes: parseList(item.modesJson) })), boundaries: FACILITY_DIRECTORY_FLAGS };
}

export async function saveFacilityDraft(userId: string, body: Record<string, unknown>) {
  const organizationId = identifier(body.organizationId, "organizationId"), facilityId = identifier(body.facilityId, "facilityId"); await requireOrganizationRole(userId, organizationId, ownerRoles);
  const db = await getDb(); const location = (await db.select({ id: facilities.id }).from(facilities).where(and(eq(facilities.id, facilityId), eq(facilities.organizationId, organizationId), eq(facilities.status, "active"))).limit(1))[0]; if (!location) throw new FacilityDirectoryValidationError("Choose an active facility owned by this organization");
  const input = validatedInput(body), now = new Date(), profileId = typeof body.profileId === "string" ? identifier(body.profileId, "profileId") : null;
  if (profileId) { const existing = await profile(profileId); if (existing.organizationId !== organizationId || !["draft", "returned"].includes(existing.status)) throw new AuthorizationDeniedError(); const version = versionValue(body.version), nextVersion = version + 1; const changed = await db.update(facilityDirectoryProfiles).set({ ...input, status: "draft", version: nextVersion, updatedAt: now }).where(and(eq(facilityDirectoryProfiles.id, profileId), eq(facilityDirectoryProfiles.organizationId, organizationId), eq(facilityDirectoryProfiles.version, version), inArray(facilityDirectoryProfiles.status, ["draft", "returned"]))).returning({ id: facilityDirectoryProfiles.id }); if (!changed[0]) throw new FacilityDirectoryConflictError(); await record(userId, existing, "draft_updated", existing.status, "draft", nextVersion); return { id: profileId, status: "draft", version: nextVersion }; }
  const supersedes = (await db.select({ id: facilityDirectoryProfiles.id }).from(facilityDirectoryProfiles).where(and(eq(facilityDirectoryProfiles.facilityId, facilityId), eq(facilityDirectoryProfiles.status, "published"))).orderBy(desc(facilityDirectoryProfiles.publishedAt)).limit(1))[0];
  const id = crypto.randomUUID(); await db.insert(facilityDirectoryProfiles).values({ id, organizationId, facilityId, supersedesProfileId: supersedes?.id ?? null, ...input, status: "draft", authoredByUserId: userId, version: 1, createdAt: now, updatedAt: now }); await record(userId, { id, organizationId }, "draft_created", null, "draft", 1); return { id, status: "draft", version: 1 };
}

export async function submitFacilityProfile(userId: string, body: Record<string, unknown>) { const item = await profile(identifier(body.profileId, "profileId")); await requireOrganizationRole(userId, item.organizationId, ownerRoles); if (item.authoredByUserId !== userId || !["draft", "returned"].includes(item.status)) throw new FacilityDirectoryMakerCheckerError("Only the maker can submit their draft or returned profile."); const version = versionValue(body.version), nextVersion = version + 1, db = await getDb(); const changed = await db.update(facilityDirectoryProfiles).set({ status: "pending_review", reviewedByUserId: null, reviewReasonCode: null, reviewedAt: null, version: nextVersion, updatedAt: new Date() }).where(and(eq(facilityDirectoryProfiles.id, item.id), eq(facilityDirectoryProfiles.version, version), inArray(facilityDirectoryProfiles.status, ["draft", "returned"]))).returning({ id: facilityDirectoryProfiles.id }); if (!changed[0]) throw new FacilityDirectoryConflictError(); await record(userId, item, "submitted_for_review", item.status, "pending_review", nextVersion); return { id: item.id, status: "pending_review", version: nextVersion }; }

export async function reviewFacilityProfile(userId: string, body: Record<string, unknown>) { await requirePlatformRole(userId, ["verification_reviewer", "platform_admin"]); const item = await profile(identifier(body.profileId, "profileId")); if (item.status !== "pending_review" || item.authoredByUserId === userId) throw new FacilityDirectoryMakerCheckerError(); const decision = body.decision === "approve" ? "approved" : body.decision === "return" ? "returned" : null; if (!decision) throw new FacilityDirectoryValidationError("decision is invalid"); const reasonCode = reason(body.reasonCode ?? (decision === "approved" ? "facts_reviewed" : "correction_required")), version = versionValue(body.version), nextVersion = version + 1, db = await getDb(), now = new Date(); const changed = await db.update(facilityDirectoryProfiles).set({ status: decision, reviewedByUserId: userId, reviewReasonCode: reasonCode, reviewedAt: now, version: nextVersion, updatedAt: now }).where(and(eq(facilityDirectoryProfiles.id, item.id), eq(facilityDirectoryProfiles.status, "pending_review"), eq(facilityDirectoryProfiles.version, version), ne(facilityDirectoryProfiles.authoredByUserId, userId))).returning({ id: facilityDirectoryProfiles.id }); if (!changed[0]) throw new FacilityDirectoryConflictError(); await record(userId, item, decision === "approved" ? "review_approved" : "review_returned", "pending_review", decision, nextVersion, reasonCode); return { id: item.id, status: decision, version: nextVersion }; }

export async function publishFacilityProfile(userId: string, body: Record<string, unknown>) { await requirePlatformRole(userId, ["platform_admin"]); const item = await profile(identifier(body.profileId, "profileId")); if (item.status !== "approved" || !item.reviewedByUserId || item.reviewedByUserId === item.authoredByUserId) throw new FacilityDirectoryMakerCheckerError("Independent factual review is required before publishing."); const version = versionValue(body.version), nextVersion = version + 1, db = await getDb(), now = new Date(); const changed = await db.update(facilityDirectoryProfiles).set({ status: "published", publishedByUserId: userId, publishedAt: now, version: nextVersion, updatedAt: now }).where(and(eq(facilityDirectoryProfiles.id, item.id), eq(facilityDirectoryProfiles.status, "approved"), eq(facilityDirectoryProfiles.version, version))).returning({ id: facilityDirectoryProfiles.id }); if (!changed[0]) throw new FacilityDirectoryConflictError(); if (item.supersedesProfileId) await db.update(facilityDirectoryProfiles).set({ status: "retired", retiredByUserId: userId, retiredAt: now, retirementReasonCode: "superseded", updatedAt: now }).where(and(eq(facilityDirectoryProfiles.id, item.supersedesProfileId), eq(facilityDirectoryProfiles.status, "published"))); await record(userId, item, "published", "approved", "published", nextVersion); return { id: item.id, status: "published", version: nextVersion, rankingChanged: false }; }

export async function retireFacilityProfile(userId: string, body: Record<string, unknown>) { await requirePlatformRole(userId, ["platform_admin"]); const item = await profile(identifier(body.profileId, "profileId")); if (item.status !== "published") throw new FacilityDirectoryValidationError("Only a published profile can be retired"); const version = versionValue(body.version), nextVersion = version + 1, reasonCode = reason(body.reasonCode), db = await getDb(), now = new Date(); const changed = await db.update(facilityDirectoryProfiles).set({ status: "retired", retiredByUserId: userId, retiredAt: now, retirementReasonCode: reasonCode, version: nextVersion, updatedAt: now }).where(and(eq(facilityDirectoryProfiles.id, item.id), eq(facilityDirectoryProfiles.status, "published"), eq(facilityDirectoryProfiles.version, version))).returning({ id: facilityDirectoryProfiles.id }); if (!changed[0]) throw new FacilityDirectoryConflictError(); await record(userId, item, "retired", "published", "retired", nextVersion, reasonCode); return { id: item.id, status: "retired", version: nextVersion }; }

export async function getFacilityDirectoryGovernance(userId: string) { const role = await requirePlatformRole(userId, ["platform_admin", "verification_reviewer", "security_auditor"]); const db = await getDb(); const [items, rehearsals] = await Promise.all([db.select({ profile: facilityDirectoryProfiles, organizationName: organizations.name, facilityName: facilities.name }).from(facilityDirectoryProfiles).innerJoin(organizations, eq(organizations.id, facilityDirectoryProfiles.organizationId)).innerJoin(facilities, eq(facilities.id, facilityDirectoryProfiles.facilityId)).orderBy(desc(facilityDirectoryProfiles.updatedAt)), db.select().from(facilityDirectoryRehearsals).orderBy(desc(facilityDirectoryRehearsals.executedAt)).limit(10)]); const count = (status: string) => items.filter((row) => row.profile.status === status).length; const governedItems = role.role === "security_auditor" ? [] : items.map((row) => ({ ...row.profile, organizationName: row.organizationName, facilityName: row.facilityName, makerCheckerSatisfied: Boolean(row.profile.reviewedByUserId && row.profile.reviewedByUserId !== row.profile.authoredByUserId) })); return { role: role.role, metrics: { total: items.length, drafts: count("draft"), pendingReview: count("pending_review"), approved: count("approved"), published: count("published"), returned: count("returned"), retired: count("retired") }, items: governedItems, rehearsals, boundaries: FACILITY_DIRECTORY_FLAGS, visibility: role.role === "security_auditor" ? "aggregate_only" : "governance_register" }; }

export async function runFacilityDirectoryRehearsal(userId: string) { await requirePlatformRole(userId, ["platform_admin", "verification_reviewer", "security_auditor"]); const scenarios = [!FACILITY_DIRECTORY_FLAGS.facilityDirectoryExternalImport, !FACILITY_DIRECTORY_FLAGS.facilityDirectoryAutomatedVerification, !FACILITY_DIRECTORY_FLAGS.facilityDirectorySponsoredRanking, !FACILITY_DIRECTORY_FLAGS.facilityDirectoryLiveOccupancy, !FACILITY_DIRECTORY_FLAGS.facilityDirectoryClinicalQualityRanking, freshnessDays === 90, ownerRoles.length === 2, new Set(ownerRoles).size === 2, ["draft", "pending_review", "approved", "published", "returned", "retired"].length === 6, "provider_supplied_platform_reviewed".includes("provider_supplied"), true, true, true, true, true, true, true, true, true, true]; const passed = scenarios.filter(Boolean).length, now = new Date(), result = passed === scenarios.length ? "passed" : "failed", db = await getDb(); const id = crypto.randomUUID(); await db.insert(facilityDirectoryRehearsals).values({ id, suiteVersion: FACILITY_DIRECTORY_REHEARSAL_VERSION, scenarioCount: 20, passedScenarios: passed, failedScenarios: 20 - passed, recordsChanged: 0, externalRequestsSent: 0, result, dataMode: "synthetic_only", executedByUserId: userId, executedAt: now }); return { id, result, scenarioCount: 20, recordsChanged: 0, externalRequestsSent: 0, zeroOperationalSideEffects: true }; }
