export const foundationFlags = {
  independentAuthentication: false,
  outboundEmailDelivery: false,
  outboundSmsDelivery: false,
  communicationsWebhooks: false,
  medicalDocumentUploads: false,
  documentScanCallbacks: false,
  documentDeletionProcessor: false,
  privateDocumentDelivery: false,
  documentUploadCleanup: false,
  documentScanRecovery: false,
  retentionAutomationExecution: false,
  externalSecurityAlertDelivery: false,
  externalObservabilityExport: false,
  pilotInvitationDelivery: false,
  pilotParticipantAcceptance: false,
  pilotAccessGrant: false,
  pilotParticipantLifecycle: false,
  realPilotFeedbackCollection: false,
  pilotLaunchRuntime: false,
  pilotCommandRuntime: false,
  careNavigatorModelAssistance: false,
  careNavigatorFreeText: false,
  careNavigatorRuleActivation: false,
  careNavigatorClinicalApproval: false,
  prescriptionOcrDispatch: false,
  prescriptionRecordCommit: false,
  reportReaderDispatch: false,
  reportReaderInterpretation: false,
  reportReaderRecordCommit: false,
  medicationReminderDelivery: false,
  medicationReminderOcrImport: false,
  medicationReminderOccurrenceMaterialization: false,
  medicationReminderDeliveryPolicyActivation: false,
  dependentCareAccess: false,
  dependentEmergencyAccess: false,
  ageOfMajorityTransition: false,
  virtualCareMediaRuntime: false,
  virtualCareExternalFallback: false,
  virtualCareClinicalProtocolActivation: false,
  careMessagingExternalDelivery: false,
  careMessagingAttachments: false,
  careMessagingClinicalAutomation: false,
  referralExternalDelivery: false,
  referralAutomatedRouting: false,
  referralClinicalRecordTransfer: false,
  patientExperiencePublicRatings: false,
  patientExperienceAutomatedProviderAction: false,
  patientExperienceExternalAnalyticsExport: false,
  waitlistAutomatedMatching: false,
  waitlistAutomaticBooking: false,
  waitlistExternalDelivery: false,
  laboratoryExternalLisIntegration: false,
  laboratoryExternalResultUpload: false,
  laboratoryAutomaticClinicalInterpretation: false,
  laboratoryAutomaticUrgentEscalation: false,
  homeCareIndependentMarketplace: false,
  homeCareExternalDelivery: false,
  homeCareLiveLocationTracking: false,
  homeCareAutomaticAssignment: false,
  encounterNoteOverwrite: false,
  encounterExternalClinicalDelivery: false,
  pharmacyAutomaticRefillApproval: false,
  pharmacyUncertainOcrActions: false,
  pharmacyInventoryIntegration: false,
  pharmacyControlledDrugSystem: false,
  pharmacyPaymentIntegration: false,
  pharmacyCourierTracking: false,
  pharmacyExternalIntegration: false,
  sampleCollectionLocationTracking: false,
  sampleCollectionExternalCourier: false,
  sampleCollectionAutomaticAssignment: false,
  sampleCollectionAutomaticResultInterpretation: false,
  sampleCollectionCriticalResultSubstitution: false,
} as const;

export function assertFoundationCapabilityDisabled(capability: keyof typeof foundationFlags) {
  if (foundationFlags[capability]) {
    throw new Error(`Foundation capability ${capability} requires an approved activation review.`);
  }
}
