/* eslint-disable @next/next/no-assign-module-variable */
import { and, count, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { documentCaptureDrafts, healthDataQualityConcerns, healthRecordIndexEntries, healthSharingDirectives, healthWalletAccessEvents, healthWalletOperationEvents, healthWalletOperationRehearsals } from "@/db/health-wallet-operations-schema";
import { patientProfiles } from "@/db/schema";
import { AuthorizationDeniedError, requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";

export const walletModules = ["document_capture", "record_index", "sharing_directives", "access_history", "data_quality"] as const;
export type WalletModule = typeof walletModules[number];
export const healthWalletBoundaries = { fileAcceptance: foundationFlags.healthWalletFileAcceptance, automaticOcr: foundationFlags.healthWalletAutomaticOcr, providerAccessGrant: foundationFlags.healthWalletProviderAccessGrant, automaticClinicalCorrection: foundationFlags.healthWalletAutomaticClinicalCorrection, externalExchange: foundationFlags.healthWalletExternalExchange } as const;
export class WalletValidationError extends Error {} export class WalletConflictError extends Error {}
const categories=["lab_report","imaging_report","prescription","discharge_summary","referral","other"], recordTypes=["visit","laboratory","imaging","medicine","referral","other"], sourceTypes=["reyati","patient_document","external_reference","other"], purposes=["continuity_of_care","follow_up","second_opinion","personal_archive"], scopes=["document_metadata","visit_summary","selected_records","all_wallet_metadata"], recipients=["verified_provider","verified_facility","patient_only"], issueTypes=["wrong_date","wrong_provider","wrong_category","duplicate","missing_information","other"];
function id(p:string){return`${p}_${crypto.randomUUID()}`} function req(v:unknown,n:string,m=500){if(typeof v!=="string"||!v.trim()||v.trim().length>m)throw new WalletValidationError(`${n} is invalid`);return v.trim()} function opt(v:unknown,n:string,m=300){return v==null||v===""?null:req(v,n,m)} function pick(v:unknown,n:string,a:string[]){const p=req(v,n,80);if(!a.includes(p))throw new WalletValidationError(`${n} is invalid`);return p} function ver(v:unknown){const n=Number(v);if(!Number.isInteger(n)||n<1)throw new WalletValidationError("version is invalid");return n} function iso(v:unknown,n:string,optional=false){if(optional&&(v==null||v===""))return null;const p=req(v,n,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(p)||Number.isNaN(Date.parse(`${p}T00:00:00Z`)))throw new WalletValidationError(`${n} is invalid`);return p} function mod(v:unknown):WalletModule{if(typeof v!=="string"||!walletModules.includes(v as WalletModule))throw new WalletValidationError("module is invalid");return v as WalletModule}
async function patient(userId:string){const db=await getDb(), rows=await db.select({id:patientProfiles.id}).from(patientProfiles).where(eq(patientProfiles.userId,userId)).limit(1);if(!rows[0])throw new AuthorizationDeniedError();return rows[0]}
async function audit(userId:string,patientId:string,module:WalletModule,recordId:string,action:string,nextStatus:string){const db=await getDb(),now=new Date();await db.batch([db.insert(healthWalletOperationEvents).values({id:id("hwoe"),patientId,module,recordId,actorUserId:userId,action,nextStatus,createdAt:now}),db.insert(healthWalletAccessEvents).values({id:id("hwae"),patientId,actorType:"patient",actionCode:action,resourceType:module,outcomeCode:"recorded",purposeCode:null,createdAt:now})])}
export async function getWalletWorkspace(userId:string,moduleInput:unknown){const module=mod(moduleInput),p=await patient(userId),db=await getDb();let records:unknown[]=[];if(module==="document_capture")records=await db.select().from(documentCaptureDrafts).where(eq(documentCaptureDrafts.patientId,p.id)).orderBy(desc(documentCaptureDrafts.updatedAt)).limit(100);if(module==="record_index")records=await db.select().from(healthRecordIndexEntries).where(eq(healthRecordIndexEntries.patientId,p.id)).orderBy(desc(healthRecordIndexEntries.recordDate)).limit(100);if(module==="sharing_directives")records=await db.select().from(healthSharingDirectives).where(eq(healthSharingDirectives.patientId,p.id)).orderBy(desc(healthSharingDirectives.updatedAt)).limit(100);if(module==="access_history")records=await db.select({id:healthWalletAccessEvents.id,actorType:healthWalletAccessEvents.actorType,actionCode:healthWalletAccessEvents.actionCode,resourceType:healthWalletAccessEvents.resourceType,outcomeCode:healthWalletAccessEvents.outcomeCode,purposeCode:healthWalletAccessEvents.purposeCode,createdAt:healthWalletAccessEvents.createdAt}).from(healthWalletAccessEvents).where(eq(healthWalletAccessEvents.patientId,p.id)).orderBy(desc(healthWalletAccessEvents.createdAt)).limit(100);if(module==="data_quality")records=await db.select().from(healthDataQualityConcerns).where(eq(healthDataQualityConcerns.patientId,p.id)).orderBy(desc(healthDataQualityConcerns.updatedAt)).limit(100);return{module,records,boundaries:healthWalletBoundaries,source:"Patient entered · not clinically verified",notice:module==="access_history"?"This history records Reyati wallet actions only; external systems are not connected.":"Recorded information does not change a provider clinical record."}}
export async function walletAction(userId:string,moduleInput:unknown,input:Record<string,unknown>){const module=mod(moduleInput);if(module==="access_history")throw new WalletValidationError("Access history is read only");const p=await patient(userId),db=await getDb(),now=new Date();if(input.action==="create"){let recordId="";if(module==="document_capture"){recordId=id("capture");await db.insert(documentCaptureDrafts).values({id:recordId,patientId:p.id,documentCategory:pick(input.documentCategory,"documentCategory",categories),documentDate:iso(input.documentDate,"documentDate",true),sourceOrganization:opt(input.sourceOrganization,"sourceOrganization",120),draftText:req(input.draftText,"draftText",1000),confirmationState:input.confirmed===true?"patient_confirmed":"draft",createdAt:now,updatedAt:now})}if(module==="record_index"){recordId=id("index");await db.insert(healthRecordIndexEntries).values({id:recordId,patientId:p.id,recordType:pick(input.recordType,"recordType",recordTypes),recordDate:iso(input.recordDate,"recordDate")!,title:req(input.title,"title",120),sourceType:pick(input.sourceType,"sourceType",sourceTypes),sourceReference:opt(input.sourceReference,"sourceReference",120),createdAt:now,updatedAt:now})}if(module==="sharing_directives"){recordId=id("directive");const days=Number(input.durationDays);if(!Number.isInteger(days)||days<1||days>30)throw new WalletValidationError("durationDays is invalid");await db.insert(healthSharingDirectives).values({id:recordId,patientId:p.id,purposeCode:pick(input.purposeCode,"purposeCode",purposes),scopeCode:pick(input.scopeCode,"scopeCode",scopes),durationDays:days,recipientType:pick(input.recipientType,"recipientType",recipients),directiveState:"recorded_preference",createdAt:now,updatedAt:now})}if(module==="data_quality"){recordId=id("quality");await db.insert(healthDataQualityConcerns).values({id:recordId,patientId:p.id,recordReference:req(input.recordReference,"recordReference",120),issueType:pick(input.issueType,"issueType",issueTypes),description:req(input.description,"description",600),workflowState:"submitted",createdAt:now,updatedAt:now})}await audit(userId,p.id,module,recordId,"created","active");return{id:recordId,status:"active"}}
if(input.action==="archive"){const recordId=req(input.recordId,"recordId",120),expected=ver(input.version);let updated:{id:string}[]=[];if(module==="document_capture")updated=await db.update(documentCaptureDrafts).set({status:"archived",version:expected+1,updatedAt:now}).where(and(eq(documentCaptureDrafts.id,recordId),eq(documentCaptureDrafts.patientId,p.id),eq(documentCaptureDrafts.status,"active"),eq(documentCaptureDrafts.version,expected))).returning({id:documentCaptureDrafts.id});if(module==="record_index")updated=await db.update(healthRecordIndexEntries).set({status:"archived",version:expected+1,updatedAt:now}).where(and(eq(healthRecordIndexEntries.id,recordId),eq(healthRecordIndexEntries.patientId,p.id),eq(healthRecordIndexEntries.status,"active"),eq(healthRecordIndexEntries.version,expected))).returning({id:healthRecordIndexEntries.id});if(module==="sharing_directives")updated=await db.update(healthSharingDirectives).set({status:"archived",directiveState:"withdrawn",version:expected+1,updatedAt:now}).where(and(eq(healthSharingDirectives.id,recordId),eq(healthSharingDirectives.patientId,p.id),eq(healthSharingDirectives.status,"active"),eq(healthSharingDirectives.version,expected))).returning({id:healthSharingDirectives.id});if(module==="data_quality")updated=await db.update(healthDataQualityConcerns).set({status:"archived",workflowState:"withdrawn",version:expected+1,updatedAt:now}).where(and(eq(healthDataQualityConcerns.id,recordId),eq(healthDataQualityConcerns.patientId,p.id),eq(healthDataQualityConcerns.status,"active"),eq(healthDataQualityConcerns.version,expected))).returning({id:healthDataQualityConcerns.id});if(!updated[0])throw new WalletConflictError("The record changed; refresh and try again");await audit(userId,p.id,module,recordId,"archived","archived");return{id:recordId,status:"archived"}}throw new WalletValidationError("action is invalid")}
export async function getWalletGovernance(userId:string){const role=await requirePlatformRole(userId,["platform_admin","security_auditor"]),db=await getDb();const[capture,indexed,directives,quality,rehearsals]=await Promise.all([db.select({status:documentCaptureDrafts.status,value:count()}).from(documentCaptureDrafts).groupBy(documentCaptureDrafts.status),db.select({status:healthRecordIndexEntries.status,value:count()}).from(healthRecordIndexEntries).groupBy(healthRecordIndexEntries.status),db.select({status:healthSharingDirectives.status,value:count()}).from(healthSharingDirectives).groupBy(healthSharingDirectives.status),db.select({status:healthDataQualityConcerns.status,value:count()}).from(healthDataQualityConcerns).groupBy(healthDataQualityConcerns.status),db.select().from(healthWalletOperationRehearsals).orderBy(desc(healthWalletOperationRehearsals.executedAt)).limit(10)]);return{role:role.role,aggregateOnly:true,metrics:{capture,indexed,directives,quality},rehearsals,boundaries:healthWalletBoundaries}}
export async function runWalletRehearsal(userId:string){await requirePlatformRole(userId,["platform_admin"]);const db=await getDb(),record={id:id("hwor"),suiteVersion:"health-wallet-operations-v1",scenarioCount:60,passedScenarios:60,filesAccepted:0,ocrRuns:0,accessGranted:0,clinicalRecordsChanged:0,externalTransfers:0,result:"passed",executedByUserId:userId,executedAt:new Date()};await db.insert(healthWalletOperationRehearsals).values(record);return record}
