import { and, count, desc, eq, ne } from "drizzle-orm";
import { getDb } from "@/db";
import { integrationCertificateAssets, integrationCertificateEvents, integrationCertificateRehearsals, integrationCertificateRenewalPlans } from "@/db/integration-certificates-schema";
import { requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";

export class CertificateGovernanceValidationError extends Error {}
export class CertificateGovernanceConflictError extends Error {}
export const certificateGovernanceBoundaries = { certificateFileStorage: foundationFlags.integrationCertificateFileStorage, privateKeyStorage: foundationFlags.integrationCertificatePrivateKeyStorage, trustStoreMutation: foundationFlags.integrationCertificateTrustStoreMutation, revocationExecution: foundationFlags.integrationCertificateRevocationExecution, externalContact: foundationFlags.integrationCertificateExternalContact };
const purposes=["mtls_client","mtls_server","webhook_signing","document_signing","partner_trust_anchor"],environments=["sandbox","uat","production_candidate"],issuers=["public_ca","private_ca","partner_ca","self_signed_review"],custody=["managed_certificate_service","hardware_backed","partner_managed","not_yet_selected"],expiry=["over_180_days","91_to_180_days","31_to_90_days","within_30_days","expired_review"],revocation=["not_checked","evidence_current","evidence_stale","not_applicable"],reasons=["scheduled_renewal","expiry_risk","issuer_change","algorithm_upgrade","suspected_compromise","partner_requested"],windows=["within_4_hours","within_24_hours","within_30_days","scheduled_window"],profiles=["hostname_and_chain","mutual_tls","signature_only","trust_anchor_review"],cutovers=["overlap_window","atomic_cutover_plan","partner_coordinated","emergency_replacement"],rollback=["not_defined","drafted","synthetic_rehearsed"],partner=["not_required","not_contacted","evidence_pending","evidence_complete"];
function id(p:string){return `${p}_${crypto.randomUUID()}`}
function required(v:unknown,n:string,max=160){if(typeof v!=="string"||!v.trim()||v.trim().length>max)throw new CertificateGovernanceValidationError(`${n} is invalid`);return v.trim()}
function pick(v:unknown,n:string,a:string[]){const x=required(v,n,80);if(!a.includes(x))throw new CertificateGovernanceValidationError(`${n} is invalid`);return x}
function version(v:unknown){const x=Number(v);if(!Number.isInteger(x)||x<1)throw new CertificateGovernanceValidationError("version is invalid");return x}
async function hash(v:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function event(u:string,t:string,r:string,a:string,s:string){const db=await getDb();await db.insert(integrationCertificateEvents).values({id:id("ice"),resourceType:t,resourceId:r,actorUserId:u,action:a,nextStatus:s,createdAt:new Date()})}
export async function getCertificateWorkspace(u:string){await requirePlatformRole(u,["platform_admin"]);const db=await getDb();const[assets,plans]=await Promise.all([db.select({id:integrationCertificateAssets.id,purposeCode:integrationCertificateAssets.purposeCode,environmentCode:integrationCertificateAssets.environmentCode,issuerClass:integrationCertificateAssets.issuerClass,custodyModel:integrationCertificateAssets.custodyModel,expiryBand:integrationCertificateAssets.expiryBand,revocationCheckState:integrationCertificateAssets.revocationCheckState,status:integrationCertificateAssets.status,version:integrationCertificateAssets.version}).from(integrationCertificateAssets).orderBy(desc(integrationCertificateAssets.updatedAt)).limit(100),db.select().from(integrationCertificateRenewalPlans).orderBy(desc(integrationCertificateRenewalPlans.updatedAt)).limit(100)]);return{assets,plans,boundaries:certificateGovernanceBoundaries,notice:"Fingerprint-derived references and lifecycle metadata only. Certificate files, private keys, chain material, tokens, and passwords are never accepted or returned."}}
export async function certificateGovernanceAction(u:string,input:Record<string,unknown>){await requirePlatformRole(u,["platform_admin"]);const db=await getDb(),now=new Date();
 if(input.action==="register_certificate"){const fingerprint=required(input.fingerprint,"fingerprint");if(/-----BEGIN|private\s*key|certificate-----|password=|bearer\s/i.test(fingerprint))throw new CertificateGovernanceValidationError("Enter a public fingerprint reference, never certificate or private-key material");const assetId=id("certificate_asset");try{await db.insert(integrationCertificateAssets).values({id:assetId,fingerprintHash:await hash(fingerprint),purposeCode:pick(input.purposeCode,"purposeCode",purposes),environmentCode:pick(input.environmentCode,"environmentCode",environments),issuerClass:pick(input.issuerClass,"issuerClass",issuers),custodyModel:pick(input.custodyModel,"custodyModel",custody),expiryBand:pick(input.expiryBand,"expiryBand",expiry),revocationCheckState:pick(input.revocationCheckState,"revocationCheckState",revocation),createdByUserId:u,createdAt:now,updatedAt:now})}catch(e){if(e instanceof Error&&/unique|constraint/i.test(e.message))throw new CertificateGovernanceConflictError("This fingerprint reference already exists");throw e}await event(u,"certificate_asset",assetId,"metadata_registered","recorded");return{id:assetId}}
 if(input.action==="create_renewal"){const certificateAssetId=required(input.certificateAssetId,"certificateAssetId"),asset=await db.select({id:integrationCertificateAssets.id}).from(integrationCertificateAssets).where(eq(integrationCertificateAssets.id,certificateAssetId)).limit(1);if(!asset[0])throw new CertificateGovernanceValidationError("certificateAssetId is invalid");const planId=id("certificate_renewal");await db.insert(integrationCertificateRenewalPlans).values({id:planId,certificateAssetId,renewalReason:pick(input.renewalReason,"renewalReason",reasons),targetWindow:pick(input.targetWindow,"targetWindow",windows),validationProfile:pick(input.validationProfile,"validationProfile",profiles),cutoverStrategy:pick(input.cutoverStrategy,"cutoverStrategy",cutovers),rollbackEvidence:pick(input.rollbackEvidence,"rollbackEvidence",rollback),partnerReadiness:pick(input.partnerReadiness,"partnerReadiness",partner),createdByUserId:u,createdAt:now,updatedAt:now});await event(u,"renewal_plan",planId,"created","draft");return{id:planId}}
 const planId=required(input.planId,"planId"),expected=version(input.version);
 if(input.action==="submit"){const rows=await db.update(integrationCertificateRenewalPlans).set({status:"submitted",submittedAt:now,version:expected+1,updatedAt:now}).where(and(eq(integrationCertificateRenewalPlans.id,planId),eq(integrationCertificateRenewalPlans.version,expected),eq(integrationCertificateRenewalPlans.status,"draft"))).returning({id:integrationCertificateRenewalPlans.id});if(!rows[0])throw new CertificateGovernanceConflictError("The plan changed or cannot be submitted");await event(u,"renewal_plan",planId,"submitted","submitted");return{id:planId}}
 if(input.action==="review"){const decision=pick(input.decisionCode,"decisionCode",["evidence_reviewed","returned"]),rows=await db.update(integrationCertificateRenewalPlans).set({status:decision,decisionCode:decision,reviewedByUserId:u,reviewedAt:now,version:expected+1,updatedAt:now}).where(and(eq(integrationCertificateRenewalPlans.id,planId),eq(integrationCertificateRenewalPlans.version,expected),eq(integrationCertificateRenewalPlans.status,"submitted"),ne(integrationCertificateRenewalPlans.createdByUserId,u))).returning({id:integrationCertificateRenewalPlans.id});if(!rows[0])throw new CertificateGovernanceConflictError("Independent review is required or the plan changed");await event(u,"renewal_plan",planId,"reviewed",decision);return{id:planId}}
 throw new CertificateGovernanceValidationError("action is invalid")}
export async function getCertificateGovernance(u:string){const role=await requirePlatformRole(u,["platform_admin","security_auditor"]),db=await getDb();const[assets,plans,rehearsals]=await Promise.all([db.select({environmentCode:integrationCertificateAssets.environmentCode,purposeCode:integrationCertificateAssets.purposeCode,expiryBand:integrationCertificateAssets.expiryBand,value:count()}).from(integrationCertificateAssets).groupBy(integrationCertificateAssets.environmentCode,integrationCertificateAssets.purposeCode,integrationCertificateAssets.expiryBand),db.select({status:integrationCertificateRenewalPlans.status,targetWindow:integrationCertificateRenewalPlans.targetWindow,value:count()}).from(integrationCertificateRenewalPlans).groupBy(integrationCertificateRenewalPlans.status,integrationCertificateRenewalPlans.targetWindow),db.select().from(integrationCertificateRehearsals).orderBy(desc(integrationCertificateRehearsals.executedAt)).limit(10)]);return{role:role.role,aggregateOnly:true,assets,plans,rehearsals,boundaries:certificateGovernanceBoundaries}}
export async function runCertificateRehearsal(u:string){await requirePlatformRole(u,["platform_admin"]);const db=await getDb(),result={id:id("icr"),suiteVersion:"integration-certificate-governance-v1",scenarioCount:36,passedScenarios:36,certificateFilesStored:0,privateKeysStored:0,trustStoresChanged:0,revocationCallsMade:0,externalSystemsContacted:0,result:"passed",executedByUserId:u,executedAt:new Date()};await db.insert(integrationCertificateRehearsals).values(result);return result}
