import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, medicationReminderDeliveryConsentEvents, medicationReminderDeliveryConsents } from "@/db/schema";
import { foundationFlags } from "@/lib/foundation-flags";

export const MEDICATION_REMINDER_CONSENT_VERSION = "medication-reminder-consent-v1";
export const MEDICATION_REMINDER_CONSENT_BOUNDARIES = ["delivery_preference_only", "generic_lock_screen_wording", "no_clinical_verification", "withdraw_any_time"] as const;
export class MedicationReminderConsentValidationError extends Error { constructor(message: string) { super(message); this.name = "MedicationReminderConsentValidationError"; } }
export class MedicationReminderConsentConflictError extends Error { constructor() { super("Your reminder preference changed. Refresh and try again."); this.name = "MedicationReminderConsentConflictError"; } }
function version(value: unknown) { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 1) throw new MedicationReminderConsentValidationError("version is invalid"); return parsed; }
function locale(value: unknown) { if (value !== "en" && value !== "ar") throw new MedicationReminderConsentValidationError("locale is invalid"); return value; }

export async function getMedicationReminderConsent(userId: string) { const db = await getDb(), consent = (await db.select().from(medicationReminderDeliveryConsents).where(eq(medicationReminderDeliveryConsents.userId, userId)).limit(1))[0] ?? null, events = consent ? await db.select().from(medicationReminderDeliveryConsentEvents).where(eq(medicationReminderDeliveryConsentEvents.consentId, consent.id)).orderBy(desc(medicationReminderDeliveryConsentEvents.createdAt)).limit(100) : []; return { consent: consent ? { ...consent, acknowledgedBoundaries: JSON.parse(consent.acknowledgedBoundariesJson) as string[], events } : null, consentVersion: MEDICATION_REMINDER_CONSENT_VERSION, boundaries: MEDICATION_REMINDER_CONSENT_BOUNDARIES, deliveryEnabled: foundationFlags.medicationReminderDelivery, effect: "preference_only" as const }; }

export async function updateMedicationReminderConsent(userId: string, body: Record<string, unknown>) { const action = body.action; if (action !== "consent" && action !== "withdraw") throw new MedicationReminderConsentValidationError("action is invalid"); const selectedLocale = locale(body.locale), db = await getDb(), current = (await db.select().from(medicationReminderDeliveryConsents).where(eq(medicationReminderDeliveryConsents.userId, userId)).limit(1))[0], now = new Date(), nextStatus = action === "consent" ? "consented" : "withdrawn"; if (action === "consent" && (body.consentVersion !== MEDICATION_REMINDER_CONSENT_VERSION || body.acknowledgementAccepted !== true)) throw new MedicationReminderConsentValidationError("Current consent boundaries must be acknowledged"); if (action === "withdraw" && !current) throw new MedicationReminderConsentValidationError("No reminder delivery preference was found"); const id = current?.id ?? crypto.randomUUID(), previousStatus = current?.status ?? null; let nextVersion = 1;
  if (current) { const expected = version(body.version); const changed = await db.update(medicationReminderDeliveryConsents).set({ consentVersion: MEDICATION_REMINDER_CONSENT_VERSION, locale: selectedLocale, status: nextStatus, acknowledgedBoundariesJson: JSON.stringify(MEDICATION_REMINDER_CONSENT_BOUNDARIES), consentedAt: action === "consent" ? now : current.consentedAt, withdrawnAt: action === "withdraw" ? now : null, version: current.version + 1, updatedAt: now }).where(and(eq(medicationReminderDeliveryConsents.id, id), eq(medicationReminderDeliveryConsents.userId, userId), eq(medicationReminderDeliveryConsents.version, expected))).returning({ version: medicationReminderDeliveryConsents.version }); if (!changed[0]) throw new MedicationReminderConsentConflictError(); nextVersion = changed[0].version; }
  else await db.insert(medicationReminderDeliveryConsents).values({ id, userId, consentVersion: MEDICATION_REMINDER_CONSENT_VERSION, locale: selectedLocale, status: nextStatus, acknowledgedBoundariesJson: JSON.stringify(MEDICATION_REMINDER_CONSENT_BOUNDARIES), consentedAt: now, withdrawnAt: null, version: 1, createdAt: now, updatedAt: now });
  const note = action === "consent" ? "Patient recorded a future delivery preference; no reminder was sent." : "Patient withdrew the future delivery preference; no reminder was sent."; await db.batch([db.insert(medicationReminderDeliveryConsentEvents).values({ id: crypto.randomUUID(), consentId: id, actorUserId: userId, action, previousStatus, nextStatus, consentVersion: MEDICATION_REMINDER_CONSENT_VERSION, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: `medication_reminder_consent.${action}`, resourceType: "medication_reminder_delivery_consent", resourceId: id, outcome: "success", metadataJson: JSON.stringify({ previousStatus, nextStatus, preferenceOnly: true, deliveryEnabled: false, clinicalContentIncluded: false }), createdAt: now })]); return { id, status: nextStatus, version: nextVersion, deliveryEnabled: false, effect: "preference_only" as const }; }
