import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, medicationReminderEvents, medicationReminderPlans, medicationReminderTimes } from "@/db/schema";
import { foundationFlags } from "@/lib/foundation-flags";
export const MEDICATION_REMINDER_ACKNOWLEDGEMENT_VERSION="patient-entered-reminder-v1";
export class MedicationReminderValidationError extends Error{constructor(message:string){super(message);this.name="MedicationReminderValidationError";}}
export class MedicationReminderConflictError extends Error{constructor(){super("This reminder plan changed. Refresh and try again.");this.name="MedicationReminderConflictError";}}
function text(value:unknown,name:string,min:number,max:number){if(typeof value!=="string"||value.trim().length<min||value.trim().length>max)throw new MedicationReminderValidationError(`${name} is invalid`);return value.trim();}
function expectedVersion(value:unknown){const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed<1)throw new MedicationReminderValidationError("version is invalid");return parsed;}
function isoDate(value:unknown,name:string){const result=text(value,name,10,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(result)||Number.isNaN(Date.parse(`${result}T00:00:00Z`)))throw new MedicationReminderValidationError(`${name} is invalid`);return result;}
function localTime(value:unknown){const result=text(value,"time",5,5);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(result))throw new MedicationReminderValidationError("time is invalid");return result;}
function cleanClinicalLabel(value:unknown,name:string,max:number){const result=text(value,name,2,max);if(/[<>\r\n]/.test(result))throw new MedicationReminderValidationError(`${name} contains unsupported characters`);return result;}
function parseTimes(value:unknown){if(!Array.isArray(value)||value.length<1||value.length>6)throw new MedicationReminderValidationError("Choose between one and six reminder times");const times=[...new Set(value.map(localTime))].sort();if(times.length!==value.length)throw new MedicationReminderValidationError("Reminder times must be unique");return times;}
export async function getMedicationReminderWorkspace(userId:string){const db=await getDb();const[plans,times,events]=await Promise.all([db.select().from(medicationReminderPlans).where(eq(medicationReminderPlans.userId,userId)).orderBy(desc(medicationReminderPlans.createdAt)).limit(100),db.select().from(medicationReminderTimes).orderBy(medicationReminderTimes.localTime),db.select().from(medicationReminderEvents).where(eq(medicationReminderEvents.actorUserId,userId)).orderBy(desc(medicationReminderEvents.createdAt)).limit(300)]);return{deliveryEnabled:foundationFlags.medicationReminderDelivery,ocrImportEnabled:foundationFlags.medicationReminderOcrImport,timezone:"Asia/Qatar",acknowledgementVersion:MEDICATION_REMINDER_ACKNOWLEDGEMENT_VERSION,plans:plans.map(plan=>({...plan,times:times.filter(item=>item.planId===plan.id).map(item=>item.localTime),events:events.filter(item=>item.planId===plan.id)}))};}
export async function createMedicationReminderPlan(userId:string,body:Record<string,unknown>){if(body.sourceType!==undefined&&body.sourceType!=="patient_entered")throw new MedicationReminderValidationError("Only patient-entered plans are available");if(body.acknowledgementAccepted!==true)throw new MedicationReminderValidationError("You must acknowledge that Qivaya does not verify medication instructions");const medicationLabel=cleanClinicalLabel(body.medicationLabel,"medicationLabel",120),directionsLabel=cleanClinicalLabel(body.directionsLabel,"directionsLabel",240),startDate=isoDate(body.startDate,"startDate"),endDate=body.endDate?isoDate(body.endDate,"endDate"):null;if(endDate&&endDate<startDate)throw new MedicationReminderValidationError("End date cannot precede start date");const times=parseTimes(body.times),db=await getDb(),now=new Date(),id=crypto.randomUUID();await db.batch([db.insert(medicationReminderPlans).values({id,userId,medicationLabel,directionsLabel,sourceType:"patient_entered",sourceReference:"patient/manual-entry",verificationStatus:"unverified",timezone:"Asia/Qatar",startDate,endDate,status:"configured",acknowledgementVersion:MEDICATION_REMINDER_ACKNOWLEDGEMENT_VERSION,acknowledgedAt:now,version:1,createdAt:now,updatedAt:now}),...times.map(time=>db.insert(medicationReminderTimes).values({id:crypto.randomUUID(),planId:id,localTime:time,daysOfWeekJson:"[0,1,2,3,4,5,6]",createdAt:now})),db.insert(medicationReminderEvents).values({id:crypto.randomUUID(),planId:id,actorUserId:userId,action:"configure",previousStatus:null,nextStatus:"configured",note:"Patient-entered plan acknowledged; delivery remains disabled.",createdAt:now}),db.insert(auditEvents).values({id:crypto.randomUUID(),actorUserId:userId,organizationId:null,action:"medication_reminder.configured",resourceType:"medication_reminder_plan",resourceId:id,outcome:"success",metadataJson:JSON.stringify({sourceType:"patient_entered",verificationStatus:"unverified",timeCount:times.length,timezone:"Asia/Qatar",deliveryEnabled:false,clinicalContentIncluded:false}),createdAt:now})]);return{id,status:"configured",version:1,deliveryEnabled:false,verificationStatus:"unverified"};}
export async function transitionMedicationReminderPlan(userId:string,body:Record<string,unknown>){const planId=text(body.planId,"planId",1,128),action=text(body.action,"action",5,7),version=expectedVersion(body.version),db=await getDb();const current=(await db.select().from(medicationReminderPlans).where(and(eq(medicationReminderPlans.id,planId),eq(medicationReminderPlans.userId,userId))).limit(1))[0];if(!current)throw new MedicationReminderValidationError("Reminder plan was not found");let nextStatus:string;if(action==="pause"&&current.status==="configured")nextStatus="paused";else if(action==="resume"&&current.status==="paused")nextStatus="configured";else if(action==="archive"&&["configured","paused"].includes(current.status))nextStatus="archived";else throw new MedicationReminderValidationError("This reminder transition is not available");const now=new Date();const changed=await db.update(medicationReminderPlans).set({status:nextStatus,version:version+1,updatedAt:now}).where(and(eq(medicationReminderPlans.id,planId),eq(medicationReminderPlans.userId,userId),eq(medicationReminderPlans.status,current.status),eq(medicationReminderPlans.version,version))).returning({id:medicationReminderPlans.id});if(!changed[0])throw new MedicationReminderConflictError();await db.batch([db.insert(medicationReminderEvents).values({id:crypto.randomUUID(),planId,actorUserId:userId,action,previousStatus:current.status,nextStatus,note:`Patient changed plan state to ${nextStatus}; delivery remains disabled.`,createdAt:now}),db.insert(auditEvents).values({id:crypto.randomUUID(),actorUserId:userId,organizationId:null,action:`medication_reminder.${action}`,resourceType:"medication_reminder_plan",resourceId:planId,outcome:"success",metadataJson:JSON.stringify({previousStatus:current.status,nextStatus,deliveryEnabled:false,clinicalContentIncluded:false}),createdAt:now})]);return{id:planId,status:nextStatus,version:version+1,deliveryEnabled:false};}
export function assertMedicationReminderAutomationDisabled(){if(foundationFlags.medicationReminderDelivery||foundationFlags.medicationReminderOcrImport)throw new Error("Reminder automation requires a separate approved activation review");return{deliveryEnabled:false,ocrImportEnabled:false};}
