import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, medicationReminderDeliveryPolicies, medicationReminderDeliveryPolicyEvents, medicationReminderSchedulerRuns, platformRoles, users } from "@/db/schema";
import { requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";

export const REMINDER_DELIVERY_POLICY_VERSION = "reminder-delivery-policy-2026-08-16";
export const REMINDER_TEMPLATE_EN = "A reminder you configured may be due. Open Qivaya to review your plan.";
export const REMINDER_TEMPLATE_AR = "قد يكون موعد تذكير قمت بإعداده. افتح ريّاتي لمراجعة خطتك.";
export class ReminderDeliveryPolicyValidationError extends Error { constructor(message: string) { super(message); this.name = "ReminderDeliveryPolicyValidationError"; } }
export class ReminderDeliveryPolicyConflictError extends Error { constructor() { super("This reminder delivery policy changed. Refresh and try again."); this.name = "ReminderDeliveryPolicyConflictError"; } }
function text(value: unknown, name: string, min: number, max: number) { if (typeof value !== "string" || value.trim().length < min || value.trim().length > max) throw new ReminderDeliveryPolicyValidationError(`${name} is invalid`); return value.trim(); }
function integer(value: unknown, name: string, min: number, max: number) { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < min || parsed > max) throw new ReminderDeliveryPolicyValidationError(`${name} is invalid`); return parsed; }
function localTime(value: unknown, name: string) { const result = text(value, name, 5, 5); if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(result)) throw new ReminderDeliveryPolicyValidationError(`${name} is invalid`); return result; }
async function operators() { const db = await getDb(); return db.select({ userId: users.id, displayName: users.displayName, role: platformRoles.role }).from(platformRoles).innerJoin(users, eq(users.id, platformRoles.userId)).where(and(eq(platformRoles.status, "active"), inArray(platformRoles.role, ["platform_admin", "security_auditor"]))).orderBy(asc(users.displayName)); }
async function verifiedSchedulerEvidence() { const db = await getDb(); return (await db.select({ id: medicationReminderSchedulerRuns.id, executedAt: medicationReminderSchedulerRuns.executedAt, reviewedAt: medicationReminderSchedulerRuns.reviewedAt }).from(medicationReminderSchedulerRuns).where(and(eq(medicationReminderSchedulerRuns.result, "pass"), eq(medicationReminderSchedulerRuns.status, "verified"))).orderBy(desc(medicationReminderSchedulerRuns.reviewedAt)).limit(1))[0] ?? null; }

export async function getReminderDeliveryPolicyCentre(userId: string) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]), db = await getDb(), [policies, events, activeOperators, evidence] = await Promise.all([db.select().from(medicationReminderDeliveryPolicies).orderBy(desc(medicationReminderDeliveryPolicies.updatedAt)), db.select().from(medicationReminderDeliveryPolicyEvents).orderBy(desc(medicationReminderDeliveryPolicyEvents.createdAt)).limit(300), operators(), verifiedSchedulerEvidence()]); const names = new Map(activeOperators.map(item => [item.userId, item.displayName]));
  return { role: access.role, currentUserId: userId, policyVersion: REMINDER_DELIVERY_POLICY_VERSION, templateEn: REMINDER_TEMPLATE_EN, templateAr: REMINDER_TEMPLATE_AR, operators: activeOperators, verifiedSchedulerEvidence: evidence, activation: { policyEnabled: foundationFlags.medicationReminderDeliveryPolicyActivation, occurrenceMaterializationEnabled: foundationFlags.medicationReminderOccurrenceMaterialization, deliveryEnabled: foundationFlags.medicationReminderDelivery }, policies: policies.map(policy => ({ ...policy, retryBackoffMinutes: JSON.parse(policy.retryBackoffMinutesJson) as number[], primaryOwnerName: names.get(policy.primaryOwnerUserId) ?? "Unavailable owner", backupOwnerName: names.get(policy.backupOwnerUserId) ?? "Unavailable owner", reviewerName: policy.reviewerUserId ? names.get(policy.reviewerUserId) ?? "Unavailable reviewer" : null, events: events.filter(event => event.policyId === policy.id) })) };
}

export async function saveReminderDeliveryPolicy(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const policyVersion = text(body.policyVersion, "policyVersion", 3, 100); if (policyVersion !== REMINDER_DELIVERY_POLICY_VERSION) throw new ReminderDeliveryPolicyValidationError("Only the deployed policy version can be saved"); const label = text(body.label, "label", 8, 120), templateEn = text(body.templateEn, "templateEn", 20, 240), templateAr = text(body.templateAr, "templateAr", 20, 240); if (templateEn !== REMINDER_TEMPLATE_EN || templateAr !== REMINDER_TEMPLATE_AR) throw new ReminderDeliveryPolicyValidationError("Only the deployed privacy-safe bilingual wording can be used"); const consentVersion = text(body.consentVersion, "consentVersion", 6, 100); if (!/^[A-Za-z0-9][A-Za-z0-9 _./:-]*$/.test(consentVersion)) throw new ReminderDeliveryPolicyValidationError("consentVersion is invalid"); const quietHoursStart = localTime(body.quietHoursStart, "quietHoursStart"), quietHoursEnd = localTime(body.quietHoursEnd, "quietHoursEnd"); if (quietHoursStart !== "22:00" || quietHoursEnd !== "07:00") throw new ReminderDeliveryPolicyValidationError("The deployed quiet-hours window is 22:00–07:00"); const maximumLatenessMinutes = integer(body.maximumLatenessMinutes, "maximumLatenessMinutes", 1, 5), maxAttempts = integer(body.maxAttempts, "maxAttempts", 1, 3), dedupeWindowMinutes = integer(body.dedupeWindowMinutes, "dedupeWindowMinutes", 5, 60), primaryOwnerUserId = text(body.primaryOwnerUserId, "primaryOwnerUserId", 1, 128), backupOwnerUserId = text(body.backupOwnerUserId, "backupOwnerUserId", 1, 128); if (primaryOwnerUserId === backupOwnerUserId) throw new ReminderDeliveryPolicyValidationError("Primary and backup owners must be different");
  const db = await getDb(), validOwners = await db.select({ id: platformRoles.userId }).from(platformRoles).where(and(inArray(platformRoles.userId, [primaryOwnerUserId, backupOwnerUserId]), eq(platformRoles.status, "active"), inArray(platformRoles.role, ["platform_admin", "security_auditor"]))); if (new Set(validOwners.map(item => item.id)).size !== 2) throw new ReminderDeliveryPolicyValidationError("Both owners must be active operators"); const current = (await db.select().from(medicationReminderDeliveryPolicies).where(eq(medicationReminderDeliveryPolicies.policyVersion, policyVersion)).limit(1))[0], now = new Date(), id = current?.id ?? crypto.randomUUID(); let version = 1, previousStatus: string | null = null;
  const values = { label, templateEn, templateAr, consentVersion, timezone: "Asia/Qatar", quietHoursStart, quietHoursEnd, quietHoursBehavior: "require_explicit_patient_time", maximumLatenessMinutes, maxAttempts, retryBackoffMinutesJson: "[1,3]", dedupeWindowMinutes, primaryOwnerUserId, backupOwnerUserId, status: "draft", reviewerUserId: null, reviewedAt: null, reviewNote: null, updatedAt: now };
  if (current) { if (Number(body.version) !== current.version) throw new ReminderDeliveryPolicyConflictError(); if (!["draft", "rejected"].includes(current.status)) throw new ReminderDeliveryPolicyValidationError("Only draft or rejected policies can be edited"); previousStatus = current.status; const changed = await db.update(medicationReminderDeliveryPolicies).set({ ...values, version: current.version + 1 }).where(and(eq(medicationReminderDeliveryPolicies.id, id), eq(medicationReminderDeliveryPolicies.version, current.version), eq(medicationReminderDeliveryPolicies.status, current.status))).returning({ version: medicationReminderDeliveryPolicies.version }); if (!changed[0]) throw new ReminderDeliveryPolicyConflictError(); version = changed[0].version; } else await db.insert(medicationReminderDeliveryPolicies).values({ id, policyVersion, ...values, preparedByUserId: userId, version: 1, createdAt: now }); await recordPolicy(userId, id, "save", previousStatus, "draft", "Privacy-safe reminder delivery policy saved; delivery remains disabled.", now); return { id, status: "draft", version, deliveryEnabled: false };
}

export async function transitionReminderDeliveryPolicy(userId: string, body: Record<string, unknown>) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]), policyId = text(body.policyId, "policyId", 1, 128), action = text(body.action, "action", 6, 7), note = text(body.note, "note", 20, 1200), version = integer(body.version, "version", 1, Number.MAX_SAFE_INTEGER), db = await getDb(), current = (await db.select().from(medicationReminderDeliveryPolicies).where(eq(medicationReminderDeliveryPolicies.id, policyId)).limit(1))[0]; if (!current) throw new ReminderDeliveryPolicyValidationError("Policy was not found"); const evidence = await verifiedSchedulerEvidence(); if (!evidence) throw new ReminderDeliveryPolicyValidationError("Independently verified scheduler evidence is required"); let nextStatus: string, reviewerUserId = current.reviewerUserId, reviewedAt = current.reviewedAt, reviewNote = current.reviewNote; const now = new Date();
  if (action === "submit") { if (access.role !== "platform_admin" || !["draft", "rejected"].includes(current.status)) throw new ReminderDeliveryPolicyValidationError("Policy cannot be submitted"); nextStatus = "pending_review"; reviewerUserId = null; reviewedAt = null; reviewNote = null; } else if (["approve", "reject"].includes(action)) { if (access.role !== "security_auditor" || current.status !== "pending_review") throw new ReminderDeliveryPolicyValidationError("Policy is not awaiting independent review"); if (current.preparedByUserId === userId || current.primaryOwnerUserId === userId) throw new ReminderDeliveryPolicyValidationError("The preparer or primary owner cannot independently review this policy"); nextStatus = action === "approve" ? "approved" : "rejected"; reviewerUserId = userId; reviewedAt = now; reviewNote = note; } else throw new ReminderDeliveryPolicyValidationError("action is invalid");
  const changed = await db.update(medicationReminderDeliveryPolicies).set({ status: nextStatus, reviewerUserId, reviewedAt, reviewNote, version: current.version + 1, updatedAt: now }).where(and(eq(medicationReminderDeliveryPolicies.id, policyId), eq(medicationReminderDeliveryPolicies.status, current.status), eq(medicationReminderDeliveryPolicies.version, version))).returning({ version: medicationReminderDeliveryPolicies.version }); if (!changed[0]) throw new ReminderDeliveryPolicyConflictError(); await recordPolicy(userId, policyId, action, current.status, nextStatus, note, now); return { policyId, status: nextStatus, version: changed[0].version, policyActivationEnabled: false, occurrenceMaterializationEnabled: false, deliveryEnabled: false };
}

async function recordPolicy(actorUserId: string, policyId: string, action: string, previousStatus: string | null, nextStatus: string, note: string, now: Date) { const db = await getDb(); await db.batch([db.insert(medicationReminderDeliveryPolicyEvents).values({ id: crypto.randomUUID(), policyId, actorUserId, action, previousStatus, nextStatus, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId, organizationId: null, action: `medication_reminder_delivery_policy.${action}`, resourceType: "medication_reminder_delivery_policy", resourceId: policyId, outcome: nextStatus === "rejected" ? "blocked" : "success", metadataJson: JSON.stringify({ previousStatus, nextStatus, privacySafeTemplate: true, consentRequired: true, timezone: "Asia/Qatar", policyActivationEnabled: false, occurrenceMaterializationEnabled: false, deliveryEnabled: false, clinicalContentIncluded: false }), createdAt: now })]); }
