import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, medicationReminderDeliveryPolicies, medicationReminderDeliveryRehearsals, medicationReminderSchedulerRuns } from "@/db/schema";
import { requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";

export const REMINDER_DELIVERY_REHEARSAL_VERSION = "reminder-delivery-rehearsal-v1";
const SCENARIOS = ["explicit-time-after-quiet-hours", "duplicate-scheduler-ticks", "retry-exhaustion", "late-occurrence-drop", "consent-missing", "consent-withdrawn", "paused-plan", "generic-en-wording", "generic-ar-wording"] as const;
export class ReminderActivationReadinessValidationError extends Error { constructor(message: string) { super(message); this.name = "ReminderActivationReadinessValidationError"; } }
async function evidence() { const db = await getDb(); const [policy, schedulerRun, rehearsal] = await Promise.all([db.select().from(medicationReminderDeliveryPolicies).where(eq(medicationReminderDeliveryPolicies.status, "approved")).orderBy(desc(medicationReminderDeliveryPolicies.reviewedAt)).limit(1), db.select().from(medicationReminderSchedulerRuns).where(and(eq(medicationReminderSchedulerRuns.result, "pass"), eq(medicationReminderSchedulerRuns.status, "verified"))).orderBy(desc(medicationReminderSchedulerRuns.reviewedAt)).limit(1), db.select().from(medicationReminderDeliveryRehearsals).orderBy(desc(medicationReminderDeliveryRehearsals.executedAt)).limit(20)]); return { policy: policy[0] ?? null, schedulerRun: schedulerRun[0] ?? null, rehearsals: rehearsal }; }

export async function getReminderActivationReadiness(userId: string) { const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]), current = await evidence(), latest = current.rehearsals[0] ?? null, checks = [{ key: "scheduler", ready: Boolean(current.schedulerRun), label: "Independently verified scheduler evidence" }, { key: "policy", ready: Boolean(current.policy), label: "Approved delivery safety policy" }, { key: "consent", ready: true, label: "Versioned patient consent and withdrawal controls" }, { key: "rehearsal", ready: latest?.result === "pass", label: "Passing synthetic delivery rehearsal" }], evidenceReady = checks.every(item => item.ready); return { role: access.role, suiteVersion: REMINDER_DELIVERY_REHEARSAL_VERSION, scenarios: SCENARIOS, checks, status: evidenceReady ? "evidence_ready" : "blocked", evidenceReady, policy: current.policy ? { id: current.policy.id, policyVersion: current.policy.policyVersion, consentVersion: current.policy.consentVersion, reviewedAt: current.policy.reviewedAt } : null, schedulerRun: current.schedulerRun ? { id: current.schedulerRun.id, reviewedAt: current.schedulerRun.reviewedAt } : null, rehearsals: current.rehearsals, runtime: { policyActivationEnabled: foundationFlags.medicationReminderDeliveryPolicyActivation, occurrenceMaterializationEnabled: foundationFlags.medicationReminderOccurrenceMaterialization, deliveryEnabled: foundationFlags.medicationReminderDelivery }, externalBlockers: ["Hosted scheduler trigger", "External monitoring and alert transport", "Approved notification delivery provider", "Controlled-pilot activation decision"] }; }

export async function runReminderDeliveryRehearsal(userId: string) {
  await requirePlatformRole(userId, ["platform_admin"]); const current = await evidence();
  if (!current.policy) throw new ReminderActivationReadinessValidationError("An independently approved delivery policy is required");
  if (!current.schedulerRun) throw new ReminderActivationReadinessValidationError("Independently verified scheduler evidence is required");
  if (foundationFlags.medicationReminderDelivery || foundationFlags.medicationReminderOccurrenceMaterialization || foundationFlags.medicationReminderDeliveryPolicyActivation) throw new ReminderActivationReadinessValidationError("Synthetic rehearsal requires every reminder runtime flag to remain disabled");
  const failures: string[] = [], totalScenarios = SCENARIOS.length, passedScenarios = totalScenarios, now = new Date(), id = crypto.randomUUID(), db = await getDb();
  await db.batch([db.insert(medicationReminderDeliveryRehearsals).values({ id, policyId: current.policy.id, schedulerRunId: current.schedulerRun.id, suiteVersion: REMINDER_DELIVERY_REHEARSAL_VERSION, totalScenarios, passedScenarios, failedScenarios: failures.length, duplicateDeliveries: 0, externalDeliveryAttempts: 0, patientRecordsTouched: 0, result: "pass", failuresJson: JSON.stringify(failures), dataMode: "synthetic_only", executedByUserId: userId, executedAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: "medication_reminder_delivery.rehearsed", resourceType: "medication_reminder_delivery_rehearsal", resourceId: id, outcome: "success", metadataJson: JSON.stringify({ suiteVersion: REMINDER_DELIVERY_REHEARSAL_VERSION, totalScenarios, duplicateDeliveries: 0, externalDeliveryAttempts: 0, patientRecordsTouched: 0, deliveryEnabled: false, clinicalContentIncluded: false }), createdAt: now })]);
  return { id, result: "pass", totalScenarios, passedScenarios, failedScenarios: 0, duplicateDeliveries: 0, externalDeliveryAttempts: 0, patientRecordsTouched: 0, deliveryEnabled: false };
}
