import { and, desc, eq, inArray, ne } from "drizzle-orm";
import { getDb } from "@/db";
import {
  auditEvents,
  controlledPilotPlans,
  pilotFeedbackEvents,
  pilotFeedbackItems,
  pilotSuccessMetricEvents,
  pilotSuccessMetrics,
  users,
} from "@/db/schema";
import { requirePlatformRole } from "@/lib/authorization";

export class PilotLearningValidationError extends Error { constructor(message: string) { super(message); this.name = "PilotLearningValidationError"; } }
export class PilotLearningConflictError extends Error { constructor() { super("This pilot-learning record changed. Refresh and try again."); this.name = "PilotLearningConflictError"; } }

const metricRules = {
  booking_journey_completion: { unit: "percentage_bps", direction: "at_least", min: 1, max: 10000 },
  provider_response_minutes: { unit: "minutes", direction: "at_most", min: 1, max: 1440 },
  record_finalization_hours: { unit: "hours", direction: "at_most", min: 1, max: 168 },
  support_resolution_hours: { unit: "hours", direction: "at_most", min: 1, max: 168 },
  participant_experience_score: { unit: "score_hundredths", direction: "at_least", min: 1, max: 500 },
  safety_incident_count: { unit: "count", direction: "at_most", min: 0, max: 100 },
} as const;
const metricKeys = ["booking_journey_completion", "provider_response_minutes", "record_finalization_hours", "support_resolution_hours", "participant_experience_score", "safety_incident_count"] as const;
const personas = ["patient", "provider", "administrator", "support"] as const;
const categories = ["discovery", "booking", "provider_workflow", "communications", "accessibility", "support", "safety"] as const;
const severities = ["observation", "minor", "major", "blocking"] as const;
function text(value: unknown, name: string, min: number, max: number) { if (typeof value !== "string" || value.trim().length < min || value.trim().length > max) throw new PilotLearningValidationError(`${name} is invalid`); return value.trim(); }
function integer(value: unknown, name: string, min: number, max: number) { const result = Number(value); if (!Number.isSafeInteger(result) || result < min || result > max) throw new PilotLearningValidationError(`${name} is invalid`); return result; }
function version(value: unknown) { return integer(value, "version", 1, Number.MAX_SAFE_INTEGER); }
function oneOf<T extends readonly string[]>(value: unknown, name: string, values: T) { const result = text(value, name, 1, 80); if (!values.includes(result)) throw new PilotLearningValidationError(`${name} is invalid`); return result as T[number]; }
function stableReference(value: unknown, name: string, max = 180) { const result = text(value, name, 3, max); if (!/^[A-Za-z0-9][A-Za-z0-9 _./:-]*$/.test(result)) throw new PilotLearningValidationError(`${name} must use stable reference characters`); return result; }
function privacySafeSummary(value: unknown) { const result = text(value, "summary", 20, 500); if (/@|\b\d{7,}\b|diagnos|prescription|medication|medical record|patient name|qatar id|passport/i.test(result)) throw new PilotLearningValidationError("Feedback must exclude names, contacts, identifiers, and clinical content"); return result; }

export async function getPilotLearningCentre(userId: string) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor", "support_agent"]); const db = await getDb();
  const [plans, metrics, metricEvents, feedback, feedbackEvents] = await Promise.all([
    db.select().from(controlledPilotPlans).where(inArray(controlledPilotPlans.status, ["approved", "active", "suspended"])).orderBy(desc(controlledPilotPlans.createdAt)),
    db.select({ id: pilotSuccessMetrics.id, planId: pilotSuccessMetrics.planId, metricKey: pilotSuccessMetrics.metricKey, definitionVersion: pilotSuccessMetrics.definitionVersion, label: pilotSuccessMetrics.label, definition: pilotSuccessMetrics.definition, unit: pilotSuccessMetrics.unit, direction: pilotSuccessMetrics.direction, targetValue: pilotSuccessMetrics.targetValue, minimumSampleSize: pilotSuccessMetrics.minimumSampleSize, evidenceSource: pilotSuccessMetrics.evidenceSource, status: pilotSuccessMetrics.status, preparedByUserId: pilotSuccessMetrics.preparedByUserId, preparedByName: users.displayName, reviewerUserId: pilotSuccessMetrics.reviewerUserId, reviewedAt: pilotSuccessMetrics.reviewedAt, reviewNote: pilotSuccessMetrics.reviewNote, version: pilotSuccessMetrics.version, createdAt: pilotSuccessMetrics.createdAt }).from(pilotSuccessMetrics).innerJoin(users, eq(users.id, pilotSuccessMetrics.preparedByUserId)).orderBy(desc(pilotSuccessMetrics.createdAt)),
    db.select({ id: pilotSuccessMetricEvents.id, metricId: pilotSuccessMetricEvents.metricId, action: pilotSuccessMetricEvents.action, note: pilotSuccessMetricEvents.note, actorName: users.displayName, createdAt: pilotSuccessMetricEvents.createdAt }).from(pilotSuccessMetricEvents).innerJoin(users, eq(users.id, pilotSuccessMetricEvents.actorUserId)).orderBy(desc(pilotSuccessMetricEvents.createdAt)).limit(400),
    db.select({ id: pilotFeedbackItems.id, planId: pilotFeedbackItems.planId, persona: pilotFeedbackItems.persona, category: pilotFeedbackItems.category, severity: pilotFeedbackItems.severity, summary: pilotFeedbackItems.summary, dataMode: pilotFeedbackItems.dataMode, status: pilotFeedbackItems.status, recordedByUserId: pilotFeedbackItems.recordedByUserId, recordedByName: users.displayName, resolutionNote: pilotFeedbackItems.resolutionNote, version: pilotFeedbackItems.version, createdAt: pilotFeedbackItems.createdAt }).from(pilotFeedbackItems).innerJoin(users, eq(users.id, pilotFeedbackItems.recordedByUserId)).orderBy(desc(pilotFeedbackItems.createdAt)).limit(500),
    db.select({ id: pilotFeedbackEvents.id, feedbackId: pilotFeedbackEvents.feedbackId, action: pilotFeedbackEvents.action, note: pilotFeedbackEvents.note, actorName: users.displayName, createdAt: pilotFeedbackEvents.createdAt }).from(pilotFeedbackEvents).innerJoin(users, eq(users.id, pilotFeedbackEvents.actorUserId)).orderBy(desc(pilotFeedbackEvents.createdAt)).limit(600),
  ]);
  return { role: access.role, currentUserId: userId, realFeedbackEnabled: false, plans: plans.map((plan) => { const planMetrics = metrics.filter((metric) => metric.planId === plan.id).map((metric) => ({ ...metric, events: metricEvents.filter((event) => event.metricId === metric.id) })); const planFeedback = feedback.filter((item) => item.planId === plan.id).map((item) => ({ ...item, events: feedbackEvents.filter((event) => event.feedbackId === item.id) })); return { ...plan, approvedMetricCount: planMetrics.filter((metric) => metric.status === "approved").length, openFeedbackCount: planFeedback.filter((item) => item.status !== "closed").length, metrics: planMetrics, feedback: planFeedback }; }) };
}

export async function savePilotSuccessMetric(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const planId = text(body.planId, "planId", 1, 128); const metricKey = oneOf(body.metricKey, "metricKey", metricKeys); const definitionVersion = stableReference(body.definitionVersion, "definitionVersion", 30); const label = text(body.label, "label", 5, 100); const definition = text(body.definition, "definition", 30, 800); const evidenceSource = stableReference(body.evidenceSource, "evidenceSource"); const minimumSampleSize = integer(body.minimumSampleSize, "minimumSampleSize", 5, 1000); const rule = metricRules[metricKey]; const targetValue = integer(body.targetValue, "targetValue", rule.min, rule.max); const db = await getDb(); const plan = (await db.select().from(controlledPilotPlans).where(and(eq(controlledPilotPlans.id, planId), inArray(controlledPilotPlans.status, ["approved", "active", "suspended"]))).limit(1))[0]; if (!plan) throw new PilotLearningValidationError("An approved pilot plan is required"); const now = new Date();
  const metricId = typeof body.metricId === "string" && body.metricId ? body.metricId : null;
  if (metricId) { const current = (await db.select().from(pilotSuccessMetrics).where(eq(pilotSuccessMetrics.id, metricId)).limit(1))[0]; if (!current || current.planId !== planId || !["draft", "rejected"].includes(current.status)) throw new PilotLearningValidationError("Only a draft or rejected metric can be edited"); const expectedVersion = version(body.version); const changed = await db.update(pilotSuccessMetrics).set({ metricKey, definitionVersion, label, definition, unit: rule.unit, direction: rule.direction, targetValue, minimumSampleSize, evidenceSource, status: "draft", preparedByUserId: userId, reviewerUserId: null, reviewedAt: null, reviewNote: null, version: current.version + 1, updatedAt: now }).where(and(eq(pilotSuccessMetrics.id, metricId), eq(pilotSuccessMetrics.version, expectedVersion), eq(pilotSuccessMetrics.status, current.status))).returning({ version: pilotSuccessMetrics.version }); if (!changed[0]) throw new PilotLearningConflictError(); await recordMetric(userId, plan.organizationId, metricId, "edit", current.status, "draft", "Metric definition updated.", now); return { id: metricId, status: "draft", version: changed[0].version, realFeedbackEnabled: false }; }
  const duplicate = (await db.select({ id: pilotSuccessMetrics.id }).from(pilotSuccessMetrics).where(and(eq(pilotSuccessMetrics.planId, planId), eq(pilotSuccessMetrics.metricKey, metricKey), eq(pilotSuccessMetrics.definitionVersion, definitionVersion))).limit(1))[0]; if (duplicate) throw new PilotLearningValidationError("This metric definition version already exists"); const id = crypto.randomUUID(); await db.batch([db.insert(pilotSuccessMetrics).values({ id, planId, metricKey, definitionVersion, label, definition, unit: rule.unit, direction: rule.direction, targetValue, minimumSampleSize, evidenceSource, status: "draft", preparedByUserId: userId, version: 1, createdAt: now, updatedAt: now }), db.insert(pilotSuccessMetricEvents).values({ id: crypto.randomUUID(), metricId: id, actorUserId: userId, action: "create", previousStatus: null, nextStatus: "draft", note: "Pilot metric definition prepared; no outcome has been claimed.", createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: plan.organizationId, action: "pilot_learning.metric_created", resourceType: "pilot_success_metric", resourceId: id, outcome: "success", metadataJson: JSON.stringify({ metricKey, definitionVersion, unit: rule.unit, direction: rule.direction, targetValue, minimumSampleSize }), createdAt: now })]); return { id, status: "draft", version: 1, realFeedbackEnabled: false };
}

export async function transitionPilotSuccessMetric(userId: string, body: Record<string, unknown>) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const metricId = text(body.metricId, "metricId", 1, 128); const action = text(body.action, "action", 3, 30); const note = text(body.note, "note", 10, 1200); const expectedVersion = version(body.version); const db = await getDb(); const current = (await db.select().from(pilotSuccessMetrics).where(eq(pilotSuccessMetrics.id, metricId)).limit(1))[0]; if (!current) throw new PilotLearningValidationError("Metric was not found"); const plan = (await db.select().from(controlledPilotPlans).where(eq(controlledPilotPlans.id, current.planId)).limit(1))[0]; if (!plan) throw new PilotLearningValidationError("Pilot plan was not found"); const now = new Date(); let nextStatus = current.status; let reviewerUserId = current.reviewerUserId; let reviewedAt = current.reviewedAt; let reviewNote = current.reviewNote;
  if (action === "submit") { if (access.role !== "platform_admin" || !["draft", "rejected"].includes(current.status)) throw new PilotLearningValidationError("Metric cannot be submitted"); nextStatus = "pending_review"; }
  else if (action === "approve" || action === "reject") { if (current.status !== "pending_review") throw new PilotLearningValidationError("Metric is not awaiting review"); if (current.preparedByUserId === userId) throw new PilotLearningValidationError("The preparer cannot independently review this metric"); nextStatus = action === "approve" ? "approved" : "rejected"; reviewerUserId = userId; reviewedAt = now; reviewNote = note; }
  else if (action === "retire") { if (access.role !== "platform_admin" || current.status !== "approved") throw new PilotLearningValidationError("Only an approved metric can be retired"); nextStatus = "retired"; }
  else throw new PilotLearningValidationError("action is invalid");
  const changed = await db.update(pilotSuccessMetrics).set({ status: nextStatus, reviewerUserId, reviewedAt, reviewNote, version: current.version + 1, updatedAt: now }).where(and(eq(pilotSuccessMetrics.id, metricId), eq(pilotSuccessMetrics.version, expectedVersion), eq(pilotSuccessMetrics.status, current.status))).returning({ version: pilotSuccessMetrics.version }); if (!changed[0]) throw new PilotLearningConflictError(); if (nextStatus === "approved") await db.update(pilotSuccessMetrics).set({ status: "retired", updatedAt: now }).where(and(eq(pilotSuccessMetrics.planId, current.planId), eq(pilotSuccessMetrics.metricKey, current.metricKey), eq(pilotSuccessMetrics.status, "approved"), ne(pilotSuccessMetrics.id, current.id))); await recordMetric(userId, plan.organizationId, metricId, action, current.status, nextStatus, note, now); return { metricId, status: nextStatus, version: changed[0].version, outcomeRecorded: false };
}

export async function recordSyntheticPilotFeedback(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin", "support_agent"]); const planId = text(body.planId, "planId", 1, 128); const persona = oneOf(body.persona, "persona", personas); const category = oneOf(body.category, "category", categories); const severity = oneOf(body.severity, "severity", severities); const summary = privacySafeSummary(body.summary); if (body.dataMode !== "synthetic_only") throw new PilotLearningValidationError("Only synthetic dry-run feedback is enabled"); const db = await getDb(); const plan = (await db.select().from(controlledPilotPlans).where(and(eq(controlledPilotPlans.id, planId), inArray(controlledPilotPlans.status, ["approved", "active", "suspended"]))).limit(1))[0]; if (!plan) throw new PilotLearningValidationError("An approved pilot plan is required"); const now = new Date(); const id = crypto.randomUUID(); await db.batch([db.insert(pilotFeedbackItems).values({ id, planId, persona, category, severity, summary, dataMode: "synthetic_only", status: "open", recordedByUserId: userId, version: 1, createdAt: now, updatedAt: now }), db.insert(pilotFeedbackEvents).values({ id: crypto.randomUUID(), feedbackId: id, actorUserId: userId, action: "record", previousStatus: null, nextStatus: "open", note: "Privacy-safe synthetic dry-run feedback recorded.", createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: plan.organizationId, action: "pilot_learning.feedback_recorded", resourceType: "pilot_feedback", resourceId: id, outcome: "success", metadataJson: JSON.stringify({ persona, category, severity, dataMode: "synthetic_only" }), createdAt: now })]); return { id, status: "open", dataMode: "synthetic_only", realFeedbackEnabled: false };
}

export async function transitionPilotFeedback(userId: string, body: Record<string, unknown>) {
  const access = await requirePlatformRole(userId, ["platform_admin", "support_agent"]); const feedbackId = text(body.feedbackId, "feedbackId", 1, 128); const action = text(body.action, "action", 3, 30); const note = privacySafeSummary(body.note); const expectedVersion = version(body.version); const db = await getDb(); const current = (await db.select().from(pilotFeedbackItems).where(eq(pilotFeedbackItems.id, feedbackId)).limit(1))[0]; if (!current) throw new PilotLearningValidationError("Feedback was not found"); let nextStatus = current.status; if (action === "review" && current.status === "open") nextStatus = "reviewed"; else if (action === "close" && ["open", "reviewed"].includes(current.status)) nextStatus = "closed"; else if (action === "reopen" && access.role === "platform_admin" && current.status === "closed") nextStatus = "open"; else throw new PilotLearningValidationError("Feedback transition is invalid"); const now = new Date(); const changed = await db.update(pilotFeedbackItems).set({ status: nextStatus, closedByUserId: nextStatus === "closed" ? userId : null, resolutionNote: nextStatus === "closed" ? note : current.resolutionNote, closedAt: nextStatus === "closed" ? now : null, version: current.version + 1, updatedAt: now }).where(and(eq(pilotFeedbackItems.id, feedbackId), eq(pilotFeedbackItems.version, expectedVersion), eq(pilotFeedbackItems.status, current.status))).returning({ version: pilotFeedbackItems.version }); if (!changed[0]) throw new PilotLearningConflictError(); await db.batch([db.insert(pilotFeedbackEvents).values({ id: crypto.randomUUID(), feedbackId, actorUserId: userId, action, previousStatus: current.status, nextStatus, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: null, action: `pilot_learning.feedback_${action}`, resourceType: "pilot_feedback", resourceId: feedbackId, outcome: "success", metadataJson: JSON.stringify({ previousStatus: current.status, nextStatus, dataMode: current.dataMode }), createdAt: now })]); return { feedbackId, status: nextStatus, version: changed[0].version };
}

async function recordMetric(actorUserId: string, organizationId: string, metricId: string, action: string, previousStatus: string, nextStatus: string, note: string, now: Date) { const db = await getDb(); await db.batch([db.insert(pilotSuccessMetricEvents).values({ id: crypto.randomUUID(), metricId, actorUserId, action, previousStatus, nextStatus, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId, organizationId, action: `pilot_learning.metric_${action}`, resourceType: "pilot_success_metric", resourceId: metricId, outcome: "success", metadataJson: JSON.stringify({ previousStatus, nextStatus, outcomeRecorded: false }), createdAt: now })]); }
