import { and, desc, eq, inArray, ne } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, controlledPilotPlans, notifications, pilotInvitationPolicies, pilotParticipationPolicies, pilotParticipationPolicyEvents, pilotWithdrawalDrillEvents, pilotWithdrawalDrills, users } from "@/db/schema";
import { requirePlatformRole } from "@/lib/authorization";
import { notificationRecord } from "@/lib/notification-center";

export class PilotParticipationValidationError extends Error { constructor(message: string) { super(message); this.name = "PilotParticipationValidationError"; } }
export class PilotParticipationConflictError extends Error { constructor() { super("This participation record changed. Refresh and try again."); this.name = "PilotParticipationConflictError"; } }

const participantTypes = ["patient", "provider"] as const;
const scenarios = ["self_service", "assisted_support", "emergency_suspend"] as const;
const fixedControls = { withdrawalMethod: "authenticated_self_service_and_support", recordTreatment: "preserve_required_records", reactivationMode: "new_invitation_and_fresh_acceptance" } as const;
function activationState() { return { participantLifecycleEnabled: false, participantAcceptanceEnabled: false, accessRevocationRuntimeEnabled: false, reactivationEnabled: false }; }
function text(value: unknown, name: string, min: number, max: number) { if (typeof value !== "string" || value.trim().length < min || value.trim().length > max) throw new PilotParticipationValidationError(`${name} is invalid`); return value.trim(); }
function integer(value: unknown, name: string, min: number, max: number) { const result = Number(value); if (!Number.isSafeInteger(result) || result < min || result > max) throw new PilotParticipationValidationError(`${name} is invalid`); return result; }
function participantType(value: unknown) { const result = text(value, "participantType", 3, 20); if (!participantTypes.includes(result as (typeof participantTypes)[number])) throw new PilotParticipationValidationError("participantType is invalid"); return result as (typeof participantTypes)[number]; }
function scenario(value: unknown) { const result = text(value, "scenario", 3, 30); if (!scenarios.includes(result as (typeof scenarios)[number])) throw new PilotParticipationValidationError("scenario is invalid"); return result as (typeof scenarios)[number]; }

export async function getPilotParticipationCentre(userId: string) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const db = await getDb();
  const [plans, invitations, policies, policyEvents, drills, drillEvents] = await Promise.all([
    db.select().from(controlledPilotPlans).where(inArray(controlledPilotPlans.status, ["approved", "active", "suspended"])).orderBy(desc(controlledPilotPlans.createdAt)),
    db.select().from(pilotInvitationPolicies).where(eq(pilotInvitationPolicies.status, "approved")).orderBy(desc(pilotInvitationPolicies.updatedAt)),
    db.select({ id: pilotParticipationPolicies.id, planId: pilotParticipationPolicies.planId, participantType: pilotParticipationPolicies.participantType, invitationPolicyId: pilotParticipationPolicies.invitationPolicyId, policyVersion: pilotParticipationPolicies.policyVersion, accessRevocationTargetMinutes: pilotParticipationPolicies.accessRevocationTargetMinutes, acknowledgementTargetHours: pilotParticipationPolicies.acknowledgementTargetHours, supportFollowupHours: pilotParticipationPolicies.supportFollowupHours, withdrawalMethod: pilotParticipationPolicies.withdrawalMethod, recordTreatment: pilotParticipationPolicies.recordTreatment, reactivationMode: pilotParticipationPolicies.reactivationMode, status: pilotParticipationPolicies.status, preparedByUserId: pilotParticipationPolicies.preparedByUserId, preparedByName: users.displayName, reviewerUserId: pilotParticipationPolicies.reviewerUserId, reviewedAt: pilotParticipationPolicies.reviewedAt, reviewNote: pilotParticipationPolicies.reviewNote, version: pilotParticipationPolicies.version, createdAt: pilotParticipationPolicies.createdAt, updatedAt: pilotParticipationPolicies.updatedAt }).from(pilotParticipationPolicies).innerJoin(users, eq(users.id, pilotParticipationPolicies.preparedByUserId)).orderBy(desc(pilotParticipationPolicies.createdAt)),
    db.select().from(pilotParticipationPolicyEvents).orderBy(desc(pilotParticipationPolicyEvents.createdAt)).limit(400),
    db.select({ id: pilotWithdrawalDrills.id, policyId: pilotWithdrawalDrills.policyId, scenario: pilotWithdrawalDrills.scenario, syntheticReference: pilotWithdrawalDrills.syntheticReference, revocationMinutes: pilotWithdrawalDrills.revocationMinutes, acknowledgementMinutes: pilotWithdrawalDrills.acknowledgementMinutes, openActionCount: pilotWithdrawalDrills.openActionCount, result: pilotWithdrawalDrills.result, status: pilotWithdrawalDrills.status, runByUserId: pilotWithdrawalDrills.runByUserId, runByName: users.displayName, reviewerUserId: pilotWithdrawalDrills.reviewerUserId, reviewedAt: pilotWithdrawalDrills.reviewedAt, reviewNote: pilotWithdrawalDrills.reviewNote, version: pilotWithdrawalDrills.version, createdAt: pilotWithdrawalDrills.createdAt }).from(pilotWithdrawalDrills).innerJoin(users, eq(users.id, pilotWithdrawalDrills.runByUserId)).orderBy(desc(pilotWithdrawalDrills.createdAt)),
    db.select().from(pilotWithdrawalDrillEvents).orderBy(desc(pilotWithdrawalDrillEvents.createdAt)).limit(400),
  ]);
  return { role: access.role, currentUserId: userId, ...activationState(), fixedControls, plans: plans.map((plan) => {
    const planInvitations = invitations.filter((item) => item.planId === plan.id).map(({ id, participantType, policyVersion, expiryHours }) => ({ id, participantType, policyVersion, expiryHours }));
    const planPolicies = policies.filter((item) => item.planId === plan.id).map((item) => { const policyDrills = drills.filter((drill) => drill.policyId === item.id).map((drill) => ({ ...drill, events: drillEvents.filter((event) => event.drillId === drill.id) })); return { ...item, invitationPolicy: planInvitations.find((invitation) => invitation.id === item.invitationPolicyId) ?? null, events: policyEvents.filter((event) => event.policyId === item.id), drills: policyDrills, verifiedPassingDrill: policyDrills.some((drill) => drill.status === "verified" && drill.result === "pass") }; });
    const readyTypes = new Set(planPolicies.filter((item) => item.status === "approved" && item.verifiedPassingDrill).map((item) => item.participantType));
    return { ...plan, approvedPolicyCount: participantTypes.filter((type) => planPolicies.some((item) => item.participantType === type && item.status === "approved")).length, verifiedDrillCount: participantTypes.filter((type) => planPolicies.some((item) => item.participantType === type && item.status === "approved" && item.verifiedPassingDrill)).length, participationGovernanceReady: participantTypes.every((type) => readyTypes.has(type)), invitations: planInvitations, policies: planPolicies };
  }) };
}

export async function savePilotParticipationPolicy(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const planId = text(body.planId, "planId", 1, 128); const type = participantType(body.participantType); const invitationPolicyId = text(body.invitationPolicyId, "invitationPolicyId", 1, 128); const policyVersion = text(body.policyVersion, "policyVersion", 1, 30); const accessRevocationTargetMinutes = integer(body.accessRevocationTargetMinutes, "accessRevocationTargetMinutes", 1, 15); const acknowledgementTargetHours = integer(body.acknowledgementTargetHours, "acknowledgementTargetHours", 1, 24); const supportFollowupHours = integer(body.supportFollowupHours, "supportFollowupHours", 1, 72);
  if (!/^[A-Za-z0-9][A-Za-z0-9 _./:-]*$/.test(policyVersion)) throw new PilotParticipationValidationError("policyVersion must use stable reference characters"); const db = await getDb();
  const plan = (await db.select().from(controlledPilotPlans).where(and(eq(controlledPilotPlans.id, planId), inArray(controlledPilotPlans.status, ["approved", "active", "suspended"]))).limit(1))[0]; if (!plan) throw new PilotParticipationValidationError("An approved pilot plan is required");
  const invitation = (await db.select().from(pilotInvitationPolicies).where(and(eq(pilotInvitationPolicies.id, invitationPolicyId), eq(pilotInvitationPolicies.planId, planId), eq(pilotInvitationPolicies.participantType, type), eq(pilotInvitationPolicies.status, "approved"))).limit(1))[0]; if (!invitation) throw new PilotParticipationValidationError("A matching approved invitation policy is required");
  const duplicate = (await db.select({ id: pilotParticipationPolicies.id }).from(pilotParticipationPolicies).where(and(eq(pilotParticipationPolicies.planId, planId), eq(pilotParticipationPolicies.participantType, type), eq(pilotParticipationPolicies.policyVersion, policyVersion))).limit(1))[0]; if (duplicate) throw new PilotParticipationValidationError("This participation-policy version already exists");
  const id = crypto.randomUUID(); const now = new Date(); await db.batch([
    db.insert(pilotParticipationPolicies).values({ id, planId, participantType: type, invitationPolicyId, policyVersion, accessRevocationTargetMinutes, acknowledgementTargetHours, supportFollowupHours, ...fixedControls, status: "draft", preparedByUserId: userId, version: 1, createdAt: now, updatedAt: now }),
    db.insert(pilotParticipationPolicyEvents).values({ id: crypto.randomUUID(), policyId: id, actorUserId: userId, action: "create", previousStatus: null, nextStatus: "draft", note: "Participation and withdrawal policy prepared; no participant state changed.", createdAt: now }),
    db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: plan.organizationId, action: "pilot_participation_policy.create", resourceType: "pilot_participation_policy", resourceId: id, outcome: "success", metadataJson: JSON.stringify({ participantType: type, invitationPolicyId, policyVersion, accessRevocationTargetMinutes, acknowledgementTargetHours, supportFollowupHours, ...activationState() }), createdAt: now }),
  ]); return { id, status: "draft", version: 1, ...activationState() };
}

export async function transitionPilotParticipationPolicy(userId: string, body: Record<string, unknown>) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const policyId = text(body.policyId, "policyId", 1, 128); const action = text(body.action, "action", 3, 30); const note = text(body.note, "note", 10, 1200); const expectedVersion = integer(body.version, "version", 1, Number.MAX_SAFE_INTEGER); const db = await getDb(); const current = (await db.select().from(pilotParticipationPolicies).where(eq(pilotParticipationPolicies.id, policyId)).limit(1))[0]; if (!current) throw new PilotParticipationValidationError("Participation policy was not found"); const plan = (await db.select().from(controlledPilotPlans).where(eq(controlledPilotPlans.id, current.planId)).limit(1))[0]; if (!plan) throw new PilotParticipationValidationError("Pilot plan was not found");
  const now = new Date(); let nextStatus = current.status; let reviewerUserId = current.reviewerUserId; let reviewedAt = current.reviewedAt; let reviewNote = current.reviewNote;
  if (action === "submit") { if (access.role !== "platform_admin" || !["draft", "rejected"].includes(current.status)) throw new PilotParticipationValidationError("Policy cannot be submitted"); nextStatus = "pending_review"; }
  else if (action === "approve" || action === "reject") { if (current.status !== "pending_review") throw new PilotParticipationValidationError("Policy is not awaiting review"); if (current.preparedByUserId === userId) throw new PilotParticipationValidationError("The preparer cannot independently review this policy"); if (action === "approve") { const invitation = (await db.select({ id: pilotInvitationPolicies.id }).from(pilotInvitationPolicies).where(and(eq(pilotInvitationPolicies.id, current.invitationPolicyId), eq(pilotInvitationPolicies.planId, current.planId), eq(pilotInvitationPolicies.participantType, current.participantType), eq(pilotInvitationPolicies.status, "approved"))).limit(1))[0]; if (!invitation) throw new PilotParticipationValidationError("The bound invitation policy is no longer approved"); } nextStatus = action === "approve" ? "approved" : "rejected"; reviewerUserId = userId; reviewedAt = now; reviewNote = note; }
  else if (action === "retire") { if (access.role !== "platform_admin" || current.status !== "approved") throw new PilotParticipationValidationError("Only an approved policy can be retired"); nextStatus = "retired"; }
  else throw new PilotParticipationValidationError("action is invalid");
  const changed = await db.update(pilotParticipationPolicies).set({ status: nextStatus, reviewerUserId, reviewedAt, reviewNote, version: current.version + 1, updatedAt: now }).where(and(eq(pilotParticipationPolicies.id, policyId), eq(pilotParticipationPolicies.version, expectedVersion), eq(pilotParticipationPolicies.status, current.status))).returning({ version: pilotParticipationPolicies.version }); if (!changed[0]) throw new PilotParticipationConflictError(); if (nextStatus === "approved") await db.update(pilotParticipationPolicies).set({ status: "retired", updatedAt: now }).where(and(eq(pilotParticipationPolicies.planId, current.planId), eq(pilotParticipationPolicies.participantType, current.participantType), eq(pilotParticipationPolicies.status, "approved"), ne(pilotParticipationPolicies.id, current.id)));
  await recordPolicy(userId, plan.organizationId, policyId, action, current.status, nextStatus, note, changed[0].version, current.preparedByUserId, now); return { policyId, status: nextStatus, version: changed[0].version, ...activationState() };
}

export async function recordPilotWithdrawalDrill(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const policyId = text(body.policyId, "policyId", 1, 128); const drillScenario = scenario(body.scenario); const syntheticReference = text(body.syntheticReference, "syntheticReference", 6, 80); if (!/^[A-Za-z0-9][A-Za-z0-9 _./:-]*$/.test(syntheticReference)) throw new PilotParticipationValidationError("syntheticReference must use stable reference characters"); const revocationMinutes = integer(body.revocationMinutes, "revocationMinutes", 0, 120); const acknowledgementMinutes = integer(body.acknowledgementMinutes, "acknowledgementMinutes", 0, 1440); const openActionCount = integer(body.openActionCount, "openActionCount", 0, 20); const db = await getDb(); const policy = (await db.select().from(pilotParticipationPolicies).where(and(eq(pilotParticipationPolicies.id, policyId), eq(pilotParticipationPolicies.status, "approved"))).limit(1))[0]; if (!policy) throw new PilotParticipationValidationError("An approved participation policy is required"); const plan = (await db.select().from(controlledPilotPlans).where(eq(controlledPilotPlans.id, policy.planId)).limit(1))[0]; if (!plan) throw new PilotParticipationValidationError("Pilot plan was not found"); const result = revocationMinutes <= policy.accessRevocationTargetMinutes && acknowledgementMinutes <= policy.acknowledgementTargetHours * 60 && openActionCount === 0 ? "pass" : "fail"; const id = crypto.randomUUID(); const now = new Date();
  await db.batch([
    db.insert(pilotWithdrawalDrills).values({ id, policyId, scenario: drillScenario, syntheticReference, revocationMinutes, acknowledgementMinutes, openActionCount, result, status: "pending_review", runByUserId: userId, version: 1, createdAt: now, updatedAt: now }),
    db.insert(pilotWithdrawalDrillEvents).values({ id: crypto.randomUUID(), drillId: id, actorUserId: userId, action: "record", previousStatus: null, nextStatus: "pending_review", note: "Synthetic withdrawal rehearsal recorded for independent verification.", createdAt: now }),
    db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: plan.organizationId, action: "pilot_withdrawal_drill.record", resourceType: "pilot_withdrawal_drill", resourceId: id, outcome: "success", metadataJson: JSON.stringify({ scenario: drillScenario, result, revocationMinutes, acknowledgementMinutes, openActionCount, dataMode: "synthetic_only", ...activationState() }), createdAt: now }),
  ]); return { id, result, status: "pending_review", version: 1, ...activationState() };
}

export async function reviewPilotWithdrawalDrill(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const drillId = text(body.drillId, "drillId", 1, 128); const action = text(body.action, "action", 3, 20); const note = text(body.note, "note", 10, 1200); const expectedVersion = integer(body.version, "version", 1, Number.MAX_SAFE_INTEGER); const db = await getDb(); const current = (await db.select().from(pilotWithdrawalDrills).where(eq(pilotWithdrawalDrills.id, drillId)).limit(1))[0]; if (!current || current.status !== "pending_review") throw new PilotParticipationValidationError("Drill is not awaiting review"); if (current.runByUserId === userId) throw new PilotParticipationValidationError("The rehearsal operator cannot independently review the drill"); if (!["verify", "reject"].includes(action)) throw new PilotParticipationValidationError("action is invalid"); if (action === "verify" && current.result !== "pass") throw new PilotParticipationValidationError("A failed drill cannot be verified"); const policy = (await db.select().from(pilotParticipationPolicies).where(eq(pilotParticipationPolicies.id, current.policyId)).limit(1))[0]; const plan = policy && (await db.select().from(controlledPilotPlans).where(eq(controlledPilotPlans.id, policy.planId)).limit(1))[0]; if (!policy || !plan) throw new PilotParticipationValidationError("Pilot policy was not found"); const now = new Date(); const nextStatus = action === "verify" ? "verified" : "rejected"; const changed = await db.update(pilotWithdrawalDrills).set({ status: nextStatus, reviewerUserId: userId, reviewedAt: now, reviewNote: note, version: current.version + 1, updatedAt: now }).where(and(eq(pilotWithdrawalDrills.id, drillId), eq(pilotWithdrawalDrills.version, expectedVersion), eq(pilotWithdrawalDrills.status, "pending_review"))).returning({ version: pilotWithdrawalDrills.version }); if (!changed[0]) throw new PilotParticipationConflictError();
  await db.batch([db.insert(pilotWithdrawalDrillEvents).values({ id: crypto.randomUUID(), drillId, actorUserId: userId, action, previousStatus: current.status, nextStatus, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId: userId, organizationId: plan.organizationId, action: `pilot_withdrawal_drill.${action}`, resourceType: "pilot_withdrawal_drill", resourceId: drillId, outcome: "success", metadataJson: JSON.stringify({ previousStatus: current.status, nextStatus, result: current.result, dataMode: "synthetic_only", ...activationState() }), createdAt: now }), db.insert(notifications).values(notificationRecord({ userId: current.runByUserId, type: "operations", title: "Withdrawal rehearsal reviewed", body: `The synthetic withdrawal rehearsal was ${nextStatus}. No participant state changed.`, actionPath: "/admin/pilot-participation", resourceType: "pilot_withdrawal_drill", resourceId: drillId, dedupeKey: `pilot-withdrawal:${drillId}:${changed[0].version}:${action}`, createdAt: now }))]); return { drillId, status: nextStatus, version: changed[0].version, result: current.result, ...activationState() };
}

async function recordPolicy(actorUserId: string, organizationId: string, policyId: string, action: string, previousStatus: string, nextStatus: string, note: string, nextVersion: number, preparerUserId: string, now: Date) { const db = await getDb(); await db.batch([db.insert(pilotParticipationPolicyEvents).values({ id: crypto.randomUUID(), policyId, actorUserId, action, previousStatus, nextStatus, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId, organizationId, action: `pilot_participation_policy.${action}`, resourceType: "pilot_participation_policy", resourceId: policyId, outcome: "success", metadataJson: JSON.stringify({ previousStatus, nextStatus, ...activationState() }), createdAt: now }), db.insert(notifications).values(notificationRecord({ userId: preparerUserId, type: "operations", title: "Participation governance updated", body: `A participation policy moved to ${nextStatus}. Participant runtime remains disabled.`, actionPath: "/admin/pilot-participation", resourceType: "pilot_participation_policy", resourceId: policyId, dedupeKey: `pilot-participation:${policyId}:${nextVersion}:${action}`, createdAt: now }))]); }
