import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, controlledPilotPlans, notifications, organizations, pilotLaunchPackageEvents, pilotLaunchPackages, pilotReadinessReviews, pilotRollbackDrillEvents, pilotRollbackDrills, platformRoles, users } from "@/db/schema";
import { requirePlatformRole } from "@/lib/authorization";
import { notificationRecord } from "@/lib/notification-center";
import { getOperationsHealth } from "@/lib/operations-health";

export const REQUIRED_ROLLBACK_SCENARIOS = ["organization_suspend", "publication_stop", "booking_stop", "participant_contact", "access_revocation"] as const;
export class PilotLaunchValidationError extends Error { constructor(message: string) { super(message); this.name = "PilotLaunchValidationError"; } }
export class PilotLaunchConflictError extends Error { constructor() { super("This launch record changed. Refresh and try again."); this.name = "PilotLaunchConflictError"; } }
function clean(value: unknown, name: string, min: number, max: number) { if (typeof value !== "string" || value.trim().length < min || value.trim().length > max) throw new PilotLaunchValidationError(`${name} is invalid`); return value.trim(); }
function stable(value: unknown, name: string, min = 3, max = 100) { const result = clean(value, name, min, max); if (!/^[A-Za-z0-9][A-Za-z0-9 _./:-]*$/.test(result)) throw new PilotLaunchValidationError(`${name} contains unsupported characters`); return result; }
function bounded(value: unknown, name: string, min: number, max: number) { const result = Number(value); if (!Number.isSafeInteger(result) || result < min || result > max) throw new PilotLaunchValidationError(`${name} must be between ${min} and ${max}`); return result; }
function instant(value: unknown, name: string) { const result = new Date(clean(value, name, 10, 40)); if (Number.isNaN(result.valueOf())) throw new PilotLaunchValidationError(`${name} is invalid`); return result; }
async function readiness(userId: string) { const current = await getOperationsHealth(userId, "Pilot launch authorization"); const gates = current.pilotReadiness.gates.map(({ id, name, status, evidence, href }) => ({ id, name, status, evidence, href })); return { generatedAt: current.generatedAt, gates, blocked: gates.filter((gate) => gate.status !== "cleared").length, total: gates.length }; }
async function eligibleOwner(db: Awaited<ReturnType<typeof getDb>>, userId: string) { return (await db.select({ id: users.id }).from(users).innerJoin(platformRoles, eq(platformRoles.userId, users.id)).where(and(eq(users.id, userId), eq(users.status, "active"), eq(platformRoles.status, "active"), inArray(platformRoles.role, ["platform_admin", "security_auditor", "support_agent"]))).limit(1))[0]; }

export async function getPilotLaunchCentre(userId: string) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const db = await getDb(); const health = await readiness(userId);
  const [plans, owners, packages, drills, events] = await Promise.all([
    db.select({ id: controlledPilotPlans.id, clinicLabel: controlledPilotPlans.clinicLabel, status: controlledPilotPlans.status, plannedStartAt: controlledPilotPlans.plannedStartAt, plannedEndAt: controlledPilotPlans.plannedEndAt, organizationName: organizations.name }).from(controlledPilotPlans).innerJoin(organizations, eq(organizations.id, controlledPilotPlans.organizationId)).where(inArray(controlledPilotPlans.status, ["approved", "active", "suspended"])).orderBy(asc(controlledPilotPlans.plannedStartAt)),
    db.selectDistinct({ id: users.id, displayName: users.displayName }).from(users).innerJoin(platformRoles, eq(platformRoles.userId, users.id)).where(and(eq(users.status, "active"), eq(platformRoles.status, "active"), inArray(platformRoles.role, ["platform_admin", "security_auditor", "support_agent"]))).orderBy(asc(users.displayName)),
    db.select().from(pilotLaunchPackages).orderBy(desc(pilotLaunchPackages.createdAt)), db.select().from(pilotRollbackDrills).orderBy(desc(pilotRollbackDrills.createdAt)), db.select().from(pilotLaunchPackageEvents).orderBy(desc(pilotLaunchPackageEvents.createdAt)).limit(300),
  ]);
  return { role: access.role, currentUserId: userId, activationEnabled: false, requiredScenarios: REQUIRED_ROLLBACK_SCENARIOS, readiness: health, owners, plans: plans.map((plan) => ({ ...plan, packages: packages.filter((item) => item.planId === plan.id).map((item) => ({ ...item, drills: drills.filter((drill) => drill.packageId === item.id), events: events.filter((event) => event.packageId === item.id) })) })) };
}

export async function savePilotLaunchPackage(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const db = await getDb(); const planId = clean(body.planId, "planId", 1, 128); const packageVersion = stable(body.packageVersion, "packageVersion"); const start = instant(body.activationWindowStart, "activationWindowStart"); const end = instant(body.activationWindowEnd, "activationWindowEnd"); const primary = clean(body.primaryOwnerUserId, "primaryOwnerUserId", 1, 128); const backup = clean(body.backupOwnerUserId, "backupOwnerUserId", 1, 128); if (primary === backup) throw new PilotLaunchValidationError("Primary and backup owners must be different"); const supportReference = stable(body.supportReference, "supportReference", 6, 100); const rollbackTargetMinutes = bounded(body.rollbackTargetMinutes, "rollbackTargetMinutes", 5, 60); const participantContactTargetHours = bounded(body.participantContactTargetHours, "participantContactTargetHours", 1, 24);
  const plan = (await db.select().from(controlledPilotPlans).where(and(eq(controlledPilotPlans.id, planId), inArray(controlledPilotPlans.status, ["approved", "suspended"]))).limit(1))[0]; if (!plan) throw new PilotLaunchValidationError("An approved or suspended controlled-pilot plan is required"); if (start < plan.plannedStartAt || end > plan.plannedEndAt || end <= start) throw new PilotLaunchValidationError("Activation window must be within the approved pilot dates"); if (!await eligibleOwner(db, primary) || !await eligibleOwner(db, backup)) throw new PilotLaunchValidationError("Active platform owners are required"); const snapshot = await readiness(userId); const now = new Date(); const existing = (await db.select().from(pilotLaunchPackages).where(and(eq(pilotLaunchPackages.planId, planId), eq(pilotLaunchPackages.packageVersion, packageVersion))).limit(1))[0]; const id = existing?.id ?? crypto.randomUUID(); let version = 1;
  if (existing) { if (Number(body.version) !== existing.version) throw new PilotLaunchConflictError(); if (!["draft", "rejected"].includes(existing.status)) throw new PilotLaunchValidationError("Only draft or rejected packages can be edited"); const changed = await db.update(pilotLaunchPackages).set({ activationWindowStart: start, activationWindowEnd: end, primaryOwnerUserId: primary, backupOwnerUserId: backup, supportReference, rollbackTargetMinutes, participantContactTargetHours, readinessSnapshotJson: JSON.stringify(snapshot), blockedGateCount: snapshot.blocked, totalGateCount: snapshot.total, status: "draft", preparedByUserId: userId, reviewerUserId: null, reviewedAt: null, reviewNote: null, version: existing.version + 1, updatedAt: now }).where(and(eq(pilotLaunchPackages.id, id), eq(pilotLaunchPackages.version, existing.version), eq(pilotLaunchPackages.status, existing.status))).returning({ version: pilotLaunchPackages.version }); if (!changed[0]) throw new PilotLaunchConflictError(); version = changed[0].version; }
  else await db.insert(pilotLaunchPackages).values({ id, planId, packageVersion, activationWindowStart: start, activationWindowEnd: end, primaryOwnerUserId: primary, backupOwnerUserId: backup, supportReference, rollbackTargetMinutes, participantContactTargetHours, readinessSnapshotJson: JSON.stringify(snapshot), blockedGateCount: snapshot.blocked, totalGateCount: snapshot.total, status: "draft", preparedByUserId: userId, version, createdAt: now, updatedAt: now });
  await packageEvent(userId, id, existing?.status ?? null, "draft", "save", `Readiness snapshot captured with ${snapshot.blocked} blocked gates.`, now); return { id, status: "draft", version, blockedGateCount: snapshot.blocked, activationEnabled: false };
}

export async function transitionPilotLaunchPackage(userId: string, body: Record<string, unknown>) {
  const access = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const db = await getDb(); const id = clean(body.packageId, "packageId", 1, 128); const action = clean(body.action, "action", 3, 20); const note = clean(body.note, "note", 10, 1200); const expected = bounded(body.version, "version", 1, Number.MAX_SAFE_INTEGER); const current = (await db.select().from(pilotLaunchPackages).where(eq(pilotLaunchPackages.id, id)).limit(1))[0]; if (!current) throw new PilotLaunchValidationError("Launch package was not found"); const now = new Date(); let status = current.status; let reviewerUserId = current.reviewerUserId; let reviewedAt = current.reviewedAt;
  if (action === "submit") { if (access.role !== "platform_admin" || !["draft", "rejected"].includes(current.status)) throw new PilotLaunchValidationError("Package cannot be submitted"); const health = await readiness(userId); if (health.blocked > 0 || current.blockedGateCount > 0) throw new PilotLaunchValidationError("All readiness gates must be cleared and the package snapshot refreshed before submission"); const drills = await db.select().from(pilotRollbackDrills).where(eq(pilotRollbackDrills.packageId, id)); const boundary = new Date(now.valueOf() - 90 * 86400000); if (!REQUIRED_ROLLBACK_SCENARIOS.every((scenario) => drills.some((drill) => drill.scenario === scenario && drill.status === "verified" && drill.result === "pass" && drill.reviewedAt && drill.reviewedAt >= boundary))) throw new PilotLaunchValidationError("Every required rollback scenario needs a fresh independently verified passing drill"); status = "pending_review"; }
  else if (action === "approve") { if (current.status !== "pending_review" || current.preparedByUserId === userId) throw new PilotLaunchValidationError("Independent review is required"); const health = await readiness(userId); const go = (await db.select({ id: pilotReadinessReviews.id }).from(pilotReadinessReviews).where(and(eq(pilotReadinessReviews.status, "approved"), eq(pilotReadinessReviews.decision, "go"))).orderBy(desc(pilotReadinessReviews.reviewedAt)).limit(1))[0]; if (health.blocked > 0 || current.blockedGateCount > 0 || !go || !await eligibleOwner(db, current.primaryOwnerUserId) || !await eligibleOwner(db, current.backupOwnerUserId) || current.primaryOwnerUserId === current.backupOwnerUserId) throw new PilotLaunchValidationError("Approval requires zero blockers, an approved Go decision, and distinct active owners"); status = "approved"; reviewerUserId = userId; reviewedAt = now; await db.update(pilotLaunchPackages).set({ status: "retired", updatedAt: now }).where(and(eq(pilotLaunchPackages.planId, current.planId), eq(pilotLaunchPackages.status, "approved"))); }
  else if (action === "reject") { if (current.status !== "pending_review" || current.preparedByUserId === userId) throw new PilotLaunchValidationError("Independent review is required"); status = "rejected"; reviewerUserId = userId; reviewedAt = now; }
  else if (action === "retire") { if (access.role !== "platform_admin" || current.status !== "approved") throw new PilotLaunchValidationError("Only an approved package can be retired"); status = "retired"; }
  else throw new PilotLaunchValidationError("action is invalid");
  const changed = await db.update(pilotLaunchPackages).set({ status, reviewerUserId, reviewedAt, reviewNote: note, version: current.version + 1, updatedAt: now }).where(and(eq(pilotLaunchPackages.id, id), eq(pilotLaunchPackages.version, expected), eq(pilotLaunchPackages.status, current.status))).returning({ version: pilotLaunchPackages.version }); if (!changed[0]) throw new PilotLaunchConflictError(); await packageEvent(userId, id, current.status, status, action, note, now); return { id, status, version: changed[0].version, activationEnabled: false };
}

export async function recordPilotRollbackDrill(userId: string, body: Record<string, unknown>) { await requirePlatformRole(userId, ["platform_admin"]); const db = await getDb(); const packageId = clean(body.packageId, "packageId", 1, 128); const scenario = clean(body.scenario, "scenario", 3, 40); if (!REQUIRED_ROLLBACK_SCENARIOS.includes(scenario as typeof REQUIRED_ROLLBACK_SCENARIOS[number])) throw new PilotLaunchValidationError("scenario is invalid"); const syntheticReference = stable(body.syntheticReference, "syntheticReference", 6, 100); const containmentMinutes = bounded(body.containmentMinutes, "containmentMinutes", 0, 180); const contactMinutes = bounded(body.contactMinutes, "contactMinutes", 0, 1440); const openActionCount = bounded(body.openActionCount, "openActionCount", 0, 20); const pack = (await db.select().from(pilotLaunchPackages).where(and(eq(pilotLaunchPackages.id, packageId), inArray(pilotLaunchPackages.status, ["draft", "rejected"]))).limit(1))[0]; if (!pack) throw new PilotLaunchValidationError("A draft launch package is required"); const result = containmentMinutes <= pack.rollbackTargetMinutes && contactMinutes <= pack.participantContactTargetHours * 60 && openActionCount === 0 ? "pass" : "fail"; const now = new Date(); const id = crypto.randomUUID(); await db.batch([db.insert(pilotRollbackDrills).values({ id, packageId, scenario, syntheticReference, containmentMinutes, contactMinutes, openActionCount, result, status: "pending_review", runByUserId: userId, version: 1, createdAt: now, updatedAt: now }), db.insert(pilotRollbackDrillEvents).values({ id: crypto.randomUUID(), drillId: id, actorUserId: userId, action: "record", previousStatus: null, nextStatus: "pending_review", note: "Synthetic rollback rehearsal recorded; no live system action was executed.", createdAt: now })]); return { id, result, status: "pending_review", activationEnabled: false }; }

export async function reviewPilotRollbackDrill(userId: string, body: Record<string, unknown>) { await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const db = await getDb(); const id = clean(body.drillId, "drillId", 1, 128); const action = clean(body.action, "action", 3, 12); const note = clean(body.note, "note", 10, 1200); const expected = bounded(body.version, "version", 1, Number.MAX_SAFE_INTEGER); const drill = (await db.select().from(pilotRollbackDrills).where(eq(pilotRollbackDrills.id, id)).limit(1))[0]; if (!drill || drill.status !== "pending_review" || drill.runByUserId === userId) throw new PilotLaunchValidationError("Independent drill review is required"); if (action === "verify" && drill.result !== "pass") throw new PilotLaunchValidationError("A failed drill cannot be verified"); if (!['verify', 'reject'].includes(action)) throw new PilotLaunchValidationError("action is invalid"); const status = action === "verify" ? "verified" : "rejected"; const now = new Date(); const changed = await db.update(pilotRollbackDrills).set({ status, reviewerUserId: userId, reviewedAt: now, reviewNote: note, version: drill.version + 1, updatedAt: now }).where(and(eq(pilotRollbackDrills.id, id), eq(pilotRollbackDrills.version, expected), eq(pilotRollbackDrills.status, "pending_review"))).returning({ version: pilotRollbackDrills.version }); if (!changed[0]) throw new PilotLaunchConflictError(); await db.insert(pilotRollbackDrillEvents).values({ id: crypto.randomUUID(), drillId: id, actorUserId: userId, action, previousStatus: "pending_review", nextStatus: status, note, createdAt: now }); return { id, status, version: changed[0].version, activationEnabled: false }; }

export async function assertPilotLaunchAuthorized(userId: string, planId: string) { const db = await getDb(); const now = new Date(); const pack = (await db.select().from(pilotLaunchPackages).where(and(eq(pilotLaunchPackages.planId, planId), eq(pilotLaunchPackages.status, "approved"))).orderBy(desc(pilotLaunchPackages.reviewedAt)).limit(1))[0]; const health = await readiness(userId); if (!pack || health.blocked > 0 || pack.blockedGateCount > 0 || now < pack.activationWindowStart || now > pack.activationWindowEnd || !await eligibleOwner(db, pack.primaryOwnerUserId) || !await eligibleOwner(db, pack.backupOwnerUserId) || pack.primaryOwnerUserId === pack.backupOwnerUserId) throw new PilotLaunchValidationError("Activation requires current readiness, active owners, and an approved launch package inside its activation window"); const drills = await db.select().from(pilotRollbackDrills).where(eq(pilotRollbackDrills.packageId, pack.id)); const boundary = new Date(now.valueOf() - 90 * 86400000); if (!REQUIRED_ROLLBACK_SCENARIOS.every((scenario) => drills.some((drill) => drill.scenario === scenario && drill.status === "verified" && drill.result === "pass" && drill.reviewedAt && drill.reviewedAt >= boundary))) throw new PilotLaunchValidationError("Activation requires fresh verified evidence for every rollback scenario"); return pack; }
async function packageEvent(actorUserId: string, packageId: string, previousStatus: string | null, nextStatus: string, action: string, note: string, now: Date) { const db = await getDb(); const pack = (await db.select({ preparedByUserId: pilotLaunchPackages.preparedByUserId }).from(pilotLaunchPackages).where(eq(pilotLaunchPackages.id, packageId)).limit(1))[0]; await db.batch([db.insert(pilotLaunchPackageEvents).values({ id: crypto.randomUUID(), packageId, actorUserId, action, previousStatus, nextStatus, note, createdAt: now }), db.insert(auditEvents).values({ id: crypto.randomUUID(), actorUserId, organizationId: null, action: `pilot_launch.${action}`, resourceType: "pilot_launch_package", resourceId: packageId, outcome: "success", metadataJson: JSON.stringify({ previousStatus, nextStatus, activationEnabled: false }), createdAt: now }), ...(pack ? [db.insert(notifications).values(notificationRecord({ userId: pack.preparedByUserId, type: "operations", title: "Pilot launch package updated", body: `Launch authorization moved to ${nextStatus}.`, actionPath: "/admin/pilot-launch", resourceType: "pilot_launch_package", resourceId: packageId, dedupeKey: `pilot-launch:${packageId}:${nextStatus}:${action}`, createdAt: now }))] : [])]); }
