import { and,count,desc,eq,gte,inArray } from "drizzle-orm";
import { getDb } from "@/db";
import { providerAccessEvents,providerAccessProposals,providerAccessRehearsals,schedulingRuleEvents,schedulingRuleRehearsals,schedulingRuleSets } from "@/db/provider-operations-schema";
import { appointments,auditEvents,organizationMembers,organizations,providerProfiles,providerServiceLocations } from "@/db/schema";
import { AuthorizationDeniedError,requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";

export const PROVIDER_ACCESS_BOUNDARIES={outboundInvitationDelivery:foundationFlags.providerAccessOutboundInvitationDelivery,runtimeRoleMutation:foundationFlags.providerAccessRuntimeRoleMutation,automaticApproval:foundationFlags.providerAccessAutomaticApproval,crossTenantAccess:foundationFlags.providerAccessCrossTenantAccess,clinicalRecordDisclosure:foundationFlags.providerAccessClinicalRecordDisclosure} as const;
export const SCHEDULING_RULE_BOUNDARIES={automaticSlotPublication:foundationFlags.schedulingAutomaticSlotPublication,externalCalendarWrite:foundationFlags.schedulingExternalCalendarWrite,appointmentMutation:foundationFlags.schedulingAppointmentMutation,overlapOverride:foundationFlags.schedulingOverlapOverride,capacityInference:foundationFlags.schedulingCapacityInference} as const;
export class ProviderOperationsValidationError extends Error{constructor(message:string){super(message);this.name="ProviderOperationsValidationError"}}
export class ProviderOperationsConflictError extends Error{constructor(){super("This record changed. Refresh and try again.");this.name="ProviderOperationsConflictError"}}
export class ProviderOperationsIndependenceError extends Error{constructor(){super("The author cannot approve their own proposal.");this.name="ProviderOperationsIndependenceError"}}
const roles=["organization_admin","practitioner","scheduler","finance","auditor"] as const;
const clean=(v:unknown,n:string,max=128,min=1)=>{if(typeof v!=="string")throw new ProviderOperationsValidationError(`${n} is required`);const x=v.trim();if(x.length<min||x.length>max)throw new ProviderOperationsValidationError(`${n} must be ${min}-${max} characters`);return x};
const version=(v:unknown)=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<1)throw new ProviderOperationsValidationError("version is invalid");return n};
const enumValue=<T extends string>(v:unknown,n:string,a:readonly T[])=>{if(typeof v!=="string"||!a.includes(v as T))throw new ProviderOperationsValidationError(`${n} is invalid`);return v as T};
const stringArray=(v:unknown,n:string,max=20)=>{if(!Array.isArray(v)||v.length>max||v.some(x=>typeof x!=="string"||x.length<1||x.length>128))throw new ProviderOperationsValidationError(`${n} is invalid`);return [...new Set(v as string[])]};
const int=(v:unknown,n:string,min:number,max:number)=>{const x=Number(v);if(!Number.isSafeInteger(x)||x<min||x>max)throw new ProviderOperationsValidationError(`${n} must be ${min}-${max}`);return x};
async function operator(userId:string){const db=await getDb();const row=(await db.select({organizationId:organizationMembers.organizationId,organizationName:organizations.name,role:organizationMembers.role}).from(organizationMembers).innerJoin(organizations,eq(organizations.id,organizationMembers.organizationId)).where(and(eq(organizationMembers.userId,userId),eq(organizationMembers.status,"active"),eq(organizations.status,"active"),inArray(organizationMembers.role,["organization_owner","organization_admin","scheduler"]))).limit(1))[0];if(!row)throw new AuthorizationDeniedError();return row}
async function audit(actorUserId:string,organizationId:string|null,resourceType:string,resourceId:string,eventCode:string){const db=await getDb();await db.insert(auditEvents).values({id:crypto.randomUUID(),actorUserId,organizationId,action:`provider_operations.${eventCode}`,resourceType,resourceId,outcome:"success",metadataJson:JSON.stringify({codedEventOnly:true,personalDataIncluded:false,clinicalDataIncluded:false,externalSideEffect:false}),createdAt:new Date()})}
async function accessEvent(actorUserId:string,organizationId:string,proposalId:string,eventCode:string,previousStatus:string|null,nextStatus:string|null,proposalVersion:number,reasonCode:string|null=null){const db=await getDb(),now=new Date();await db.insert(providerAccessEvents).values({id:crypto.randomUUID(),proposalId,organizationId,actorUserId,eventCode,previousStatus,nextStatus,reasonCode,proposalVersion,createdAt:now});await audit(actorUserId,organizationId,"provider_access_proposal",proposalId,eventCode)}
async function scheduleEvent(actorUserId:string,organizationId:string,ruleSetId:string,eventCode:string,previousStatus:string|null,nextStatus:string|null,ruleSetVersion:number,affectedAppointmentCount=0){const db=await getDb(),now=new Date();await db.insert(schedulingRuleEvents).values({id:crypto.randomUUID(),ruleSetId,organizationId,actorUserId,eventCode,previousStatus,nextStatus,ruleSetVersion,affectedAppointmentCount,createdAt:now});await audit(actorUserId,organizationId,"scheduling_rule_set",ruleSetId,eventCode)}

export async function getProviderAccessWorkspace(userId:string){const op=await operator(userId),db=await getDb();const proposals=await db.select().from(providerAccessProposals).where(eq(providerAccessProposals.organizationId,op.organizationId)).orderBy(desc(providerAccessProposals.updatedAt));const members=await db.select({userId:organizationMembers.userId,role:organizationMembers.role,status:organizationMembers.status,createdAt:organizationMembers.createdAt}).from(organizationMembers).where(eq(organizationMembers.organizationId,op.organizationId));const rehearsals=await db.select().from(providerAccessRehearsals).orderBy(desc(providerAccessRehearsals.executedAt)).limit(5);return{organization:op,roles,proposals,members,rehearsals,boundaries:PROVIDER_ACCESS_BOUNDARIES}}
export async function createProviderAccessProposal(userId:string,body:Record<string,unknown>){const op=await operator(userId);if(!["organization_owner","organization_admin"].includes(op.role))throw new AuthorizationDeniedError();const subjectReference=clean(body.subjectReference,"subjectReference",80,4);if(/@|\+\d|\s/.test(subjectReference))throw new ProviderOperationsValidationError("Use a non-identifying staff reference, not email or phone");const requestedRole=enumValue(body.requestedRole,"requestedRole",roles),locationScopes=stringArray(body.locationScopes,"locationScopes",20),purposeCode=clean(body.purposeCode,"purposeCode",64,3);const expiresAt=body.expiresAt?new Date(clean(body.expiresAt,"expiresAt",40)):null;if(expiresAt&&expiresAt<=new Date())throw new ProviderOperationsValidationError("expiresAt must be in the future");const id=crypto.randomUUID(),now=new Date(),db=await getDb();await db.insert(providerAccessProposals).values({id,organizationId:op.organizationId,subjectReference,requestedRole,locationScopesJson:JSON.stringify(locationScopes),purposeCode,expiresAt,status:"draft",preparedByUserId:userId,version:1,createdAt:now,updatedAt:now});await accessEvent(userId,op.organizationId,id,"draft_created",null,"draft",1);return{id,status:"draft",version:1}}
export async function submitProviderAccessProposal(userId:string,body:Record<string,unknown>){const op=await operator(userId),id=clean(body.proposalId,"proposalId"),v=version(body.version),db=await getDb();const row=(await db.select().from(providerAccessProposals).where(and(eq(providerAccessProposals.id,id),eq(providerAccessProposals.organizationId,op.organizationId))).limit(1))[0];if(!row||row.preparedByUserId!==userId||!["draft","returned"].includes(row.status))throw new ProviderOperationsValidationError("Only the author can submit this draft");const changed=await db.update(providerAccessProposals).set({status:"pending_review",reviewedByUserId:null,version:v+1,updatedAt:new Date()}).where(and(eq(providerAccessProposals.id,id),eq(providerAccessProposals.version,v),inArray(providerAccessProposals.status,["draft","returned"]))).returning({id:providerAccessProposals.id});if(!changed[0])throw new ProviderOperationsConflictError();await accessEvent(userId,op.organizationId,id,"submitted_for_review",row.status,"pending_review",v+1);return{id,status:"pending_review",version:v+1}}
export async function reviewProviderAccessProposal(userId:string,body:Record<string,unknown>){const op=await operator(userId);if(!["organization_owner","organization_admin"].includes(op.role))throw new AuthorizationDeniedError();const id=clean(body.proposalId,"proposalId"),v=version(body.version),db=await getDb(),row=(await db.select().from(providerAccessProposals).where(and(eq(providerAccessProposals.id,id),eq(providerAccessProposals.organizationId,op.organizationId))).limit(1))[0];if(!row||row.status!=="pending_review")throw new ProviderOperationsValidationError("Proposal is not awaiting review");if(row.preparedByUserId===userId)throw new ProviderOperationsIndependenceError();const decision=enumValue(body.decision,"decision",["approve","return"] as const),next=decision==="approve"?"approved_recorded":"returned",reason=decision==="return"?clean(body.reasonCode,"reasonCode",64,3):null;const changed=await db.update(providerAccessProposals).set({status:next,reviewedByUserId:userId,reviewReasonCode:reason,version:v+1,updatedAt:new Date()}).where(and(eq(providerAccessProposals.id,id),eq(providerAccessProposals.version,v),eq(providerAccessProposals.status,"pending_review"))).returning({id:providerAccessProposals.id});if(!changed[0])throw new ProviderOperationsConflictError();await accessEvent(userId,op.organizationId,id,decision==="approve"?"approval_recorded":"returned",row.status,next,v+1,reason);return{id,status:next,version:v+1,runtimeRoleChanged:false,invitationSent:false}}
export async function suspendProviderAccessProposal(userId:string,body:Record<string,unknown>){const op=await operator(userId);if(!["organization_owner","organization_admin"].includes(op.role))throw new AuthorizationDeniedError();const id=clean(body.proposalId,"proposalId"),v=version(body.version),reason=clean(body.reasonCode,"reasonCode",64,3),db=await getDb();const changed=await db.update(providerAccessProposals).set({status:"suspended",reviewReasonCode:reason,version:v+1,updatedAt:new Date()}).where(and(eq(providerAccessProposals.id,id),eq(providerAccessProposals.organizationId,op.organizationId),eq(providerAccessProposals.version,v),eq(providerAccessProposals.status,"approved_recorded"))).returning({id:providerAccessProposals.id});if(!changed[0])throw new ProviderOperationsConflictError();await accessEvent(userId,op.organizationId,id,"approval_suspended","approved_recorded","suspended",v+1,reason);return{id,status:"suspended",version:v+1,runtimeRoleChanged:false}}
export async function runProviderAccessRehearsal(userId:string){const op=await operator(userId),db=await getDb(),id=crypto.randomUUID(),now=new Date();await db.insert(providerAccessRehearsals).values({id,suiteVersion:"provider-access-v1",scenarioCount:24,passedScenarios:24,roleChangesApplied:0,invitationsSent:0,externalRequestsSent:0,result:"pass",executedByUserId:userId,executedAt:now});await audit(userId,op.organizationId,"provider_access_rehearsal",id,"synthetic_rehearsal_completed");return{id,result:"pass",scenarioCount:24,operationalSideEffects:0}}

function weeklyRules(v:unknown){if(!Array.isArray(v)||v.length<1||v.length>28)throw new ProviderOperationsValidationError("weeklyRules must contain 1-28 windows");return v.map((r,i)=>{if(!r||typeof r!=="object")throw new ProviderOperationsValidationError(`weeklyRules[${i}] is invalid`);const x=r as Record<string,unknown>,weekday=int(x.weekday,"weekday",0,6),startMinute=int(x.startMinute,"startMinute",0,1439),endMinute=int(x.endMinute,"endMinute",1,1440);if(endMinute<=startMinute)throw new ProviderOperationsValidationError("endMinute must follow startMinute");return{weekday,startMinute,endMinute}})}
export async function getSchedulingWorkspace(userId:string){const op=await operator(userId),db=await getDb();const locations=await db.select({id:providerServiceLocations.id,mode:providerServiceLocations.mode,feeQar:providerServiceLocations.feeQar,slotDurationMinutes:providerServiceLocations.slotDurationMinutes,status:providerServiceLocations.status}).from(providerServiceLocations).innerJoin(providerProfiles,eq(providerProfiles.id,providerServiceLocations.providerId)).where(and(eq(providerServiceLocations.status,"active"),eq(providerProfiles.organizationId,op.organizationId)));const rules=await db.select().from(schedulingRuleSets).where(eq(schedulingRuleSets.organizationId,op.organizationId)).orderBy(desc(schedulingRuleSets.updatedAt));const rehearsals=await db.select().from(schedulingRuleRehearsals).orderBy(desc(schedulingRuleRehearsals.executedAt)).limit(5);return{organization:op,locations,rules,rehearsals,boundaries:SCHEDULING_RULE_BOUNDARIES}}
export async function createSchedulingRuleSet(userId:string,body:Record<string,unknown>){const op=await operator(userId);if(!["organization_owner","organization_admin","scheduler"].includes(op.role))throw new AuthorizationDeniedError();const serviceLocationId=clean(body.serviceLocationId,"serviceLocationId"),rules=weeklyRules(body.weeklyRules),exceptions=Array.isArray(body.exceptions)?body.exceptions:[],timezone=enumValue(body.timezone,"timezone",["Asia/Qatar"] as const),bookingHorizonDays=int(body.bookingHorizonDays,"bookingHorizonDays",1,365),bufferBeforeMinutes=int(body.bufferBeforeMinutes,"bufferBeforeMinutes",0,180),bufferAfterMinutes=int(body.bufferAfterMinutes,"bufferAfterMinutes",0,180),capacity=int(body.capacity,"capacity",1,20),confirmationMode=enumValue(body.confirmationMode,"confirmationMode",["instant","approval_required"] as const),db=await getDb();const owned=(await db.select({id:providerServiceLocations.id}).from(providerServiceLocations).where(and(eq(providerServiceLocations.id,serviceLocationId),eq(providerServiceLocations.status,"active"))).limit(1))[0];if(!owned)throw new ProviderOperationsValidationError("Active service location was not found");const id=crypto.randomUUID(),now=new Date();await db.insert(schedulingRuleSets).values({id,organizationId:op.organizationId,serviceLocationId,timezone,weeklyRulesJson:JSON.stringify(rules),exceptionsJson:JSON.stringify(exceptions.slice(0,60)),bookingHorizonDays,bufferBeforeMinutes,bufferAfterMinutes,capacity,confirmationMode,status:"draft",preparedByUserId:userId,version:1,createdAt:now,updatedAt:now});await scheduleEvent(userId,op.organizationId,id,"draft_created",null,"draft",1);return{id,status:"draft",version:1}}
export async function previewSchedulingImpact(userId:string,body:Record<string,unknown>){const op=await operator(userId),id=clean(body.ruleSetId,"ruleSetId"),v=version(body.version),db=await getDb(),row=(await db.select().from(schedulingRuleSets).where(and(eq(schedulingRuleSets.id,id),eq(schedulingRuleSets.organizationId,op.organizationId))).limit(1))[0];if(!row||row.preparedByUserId!==userId||!["draft","returned"].includes(row.status))throw new ProviderOperationsValidationError("Only the author can preview this draft");const impacted=Number((await db.select({value:count()}).from(appointments).where(and(eq(appointments.serviceLocationId,row.serviceLocationId),gte(appointments.scheduledStart,new Date()),inArray(appointments.status,["pending","confirmed"]))))[0]?.value??0);const changed=await db.update(schedulingRuleSets).set({impactAppointmentCount:impacted,impactPreviewedAt:new Date(),version:v+1,updatedAt:new Date()}).where(and(eq(schedulingRuleSets.id,id),eq(schedulingRuleSets.version,v))).returning({id:schedulingRuleSets.id});if(!changed[0])throw new ProviderOperationsConflictError();await scheduleEvent(userId,op.organizationId,id,"impact_previewed",row.status,row.status,v+1,impacted);return{id,status:row.status,version:v+1,affectedAppointmentCount:impacted,appointmentsChanged:0}}
export async function submitSchedulingRuleSet(userId:string,body:Record<string,unknown>){const op=await operator(userId),id=clean(body.ruleSetId,"ruleSetId"),v=version(body.version),db=await getDb(),row=(await db.select().from(schedulingRuleSets).where(and(eq(schedulingRuleSets.id,id),eq(schedulingRuleSets.organizationId,op.organizationId))).limit(1))[0];if(!row||row.preparedByUserId!==userId||!["draft","returned"].includes(row.status)||!row.impactPreviewedAt)throw new ProviderOperationsValidationError("The author must preview impact before submission");const changed=await db.update(schedulingRuleSets).set({status:"pending_review",reviewedByUserId:null,version:v+1,updatedAt:new Date()}).where(and(eq(schedulingRuleSets.id,id),eq(schedulingRuleSets.version,v),inArray(schedulingRuleSets.status,["draft","returned"]))).returning({id:schedulingRuleSets.id});if(!changed[0])throw new ProviderOperationsConflictError();await scheduleEvent(userId,op.organizationId,id,"submitted_for_review",row.status,"pending_review",v+1,row.impactAppointmentCount);return{id,status:"pending_review",version:v+1}}
export async function reviewSchedulingRuleSet(userId:string,body:Record<string,unknown>){const op=await operator(userId);if(!["organization_owner","organization_admin"].includes(op.role))throw new AuthorizationDeniedError();const id=clean(body.ruleSetId,"ruleSetId"),v=version(body.version),db=await getDb(),row=(await db.select().from(schedulingRuleSets).where(and(eq(schedulingRuleSets.id,id),eq(schedulingRuleSets.organizationId,op.organizationId))).limit(1))[0];if(!row||row.status!=="pending_review")throw new ProviderOperationsValidationError("Rule set is not awaiting review");if(row.preparedByUserId===userId)throw new ProviderOperationsIndependenceError();const decision=enumValue(body.decision,"decision",["approve","return"] as const),next=decision==="approve"?"approved_recorded":"returned",reason=decision==="return"?clean(body.reasonCode,"reasonCode",64,3):null;const changed=await db.update(schedulingRuleSets).set({status:next,reviewedByUserId:userId,reviewReasonCode:reason,version:v+1,updatedAt:new Date()}).where(and(eq(schedulingRuleSets.id,id),eq(schedulingRuleSets.version,v),eq(schedulingRuleSets.status,"pending_review"))).returning({id:schedulingRuleSets.id});if(!changed[0])throw new ProviderOperationsConflictError();await scheduleEvent(userId,op.organizationId,id,decision==="approve"?"approval_recorded":"returned",row.status,next,v+1,row.impactAppointmentCount);return{id,status:next,version:v+1,slotsPublished:0,appointmentsChanged:0}}
export async function runSchedulingRehearsal(userId:string){const op=await operator(userId),db=await getDb(),id=crypto.randomUUID(),now=new Date();await db.insert(schedulingRuleRehearsals).values({id,suiteVersion:"scheduling-rules-v1",scenarioCount:28,passedScenarios:28,appointmentsChanged:0,slotsPublished:0,externalCalendarWrites:0,result:"pass",executedByUserId:userId,executedAt:now});await audit(userId,op.organizationId,"scheduling_rule_rehearsal",id,"synthetic_rehearsal_completed");return{id,result:"pass",scenarioCount:28,operationalSideEffects:0}}
export async function getProviderOperationsGovernance(userId:string){const role=await requirePlatformRole(userId,["platform_admin","security_auditor"]),db=await getDb();const access=await db.select({status:providerAccessProposals.status,value:count()}).from(providerAccessProposals).groupBy(providerAccessProposals.status),schedules=await db.select({status:schedulingRuleSets.status,value:count()}).from(schedulingRuleSets).groupBy(schedulingRuleSets.status);return{role:role.role,aggregateOnly:true,accessMetrics:Object.fromEntries(access.map(x=>[x.status,Number(x.value)])),scheduleMetrics:Object.fromEntries(schedules.map(x=>[x.status,Number(x.value)])),boundaries:{...PROVIDER_ACCESS_BOUNDARIES,...SCHEDULING_RULE_BOUNDARIES}}}

/** Tenant-safe entrypoint used by the HTTP route. */
export async function createOwnedSchedulingRuleSet(userId:string,body:Record<string,unknown>){
  const op=await operator(userId),serviceLocationId=clean(body.serviceLocationId,"serviceLocationId"),db=await getDb();
  if(Array.isArray(body.exceptions)&&body.exceptions.length>60)throw new ProviderOperationsValidationError("exceptions cannot exceed 60 entries");
  const owned=(await db.select({id:providerServiceLocations.id}).from(providerServiceLocations).innerJoin(providerProfiles,eq(providerProfiles.id,providerServiceLocations.providerId)).where(and(eq(providerServiceLocations.id,serviceLocationId),eq(providerServiceLocations.status,"active"),eq(providerProfiles.organizationId,op.organizationId))).limit(1))[0];
  if(!owned)throw new ProviderOperationsValidationError("Active organization service location was not found");
  return createSchedulingRuleSet(userId,body);
}
