import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { auditEvents, reportReaderCases, reportReaderEvaluationRuns, reportReaderEvents, reportReaderSuites } from "@/db/schema";
import { requireActiveProvider, requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";
export const REPORT_READER_SUITE_VERSION="report-reader-safety-2026-08-16";
export class ReportReaderValidationError extends Error{constructor(message:string){super(message);this.name="ReportReaderValidationError";}}
export class ReportReaderConflictError extends Error{constructor(){super("This review task changed. Refresh and try again.");this.name="ReportReaderConflictError";}}
function text(value:unknown,name:string,min:number,max:number){if(typeof value!=="string"||value.trim().length<min||value.trim().length>max)throw new ReportReaderValidationError(`${name} is invalid`);return value.trim();}
function version(value:unknown){const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed<1)throw new ReportReaderValidationError("version is invalid");return parsed;}
function stable(value:unknown,name:string){const result=text(value,name,3,160);if(!/^[A-Za-z0-9][A-Za-z0-9 _./:-]*$/.test(result))throw new ReportReaderValidationError(`${name} is invalid`);return result;}
type Observation={key:string;label:string;value:string;unit:string|null;referenceRange:string|null;sourceReportedFlag:"normal"|"high"|"low"|"not_reported";confidenceBps:number;sourcePage:number;sourceRegion:string;issueCode:string|null};
const fixtures:readonly{caseKey:string;locale:"en"|"ar";reportType:string;checksum:string;decision:"accept"|"reject";observations:Observation[]}[]=[
 {caseKey:"en-complete-lab",locale:"en",reportType:"laboratory_report",checksum:"1".repeat(64),decision:"accept",observations:[{key:"synthetic_result_a",label:"Synthetic result A",value:"7.2",unit:"unit-A",referenceRange:"4.0–10.0",sourceReportedFlag:"normal",confidenceBps:9900,sourcePage:1,sourceRegion:"p1:r1",issueCode:null},{key:"synthetic_result_b",label:"Synthetic result B",value:"12.1",unit:"unit-B",referenceRange:"2.0–9.0",sourceReportedFlag:"high",confidenceBps:9800,sourcePage:1,sourceRegion:"p1:r2",issueCode:null}]},
 {caseKey:"en-missing-unit",locale:"en",reportType:"laboratory_report",checksum:"2".repeat(64),decision:"reject",observations:[{key:"synthetic_result_c",label:"Synthetic result C",value:"5.4",unit:null,referenceRange:"3.0–7.0",sourceReportedFlag:"normal",confidenceBps:9200,sourcePage:1,sourceRegion:"p1:r1",issueCode:"unit_missing"}]},
 {caseKey:"en-range-conflict",locale:"en",reportType:"laboratory_report",checksum:"3".repeat(64),decision:"reject",observations:[{key:"synthetic_result_d",label:"Synthetic result D",value:"8.8",unit:"unit-D",referenceRange:"conflicting source ranges",sourceReportedFlag:"not_reported",confidenceBps:8800,sourcePage:2,sourceRegion:"p2:r3",issueCode:"range_conflict"}]},
 {caseKey:"ar-complete-lab",locale:"ar",reportType:"laboratory_report",checksum:"4".repeat(64),decision:"accept",observations:[{key:"synthetic_result_ar",label:"نتيجة اصطناعية أ",value:"٦٫٤",unit:"وحدة-أ",referenceRange:"٤٫٠–٨٫٠",sourceReportedFlag:"normal",confidenceBps:9800,sourcePage:1,sourceRegion:"p1:r1",issueCode:null}]},
] as const;
export async function getReportReaderCentre(userId:string){const access=await requirePlatformRole(userId,["platform_admin","security_auditor"]);const db=await getDb();const[suites,cases,runs]=await Promise.all([db.select().from(reportReaderSuites).orderBy(desc(reportReaderSuites.createdAt)),db.select().from(reportReaderCases).orderBy(reportReaderCases.caseKey),db.select().from(reportReaderEvaluationRuns).orderBy(desc(reportReaderEvaluationRuns.executedAt)).limit(100)]);return{role:access.role,dispatchEnabled:foundationFlags.reportReaderDispatch,interpretationEnabled:foundationFlags.reportReaderInterpretation,recordCommitEnabled:foundationFlags.reportReaderRecordCommit,suiteVersion:REPORT_READER_SUITE_VERSION,thresholds:{minimumConfidenceBps:9000,unsafeAcceptances:0,interpretationCount:0},suites:suites.map(suite=>({...suite,cases:cases.filter(item=>item.suiteId===suite.id).map(item=>({...item,observations:JSON.parse(item.extractedObservationsJson) as Observation[]})),runs:runs.filter(item=>item.suiteId===suite.id)}))};}
export async function createReportReaderSuite(userId:string,body:Record<string,unknown>){await requirePlatformRole(userId,["platform_admin"]);const suiteVersion=stable(body.suiteVersion,"suiteVersion");if(suiteVersion!==REPORT_READER_SUITE_VERSION)throw new ReportReaderValidationError("Only the deployed Report Reader suite can be registered");const label=text(body.label,"label",8,120);const sourceReference=stable(body.sourceReference,"sourceReference");const db=await getDb();if((await db.select({id:reportReaderSuites.id}).from(reportReaderSuites).where(eq(reportReaderSuites.suiteVersion,suiteVersion)).limit(1))[0])throw new ReportReaderValidationError("This suite version is already registered");const now=new Date(),id=crypto.randomUUID();await db.batch([db.insert(reportReaderSuites).values({id,suiteVersion,label,sourceReference,engineAlias:"synthetic-report-fixture",modelVersion:"fixture-v1",minimumConfidenceBps:9000,status:"draft",preparedByUserId:userId,version:1,createdAt:now,updatedAt:now}),db.insert(auditEvents).values({id:crypto.randomUUID(),actorUserId:userId,organizationId:null,action:"report_reader.suite_created",resourceType:"report_reader_suite",resourceId:id,outcome:"success",metadataJson:JSON.stringify({dataMode:"synthetic_only",interpretationEnabled:false,recordCommitEnabled:false}),createdAt:now})]);return{id,status:"draft"};}
export async function seedReportReaderSuite(userId:string,body:Record<string,unknown>){await requirePlatformRole(userId,["platform_admin"]);const suiteId=text(body.suiteId,"suiteId",1,128);const db=await getDb();const suite=(await db.select().from(reportReaderSuites).where(eq(reportReaderSuites.id,suiteId)).limit(1))[0];if(!suite||suite.status!=="draft")throw new ReportReaderValidationError("A draft suite is required");if((await db.select({id:reportReaderCases.id}).from(reportReaderCases).where(eq(reportReaderCases.suiteId,suiteId)).limit(1))[0])throw new ReportReaderValidationError("The standard suite is already present");const now=new Date();await db.insert(reportReaderCases).values(fixtures.map(item=>({id:crypto.randomUUID(),suiteId,caseKey:item.caseKey,locale:item.locale,reportType:item.reportType,sourceReference:`${REPORT_READER_SUITE_VERSION}/${item.caseKey}`,sourceChecksumSha256:item.checksum,documentId:null,documentVersion:null,extractedObservationsJson:JSON.stringify(item.observations),expectedDecision:item.decision,status:"review_required",dataMode:"synthetic_only",interpretationGenerated:false,version:1,createdAt:now,updatedAt:now})));await db.insert(auditEvents).values({id:crypto.randomUUID(),actorUserId:userId,organizationId:null,action:"report_reader.suite_seeded",resourceType:"report_reader_suite",resourceId:suiteId,outcome:"success",metadataJson:JSON.stringify({cases:fixtures.length,dataMode:"synthetic_only",interpretationsGenerated:0,patientRecordsTouched:0}),createdAt:now});return{suiteId,caseCount:fixtures.length};}
export async function getProviderReportReviews(userId:string){const provider=await requireActiveProvider(userId);const db=await getDb();const rows=await db.select({case:reportReaderCases,suiteLabel:reportReaderSuites.label}).from(reportReaderCases).innerJoin(reportReaderSuites,eq(reportReaderSuites.id,reportReaderCases.suiteId)).orderBy(reportReaderCases.createdAt);return{providerId:provider.id,dataMode:"synthetic_only",interpretationEnabled:false,recordCommitEnabled:false,cases:rows.map(row=>({...row.case,suiteLabel:row.suiteLabel,observations:JSON.parse(row.case.extractedObservationsJson) as Observation[]}))};}
export async function reviewReportReaderCase(userId:string,body:Record<string,unknown>){const provider=await requireActiveProvider(userId);const caseId=text(body.caseId,"caseId",1,128),decision=text(body.decision,"decision",6,8);if(!(["accept","reject"] as string[]).includes(decision))throw new ReportReaderValidationError("decision is invalid");const note=text(body.note,"note",20,800),expectedVersion=version(body.version),db=await getDb();const current=(await db.select().from(reportReaderCases).where(eq(reportReaderCases.id,caseId)).limit(1))[0];if(!current||current.dataMode!=="synthetic_only"||current.status!=="review_required"||current.interpretationGenerated)throw new ReportReaderValidationError("An open non-interpreted synthetic case is required");const now=new Date(),nextStatus=decision==="accept"?"human_verified":"rejected";const changed=await db.update(reportReaderCases).set({reviewerProviderId:provider.id,reviewDecision:decision,reviewNote:note,reviewedAt:now,status:nextStatus,version:expectedVersion+1,updatedAt:now}).where(and(eq(reportReaderCases.id,caseId),eq(reportReaderCases.status,"review_required"),eq(reportReaderCases.version,expectedVersion),eq(reportReaderCases.interpretationGenerated,false))).returning({id:reportReaderCases.id});if(!changed[0])throw new ReportReaderConflictError();await db.batch([db.insert(reportReaderEvents).values({id:crypto.randomUUID(),caseId,actorUserId:userId,action:`human_${decision}`,previousStatus:"review_required",nextStatus,note,createdAt:now}),db.insert(auditEvents).values({id:crypto.randomUUID(),actorUserId:userId,organizationId:provider.organizationId,action:"report_reader.synthetic_reviewed",resourceType:"report_reader_case",resourceId:caseId,outcome:"success",metadataJson:JSON.stringify({decision,dataMode:"synthetic_only",interpretationGenerated:false,patientRecordWritten:false}),createdAt:now})]);return{id:caseId,status:nextStatus,version:expectedVersion+1,interpretationEnabled:false,recordCommitEnabled:false};}
export async function runReportReaderEvaluation(userId:string,body:Record<string,unknown>){await requirePlatformRole(userId,["platform_admin"]);const suiteId=text(body.suiteId,"suiteId",1,128),db=await getDb(),cases=await db.select().from(reportReaderCases).where(eq(reportReaderCases.suiteId,suiteId));if(cases.length!==fixtures.length)throw new ReportReaderValidationError("The complete standard suite is required");const reviewed=cases.filter(item=>item.reviewDecision);if(reviewed.length!==cases.length)throw new ReportReaderValidationError("Every case requires verified-provider review");const correct=reviewed.filter(item=>item.reviewDecision===item.expectedDecision).length,unsafeAcceptances=reviewed.filter(item=>item.reviewDecision==="accept"&&item.expectedDecision==="reject").length,interpretationCount=cases.filter(item=>item.interpretationGenerated).length,result=correct===cases.length&&unsafeAcceptances===0&&interpretationCount===0?"pass":"fail",now=new Date(),id=crypto.randomUUID();await db.batch([db.insert(reportReaderEvaluationRuns).values({id,suiteId,executedByUserId:userId,totalCases:cases.length,reviewedCases:reviewed.length,correctDecisions:correct,unsafeAcceptances,interpretationCount,result,dataMode:"synthetic_only",executedAt:now}),db.insert(auditEvents).values({id:crypto.randomUUID(),actorUserId:userId,organizationId:null,action:"report_reader.evaluation_run",resourceType:"report_reader_evaluation_run",resourceId:id,outcome:result==="pass"?"success":"blocked",metadataJson:JSON.stringify({suiteId,totalCases:cases.length,correctDecisions:correct,unsafeAcceptances,interpretationCount,dataMode:"synthetic_only",recordCommitEnabled:false}),createdAt:now})]);return{id,result,totalCases:cases.length,correctDecisions:correct,unsafeAcceptances,interpretationCount,interpretationEnabled:false,recordCommitEnabled:false};}
export function assertReportReaderRuntimeDisabled(){if(foundationFlags.reportReaderDispatch||foundationFlags.reportReaderInterpretation||foundationFlags.reportReaderRecordCommit)throw new Error("Report Reader runtime activation requires a separate approved review");return{dispatchEnabled:false,interpretationEnabled:false,recordCommitEnabled:false};}
