import { and, desc, eq, inArray, ne } from "drizzle-orm";
import { getDb } from "@/db";
import { tenantConfigurationDrafts, tenantConfigurationEvents, tenantConfigurationRehearsals } from "@/db/tenant-configuration-schema";
import { AuthorizationDeniedError, getActiveMemberships, requireOrganizationRole, requirePlatformRole } from "@/lib/authorization";
import { foundationFlags } from "@/lib/foundation-flags";

export const TENANT_CONFIGURATION_LOCALES = ["en", "ar", "bilingual"] as const;
export const TENANT_CONFIGURATION_TIMEZONES = ["Asia/Qatar", "Asia/Riyadh", "UTC"] as const;
export const TENANT_FACILITY_DISPLAY_DEFAULTS = ["alphabetical", "area_then_name", "organization_priority"] as const;
export const TENANT_VISIBLE_MODULES = ["appointments", "facilities", "virtual_care", "messages", "referrals", "benefits", "health_records", "family_access"] as const;
export const TENANT_CONFIGURATION_REHEARSAL_VERSION = "tenant-configuration-governance-v1";
export const TENANT_CONFIGURATION_BOUNDARIES = {
  tenantConfigurationRuntimeApplication: foundationFlags.tenantConfigurationRuntimeApplication,
  tenantConfigurationAutomaticApproval: foundationFlags.tenantConfigurationAutomaticApproval,
  tenantConfigurationExternalSync: foundationFlags.tenantConfigurationExternalSync,
  tenantConfigurationSecretStorage: foundationFlags.tenantConfigurationSecretStorage,
  tenantConfigurationCrossTenantOverride: foundationFlags.tenantConfigurationCrossTenantOverride,
} as const;

type Locale = (typeof TENANT_CONFIGURATION_LOCALES)[number];
type Timezone = (typeof TENANT_CONFIGURATION_TIMEZONES)[number];
type FacilityDefault = (typeof TENANT_FACILITY_DISPLAY_DEFAULTS)[number];
const ownerRoles = ["organization_owner", "organization_admin"] as const;

export class TenantConfigurationValidationError extends Error { constructor(message: string) { super(message); this.name = "TenantConfigurationValidationError"; } }
export class TenantConfigurationConflictError extends Error { constructor() { super("This configuration changed. Refresh and try again."); this.name = "TenantConfigurationConflictError"; } }
export class TenantConfigurationIndependenceError extends Error { constructor(message = "An independent platform reviewer is required.") { super(message); this.name = "TenantConfigurationIndependenceError"; } }

function clean(value: unknown, name: string, max: number, min = 1) { if (typeof value !== "string") throw new TenantConfigurationValidationError(`${name} is required`); const result = value.trim(); if (result.length < min || result.length > max) throw new TenantConfigurationValidationError(`${name} must be ${min}-${max} characters`); return result; }
function identifier(value: unknown, name: string) { return clean(value, name, 128); }
function machineCode(value: unknown, name: string, max = 80) { const result = clean(value, name, max, 2).toLowerCase(); if (!/^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test(result)) throw new TenantConfigurationValidationError(`${name} must be a bounded machine reference`); return result; }
function versionValue(value: unknown) { const result = Number(value); if (!Number.isSafeInteger(result) || result < 1) throw new TenantConfigurationValidationError("version is invalid"); return result; }
function enumValue<T extends string>(value: unknown, name: string, allowed: readonly T[]) { if (!allowed.includes(value as T)) throw new TenantConfigurationValidationError(`${name} is invalid`); return value as T; }
function boundedNumber(value: unknown, name: string, min: number, max: number) { const result = Number(value); if (!Number.isSafeInteger(result) || result < min || result > max) throw new TenantConfigurationValidationError(`${name} must be ${min}-${max}`); return result; }
function modules(value: unknown) { if (!Array.isArray(value) || value.length > TENANT_VISIBLE_MODULES.length) throw new TenantConfigurationValidationError(`moduleVisibilityRequests must contain at most ${TENANT_VISIBLE_MODULES.length} entries`); const result = value.map((item) => enumValue(item, "moduleVisibilityRequest", TENANT_VISIBLE_MODULES)); if (new Set(result).size !== result.length) throw new TenantConfigurationValidationError("moduleVisibilityRequests must be unique"); return result; }
function parseModules(value: string) { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }

function configurationInput(body: Record<string, unknown>) { return {
  locale: enumValue(body.locale, "locale", TENANT_CONFIGURATION_LOCALES) as Locale,
  timezone: enumValue(body.timezone, "timezone", TENANT_CONFIGURATION_TIMEZONES) as Timezone,
  bookingHorizonDays: boundedNumber(body.bookingHorizonDays, "bookingHorizonDays", 1, 365),
  cancellationWindowReference: machineCode(body.cancellationWindowReference, "cancellationWindowReference", 96),
  reminderPolicyReference: machineCode(body.reminderPolicyReference, "reminderPolicyReference", 96),
  supportContactAlias: machineCode(body.supportContactAlias, "supportContactAlias", 80),
  facilityDisplayDefault: enumValue(body.facilityDisplayDefault, "facilityDisplayDefault", TENANT_FACILITY_DISPLAY_DEFAULTS) as FacilityDefault,
  moduleVisibilityRequestsJson: JSON.stringify(modules(body.moduleVisibilityRequests)),
  rationale: clean(body.rationale, "rationale", 1200, 12),
}; }

async function configuration(configurationId: string) { const item = (await (await getDb()).select().from(tenantConfigurationDrafts).where(eq(tenantConfigurationDrafts.id, configurationId)).limit(1))[0]; if (!item) throw new TenantConfigurationValidationError("Configuration was not found"); return item; }
async function event(input: { actorUserId: string; eventCode: string; configurationId?: string; organizationId?: string; previousStatus?: string; nextStatus?: string; reasonCode?: string; configurationVersion?: number }) {
  await (await getDb()).insert(tenantConfigurationEvents).values({ id: crypto.randomUUID(), configurationId: input.configurationId ?? null, organizationId: input.organizationId ?? null, actorUserId: input.actorUserId, eventCode: input.eventCode, previousStatus: input.previousStatus ?? null, nextStatus: input.nextStatus ?? null, reasonCode: input.reasonCode ?? null, configurationVersion: input.configurationVersion ?? null, evidenceJson: JSON.stringify({ codedEvidenceOnly: true, configurationValuesIncluded: false, runtimeApplied: false, automaticApproval: false, externalSync: false, secretStored: false, crossTenantOverride: false }), createdAt: new Date() });
}
function safe(item: typeof tenantConfigurationDrafts.$inferSelect) { return { ...item, moduleVisibilityRequests: parseModules(item.moduleVisibilityRequestsJson), moduleVisibilityRequestsJson: undefined, runtimeApplied: false }; }

export async function getOrganizationTenantConfiguration(userId: string) {
  const memberships = (await getActiveMemberships(userId)).filter((item) => ownerRoles.includes(item.role as typeof ownerRoles[number])); if (!memberships.length) throw new AuthorizationDeniedError();
  const organizationIds = memberships.map((item) => item.organizationId), rows = await (await getDb()).select().from(tenantConfigurationDrafts).where(inArray(tenantConfigurationDrafts.organizationId, organizationIds)).orderBy(desc(tenantConfigurationDrafts.updatedAt));
  return { memberships, configurations: rows.map(safe), options: { locales: TENANT_CONFIGURATION_LOCALES, timezones: TENANT_CONFIGURATION_TIMEZONES, facilityDisplayDefaults: TENANT_FACILITY_DISPLAY_DEFAULTS, modules: TENANT_VISIBLE_MODULES }, boundaries: TENANT_CONFIGURATION_BOUNDARIES, approvalEffect: "evidence_only" };
}

export async function saveTenantConfigurationDraft(userId: string, body: Record<string, unknown>) {
  const organizationId = identifier(body.organizationId, "organizationId"); await requireOrganizationRole(userId, organizationId, ownerRoles); const input = configurationInput(body), db = await getDb(), now = new Date();
  if (body.configurationId) { const configurationId = identifier(body.configurationId, "configurationId"), current = await configuration(configurationId); if (current.organizationId !== organizationId || current.preparedByUserId !== userId || !["draft", "returned"].includes(current.status)) throw new AuthorizationDeniedError(); const version = versionValue(body.version), nextVersion = version + 1; const changed = await db.update(tenantConfigurationDrafts).set({ ...input, status: "draft", reviewedByUserId: null, reviewReasonCode: null, reviewedAt: null, version: nextVersion, updatedAt: now }).where(and(eq(tenantConfigurationDrafts.id, configurationId), eq(tenantConfigurationDrafts.organizationId, organizationId), eq(tenantConfigurationDrafts.preparedByUserId, userId), eq(tenantConfigurationDrafts.version, version), inArray(tenantConfigurationDrafts.status, ["draft", "returned"]))).returning({ id: tenantConfigurationDrafts.id }); if (!changed[0]) throw new TenantConfigurationConflictError(); await event({ actorUserId: userId, eventCode: "tenant_configuration_revised", configurationId, organizationId, previousStatus: current.status, nextStatus: "draft", configurationVersion: nextVersion }); return { id: configurationId, status: "draft", version: nextVersion, runtimeApplied: false }; }
  const id = crypto.randomUUID(); await db.insert(tenantConfigurationDrafts).values({ id, organizationId, ...input, status: "draft", preparedByUserId: userId, version: 1, createdAt: now, updatedAt: now }); await event({ actorUserId: userId, eventCode: "tenant_configuration_prepared", configurationId: id, organizationId, nextStatus: "draft", configurationVersion: 1 }); return { id, status: "draft", version: 1, runtimeApplied: false };
}

export async function submitTenantConfiguration(userId: string, body: Record<string, unknown>) {
  const current = await configuration(identifier(body.configurationId, "configurationId")); await requireOrganizationRole(userId, current.organizationId, ownerRoles); if (current.preparedByUserId !== userId || !["draft", "returned"].includes(current.status)) throw new TenantConfigurationIndependenceError("Only the original maker can submit this configuration."); const version = versionValue(body.version), nextVersion = version + 1; const changed = await (await getDb()).update(tenantConfigurationDrafts).set({ status: "pending_review", reviewedByUserId: null, reviewReasonCode: null, reviewedAt: null, version: nextVersion, updatedAt: new Date() }).where(and(eq(tenantConfigurationDrafts.id, current.id), eq(tenantConfigurationDrafts.organizationId, current.organizationId), eq(tenantConfigurationDrafts.preparedByUserId, userId), eq(tenantConfigurationDrafts.version, version), inArray(tenantConfigurationDrafts.status, ["draft", "returned"]))).returning({ id: tenantConfigurationDrafts.id }); if (!changed[0]) throw new TenantConfigurationConflictError(); await event({ actorUserId: userId, eventCode: "tenant_configuration_submitted", configurationId: current.id, organizationId: current.organizationId, previousStatus: current.status, nextStatus: "pending_review", configurationVersion: nextVersion }); return { id: current.id, status: "pending_review", version: nextVersion, runtimeApplied: false };
}

export async function reviewTenantConfiguration(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const current = await configuration(identifier(body.configurationId, "configurationId")); if (current.status !== "pending_review" || current.preparedByUserId === userId) throw new TenantConfigurationIndependenceError(); const decision = body.decision === "approve" ? "approved" : body.decision === "return" ? "returned" : null; if (!decision) throw new TenantConfigurationValidationError("decision is invalid"); const reasonCode = machineCode(body.reasonCode ?? (decision === "approved" ? "configuration_reviewed" : "correction_required"), "reasonCode", 80), version = versionValue(body.version), nextVersion = version + 1, now = new Date(); const changed = await (await getDb()).update(tenantConfigurationDrafts).set({ status: decision, reviewedByUserId: userId, reviewReasonCode: reasonCode, reviewedAt: now, version: nextVersion, updatedAt: now }).where(and(eq(tenantConfigurationDrafts.id, current.id), eq(tenantConfigurationDrafts.status, "pending_review"), eq(tenantConfigurationDrafts.version, version), ne(tenantConfigurationDrafts.preparedByUserId, userId))).returning({ id: tenantConfigurationDrafts.id }); if (!changed[0]) throw new TenantConfigurationConflictError(); await event({ actorUserId: userId, eventCode: decision === "approved" ? "tenant_configuration_approved_as_evidence" : "tenant_configuration_returned", configurationId: current.id, organizationId: current.organizationId, previousStatus: "pending_review", nextStatus: decision, reasonCode, configurationVersion: nextVersion }); return { id: current.id, status: decision, version: nextVersion, runtimeApplied: false, approvalEffect: "evidence_only" };
}

export async function retireTenantConfiguration(userId: string, body: Record<string, unknown>) {
  await requirePlatformRole(userId, ["platform_admin"]); const current = await configuration(identifier(body.configurationId, "configurationId")); if (current.status !== "approved") throw new TenantConfigurationValidationError("Only approved evidence can be retired"); const version = versionValue(body.version), reasonCode = machineCode(body.reasonCode, "reasonCode", 80), nextVersion = version + 1, now = new Date(); const changed = await (await getDb()).update(tenantConfigurationDrafts).set({ status: "retired", retiredByUserId: userId, retiredAt: now, retirementReasonCode: reasonCode, version: nextVersion, updatedAt: now }).where(and(eq(tenantConfigurationDrafts.id, current.id), eq(tenantConfigurationDrafts.status, "approved"), eq(tenantConfigurationDrafts.version, version))).returning({ id: tenantConfigurationDrafts.id }); if (!changed[0]) throw new TenantConfigurationConflictError(); await event({ actorUserId: userId, eventCode: "tenant_configuration_retired", configurationId: current.id, organizationId: current.organizationId, previousStatus: "approved", nextStatus: "retired", reasonCode, configurationVersion: nextVersion }); return { id: current.id, status: "retired", version: nextVersion, runtimeApplied: false };
}

export async function getTenantConfigurationGovernance(userId: string) {
  const role = await requirePlatformRole(userId, ["platform_admin", "security_auditor"]), db = await getDb(); const [rows, rehearsals] = await Promise.all([db.select().from(tenantConfigurationDrafts).orderBy(desc(tenantConfigurationDrafts.updatedAt)).limit(250), db.select().from(tenantConfigurationRehearsals).orderBy(desc(tenantConfigurationRehearsals.executedAt)).limit(10)]); const count = (status: string) => rows.filter((item) => item.status === status).length; return { role: role.role, visibility: role.role === "security_auditor" ? "aggregate_only" : "private_governance_register", metrics: { total: rows.length, drafts: count("draft"), pendingReview: count("pending_review"), approvedEvidence: count("approved"), returned: count("returned"), retired: count("retired"), organizations: new Set(rows.map((item) => item.organizationId)).size }, configurations: role.role === "security_auditor" ? [] : rows.map((item) => ({ ...safe(item), independentReview: Boolean(item.reviewedByUserId && item.reviewedByUserId !== item.preparedByUserId) })), rehearsals, boundaries: TENANT_CONFIGURATION_BOUNDARIES, approvalEffect: "evidence_only" };
}

export async function runTenantConfigurationRehearsal(userId: string) {
  await requirePlatformRole(userId, ["platform_admin", "security_auditor"]); const boundaryValues = Object.values(TENANT_CONFIGURATION_BOUNDARIES); const lifecycle = ["draft", "pending_review", "approved", "returned", "retired"]; const scenarios = [boundaryValues.length === 5, boundaryValues.every((value) => value === false), TENANT_CONFIGURATION_LOCALES.length === 3, TENANT_CONFIGURATION_TIMEZONES.length === 3, TENANT_FACILITY_DISPLAY_DEFAULTS.length === 3, TENANT_VISIBLE_MODULES.length === 8, new Set(TENANT_VISIBLE_MODULES).size === 8, new Set(lifecycle).size === 5, lifecycle.includes("pending_review"), lifecycle.includes("retired"), !lifecycle.includes("active"), !lifecycle.includes("deployed"), 1 >= 1, 365 <= 365, !Number.isSafeInteger(1.5), /^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test("policy.v1"), !/^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test("unsafe value"), ownerRoles.length === 2, ownerRoles.includes("organization_owner"), ownerRoles.includes("organization_admin"), TENANT_CONFIGURATION_BOUNDARIES.tenantConfigurationRuntimeApplication === false, TENANT_CONFIGURATION_BOUNDARIES.tenantConfigurationAutomaticApproval === false, TENANT_CONFIGURATION_BOUNDARIES.tenantConfigurationExternalSync === false, TENANT_CONFIGURATION_BOUNDARIES.tenantConfigurationSecretStorage === false, TENANT_CONFIGURATION_BOUNDARIES.tenantConfigurationCrossTenantOverride === false]; const passedScenarios = scenarios.filter(Boolean).length, scenarioCount = scenarios.length, result = passedScenarios === scenarioCount ? "passed" : "failed", id = crypto.randomUUID(), now = new Date(); await (await getDb()).insert(tenantConfigurationRehearsals).values({ id, suiteVersion: TENANT_CONFIGURATION_REHEARSAL_VERSION, scenarioCount, passedScenarios, failedScenarios: scenarioCount - passedScenarios, recordsChanged: 0, externalRequestsSent: 0, runtimeChanges: 0, result, dataMode: "synthetic_only", executedByUserId: userId, executedAt: now }); await event({ actorUserId: userId, eventCode: "tenant_configuration_zero_side_effect_rehearsal" }); return { id, result, scenarioCount, passedScenarios, failedScenarios: scenarioCount - passedScenarios, recordsChanged: 0, runtimeChanges: 0, externalRequestsSent: 0, zeroOperationalSideEffects: true };
}
