"use client";

import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./admin-health-profile.module.css";

type Governance={visibility:"aggregate_only";metrics:Record<string,number>;privacy:{healthContentsExposed:boolean;patientIdentitiesExposed:boolean;providerAccessAvailable:boolean};rehearsals:Array<{id:string;result:string;scenarioCount:number;executedAt:string}>};
const labels:Record<string,{en:string;ar:string}>={activeProfiles:{en:"Active profiles",ar:"الملفات النشطة"},profilesWithEntries:{en:"Profiles with entries",ar:"ملفات تحتوي معلومات"},activeAllergies:{en:"Active allergy entries",ar:"الحساسيات النشطة"},activeConditions:{en:"Active condition entries",ar:"الحالات النشطة"},activeMedicines:{en:"Active medicine entries",ar:"الأدوية النشطة"},activeAccessibilityNeeds:{en:"Accessibility needs",ar:"احتياجات سهولة الوصول"},removedEntries:{en:"Removed entries",ar:"المعلومات المحذوفة"}};

export default function HealthProfileGovernancePage(){
  const[lang,setLang]=useReyatiLocale(),ar=lang==="ar";
  const[data,setData]=useState<Governance|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const response=await fetch("/api/admin/health-profile",{cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error);setData(payload.data);setError("")}catch{setError(ar?"تعذر تحميل حوكمة الملف الصحي.":"Health-profile governance could not be loaded.")}},[ar]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function rehearse(){setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/admin/health-profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"run_rehearsal"})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error);setMessage(ar?"نجحت 20 حالة من دون أي أثر على الملفات أو الرعاية.":"All 20 scenarios passed with zero profile, care, or external side effects.");await load()}catch{setError(ar?"تعذر تشغيل الاختبار الآمن.":"The safe boundary rehearsal could not be completed.")}finally{setBusy(false)}}
  return <main className={styles.shell} dir={ar?"rtl":"ltr"}>
    <header className={styles.top}><a href="/admin"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya"/></a><nav><a href="/admin">{ar?"العمليات":"Operations"}</a><a href="/admin/audit">{ar?"التدقيق":"Audit"}</a><button type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></nav></header>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{ar?"حوكمة مجمعة تحافظ على الخصوصية":"Privacy-preserving aggregate governance"}</span><h1>{ar?"حوكمة الملف الصحي الشخصي":"Personal health profile governance"}</h1><p>{ar?"راقب تبني الميزة وحدود السلامة من خلال أرقام مجمعة فقط، من دون الوصول إلى هوية المريض أو محتوى أي معلومة صحية.":"Monitor adoption and safety boundaries through aggregate counts only, without access to patient identity or the contents of any health entry."}</p></div></section>
    <div className={styles.content}>
      <section className={styles.boundary}><span className={styles.shield}>✓</span><div><strong>{ar?"لا يوجد مسار للوصول إلى الملفات الفردية":"No path to individual profiles"}</strong><p>{ar?"لا تظهر الأسماء أو الحساسية أو الحالات أو الأدوية أو احتياجات سهولة الوصول. ولا يتوفر وصول لمقدمي الرعاية.":"Names, allergies, conditions, medicines, and accessibility details are never shown. Provider access is unavailable."}</p></div><span className={styles.private}>{ar?"مقاييس فقط":"METRICS ONLY"}</span></section>
      {message&&<p className={styles.status} role="status">{message}</p>}{error&&<p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
      <section className={`${styles.workspace} ${styles.adminPanel}`}><div className={styles.adminHead}><div><h2>{ar?"مقاييس الحوكمة":"Governance metrics"}</h2><p>{ar?"أعداد مجمعة لا تكشف محتوى أو هوية.":"Aggregate counts that reveal neither content nor identity."}</p></div><span className={styles.aggregate}>{data?.visibility==="aggregate_only"?(ar?"مجمعة فقط":"AGGREGATE ONLY"):"—"}</span></div><div className={styles.metricGrid}>{Object.entries(data?.metrics??{}).map(([key,value])=><article className={styles.metric} key={key}><b>{value}</b><span>{labels[key]?.[ar?"ar":"en"]??key}</span></article>)}</div></section>
      <section className={`${styles.workspace} ${styles.adminPanel}`}><div className={styles.adminHead}><div><h2>{ar?"اختبار الحدود دون آثار جانبية":"Zero-side-effect boundary rehearsal"}</h2><p>{ar?"يتحقق من الملكية والإصدارات ودورة الحياة ومنع وصول مقدمي الرعاية والاستخدام السريري والتبادل الخارجي والتوصيات.":"Validates ownership, versioning, lifecycle, and the absence of provider access, clinical use, external exchange, and recommendations."}</p></div><button className={styles.run} type="button" disabled={busy} onClick={()=>void rehearse()}>{busy?(ar?"جارٍ التشغيل…":"Running…"):(ar?"تشغيل 20 حالة":"Run 20 scenarios")}</button></div><div className={styles.rehearsals}>{data?.rehearsals.map(item=><article key={item.id}><strong>{item.result}</strong><span>{item.scenarioCount} {ar?"حالة":"scenarios"}</span><small>{new Date(item.executedAt).toLocaleString(ar?"ar-QA":"en-QA")}</small></article>)}</div></section>
    </div>
  </main>
}
