"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "../../care-plan/care-plans.module.css";

type Rehearsal={id:string;scenarioCount:number;passedScenarios:number;failedScenarios:number;plansCreated:number;clinicalInstructionsChanged:number;externalMessagesSent:number;deviceActionsTriggered:number;result:string;executedAt:string};
type Data={role:string;metrics:Record<string,number>;rehearsals:Rehearsal[];contentVisibility:string};
async function api(init?:RequestInit){const response=await fetch("/api/admin/care-plans",{cache:"no-store",credentials:"same-origin",...init});if(response.status===401){location.assign("/signin-with-chatgpt?return_to=/admin/care-plans");throw Error("Authentication required")}const payload=await response.json().catch(()=>({}));if(!response.ok||payload.data===undefined)throw Error(payload.message||payload.error||"Care plan governance is unavailable");return payload.data as Data}
function date(value:string){return new Intl.DateTimeFormat("en-QA",{timeZone:"Asia/Qatar",dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
export default function AdminCarePlansPage(){const[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const load=useCallback(async()=>setData(await api()),[]);useEffect(()=>{queueMicrotask(()=>void load().catch(e=>setError(e.message)))},[load]);async function rehearse(){setBusy(true);setError("");try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"run_rehearsal"})});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to run rehearsal")}finally{setBusy(false)}}
return <main className={styles.providerLayout} id="main-content"><aside className={styles.side}><a href="/admin"><img src="/brand/qivaya-logo-reversed.png" alt="Qivaya"/></a><nav><a href="/admin">Admin overview</a><a className={styles.active} href="/admin/care-plans">Care plan governance</a><a href="/admin/audit">Audit</a><a href="/admin/operations">System health</a></nav></aside><section className={styles.content}><header className={styles.heading}><div><p className={styles.eyebrow}>AGGREGATE CARE PLAN GOVERNANCE</p><h1>Lifecycle assurance without exposing clinical content.</h1><p className={styles.muted}>{data?.contentVisibility||"Loading aggregate controls…"}</p></div><span className={styles.pill}>{data?.role?.replaceAll("_"," ")||"Authorizing role"}</span></header>{error&&<p className={`${styles.notice} ${styles.error}`}>{error}</p>}<section className={styles.metrics}>{data&&Object.entries(data.metrics).map(([key,value])=><article className={styles.metric} key={key}><b>{value}</b><span className={styles.muted}>{key.replaceAll(/([A-Z])/g," $1").toLowerCase()}</span></article>)}</section><section className={styles.grid}><article className={styles.section}><p className={styles.eyebrow}>CLINICAL AUTHORITY BOUNDARY</p><h2>Verified humans stay accountable</h2><p className={styles.muted}>Plans originate from eligible appointments. Every revision is a new immutable snapshot. Patients may acknowledge, record a bounded progress band, or request review, but cannot edit instructions.</p><p className={styles.notice}>No diagnosis, autonomous recommendation, device integration, clinical automation, or external messaging is enabled.</p></article><article className={styles.section}><p className={styles.eyebrow}>SYNTHETIC SAFETY REHEARSAL</p><h2>Fourteen scenarios, zero side effects</h2><p className={styles.muted}>Covers provider verification, appointment ownership, bilingual completeness, accountable owners, due dates, immutable versions, patient scope, optimistic concurrency, review routing, emergency language, audit minimization, notification minimization, aggregate privacy, and disabled integrations.</p><button className={styles.button} disabled={busy||data?.role!=="platform_admin"} onClick={()=>void rehearse()}>{busy?"Running rehearsal…":"Run complete rehearsal"}</button></article></section><section className={styles.section}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>REHEARSAL LEDGER</p><h2>Non-destructive evidence</h2></div></div><div className={styles.ledger}>{data?.rehearsals.map(item=><div className={styles.ledgerRow} key={item.id}><b>{item.result.toUpperCase()}</b><span>{item.passedScenarios}/{item.scenarioCount} scenarios</span><span>0 plans · 0 instruction changes · 0 external · 0 device actions</span><small>{date(item.executedAt)}</small></div>)}{data&&!data.rehearsals.length&&<p className={styles.muted}>No rehearsal has been run yet.</p>}</div></section></section></main>}
