"use client";

import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./account-security.module.css";

type Session = { id:string;deviceLabel:string;platformFamily:string;browserFamily:string;status:string;current:boolean;lastActiveAt:string;createdAt:string;expiresAt:string;revokedAt:string|null;version:number;providerManaged?:boolean };
type SecurityEvent = { id:string;eventType:string;outcome:string;reasonCode:string|null;occurredAt:string };
type Workspace = { sessions:Session[];events:SecurityEvent[];reauthentication:{sensitiveActionsRequireCurrentAuthenticatedSession:boolean;freshIdentityProviderReauthenticationAvailable:boolean;currentSessionRevocationAllowed:boolean;hostedChatGPTSessionTerminationAvailable:boolean};privacy:{tokensExposed:boolean;ipAddressesExposed:boolean;rawUserAgentsExposed:boolean;preciseLocationsExposed:boolean} };

export default function AccountSecurityPage(){
  const[lang,setLang]=useReyatiLocale(),ar=lang==="ar",[data,setData]=useState<Workspace|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const load=useCallback(async(signal?:AbortSignal)=>{try{const response=await fetch("/api/account/security",{cache:"no-store",signal});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.error);setData(payload.data);setError("")}catch(cause){if(cause instanceof DOMException&&cause.name==="AbortError")return;setError(ar?"تعذر تحميل أمان الحساب. حاول مرة أخرى.":"Account security could not be loaded. Try again.")}},[ar]);
  useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)void load(controller.signal)});return()=>controller.abort()},[load]);
  async function revoke(body:Record<string,unknown>){setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/account/security",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,requestId:crypto.randomUUID(),confirmCurrentAuthenticatedSession:true,reasonCode:"user_security_choice"})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.error);setMessage(ar?`تم إنهاء ${payload.data.affectedCount} من جلسات تسجيل الدخول الأخرى. ستحتاج تلك الأجهزة إلى تسجيل الدخول مجدداً.`:`${payload.data.affectedCount} other sign-in session(s) ended. Those devices must sign in again.`);await load()}catch(cause){setError(cause instanceof Error?cause.message:(ar?"تعذر إكمال الإجراء.":"The action could not be completed."))}finally{setBusy(false)}}
  const locale=ar?"ar-QA":"en-QA",active=data?.sessions.filter(item=>item.status==="active")??[],otherActive=active.filter(item=>!item.current);
  const eventLabel=(value:string)=>({session_observed:ar?"تم التعرف على جلسة Qivaya":"Qivaya session observed",session_revoked:ar?"تم إلغاء جلسة Qivaya":"Qivaya session revoked",other_sessions_revoked:ar?"تم إلغاء الجلسات الأخرى":"Other Qivaya sessions revoked",identity_session_revoked:ar?"تم إنهاء جلسة تسجيل دخول":"Sign-in session ended",identity_other_sessions_revoked:ar?"تم إنهاء جلسات تسجيل الدخول الأخرى":"Other sign-in sessions ended"}[value]??value.replaceAll("_"," "));
  return <main className={`${styles.shell} trust-center-shell account-security-experience`} dir={ar?"rtl":"ltr"}>
    <header className={styles.top}><a href="/"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya"/></a><nav><a href="/account/identity">{ar?"كلمة المرور والتحقق":"Password & MFA"}</a><a href="/notifications">{ar?"الإشعارات":"Notifications"}</a><a href="/support">{ar?"الدعم":"Support"}</a><button type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></nav></header>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{ar?"حسابك، تحت سيطرتك":"Your account, under your control"}</span><h1>{ar?"أمان الحساب والجلسات":"Account security & sessions"}</h1><p>{ar?"راجع الأجهزة المسجلة في حسابك وأنهِ أي جلسة لا تتعرف عليها. تتم إدارة كلمات المرور والتحقق متعدد العوامل بأمان بواسطة موفر الهوية.":"Review devices signed in to your account and end any session you do not recognize. Passwords and multi-factor authentication are managed securely by the identity provider."}</p></div></section>
    <div className={styles.content}>
      <section className={styles.boundary}><span className={styles.shield}>✓</span><div><strong>{ar?"خصوصية الجهاز مدمجة":"Device privacy is built in"}</strong><p>{ar?"نعرض نوع المنصة والمتصفح بشكل تقريبي فقط. لا نعرض رمز جلسة أو عنوان IP أو موقعاً دقيقاً أو معلومات المتصفح الخام.":"Only an approximate platform and browser family are shown. Session tokens, IP addresses, precise location, and raw browser details are never displayed."}</p></div><span className={styles.private}>{ar?"خاص":"PRIVATE"}</span></section>
      {message&&<p className={styles.status} role="status">{message}</p>}{error&&<p className={`${styles.status} ${styles.error}`} role="alert">{error} <button className={styles.secondary} type="button" onClick={()=>void load()}>{ar?"إعادة المحاولة":"Retry"}</button></p>}
      <section className={styles.panel} aria-busy={!data}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar?"جلسات تسجيل الدخول":"Sign-in sessions"}</span><h2>{ar?"أجهزتك النشطة":"Your active devices"}</h2><p className={styles.muted}>{ar?"الجلسة الحالية محمية. استخدم تسجيل الخروج من قائمة الحساب لإنهائها.":"Your current session is protected. Use sign out from the account menu to end it."}</p></div><button className={styles.danger} type="button" disabled={busy||otherActive.length===0} onClick={()=>void revoke({action:"revoke_other_sessions"})}>{ar?"إنهاء الجلسات الأخرى":"End other sessions"}</button></div>
        {!data?<div className={styles.empty}>{ar?"جارٍ تحميل الجلسات…":"Loading sessions…"}</div>:active.length===0?<div className={styles.empty}><b>{ar?"لا توجد جلسات نشطة مسجلة":"No active sessions recorded"}</b><p>{ar?"حدّث الصفحة لإعادة إنشاء سجل الجلسة الحالية بأمان.":"Refresh to safely establish the current session record."}</p></div>:<div className={styles.grid}>{active.map(session=><article className={`${styles.card} ${session.current?styles.current:""}`} key={session.id}><div className={styles.cardTop}><div className={styles.deviceRow}><span className={styles.device} aria-hidden="true">{session.current?"●":"○"}</span><div><h3>{session.deviceLabel}</h3><p className={styles.muted}>{session.platformFamily} · {session.browserFamily}</p></div></div>{session.current&&<span className={styles.pill}>{ar?"هذه الجلسة":"Current"}</span>}</div><div className={styles.meta}><div><small>{ar?"آخر نشاط":"Last activity"}</small><b>{new Date(session.lastActiveAt).toLocaleString(locale)}</b></div><div><small>{ar?"أول تسجيل":"First recorded"}</small><b>{new Date(session.createdAt).toLocaleDateString(locale)}</b></div></div><div className={styles.cardFoot}><small>{ar?"تنتهي المدة":"Expires"} {new Date(session.expiresAt).toLocaleDateString(locale)}</small><div className={styles.actions}>{session.current?<span className={styles.muted}>{ar?"محمية":"Protected"}</span>:<button className={styles.danger} type="button" disabled={busy} onClick={()=>void revoke({action:"revoke_session",sessionId:session.id,version:session.version})}>{ar?"إلغاء هذه الجلسة":"Revoke session"}</button>}</div></div></article>)}</div>}
        <p className={styles.localNote}>{ar?"إنهاء جلسة يؤدي إلى إلغائها لدى Clerk وتسجيل خروج ذلك الجهاز من Qivaya. لا يتم عرض رموز الجلسة أو عناوين IP أو الموقع الدقيق هنا.":"Ending a session revokes it with Clerk and signs that device out of Qivaya. Session tokens, IP addresses, and precise location are never displayed here."}</p>
      </section>
      <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar?"سجل الأمان":"Security history"}</span><h2>{ar?"النشاط الأخير":"Recent activity"}</h2></div><span className={styles.private}>{ar?"من دون رموز أو عناوين IP":"NO TOKENS OR IPs"}</span></div>{!data?.events.length?<div className={styles.empty}>{ar?"لا توجد أحداث أمان مسجلة بعد.":"No security events have been recorded yet."}</div>:<div className={styles.events}>{data.events.map(item=><div className={styles.event} key={item.id}><span className={styles.dot}/><div><b>{eventLabel(item.eventType)}</b><small>{item.outcome}{item.reasonCode?` · ${item.reasonCode.replaceAll("_"," ")}`:""}</small></div><time dateTime={item.occurredAt}>{new Date(item.occurredAt).toLocaleString(locale)}</time></div>)}</div>}</section>
    </div>
  </main>
}
