import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { documentActivationWindows, users } from "./schema";

export const documentStabilityAssuranceRuns = sqliteTable("document_stability_assurance_runs", {
  id: text("id").primaryKey(),
  activationWindowId: text("activation_window_id").notNull().references(() => documentActivationWindows.id, { onDelete: "restrict" }),
  collectedByUserId: text("collected_by_user_id").notNull().references(() => users.id, { onDelete: "restrict" }),
  clientRequestId: text("client_request_id").notNull(),
  frameworkVersion: text("framework_version").notNull(),
  evidenceReference: text("evidence_reference").notNull(),
  targetEnvironment: text("target_environment").notNull().default("production"),
  observationStartedAt: integer("observation_started_at", { mode: "timestamp_ms" }).notNull(),
  observationEndedAt: integer("observation_ended_at", { mode: "timestamp_ms" }).notNull(),
  observationWindowMinutes: integer("observation_window_minutes").notNull(),
  protectedStorageConfigured: integer("protected_storage_configured", { mode: "boolean" }).notNull().default(false),
  privateScannerConfigured: integer("private_scanner_configured", { mode: "boolean" }).notNull().default(false),
  runtimeControlsEnabled: integer("runtime_controls_enabled", { mode: "boolean" }).notNull().default(false),
  totalDocumentCount: integer("total_document_count").notNull().default(0),
  quarantinedDocumentCount: integer("quarantined_document_count").notNull().default(0),
  stuckScanJobCount: integer("stuck_scan_job_count").notNull().default(0),
  failedScanJobCount: integer("failed_scan_job_count").notNull().default(0),
  failedDeletionJobCount: integer("failed_deletion_job_count").notNull().default(0),
  legalHoldConflictCount: integer("legal_hold_conflict_count").notNull().default(0),
  failedRetentionRunCount: integer("failed_retention_run_count").notNull().default(0),
  activeIncidentCount: integer("active_incident_count").notNull().default(0),
  checkCount: integer("check_count").notNull(),
  passedChecks: integer("passed_checks").notNull(),
  failedChecks: integer("failed_checks").notNull(),
  checkResultsJson: text("check_results_json").notNull(),
  result: text("result").notNull(),
  decision: text("decision").notNull().default("pending"),
  reviewedByUserId: text("reviewed_by_user_id").references(() => users.id, { onDelete: "restrict" }),
  reviewNote: text("review_note"),
  reviewedAt: integer("reviewed_at", { mode: "timestamp_ms" }),
  dataMode: text("data_mode").notNull().default("aggregate_only"),
  customerRecordsRead: integer("customer_records_read").notNull().default(0),
  objectsRead: integer("objects_read").notNull().default(0),
  objectsChanged: integer("objects_changed").notNull().default(0),
  scannerCallsMade: integer("scanner_calls_made").notNull().default(0),
  externalMessagesSent: integer("external_messages_sent").notNull().default(0),
  version: integer("version").notNull().default(1),
  collectedAt: integer("collected_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("idx_document_assurance_request").on(table.collectedByUserId, table.clientRequestId),
  index("idx_document_assurance_activation_collected").on(table.activationWindowId, table.collectedAt),
  index("idx_document_assurance_result_decision").on(table.result, table.decision, table.collectedAt),
]);

export const documentStabilityAssuranceEvents = sqliteTable("document_stability_assurance_events", {
  id: text("id").primaryKey(),
  assuranceRunId: text("assurance_run_id").notNull().references(() => documentStabilityAssuranceRuns.id, { onDelete: "restrict" }),
  actorUserId: text("actor_user_id").notNull().references(() => users.id, { onDelete: "restrict" }),
  eventCode: text("event_code").notNull(),
  previousDecision: text("previous_decision"),
  nextDecision: text("next_decision").notNull(),
  codedDetailsJson: text("coded_details_json").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  index("idx_document_assurance_event_run_created").on(table.assuranceRunId, table.createdAt),
  index("idx_document_assurance_event_code_created").on(table.eventCode, table.createdAt),
]);
