import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { patientProfiles, users } from "./schema";

const owned = { patientId: text("patient_id").notNull().references(() => patientProfiles.id, { onDelete: "restrict" }), status: text("status").notNull().default("active"), version: integer("version").notNull().default(1), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull() };
export const documentCaptureDrafts = sqliteTable("document_capture_drafts", { id: text("id").primaryKey(), ...owned, documentCategory: text("document_category").notNull(), documentDate: text("document_date"), sourceOrganization: text("source_organization"), draftText: text("draft_text").notNull(), confirmationState: text("confirmation_state").notNull().default("draft"), sourceLabel: text("source_label").notNull().default("patient_entered_unverified") }, t => [index("idx_capture_patient_status").on(t.patientId, t.status, t.updatedAt)]);
export const healthRecordIndexEntries = sqliteTable("health_record_index_entries", { id: text("id").primaryKey(), ...owned, recordType: text("record_type").notNull(), recordDate: text("record_date").notNull(), title: text("title").notNull(), sourceType: text("source_type").notNull(), sourceReference: text("source_reference"), sourceLabel: text("source_label").notNull().default("patient_entered_unverified") }, t => [index("idx_record_index_patient_date").on(t.patientId, t.recordDate), index("idx_record_index_patient_status").on(t.patientId, t.status)]);
export const healthSharingDirectives = sqliteTable("health_sharing_directives", { id: text("id").primaryKey(), ...owned, purposeCode: text("purpose_code").notNull(), scopeCode: text("scope_code").notNull(), durationDays: integer("duration_days").notNull(), recipientType: text("recipient_type").notNull(), directiveState: text("directive_state").notNull().default("recorded_preference") }, t => [index("idx_sharing_directive_patient_status").on(t.patientId, t.status, t.updatedAt)]);
export const healthWalletAccessEvents = sqliteTable("health_wallet_access_events", { id: text("id").primaryKey(), patientId: text("patient_id").notNull().references(() => patientProfiles.id, { onDelete: "restrict" }), actorType: text("actor_type").notNull(), actionCode: text("action_code").notNull(), resourceType: text("resource_type").notNull(), outcomeCode: text("outcome_code").notNull(), purposeCode: text("purpose_code"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, t => [index("idx_wallet_access_patient_created").on(t.patientId, t.createdAt)]);
export const healthDataQualityConcerns = sqliteTable("health_data_quality_concerns", { id: text("id").primaryKey(), ...owned, recordReference: text("record_reference").notNull(), issueType: text("issue_type").notNull(), description: text("description").notNull(), workflowState: text("workflow_state").notNull().default("submitted") }, t => [index("idx_quality_patient_state").on(t.patientId, t.workflowState, t.updatedAt)]);
export const healthWalletOperationEvents = sqliteTable("health_wallet_operation_events", { id: text("id").primaryKey(), patientId: text("patient_id").notNull().references(() => patientProfiles.id, { onDelete: "restrict" }), module: text("module").notNull(), recordId: text("record_id").notNull(), actorUserId: text("actor_user_id").notNull().references(() => users.id, { onDelete: "restrict" }), action: text("action").notNull(), nextStatus: text("next_status").notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, t => [index("idx_wallet_operations_record").on(t.module, t.recordId, t.createdAt)]);
export const healthWalletOperationRehearsals = sqliteTable("health_wallet_operation_rehearsals", { id: text("id").primaryKey(), suiteVersion: text("suite_version").notNull(), scenarioCount: integer("scenario_count").notNull(), passedScenarios: integer("passed_scenarios").notNull(), filesAccepted: integer("files_accepted").notNull(), ocrRuns: integer("ocr_runs").notNull(), accessGranted: integer("access_granted").notNull(), clinicalRecordsChanged: integer("clinical_records_changed").notNull(), externalTransfers: integer("external_transfers").notNull(), result: text("result").notNull(), executedByUserId: text("executed_by_user_id").notNull().references(() => users.id, { onDelete: "restrict" }), executedAt: integer("executed_at", { mode: "timestamp_ms" }).notNull() }, t => [index("idx_wallet_rehearsal_executed").on(t.executedAt)]);
export const healthWalletOperationsSchema = { documentCaptureDrafts, healthRecordIndexEntries, healthSharingDirectives, healthWalletAccessEvents, healthDataQualityConcerns, healthWalletOperationEvents, healthWalletOperationRehearsals };
