import { drizzle } from "drizzle-orm/d1";
import { D1RestDatabase } from "./d1-rest";
import { getRuntimeEnv } from "@/lib/runtime-env";
import * as coreSchema from "./schema";
import * as digitalQueueSchema from "./digital-queue-schema";
import * as homeCareSchema from "./home-care-schema";
import * as laboratorySchema from "./laboratory-schema";
import * as encounterContinuitySchema from "./encounter-continuity-schema";
import * as pharmacyFulfilmentSchema from "./pharmacy-fulfilment-schema";
import * as sampleCollectionSchema from "./sample-collection-schema";
import * as employerBenefitsSchema from "./employer-benefits-schema";
import * as patientReviewsSchema from "./patient-reviews-schema";
import * as financeControlsSchema from "./finance-controls-schema";
import * as carePlansSchema from "./care-plans-schema";
import * as diagnosticImagingSchema from "./diagnostic-imaging-schema";
import * as insuranceAuthorizationSchema from "./insurance-authorization-schema";
import * as savedCareSchema from "./saved-care-schema";
import * as privacyRightsSchema from "./privacy-rights-schema";
import * as healthContentSchema from "./health-content-schema";
import * as emergencyProfileSchema from "./emergency-profile-schema";
import * as personalHealthProfileSchema from "./personal-health-profile-schema";
import * as consentCenterSchema from "./consent-center-schema";
import * as complaintsSchema from "./complaints-schema";
import * as accountSecuritySchema from "./account-security-schema";
import * as notificationPreferencesModuleSchema from "./notification-preferences-schema";
import * as catalogueGovernanceSchema from "./catalogue-governance-schema";
import * as accessibilitySettingsModuleSchema from "./accessibility-settings-schema";
import * as facilityDirectorySchema from "./facility-directory-schema";
import * as releaseControlsSchema from "./release-controls-schema";
import * as patientProfileSettingsModuleSchema from "./patient-profile-settings-schema";
import * as tenantConfigurationSchema from "./tenant-configuration-schema";
import * as policyTemplatesSchema from "./policy-templates-schema";
import * as serviceStatusSchema from "./service-status-schema";
import * as providerOperationsSchema from "./provider-operations-schema";
import * as partnerGovernanceSchema from "./partner-governance-schema";
import * as verificationLifecycleSchema from "./verification-lifecycle-schema";
import * as workforceGovernanceSchema from "./workforce-governance-schema";
import * as providerCoverageSchema from "./provider-coverage-schema";
import * as appointmentJourneySchema from "./appointment-journey-schema";
import * as personalTrackingSchema from "./personal-tracking-schema";
import * as healthWalletOperationsSchema from "./health-wallet-operations-schema";
import * as releaseTwoReadinessSchema from "./release-two-readiness-schema";
import * as integrationOperationsSchema from "./integration-operations-schema";
import * as integrationAssuranceSchema from "./integration-assurance-schema";
import * as exchangeReconciliationSchema from "./exchange-reconciliation-schema";
import * as integrationLifecycleSchema from "./integration-lifecycle-schema";
import * as integrationSecretsSchema from "./integration-secrets-schema";
import * as integrationCertificatesSchema from "./integration-certificates-schema";
import * as integrationNetworkSchema from "./integration-network-schema";
import * as integrationPayloadSecuritySchema from "./integration-payload-security-schema";
import * as integrationTrafficSchema from "./integration-traffic-schema";
import * as integrationResilienceSchema from "./integration-resilience-schema";
import * as integrationChangeSchema from "./integration-change-schema";
import * as integrationObservabilitySchema from "./integration-observability-schema";
import * as integrationResidencySchema from "./integration-residency-schema";
import * as integrationAccessReviewSchema from "./integration-access-review-schema";
import * as paymentProcessingSchema from "./payment-processing-schema";
import * as documentIncidentsSchema from "./document-incidents-schema";
import * as documentAssuranceSchema from "./document-assurance-schema";
import * as documentReleaseSchema from "./document-release-schema";

const schema = { ...coreSchema, ...digitalQueueSchema, ...homeCareSchema, ...laboratorySchema, ...encounterContinuitySchema, ...pharmacyFulfilmentSchema, ...sampleCollectionSchema, ...employerBenefitsSchema, ...patientReviewsSchema, ...financeControlsSchema, ...carePlansSchema, ...diagnosticImagingSchema, ...insuranceAuthorizationSchema, ...savedCareSchema, ...privacyRightsSchema, ...healthContentSchema, ...emergencyProfileSchema, ...personalHealthProfileSchema, ...consentCenterSchema, ...complaintsSchema, ...accountSecuritySchema, ...notificationPreferencesModuleSchema, ...catalogueGovernanceSchema, ...accessibilitySettingsModuleSchema, ...facilityDirectorySchema, ...releaseControlsSchema, ...patientProfileSettingsModuleSchema, ...tenantConfigurationSchema, ...policyTemplatesSchema, ...serviceStatusSchema, ...providerOperationsSchema, ...partnerGovernanceSchema, ...verificationLifecycleSchema, ...workforceGovernanceSchema, ...providerCoverageSchema, ...appointmentJourneySchema, ...personalTrackingSchema, ...healthWalletOperationsSchema, ...releaseTwoReadinessSchema, ...integrationOperationsSchema, ...integrationAssuranceSchema, ...exchangeReconciliationSchema, ...integrationLifecycleSchema, ...integrationSecretsSchema, ...integrationCertificatesSchema, ...integrationNetworkSchema, ...integrationPayloadSecuritySchema, ...integrationTrafficSchema, ...integrationResilienceSchema, ...integrationChangeSchema, ...integrationObservabilitySchema, ...integrationResidencySchema, ...integrationAccessReviewSchema, ...paymentProcessingSchema, ...documentIncidentsSchema, ...documentAssuranceSchema, ...documentReleaseSchema };

export async function getDb() {
  const env = await getRuntimeEnv();
  if (env.DB) return drizzle(env.DB, { schema });
  const accountId = env.CLOUDFLARE_ACCOUNT_ID?.trim();
  const databaseId = env.CLOUDFLARE_D1_DATABASE_ID?.trim();
  const apiToken = env.CLOUDFLARE_D1_API_TOKEN?.trim();
  if (accountId && databaseId && apiToken) {
    return drizzle(new D1RestDatabase(accountId, databaseId, apiToken) as unknown as D1Database, { schema });
  }
  throw new Error("Database access is unavailable. Configure the Sites DB binding or the scoped Cloudflare D1 REST credentials for Vercel.");
}
