import{index,integer,sqliteTable,text}from"drizzle-orm/sqlite-core";import{users}from"./schema";const common={status:text("status").notNull().default("draft"),version:integer("version").notNull().default(1),createdByUserId:text("created_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp_ms"}).notNull()};
export const integrationVendorProposals=sqliteTable("integration_vendor_proposals",{id:text("id").primaryKey(),vendorReference:text("vendor_reference").notNull(),vendorCategory:text("vendor_category").notNull(),dataResidencyBand:text("data_residency_band").notNull(),assuranceState:text("assurance_state").notNull(),...common},t=>[index("idx_integration_vendor_status").on(t.status,t.updatedAt)]);
export const connectionOnboardingProposals=sqliteTable("connection_onboarding_proposals",{id:text("id").primaryKey(),connectionReference:text("connection_reference").notNull(),vendorReference:text("vendor_reference").notNull(),protocolCode:text("protocol_code").notNull(),environmentCode:text("environment_code").notNull(),readinessBand:text("readiness_band").notNull(),...common},t=>[index("idx_connection_onboarding_status").on(t.status,t.updatedAt)]);
export const integrationMappingProposals=sqliteTable("integration_mapping_proposals",{id:text("id").primaryKey(),mappingReference:text("mapping_reference").notNull(),sourceResource:text("source_resource").notNull(),targetResource:text("target_resource").notNull(),terminologyState:text("terminology_state").notNull(),validationBand:text("validation_band").notNull(),...common},t=>[index("idx_integration_mapping_status").on(t.status,t.updatedAt)]);
export const dataMigrationRehearsalPlans=sqliteTable("data_migration_rehearsal_plans",{id:text("id").primaryKey(),migrationReference:text("migration_reference").notNull(),sourceClass:text("source_class").notNull(),recordBand:text("record_band").notNull(),validationScope:text("validation_scope").notNull(),rollbackState:text("rollback_state").notNull(),...common},t=>[index("idx_migration_plan_status").on(t.status,t.updatedAt)]);
export const integrationIncidentCases=sqliteTable("integration_incident_cases",{id:text("id").primaryKey(),incidentReference:text("incident_reference").notNull(),connectionReference:text("connection_reference").notNull(),severityBand:text("severity_band").notNull(),symptomCode:text("symptom_code").notNull(),containmentState:text("containment_state").notNull(),...common},t=>[index("idx_integration_incident_status").on(t.status,t.updatedAt)]);
export const integrationOperationEvents=sqliteTable("integration_operation_events",{id:text("id").primaryKey(),module:text("module").notNull(),recordId:text("record_id").notNull(),actorUserId:text("actor_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),action:text("action").notNull(),nextStatus:text("next_status").notNull(),createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull()},t=>[index("idx_integration_operation_events").on(t.module,t.recordId,t.createdAt)]);
export const integrationOperationRehearsals=sqliteTable("integration_operation_rehearsals",{id:text("id").primaryKey(),suiteVersion:text("suite_version").notNull(),scenarioCount:integer("scenario_count").notNull(),passedScenarios:integer("passed_scenarios").notNull(),vendorsApproved:integer("vendors_approved").notNull(),connectionsOpened:integer("connections_opened").notNull(),mappingsApplied:integer("mappings_applied").notNull(),recordsMigrated:integer("records_migrated").notNull(),incidentsAutoClosed:integer("incidents_auto_closed").notNull(),result:text("result").notNull(),executedByUserId:text("executed_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),executedAt:integer("executed_at",{mode:"timestamp_ms"}).notNull()},t=>[index("idx_integration_rehearsal_executed").on(t.executedAt)]);
export const integrationOperationsSchema={integrationVendorProposals,connectionOnboardingProposals,integrationMappingProposals,dataMigrationRehearsalPlans,integrationIncidentCases,integrationOperationEvents,integrationOperationRehearsals};
