import{index,integer,sqliteTable,text}from"drizzle-orm/sqlite-core";import{users}from"./schema";const common={status:text("status").notNull().default("draft"),version:integer("version").notNull().default(1),createdByUserId:text("created_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),reviewedByUserId:text("reviewed_by_user_id").references(()=>users.id,{onDelete:"restrict"}),decisionCode:text("decision_code"),submittedAt:integer("submitted_at",{mode:"timestamp_ms"}),reviewedAt:integer("reviewed_at",{mode:"timestamp_ms"}),createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp_ms"}).notNull()};
export const apiContractVersions=sqliteTable("api_contract_versions",{id:text("id").primaryKey(),contractReference:text("contract_reference").notNull(),versionLabel:text("version_label").notNull(),compatibilityClass:text("compatibility_class").notNull(),schemaState:text("schema_state").notNull(),consumerImpactBand:text("consumer_impact_band").notNull(),...common},t=>[index("idx_api_contract_status").on(t.status,t.updatedAt)]);
export const apiDeprecationPlans=sqliteTable("api_deprecation_plans",{id:text("id").primaryKey(),planReference:text("plan_reference").notNull(),contractReference:text("contract_reference").notNull(),noticeWindowBand:text("notice_window_band").notNull(),migrationGuideState:text("migration_guide_state").notNull(),sunsetReadiness:text("sunset_readiness").notNull(),...common},t=>[index("idx_api_deprecation_status").on(t.status,t.updatedAt)]);
export const integrationRetentionPolicies=sqliteTable("integration_retention_policies",{id:text("id").primaryKey(),policyReference:text("policy_reference").notNull(),dataClass:text("data_class").notNull(),retentionBand:text("retention_band").notNull(),legalHoldHandling:text("legal_hold_handling").notNull(),deletionEvidenceState:text("deletion_evidence_state").notNull(),...common},t=>[index("idx_integration_retention_status").on(t.status,t.updatedAt)]);
export const partnerSlaCommitments=sqliteTable("partner_sla_commitments",{id:text("id").primaryKey(),commitmentReference:text("commitment_reference").notNull(),partnerReference:text("partner_reference").notNull(),serviceClass:text("service_class").notNull(),availabilityBand:text("availability_band").notNull(),recoveryBand:text("recovery_band").notNull(),...common},t=>[index("idx_partner_sla_status").on(t.status,t.updatedAt)]);
export const exchangePurposeMappings=sqliteTable("exchange_purpose_mappings",{id:text("id").primaryKey(),mappingReference:text("mapping_reference").notNull(),exchangeFamily:text("exchange_family").notNull(),purposeCode:text("purpose_code").notNull(),consentRequirement:text("consent_requirement").notNull(),minimumDataBand:text("minimum_data_band").notNull(),...common},t=>[index("idx_exchange_purpose_status").on(t.status,t.updatedAt)]);
export const integrationLifecycleEvents=sqliteTable("integration_lifecycle_events",{id:text("id").primaryKey(),module:text("module").notNull(),recordId:text("record_id").notNull(),actorUserId:text("actor_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),action:text("action").notNull(),nextStatus:text("next_status").notNull(),createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull()},t=>[index("idx_integration_lifecycle_events").on(t.module,t.recordId,t.createdAt)]);
export const integrationLifecycleRehearsals=sqliteTable("integration_lifecycle_rehearsals",{id:text("id").primaryKey(),suiteVersion:text("suite_version").notNull(),scenarioCount:integer("scenario_count").notNull(),passedScenarios:integer("passed_scenarios").notNull(),contractsPublished:integer("contracts_published").notNull(),trafficRouted:integer("traffic_routed").notNull(),recordsDeleted:integer("records_deleted").notNull(),slaActionsExecuted:integer("sla_actions_executed").notNull(),consentRulesEnforced:integer("consent_rules_enforced").notNull(),result:text("result").notNull(),executedByUserId:text("executed_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),executedAt:integer("executed_at",{mode:"timestamp_ms"}).notNull()},t=>[index("idx_integration_lifecycle_rehearsal").on(t.executedAt)]);
export const integrationLifecycleSchema={apiContractVersions,apiDeprecationPlans,integrationRetentionPolicies,partnerSlaCommitments,exchangePurposeMappings,integrationLifecycleEvents,integrationLifecycleRehearsals};
