import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { documentRecords, paymentLedgerEntries, users } from "./schema";

export const paymentCheckoutSessions = sqliteTable("payment_checkout_sessions", {
  id: text("id").primaryKey(),
  ledgerEntryId: text("ledger_entry_id").notNull().references(() => paymentLedgerEntries.id, { onDelete: "restrict" }),
  createdByUserId: text("created_by_user_id").notNull().references(() => users.id, { onDelete: "restrict" }),
  clientRequestId: text("client_request_id").notNull(),
  provider: text("provider").notNull().default("stripe"),
  providerSessionId: text("provider_session_id").notNull(),
  providerPaymentIntentId: text("provider_payment_intent_id"),
  status: text("status").notNull().default("open"),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("idx_payment_checkout_provider_session").on(table.provider, table.providerSessionId),
  uniqueIndex("idx_payment_checkout_provider_intent").on(table.provider, table.providerPaymentIntentId),
  uniqueIndex("idx_payment_checkout_client_request").on(table.createdByUserId, table.ledgerEntryId, table.clientRequestId),
  index("idx_payment_checkout_ledger_status_created").on(table.ledgerEntryId, table.status, table.createdAt),
]);

export const paymentProcessorEvents = sqliteTable("payment_processor_events", {
  id: text("id").primaryKey(),
  provider: text("provider").notNull().default("stripe"),
  providerEventId: text("provider_event_id").notNull(),
  eventType: text("event_type").notNull(),
  processingStatus: text("processing_status").notNull().default("received"),
  ledgerEntryId: text("ledger_entry_id").references(() => paymentLedgerEntries.id, { onDelete: "restrict" }),
  errorCode: text("error_code"),
  receivedAt: integer("received_at", { mode: "timestamp_ms" }).notNull(),
  processedAt: integer("processed_at", { mode: "timestamp_ms" }),
}, (table) => [
  uniqueIndex("idx_payment_processor_provider_event").on(table.provider, table.providerEventId),
  index("idx_payment_processor_status_received").on(table.processingStatus, table.receivedAt),
  index("idx_payment_processor_ledger_received").on(table.ledgerEntryId, table.receivedAt),
]);

export const paymentRefundExecutions = sqliteTable("payment_refund_executions", {
  id: text("id").primaryKey(),
  caseId: text("case_id").notNull(),
  adjustmentId: text("adjustment_id").notNull(),
  ledgerEntryId: text("ledger_entry_id").notNull().references(() => paymentLedgerEntries.id, { onDelete: "restrict" }),
  requestedByUserId: text("requested_by_user_id").notNull().references(() => users.id, { onDelete: "restrict" }),
  clientRequestId: text("client_request_id").notNull(),
  provider: text("provider").notNull().default("stripe"),
  providerRefundId: text("provider_refund_id"),
  providerPaymentIntentId: text("provider_payment_intent_id").notNull(),
  amountMinor: integer("amount_minor").notNull(),
  currency: text("currency").notNull().default("qar"),
  status: text("status").notNull().default("requesting"),
  failureCode: text("failure_code"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
}, (table) => [
  uniqueIndex("idx_payment_refund_adjustment").on(table.adjustmentId),
  uniqueIndex("idx_payment_refund_provider_refund").on(table.provider, table.providerRefundId),
  uniqueIndex("idx_payment_refund_client_request").on(table.requestedByUserId, table.adjustmentId, table.clientRequestId),
  index("idx_payment_refund_ledger_status_created").on(table.ledgerEntryId, table.status, table.createdAt),
]);

export const paymentReconciliationRuns = sqliteTable("payment_reconciliation_runs", {
  id: text("id").primaryKey(),
  requestedByUserId: text("requested_by_user_id").notNull().references(() => users.id, { onDelete: "restrict" }),
  clientRequestId: text("client_request_id").notNull(),
  provider: text("provider").notNull().default("stripe"),
  windowStart: integer("window_start", { mode: "timestamp_ms" }).notNull(),
  windowEnd: integer("window_end", { mode: "timestamp_ms" }).notNull(),
  status: text("status").notNull().default("running"),
  providerItemCount: integer("provider_item_count").notNull().default(0),
  matchedItemCount: integer("matched_item_count").notNull().default(0),
  exceptionItemCount: integer("exception_item_count").notNull().default(0),
  informationalItemCount: integer("informational_item_count").notNull().default(0),
  grossMinor: integer("gross_minor").notNull().default(0),
  feeMinor: integer("fee_minor").notNull().default(0),
  netMinor: integer("net_minor").notNull().default(0),
  currency: text("currency").notNull().default("qar"),
  failureCode: text("failure_code"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
}, (table) => [
  uniqueIndex("idx_payment_reconciliation_client_request").on(table.requestedByUserId, table.clientRequestId),
  index("idx_payment_reconciliation_status_created").on(table.status, table.createdAt),
  index("idx_payment_reconciliation_window").on(table.windowStart, table.windowEnd),
]);

export const paymentReconciliationItems = sqliteTable("payment_reconciliation_items", {
  id: text("id").primaryKey(),
  runId: text("run_id").notNull().references(() => paymentReconciliationRuns.id, { onDelete: "restrict" }),
  ledgerEntryId: text("ledger_entry_id").references(() => paymentLedgerEntries.id, { onDelete: "restrict" }),
  provider: text("provider").notNull().default("stripe"),
  providerBalanceTransactionId: text("provider_balance_transaction_id").notNull(),
  providerType: text("provider_type").notNull(),
  amountMinor: integer("amount_minor").notNull(),
  feeMinor: integer("fee_minor").notNull(),
  netMinor: integer("net_minor").notNull(),
  expectedAmountMinor: integer("expected_amount_minor"),
  currency: text("currency").notNull(),
  matchStatus: text("match_status").notNull(),
  reasonCode: text("reason_code"),
  providerCreatedAt: integer("provider_created_at", { mode: "timestamp_ms" }).notNull(),
  providerAvailableOn: integer("provider_available_on", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("idx_payment_reconciliation_provider_transaction").on(table.runId, table.provider, table.providerBalanceTransactionId),
  index("idx_payment_reconciliation_item_run_status").on(table.runId, table.matchStatus),
  index("idx_payment_reconciliation_item_ledger").on(table.ledgerEntryId, table.createdAt),
]);

export const paymentDisputes = sqliteTable("payment_disputes", {
  id: text("id").primaryKey(),
  ledgerEntryId: text("ledger_entry_id").references(() => paymentLedgerEntries.id, { onDelete: "restrict" }),
  provider: text("provider").notNull().default("stripe"),
  providerDisputeId: text("provider_dispute_id").notNull(),
  providerChargeId: text("provider_charge_id"),
  providerPaymentIntentId: text("provider_payment_intent_id"),
  amountMinor: integer("amount_minor").notNull(),
  currency: text("currency").notNull(),
  reasonCode: text("reason_code").notNull(),
  status: text("status").notNull(),
  evidenceDueAt: integer("evidence_due_at", { mode: "timestamp_ms" }),
  providerCreatedAt: integer("provider_created_at", { mode: "timestamp_ms" }).notNull(),
  providerUpdatedAt: integer("provider_updated_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
  closedAt: integer("closed_at", { mode: "timestamp_ms" }),
}, (table) => [
  uniqueIndex("idx_payment_dispute_provider_id").on(table.provider, table.providerDisputeId),
  index("idx_payment_dispute_status_updated").on(table.status, table.updatedAt),
  index("idx_payment_dispute_ledger_updated").on(table.ledgerEntryId, table.updatedAt),
]);

export const paymentDisputeEvents = sqliteTable("payment_dispute_events", {
  id: text("id").primaryKey(),
  disputeId: text("dispute_id").notNull().references(() => paymentDisputes.id, { onDelete: "restrict" }),
  provider: text("provider").notNull().default("stripe"),
  providerEventId: text("provider_event_id").notNull(),
  eventType: text("event_type").notNull(),
  previousStatus: text("previous_status"),
  nextStatus: text("next_status").notNull(),
  receivedAt: integer("received_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("idx_payment_dispute_event_provider_id").on(table.provider, table.providerEventId),
  index("idx_payment_dispute_event_dispute_received").on(table.disputeId, table.receivedAt),
]);

export const paymentReceipts = sqliteTable("payment_receipts", {
  id: text("id").primaryKey(),
  ledgerEntryId: text("ledger_entry_id").notNull().references(() => paymentLedgerEntries.id, { onDelete: "restrict" }),
  receiptNumber: text("receipt_number").notNull(),
  provider: text("provider").notNull().default("stripe"),
  providerEventId: text("provider_event_id").notNull(),
  providerPaymentIntentId: text("provider_payment_intent_id"),
  providerName: text("provider_name").notNull(),
  facilityName: text("facility_name"),
  appointmentStartedAt: integer("appointment_started_at", { mode: "timestamp_ms" }).notNull(),
  careMode: text("care_mode").notNull(),
  amountMinor: integer("amount_minor").notNull(),
  currency: text("currency").notNull(),
  documentId: text("document_id").references(() => documentRecords.id, { onDelete: "restrict" }),
  issuedAt: integer("issued_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("idx_payment_receipt_ledger").on(table.ledgerEntryId),
  uniqueIndex("idx_payment_receipt_number").on(table.receiptNumber),
  uniqueIndex("idx_payment_receipt_provider_event").on(table.provider, table.providerEventId),
  uniqueIndex("idx_payment_receipt_document").on(table.documentId),
  index("idx_payment_receipt_issued").on(table.issuedAt),
]);

export const paymentCreditNotes = sqliteTable("payment_credit_notes", {
  id: text("id").primaryKey(),
  receiptId: text("receipt_id").notNull().references(() => paymentReceipts.id, { onDelete: "restrict" }),
  ledgerEntryId: text("ledger_entry_id").notNull().references(() => paymentLedgerEntries.id, { onDelete: "restrict" }),
  creditNoteNumber: text("credit_note_number").notNull(),
  provider: text("provider").notNull().default("stripe"),
  providerEventId: text("provider_event_id").notNull(),
  providerRefundId: text("provider_refund_id"),
  amountMinor: integer("amount_minor").notNull(),
  currency: text("currency").notNull(),
  reasonCode: text("reason_code").notNull().default("provider_confirmed_refund"),
  documentId: text("document_id").references(() => documentRecords.id, { onDelete: "restrict" }),
  issuedAt: integer("issued_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("idx_payment_credit_note_number").on(table.creditNoteNumber),
  uniqueIndex("idx_payment_credit_note_provider_event").on(table.provider, table.providerEventId),
  uniqueIndex("idx_payment_credit_note_document").on(table.documentId),
  index("idx_payment_credit_note_receipt_issued").on(table.receiptId, table.issuedAt),
  index("idx_payment_credit_note_ledger_issued").on(table.ledgerEntryId, table.issuedAt),
]);

export const paymentLifecycleRehearsals = sqliteTable("payment_lifecycle_rehearsals", {
  id: text("id").primaryKey(),
  requestedByUserId: text("requested_by_user_id").notNull().references(() => users.id, { onDelete: "restrict" }),
  clientRequestId: text("client_request_id").notNull(),
  suiteVersion: text("suite_version").notNull(),
  scenarioCount: integer("scenario_count").notNull(),
  passedScenarios: integer("passed_scenarios").notNull(),
  failedScenarios: integer("failed_scenarios").notNull(),
  result: text("result").notNull(),
  dataMode: text("data_mode").notNull().default("synthetic_only"),
  scenarioResultsJson: text("scenario_results_json").notNull(),
  stripeCallsMade: integer("stripe_calls_made").notNull().default(0),
  r2ObjectsWritten: integer("r2_objects_written").notNull().default(0),
  emailsSent: integer("emails_sent").notNull().default(0),
  moneyMovementMinor: integer("money_movement_minor").notNull().default(0),
  customerRecordsCreated: integer("customer_records_created").notNull().default(0),
  operationalRecordsCreated: integer("operational_records_created").notNull().default(0),
  executedAt: integer("executed_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => [
  uniqueIndex("idx_payment_lifecycle_rehearsal_request").on(table.requestedByUserId, table.clientRequestId),
  index("idx_payment_lifecycle_rehearsal_result_executed").on(table.result, table.executedAt),
]);
