import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { patientProfiles, users } from "./schema";

const timestamps={createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp_ms"}).notNull()};
export const patientImmunizationRecords=sqliteTable("patient_immunization_records",{id:text("id").primaryKey(),patientId:text("patient_id").notNull().references(()=>patientProfiles.id,{onDelete:"restrict"}),vaccineCategory:text("vaccine_category").notNull(),productLabel:text("product_label"),doseLabel:text("dose_label").notNull(),administeredOn:text("administered_on").notNull(),countryCode:text("country_code"),sourceLabel:text("source_label").notNull().default("patient_entered_unverified"),status:text("status").notNull().default("active"),version:integer("version").notNull().default(1),...timestamps},t=>[index("idx_immunization_patient_date").on(t.patientId,t.administeredOn),index("idx_immunization_patient_status").on(t.patientId,t.status,t.updatedAt)]);
export const preventiveScreeningRecords=sqliteTable("preventive_screening_records",{id:text("id").primaryKey(),patientId:text("patient_id").notNull().references(()=>patientProfiles.id,{onDelete:"restrict"}),screeningCategory:text("screening_category").notNull(),completionState:text("completion_state").notNull(),performedOn:text("performed_on"),nextDueBand:text("next_due_band"),providerReference:text("provider_reference"),sourceLabel:text("source_label").notNull().default("patient_entered_unverified"),status:text("status").notNull().default("active"),version:integer("version").notNull().default(1),...timestamps},t=>[index("idx_screening_patient_category").on(t.patientId,t.screeningCategory,t.status),index("idx_screening_patient_updated").on(t.patientId,t.updatedAt)]);
export const healthMeasurementRecords=sqliteTable("health_measurement_records",{id:text("id").primaryKey(),patientId:text("patient_id").notNull().references(()=>patientProfiles.id,{onDelete:"restrict"}),measurementType:text("measurement_type").notNull(),numericValue:real("numeric_value").notNull(),secondaryValue:real("secondary_value"),unit:text("unit").notNull(),measuredAt:integer("measured_at",{mode:"timestamp_ms"}).notNull(),contextCode:text("context_code").notNull(),sourceLabel:text("source_label").notNull().default("patient_entered_unverified"),status:text("status").notNull().default("active"),version:integer("version").notNull().default(1),...timestamps},t=>[index("idx_measurement_patient_type_time").on(t.patientId,t.measurementType,t.measuredAt),index("idx_measurement_patient_status").on(t.patientId,t.status,t.updatedAt)]);
export const symptomJournalEntries=sqliteTable("symptom_journal_entries",{id:text("id").primaryKey(),patientId:text("patient_id").notNull().references(()=>patientProfiles.id,{onDelete:"restrict"}),symptomCategory:text("symptom_category").notNull(),severityBand:text("severity_band").notNull(),startedBand:text("started_band").notNull(),trend:text("trend").notNull(),note:text("note"),emergencyWarningAcknowledged:integer("emergency_warning_acknowledged",{mode:"boolean"}).notNull().default(false),sourceLabel:text("source_label").notNull().default("patient_entered_unverified"),status:text("status").notNull().default("active"),version:integer("version").notNull().default(1),...timestamps},t=>[index("idx_symptom_patient_created").on(t.patientId,t.createdAt),index("idx_symptom_patient_status").on(t.patientId,t.status,t.updatedAt)]);
export const wellnessJournalEntries=sqliteTable("wellness_journal_entries",{id:text("id").primaryKey(),patientId:text("patient_id").notNull().references(()=>patientProfiles.id,{onDelete:"restrict"}),entryDate:text("entry_date").notNull(),sleepBand:text("sleep_band").notNull(),activityBand:text("activity_band").notNull(),energyBand:text("energy_band").notNull(),note:text("note"),sourceLabel:text("source_label").notNull().default("patient_entered_unverified"),status:text("status").notNull().default("active"),version:integer("version").notNull().default(1),...timestamps},t=>[index("idx_wellness_patient_date").on(t.patientId,t.entryDate),index("idx_wellness_patient_status").on(t.patientId,t.status,t.updatedAt)]);
export const personalTrackingEvents=sqliteTable("personal_tracking_events",{id:text("id").primaryKey(),module:text("module").notNull(),recordId:text("record_id").notNull(),actorUserId:text("actor_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),action:text("action").notNull(),previousStatus:text("previous_status"),nextStatus:text("next_status").notNull(),createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull()},t=>[index("idx_personal_tracking_events_record").on(t.module,t.recordId,t.createdAt)]);
export const personalTrackingRehearsals=sqliteTable("personal_tracking_rehearsals",{id:text("id").primaryKey(),suiteVersion:text("suite_version").notNull(),scenarioCount:integer("scenario_count").notNull(),passedScenarios:integer("passed_scenarios").notNull(),clinicalDecisionsMade:integer("clinical_decisions_made").notNull(),providerRecordsDisclosed:integer("provider_records_disclosed").notNull(),externalMessagesSent:integer("external_messages_sent").notNull(),deviceImportsPerformed:integer("device_imports_performed").notNull(),result:text("result").notNull(),executedByUserId:text("executed_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),executedAt:integer("executed_at",{mode:"timestamp_ms"}).notNull()},t=>[index("idx_personal_tracking_rehearsals_executed").on(t.executedAt)]);
export const personalTrackingSchema={patientImmunizationRecords,preventiveScreeningRecords,healthMeasurementRecords,symptomJournalEntries,wellnessJournalEntries,personalTrackingEvents,personalTrackingRehearsals};
