import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { organizations, providerServiceLocations, users } from "./schema";

export const providerAccessProposals = sqliteTable("provider_access_proposals", {
  id:text("id").primaryKey(), organizationId:text("organization_id").notNull().references(()=>organizations.id,{onDelete:"restrict"}),
  subjectReference:text("subject_reference").notNull(), requestedRole:text("requested_role").notNull(), locationScopesJson:text("location_scopes_json").notNull().default("[]"),
  purposeCode:text("purpose_code").notNull(), expiresAt:integer("expires_at",{mode:"timestamp_ms"}), status:text("status").notNull().default("draft"),
  preparedByUserId:text("prepared_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}), reviewedByUserId:text("reviewed_by_user_id").references(()=>users.id,{onDelete:"restrict"}),
  reviewReasonCode:text("review_reason_code"), version:integer("version").notNull().default(1), createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull(), updatedAt:integer("updated_at",{mode:"timestamp_ms"}).notNull(),
},t=>[index("idx_provider_access_org_status").on(t.organizationId,t.status,t.updatedAt),index("idx_provider_access_subject").on(t.organizationId,t.subjectReference)]);
export const providerAccessEvents = sqliteTable("provider_access_events", { id:text("id").primaryKey(), proposalId:text("proposal_id").references(()=>providerAccessProposals.id,{onDelete:"restrict"}), organizationId:text("organization_id").references(()=>organizations.id,{onDelete:"restrict"}), actorUserId:text("actor_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}), eventCode:text("event_code").notNull(), previousStatus:text("previous_status"), nextStatus:text("next_status"), reasonCode:text("reason_code"), proposalVersion:integer("proposal_version"), createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull() },t=>[index("idx_provider_access_events_proposal").on(t.proposalId,t.createdAt)]);
export const providerAccessRehearsals = sqliteTable("provider_access_rehearsals", { id:text("id").primaryKey(), suiteVersion:text("suite_version").notNull(), scenarioCount:integer("scenario_count").notNull(), passedScenarios:integer("passed_scenarios").notNull(), roleChangesApplied:integer("role_changes_applied").notNull(), invitationsSent:integer("invitations_sent").notNull(), externalRequestsSent:integer("external_requests_sent").notNull(), result:text("result").notNull(), executedByUserId:text("executed_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}), executedAt:integer("executed_at",{mode:"timestamp_ms"}).notNull() },t=>[index("idx_provider_access_rehearsals_executed").on(t.executedAt)]);

export const schedulingRuleSets = sqliteTable("scheduling_rule_sets", {
  id:text("id").primaryKey(), organizationId:text("organization_id").notNull().references(()=>organizations.id,{onDelete:"restrict"}), serviceLocationId:text("service_location_id").notNull().references(()=>providerServiceLocations.id,{onDelete:"restrict"}),
  timezone:text("timezone").notNull().default("Asia/Qatar"), weeklyRulesJson:text("weekly_rules_json").notNull(), exceptionsJson:text("exceptions_json").notNull().default("[]"), bookingHorizonDays:integer("booking_horizon_days").notNull(), bufferBeforeMinutes:integer("buffer_before_minutes").notNull(), bufferAfterMinutes:integer("buffer_after_minutes").notNull(), capacity:integer("capacity").notNull().default(1), confirmationMode:text("confirmation_mode").notNull(),
  impactAppointmentCount:integer("impact_appointment_count").notNull().default(0), impactPreviewedAt:integer("impact_previewed_at",{mode:"timestamp_ms"}), status:text("status").notNull().default("draft"), preparedByUserId:text("prepared_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}), reviewedByUserId:text("reviewed_by_user_id").references(()=>users.id,{onDelete:"restrict"}), reviewReasonCode:text("review_reason_code"), version:integer("version").notNull().default(1), createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull(), updatedAt:integer("updated_at",{mode:"timestamp_ms"}).notNull(),
},t=>[index("idx_scheduling_rules_org_status").on(t.organizationId,t.status,t.updatedAt),index("idx_scheduling_rules_location_status").on(t.serviceLocationId,t.status)]);
export const schedulingRuleEvents = sqliteTable("scheduling_rule_events", { id:text("id").primaryKey(), ruleSetId:text("rule_set_id").references(()=>schedulingRuleSets.id,{onDelete:"restrict"}), organizationId:text("organization_id").references(()=>organizations.id,{onDelete:"restrict"}), actorUserId:text("actor_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}), eventCode:text("event_code").notNull(), previousStatus:text("previous_status"), nextStatus:text("next_status"), ruleSetVersion:integer("rule_set_version"), affectedAppointmentCount:integer("affected_appointment_count").notNull().default(0), createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull() },t=>[index("idx_scheduling_rule_events_rule").on(t.ruleSetId,t.createdAt)]);
export const schedulingRuleRehearsals = sqliteTable("scheduling_rule_rehearsals", { id:text("id").primaryKey(), suiteVersion:text("suite_version").notNull(), scenarioCount:integer("scenario_count").notNull(), passedScenarios:integer("passed_scenarios").notNull(), appointmentsChanged:integer("appointments_changed").notNull(), slotsPublished:integer("slots_published").notNull(), externalCalendarWrites:integer("external_calendar_writes").notNull(), result:text("result").notNull(), executedByUserId:text("executed_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}), executedAt:integer("executed_at",{mode:"timestamp_ms"}).notNull() },t=>[index("idx_scheduling_rule_rehearsals_executed").on(t.executedAt)]);
export const providerOperationsSchema={providerAccessProposals,providerAccessEvents,providerAccessRehearsals,schedulingRuleSets,schedulingRuleEvents,schedulingRuleRehearsals};
