import{index,integer,sqliteTable,text}from"drizzle-orm/sqlite-core";import{patientProfiles,users}from"./schema";const stamp={status:text("status").notNull().default("draft"),version:integer("version").notNull().default(1),createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp_ms"}).notNull()};
export const externalRecordConnectionRequests=sqliteTable("external_record_connection_requests",{id:text("id").primaryKey(),patientId:text("patient_id").notNull().references(()=>patientProfiles.id,{onDelete:"restrict"}),systemType:text("system_type").notNull(),organizationReference:text("organization_reference").notNull(),requestedScope:text("requested_scope").notNull(),consentAcknowledged:integer("consent_acknowledged",{mode:"boolean"}).notNull(),...stamp},t=>[index("idx_external_connection_patient_status").on(t.patientId,t.status,t.updatedAt)]);
export const wearableConnectionRequests=sqliteTable("wearable_connection_requests",{id:text("id").primaryKey(),patientId:text("patient_id").notNull().references(()=>patientProfiles.id,{onDelete:"restrict"}),deviceCategory:text("device_category").notNull(),dataScope:text("data_scope").notNull(),purposeCode:text("purpose_code").notNull(),consentAcknowledged:integer("consent_acknowledged",{mode:"boolean"}).notNull(),...stamp},t=>[index("idx_wearable_connection_patient_status").on(t.patientId,t.status,t.updatedAt)]);
export const interoperabilityProfileProposals=sqliteTable("interoperability_profile_proposals",{id:text("id").primaryKey(),profileName:text("profile_name").notNull(),standardVersion:text("standard_version").notNull(),resourceScope:text("resource_scope").notNull(),partnerReference:text("partner_reference").notNull(),createdByUserId:text("created_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),...stamp},t=>[index("idx_interop_profile_status").on(t.status,t.updatedAt)]);
export const dataQualityRuleProposals=sqliteTable("data_quality_rule_proposals",{id:text("id").primaryKey(),metricCode:text("metric_code").notNull(),resourceScope:text("resource_scope").notNull(),thresholdBand:text("threshold_band").notNull(),responseCode:text("response_code").notNull(),createdByUserId:text("created_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),...stamp},t=>[index("idx_data_quality_rule_status").on(t.status,t.updatedAt)]);
export const tenantExperienceProposals=sqliteTable("tenant_experience_proposals",{id:text("id").primaryKey(),tenantReference:text("tenant_reference").notNull(),experienceName:text("experience_name").notNull(),localeSet:text("locale_set").notNull(),themeTokenSet:text("theme_token_set").notNull(),createdByUserId:text("created_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),...stamp},t=>[index("idx_tenant_experience_status").on(t.status,t.updatedAt)]);
export const releaseTwoReadinessEvents=sqliteTable("release_two_readiness_events",{id:text("id").primaryKey(),module:text("module").notNull(),recordId:text("record_id").notNull(),actorUserId:text("actor_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),action:text("action").notNull(),nextStatus:text("next_status").notNull(),createdAt:integer("created_at",{mode:"timestamp_ms"}).notNull()},t=>[index("idx_release_two_events_record").on(t.module,t.recordId,t.createdAt)]);
export const releaseTwoReadinessRehearsals=sqliteTable("release_two_readiness_rehearsals",{id:text("id").primaryKey(),suiteVersion:text("suite_version").notNull(),scenarioCount:integer("scenario_count").notNull(),passedScenarios:integer("passed_scenarios").notNull(),externalConnectionsMade:integer("external_connections_made").notNull(),deviceDataImported:integer("device_data_imported").notNull(),profilesActivated:integer("profiles_activated").notNull(),runtimeRulesChanged:integer("runtime_rules_changed").notNull(),tenantThemesApplied:integer("tenant_themes_applied").notNull(),result:text("result").notNull(),executedByUserId:text("executed_by_user_id").notNull().references(()=>users.id,{onDelete:"restrict"}),executedAt:integer("executed_at",{mode:"timestamp_ms"}).notNull()},t=>[index("idx_release_two_rehearsal_executed").on(t.executedAt)]);
export const releaseTwoReadinessSchema={externalRecordConnectionRequests,wearableConnectionRequests,interoperabilityProfileProposals,dataQualityRuleProposals,tenantExperienceProposals,releaseTwoReadinessEvents,releaseTwoReadinessRehearsals};
