"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "./diagnostic-imaging.module.css";
type Report={source:string;reportStatus:string;findingsText:string;impressionText:string;recommendationsText:string;urgentFinding:boolean;partnerProtocolAttested:boolean;issuedAt:string};
type Order={id:string;providerName:string;organizationName:string;studyType:string;bodyRegion:string;priority:string;status:string;preparationInstructions:string;signedAt:string;scheduledAt:string|null;report:Report|null};
type Data={orders:Order[];boundary:string;urgentProtocol:string};
export default function DiagnosticImagingPage(){
  const[data,setData]=useState<Data|null>(null),[error,setError]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/diagnostic-imaging",{cache:"no-store"});if(response.status===401){location.assign("/signin-with-chatgpt?return_to=/diagnostic-imaging");return}const payload=await response.json();if(!response.ok)throw new Error(payload.message||"Diagnostic imaging unavailable");setData(payload.data)},[]);
  useEffect(()=>{queueMicrotask(()=>void load().catch(reason=>setError(reason.message)))},[load]);
  return <main className={`${styles.shell} specialist-patient-shell clinical-module-experience imaging-experience`}><header className={styles.top}><a href="/"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya"/></a><a href="/appointments">Appointments</a></header><section className={styles.hero}><small>PATIENT DIAGNOSTIC IMAGING</small><h1>Your imaging journey, clearly coordinated.</h1><p>Track signed orders, preparation, scheduling, and final text-only synthetic reports without implying an image system connection.</p></section><section className={styles.panel}><p className={styles.boundary}>{data?.boundary||"Loading controlled imaging boundary…"}</p><p className={styles.protocol}><b>Urgent findings:</b> {data?.urgentProtocol}</p>{error&&<p className={styles.error}>{error}</p>}<div className={styles.grid}>{data?.orders.map(order=><article className={styles.card} key={order.id}><span className={`${styles.pill} ${order.priority==="urgent"?styles.urgent:""}`}>{order.priority} · {order.status}</span><h3>{order.studyType} · {order.bodyRegion}</h3><p className={styles.meta}>{order.organizationName} · Ordered by {order.providerName} · Signed {new Date(order.signedAt).toLocaleDateString()}</p><b>Preparation</b><p>{order.preparationInstructions}</p>{order.scheduledAt&&<p><b>Scheduled:</b> {new Date(order.scheduledAt).toLocaleString()}</p>}{order.report&&<div className={styles.report}><span className={styles.pill}>{order.report.source.replace("_"," ")} · {order.report.reportStatus}</span><h4>Findings</h4><p>{order.report.findingsText}</p><h4>Impression</h4><p>{order.report.impressionText}</p><h4>Recommendations</h4><p>{order.report.recommendationsText}</p>{order.report.urgentFinding&&<small>Urgent finding · external protocol attestation recorded</small>}</div>}</article>)}{data&&!data.orders.length&&<article className={styles.card}><h3>No imaging orders</h3><p>Signed diagnostic imaging orders will appear here.</p></article>}</div></section></main>;
}
