"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./patient-profile.module.css";

type Settings = { reyatiDisplayName: string | null; preferredLanguage: "en" | "ar"; timezone: string; contactDisplayPreference: "masked" | "identity_email" | "hidden"; emergencyContactReference: string | null; communicationSupportNeeds: string | null; completionState: "in_progress" | "complete"; version: number; updatedAt: string };
type Workspace = {
  identity: { displayName: string; email: string; contactStatus: string; identityOwned: boolean; editableInReyati: boolean; verificationClaim: string };
  settings: Settings; history: Array<{ id: string; action: string; changedCodes: string[]; profileVersion: number; occurredAt: string }>;
  options: { timezones: string[]; displayNameLimit: number; emergencyContactReferenceLimit: number; communicationSupportNeedsLimit: number };
};
const editableKeys = ["reyatiDisplayName", "preferredLanguage", "timezone", "contactDisplayPreference", "emergencyContactReference", "communicationSupportNeeds", "completionState"] as const;

export default function PatientProfilePage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Workspace | null>(null), [form, setForm] = useState<Settings | null>(null), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => {
    setLoading(true);
    try { const response = await fetch("/api/account/profile", { cache: "no-store" }), payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setData(payload.data); setForm(payload.data.settings); setError(""); }
    catch { setError(ar ? "تعذر تحميل ملفك. يمكنك إعادة المحاولة." : "Your profile could not be loaded. You can try again."); }
    finally { setLoading(false); }
  }, [ar]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const dirty = useMemo(() => !!(data && form && editableKeys.some((key) => (form[key] ?? "") !== (data.settings[key] ?? ""))), [data, form]);
  async function save() {
    if (!data || !form || !dirty) return; setSaving(true); setError(""); setMessage("");
    try { const response = await fetch("/api/account/profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "update_profile", ...form, version: data.settings.version }) }), payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); await load(); setMessage(ar ? "تم حفظ ملفك بأمان." : "Your profile was saved securely."); }
    catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? "تعذر حفظ الملف." : "The profile could not be saved.")); }
    finally { setSaving(false); }
  }
  const patch = <K extends keyof Settings>(key: K, value: Settings[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  return <main className={`${styles.shell} trust-center-shell account-profile-experience`} dir={ar ? "rtl" : "ltr"}>
    <header className={styles.top}><a href="/"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya" /></a><nav aria-label={ar ? "التنقل الرئيسي" : "Primary navigation"}><a href="/account/security">{ar ? "أمان الحساب" : "Security"}</a><a href="/settings/accessibility">{ar ? "إمكانية الوصول" : "Accessibility"}</a><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></nav></header>
    <section className={styles.hero}><div><span>{ar ? "ملفك تحت سيطرتك" : "YOUR PROFILE, UNDER YOUR CONTROL"}</span><h1>{ar ? "الملف الشخصي وبيانات الاتصال" : "Profile & contact details"}</h1><p>{ar ? "اختر كيف تظهر داخل كيفايا وكيف يمكننا دعم تواصلك، دون تغيير هوية تسجيل الدخول الموثقة." : "Choose how you appear inside Qivaya and how we can support your communication—without changing your verified sign-in identity."}</p></div><aside><i aria-hidden="true">{form?.completionState === "complete" ? "✓" : "···"}</i><b>{form?.completionState === "complete" ? (ar ? "مكتمل" : "Complete") : (ar ? "قيد الإعداد" : "In progress")}</b><small>{ar ? "حالة الملف" : "Profile status"}</small></aside></section>
    <div className={styles.content}>
      <section className={styles.boundary}><div><b>{ar ? "هوية تسجيل الدخول للقراءة فقط" : "Sign-in identity is read-only"}</b><p>{ar ? "البريد والاسم أدناه واردان من جلسة تسجيل الدخول الموثقة. كيفايا لا يغيرهما ولا يدّعي التحقق من وسيلة اتصال." : "The email and identity name below come from your verified sign-in session. Qivaya does not change them or claim contact verification."}</p></div><span>{ar ? "لا تغيير للهوية" : "No identity mutation"}</span></section>
      {message && <p className={styles.success} role="status">{message}</p>}{error && <div className={styles.error} role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>{ar ? "إعادة المحاولة" : "Try again"}</button></div>}
      {loading ? <div className={styles.loading} role="status">{ar ? "جارٍ تحميل ملفك…" : "Loading your profile…"}</div> : data && form && <>
        <section className={styles.identity}><div className={styles.avatar}>{data.identity.displayName.slice(0, 2).toUpperCase()}</div><div><span>{ar ? "الهوية المسجلة" : "SIGNED-IN IDENTITY"}</span><h2>{data.identity.displayName}</h2><p>{data.identity.email}</p></div><em>{ar ? "للقراءة فقط · غير مُعلن كموثّق" : "Read-only · not claimed as verified"}</em></section>
        <section className={styles.grid}>
          <article className={styles.card}><div className={styles.cardHead}><span>01</span><div><h2>{ar ? "كيف تظهر في كيفايا" : "How you appear in Qivaya"}</h2><p>{ar ? "هذا اسم عرض داخل كيفايا فقط." : "This is a Qivaya-only display preference."}</p></div></div><label>{ar ? "اسم العرض في كيفايا" : "Qivaya display name"}<input maxLength={data.options.displayNameLimit} value={form.reyatiDisplayName ?? ""} onChange={(event) => patch("reyatiDisplayName", event.target.value)} placeholder={data.identity.displayName} /></label><div className={styles.two}><label>{ar ? "اللغة المفضلة" : "Preferred language"}<select value={form.preferredLanguage} onChange={(event) => patch("preferredLanguage", event.target.value as "en" | "ar")}><option value="en">English</option><option value="ar">العربية</option></select></label><label>{ar ? "المنطقة الزمنية" : "Timezone"}<select value={form.timezone} onChange={(event) => patch("timezone", event.target.value)}>{data.options.timezones.map((zone) => <option key={zone}>{zone}</option>)}</select></label></div></article>
          <article className={styles.card}><div className={styles.cardHead}><span>02</span><div><h2>{ar ? "عرض بيانات الاتصال" : "Contact display"}</h2><p>{ar ? "يؤثر على العرض داخل حسابك فقط." : "Controls presentation inside your account only."}</p></div></div><div className={styles.choices}>{(["masked", "identity_email", "hidden"] as const).map((choice) => <label key={choice} className={form.contactDisplayPreference === choice ? styles.selected : ""}><input type="radio" name="contact-display" checked={form.contactDisplayPreference === choice} onChange={() => patch("contactDisplayPreference", choice)} /><b>{choice === "masked" ? (ar ? "مخفي جزئياً" : "Masked") : choice === "identity_email" ? (ar ? "بريد الهوية" : "Identity email") : (ar ? "مخفي" : "Hidden")}</b><small>{choice === "masked" ? "a•••@•••" : choice === "identity_email" ? data.identity.email : (ar ? "لا يظهر" : "Not shown")}</small></label>)}</div><p className={styles.hint}>{ar ? "هذا لا يغيّر البريد ولا يثبت ملكيته ولا يرسل البيانات للخارج." : "This does not change the email, verify ownership, or send contact data externally."}</p></article>
          <article className={styles.card}><div className={styles.cardHead}><span>03</span><div><h2>{ar ? "مرجع جهة اتصال للطوارئ" : "Emergency contact reference"}</h2><p>{ar ? "معلومة اختيارية تدخلها أنت وليست جهة اتصال موثقة." : "Optional, user-entered, and not a verified contact method."}</p></div></div><label>{ar ? "مرجع مختصر" : "Short reference"}<textarea maxLength={data.options.emergencyContactReferenceLimit} value={form.emergencyContactReference ?? ""} onChange={(event) => patch("emergencyContactReference", event.target.value)} placeholder={ar ? "مثال: أحد أفراد الأسرة — استخدم جهة الاتصال المحفوظة لدي" : "Example: Family member — use the contact saved with me"} /></label><p className={styles.hint}>{ar ? "لا تستخدمه للطوارئ الفعلية. اتصل بـ 999 في قطر عند وجود خطر فوري." : "Not an emergency dispatch service. Call 999 in Qatar for immediate danger."}</p></article>
          <article className={styles.card}><div className={styles.cardHead}><span>04</span><div><h2>{ar ? "احتياجات دعم التواصل" : "Communication support needs"}</h2><p>{ar ? "اطلب مساعدة عملية غير سريرية." : "Request practical, non-clinical communication support."}</p></div></div><label>{ar ? "كيف يمكننا دعم التواصل؟" : "How can communication be easier?"}<textarea maxLength={data.options.communicationSupportNeedsLimit} value={form.communicationSupportNeeds ?? ""} onChange={(event) => patch("communicationSupportNeeds", event.target.value)} placeholder={ar ? "مثال: أفضّل شرحاً واضحاً وبطيئاً" : "Example: I prefer clear, unhurried explanations"} /></label><p className={styles.hint}>{ar ? "لا تدخل تشخيصات أو أدوية أو ملاحظات طبية هنا. لا تُستنتج احتياجات سريرية من هذا النص." : "Do not enter diagnoses, medicines, or clinical notes here. No clinical needs are inferred from this text."}</p></article>
        </section>
        <section className={styles.finish}><div><span>{ar ? "جاهزية الملف" : "PROFILE READINESS"}</span><h2>{ar ? "اختر حالة ملفك" : "Choose your profile state"}</h2><p>{ar ? "يمكنك العودة وتحديث هذه المعلومات في أي وقت." : "You can return and update these details at any time."}</p></div><select aria-label={ar ? "حالة اكتمال الملف" : "Profile completion state"} value={form.completionState} onChange={(event) => patch("completionState", event.target.value as "in_progress" | "complete")}><option value="in_progress">{ar ? "قيد الإعداد" : "In progress"}</option><option value="complete">{ar ? "مكتمل" : "Complete"}</option></select><button type="button" disabled={!dirty || saving} onClick={() => void save()}>{saving ? (ar ? "جارٍ الحفظ…" : "Saving…") : (ar ? "حفظ الملف" : "Save profile")}</button></section>
        <section className={styles.history}><div><span>{ar ? "سجل مشفر غير قابل للتعديل" : "IMMUTABLE CODED HISTORY"}</span><h2>{ar ? "نشاط الملف" : "Profile activity"}</h2></div>{data.history.length === 0 ? <p>{ar ? "لا توجد تغييرات مسجلة بعد." : "No recorded changes yet."}</p> : data.history.map((event) => <article key={event.id}><div><b>{ar ? "تم تحديث الملف" : "Profile updated"}</b><small>{event.changedCodes.map((code) => code.replaceAll("_", " ")).join(" · ")}</small></div><time>{new Date(event.occurredAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</time></article>)}</section>
      </>}
    </div>
  </main>;
}
