"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import { reyatiDate, reyatiNumber } from "@/lib/reyati-i18n";

type Operator = { userId: string; displayName: string; role: string };
type Update = { id: string; action: string; previousStatus: string | null; nextStatus: string; note: string; actorName: string; createdAt: string };
type Incident = { id: string; reference: string; title: string; summary: string; category: string; severity: string; status: string; assignedToUserId: string; assigneeName: string; responseDueAt: string; acknowledgedAt: string | null; responseOverdue: boolean; version: number; updatedAt: string; updates: Update[] };
type Data = { role: string; operators: Operator[]; categories: string[]; severities: string[]; incidents: Incident[] };
const labels: Record<string, { en: string; ar: string }> = { security: { en: "Security", ar: "الأمن" }, privacy: { en: "Privacy", ar: "الخصوصية" }, availability: { en: "Availability", ar: "التوفر" }, data_integrity: { en: "Data integrity", ar: "سلامة البيانات" }, communications: { en: "Communications", ar: "الاتصالات" }, care_continuity: { en: "Care continuity", ar: "استمرارية الرعاية" }, open: { en: "Open", ar: "مفتوح" }, acknowledged: { en: "Acknowledged", ar: "تم الاستلام" }, contained: { en: "Contained", ar: "تم الاحتواء" }, monitoring: { en: "Monitoring", ar: "تحت المراقبة" }, resolved: { en: "Resolved", ar: "تم الحل" }, closed: { en: "Closed", ar: "مغلق" } };
const actions: Record<string, string[]> = { open: ["acknowledge"], acknowledged: ["contain", "resolve"], contained: ["monitor", "resolve"], monitoring: ["contain", "resolve"], resolved: ["reopen", "close"], closed: ["reopen"] };
const actionCopy: Record<string, { en: string; ar: string }> = { acknowledge: { en: "Acknowledge", ar: "استلام" }, contain: { en: "Record containment", ar: "تسجيل الاحتواء" }, monitor: { en: "Start monitoring", ar: "بدء المراقبة" }, resolve: { en: "Resolve", ar: "حل الحادث" }, close: { en: "Close", ar: "إغلاق" }, reopen: { en: "Reopen", ar: "إعادة فتح" } };

async function request(init?: RequestInit) { const response = await fetch("/api/admin/incidents", { credentials: "same-origin", ...init }); const payload = await response.json().catch(() => ({})) as { data?: unknown; message?: string; error?: string }; if (response.status === 401) { window.location.assign(`/signin-with-chatgpt?return_to=${encodeURIComponent("/admin/incidents")}`); throw new Error("Authentication required"); } if (!response.ok || payload.data === undefined) throw new Error(payload.message || payload.error || "Incident workspace unavailable"); return payload.data; }

export default function IncidentResponseCentre() {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar"; const [data, setData] = useState<Data | null>(null); const [selectedId, setSelectedId] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { const next = await request() as Data; setData(next); setSelectedId((current) => current || next.incidents[0]?.id || ""); }
  useEffect(() => { let active = true; request().then((value) => { if (!active) return; const next = value as Data; setData(next); setSelectedId(next.incidents[0]?.id || ""); }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "Incident workspace unavailable"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const selected = useMemo(() => data?.incidents.find((incident) => incident.id === selectedId) ?? null, [data, selectedId]); const activeCount = data?.incidents.filter((incident) => !["resolved", "closed"].includes(incident.status)).length ?? 0; const overdueCount = data?.incidents.filter((incident) => incident.responseOverdue).length ?? 0;
  async function submit(body: Record<string, unknown>) { setBusy(true); setError(""); try { await request({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setNotice(ar ? "تم تسجيل التغيير وإخطار المسؤول وتحديث سجل التدقيق." : "Change recorded, owner notified, and audit evidence updated."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "The change could not be saved"); } finally { setBusy(false); } }
  function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ operation: "create", title: form.get("title"), summary: form.get("summary"), category: form.get("category"), severity: form.get("severity"), assignedToUserId: form.get("assignedToUserId") }); }
  function transition(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); void submit({ operation: "update", incidentId: selected.id, version: selected.version, action: form.get("action"), note: form.get("note") }); }
  const copy = (value: string) => labels[value]?.[ar ? "ar" : "en"] ?? value.replaceAll("_", " ");
  return <main className={`incident-shell ${ar ? "arabic" : ""}`} dir={ar ? "rtl" : "ltr"} id="main-content"><aside className="incident-side"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar ? "عمليات المنصة" : "Platform operations"}</span></a><nav><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a href="/admin/operations">{ar ? "جاهزية البرنامج" : "Pilot readiness"}</a><a href="/admin/ownership">{ar ? "الملكية والتصعيد" : "Ownership & escalation"}</a><a className="active" href="/admin/incidents">{ar ? "الاستجابة للحوادث" : "Incident response"}</a><a href="/admin/recovery">{ar ? "تجارب الاستعادة" : "Recovery rehearsals"}</a><a href="/admin/continuity">{ar ? "استمرارية الرعاية" : "Care continuity"}</a><a href="/admin/audit">{ar ? "سجل التدقيق" : "Audit ledger"}</a></nav><div><b>{ar ? "حدود آمنة للخصوصية" : "Privacy-safe boundary"}</b><p>{ar ? "سجل الأثر التشغيلي فقط. لا تُدخل ملاحظات سريرية أو وثائق أو رموز وصول أو بيانات صحية تعريفية." : "Record operational impact only. Never enter clinical notes, documents, access tokens, or identifiable health information."}</p></div></aside>
    <section className="incident-main"><header><div><small>{ar ? "القيادة التشغيلية" : "OPERATIONAL COMMAND"}</small><b>{ar ? "سير عمل محمي وقابل للتدقيق" : "Protected, auditable response workflow"}</b></div><div><button onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button><a href="/notifications" aria-label={ar ? "الإشعارات" : "Notifications"}>●</a></div></header><div className="incident-workspace"><div className="incident-heading"><div><p>{ar ? "الاستجابة للحوادث" : "INCIDENT RESPONSE"}</p><h1>{ar ? "مركز قيادة الحوادث" : "Incident Command Centre"}</h1><span>{ar ? "أعلن الحوادث وعيّن المسؤولية وتتبع الاستجابة والاحتواء والحل دون ادعاء وجود مراقبة خارجية." : "Declare incidents, assign accountability, and track response, containment, and resolution without claiming external monitoring is connected."}</span></div><button onClick={() => void load()}>↻ {ar ? "تحديث" : "Refresh"}</button></div>
      <section className="incident-summary"><article><b>{reyatiNumber(activeCount, lang)}</b><span>{ar ? "حوادث نشطة" : "active incidents"}</span></article><article className={overdueCount ? "attention" : ""}><b>{reyatiNumber(overdueCount, lang)}</b><span>{ar ? "تجاوزت هدف الاستجابة" : "response targets missed"}</span></article><div><b>{ar ? "إشارات يدوية فقط" : "Manual signals only"}</b><p>{ar ? "لا يوجد مزود مراقبة أو نقل تنبيه متصل حتى الآن. يمكن للمشغلين إعلان الحالات الملاحظة يدوياً." : "No monitoring vendor or alert transport is connected yet. Operators can declare observed incidents manually."}</p></div></section>
      {loading && <div className="incident-state">{ar ? "جارٍ تحميل سجل الحوادث المحمي…" : "Loading the protected incident register…"}</div>}{error && <div className="incident-alert error"><span>{error}</span><button onClick={() => setError("")}>×</button></div>}{notice && <div className="incident-alert success"><span>✓ {notice}</span><button onClick={() => setNotice("")}>×</button></div>}
      {data && <section className="incident-grid"><div><form className="incident-declare" onSubmit={create}><p>{ar ? "إعلان آمن للخصوصية" : "PRIVACY-SAFE DECLARATION"}</p><h2>{ar ? "إعلان حادث" : "Declare an incident"}</h2><div className="incident-pair"><label>{ar ? "الفئة" : "Category"}<select name="category" required>{data.categories.map((item) => <option key={item} value={item}>{copy(item)}</option>)}</select></label><label>{ar ? "الأولوية" : "Priority"}<select name="severity" required defaultValue="P2">{data.severities.map((item) => <option key={item}>{item}</option>)}</select></label></div><label>{ar ? "عنوان تشغيلي" : "Operational title"}<input name="title" minLength={8} maxLength={120} required/></label><label>{ar ? "ملخص منقح" : "Redacted summary"}<textarea name="summary" minLength={20} maxLength={800} required placeholder={ar ? "صف التأثير الملحوظ دون أسماء أو محتوى صحي…" : "Describe observed impact without names or health content…"}/></label><label>{ar ? "المسؤول" : "Assignee"}<select name="assignedToUserId" required>{data.operators.map((operator) => <option key={`${operator.userId}:${operator.role}`} value={operator.userId}>{operator.displayName} · {operator.role.replaceAll("_", " ")}</option>)}</select></label><small>{ar ? "سيُحسب هدف الاستجابة من سجل الملكية إن وجد." : "The response target is derived from the ownership register when available."}</small><button disabled={busy}>{busy ? (ar ? "جارٍ التسجيل…" : "Recording…") : (ar ? "إعلان الحادث" : "Declare incident")}</button></form>
        <section className="incident-list"><div><h2>{ar ? "سجل الحوادث" : "Incident register"}</h2><span>{reyatiNumber(data.incidents.length, lang)}</span></div>{data.incidents.length === 0 ? <p className="incident-empty">{ar ? "لم يتم إعلان أي حوادث. هذه ليست مطالبة بعدم وجود مخاطر." : "No incidents have been declared. This is not a claim that no risks exist."}</p> : data.incidents.map((incident) => <button key={incident.id} className={selectedId === incident.id ? "active" : ""} onClick={() => setSelectedId(incident.id)}><span className={`severity ${incident.severity.toLowerCase()}`}>{incident.severity}</span><div><b>{incident.title}</b><small>{incident.reference} · {copy(incident.category)}</small><i>{incident.assigneeName}</i></div><em className={incident.responseOverdue ? "overdue" : incident.status}>{incident.responseOverdue ? (ar ? "متأخر" : "OVERDUE") : copy(incident.status)}</em></button>)}</section></div>
        <aside className="incident-detail">{selected ? <><div className="incident-detail-head"><span className={`severity ${selected.severity.toLowerCase()}`}>{selected.severity}</span><div><p>{selected.reference}</p><h2>{selected.title}</h2><small>{copy(selected.category)} · {selected.assigneeName}</small></div><i className={selected.status}>{copy(selected.status)}</i></div><p className="incident-summary-copy">{selected.summary}</p><dl><div><dt>{ar ? "هدف الاستجابة" : "Response due"}</dt><dd>{reyatiDate(selected.responseDueAt, lang, { dateStyle: "medium", timeStyle: "short" })}</dd></div><div><dt>{ar ? "آخر تحديث" : "Last updated"}</dt><dd>{reyatiDate(selected.updatedAt, lang, { dateStyle: "medium", timeStyle: "short" })}</dd></div></dl><form onSubmit={transition}><div className="incident-pair"><label>{ar ? "الإجراء التالي" : "Next action"}<select name="action">{(actions[selected.status] ?? []).map((action) => <option key={action} value={action}>{actionCopy[action][ar ? "ar" : "en"]}</option>)}</select></label></div><label>{ar ? "ملاحظة تشغيلية منقحة" : "Redacted operational note"}<textarea name="note" minLength={10} maxLength={1200} required placeholder={ar ? "سجل القرار أو الاحتواء أو دليل الحل…" : "Record the decision, containment, or resolution evidence…"}/></label><button disabled={busy}>{busy ? (ar ? "جارٍ الحفظ…" : "Saving…") : (ar ? "تسجيل التحديث" : "Record update")}</button></form><section className="incident-timeline"><h3>{ar ? "خط زمني غير قابل للتغيير" : "Immutable response timeline"}</h3>{selected.updates.map((update) => <article key={update.id}><span>•</span><div><b>{actionCopy[update.action]?.[ar ? "ar" : "en"] ?? update.action}</b><p>{update.note}</p><small>{update.actorName} · {reyatiDate(update.createdAt, lang, { dateStyle: "medium", timeStyle: "short" })}</small></div></article>)}</section></> : <div className="incident-empty">{ar ? "اختر حادثاً لمراجعته." : "Select an incident to review it."}</div>}</aside></section>}
    </div></section></main>;
}
