"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "../../diagnostic-imaging/diagnostic-imaging.module.css";
type Data={metrics:Record<string,number>;rehearsals:Array<{id:string;result:string;scenarioCount:number;executedAt:string}>;visibility:string;boundaries:Record<string,boolean>};
async function api(init?:RequestInit){const response=await fetch("/api/admin/diagnostic-imaging",{cache:"no-store",...init});const payload=await response.json();if(response.status===401){location.assign("/signin-with-chatgpt?return_to=/admin/diagnostic-imaging");throw new Error("Sign in required")}if(!response.ok)throw new Error(payload.message||payload.error||"Imaging governance unavailable");return payload.data}
export default function DiagnosticImagingGovernance(){
  const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=useCallback(()=>api().then(setData).catch(reason=>setError(reason.message)),[]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function rehearse(){setBusy(true);setError("");try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"run_rehearsal"})});await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to rehearse safeguards")}finally{setBusy(false)}}
  return <main className={styles.shell}><header className={styles.top}><a href="/admin"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><a href="/admin">Platform operations</a></header><section className={styles.hero}><small>AGGREGATE GOVERNANCE</small><h1>Diagnostic imaging workflow assurance.</h1><p>Monitor aggregate state transitions and rehearse safeguards without exposing patient, order, indication, or report content.</p></section><section className={styles.panel}>{error&&<p className={styles.error}>{error}</p>}<div className={styles.grid}>{Object.entries(data?.metrics||{}).map(([key,value])=><article className={styles.card} key={key}><span>{key.replaceAll(/([A-Z_])/g," $1")}</span><div className={styles.metric}>{value}</div></article>)}</div><p className={styles.boundary}>Aggregate-only visibility. PACS/RIS/DICOM integration, image upload and viewing, automatic interpretation, and automatic urgent escalation are disabled.</p><button className={styles.button} disabled={busy} onClick={()=>void rehearse()}>Run 14-scenario zero-side-effect rehearsal</button><div className={styles.grid}>{data?.rehearsals.map(rehearsal=><article className={styles.card} key={rehearsal.id}><span className={styles.pill}>{rehearsal.result}</span><h3>{rehearsal.scenarioCount} scenarios</h3><p>{new Date(rehearsal.executedAt).toLocaleString()} · zero operational side effects</p></article>)}</div></section></main>;
}
