"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/ReyatiLocaleProvider";
type Scenario = { id: string; scenarioKey: string; locale: string; expectedOccurrenceCount: number; expectedBlockReason: string | null; input: { status: string; sourceType: string; timezone: string } };
type Run = { id: string; result: string; status: string; version: number; reviewNote: string | null; totalScenarios: number; passedScenarios: number; duplicateOccurrences: number; invalidSourceOccurrences: number; deliveryAttempts: number };
type Suite = { id: string; suiteVersion: string; label: string; status: string; scenarios: Scenario[]; runs: Run[] };
type Data = { role: string; suiteVersion: string; occurrenceMaterializationEnabled: boolean; deliveryEnabled: boolean; suites: Suite[] };
async function api(init?: RequestInit) { const response = await fetch("/api/admin/reminder-readiness", { credentials: "same-origin", ...init }), payload = await response.json().catch(() => ({})) as { data?: unknown; message?: string; error?: string }; if (response.status === 401) { window.location.assign("/signin-with-chatgpt?return_to=/admin/reminder-readiness"); throw new Error("Authentication required"); } if (!response.ok || payload.data === undefined) throw new Error(payload.message || payload.error || "Reminder readiness workspace unavailable"); return payload.data; }
export default function ReminderReadinessPage() {
  const { lang, setLang } = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Data | null>(null), [selectedId, setSelectedId] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const suite = useMemo(() => data?.suites.find(item => item.id === selectedId) ?? data?.suites[0], [data, selectedId]), latest = suite?.runs[0];
  const load = async () => { setError(""); try { const next = await api() as Data; setData(next); setSelectedId(value => value || next.suites[0]?.id || ""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load"); } };
  useEffect(() => { void load(); }, []);
  const submit = async (body: Record<string, unknown>, message: string) => { setBusy(true); setError(""); setNotice(""); try { await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setNotice(message); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Request failed"); } finally { setBusy(false); } };
  const create = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ operation: "create_suite", suiteVersion: form.get("suiteVersion"), label: form.get("label"), sourceReference: form.get("sourceReference") }, ar ? "تم تسجيل مجموعة الجاهزية." : "Readiness suite registered."); };
  const review = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!latest) return; const form = new FormData(event.currentTarget), submitter = (event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null; void submit({ operation: "review_run", runId: latest.id, version: latest.version, action: submitter?.value, note: form.get("note") }, ar ? "تم تسجيل المراجعة المستقلة." : "Independent review recorded."); };
  return <main className={`lifecycle-shell ${ar ? "arabic" : ""}`} dir={ar ? "rtl" : "ltr"} id="main-content">
    <aside className="lifecycle-side"><a href="/" className="provider-logo"><img src="/brand/qivaya-logo-reversed.png" alt="Qivaya"/><span>{ar ? "عمليات المنصة" : "Platform operations"}</span></a><nav><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a className="active" href="/admin/reminder-readiness">{ar ? "جاهزية التذكير" : "Reminder readiness"}</a><a href="/admin/report-reader">{ar ? "قارئ التقارير" : "Report Reader"}</a><a href="/admin/prescription-intelligence">{ar ? "ذكاء الوصفات" : "Prescription intelligence"}</a><a href="/admin/audit">{ar ? "سجل التدقيق" : "Audit ledger"}</a></nav><div><b>{ar ? "مراجعة مستقلة دون تشغيل" : "Independent review without activation"}</b><p>{ar ? "الدليل اصطناعي فقط ولا ينشئ حدثاً أو إشعاراً أو سجل مريض." : "Evidence is synthetic-only and creates no occurrence, notification, or patient record."}</p></div></aside>
    <section className="lifecycle-main"><header><div><small>{ar ? "سلامة مجدول التذكير" : "REMINDER SCHEDULER SAFETY"}</small><b>{ar ? "إثبات ومراجعة قبل التشغيل" : "Evaluate and review before activation"}</b></div><div><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button><a href="/notifications">●</a></div></header><div className="lifecycle-workspace">
      <div className="lifecycle-heading"><div><p>{ar ? "مختبر اصطناعي فقط" : "SYNTHETIC-ONLY LAB"}</p><h1>{ar ? "جاهزية تذكيرات الدواء" : "Medication Reminder Readiness"}</h1><span>{ar ? "اختبر التوقيت والحدود ومنع التكرار، ثم اطلب مراجعة مستقلة دون تشغيل الإرسال." : "Test timing, boundaries, and deduplication, then require independent review without enabling delivery."}</span></div><button type="button" onClick={() => void load()}>↻ {ar ? "تحديث" : "Refresh"}</button></div>
      {data && <section className="lifecycle-summary"><article><b>{data.occurrenceMaterializationEnabled || data.deliveryEnabled ? "ACTIVE" : "GATED"}</b><span>{ar ? "التشغيل والإرسال" : "materialization & delivery"}</span></article><div><b>{ar ? "فصل المشغّل عن المراجع" : "Operator–reviewer separation"}</b><p>{ar ? "لا يستطيع منفذ التقييم مراجعة تشغيله، والتحقق لا يفعّل أي مسار للمريض." : "The evaluator cannot review their own run, and verification activates no patient pathway."}</p></div></section>}
      {error && <div className="lifecycle-alert error"><span>{error}</span><button type="button" onClick={() => setError("")}>×</button></div>}{notice && <div className="lifecycle-alert success"><span>✓ {notice}</span><button type="button" onClick={() => setNotice("")}>×</button></div>}
      {data && <section className="lifecycle-grid"><div className="lifecycle-classes">{data.suites.map(item => <button type="button" key={item.id} className={suite?.id === item.id ? "active" : ""} onClick={() => setSelectedId(item.id)}><span>{item.runs[0]?.status === "verified" ? "✓" : "◇"}</span><div><b>{item.label}</b><small>{item.scenarios.length} {ar ? "حالات اصطناعية" : "synthetic scenarios"}</small></div><i className={item.runs[0]?.status === "verified" ? "approved" : "draft"}>{item.runs[0]?.status ?? item.status}</i></button>)}{data.suites.length === 0 && <p className="lifecycle-state">{ar ? "سجّل مجموعة الجاهزية للبدء." : "Register the readiness suite to begin."}</p>}</div>
        <aside className="lifecycle-editor"><div className="lifecycle-editor-head"><p>{ar ? "دليل جاهزية المجدول" : "SCHEDULER READINESS EVIDENCE"}</p><h2>{suite?.label ?? (ar ? "لا توجد مجموعة" : "No registered suite")}</h2><span>{ar ? "لا تدخل أسماء أدوية أو بيانات مرضى أو مستندات حقيقية." : "Never enter medication names, patient data, or real documents."}</span></div>
          {!suite && data.role === "platform_admin" && <form onSubmit={create}><label>{ar ? "إصدار المجموعة" : "Suite version"}<input name="suiteVersion" defaultValue={data.suiteVersion} pattern="[A-Za-z0-9][A-Za-z0-9 _./:-]*" required/></label><label>{ar ? "اسم المجموعة" : "Suite label"}<input name="label" defaultValue="Medication reminder scheduler readiness suite" minLength={8} maxLength={120} required/></label><label>{ar ? "مرجع المصدر" : "Source reference"}<input name="sourceReference" defaultValue="ADR-030/reminder-scheduler-readiness" pattern="[A-Za-z0-9][A-Za-z0-9 _./:-]*" required/></label><button disabled={busy}>{ar ? "تسجيل المجموعة" : "Register suite"}</button></form>}
          {suite && <><section className="lifecycle-checks"><article><span>◇</span><div><b>{ar ? "التوقيت" : "Timezone"}</b><p>Asia/Qatar · UTC+03:00</p></div></article><article><span>!</span><div><b>{ar ? "حد التشغيل" : "Runtime boundary"}</b><p>{ar ? "لا إنشاء أحداث ولا إرسال" : "no occurrences; no delivery"}</p></div></article></section>
            {suite.scenarios.length === 0 && data.role === "platform_admin" && <button type="button" disabled={busy} onClick={() => void submit({ operation: "seed_suite", suiteId: suite.id }, ar ? "تم إنشاء الحالات الاصطناعية." : "Synthetic scenarios seeded.")}>{ar ? "إنشاء مجموعة الاختبار" : "Seed standard test suite"}</button>}
            {suite.scenarios.length > 0 && <section className="lifecycle-timeline"><h3>{ar ? "سيناريوهات الجدولة" : "Scheduling scenarios"}</h3>{suite.scenarios.map(item => <article key={item.id}><span>{item.expectedOccurrenceCount ? "◇" : "×"}</span><div><b>{item.scenarioKey} · {item.locale.toUpperCase()}</b><p>{item.expectedOccurrenceCount} {ar ? "حدث متوقع" : "expected occurrence"} · {item.expectedBlockReason ?? (ar ? "مستحق" : "due")}</p><small>{item.input.status} · {item.input.sourceType} · {item.input.timezone}</small></div></article>)}</section>}
            {suite.scenarios.length > 0 && data.role === "platform_admin" && <button type="button" disabled={busy} onClick={() => void submit({ operation: "run_evaluation", suiteId: suite.id }, ar ? "اكتمل تقييم الجاهزية." : "Readiness evaluation completed.")}>{ar ? "تشغيل تقييم السلامة" : "Run safety evaluation"}</button>}
            {latest && <section className="lifecycle-timeline"><h3>{ar ? "أحدث نتيجة" : "Latest result"}</h3><article><span>{latest.result === "pass" ? "✓" : "!"}</span><div><b>{latest.result.toUpperCase()} · {latest.passedScenarios}/{latest.totalScenarios}</b><p>{latest.duplicateOccurrences} {ar ? "تكرار" : "duplicates"} · {latest.invalidSourceOccurrences} {ar ? "مصادر غير صالحة" : "invalid sources"} · {latest.deliveryAttempts} {ar ? "محاولات إرسال" : "delivery attempts"}</p><small>{latest.status.replaceAll("_", " ")}{latest.reviewNote ? ` · ${latest.reviewNote}` : ""}</small></div></article></section>}
            {latest && latest.status === "pending_review" && data.role === "security_auditor" && <form onSubmit={review}><label>{ar ? "ملاحظة المراجعة المستقلة" : "Independent review note"}<textarea name="note" minLength={20} maxLength={1200} required defaultValue={ar ? "راجعت نتائج المجموعة الاصطناعية وحدود التشغيل المستقلة." : "Reviewed the synthetic suite results and the independent runtime boundaries."}/></label><div className="lifecycle-review"><button type="submit" name="action" value="verify" disabled={busy || latest.result !== "pass"}>{ar ? "تحقق من الدليل" : "Verify evidence"}</button><button type="submit" name="action" value="reject" className="danger" disabled={busy}>{ar ? "رفض الدليل" : "Reject evidence"}</button></div><p className="lifecycle-state">{ar ? "التحقق لا يفعّل إنشاء الأحداث أو الإرسال." : "Verification does not activate occurrence creation or delivery."}</p></form>}
          </>}
        </aside>
      </section>}
    </div></section>
  </main>;
}
