import { AuthorizationDeniedError } from "@/lib/authorization";
import { FacilityDirectoryConflictError, FacilityDirectoryMakerCheckerError, FacilityDirectoryValidationError, getOrganizationFacilityWorkspace, saveFacilityDraft, submitFacilityProfile } from "@/lib/facility-directory";
import { AuthenticationRequiredError, getOrCreateCurrentUser } from "@/lib/identity";
import { reportOperationalError } from "@/lib/observability";
import { enforceWriteRateLimit, rateLimitResponse } from "@/lib/rate-limits";
export const dynamic = "force-dynamic"; const headers = { "Cache-Control": "private, no-store" };
export async function GET() { return handle((id) => getOrganizationFacilityWorkspace(id)); }
export async function POST(request: Request) { const body = await request.json().catch(() => null) as Record<string, unknown> | null; return handle(async (id) => { if (!body) throw new FacilityDirectoryValidationError("A JSON object is required"); if (body.action === "save_draft") return saveFacilityDraft(id, body); if (body.action === "submit_review") return submitFacilityProfile(id, body); throw new FacilityDirectoryValidationError("action is invalid"); }, "provider.facility_profile"); }
async function handle(operation: (id: string) => Promise<unknown>, scope?: string) { try { const user = await getOrCreateCurrentUser(); if (user.status !== "active") throw new AuthorizationDeniedError(); if (scope) await enforceWriteRateLimit(user.id, scope, { limit: 24 }); return Response.json({ data: await operation(user.id) }, { headers }); } catch (error) { const limited = rateLimitResponse(error, headers); if (limited) return limited; if (error instanceof AuthenticationRequiredError) return Response.json({ error: "authentication_required" }, { status: 401, headers }); if (error instanceof AuthorizationDeniedError || error instanceof FacilityDirectoryMakerCheckerError) return Response.json({ error: "forbidden", message: error.message }, { status: 403, headers }); if (error instanceof FacilityDirectoryConflictError) return Response.json({ error: "profile_conflict", message: error.message }, { status: 409, headers }); if (error instanceof FacilityDirectoryValidationError) return Response.json({ error: "invalid_request", message: error.message }, { status: 400, headers }); reportOperationalError("provider.facility_profile.failed", error); return Response.json({ error: "service_unavailable" }, { status: 503, headers: { ...headers, "Retry-After": "30" } }); } }
