"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "../payment-activation/payment-activation.module.css";

type Posture = { productionEnvironment: boolean; protectedStorageConfigured: boolean; privateScannerConfigured: boolean; cleanupEnabled: boolean; scanRecoveryEnabled: boolean; scanDispatchEnabled: boolean; scanPollingEnabled: boolean; retentionExecutionEnabled: boolean; deletionProcessorEnabled: boolean; allRuntimeControlsEnabled: boolean };
type Prerequisites = { approvedPolicyCount: number; requiredPolicyCount: number; approvedRetentionPlan: boolean; freshSafetyRehearsal: boolean; safetyScenarioCount: number; overdueLegalHoldCount: number; governanceReady: boolean; posture: Posture };
type ActivationWindow = { id: string; reference: string; preparedByUserId: string; evidenceReference: string; windowStartsAt: string; windowEndsAt: string; changeOwner: string; monitoringOwner: string; rollbackOwner: string; status: string; reviewNote: string | null; openedByUserId: string | null; postureObservedAt: string | null; verificationNote: string | null; verifiedAt: string | null; rollbackVerifiedAt: string | null; version: number; createdAt: string };
type ActivationEvent = { id: string; windowId: string; eventCode: string; previousStatus: string | null; nextStatus: string; createdAt: string };
type Workspace = { currentUserId: string; role: string; workflowVersion: string; windows: ActivationWindow[]; events: ActivationEvent[]; readiness: { prerequisites: Prerequisites; ownershipReady: boolean; preActivationReady: boolean }; posture: Posture; boundaries: Record<string, boolean> };

async function api(init?: RequestInit) {
  const response = await fetch("/api/admin/document-activation", { cache: "no-store", credentials: "same-origin", ...init });
  const payload = await response.json().catch(() => ({})) as { data?: unknown; message?: string; error?: string };
  if (response.status === 401) { window.location.assign(`/sign-in?redirect_url=${encodeURIComponent("/admin/document-activation")}`); throw new Error("Authentication required"); }
  if (!response.ok || payload.data === undefined) throw new Error(payload.message || payload.error || "Document activation control is unavailable");
  return payload.data;
}

function stamp(value: string | null, ar: boolean) {
  if (!value) return ar ? "غير مسجل" : "Not recorded";
  return new Intl.DateTimeFormat(ar ? "ar-QA" : "en-QA", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Qatar" }).format(new Date(value));
}

export default function DocumentActivationPage() {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar";
  const [data, setData] = useState<Workspace | null>(null); const [selectedId, setSelectedId] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setError(""); try { const next = await api() as Workspace; setData(next); setSelectedId((current) => current || next.windows[0]?.id || ""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Document activation control is unavailable"); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);

  async function prepare(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); setNotice(""); const form = new FormData(event.currentTarget);
    try { const result = await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "prepare", clientRequestId: crypto.randomUUID(), evidenceReference: form.get("evidenceReference"), windowStartsAt: form.get("windowStartsAt"), windowEndsAt: form.get("windowEndsAt"), changeOwner: form.get("changeOwner"), monitoringOwner: form.get("monitoringOwner"), rollbackOwner: form.get("rollbackOwner") }) }) as ActivationWindow; setSelectedId(result.id); setNotice(ar ? "تم إعداد نافذة تفعيل المستندات للمراجعة المستقلة." : "Document activation window prepared for independent review."); await load(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Window preparation failed"); } finally { setBusy(false); }
  }

  async function act(action: string, extra: Record<string, unknown> = {}) {
    const selected = data?.windows.find((item) => item.id === selectedId) ?? data?.windows[0]; if (!selected) return;
    setBusy(true); setError(""); setNotice("");
    try { await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, windowId: selected.id, version: selected.version, ...extra }) }); setNotice(ar ? "تم تسجيل الخطوة في سجل التحكم." : "Control step recorded in the immutable trail."); await load(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Control step failed"); } finally { setBusy(false); }
  }

  const selected = data?.windows.find((item) => item.id === selectedId) ?? data?.windows[0]; const events = data?.events.filter((item) => item.windowId === selected?.id) ?? []; const admin = data?.role === "platform_admin"; const canReview = Boolean(selected?.status === "pending_review" && selected.preparedByUserId !== data?.currentUserId); const canIndependentlyVerify = Boolean(selected && selected.preparedByUserId !== data?.currentUserId && selected.openedByUserId !== data?.currentUserId);
  const p = data?.readiness.prerequisites; const posture = data?.posture;
  const checks = [
    { label: ar ? "سياسات دورة الحياة" : "Lifecycle policies", value: `${p?.approvedPolicyCount ?? 0}/${p?.requiredPolicyCount ?? 5}`, pass: p?.approvedPolicyCount === p?.requiredPolicyCount },
    { label: ar ? "خطة الاحتفاظ" : "Retention plan", value: p?.approvedRetentionPlan ? "approved" : "required", pass: p?.approvedRetentionPlan },
    { label: ar ? "بروفة السلامة" : "Safety rehearsal", value: `${p?.safetyScenarioCount ?? 0}/22`, pass: p?.freshSafetyRehearsal },
    { label: ar ? "مراجعة الحجز" : "Legal-hold review", value: `${p?.overdueLegalHoldCount ?? 0} overdue`, pass: p?.overdueLegalHoldCount === 0 },
    { label: ar ? "التخزين والماسح" : "Storage + scanner", value: p?.posture.protectedStorageConfigured && p?.posture.privateScannerConfigured ? "ready" : "blocked", pass: p?.posture.protectedStorageConfigured && p?.posture.privateScannerConfigured },
    { label: ar ? "ملكية التشغيل" : "Operating ownership", value: data?.readiness.ownershipReady ? "verified" : "required", pass: data?.readiness.ownershipReady },
  ];

  return <main className={styles.shell} dir={ar ? "rtl" : "ltr"} id="main-content">
    <aside className={styles.side}><a className={styles.brand} href="/admin"><Image src="/brand/qivaya-logo-reversed.png" width={124} height={47} alt="Qivaya" /></a><span className={styles.sideLabel}>{ar ? "عمليات المنصة" : "PLATFORM OPERATIONS"}</span><nav aria-label={ar ? "تنقل تفعيل المستندات" : "Document activation navigation"}><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a href="/admin/data-lifecycle">{ar ? "سياسات دورة الحياة" : "Lifecycle policies"}</a><a href="/admin/retention-automation">{ar ? "أتمتة الاحتفاظ" : "Retention automation"}</a><a className={styles.active} href="/admin/document-activation">{ar ? "تفعيل المستندات" : "Document activation"}</a><a href="/admin/data-lifecycle-acceptance">{ar ? "قبول دورة الحياة" : "Lifecycle acceptance"}</a><a href="/admin/audit">{ar ? "سجل التدقيق" : "Audit ledger"}</a></nav><div className={styles.sideNote}><i>⚑</i><div><b>{ar ? "تحكم دون تنفيذ" : "Governance without execution"}</b><p>{ar ? "تُنفذ تغييرات Vercel وCloudflare يدوياً. هذه المساحة تراقب الإعداد فقط ولا تحذف أي كائن." : "Vercel and Cloudflare changes remain manual. This workspace observes configuration and never deletes an object."}</p></div></div></aside>
    <section className={styles.workspace}><header className={styles.topbar}><a href="/admin/data-lifecycle-acceptance">← {ar ? "قبول دورة الحياة" : "Lifecycle acceptance"}</a><div><span data-ready={data?.readiness.preActivationReady}>{data?.readiness.preActivationReady ? (ar ? "جاهز قبل التفعيل" : "PRE-ACTIVATION READY") : (ar ? "مغلق افتراضياً" : "FAIL-CLOSED")}</span><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></div></header>
      <div className={styles.content}><section className={styles.hero}><div><p>{ar ? "تغيير إنتاج محكوم" : "CONTROLLED PRODUCTION CHANGE"}</p><h1>{ar ? "تفعيل خزنة المستندات" : "Medical document activation"}</h1><span>{ar ? "حوّل جاهزية دورة الحياة إلى نافذة إنتاج محددة، ومراجعة مستقلة، وتحقق من الوضع أو احتواء التراجع." : "Move lifecycle readiness through a time-boxed production window, independent review, posture verification, and rollback containment."}</span></div><div className={styles.heroSeal}><b>{data?.windows.filter((item) => item.status === "verified").length ?? 0}</b><span>{ar ? "تفعيلات موثقة" : "verified activations"}</span></div></section>
      {error && <div className={styles.error} role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>{ar ? "إعادة المحاولة" : "Retry"}</button></div>}{notice && <div className={styles.notice} role="status">✓ {notice}</div>}
      <section className={styles.boundary}>{checks.map((check) => <article key={check.label}><b>{check.pass ? "✓" : "!"}</b><span>{check.label}<br/>{check.value}</span></article>)}</section>
      <section className={styles.prepare}><div><p>{data?.workflowVersion ?? "medical-document-activation-v1"}</p><h2>{ar ? "إعداد نافذة الإنتاج" : "Prepare a production window"}</h2><span>{ar ? "لا تغير هذه الخطوة أي علم تشغيل أو مفتاح أو كائن R2." : "This step changes no runtime flag, credential, deployment, scanner request, or R2 object."}</span></div><form onSubmit={prepare}><label>{ar ? "مرجع الدليل المشفر" : "Coded evidence reference"}<input name="evidenceReference" pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{5,159}" placeholder="MDA-CHANGE-20260824-A1" required/></label><label>{ar ? "بداية النافذة" : "Window starts"}<input name="windowStartsAt" type="datetime-local" required/></label><label>{ar ? "نهاية النافذة" : "Window ends"}<input name="windowEndsAt" type="datetime-local" required/></label><label>{ar ? "مالك التغيير" : "Change owner"}<input name="changeOwner" maxLength={160} required/></label><label>{ar ? "مالك المراقبة" : "Monitoring owner"}<input name="monitoringOwner" maxLength={160} required/></label><label>{ar ? "مالك التراجع" : "Rollback owner"}<input name="rollbackOwner" maxLength={160} required/></label><button type="submit" disabled={busy || !admin || !data?.readiness.preActivationReady}>{busy ? (ar ? "جارٍ الإعداد…" : "Preparing…") : data?.readiness.preActivationReady ? (ar ? "إرسال للمراجعة" : "Send for review") : (ar ? "أكمل المتطلبات" : "Complete prerequisites")}</button></form></section>
      {loading ? <div className={styles.state}>{ar ? "جارٍ تحميل سجل التفعيل…" : "Loading activation ledger…"}</div> : !data?.windows.length ? <div className={styles.empty}><i>⚑</i><h2>{ar ? "لا توجد نافذة تفعيل" : "No activation window yet"}</h2><p>{ar ? "يبقى التفعيل مغلقاً حتى تكتمل كل متطلبات الحوكمة ويعتمد مشغل مستقل النافذة." : "Activation remains locked until every governance prerequisite passes and another operator approves a window."}</p></div> : <div className={styles.grid}><aside className={styles.history}><header><div><p>ACTIVATION LEDGER</p><h2>{ar ? "نوافذ الإنتاج" : "Production windows"}</h2></div><span>{data.windows.length}</span></header>{data.windows.map((item) => <button type="button" key={item.id} className={selected?.id === item.id ? styles.selected : ""} onClick={() => setSelectedId(item.id)}><i data-status={item.status}>{item.status === "verified" ? "✓" : item.status === "rolled_back" ? "↻" : "⚑"}</i><span><b>{item.reference}</b><small>{item.status.replaceAll("_", " ")} · {stamp(item.windowStartsAt, ar)}</small></span></button>)}</aside>
        <section className={styles.detail}>{selected && <><header><div><p>{selected.evidenceReference}</p><h2>{selected.status.replaceAll("_", " ")}</h2><span>{stamp(selected.windowStartsAt, ar)} — {stamp(selected.windowEndsAt, ar)}</span></div><em data-status={selected.status}>{posture?.allRuntimeControlsEnabled ? (ar ? "الوضع المستهدف ظاهر" : "target posture observed") : (ar ? "الضوابط الخطرة مغلقة" : "hazardous controls locked")}</em></header><div className={styles.owners}><article><span>{ar ? "التغيير" : "CHANGE"}</span><b>{selected.changeOwner}</b></article><article><span>{ar ? "المراقبة" : "MONITOR"}</span><b>{selected.monitoringOwner}</b></article><article><span>{ar ? "التراجع" : "ROLLBACK"}</span><b>{selected.rollbackOwner}</b></article></div><div className={styles.actions}>
          {selected.status === "pending_review" && <><button type="button" className={styles.secondary} disabled={busy || !canReview} onClick={() => void act("review", { decision: "return", reviewNote: "Activation evidence or ownership requires revision." })}>{ar ? "إرجاع" : "Return"}</button><button type="button" disabled={busy || !canReview} onClick={() => void act("review", { decision: "approve", reviewNote: "Independently reviewed the coded plan, owners, bounds, and rollback procedure." })}>{ar ? "اعتماد النافذة" : "Approve window"}</button></>}
          {selected.status === "approved" && <button type="button" disabled={busy || !admin} onClick={() => void act("open")}>{ar ? "فتح النافذة" : "Open approved window"}</button>}
          {selected.status === "in_progress" && <><button type="button" className={styles.secondary} disabled={busy || !admin} onClick={() => void act("request_rollback")}>{ar ? "طلب التراجع" : "Request rollback"}</button><button type="button" disabled={busy || !admin} onClick={() => void act("observe")}>{ar ? "التقاط الوضع" : "Observe server posture"}</button></>}
          {selected.status === "verification_pending" && <><button type="button" className={styles.secondary} disabled={busy || !admin} onClick={() => void act("request_rollback")}>{ar ? "طلب التراجع" : "Request rollback"}</button><button type="button" disabled={busy || !canIndependentlyVerify} onClick={() => void act("verify", { verificationNote: "Independently revalidated the complete production posture and current governance evidence." })}>{ar ? "توثيق التفعيل" : "Verify activation"}</button></>}
          {selected.status === "rollback_required" && <button type="button" disabled={busy || !canIndependentlyVerify} onClick={() => void act("verify_rollback")}>{ar ? "توثيق احتواء التراجع" : "Verify rollback containment"}</button>}
        </div><div className={styles.timeline}><h3>{ar ? "أثر تحكمي غير قابل للتعديل" : "Immutable control trail"}</h3>{events.map((item) => <article key={item.id}><i>•</i><div><b>{item.eventCode.replaceAll("_", " ")}</b><span>{item.previousStatus ? `${item.previousStatus} → ` : ""}{item.nextStatus} · {stamp(item.createdAt, ar)}</span></div></article>)}</div></>}</section></div>}
      </div></section>
  </main>;
}
