"use client";

import { useState } from "react";

type Tab="catalog"|"availability"|"locations";
type Service={id:number,name:string,nameAr:string,category:string,categoryAr:string,duration:number,price:number,status:"Published"|"Draft"|"Restricted",bookings:number,mode:string};
const initial:Service[]=[
  {id:1,name:"Family medicine consultation",nameAr:"استشارة طب الأسرة",category:"Consultation",categoryAr:"استشارة",duration:30,price:250,status:"Published",bookings:86,mode:"In-person"},
  {id:2,name:"Annual health review",nameAr:"مراجعة صحية سنوية",category:"Preventive care",categoryAr:"رعاية وقائية",duration:45,price:350,status:"Published",bookings:31,mode:"In-person"},
  {id:3,name:"Chronic care follow-up",nameAr:"متابعة الرعاية المزمنة",category:"Follow-up",categoryAr:"متابعة",duration:30,price:220,status:"Published",bookings:58,mode:"In-person"},
  {id:4,name:"Video follow-up",nameAr:"متابعة عبر الفيديو",category:"Virtual care",categoryAr:"رعاية افتراضية",duration:20,price:180,status:"Restricted",bookings:0,mode:"Video"},
  {id:5,name:"Travel health consultation",nameAr:"استشارة صحة السفر",category:"Consultation",categoryAr:"استشارة",duration:30,price:280,status:"Draft",bookings:0,mode:"In-person"},
];

export default function ProviderServices(){
  const [lang,setLang]=useState<"en"|"ar">("en");const [tab,setTab]=useState<Tab>("catalog");const [services,setServices]=useState(initial);const [selected,setSelected]=useState<Service|null>(null);const [notice,setNotice]=useState("");const [week,setWeek]=useState(0);const ar=lang==="ar";
  const save=(publish=false)=>{if(selected){setServices(v=>v.map(s=>s.id===selected.id?{...s,status:publish?"Published":s.status}:s));setSelected(null);setNotice(publish?(ar?"تم نشر الخدمة التجريبية":"Prototype service published"):(ar?"تم حفظ التغييرات":"Changes saved"))}};
  return <main className={`services-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <aside className="services-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar?"بوابة مقدم الرعاية":"Provider console"}</span></a><div className="services-facility"><span>AN</span><div><b>{ar?"مركز النور الطبي":"Al Noor Medical Center"}</b><small>{ar?"فرع الوعب":"Al Waab location"}</small></div></div><nav><a href="/provider"><span>◫</span>{ar?"اليوم":"Today"}</a><a href="/provider"><span>□</span>{ar?"التقويم":"Calendar"}</a><a href="/provider/patients"><span>♙</span>{ar?"المرضى":"Patients"}</a><a className="active" href="/provider/services"><span>◇</span>{ar?"الخدمات":"Services"}<i>5</i></a><a href="/provider/insights"><span>↗</span>{ar?"التقارير":"Insights"}</a><a href="/provider/settings"><span>⚙</span>{ar?"الإعدادات":"Settings"}</a></nav><div className="services-side-bottom"><a href="/journeys">◇ {ar?"جميع المسارات":"All journeys"}</a><a href="/provider">← {ar?"لوحة مقدم الرعاية":"Provider dashboard"}</a><p>{ar?"بيانات اصطناعية · لا توجد صلاحيات نشر حقيقية":"Synthetic data · No live publishing"}</p></div></aside>
    <section className="services-main"><header className="services-top"><div><span>⌖</span><div><b>{ar?"مركز النور الطبي · الوعب":"Al Noor Medical Center · Al Waab"}</b><small>{ar?"مدير الخدمات · صلاحيات محددة":"Service manager · scoped permissions"}</small></div></div><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a href="/notifications">●</a><span>LK</span></div></header>
      <div className="services-workspace"><div className="services-heading"><div><p>{ar?"الكتالوج والجدولة":"CATALOG & SCHEDULING"}</p><h1>{ar?"الخدمات والتوفر":"Services & availability"}</h1><span>{ar?"حافظ على دقة ما يراه المرضى من خدمة وسعر وموعد وموقع.":"Keep every patient-facing service, price, time, and location accurate."}</span></div><button onClick={()=>setSelected({id:99,name:"New service",nameAr:"خدمة جديدة",category:"Consultation",categoryAr:"استشارة",duration:30,price:250,status:"Draft",bookings:0,mode:"In-person"})}>＋ {ar?"إضافة خدمة":"Add service"}</button></div><div className="publish-warning"><span>!</span><p><b>{ar?"النشر الجديد مقيد مؤقتاً":"New publishing is temporarily restricted"}</b>{ar?"تنتهي صلاحية الترخيص المهني خلال ٢١ يوماً. يمكن تعديل الخدمات المنشورة، لكن يتطلب نشر خدمة جديدة تجديد الإثبات.":"The professional licence expires in 21 days. Published services can be edited, but a new service requires renewed evidence."}</p><a href="/provider">{ar?"مراجعة التحقق":"Review verification"} →</a></div><div className="services-metrics"><article><span>◇</span><div><b>3</b><p>{ar?"خدمات منشورة":"Published services"}</p></div></article><article><span>□</span><div><b>175</b><p>{ar?"فترة متاحة هذا الشهر":"Open slots this month"}</p></div></article><article><span>Q</span><div><b>QAR 250</b><p>{ar?"متوسط السعر":"Average price"}</p></div></article><article><span>⌖</span><div><b>1</b><p>{ar?"موقع نشط":"Active location"}</p></div></article></div><div className="services-tabs"><button className={tab==="catalog"?"active":""} onClick={()=>setTab("catalog")}>{ar?"كتالوج الخدمات":"Service catalog"}</button><button className={tab==="availability"?"active":""} onClick={()=>setTab("availability")}>{ar?"قوالب التوفر":"Availability templates"}</button><button className={tab==="locations"?"active":""} onClick={()=>setTab("locations")}>{ar?"المواقع":"Locations"}</button></div>
        {tab==="catalog"&&<section className="service-catalog"><div className="catalog-tools"><div><button className="active">{ar?"الكل":"All"} <span>5</span></button><button>{ar?"منشور":"Published"} <span>3</span></button><button>{ar?"مسودة":"Draft"} <span>1</span></button></div><label>⌕<input placeholder={ar?"البحث عن خدمة":"Search services"}/></label></div><div className="service-table"><div className="service-head"><span>{ar?"الخدمة":"Service"}</span><span>{ar?"الطريقة":"Mode"}</span><span>{ar?"المدة":"Duration"}</span><span>{ar?"السعر":"Price"}</span><span>{ar?"الحجوزات":"Bookings"}</span><span>{ar?"الحالة":"Status"}</span><span/></div>{services.map(s=><button key={s.id} onClick={()=>setSelected(s)}><div><span>◇</span><p><b>{ar?s.nameAr:s.name}</b><small>{ar?s.categoryAr:s.category}</small></p></div><span>{s.mode}</span><span>{s.duration} min</span><strong>{s.price} QAR</strong><span>{s.bookings}</span><i className={s.status.toLowerCase()}>{s.status}</i><em>›</em></button>)}</div></section>}
        {tab==="availability"&&<section className="availability-view"><div className="availability-head"><div><h2>{ar?"جدول د. ليلى":"Dr. Laila’s schedule"}</h2><p>{ar?"قالب أسبوعي · التوقيت المحلي للدوحة":"Weekly template · Doha local time"}</p></div><div><button onClick={()=>setWeek(v=>v-1)}>‹</button><b>{week===0?(ar?"هذا الأسبوع":"This week"):week>0?(ar?"الأسبوع القادم":"Next week"):(ar?"الأسبوع السابق":"Previous week")}</b><button onClick={()=>setWeek(v=>v+1)}>›</button></div></div><div className="availability-grid">{[["SUN","08:00 – 16:00",8],["MON","09:00 – 17:00",9],["TUE","08:00 – 14:00",6],["WED","10:00 – 18:00",8],["THU","08:00 – 13:00",5]].map(([day,time,count],i)=><article key={String(day)}><div><b>{day}</b><span>{time}</span></div><p><i style={{width:`${Number(count)*10}%`}}/></p><small>{count} {ar?"فترات متاحة":"open slots"}</small><button>{ar?"تعديل":"Edit"}</button></article>)}</div><div className="availability-rules"><h2>{ar?"قواعد الحجز":"Booking rules"}</h2>{[["Minimum notice","2 hours"],["Maximum advance booking","60 days"],["Buffer between visits","10 minutes"],["Same-day booking","Enabled"]].map(r=><div key={r[0]}><span>{r[0]}</span><b>{r[1]}</b><button>{ar?"تعديل":"Edit"}</button></div>)}</div></section>}
        {tab==="locations"&&<section className="locations-view"><article><div className="location-map"><span>⌖</span><i/><b>Al Waab</b></div><div className="location-copy"><p>{ar?"موقع نشط":"ACTIVE LOCATION"}</p><h2>{ar?"مركز النور الطبي":"Al Noor Medical Center"}</h2><span>{ar?"شارع الوعب، الدوحة · الطابق الثاني":"Al Waab Street, Doha · Level 2"}</span><ul><li>♿ {ar?"مدخل ومصعد مهيآن":"Accessible entrance and lift"}</li><li>▣ {ar?"مواقف سيارات متاحة":"Patient parking available"}</li><li>◎ {ar?"غرفة صلاة":"Prayer room"}</li></ul><div><button>{ar?"تعديل التفاصيل":"Edit details"}</button><button>{ar?"إدارة ساعات العمل":"Manage hours"}</button></div></div><aside><p>{ar?"الخدمات في هذا الموقع":"Services here"}</p><b>4</b><small>{ar?"٣ منشورة · ١ مقيدة":"3 published · 1 restricted"}</small><hr/><p>{ar?"السعة هذا الأسبوع":"Capacity this week"}</p><b>36</b><small>{ar?"فترة متاحة":"open slots"}</small></aside></article><button className="add-location">＋ {ar?"طلب إضافة موقع":"Request another location"}</button></section>}
      </div>
    </section>
    {selected&&<div className="service-drawer-layer" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="service-drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p>{selected.id===99?(ar?"خدمة جديدة":"NEW SERVICE"):(ar?"تعديل الخدمة":"EDIT SERVICE")}</p><h2>{ar?selected.nameAr:selected.name}</h2><div className="service-drawer-status"><span className={selected.status.toLowerCase()}>{selected.status}</span><b>SRV-{String(selected.id).padStart(4,"0")}</b></div><label>{ar?"اسم الخدمة بالإنجليزية":"Service name in English"}<input defaultValue={selected.name}/></label><label>{ar?"اسم الخدمة بالعربية":"Service name in Arabic"}<input defaultValue={selected.nameAr}/></label><div className="service-form-grid"><label>{ar?"الفئة":"Category"}<select defaultValue={selected.category}><option>Consultation</option><option>Preventive care</option><option>Follow-up</option><option>Virtual care</option></select></label><label>{ar?"طريقة التقديم":"Mode"}<select defaultValue={selected.mode}><option>In-person</option><option>Video</option></select></label><label>{ar?"المدة":"Duration"}<select defaultValue={selected.duration}><option value="20">20 min</option><option value="30">30 min</option><option value="45">45 min</option></select></label><label>{ar?"السعر الإجمالي":"Total price"}<div className="price-input"><span>QAR</span><input defaultValue={selected.price}/></div></label></div><label>{ar?"وصف واضح للمريض":"Patient-facing description"}<textarea defaultValue={ar?"استشارة واضحة مع مقدم رعاية موثّق، تشمل مراجعة الأعراض والخطة التالية.":"A clear consultation with a verified provider, including review and next-step planning."}/></label><div className="price-truth"><span>Q</span><p><b>{ar?"يجب أن يكون السعر كاملاً":"Price must be complete"}</b>{ar?"يشمل السعر المعروض جميع الرسوم الإلزامية المعروفة قبل الحجز.":"The displayed amount includes all known mandatory fees before booking."}</p></div>{selected.id===99&&<div className="publish-gate"><span>!</span><p><b>{ar?"يتطلب النشر تجديد الترخيص":"Publishing requires renewed evidence"}</b>{ar?"يمكن حفظ الخدمة كمسودة الآن.":"You can save this service as a draft now."}</p></div>}<div className="service-drawer-actions"><button onClick={()=>save(false)}>{ar?"حفظ كمسودة":"Save draft"}</button><button disabled={selected.id===99} onClick={()=>save(true)}>{ar?"نشر التغييرات":"Publish changes"}</button></div></aside></div>}
    {notice&&<div className="service-toast"><span>✓</span>{notice}<button onClick={()=>setNotice("")}>×</button></div>}
  </main>
}
