"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import PatientHeader from "@/app/components/PatientHeader";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";

type Topic = "booking" | "payment" | "complaint" | "privacy" | "safety";
type SupportCase = { id:string; reference:string; category:string; subject:string; status:string; priority:string; version:number; updatedAt:string };
type Message = { id:string; caseId:string; authorKind:string; body:string; createdAt:string };
function topics(ar:boolean):{id:Topic;icon:string;title:string;text:string}[]{return [
  {id:"booking",icon:"◎",title:ar?"الحجوزات والمواعيد":"Booking & appointments",text:ar?"التغييرات أو الإلغاء أو الوصول أو توفر مقدم الرعاية":"Changes, cancellations, arrival, or provider availability"},
  {id:"payment",icon:"Q",title:ar?"المدفوعات والاستردادات":"Payments & refunds",text:ar?"أسئلة عن حالة الدفع أو الاسترداد المسجلة":"Recorded payment or refund status questions"},
  {id:"complaint",icon:"◇",title:ar?"شكوى عن الخدمة":"Service complaint",text:ar?"مخاوف بشأن الوصول أو السلوك أو التجربة":"Concerns about access, conduct, or experience"},
  {id:"privacy",icon:"♙",title:ar?"طلب خصوصية":"Privacy request",text:ar?"الوصول إلى البيانات المؤهلة أو تصحيحها أو تصديرها أو تقييدها أو حذفها":"Access, correct, export, restrict, or delete eligible data"},
  {id:"safety",icon:"!",title:ar?"ملاحظة تتعلق بالسلامة":"Safety concern",text:ar?"الإبلاغ عن مشكلة سلامة سريرية أو خدمية غير طارئة":"Report a non-emergency clinical or service safety issue"},
];}

async function api(init?:RequestInit) {
  const response=await fetch("/api/support",init); const payload=await response.json().catch(()=>({})) as {data?:unknown;message?:string;error?:string};
  if(response.status===401){window.location.assign(`/sign-in?redirect_url=${encodeURIComponent("/support")}`);throw new Error("Authentication required");}
  if(!response.ok) throw new Error(payload.message||payload.error||"Support is temporarily unavailable"); return payload.data;
}
function label(value:string,ar=false){const labels:Record<string,string>={open:"مفتوح",in_progress:"قيد المعالجة",waiting_requester:"بانتظار مقدم الطلب",resolved:"تم الحل",closed:"مغلق",booking:"الحجوزات",payment:"المدفوعات",complaint:"الشكاوى",privacy:"الخصوصية",safety:"السلامة"};return ar?labels[value]||value.replaceAll("_"," "):value.replaceAll("_"," ").replace(/^./,(letter)=>letter.toUpperCase());}

export default function Support(){
  const [lang,setLang]=useReyatiLocale(); const ar=lang==="ar"; const topicOptions=topics(ar);
  const [cases,setCases]=useState<SupportCase[]>([]); const [messages,setMessages]=useState<Message[]>([]); const [loading,setLoading]=useState(true);
  const [topic,setTopic]=useState<Topic|null>(null); const [selected,setSelected]=useState<SupportCase|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const thread=useMemo(()=>messages.filter((message)=>message.caseId===selected?.id),[messages,selected]);
  async function load(){const data=await api() as {cases:SupportCase[];messages:Message[]};setCases(data.cases);setMessages(data.messages);if(selected)setSelected(data.cases.find((item)=>item.id===selected.id)||null);}
  useEffect(()=>{let active=true;const controller=new AbortController();api({signal:controller.signal}).then((value)=>{if(active){const data=value as {cases:SupportCase[];messages:Message[]};setCases(data.cases);setMessages(data.messages);}}).catch((caught)=>{if(active&&(!(caught instanceof DOMException)||caught.name!=="AbortError"))setError(caught instanceof Error?caught.message:"Support unavailable");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};},[]);
  async function retry(){setLoading(true);setError("");try{await load();}catch(caught){setError(caught instanceof Error?caught.message:"Support unavailable");}finally{setLoading(false);}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!topic)return;setSaving(true);setError("");const form=new FormData(event.currentTarget);try{const created=await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category:topic,description:form.get("description"),relatedReference:form.get("relatedReference"),privacyRequestType:form.get("privacyRequestType")})}) as SupportCase;setTopic(null);setNotice(`${created.reference} created and securely routed`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"Request could not be created");}finally{setSaving(false);}}
  async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setSaving(true);const form=new FormData(event.currentTarget);try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reply",caseId:selected.id,message:form.get("message")})});event.currentTarget.reset();setNotice("Reply added to your support request");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Reply could not be sent");}finally{setSaving(false);}}
  return <main className={`support-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"} id="main-content">
    <PatientHeader ar={ar} displayName={ar ? "عضو كيفايا" : "Qivaya member"} onLocaleChange={() => setLang(ar ? "en" : "ar")} active="messages" />
    <section className="support-hero"><div><p>{ar?"المساعدة المناسبة عبر المسار المناسب":"THE RIGHT HELP, THROUGH THE RIGHT PATH"}</p><h1>{ar?"كيف يمكننا مساعدتك؟":"How can we help?"}</h1><span>{ar?"أنشئ طلبات دعم آمنة ومملوكة لحسابك وتابعها.":"Create and track secure, account-owned support requests."}</span></div></section>
    <section className="support-workspace"><div className="emergency-banner"><span>＋</span><div><b>{ar?"هل هناك شخص في خطر فوري؟":"Is someone in immediate danger?"}</b><p>{ar?"لا تنتظر رداً داخل التطبيق. في قطر، اتصل بخدمات الطوارئ فوراً على 999.":"Do not wait for an in-app response. In Qatar, call emergency services immediately on 999."}</p></div><a href="tel:999">{ar?"اتصل بـ 999":"Call 999"}</a></div>
      {error&&<div className="family-live-alert error"><span>{error}</span><button type="button" onClick={()=>void retry()}>{ar?"حاول مرة أخرى":"Try again"}</button></div>}{notice&&<div className="family-live-alert success"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
      <div className="support-grid"><section><div className="support-section-head"><div><h2>{ar?"اختر نوع المساعدة التي تحتاجها":"Choose what you need help with"}</h2><p>{ar?"يُوجّه كل طلب حسب فئته ويُسجل في حسابك.":"Each request is routed by category and recorded in your account."}</p></div></div><div className="support-topics">{topicOptions.map((item)=><button className={item.id==="safety"?"safety":""} key={item.id} onClick={()=>setTopic(item.id)}><span>{item.icon}</span><div><b>{item.title}</b><small>{item.text}</small></div><i>›</i></button>)}</div></section>
        <aside><section className="case-card"><div><h2>{ar?"طلبات الدعم الخاصة بك":"Your support requests"}</h2><span>{cases.filter((item)=>!["resolved","closed"].includes(item.status)).length}</span></div>{loading?<p>{ar?"جارٍ تحميل طلباتك…":"Loading your requests…"}</p>:error?<p>{ar?"طلبات الدعم غير متاحة. حاول مرة أخرى قبل الاعتماد على هذه القائمة.":"Support requests are unavailable. Try again before relying on this list."}</p>:cases.length===0?<p>{ar?"لا توجد طلبات دعم بعد.":"No support requests yet."}</p>:cases.map((item)=><button key={item.id} onClick={()=>setSelected(item)}><i className={item.priority==="critical"?"case-gold":"case-blue"}>◎</i><div><p>{item.subject}</p><b>{item.reference}</b><small>{label(item.status,ar)} · {new Date(item.updatedAt).toLocaleString(ar?"ar-QA":"en-QA")}</small></div><em>›</em></button>)}</section><section className="support-promise"><span>♙</span><h2>{ar?"ما الذي يمكنك توقعه":"What you can expect"}</h2><ul><li>{ar?"مرجع دائم لكل طلب":"A durable reference for every request"}</li><li>{ar?"تحديثات في صندوق الإشعارات":"Updates in your notification inbox"}</li><li>{ar?"وصول يقتصر على أدوار الدعم المصرح بها":"Access limited to authorized support roles"}</li><li>{ar?"مسارات منفصلة للخصوصية والسلامة":"Separate privacy and safety routing"}</li></ul></section></aside></div>
    </section>
    {topic&&<div className="support-modal-layer" onMouseDown={(event)=>event.target===event.currentTarget&&setTopic(null)}><form className={`support-modal ${topic==="safety"?"safety-modal":""}`} onSubmit={create}><button type="button" className="drawer-close" onClick={()=>setTopic(null)} aria-label={ar?"إغلاق":"Close"}>×</button><p>{ar?"طلب جديد":"NEW REQUEST"}</p><h2>{topicOptions.find((item)=>item.id===topic)?.title}</h2>{topic==="safety"&&<div className="modal-emergency"><span>!</span><p><b>{ar?"هذه القناة ليست للطوارئ":"This channel is not for emergencies"}</b>{ar?"إذا كان هناك خطر فوري أو حاجة طبية تهدد الحياة، فاتصل الآن على 999.":"If there is immediate danger or a life-threatening medical need, call 999 now."}</p><a href="tel:999">999</a></div>}<label>{ar?"ماذا حدث؟":"What happened?"}<textarea name="description" required maxLength={4000}/><small>{ar?"تجنب المعلومات الصحية ما لم تكن ضرورية لهذا الطلب.":"Avoid health information unless it is necessary for this request."}</small></label>{topic==="privacy"&&<label>{ar?"نوع الطلب":"Request type"}<select name="privacyRequestType"><option>{ar?"الوصول إلى بياناتي":"Access my data"}</option><option>{ar?"تصحيح بياناتي":"Correct my data"}</option><option>{ar?"تصدير بياناتي":"Export my data"}</option><option>{ar?"تقييد المعالجة":"Restrict processing"}</option><option>{ar?"حذف البيانات المؤهلة":"Delete eligible data"}</option></select></label>}<label>{ar?"مرجع ذو صلة (اختياري)":"Related reference (optional)"}<input name="relatedReference" maxLength={128}/></label><div className="routing-note"><span>♙</span><p><b>{ar?"وصول حسب الحاجة":"Need-to-know access"}</b>{ar?"يمكن فقط للموظفين المصرح لهم والمكلفين بمسار الدعم المناسب إدارة هذا الطلب.":"Only authorized staff assigned to the relevant support workflow can manage this request."}</p></div><button type="submit" className="submit-support" disabled={saving}>{saving?(ar?"جارٍ الإنشاء…":"Creating…"):(ar?"إنشاء الطلب":"Create request")}</button></form></div>}
    {selected&&<div className="support-modal-layer" onMouseDown={(event)=>event.target===event.currentTarget&&setSelected(null)}><section className="case-detail"><button className="drawer-close" onClick={()=>setSelected(null)} aria-label={ar?"إغلاق":"Close"}>×</button><p>{selected.subject}</p><h2>{selected.reference}</h2><div className="case-status"><span>●</span><div><b>{label(selected.status,ar)}</b><small>{label(selected.category,ar)} {ar?"فريق":"team"}</small></div></div><div className="case-thread">{thread.map((message)=><article className={message.authorKind==="requester"?"mine":""} key={message.id}><span>{message.authorKind==="requester"?(ar?"أنت":"YOU"):"RS"}</span><div><b>{message.authorKind==="requester"?(ar?"أنت":"You"):(ar?"دعم كيفايا":"Qivaya Support")}<small>{new Date(message.createdAt).toLocaleString(ar?"ar-QA":"en-QA")}</small></b><p>{message.body}</p></div></article>)}</div>{!["resolved","closed"].includes(selected.status)&&<form className="case-reply" onSubmit={reply}><textarea name="message" required maxLength={4000} placeholder={ar?"اكتب ردك…":"Write your reply…"}/><button type="submit" disabled={saving}>{saving?(ar?"جارٍ الإرسال…":"Sending…"):(ar?"إرسال":"Send")}</button></form>}<small className="case-footnote">{ar?"تتوفر في هذه الحالة فقط المعلومات اللازمة لحل الطلب.":"Only information needed to resolve this request is available in this case."}</small></section></div>}
  </main>;
}
