"use client";

import { useState } from "react";

type Topic="booking"|"payment"|"complaint"|"privacy"|"safety";
const topicData:{id:Topic,icon:string,title:string,titleAr:string,text:string,textAr:string}[]=[
  {id:"booking",icon:"◎",title:"Booking & appointments",titleAr:"الحجز والمواعيد",text:"Changes, cancellations, arrival, or provider availability",textAr:"التغييرات والإلغاء والوصول أو توفر مقدم الرعاية"},
  {id:"payment",icon:"Q",title:"Payments & refunds",titleAr:"المدفوعات والاستردادات",text:"Charges, benefits, receipts, and refund tracking",textAr:"الرسوم والمزايا والإيصالات وتتبع الاسترداد"},
  {id:"complaint",icon:"◇",title:"Service complaint",titleAr:"شكوى عن الخدمة",text:"Share concerns about access, conduct, or experience",textAr:"شارك مخاوفك بشأن الوصول أو السلوك أو التجربة"},
  {id:"privacy",icon:"♙",title:"Privacy request",titleAr:"طلب خصوصية",text:"Access, correct, export, restrict, or delete data",textAr:"الوصول أو التصحيح أو التصدير أو التقييد أو الحذف"},
  {id:"safety",icon:"!",title:"Safety concern",titleAr:"مخاوف السلامة",text:"Report a non-emergency clinical or service safety issue",textAr:"الإبلاغ عن مشكلة سلامة سريرية أو خدمية غير طارئة"},
];

export default function Support(){
  const [lang,setLang]=useState<"en"|"ar">("en");const [topic,setTopic]=useState<Topic|null>(null);const [submitted,setSubmitted]=useState(false);const [detail,setDetail]=useState(false);const [query,setQuery]=useState("");const ar=lang==="ar";
  const open=(t:Topic)=>{setTopic(t);setSubmitted(false)};
  const chosen=topicData.find(t=>t.id===topic);
  return <main className={`support-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <header className="support-header"><a className="brand" href="/"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav><a href="/providers">{ar?"ابحث عن رعاية":"Find care"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a><a href="/wallet">{ar?"المحفظة الصحية":"Health wallet"}</a><a className="active" href="/support">{ar?"الدعم":"Support"}</a></nav><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a href="/notifications">●</a><span>MA</span></div></header>
    <section className="support-hero"><div><p>{ar?"المساعدة المناسبة، بالمسار المناسب":"THE RIGHT HELP, THROUGH THE RIGHT PATH"}</p><h1>{ar?"كيف يمكننا المساعدة؟":"How can we help?"}</h1><span>{ar?"احصل على إجابات، تتبع طلباً، أو تواصل مع الفريق المختص بأمان.":"Find answers, track a request, or reach the right team safely."}</span><label><i>⌕</i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?"ابحث عن إجابة أو موضوع دعم":"Search for an answer or support topic"}/><button>{ar?"بحث":"Search"}</button></label></div></section>
    <section className="support-workspace">
      <div className="emergency-banner"><span>＋</span><div><b>{ar?"هل هناك خطر فوري على الحياة؟":"Is someone in immediate danger?"}</b><p>{ar?"لا تنتظر رداً داخل التطبيق. في قطر، اتصل فوراً بخدمات الطوارئ على الرقم 999.":"Do not wait for an in-app response. In Qatar, call emergency services immediately on 999."}</p></div><a href="tel:999">{ar?"اتصل بـ 999":"Call 999"}</a></div>
      <div className="support-grid"><section><div className="support-section-head"><div><h2>{ar?"اختر نوع المساعدة":"Choose what you need help with"}</h2><p>{ar?"سنوجه طلبك إلى فريق منفصل ومحدد الصلاحيات.":"We’ll route your request to a separate, permission-scoped team."}</p></div></div><div className="support-topics">{topicData.filter(t=>!query||`${t.title} ${t.titleAr} ${t.text} ${t.textAr}`.toLowerCase().includes(query.toLowerCase())).map(t=><button className={t.id==="safety"?"safety":""} key={t.id} onClick={()=>open(t.id)}><span>{t.icon}</span><div><b>{ar?t.titleAr:t.title}</b><small>{ar?t.textAr:t.text}</small></div><i>›</i></button>)}</div><section className="self-service"><div className="support-section-head"><div><h2>{ar?"إجابات سريعة":"Quick answers"}</h2><p>{ar?"حلول واضحة للطلبات الشائعة":"Clear guidance for common requests"}</p></div><button>{ar?"عرض الكل":"View all"}</button></div>{[["How do I reschedule without a fee?","كيف أعيد الجدولة دون رسوم؟"],["When will my refund arrive?","متى سيصل الاسترداد؟"],["Who can see my health wallet?","من يمكنه رؤية محفظتي الصحية؟"],["How are providers verified?","كيف يتم التحقق من مقدمي الرعاية؟"]].map(q=><details key={q[0]}><summary>{ar?q[1]:q[0]}<span>＋</span></summary><p>{ar?"ستظهر الإجابة الكاملة هنا مع روابط مباشرة إلى الإجراء المناسب وسجل واضح لأي تغيير.":"The full answer appears here with direct links to the relevant action and a clear record of any change."}</p></details>)}</section></section>
        <aside><section className="case-card"><div><h2>{ar?"طلباتك المفتوحة":"Your open requests"}</h2><span>2</span></div><button onClick={()=>setDetail(true)}><i className="case-blue">◎</i><div><p>{ar?"دعم موعد":"Appointment support"}</p><b>SUP-260802-184</b><small>{ar?"بانتظار ردك · منذ ساعتين":"Waiting for you · 2 hours ago"}</small></div><em>›</em></button><button onClick={()=>setDetail(true)}><i className="case-gold">↻</i><div><p>{ar?"استرداد":"Refund"}</p><b>RFD-260802-8814</b><small>{ar?"قيد المعالجة · اليوم":"Processing · Today"}</small></div><em>›</em></button><a href="/payments">{ar?"عرض سجل المدفوعات":"View payment history"} →</a></section><section className="support-promise"><span>♙</span><h2>{ar?"ما الذي يمكنك توقعه":"What you can expect"}</h2><ul><li>{ar?"رقم مرجعي لكل طلب":"A reference for every request"}</li><li>{ar?"تحديثات داخل التطبيق":"Updates in the app"}</li><li>{ar?"وصول محدود للفريق المختص":"Access limited to the assigned team"}</li><li>{ar?"مسار مستقل للخصوصية والسلامة":"Separate privacy and safety routes"}</li></ul></section></aside></div>
    </section>
    {topic&&<div className="support-modal-layer" onMouseDown={e=>e.target===e.currentTarget&&setTopic(null)}><section className={`support-modal ${topic==="safety"?"safety-modal":""}`}><button className="drawer-close" onClick={()=>setTopic(null)}>×</button>{submitted?<div className="support-success"><span>✓</span><p>{ar?"تم إنشاء الطلب":"REQUEST CREATED"}</p><h2>{topic==="safety"?(ar?"تمت الإحالة إلى فريق السلامة":"Routed to the safety team"):(ar?"طلبك في المسار الصحيح":"Your request is with the right team")}</h2><b>{topic==="privacy"?"PRV-260802-092":topic==="safety"?"SAF-260802-031":"SUP-260802-196"}</b><small>{ar?"ستظهر التحديثات في مركز الإشعارات. هذه محاكاة ولا يتم إرسال بيانات حقيقية.":"Updates will appear in the Notification Centre. This is a simulation and no real data is sent."}</small><button onClick={()=>setTopic(null)}>{ar?"تم":"Done"}</button></div>:<><p>{ar?"طلب جديد":"NEW REQUEST"}</p><h2>{chosen&&(ar?chosen.titleAr:chosen.title)}</h2>{topic==="safety"&&<div className="modal-emergency"><span>!</span><p><b>{ar?"هذه القناة ليست للطوارئ":"This channel is not for emergencies"}</b>{ar?"إذا كان هناك خطر فوري أو حاجة طبية عاجلة لإنقاذ الحياة، اتصل بـ 999 الآن.":"If there is immediate danger or a life-threatening medical need, call 999 now."}</p><a href="tel:999">999</a></div>}<label>{ar?"ما الذي حدث؟":"What happened?"}<textarea defaultValue={topic==="payment"?"I need help understanding the status of my refund.":topic==="privacy"?"I would like a copy of my Reyati data.":topic==="safety"?"I want to report a non-emergency safety concern.":"I need help with my Reyati experience."}/><small>{ar?"لا تضف معلومات صحية إلا إذا كانت ضرورية لهذا الطلب.":"Avoid health information unless it is necessary for this request."}</small></label>{topic==="privacy"&&<label>{ar?"نوع الطلب":"Request type"}<select><option>Access my data</option><option>Correct my data</option><option>Export my data</option><option>Restrict processing</option><option>Delete eligible data</option></select></label>}<label>{ar?"مرجع مرتبط (اختياري)":"Related reference (optional)"}<input defaultValue={topic==="payment"?"RFD-260802-8814":topic==="booking"?"RYT-260802-1042":""} placeholder="RYT-••••••-••••"/></label><div className="routing-note"><span>♙</span><p><b>{ar?"الوصول حسب الحاجة":"Need-to-know access"}</b>{topic==="privacy"?(ar?"يتم توجيه هذا الطلب إلى فريق الخصوصية فقط.":"This request routes only to the privacy team."):topic==="safety"?(ar?"يتم توجيه هذا الطلب إلى فريق السلامة وليس دعم العملاء العام.":"This routes to the safety team, not general support."):(ar?"سيتمكن فريق الدعم المخصص فقط من رؤية هذه الحالة.":"Only the assigned support team can view this case.")}</p></div><button className="submit-support" onClick={()=>setSubmitted(true)}>{ar?"إنشاء الطلب":"Create request"}</button></>}</section></div>}
    {detail&&<div className="support-modal-layer" onMouseDown={e=>e.target===e.currentTarget&&setDetail(false)}><section className="case-detail"><button className="drawer-close" onClick={()=>setDetail(false)}>×</button><p>{ar?"طلب دعم موعد":"APPOINTMENT SUPPORT"}</p><h2>SUP-260802-184</h2><div className="case-status"><span>●</span><div><b>{ar?"بانتظار ردك":"Waiting for you"}</b><small>{ar?"فريق دعم الحجوزات":"Booking support team"}</small></div></div><div className="case-thread"><article><span>RS</span><div><b>{ar?"ريم · فريق دعم رعايتي":"Reem · Reyati Support"}<small>{ar?"اليوم، ١١:٠٥ ص":"Today, 11:05 AM"}</small></b><p>{ar?"أكدت المنشأة أنها تستطيع استقبال المريضة قبل ١٥ دقيقة. هل تريدين الاحتفاظ بالموعد؟":"The facility confirmed they can receive the patient 15 minutes early. Would you like to keep the appointment?"}</p></div></article><article className="mine"><span>MA</span><div><b>{ar?"أنت":"You"}<small>{ar?"اليوم، ١٠:٤٢ ص":"Today, 10:42 AM"}</small></b><p>{ar?"أحتاج إلى معرفة ما إذا كان الوصول المبكر ممكناً.":"I need to know whether arriving early is possible."}</p></div></article></div><label className="case-reply"><textarea placeholder={ar?"اكتب ردك...":"Write your reply..."}/><button onClick={()=>setDetail(false)}>{ar?"إرسال":"Send"}</button></label><small className="case-footnote">{ar?"تظهر في هذه الحالة فقط المعلومات اللازمة لحل طلب الحجز.":"Only information needed to resolve this booking request is visible in the case."}</small></section></div>}
  </main>
}
