"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Topic = "booking" | "payment" | "complaint" | "privacy" | "safety";
type SupportCase = { id:string; reference:string; category:string; subject:string; status:string; priority:string; version:number; updatedAt:string };
type Message = { id:string; caseId:string; authorKind:string; body:string; createdAt:string };
const topics:{id:Topic;icon:string;title:string;text:string}[] = [
  {id:"booking",icon:"◎",title:"Booking & appointments",text:"Changes, cancellations, arrival, or provider availability"},
  {id:"payment",icon:"Q",title:"Payments & refunds",text:"Recorded payment or refund status questions"},
  {id:"complaint",icon:"◇",title:"Service complaint",text:"Concerns about access, conduct, or experience"},
  {id:"privacy",icon:"♙",title:"Privacy request",text:"Access, correct, export, restrict, or delete eligible data"},
  {id:"safety",icon:"!",title:"Safety concern",text:"Report a non-emergency clinical or service safety issue"},
];

async function api(init?:RequestInit) {
  const response=await fetch("/api/support",init); const payload=await response.json().catch(()=>({})) as {data?:unknown;message?:string;error?:string};
  if(response.status===401){window.location.assign(`/signin-with-chatgpt?return_to=${encodeURIComponent("/support")}`);throw new Error("Authentication required");}
  if(!response.ok) throw new Error(payload.message||payload.error||"Support is temporarily unavailable"); return payload.data;
}
function label(value:string){return value.replaceAll("_"," ").replace(/^./,(letter)=>letter.toUpperCase());}

export default function Support(){
  const [cases,setCases]=useState<SupportCase[]>([]); const [messages,setMessages]=useState<Message[]>([]); const [loading,setLoading]=useState(true);
  const [topic,setTopic]=useState<Topic|null>(null); const [selected,setSelected]=useState<SupportCase|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const thread=useMemo(()=>messages.filter((message)=>message.caseId===selected?.id),[messages,selected]);
  async function load(){const data=await api() as {cases:SupportCase[];messages:Message[]};setCases(data.cases);setMessages(data.messages);if(selected)setSelected(data.cases.find((item)=>item.id===selected.id)||null);}
  useEffect(()=>{let active=true;const controller=new AbortController();api({signal:controller.signal}).then((value)=>{if(active){const data=value as {cases:SupportCase[];messages:Message[]};setCases(data.cases);setMessages(data.messages);}}).catch((caught)=>{if(active&&(!(caught instanceof DOMException)||caught.name!=="AbortError"))setError(caught instanceof Error?caught.message:"Support unavailable");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};},[]);
  async function retry(){setLoading(true);setError("");try{await load();}catch(caught){setError(caught instanceof Error?caught.message:"Support unavailable");}finally{setLoading(false);}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!topic)return;setSaving(true);setError("");const form=new FormData(event.currentTarget);try{const created=await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category:topic,description:form.get("description"),relatedReference:form.get("relatedReference"),privacyRequestType:form.get("privacyRequestType")})}) as SupportCase;setTopic(null);setNotice(`${created.reference} created and securely routed`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"Request could not be created");}finally{setSaving(false);}}
  async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setSaving(true);const form=new FormData(event.currentTarget);try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reply",caseId:selected.id,message:form.get("message")})});event.currentTarget.reset();setNotice("Reply added to your support request");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Reply could not be sent");}finally{setSaving(false);}}
  return <main className="support-shell" id="main-content">
    <header className="support-header"><a className="brand" href="/"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav><a href="/providers">Find care</a><a href="/appointments">Appointments</a><a href="/wallet">Health wallet</a><a className="active" href="/support">Support</a></nav><div><a href="/notifications">●</a><span>RY</span></div></header>
    <section className="support-hero"><div><p>THE RIGHT HELP, THROUGH THE RIGHT PATH</p><h1>How can we help?</h1><span>Create and track secure, account-owned support requests.</span></div></section>
    <section className="support-workspace"><div className="emergency-banner"><span>＋</span><div><b>Is someone in immediate danger?</b><p>Do not wait for an in-app response. In Qatar, call emergency services immediately on 999.</p></div><a href="tel:999">Call 999</a></div>
      {error&&<div className="family-live-alert error"><span>{error}</span><button type="button" onClick={()=>void retry()}>Try again</button></div>}{notice&&<div className="family-live-alert success"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
      <div className="support-grid"><section><div className="support-section-head"><div><h2>Choose what you need help with</h2><p>Each request is routed by category and recorded in your account.</p></div></div><div className="support-topics">{topics.map((item)=><button className={item.id==="safety"?"safety":""} key={item.id} onClick={()=>setTopic(item.id)}><span>{item.icon}</span><div><b>{item.title}</b><small>{item.text}</small></div><i>›</i></button>)}</div></section>
        <aside><section className="case-card"><div><h2>Your support requests</h2><span>{cases.filter((item)=>!["resolved","closed"].includes(item.status)).length}</span></div>{loading?<p>Loading your requests…</p>:error?<p>Support requests are unavailable. Try again before relying on this list.</p>:cases.length===0?<p>No support requests yet.</p>:cases.map((item)=><button key={item.id} onClick={()=>setSelected(item)}><i className={item.priority==="critical"?"case-gold":"case-blue"}>◎</i><div><p>{item.subject}</p><b>{item.reference}</b><small>{label(item.status)} · {new Date(item.updatedAt).toLocaleString()}</small></div><em>›</em></button>)}</section><section className="support-promise"><span>♙</span><h2>What you can expect</h2><ul><li>A durable reference for every request</li><li>Updates in your notification inbox</li><li>Access limited to authorized support roles</li><li>Separate privacy and safety routing</li></ul></section></aside></div>
    </section>
    {topic&&<div className="support-modal-layer" onMouseDown={(event)=>event.target===event.currentTarget&&setTopic(null)}><form className={`support-modal ${topic==="safety"?"safety-modal":""}`} onSubmit={create}><button type="button" className="drawer-close" onClick={()=>setTopic(null)}>×</button><p>NEW REQUEST</p><h2>{topics.find((item)=>item.id===topic)?.title}</h2>{topic==="safety"&&<div className="modal-emergency"><span>!</span><p><b>This channel is not for emergencies</b>If there is immediate danger or a life-threatening medical need, call 999 now.</p><a href="tel:999">999</a></div>}<label>What happened?<textarea name="description" required maxLength={4000}/><small>Avoid health information unless it is necessary for this request.</small></label>{topic==="privacy"&&<label>Request type<select name="privacyRequestType"><option>Access my data</option><option>Correct my data</option><option>Export my data</option><option>Restrict processing</option><option>Delete eligible data</option></select></label>}<label>Related reference (optional)<input name="relatedReference" maxLength={128}/></label><div className="routing-note"><span>♙</span><p><b>Need-to-know access</b>Only authorized staff assigned to the relevant support workflow can manage this request.</p></div><button type="submit" className="submit-support" disabled={saving}>{saving?"Creating…":"Create request"}</button></form></div>}
    {selected&&<div className="support-modal-layer" onMouseDown={(event)=>event.target===event.currentTarget&&setSelected(null)}><section className="case-detail"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p>{selected.subject}</p><h2>{selected.reference}</h2><div className="case-status"><span>●</span><div><b>{label(selected.status)}</b><small>{label(selected.category)} team</small></div></div><div className="case-thread">{thread.map((message)=><article className={message.authorKind==="requester"?"mine":""} key={message.id}><span>{message.authorKind==="requester"?"YOU":"RS"}</span><div><b>{message.authorKind==="requester"?"You":"Reyati Support"}<small>{new Date(message.createdAt).toLocaleString()}</small></b><p>{message.body}</p></div></article>)}</div>{!["resolved","closed"].includes(selected.status)&&<form className="case-reply" onSubmit={reply}><textarea name="message" required maxLength={4000} placeholder="Write your reply…"/><button type="submit" disabled={saving}>{saving?"Sending…":"Send"}</button></form>}<small className="case-footnote">Only information needed to resolve this request is available in this case.</small></section></div>}
  </main>;
}
