"use client";

import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./admin-patient-profiles.module.css";

type Distribution = { key: string; count: number };
type Governance = { role: string; visibility: string; metrics: { profiles: number; emergencyReferenceCount: number; communicationSupportNeedsCount: number }; distributions: { languages: Distribution[]; completionStates: Distribution[]; contactPreferences: Distribution[] }; rehearsals: Array<{ id: string; scenarioCount: number; passedScenarios: number; result: string; executedAt: string }> };
const labels: Record<string, { en: string; ar: string }> = { en: { en: "English", ar: "الإنجليزية" }, ar: { en: "Arabic", ar: "العربية" }, in_progress: { en: "In progress", ar: "قيد الإعداد" }, complete: { en: "Complete", ar: "مكتمل" }, masked: { en: "Masked", ar: "مخفي جزئياً" }, identity_email: { en: "Identity email", ar: "بريد الهوية" }, hidden: { en: "Hidden", ar: "مخفي" } };

export default function AdminPatientProfilesPage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Governance | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/admin/patient-profiles", { cache: "no-store" }), payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setData(payload.data); setError(""); } catch { setError(ar ? "تعذر تحميل حوكمة الملفات." : "Patient profile governance could not be loaded."); } finally { setLoading(false); } }, [ar]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function rehearse() { setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/patient-profiles", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "run_rehearsal" }) }), payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); await load(); setMessage(ar ? "نجحت 28 حالة اصطناعية دون آثار تشغيلية." : "All 28 synthetic scenarios passed with zero operational side effects."); } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? "تعذر تشغيل الاختبار." : "The rehearsal could not run.")); } finally { setBusy(false); } }
  return <main className={styles.shell} dir={ar ? "rtl" : "ltr"}>
    <header className={styles.top}><a href="/admin"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya" /></a><nav><a href="/admin">{ar ? "العمليات" : "Operations"}</a><a href="/admin/audit">{ar ? "التدقيق" : "Audit"}</a><button type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></nav></header>
    <section className={styles.hero}><div><span>{ar ? "حوكمة الملف الشخصي" : "PATIENT PROFILE GOVERNANCE"}</span><h1>{ar ? "ضمان الملف وبيانات الاتصال" : "Profile & contact assurance"}</h1><p>{ar ? "مؤشرات مجمعة فقط لجودة اكتمال الملف وخيارات العرض، دون أسماء أو عناوين اتصال أو ملاحظات." : "Aggregate-only assurance for profile completion and presentation choices—without names, contact addresses, references, or notes."}</p></div><aside><b>{data?.metrics.profiles ?? 0}</b><small>{ar ? "ملف شخصي" : "profile settings"}</small></aside></section>
    <div className={styles.content}><section className={styles.boundary}><div><b>{ar ? "لا كشف للهوية" : "No identity disclosure"}</b><p>{ar ? "لا يستطيع المسؤول عرض اسم أو بريد أو مرجع طوارئ أو احتياج تواصل لمريض، ولا تغيير الملف أو التحقق من جهة اتصال." : "Administrators cannot view patient names, email addresses, emergency references, or communication needs—and cannot change profiles or verify contacts."}</p></div><span>{data?.visibility.replaceAll("_", " ") ?? "aggregate only"}</span></section>
      {message && <p className={styles.success} role="status">{message}</p>}{error && <div className={styles.error} role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>{ar ? "إعادة المحاولة" : "Retry"}</button></div>}
      {loading ? <div className={styles.loading} role="status">{ar ? "جارٍ تحميل المقاييس المجمعة…" : "Loading aggregate metrics…"}</div> : data && <>
        <section className={styles.metrics}><Metric label={ar ? "إجمالي الملفات" : "Total profiles"} value={data.metrics.profiles} /><Metric label={ar ? "مراجع طوارئ" : "Emergency references"} value={data.metrics.emergencyReferenceCount} /><Metric label={ar ? "احتياجات تواصل" : "Communication needs"} value={data.metrics.communicationSupportNeedsCount} /></section>
        <section className={styles.panel}><div className={styles.panelHead}><div><span>{ar ? "توزيع بلا هوية" : "IDENTITY-FREE DISTRIBUTION"}</span><h2>{ar ? "حالة الملفات المجمعة" : "Aggregate profile posture"}</h2></div><p>{ar ? "أعداد فقط؛ لا صفوف على مستوى المستخدم ولا قيم أو نصوص اتصال." : "Counts only; no user-level rows, contact values, references, or note content."}</p></div><div className={styles.distributions}><DistributionBlock title={ar ? "اللغة" : "Language"} values={data.distributions.languages} ar={ar} /><DistributionBlock title={ar ? "الاكتمال" : "Completion"} values={data.distributions.completionStates} ar={ar} /><DistributionBlock title={ar ? "عرض الاتصال" : "Contact display"} values={data.distributions.contactPreferences} ar={ar} /></div></section>
        <section className={styles.panel}><div className={styles.panelHead}><div><span>{ar ? "تحقق اصطناعي" : "SYNTHETIC ASSURANCE"}</span><h2>{ar ? "اختبار بلا آثار جانبية" : "Zero-side-effect rehearsal"}</h2></div>{data.role !== "security_auditor" && <button className={styles.primary} type="button" disabled={busy} onClick={() => void rehearse()}>{busy ? (ar ? "جارٍ التشغيل…" : "Running…") : (ar ? "تشغيل 28 سيناريو" : "Run 28 scenarios")}</button>}</div><p className={styles.explain}>{ar ? "يتحقق من الملكية وتعارض الإصدارات والحدود والسجل المشفر ومنع تغيير الهوية والتحقق التلقائي والكشف والمزامنة والاستنتاج السريري. لا يغيّر أي ملف." : "Checks ownership, version conflicts, field limits, coded history, and prevention of identity mutation, automatic verification, disclosure, external sync, and clinical inference. No profile is changed."}</p><div className={styles.runs}>{data.rehearsals.length === 0 ? <div className={styles.empty}><b>{ar ? "لم تُشغّل اختبارات بعد" : "No rehearsals have run yet"}</b><p>{ar ? "يمكن لمسؤول المنصة تشغيل الاختبار الاصطناعي." : "A platform administrator can run the synthetic suite."}</p></div> : data.rehearsals.map((run) => <article key={run.id}><span>✓ {run.result}</span><b>{run.passedScenarios}/{run.scenarioCount}</b><time>{new Date(run.executedAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</time></article>)}</div></section>
      </>}
    </div>
  </main>;
}

function Metric({ label, value }: { label: string; value: number }) { return <article><span>{label}</span><b>{value}</b><small>aggregate</small></article>; }
function DistributionBlock({ title, values, ar }: { title: string; values: Distribution[]; ar: boolean }) { return <div><h3>{title}</h3>{values.length === 0 ? <p>{ar ? "لا توجد بيانات بعد" : "No data yet"}</p> : values.map((item) => <div className={styles.row} key={item.key}><span>{labels[item.key]?.[ar ? "ar" : "en"] ?? item.key}</span><b>{item.count}</b></div>)}</div>; }
