"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";

type AuditEvent = { id: string; action: string; resourceType: string; resourceId: string; outcome: string; createdAt: string; actorUserId: string | null; actorName: string | null; actorEmail: string | null; organizationId: string | null; organizationName: string | null; metadataAvailable: boolean };
type AuditData = { role: string; events: AuditEvent[]; nextCursor: string | null; metrics: { total: number; recent30Days: number }; organizations: { id: string; name: string }[] };

async function request(url: string) {
  const response = await fetch(url); const payload = await response.json().catch(() => ({})) as { data?: unknown; message?: string; error?: string };
  if (response.status === 401) { window.location.assign("/signin-with-chatgpt?return_to=/admin/audit"); throw new Error("Authentication required"); }
  if (!response.ok || payload.data === undefined) { const error = new Error(payload.message || payload.error || "Request failed"); (error as Error & { status?: number }).status = response.status; throw error; }
  return payload.data as AuditData;
}

function label(value: string, ar = false) { const labels: Record<string, string> = { platform_admin: "مدير المنصة", security_auditor: "مدقق أمني", verification_reviewer: "مراجع التحقق", support_agent: "وكيل الدعم", success: "نجاح", blocked: "محظور", failure: "فشل", high: "مرتفع", normal: "عادي", low: "منخفض" }; return ar ? labels[value] || value.replaceAll(".", " · ").replaceAll("_", " ") : value.replaceAll(".", " · ").replaceAll("_", " "); }
function risk(event: AuditEvent) { return event.outcome !== "success" ? "high" : /verification|bootstrap|suspend|revoke/.test(event.action) ? "normal" : "low"; }

export default function AuditWorkspace() {
  const [lang, setLang] = useReyatiLocale(); const ar = lang === "ar";
  const [data, setData] = useState<AuditData | null>(null); const [events, setEvents] = useState<AuditEvent[]>([]); const [selected, setSelected] = useState<AuditEvent | null>(null);
  const [query, setQuery] = useState(""); const [organizationId, setOrganizationId] = useState(""); const [outcome, setOutcome] = useState("");
  const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [forbidden, setForbidden] = useState(false); const [error, setError] = useState("");

  function url(cursor?: string | null) { const params = new URLSearchParams(); if (query.trim()) params.set("query", query.trim()); if (organizationId) params.set("organizationId", organizationId); if (outcome) params.set("outcome", outcome); if (cursor) params.set("cursor", cursor); return `/api/admin/audit?${params}`; }
  async function load() {
    setLoading(true); setError("");
    try { const next = await request(url()); setData(next); setEvents(next.events); setSelected(next.events[0] ?? null); setForbidden(false); }
    catch (caught) { if ((caught as Error & { status?: number }).status === 403) setForbidden(true); else setError(caught instanceof Error ? caught.message : "Audit log unavailable"); }
    finally { setLoading(false); }
  }
  useEffect(() => { let active = true; request("/api/admin/audit").then((next) => { if (active) { setData(next); setEvents(next.events); setSelected(next.events[0] ?? null); } }).catch((caught) => { if (!active) return; if ((caught as Error & { status?: number }).status === 403) setForbidden(true); else setError(caught instanceof Error ? caught.message : "Audit log unavailable"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function filter(event: FormEvent) { event.preventDefault(); await load(); }
  async function more() { if (!data?.nextCursor) return; setLoadingMore(true); try { const next = await request(url(data.nextCursor)); setEvents((current) => [...current, ...next.events]); setData((current) => current ? { ...next, metrics: current.metrics, organizations: current.organizations } : next); } catch (caught) { setError(caught instanceof Error ? caught.message : "More events could not be loaded"); } finally { setLoadingMore(false); } }
  const actions = useMemo(() => new Set(events.map((event) => event.action)).size, [events]);

  return <main className={`audit-shell ${ar ? "arabic" : ""}`} dir={ar ? "rtl" : "ltr"} id="main-content"><aside className="audit-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar ? "عمليات المنصة" : "Platform operations"}</span></a><div className="audit-role"><span>AU</span><div><b>{ar ? "مدقق أمني" : "Security auditor"}</b><small>{ar ? "للقراءة فقط · محدد بالدور" : "Read-only · role scoped"}</small></div></div><nav><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a href="/admin/organizations">{ar ? "المؤسسات" : "Organizations"}</a><a href="/admin/verification">{ar ? "التحقق" : "Verification"}</a><a className="active" href="/admin/audit">{ar ? "التدقيق" : "Audit"}</a></nav><div className="audit-side-note"><span>⌘</span><p><b>{ar ? "سجل غير قابل للتغيير" : "Immutable record"}</b>{ar ? "لا يمكن لمشاهدي التدقيق تعديل الأحداث التي يفحصونها أو حذفها." : "Audit viewers cannot alter or delete the events they inspect."}</p></div></aside><section className="audit-main"><header className="audit-top"><div><span>{ar ? "وضع القراءة فقط" : "READ-ONLY MODE"}</span><b>{data?.role ? label(data.role, ar) : (ar ? "جارٍ التحقق من الوصول" : "Checking access")}</b></div><div><button className="lang" type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button><a href="/notifications">●</a><span>AU</span></div></header><div className="audit-workspace"><div className="audit-heading"><div><p>{ar ? "الأمان والمساءلة" : "SECURITY & ACCOUNTABILITY"}</p><h1>{ar ? "سجل أحداث التدقيق" : "Audit event ledger"}</h1><span>{ar ? "تتبع إجراءات الهوية والمؤسسات والحجز والنشر والتحقق المسجلة على الخادم." : "Trace server-recorded identity, organization, booking, publishing, and verification actions."}</span></div><button onClick={() => void load()}>↻ {ar ? "تحديث السجل" : "Refresh ledger"}</button></div>
    {loading && <div className="audit-live-state"><span>◇</span><h2>{ar ? "جارٍ تحميل أحداث التدقيق المحمية…" : "Loading protected audit events…"}</h2></div>}{!loading && forbidden && <div className="audit-live-state restricted"><span>♙</span><h2>{ar ? "يلزم الوصول إلى التدقيق" : "Audit access is required"}</h2><p>{ar ? "يمكن فقط لمديري المنصة ومدققي المؤسسات النشطين قراءة هذا السجل. يقتصر مدققو المؤسسات على مؤسساتهم." : "Only platform administrators and active organization auditors can read this ledger. Organization auditors are restricted to their own organizations."}</p></div>}{!loading && !forbidden && error && <div className="audit-live-state error"><span>!</span><h2>{ar ? "سجل التدقيق غير متاح" : "Audit log unavailable"}</h2><p>{error}</p></div>}
    {!loading && !forbidden && data && <><div className="audit-banner"><span>✓</span><p><b>{ar ? "أحداث مباشرة مسجلة على الخادم" : "Live, server-recorded events"}</b>{ar ? "تبقى حمولات البيانات الوصفية محجوبة في هذه المساحة. يظهر الفاعل والمؤسسة والنتيجة والمورد والطابع الزمني للمراجعة المسؤولة." : "Metadata payloads remain masked in this workspace. Actor, organization, outcome, resource, and timestamp are shown for accountable review."}</p><i>{ar ? "محدد بالدور" : "ROLE SCOPED"}</i></div><section className="audit-metrics"><article><span>▤</span><div><b>{data.metrics.total.toLocaleString(ar ? "ar-QA" : "en-QA")}</b><p>{ar ? "إجمالي الأحداث المسجلة" : "Total recorded events"}</p></div></article><article><span>◷</span><div><b>{data.metrics.recent30Days.toLocaleString(ar ? "ar-QA" : "en-QA")}</b><p>{ar ? "أحداث خلال 30 يوماً" : "Events in 30 days"}</p></div></article><article><span>◇</span><div><b>{actions}</b><p>{ar ? "الإجراءات في هذه الصفحة" : "Actions on this page"}</p></div></article><article><span>♙</span><div><b>{label(data.role, ar)}</b><p>{ar ? "نطاق الوصول الحالي" : "Current access scope"}</p></div></article></section><form className="audit-live-filters" onSubmit={filter}><label>{ar ? "بحث" : "Search"}<input value={query} onChange={(event) => setQuery(event.target.value)} maxLength={120} placeholder={ar ? "الإجراء أو نوع المورد أو المعرّف" : "Action, resource type, or ID"}/></label><label>{ar ? "المؤسسة" : "Organization"}<select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}><option value="">{ar ? "كل المؤسسات المسموح بها" : "All permitted organizations"}</option>{data.organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></label><label>{ar ? "النتيجة" : "Outcome"}<select value={outcome} onChange={(event) => setOutcome(event.target.value)}><option value="">{ar ? "كل النتائج" : "All outcomes"}</option><option value="success">{ar ? "نجاح" : "Success"}</option><option value="blocked">{ar ? "محظور" : "Blocked"}</option><option value="failure">{ar ? "فشل" : "Failure"}</option></select></label><button type="submit">{ar ? "تطبيق عوامل التصفية" : "Apply filters"}</button></form>
    <section className="audit-layout"><div className="event-panel"><div className="event-table"><header><span>{ar ? "الوقت" : "Time"}</span><span>{ar ? "الفاعل" : "Actor"}</span><span>{ar ? "الإجراء" : "Action"}</span><span>{ar ? "المورد" : "Resource"}</span><span>{ar ? "النتيجة" : "Result"}</span><span>{ar ? "المخاطر" : "Risk"}</span><span/></header>{events.length === 0 ? <div className="audit-empty">{ar ? "لا توجد أحداث تدقيق تطابق عوامل التصفية." : "No audit events match these filters."}</div> : events.map((event) => <button key={event.id} className={selected?.id === event.id ? "selected" : ""} onClick={() => setSelected(event)}><time>{new Date(event.createdAt).toLocaleString(ar ? "ar-QA" : "en-QA", { dateStyle: "short", timeStyle: "short" })}</time><div><b>{event.actorName || (ar ? "النظام" : "System")}</b><small>{event.actorEmail || (ar ? "تحكم آلي" : "Automated control")}</small></div><span>{label(event.action, ar)}</span><code>{event.resourceType} · {event.resourceId.slice(0, 10)}</code><i className={event.outcome}>{label(event.outcome, ar)}</i><em className={risk(event)}>{label(risk(event), ar)}</em><span>›</span></button>)}</div>{data.nextCursor && <button className="audit-more" disabled={loadingMore} onClick={() => void more()}>{loadingMore ? (ar ? "جارٍ التحميل…" : "Loading…") : (ar ? "تحميل 50 حدثاً إضافياً" : "Load 50 more events")}</button>}</div>{selected && <aside className="event-detail"><div className="event-detail-head"><div><p>{selected.id}</p><h2>{label(selected.action, ar)}</h2><span>{new Date(selected.createdAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</span></div><i className={risk(selected)}>{label(risk(selected), ar)}</i></div><section className="actor-card"><span>{(selected.actorName || "SY").slice(0,2).toUpperCase()}</span><div><b>{selected.actorName || (ar ? "النظام" : "System")}</b><p>{selected.actorEmail || (ar ? "تحكم آلي" : "Automated control")}</p><small>{selected.organizationName || (ar ? "حدث على مستوى المنصة" : "Platform-wide event")}</small></div></section><section className="event-facts"><h3>{ar ? "سياق الحدث" : "Event context"}</h3><dl><div><dt>{ar ? "النتيجة" : "Outcome"}</dt><dd>{label(selected.outcome, ar)}</dd></div><div><dt>{ar ? "نوع المورد" : "Resource type"}</dt><dd>{selected.resourceType}</dd></div><div><dt>{ar ? "معرّف المورد" : "Resource ID"}</dt><dd>{selected.resourceId}</dd></div><div><dt>{ar ? "المؤسسة" : "Organization"}</dt><dd>{selected.organizationName || (ar ? "المنصة" : "Platform")}</dd></div><div><dt>{ar ? "البيانات الوصفية" : "Metadata"}</dt><dd>{selected.metadataAvailable ? (ar ? "محمية" : "Protected") : (ar ? "غير مسجلة" : "None recorded")}</dd></div></dl></section><div className="hash-proof"><span>⌘</span><p><b>{ar ? "معرّف حدث غير قابل للتغيير" : "Immutable event identifier"}</b><code>{selected.id}</code></p><i>✓ {ar ? "مسجل" : "Recorded"}</i></div></aside>}</section></>}
  </div></section></main>;
}
