"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type AuditEvent = { id: string; action: string; resourceType: string; resourceId: string; outcome: string; createdAt: string; actorUserId: string | null; actorName: string | null; actorEmail: string | null; organizationId: string | null; organizationName: string | null; metadataAvailable: boolean };
type AuditData = { role: string; events: AuditEvent[]; nextCursor: string | null; metrics: { total: number; recent30Days: number }; organizations: { id: string; name: string }[] };

async function request(url: string) {
  const response = await fetch(url); const payload = await response.json() as { data?: unknown; message?: string; error?: string };
  if (response.status === 401) { window.location.assign("/signin-with-chatgpt?return_to=/admin/audit"); throw new Error("Authentication required"); }
  if (!response.ok) { const error = new Error(payload.message || payload.error || "Request failed"); (error as Error & { status?: number }).status = response.status; throw error; }
  return payload.data as AuditData;
}

function label(value: string) { return value.replaceAll(".", " · ").replaceAll("_", " "); }
function risk(event: AuditEvent) { return event.outcome !== "success" ? "high" : /verification|bootstrap|suspend|revoke/.test(event.action) ? "normal" : "low"; }

export default function AuditWorkspace() {
  const [data, setData] = useState<AuditData | null>(null); const [events, setEvents] = useState<AuditEvent[]>([]); const [selected, setSelected] = useState<AuditEvent | null>(null);
  const [query, setQuery] = useState(""); const [organizationId, setOrganizationId] = useState(""); const [outcome, setOutcome] = useState("");
  const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [forbidden, setForbidden] = useState(false); const [error, setError] = useState("");

  function url(cursor?: string | null) { const params = new URLSearchParams(); if (query.trim()) params.set("query", query.trim()); if (organizationId) params.set("organizationId", organizationId); if (outcome) params.set("outcome", outcome); if (cursor) params.set("cursor", cursor); return `/api/admin/audit?${params}`; }
  async function load() {
    setLoading(true); setError("");
    try { const next = await request(url()); setData(next); setEvents(next.events); setSelected(next.events[0] ?? null); setForbidden(false); }
    catch (caught) { if ((caught as Error & { status?: number }).status === 403) setForbidden(true); else setError(caught instanceof Error ? caught.message : "Audit log unavailable"); }
    finally { setLoading(false); }
  }
  useEffect(() => { let active = true; request("/api/admin/audit").then((next) => { if (active) { setData(next); setEvents(next.events); setSelected(next.events[0] ?? null); } }).catch((caught) => { if (!active) return; if ((caught as Error & { status?: number }).status === 403) setForbidden(true); else setError(caught instanceof Error ? caught.message : "Audit log unavailable"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function filter(event: FormEvent) { event.preventDefault(); await load(); }
  async function more() { if (!data?.nextCursor) return; setLoadingMore(true); try { const next = await request(url(data.nextCursor)); setEvents((current) => [...current, ...next.events]); setData((current) => current ? { ...next, metrics: current.metrics, organizations: current.organizations } : next); } catch (caught) { setError(caught instanceof Error ? caught.message : "More events could not be loaded"); } finally { setLoadingMore(false); } }
  const actions = useMemo(() => new Set(events.map((event) => event.action)).size, [events]);

  return <main className="audit-shell" id="main-content"><aside className="audit-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>Platform operations</span></a><div className="audit-role"><span>AU</span><div><b>Security auditor</b><small>Read-only · role scoped</small></div></div><nav><a href="/admin">Overview</a><a href="/admin/organizations">Organizations</a><a href="/admin/verification">Verification</a><a className="active" href="/admin/audit">Audit</a></nav><div className="audit-side-note"><span>⌘</span><p><b>Immutable record</b>Audit viewers cannot alter or delete the events they inspect.</p></div></aside><section className="audit-main"><header className="audit-top"><div><span>READ-ONLY MODE</span><b>{data?.role ? label(data.role) : "Checking access"}</b></div><div><a href="/notifications">●</a><span>AU</span></div></header><div className="audit-workspace"><div className="audit-heading"><div><p>SECURITY &amp; ACCOUNTABILITY</p><h1>Audit event ledger</h1><span>Trace server-recorded identity, organization, booking, publishing, and verification actions.</span></div><button onClick={() => void load()}>↻ Refresh ledger</button></div>
    {loading && <div className="audit-live-state"><span>◇</span><h2>Loading protected audit events…</h2></div>}{!loading && forbidden && <div className="audit-live-state restricted"><span>♙</span><h2>Audit access is required</h2><p>Only platform administrators and active organization auditors can read this ledger. Organization auditors are restricted to their own organizations.</p></div>}{!loading && !forbidden && error && <div className="audit-live-state error"><span>!</span><h2>Audit log unavailable</h2><p>{error}</p></div>}
    {!loading && !forbidden && data && <><div className="audit-banner"><span>✓</span><p><b>Live, server-recorded events</b>Metadata payloads remain masked in this workspace. Actor, organization, outcome, resource, and timestamp are shown for accountable review.</p><i>ROLE SCOPED</i></div><section className="audit-metrics"><article><span>▤</span><div><b>{data.metrics.total.toLocaleString()}</b><p>Total recorded events</p></div></article><article><span>◷</span><div><b>{data.metrics.recent30Days.toLocaleString()}</b><p>Events in 30 days</p></div></article><article><span>◇</span><div><b>{actions}</b><p>Actions on this page</p></div></article><article><span>♙</span><div><b>{label(data.role)}</b><p>Current access scope</p></div></article></section><form className="audit-live-filters" onSubmit={filter}><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} maxLength={120} placeholder="Action, resource type, or ID"/></label><label>Organization<select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}><option value="">All permitted organizations</option>{data.organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></label><label>Outcome<select value={outcome} onChange={(event) => setOutcome(event.target.value)}><option value="">All outcomes</option><option value="success">Success</option><option value="blocked">Blocked</option><option value="failure">Failure</option></select></label><button type="submit">Apply filters</button></form>
    <section className="audit-layout"><div className="event-panel"><div className="event-table"><header><span>Time</span><span>Actor</span><span>Action</span><span>Resource</span><span>Result</span><span>Risk</span><span/></header>{events.length === 0 ? <div className="audit-empty">No audit events match these filters.</div> : events.map((event) => <button key={event.id} className={selected?.id === event.id ? "selected" : ""} onClick={() => setSelected(event)}><time>{new Date(event.createdAt).toLocaleString([], { dateStyle: "short", timeStyle: "short" })}</time><div><b>{event.actorName || "System"}</b><small>{event.actorEmail || "Automated control"}</small></div><span>{label(event.action)}</span><code>{event.resourceType} · {event.resourceId.slice(0, 10)}</code><i className={event.outcome}>{event.outcome}</i><em className={risk(event)}>{risk(event)}</em><span>›</span></button>)}</div>{data.nextCursor && <button className="audit-more" disabled={loadingMore} onClick={() => void more()}>{loadingMore ? "Loading…" : "Load 50 more events"}</button>}</div>{selected && <aside className="event-detail"><div className="event-detail-head"><div><p>{selected.id}</p><h2>{label(selected.action)}</h2><span>{new Date(selected.createdAt).toLocaleString()}</span></div><i className={risk(selected)}>{risk(selected)}</i></div><section className="actor-card"><span>{(selected.actorName || "SY").slice(0,2).toUpperCase()}</span><div><b>{selected.actorName || "System"}</b><p>{selected.actorEmail || "Automated control"}</p><small>{selected.organizationName || "Platform-wide event"}</small></div></section><section className="event-facts"><h3>Event context</h3><dl><div><dt>Outcome</dt><dd>{selected.outcome}</dd></div><div><dt>Resource type</dt><dd>{selected.resourceType}</dd></div><div><dt>Resource ID</dt><dd>{selected.resourceId}</dd></div><div><dt>Organization</dt><dd>{selected.organizationName || "Platform"}</dd></div><div><dt>Metadata</dt><dd>{selected.metadataAvailable ? "Protected" : "None recorded"}</dd></div></dl></section><div className="hash-proof"><span>⌘</span><p><b>Immutable event identifier</b><code>{selected.id}</code></p><i>✓ Recorded</i></div></aside>}</section></>}
  </div></section></main>;
}
