"use client";

import { useMemo, useState } from "react";

type Tab="events"|"alerts"|"access"|"exports";
type Event={id:string,time:string,actor:string,role:string,action:string,target:string,result:string,risk:"High"|"Normal"|"Low",ip:string};
const events:Event[]=[
  {id:"AUD-9201",time:"10:42:18",actor:"OPS-••18",role:"Privacy operator",action:"Sensitive support view opened",target:"Case PRV-092",result:"Allowed",risk:"High",ip:"185.••.42.18"},
  {id:"AUD-9198",time:"10:31:05",actor:"VER-••04",role:"Verification reviewer",action:"Verification state changed",target:"VER-1842",result:"Recorded",risk:"Normal",ip:"185.••.42.22"},
  {id:"AUD-9192",time:"10:08:44",actor:"FIN-••11",role:"Finance approver",action:"Refund approved",target:"RFD-8814",result:"Allowed",risk:"Normal",ip:"185.••.41.16"},
  {id:"AUD-9187",time:"09:52:11",actor:"PRV-••31",role:"Provider owner",action:"Team permission changed",target:"Member SA",result:"Allowed",risk:"Normal",ip:"37.••.118.9"},
  {id:"AUD-9181",time:"09:36:02",actor:"OPS-••07",role:"Operations operator",action:"Repeated reveal requests",target:"3 support cases",result:"Blocked",risk:"High",ip:"185.••.63.44"},
  {id:"AUD-9174",time:"09:14:29",actor:"SYS",role:"Automated control",action:"Expired session revoked",target:"Session ••8821",result:"Enforced",risk:"Low",ip:"Internal"},
];

export default function AuditWorkspace(){
  const [lang,setLang]=useState<"en"|"ar">("en");const [tab,setTab]=useState<Tab>("events");const [filter,setFilter]=useState("All");const [query,setQuery]=useState("");const [selected,setSelected]=useState<Event|null>(events[0]);const [notice,setNotice]=useState("");const ar=lang==="ar";const rows=useMemo(()=>events.filter(e=>(filter==="All"||e.risk===filter||e.result===filter)&&`${e.id} ${e.actor} ${e.action} ${e.target}`.toLowerCase().includes(query.toLowerCase())),[filter,query]);const flash=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),2500)};
  return <main className={`audit-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <aside className="audit-sidebar"><a href="/" className="provider-logo"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar?"عمليات المنصة":"Platform operations"}</span></a><div className="audit-role"><span>AU</span><div><b>{ar?"مراجع الأمن":"Security auditor"}</b><small>{ar?"قراءة فقط · مصادقة متعددة":"Read-only · MFA verified"}</small></div></div><nav><a href="/admin"><span>◫</span>{ar?"نظرة عامة":"Overview"}</a><a href="/admin/verification"><span>✓</span>{ar?"التحقق":"Verification"}</a><a href="/admin/finance"><span>Q</span>{ar?"المالية":"Finance"}</a><a href="/admin/cases"><span>◇</span>{ar?"الحالات":"Cases"}</a><a href="/admin/moderation"><span>◉</span>{ar?"الإشراف":"Moderation"}</a><a className="active" href="/admin/audit"><span>▤</span>{ar?"التدقيق":"Audit"}<i>3</i></a></nav><div className="audit-side-note"><span>⌘</span><p><b>{ar?"سجل غير قابل للتعديل":"Immutable record"}</b>{ar?"لا يستطيع المراجع تعديل أو حذف الأحداث التي يراجعها.":"Auditors cannot alter or delete the events they inspect."}</p></div><div className="audit-links"><a href="/journeys">◇ {ar?"جميع المسارات":"All journeys"}</a><a href="/admin">← {ar?"لوحة العمليات":"Operations dashboard"}</a></div></aside>
    <section className="audit-main"><header className="audit-top"><div><span>{ar?"وضع القراءة فقط":"READ-ONLY MODE"}</span><b>{ar?"سلامة السجل موثقة":"Log integrity verified"}</b></div><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a href="/notifications">●</a><span>AU</span></div></header><div className="audit-workspace">
      <div className="audit-heading"><div><p>{ar?"الأمن والمساءلة":"SECURITY & ACCOUNTABILITY"}</p><h1>{ar?"التدقيق ومراقبة الوصول":"Audit & access monitoring"}</h1><span>{ar?"تتبع الوصول المميز واكتشف الشذوذ وأثبت تطبيق الضوابط.":"Trace privileged access, detect anomalies, and prove controls are operating."}</span></div><button onClick={()=>setTab("exports")}>⇩ {ar?"إنشاء حزمة أدلة":"Create evidence package"}</button></div>
      <div className="audit-banner"><span>✓</span><p><b>{ar?"سلسلة السجل سليمة":"Audit chain is intact"}</b>{ar?"تم التحقق من 12,842 حدثاً ضمن فترة الاحتفاظ الحالية دون فجوات أو تعديلات.":"12,842 events in the current retention window verified with no gaps or alterations."}</p><i>SHA-256 · {ar?"موثق":"VERIFIED"}</i></div>
      <section className="audit-metrics">{[["12,842",ar?"أحداث خلال 30 يوماً":"Events in 30 days","▤"],["3",ar?"تنبيهات نشطة":"Active alerts","!"],["100%",ar?"جلسات مميزة بمصادقة متعددة":"Privileged MFA","✓"],["0",ar?"فجوات في السجل":"Log gaps","◇"]].map(x=><article key={x[1]}><span>{x[2]}</span><div><b>{x[0]}</b><p>{x[1]}</p></div></article>)}</section>
      <div className="audit-tabs">{(["events","alerts","access","exports"] as Tab[]).map(x=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{x==="events"?(ar?"سجل الأحداث":"Event log"):x==="alerts"?(ar?"التنبيهات":"Security alerts"):x==="access"?(ar?"وضع الوصول":"Access posture"):(ar?"حزم الأدلة":"Evidence packages")}</button>)}</div>
      {tab==="events"&&<section className="audit-layout"><div className="event-panel"><div className="event-tools"><div>{["All","High","Normal","Blocked"].map(x=><button className={filter===x?"active":""} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?"البحث في الأحداث":"Search events"}/></label></div><div className="event-table"><header><span>{ar?"الوقت":"Time"}</span><span>{ar?"الفاعل":"Actor"}</span><span>{ar?"الإجراء":"Action"}</span><span>{ar?"الهدف":"Target"}</span><span>{ar?"النتيجة":"Result"}</span><span>{ar?"المخاطر":"Risk"}</span><span/></header>{rows.map(e=><button key={e.id} className={selected?.id===e.id?"selected":""} onClick={()=>setSelected(e)}><time>{e.time}</time><div><b>{e.actor}</b><small>{e.role}</small></div><span>{e.action}</span><code>{e.target}</code><i className={e.result.toLowerCase()}>{e.result}</i><em className={e.risk.toLowerCase()}>{e.risk}</em><span>›</span></button>)}</div></div>{selected&&<aside className="event-detail"><div className="event-detail-head"><div><p>{selected.id}</p><h2>{selected.action}</h2><span>{selected.time} · 2 Aug 2026</span></div><i className={selected.risk.toLowerCase()}>{selected.risk}</i></div><section className="actor-card"><span>{selected.actor.slice(0,2)}</span><div><b>{selected.actor}</b><p>{selected.role}</p><small>{selected.ip} · Doha, Qatar</small></div><i>✓ MFA</i></section><section className="event-facts"><h3>{ar?"سياق الحدث":"Event context"}</h3><dl><div><dt>{ar?"النتيجة":"Result"}</dt><dd>{selected.result}</dd></div><div><dt>{ar?"المورد":"Resource"}</dt><dd>{selected.target}</dd></div><div><dt>{ar?"معرف الجلسة":"Session ID"}</dt><dd>SES-••4821</dd></div><div><dt>{ar?"سبب الوصول":"Access purpose"}</dt><dd>Case resolution</dd></div><div><dt>{ar?"مدة الوصول":"Access duration"}</dt><dd>7m 42s</dd></div></dl></section><section className="event-chain"><h3>{ar?"سياق الجلسة":"Session timeline"}</h3>{[["10:39:02","Step-up authentication passed"],["10:41:55","Case purpose confirmed"],[selected.time,selected.action],["10:49:44","Sensitive access ended"]].map((x,i)=><article key={x[0]}><span className={i===2?"focus":"done"}>{i===2?"●":"✓"}</span><p><b>{x[1]}</b><small>{x[0]}</small></p></article>)}</section><div className="hash-proof"><span>⌘</span><p><b>{ar?"إثبات سلامة الحدث":"Event integrity proof"}</b><code>8f31…a90c · SHA-256</code></p><i>✓ {ar?"صالح":"Valid"}</i></div><div className="event-actions"><button onClick={()=>flash(ar?"تم إعداد إثبات الحدث":"Event proof prepared")}>⇩ {ar?"تصدير الإثبات":"Export proof"}</button><button onClick={()=>{setTab("alerts");flash(ar?"تم إنشاء تنبيه تجريبي":"Prototype alert created")}}>! {ar?"إنشاء تنبيه":"Create alert"}</button></div></aside>}</section>}
      {tab==="alerts"&&<section className="alerts-layout"><article className="alerts-panel"><div className="section-head"><div><h2>{ar?"تنبيهات الأمن النشطة":"Active security alerts"}</h2><p>{ar?"إشارات سلوكية تتطلب مراجعة بشرية.":"Behavioral signals requiring human review."}</p></div><span>3 {ar?"نشطة":"ACTIVE"}</span></div>{[["ALT-031","Repeated sensitive reveal requests","OPS-••07 · 3 cases in 14 minutes","High","Investigating"],["ALT-029","New device for finance approver","FIN-••11 · Doha · MFA passed","Normal","Monitoring"],["ALT-026","After-hours export request","OPS-••22 · Evidence package","Normal","Needs review"]].map((x,i)=><div className="alert-row" key={x[0]}><span className={i===0?"high":"normal"}>{i===0?"!":"●"}</span><div><code>{x[0]}</code><b>{x[1]}</b><small>{x[2]}</small></div><i>{x[3]}</i><em>{x[4]}</em><button onClick={()=>flash(ar?"تم فتح تحقيق تجريبي":"Prototype investigation opened")}>{ar?"تحقيق":"Investigate"}</button></div>)}</article><aside className="alert-rules"><h2>{ar?"ضوابط الكشف":"Detection controls"}</h2>{[["Sensitive views","3 in 15 min","Enabled"],["New privileged device","Any","Enabled"],["After-hours exports","20:00–06:00","Enabled"],["Failed MFA","2 attempts","Enabled"]].map(x=><div key={x[0]}><p><b>{x[0]}</b><small>{x[1]}</small></p><i>✓ {x[2]}</i></div>)}<button onClick={()=>flash(ar?"تم فتح إعدادات الضوابط":"Control settings opened")}>{ar?"إدارة الضوابط":"Manage controls"}</button></aside></section>}
      {tab==="access"&&<section className="access-layout"><article><div className="section-head"><div><h2>{ar?"وضع الوصول المميز":"Privileged access posture"}</h2><p>{ar?"الصلاحيات الحرجة والجلسات النشطة ومواعيد المراجعة.":"Critical roles, active sessions, and review dates."}</p></div><span>✓ {ar?"سليم":"HEALTHY"}</span></div><div className="access-table"><header><span>{ar?"الدور":"Role"}</span><span>{ar?"المستخدمون":"Users"}</span><span>{ar?"مصادقة متعددة":"MFA"}</span><span>{ar?"آخر مراجعة":"Last review"}</span><span>{ar?"القادم":"Next review"}</span><span/></header>{[["Platform administrator","2","100%","12 Jul","10 Oct"],["Finance approver","3","100%","18 Jul","16 Oct"],["Privacy operator","4","100%","22 Jul","20 Oct"],["Security auditor","2","100%","31 Jul","29 Oct"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><i>✓ {x[2]}</i><span>{x[3]}</span><strong>{x[4]}</strong><button onClick={()=>flash(ar?"تم فتح تفاصيل الدور":"Role details opened")}>›</button></div>)}</div></article><aside><h2>{ar?"الجلسات المميزة النشطة":"Active privileged sessions"}</h2>{[["OPS-••18","Privacy operator","7m"],["FIN-••11","Finance approver","12m"],["VER-••04","Verification reviewer","24m"]].map(x=><div className="session-row" key={x[0]}><span>●</span><p><b>{x[0]}</b><small>{x[1]} · {x[2]}</small></p><button onClick={()=>flash(ar?"تم إرسال طلب إنهاء تجريبي":"Prototype termination requested")}>{ar?"إنهاء":"End"}</button></div>)}<footer><span>✓</span><p>{ar?"كل الجلسات ضمن سياسات المدة والجهاز.":"All sessions comply with duration and device policies."}</p></footer></aside></section>}
      {tab==="exports"&&<section className="exports-layout"><article><div className="section-head"><div><h2>{ar?"إنشاء حزمة أدلة":"Create evidence package"}</h2><p>{ar?"تصدير محدود وموقع لفترة وغرض محددين.":"Scoped, signed export for a defined period and purpose."}</p></div></div><div className="export-form"><label>{ar?"الغرض":"Purpose"}<select><option>Internal control review</option><option>Regulatory request</option><option>Incident investigation</option></select></label><div><label>{ar?"من":"From"}<input type="date" defaultValue="2026-07-01"/></label><label>{ar?"إلى":"To"}<input type="date" defaultValue="2026-08-02"/></label></div><label>{ar?"نطاق الأحداث":"Event scope"}<select><option>Privileged access only</option><option>Financial actions</option><option>Verification decisions</option><option>All audit events</option></select></label><div className="export-warning"><span>▣</span><p><b>{ar?"التصدير نفسه يسجل":"Export is itself audited"}</b>{ar?"سيتم تسجيل الغرض والنطاق والفاعل وبصمة الملف.":"Purpose, scope, actor, and file fingerprint will be recorded."}</p></div><button onClick={()=>flash(ar?"تم إنشاء حزمة أدلة تجريبية موقعة":"Signed prototype evidence package created")}>⌘ {ar?"إنشاء حزمة موقعة":"Create signed package"}</button></div></article><aside><h2>{ar?"الحزم الأخيرة":"Recent packages"}</h2>{[["EXP-0812","Internal control review","2 Aug · 09:10","Ready"],["EXP-0804","Finance evidence","1 Aug · 16:42","Downloaded"],["EXP-0798","Privacy case PRV-092","31 Jul · 11:08","Expired"]].map(x=><div className="package-row" key={x[0]}><span>▤</span><p><code>{x[0]}</code><b>{x[1]}</b><small>{x[2]}</small></p><i className={x[3].toLowerCase()}>{x[3]}</i></div>)}<footer><span>ⓘ</span><p>{ar?"تنتهي روابط التنزيل بعد 24 ساعة.":"Download links expire after 24 hours."}</p></footer></aside></section>}
      <footer className="audit-footer"><span>ⓘ</span><p>{ar?"كل الأحداث والتنبيهات اصطناعية لأغراض تخطيط المنتج فقط.":"All events and alerts are synthetic for product planning only."}</p><a href="/support">{ar?"سياسة التدقيق":"Audit policy"}</a></footer>
    </div></section>{notice&&<div className="audit-toast"><span>✓</span>{notice}</div>}
  </main>
}
