"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./catalogue.module.css";

type Category = "specialties" | "services" | "appointment_types" | "document_types" | "languages" | "facility_attributes";
type Item = { id: string; category: Category; code: string; labelEn: string; labelAr: string; descriptionEn: string; descriptionAr: string; sortOrder: number; status: string; version: number; authoredByUserId: string; reviewedByUserId: string | null; reviewReasonCode: string | null; dependencyCount: number; makerCheckerSatisfied: boolean };
type Rehearsal = { id: string; result: string; scenarioCount: number; executedAt: string };
type Data = { role: string; visibility: string; categories: Category[]; metrics: Record<string, number>; items: Item[]; rehearsals: Rehearsal[]; boundaries: Record<string, boolean> };
const categoryCopy: Record<Category, { en: string; ar: string }> = {
  specialties: { en: "Specialties", ar: "التخصصات" }, services: { en: "Services", ar: "الخدمات" },
  appointment_types: { en: "Appointment types", ar: "أنواع المواعيد" }, document_types: { en: "Document types", ar: "أنواع المستندات" },
  languages: { en: "Languages", ar: "اللغات" }, facility_attributes: { en: "Facility attributes", ar: "خصائص المنشآت" },
};
const emptyDraft = { category: "specialties" as Category, code: "", labelEn: "", labelAr: "", descriptionEn: "", descriptionAr: "", sortOrder: "100", dependencyItemIds: [] as string[] };

export default function CatalogueGovernancePage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<Data | null>(null), [draft, setDraft] = useState(emptyDraft), [reasonCodes, setReasonCodes] = useState<Record<string, string>>({});
  const [filter, setFilter] = useState<"all" | Category>("all"), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { setError(""); try { const response = await fetch("/api/admin/catalogue", { cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setData(payload.data); } catch (cause) { setError(cause instanceof Error ? cause.message : (ar ? "تعذر تحميل سجل الكتالوج." : "The catalogue register could not be loaded.")); } }, [ar]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function act(body: Record<string, unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/catalogue", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setMessage(success); setReasonCodes({}); await load(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : (ar ? "تعذر إكمال الإجراء." : "The action could not be completed.")); return false; } finally { setBusy(false); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const saved = await act({ action: "create_draft", ...draft, sortOrder: Number(draft.sortOrder) }, ar ? "تم حفظ المسودة الخاصة." : "Private draft saved."); if (saved) setDraft(emptyDraft); }
  const activeDependencies = data?.items.filter((item) => item.status === "active") ?? [];
  const visibleItems = useMemo(() => (data?.items ?? []).filter((item) => filter === "all" || item.category === filter), [data, filter]);
  const isAuditor = data?.role === "security_auditor";
  const statusLabel = (status: string) => ({ draft: ar ? "مسودة" : "Draft", pending_review: ar ? "قيد المراجعة" : "Pending review", approved: ar ? "معتمد" : "Approved", returned: ar ? "مُعاد" : "Returned", active: ar ? "نشط" : "Active", retired: ar ? "متقاعد" : "Retired" }[status] ?? status);
  const categoryLabel = (category: Category) => categoryCopy[category][ar ? "ar" : "en"];

  return <main className={styles.shell} dir={ar ? "rtl" : "ltr"}>
    <aside className={styles.sidebar}><a className={styles.brand} href="/admin"><img src="/brand/reyati-logo-white.svg" alt="Reyati" /></a><p>{ar ? "عمليات المنصة" : "Platform operations"}</p><nav aria-label={ar ? "التنقل الإداري" : "Administration navigation"}><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a className={styles.active} href="/admin/catalogue" aria-current="page">{ar ? "حوكمة الكتالوج" : "Catalogue governance"}</a><a href="/admin/audit">{ar ? "سجل التدقيق" : "Audit ledger"}</a></nav><div className={styles.sideNote}>{ar ? "تغييرات يدوية فقط، مع فصل الأدوار وسجل رمزي." : "Manual changes only, with separated duties and coded history."}</div></aside>
    <div className={styles.workspace}>
      <header className={styles.topbar}><div><span className={styles.eyebrow}>{ar ? "مصدر مرجعي محكوم" : "Governed source of truth"}</span><h1>{ar ? "كتالوج المنصة" : "Platform catalogue"}</h1><p>{ar ? "إدارة المصطلحات التشغيلية ثنائية اللغة دون ادعاءات ترميز سريري أو نشر تلقائي." : "Manage bilingual operational terminology without clinical-coding claims or automatic publishing."}</p></div><button className={styles.locale} type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></header>
      <section className={styles.boundary} aria-label={ar ? "حدود الحوكمة" : "Governance boundaries"}><span aria-hidden="true">i</span><div><b>{ar ? "لا توجد آثار جانبية خفية" : "No hidden downstream effects"}</b><p>{ar ? "لا توليد تلقائي للتصنيف، ولا مزامنة لمصطلحات خارجية، ولا نشر تلقائي، ولا تغييرات جماعية مدمرة." : "No automatic taxonomy generation, external terminology sync, automatic publishing, or bulk destructive changes."}</p></div></section>
      {message && <div className={styles.success} role="status">{message}</div>}
      {error && <div className={styles.error} role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>{ar ? "إعادة المحاولة" : "Try again"}</button></div>}
      {!data && !error ? <section className={styles.loading} aria-live="polite"><span></span>{ar ? "جارٍ تحميل السجل المحكوم…" : "Loading the governed register…"}</section> : data && <>
        <section className={styles.metrics} aria-label={ar ? "مقاييس مجمعة" : "Aggregate metrics"}>{Object.entries(data.metrics).map(([key, value]) => <article key={key}><b>{value}</b><span>{key.replaceAll(/([A-Z])/g, " $1")}</span></article>)}</section>
        {!isAuditor && <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "مساحة المُعدّ" : "Maker workspace"}</span><h2>{ar ? "إنشاء سجل ثنائي اللغة" : "Create a bilingual record"}</h2></div><span className={styles.role}>platform_admin</span></div><form className={styles.form} onSubmit={create}>
          <label>{ar ? "الفئة" : "Category"}<select value={draft.category} onChange={(event) => setDraft((current) => ({ ...current, category: event.target.value as Category }))}>{data.categories.map((category) => <option value={category} key={category}>{categoryLabel(category)}</option>)}</select></label>
          <label>{ar ? "الرمز الآلي" : "Machine code"}<input required pattern="[a-z][a-z0-9_]+" maxLength={64} placeholder="family_medicine" value={draft.code} onChange={(event) => setDraft((current) => ({ ...current, code: event.target.value }))} /></label>
          <label>{ar ? "ترتيب العرض" : "Display order"}<input required type="number" min="0" max="10000" value={draft.sortOrder} onChange={(event) => setDraft((current) => ({ ...current, sortOrder: event.target.value }))} /></label>
          <label>English label<input required minLength={2} maxLength={160} value={draft.labelEn} onChange={(event) => setDraft((current) => ({ ...current, labelEn: event.target.value }))} /></label>
          <label>التسمية العربية<input required dir="rtl" lang="ar" minLength={2} maxLength={160} value={draft.labelAr} onChange={(event) => setDraft((current) => ({ ...current, labelAr: event.target.value }))} /></label>
          <label className={styles.wide}>English description<textarea required minLength={8} maxLength={800} value={draft.descriptionEn} onChange={(event) => setDraft((current) => ({ ...current, descriptionEn: event.target.value }))} /></label>
          <label className={styles.wide}>الوصف العربي<textarea required dir="rtl" lang="ar" minLength={8} maxLength={800} value={draft.descriptionAr} onChange={(event) => setDraft((current) => ({ ...current, descriptionAr: event.target.value }))} /></label>
          <fieldset className={styles.dependencies}><legend>{ar ? "اعتماديات نشطة اختيارية" : "Optional active dependencies"}</legend>{!activeDependencies.length ? <p>{ar ? "لا توجد عناصر نشطة متاحة." : "No active items are available."}</p> : activeDependencies.map((item) => <label key={item.id}><input type="checkbox" checked={draft.dependencyItemIds.includes(item.id)} onChange={(event) => setDraft((current) => ({ ...current, dependencyItemIds: event.target.checked ? [...current.dependencyItemIds, item.id] : current.dependencyItemIds.filter((id) => id !== item.id) }))} />{ar ? item.labelAr : item.labelEn} <small>{item.category} · {item.code}</small></label>)}</fieldset>
          <div className={styles.formActions}><button className={styles.primary} disabled={busy} type="submit">{ar ? "حفظ كمسودة خاصة" : "Save private draft"}</button></div>
        </form></section>}
        <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "دورة حياة واضحة" : "Explicit lifecycle"}</span><h2>{ar ? "سجل الكتالوج" : "Catalogue register"}</h2></div><select aria-label={ar ? "تصفية حسب الفئة" : "Filter by category"} value={filter} onChange={(event) => setFilter(event.target.value as "all" | Category)}><option value="all">{ar ? "كل الفئات" : "All categories"}</option>{data.categories.map((category) => <option value={category} key={category}>{categoryLabel(category)}</option>)}</select></div>
          {!visibleItems.length ? <div className={styles.empty}><b>{ar ? "لا توجد سجلات في هذا العرض" : "No records in this view"}</b><p>{ar ? "أنشئ مسودة أو اختر فئة أخرى." : "Create a draft or choose another category."}</p></div> : <div className={styles.register}>{visibleItems.map((item) => { const reason = reasonCodes[item.id] ?? ""; return <article className={styles.card} key={item.id}><header><div><span className={styles.eyebrow}>{categoryLabel(item.category)}</span><h3>{ar ? item.labelAr : item.labelEn}</h3><code>{item.code}</code></div><span className={`${styles.status} ${styles[item.status] ?? ""}`}>{statusLabel(item.status)}</span></header><div className={styles.bilingual}><div><b>{item.labelEn}</b><p>{item.descriptionEn}</p></div><div dir="rtl"><b>{item.labelAr}</b><p>{item.descriptionAr}</p></div></div><div className={styles.meta}><span>v{item.version}</span><span>{ar ? "الاعتماديات" : "Dependencies"}: {item.dependencyCount}</span><span>{ar ? "فصل الأدوار" : "Maker-checker"}: {item.makerCheckerSatisfied ? "✓" : "—"}</span></div>
            {["pending_review", "active"].includes(item.status) && <label className={styles.reason}>{ar ? "رمز سبب الإرجاع أو التقاعد" : "Return or retirement reason code"}<input maxLength={64} placeholder="scope_update" value={reason} onChange={(event) => setReasonCodes((current) => ({ ...current, [item.id]: event.target.value }))} /></label>}
            <div className={styles.actions}>{!isAuditor && ["draft", "returned"].includes(item.status) && <button className={styles.primary} disabled={busy} type="button" onClick={() => void act({ action: "submit_review", itemId: item.id, version: item.version }, ar ? "أُرسل السجل للمراجعة." : "Record submitted for review.")}>{ar ? "إرسال للمراجعة" : "Submit for review"}</button>}{item.status === "pending_review" && <><button className={styles.primary} disabled={busy} type="button" onClick={() => void act({ action: "review", decision: "approve", reasonCode: "review_complete", itemId: item.id, version: item.version }, ar ? "اعتمد المراجع المستقل السجل." : "Independent checker approved the record.")}>{ar ? "اعتماد كمراجع" : "Approve as checker"}</button><button className={styles.secondary} disabled={busy || !reason} type="button" onClick={() => void act({ action: "review", decision: "return", reasonCode: reason, itemId: item.id, version: item.version }, ar ? "أُعيد السجل للمُعدّ." : "Record returned to maker.")}>{ar ? "إعادة للمُعدّ" : "Return to maker"}</button></>}{!isAuditor && item.status === "approved" && <button className={styles.primary} disabled={busy} type="button" onClick={() => void act({ action: "activate", itemId: item.id, version: item.version }, ar ? "فُعّل السجل دون نشر تلقائي." : "Record activated without automatic publishing.")}>{ar ? "تفعيل يدوي" : "Activate manually"}</button>}{!isAuditor && item.status === "active" && <button className={styles.danger} disabled={busy || !reason} type="button" onClick={() => void act({ action: "retire", reasonCode: reason, itemId: item.id, version: item.version }, ar ? "تقاعد السجل بعد فحص الاعتماديات." : "Record retired after dependency checks.")}>{ar ? "تقاعد آمن" : "Retire safely"}</button>}</div>
          </article>; })}</div>}
        </section>
        <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "ضمان اصطناعي" : "Synthetic assurance"}</span><h2>{ar ? "اختبار بلا آثار تشغيلية" : "Zero-side-effect rehearsal"}</h2><p>{ar ? "عشرون سيناريو للتحقق من الحدود وفصل الأدوار والتبعية والإصدارات دون تغيير الكتالوج." : "Twenty scenarios verify boundaries, separation, dependencies, and versions without changing catalogue records."}</p></div><button className={styles.primary} disabled={busy} type="button" onClick={() => void act({ action: "run_rehearsal" }, ar ? "اكتمل الاختبار." : "Rehearsal completed.")}>{ar ? "تشغيل 20 سيناريو" : "Run 20 scenarios"}</button></div><div className={styles.rehearsals}>{!data.rehearsals.length ? <span>{ar ? "لم تُشغّل اختبارات بعد." : "No rehearsal has run yet."}</span> : data.rehearsals.map((item) => <span key={item.id}><b>{item.result}</b>{item.scenarioCount} · {new Date(item.executedAt).toLocaleString()}</span>)}</div></section>
      </>}
    </div>
  </main>;
}
