"use client";

import { useMemo, useState } from "react";

type Provider={id:number,name:string,nameAr:string,initials:string,specialty:string,specialtyAr:string,facility:string,facilityAr:string,area:string,fee:number,rating:number,reviews:number,gender:"Female"|"Male",languages:string[],next:string,slots:string[],color:string,years:number,about:string,aboutAr:string};
const providers:Provider[]=[
  {id:1,name:"Dr. Laila Al-Kuwari",nameAr:"د. ليلى الكواري",initials:"LK",specialty:"Family Medicine",specialtyAr:"طب الأسرة",facility:"Al Noor Medical Center",facilityAr:"مركز النور الطبي",area:"Al Waab",fee:250,rating:4.9,reviews:128,gender:"Female",languages:["Arabic","English"],next:"Today, 4:30 PM",slots:["4:30 PM","5:15 PM","6:00 PM"],color:"coral",years:12,about:"Family physician focused on preventive care, women’s health, and long-term relationships with families.",aboutAr:"طبيبة أسرة تركز على الرعاية الوقائية وصحة المرأة وبناء علاقات طويلة الأمد مع العائلات."},
  {id:2,name:"Dr. Omar Rahman",nameAr:"د. عمر رحمن",initials:"OR",specialty:"Internal Medicine",specialtyAr:"الطب الباطني",facility:"West Bay Clinic",facilityAr:"عيادة الخليج الغربي",area:"West Bay",fee:300,rating:4.8,reviews:94,gender:"Male",languages:["Arabic","English","Urdu"],next:"Tomorrow, 9:00 AM",slots:["9:00 AM","10:30 AM","1:00 PM"],color:"blue",years:15,about:"Consultant in adult medicine with a special interest in diabetes, blood pressure, and coordinated chronic care.",aboutAr:"استشاري في طب البالغين مع اهتمام خاص بالسكري وضغط الدم وتنسيق الرعاية المزمنة."},
  {id:3,name:"Dr. Sara El-Masri",nameAr:"د. سارة المصري",initials:"SE",specialty:"Dermatology",specialtyAr:"الأمراض الجلدية",facility:"Pearl Health Clinic",facilityAr:"عيادة اللؤلؤة الصحية",area:"The Pearl",fee:350,rating:4.9,reviews:211,gender:"Female",languages:["Arabic","English","French"],next:"Wed, 11:30 AM",slots:["11:30 AM","1:45 PM","3:00 PM"],color:"mint",years:10,about:"Medical dermatologist providing evidence-based care for skin, hair, and nail conditions across all ages.",aboutAr:"طبيبة جلدية تقدم رعاية مبنية على الأدلة لحالات الجلد والشعر والأظافر لجميع الأعمار."},
  {id:4,name:"Dr. Faisal Noor",nameAr:"د. فيصل نور",initials:"FN",specialty:"Cardiology",specialtyAr:"أمراض القلب",facility:"Lusail Medical Centre",facilityAr:"مركز لوسيل الطبي",area:"Lusail",fee:500,rating:4.7,reviews:76,gender:"Male",languages:["Arabic","English"],next:"Thu, 2:00 PM",slots:["2:00 PM","3:30 PM","5:00 PM"],color:"gold",years:18,about:"Consultant cardiologist supporting prevention, diagnosis, and ongoing management with shared decisions.",aboutAr:"استشاري قلب يدعم الوقاية والتشخيص والإدارة المستمرة من خلال القرارات المشتركة."},
  {id:5,name:"Dr. Hana Al-Sulaiti",nameAr:"د. هناء السليطي",initials:"HS",specialty:"Pediatrics",specialtyAr:"طب الأطفال",facility:"Al Rayyan Family Clinic",facilityAr:"عيادة الريان العائلية",area:"Al Rayyan",fee:280,rating:4.9,reviews:163,gender:"Female",languages:["Arabic","English"],next:"Today, 7:00 PM",slots:["7:00 PM","7:30 PM","8:15 PM"],color:"violet",years:11,about:"Pediatrician offering family-centred care from newborn checks through adolescent health.",aboutAr:"طبيبة أطفال تقدم رعاية تركز على الأسرة من فحوصات حديثي الولادة حتى صحة المراهقين."},
];

export default function ProviderDiscovery(){
  const [lang,setLang]=useState<"en"|"ar">("en");const [query,setQuery]=useState("");const [specialty,setSpecialty]=useState("All");const [gender,setGender]=useState("Any");const [available,setAvailable]=useState(false);const [sort,setSort]=useState("Recommended");const [selected,setSelected]=useState<Provider|null>(null);const [compare,setCompare]=useState<number[]>([]);const [slot,setSlot]=useState("");const [confirmed,setConfirmed]=useState(false);const ar=lang==="ar";
  const filtered=useMemo(()=>providers.filter(p=>(specialty==="All"||p.specialty===specialty)&&(gender==="Any"||p.gender===gender)&&(`${p.name} ${p.nameAr} ${p.specialty} ${p.specialtyAr} ${p.facility} ${p.area}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==="Price"?a.fee-b.fee:sort==="Rating"?b.rating-a.rating:a.id-b.id),[query,specialty,gender,sort]);
  const toggleCompare=(id:number)=>setCompare(v=>v.includes(id)?v.filter(x=>x!==id):v.length<2?[...v,id]:v);
  const open=(p:Provider)=>{setSelected(p);setSlot("");setConfirmed(false)};
  return <main className={`providers-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <header className="providers-header"><a className="brand" href="/"><img src="/brand/reyati-logo.svg" alt="Reyati"/></a><nav><a className="active" href="/providers">{ar?"ابحث عن رعاية":"Find care"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a><a href="/wallet">{ar?"المحفظة الصحية":"Health wallet"}</a></nav><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a href="/notifications">●</a><span>MA</span></div></header>
    <section className="provider-search-hero"><div><p>{ar?"بحث موثوق وشفاف":"TRUSTED, TRANSPARENT DISCOVERY"}</p><h1>{ar?"اعثر على الرعاية المناسبة لك":"Find care that fits you"}</h1><span>{ar?"قارن مقدمي الرعاية الموثّقين والأسعار والتوفر الفعلي بثقة.":"Compare verified providers, transparent prices, and real availability with confidence."}</span><label><i>⌕</i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?"الطبيب أو التخصص أو المنشأة":"Doctor, specialty, or facility"}/><b>⌖ {ar?"الدوحة":"Doha"}</b><button>{ar?"بحث":"Search"}</button></label></div></section>
    <section className="providers-workspace"><div className="filter-row"><select value={specialty} onChange={e=>setSpecialty(e.target.value)} aria-label="Specialty"><option value="All">{ar?"كل التخصصات":"All specialties"}</option>{[...new Set(providers.map(p=>p.specialty))].map(s=><option key={s}>{s}</option>)}</select><select value={gender} onChange={e=>setGender(e.target.value)} aria-label="Gender"><option value="Any">{ar?"أي جنس":"Any gender"}</option><option value="Female">{ar?"طبيبة":"Female"}</option><option value="Male">{ar?"طبيب":"Male"}</option></select><button className={available?"selected":""} onClick={()=>setAvailable(!available)}>◷ {ar?"متاح قريباً":"Available soon"}</button><button>⌖ {ar?"المنطقة":"Area"}</button><button>Q {ar?"نطاق السعر":"Price range"}</button><button className="clear" onClick={()=>{setSpecialty("All");setGender("Any");setAvailable(false)}}>{ar?"مسح الفلاتر":"Clear filters"}</button></div><div className="results-head"><div><h2>{filtered.length} {ar?"مقدمي رعاية موثّقين":"verified providers"}</h2><p>{ar?"يتم التحقق من الترخيص والانتماء قبل النشر.":"Licence and affiliation are checked before publication."}</p></div><label>{ar?"ترتيب":"Sort"}<select value={sort} onChange={e=>setSort(e.target.value)}><option>Recommended</option><option>Rating</option><option>Price</option></select></label></div>
      <div className="provider-results"><section className="provider-list">{filtered.map(p=><article className="provider-result" key={p.id}><div className={`provider-photo ${p.color}`}>{p.initials}<span>✓</span></div><div className="provider-info"><p>✓ {ar?"مقدم رعاية موثّق":"Verified provider"}</p><button className="provider-name" onClick={()=>open(p)}>{ar?p.nameAr:p.name}</button><h3>{ar?p.specialtyAr:p.specialty}</h3><span>⌖ {ar?p.facilityAr:p.facility} · {p.area}</span><div className="provider-tags"><i>★ {p.rating} <small>({p.reviews})</small></i>{p.languages.map(l=><i key={l}>{l}</i>)}<i>♿ {ar?"مدخل مهيأ":"Accessible"}</i></div><button className={compare.includes(p.id)?"compare active":"compare"} onClick={()=>toggleCompare(p.id)}>□ {compare.includes(p.id)?(ar?"تمت الإضافة":"Added"):(ar?"مقارنة":"Compare")}</button></div><aside><div><small>{ar?"أقرب موعد":"Next available"}</small><b>{p.next}</b></div><div><strong>{p.fee} {ar?"ر.ق":"QAR"}</strong><small>{ar?"شامل الرسوم":"incl. fees"}</small></div><button onClick={()=>open(p)}>{ar?"عرض الملف والمواعيد":"View profile & times"}</button></aside></article>)}</section><aside className="trust-panel"><span>♙</span><h2>{ar?"كيف نبني الثقة":"How Reyati builds trust"}</h2><p>{ar?"نفصل الحقائق الموثّقة عن معلومات مقدم الرعاية وتقييمات المرضى.":"We separate verified facts from provider-supplied information and patient reviews."}</p><ul><li><b>{ar?"ترخيص موثّق":"Verified licence"}</b><small>{ar?"تم فحصه من المصدر":"Checked against source"}</small></li><li><b>{ar?"سعر واضح":"Clear price"}</b><small>{ar?"قبل تأكيد الموعد":"Before booking confirmation"}</small></li><li><b>{ar?"توفر فعلي":"Real availability"}</b><small>{ar?"محدّث من جدول المنشأة":"Synced from facility schedule"}</small></li><li><b>{ar?"تقييمات موثوقة":"Trusted reviews"}</b><small>{ar?"بعد زيارة مكتملة فقط":"Only after completed visits"}</small></li></ul><a href="#">{ar?"تعرف على معايير التحقق":"About verification standards"} →</a></aside></div>
    </section>
    {compare.length>0&&<div className="compare-bar"><div><span>⇄</span><p><b>{compare.length}/2 {ar?"للمقارنة":"selected to compare"}</b><small>{ar?"اختر مقدمَي رعاية لعرضهما جنباً إلى جنب":"Choose two providers for a side-by-side view"}</small></p></div><div className="compare-people">{compare.map(id=>{const p=providers.find(x=>x.id===id)!;return <button key={id} onClick={()=>toggleCompare(id)}><i className={p.color}>{p.initials}</i><b>{ar?p.nameAr:p.name}</b><span>×</span></button>})}</div><button disabled={compare.length<2} onClick={()=>{const p=providers.find(x=>x.id===compare[0]);if(p)open(p)}}>{ar?"مقارنة الآن":"Compare now"}</button></div>}
    {selected&&<div className="profile-layer" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="provider-profile"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button>{confirmed?<div className="profile-confirmed"><span>✓</span><p>{ar?"تم الحجز":"BOOKING CONFIRMED"}</p><h2>{ar?"موعدك جاهز":"Your appointment is set"}</h2><b>{slot} · {ar?selected.nameAr:selected.name}</b><small>{ar?"أرسلنا تفاصيل تجريبية إلى مركز الإشعارات.":"A prototype confirmation was added to your Notification Centre."}</small><a href="/appointments">{ar?"عرض مواعيدي":"View my appointments"}</a></div>:<><div className="profile-head"><div className={`provider-photo large ${selected.color}`}>{selected.initials}<span>✓</span></div><div><p>✓ {ar?"مقدم رعاية موثّق":"Verified provider"}</p><h2>{ar?selected.nameAr:selected.name}</h2><span>{ar?selected.specialtyAr:selected.specialty}</span><small>★ {selected.rating} ({selected.reviews} {ar?"تقييماً":"reviews"})</small></div></div><div className="verification-strip"><span>♙</span><p><b>{ar?"تم التحقق من الترخيص والانتماء":"Licence and affiliation verified"}</b>{ar?"آخر تحقق: ٢٤ يوليو ٢٠٢٦":"Last checked 24 July 2026"}</p><button>{ar?"عرض التفاصيل":"Details"}</button></div><section className="profile-about"><h3>{ar?"عن مقدم الرعاية":"About"}</h3><p>{ar?selected.aboutAr:selected.about}</p><div><article><b>{selected.years}+</b><small>{ar?"سنوات خبرة":"Years experience"}</small></article><article><b>{selected.languages.join(" · ")}</b><small>{ar?"اللغات":"Languages"}</small></article><article><b>♿</b><small>{ar?"منشأة مهيأة":"Accessible facility"}</small></article></div></section><section className="profile-location"><h3>{ar?"الموقع والسعر":"Location & price"}</h3><div><span>⌖</span><p><b>{ar?selected.facilityAr:selected.facility}</b><small>{selected.area}, Doha · {ar?"زيارة في العيادة":"In-person visit"}</small></p><strong>{selected.fee} {ar?"ر.ق":"QAR"}<small>{ar?"السعر الإجمالي":"total price"}</small></strong></div></section><section className="profile-slots"><div><h3>{ar?"اختر موعداً":"Choose a time"}</h3><span>{ar?"الأقرب · اليوم":"Earliest · Today"}</span></div><div>{selected.slots.map(s=><button className={slot===s?"active":""} key={s} onClick={()=>setSlot(s)}>{s}</button>)}</div></section><div className="profile-book"><div><small>{ar?"الإجمالي":"Total"}</small><b>{selected.fee} {ar?"ر.ق":"QAR"}</b></div><button disabled={!slot} onClick={()=>setConfirmed(true)}>{slot?(ar?"تأكيد الموعد":"Confirm appointment"):(ar?"اختر وقتاً للمتابعة":"Select a time to continue")}</button></div></>}</aside></div>}
  </main>
}
