"use client";

import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "@/app/account/security/account-security.module.css";

type Governance={visibility:"aggregate_only";metrics:Record<string,number>;eventAggregates:Array<{eventType:string;outcome:string;count:number}>;privacy:Record<string,boolean>;rehearsals:Array<{id:string;result:string;scenarioCount:number;executedAt:string}>};
const labels:Record<string,{en:string;ar:string}>={activeSessions:{en:"Active local sessions",ar:"الجلسات المحلية النشطة"},revokedSessions:{en:"Revoked local sessions",ar:"الجلسات المحلية الملغاة"},expiredSessions:{en:"Expired session records",ar:"سجلات الجلسات المنتهية"},recordedSecurityEvents:{en:"Recorded security events",ar:"أحداث الأمان المسجلة"}};
export default function AccountSecurityGovernancePage(){
  const[lang,setLang]=useReyatiLocale(),ar=lang==="ar",[data,setData]=useState<Governance|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const response=await fetch("/api/admin/account-security",{cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error);setData(payload.data);setError("")}catch{setError(ar?"تعذر تحميل حوكمة أمان الحساب.":"Account-security governance could not be loaded.")}},[ar]);
  useEffect(()=>{queueMicrotask(()=>void load())},[load]);
  async function rehearse(){setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/admin/account-security",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"run_rehearsal"})});if(!response.ok)throw new Error("failed");setMessage(ar?"نجحت 20 حالة اصطناعية من دون تغيير جلسات أو الاتصال بموفر الهوية.":"All 20 synthetic scenarios passed without changing sessions or calling an identity provider.");await load()}catch{setError(ar?"تعذر تشغيل الاختبار الآمن.":"The safe boundary rehearsal could not be completed.")}finally{setBusy(false)}}
  return <main className={styles.shell} dir={ar?"rtl":"ltr"}><header className={styles.top}><a href="/admin"><img src="/brand/qivaya-logo-primary.png" alt="Qivaya"/></a><nav><a href="/admin">{ar?"العمليات":"Operations"}</a><a href="/admin/audit">{ar?"التدقيق":"Audit"}</a><button type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></nav></header>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{ar?"حوكمة مجمعة تحافظ على الخصوصية":"Privacy-preserving aggregate governance"}</span><h1>{ar?"حوكمة أمان الحساب":"Account security governance"}</h1><p>{ar?"راقب صحة سجلات الجلسات وحدود الأمان باستخدام أرقام مجمعة فقط، من دون هوية المستخدم أو معرف الجهاز أو الرمز أو عنوان IP.":"Monitor local session-record health and safety boundaries using aggregate counts only, without user identity, device identifiers, tokens, or IP addresses."}</p></div></section>
    <div className={styles.content}><section className={styles.boundary}><span className={styles.shield}>✓</span><div><strong>{ar?"لا يوجد مسار إلى الجلسات الفردية":"No path to individual sessions"}</strong><p>{ar?"هذه الصفحة لا تعرض المستخدم أو الجهاز أو المتصفح الخام أو الموقع أو أي رمز مصادقة.":"This surface never exposes a user, device identifier, raw browser data, location, or authentication token."}</p></div><span className={styles.private}>{ar?"مقاييس فقط":"METRICS ONLY"}</span></section>
      {message&&<p className={styles.status} role="status">{message}</p>}{error&&<p className={`${styles.status} ${styles.error}`} role="alert">{error} <button className={styles.secondary} type="button" onClick={()=>void load()}>{ar?"إعادة المحاولة":"Retry"}</button></p>}
      <section className={styles.panel}><div className={styles.adminHead}><div><h2>{ar?"مقاييس الحوكمة":"Governance metrics"}</h2><p className={styles.muted}>{ar?"أعداد مجمعة لا تكشف هوية أو تفاصيل جهاز.":"Aggregate counts that reveal neither identity nor device details."}</p></div><span className={styles.aggregate}>{data?.visibility==="aggregate_only"?(ar?"مجمعة فقط":"AGGREGATE ONLY"):"—"}</span></div><div className={styles.metricGrid}>{Object.entries(data?.metrics??{}).map(([key,value])=><article className={styles.metric} key={key}><b>{value}</b><span>{labels[key]?.[ar?"ar":"en"]??key}</span></article>)}</div></section>
      <section className={styles.panel}><div className={styles.adminHead}><div><h2>{ar?"أحداث مجمعة حسب النوع":"Events aggregated by type"}</h2><p className={styles.muted}>{ar?"لا توجد أسماء مستخدمين أو معرفات جلسات في النتائج.":"No user names or session identifiers are included."}</p></div></div>{!data?.eventAggregates.length?<div className={styles.empty}>{ar?"لا توجد أحداث مجمعة بعد.":"No aggregate events yet."}</div>:<div className={styles.events}>{data.eventAggregates.map(item=><div className={styles.event} key={`${item.eventType}-${item.outcome}`}><span className={styles.dot}/><div><b>{item.eventType.replaceAll("_"," ")}</b><small>{item.outcome}</small></div><strong>{item.count}</strong></div>)}</div>}</section>
      <section className={styles.panel}><div className={styles.adminHead}><div><h2>{ar?"اختبار حدود بلا آثار جانبية":"Zero-side-effect boundary rehearsal"}</h2><p className={styles.muted}>{ar?"يتحقق من الملكية والإصدارات وحماية الجلسة الحالية ومنع الرموز والموقع الدقيق والتقييم الخارجي والإغلاق التلقائي والتحكم بموفر الهوية.":"Validates ownership, versioning, current-session protection, and the absence of tokens, precise location, external scoring, automatic lockout, and identity-provider control."}</p></div><button className={styles.primary} type="button" disabled={busy} onClick={()=>void rehearse()}>{busy?(ar?"جارٍ التشغيل…":"Running…"):(ar?"تشغيل 20 حالة":"Run 20 scenarios")}</button></div><div className={styles.rehearsals}>{data?.rehearsals.map(item=><article key={item.id}><strong>{item.result}</strong><span>{item.scenarioCount} {ar?"حالة":"scenarios"}</span><small>{new Date(item.executedAt).toLocaleString(ar?"ar-QA":"en-QA")}</small></article>)}</div></section>
    </div></main>
}
