import { AuthorizationDeniedError } from "@/lib/authorization";
import { AuthenticationRequiredError, getOrCreateCurrentUser } from "@/lib/identity";
import { reportOperationalError } from "@/lib/observability";
import { RecoveryConflictError, RecoveryValidationError, createRecoveryRehearsal, getRecoveryCentre, updateRecoveryRehearsal } from "@/lib/recovery-rehearsals";
import { enforceWriteRateLimit, rateLimitResponse } from "@/lib/rate-limits";

export const dynamic = "force-dynamic"; const noStore = { "Cache-Control": "private, no-store" };
export async function GET() { return handle(async (userId) => getRecoveryCentre(userId)); }
export async function POST(request: Request) { return handle(async (userId) => { let body: Record<string, unknown>; try { body = await request.json() as Record<string, unknown>; } catch { throw new RecoveryValidationError("A valid JSON body is required"); } return body.operation === "create" ? createRecoveryRehearsal(userId, body) : updateRecoveryRehearsal(userId, body); }, "admin.recovery"); }
async function handle(operation: (userId: string) => Promise<unknown>, scope?: string) { try { const user = await getOrCreateCurrentUser(); if (user.status !== "active") throw new AuthorizationDeniedError(); if (scope) await enforceWriteRateLimit(user.id, scope, { limit: 35 }); return Response.json({ data: await operation(user.id) }, { headers: noStore }); } catch (error) { const limited = rateLimitResponse(error, noStore); if (limited) return limited; if (error instanceof AuthenticationRequiredError) return Response.json({ error: "authentication_required" }, { status: 401, headers: noStore }); if (error instanceof AuthorizationDeniedError) return Response.json({ error: "forbidden" }, { status: 403, headers: noStore }); if (error instanceof RecoveryValidationError) return Response.json({ error: "invalid_request", message: error.message }, { status: 400, headers: noStore }); if (error instanceof RecoveryConflictError) return Response.json({ error: "conflict", message: error.message }, { status: 409, headers: noStore }); reportOperationalError("admin.recovery.failed", error); return Response.json({ error: "service_unavailable" }, { status: 503, headers: { ...noStore, "Retry-After": "30" } }); } }
