"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "./health-library.module.css";

type Source={label:string;publisher:string;url:string;accessedOn:string};
type Article={id:string;slug:string;category:string;versionNumber:number;titleEn:string;titleAr:string;summaryEn:string;summaryAr:string;bodyEn:string;bodyAr:string;authorName:string;authorCredentials:string;medicalReviewerName:string|null;medicalReviewerCredentials:string|null;publishedAt:string;evidenceReviewedThrough:string;nextReviewDueAt:string;correctionNoticeEn:string|null;correctionNoticeAr:string|null;sources:Source[]};
type Library={articles:Article[];categories:string[];disclaimer:string};

export default function HealthLibraryPage(){
  const[lang,setLang]=useReyatiLocale(),ar=lang==="ar";
  const[data,setData]=useState<Library|null>(null),[search,setSearch]=useState(""),[category,setCategory]=useState(""),[open,setOpen]=useState<string|null>(null),[error,setError]=useState("");
  const load=useCallback(async(signal?:AbortSignal)=>{try{const params=new URLSearchParams();if(search.trim())params.set("search",search.trim());if(category)params.set("category",category);const response=await fetch(`/api/health-library?${params}`,{cache:"no-store",signal});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error();setData(payload.data);setError("")}catch(reason){if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(ar?"تعذر تحميل مكتبة الصحة الآن.":"The health library could not be loaded right now.")}},[ar,category,search]);
  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),search?250:0);return()=>{clearTimeout(timer);controller.abort()}},[load,search]);
  const date=(value:string)=>new Intl.DateTimeFormat(ar?"ar-QA":"en-QA",{dateStyle:"medium"}).format(new Date(value));
  const count=useMemo(()=>data?.articles.length??0,[data]);
  return <main className={styles.shell} dir={ar?"rtl":"ltr"}>
    <header className={styles.top}><a className={styles.logo} href="/"><img src="/brand/reyati-logo-primary.svg" alt="Reyati"/></a><nav aria-label={ar?"التنقل الرئيسي":"Main navigation"}><a href="/providers">{ar?"ابحث عن رعاية":"Find care"}</a><a href="/appointments">{ar?"المواعيد":"Appointments"}</a><button type="button" onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button></nav></header>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{ar?"معلومات موثوقة. قرارات أوضح.":"Trusted information. Clearer choices."}</span><h1>{ar?"مكتبة ريّاتي الصحية":"Reyati health library"}</h1><p>{ar?"مقالات تثقيفية ثنائية اللغة يكتبها مختصون، ويراجعها طبياً مختص مستقل، وتُنشر بموافقة منفصلة.":"Bilingual educational articles written by qualified authors, medically reviewed by an independent professional, and published with separate approval."}</p><div className={styles.trust}><span>✓ {ar?"مراجعة طبية":"Medically reviewed"}</span><span>✓ {ar?"مصادر موثوقة":"Trusted sources"}</span><span>✓ {ar?"سجل إصدارات وتصحيحات":"Versioned and corrected"}</span></div></div><aside><b>{ar?"مهم":"Important"}</b><p>{ar?"هذه معلومات عامة وليست تشخيصاً أو نصيحة شخصية. اتصل بـ 999 في حالات الطوارئ المهددة للحياة في قطر.":"This is general information—not a diagnosis or personal advice. Call 999 for a life-threatening emergency in Qatar."}</p></aside></section>
    <section className={styles.content}>
      <div className={styles.tools}><label><span>{ar?"ابحث في المكتبة":"Search the library"}</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={ar?"موضوع أو كلمة رئيسية":"Topic or keyword"}/></label><label><span>{ar?"الموضوع":"Topic"}</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">{ar?"كل المواضيع":"All topics"}</option>{data?.categories.map(item=><option key={item}>{item}</option>)}</select></label><div className={styles.resultCount}><b>{count}</b><span>{ar?"مقالة موثوقة":"trusted articles"}</span></div></div>
      {error&&<p className={styles.error} role="alert">{error}</p>}
      {!data&&!error?<div className={styles.loading}>{ar?"جارٍ تحميل المقالات المراجعة…":"Loading reviewed articles…"}</div>:data&&data.articles.length===0?<div className={styles.empty}><b>{ar?"لا توجد مقالات مطابقة":"No matching articles"}</b><p>{ar?"جرّب كلمة أخرى أو اعرض كل المواضيع.":"Try another keyword or view all topics."}</p></div>:<div className={styles.library}>{data?.articles.map(article=>{const expanded=open===article.id;return <article className={styles.article} key={article.id}><header><div><span className={styles.category}>{article.category}</span><h2>{ar?article.titleAr:article.titleEn}</h2><p>{ar?article.summaryAr:article.summaryEn}</p></div><button type="button" aria-expanded={expanded} onClick={()=>setOpen(expanded?null:article.id)}>{expanded?(ar?"إغلاق":"Close"):(ar?"قراءة المقالة":"Read article")}</button></header><div className={styles.reviewStrip}><span><b>{ar?"الكاتب":"Author"}</b>{article.authorName}, {article.authorCredentials}</span><span><b>{ar?"المراجع الطبي":"Medical reviewer"}</b>{article.medicalReviewerName}, {article.medicalReviewerCredentials}</span><span><b>{ar?"نُشر":"Published"}</b>{date(article.publishedAt)} · v{article.versionNumber}</span></div>{expanded&&<div className={styles.expanded}>{(ar?article.correctionNoticeAr:article.correctionNoticeEn)&&<div className={styles.correction}><b>{ar?"إشعار تصحيح":"Correction notice"}</b><p>{ar?article.correctionNoticeAr:article.correctionNoticeEn}</p></div>}<div className={styles.body}>{(ar?article.bodyAr:article.bodyEn).split(/\n+/).filter(Boolean).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><section className={styles.sources}><h3>{ar?"المصادر الموثوقة":"Trusted sources"}</h3><ol>{article.sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label}</a><span>{source.publisher} · {ar?"تم الاطلاع":"Accessed"} {source.accessedOn}</span></li>)}</ol></section><footer><span>{ar?"تمت مراجعة الأدلة حتى":"Evidence reviewed through"} {article.evidenceReviewedThrough}</span><span>{ar?"المراجعة التالية بحلول":"Next review due"} {date(article.nextReviewDueAt)}</span></footer></div>}</article>})}</div>}
      <div className={styles.boundary}><b>{ar?"كيف تستخدم هذه المكتبة":"How to use this library"}</b><p>{ar?"استخدم المقالات للتحضير لمحادثة مع مختص صحي. لا تستخدمها لتشخيص الأعراض أو تغيير دواء أو تأخير طلب الرعاية.":"Use these articles to prepare for a conversation with a healthcare professional. Do not use them to diagnose symptoms, change medication, or delay seeking care."}</p></div>
    </section>
  </main>
}
