import { AuthorizationDeniedError } from "@/lib/authorization";
import { DiagnosticImagingConflictError, DiagnosticImagingValidationError, getPartnerDiagnosticImaging, updatePartnerDiagnosticImaging } from "@/lib/diagnostic-imaging";
import { AuthenticationRequiredError, getOrCreateCurrentUser } from "@/lib/identity";
import { reportOperationalError } from "@/lib/observability";
import { enforceWriteRateLimit, rateLimitResponse } from "@/lib/rate-limits";
export const dynamic = "force-dynamic";
const headers = { "Cache-Control": "private, no-store" };
async function currentUser() { const user = await getOrCreateCurrentUser(); if (user.status !== "active") throw new AuthorizationDeniedError(); return user; }
export async function GET() { return handle(async () => getPartnerDiagnosticImaging((await currentUser()).id)); }
export async function POST(request: Request) { return handle(async () => { const user = await currentUser(); await enforceWriteRateLimit(user.id, "partner.diagnostic_imaging", { limit: 50 }); let body: Record<string, unknown>; try { body = await request.json() as Record<string, unknown>; } catch { throw new DiagnosticImagingValidationError("A valid JSON body is required"); } return updatePartnerDiagnosticImaging(user.id, body); }); }
async function handle(operation: () => Promise<unknown>) { try { return Response.json({ data: await operation() }, { headers }); } catch (error) { const limited = rateLimitResponse(error, headers); if (limited) return limited; if (error instanceof AuthenticationRequiredError) return Response.json({ error: "authentication_required" }, { status: 401, headers }); if (error instanceof AuthorizationDeniedError) return Response.json({ error: "forbidden" }, { status: 403, headers }); if (error instanceof DiagnosticImagingValidationError) return Response.json({ error: "invalid_request", message: error.message }, { status: 400, headers }); if (error instanceof DiagnosticImagingConflictError) return Response.json({ error: "conflict", message: error.message }, { status: 409, headers }); reportOperationalError("diagnostic_imaging.partner.failed", error); return Response.json({ error: "service_unavailable" }, { status: 503, headers: { ...headers, "Retry-After": "30" } }); } }
