"use client";

import { useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "@/app/privacy-rights/privacy-rights.module.css";

type Submission = { id: string; submissionType: string; details: string; createdAt: string };
type QueueItem = { id: string; requestType: string; status: string; version: number; submittedAt: string; submissions: Submission[] };
type AdminData = { role: string; visibility: string; metrics: Record<string, number>; queue: QueueItem[]; rehearsals: Array<{ id: string; result: string; scenarioCount: number; executedAt: string }> };

export default function PrivacyRightsAdministrationPage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<AdminData | null>(null), [reason, setReason] = useState<Record<string, string>>({}), [reference, setReference] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/admin/privacy-rights", { cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error); setData(payload.data); setError(""); } catch { setError(ar ? "تعذر تحميل عمليات حقوق الخصوصية." : "Privacy-rights operations could not be loaded."); } }, [ar]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function act(body: Record<string, unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/privacy-rights", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setMessage(success); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : (ar ? "فشلت العملية." : "The operation failed.")); } finally { setBusy(false); } }
  const typeLabel = (value: string) => ({ data_export: ar ? "تصدير البيانات" : "Data export", data_correction: ar ? "تصحيح البيانات" : "Data correction", account_closure: ar ? "إغلاق الحساب" : "Account closure" }[value] ?? value);
  return <main className={styles.adminShell} dir={ar ? "rtl" : "ltr"}><aside className={styles.side}><a href="/admin"><img src="/brand/qivaya-logo-reversed.png" alt="Qivaya" /></a><nav><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a className={styles.active} href="/admin/privacy-rights">{ar ? "حقوق الخصوصية" : "Privacy rights"}</a><a href="/admin/audit">{ar ? "سجل التدقيق" : "Audit ledger"}</a></nav></aside><div className={styles.content}>
    <header className={styles.heading}><div><span className={styles.eyebrow}>{ar ? "عمليات خاضعة للصلاحيات" : "Role-scoped operations"}</span><h1>{ar ? "عمليات حقوق الخصوصية" : "Privacy-rights operations"}</h1><p className={styles.muted}>{ar ? "معالجة يدوية موثقة مع مقاييس مجمعة لا تكشف هوية المرضى." : "Tracked manual processing with aggregate metrics that never expose patient identity."}</p></div><button className={styles.secondary} type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></header>
    <div className={styles.boundary}><span className={styles.boundaryIcon}>i</span><div><b>{ar ? "لا تنفيذ تلقائياً" : "No automated fulfilment"}</b><p>{ar ? "لا يقوم هذا السطح بتسليم ملف تصدير أو حذف سجل أو إغلاق حساب أو إرسال طلب إلى جهة خارجية." : "This workspace does not deliver an export, delete a record, close an account, or submit anything to an external authority."}</p></div></div>
    {message && <p className={styles.status} role="status">{message}</p>}{error && <p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
    <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "مقاييس مجمعة" : "Aggregate metrics"}</span><h2>{ar ? "حالة الطلبات" : "Request posture"}</h2></div><span className={styles.pill}>{data?.visibility.replaceAll("_", " ")}</span></div><div className={styles.metrics}>{Object.entries(data?.metrics ?? {}).map(([key, value]) => <div className={styles.metric} key={key}><b>{value}</b><span>{key.replaceAll(/([A-Z])/g, " $1")}</span></div>)}</div></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "قائمة معالجة بدون هوية" : "Identity-free processing queue"}</span><h2>{ar ? "الطلبات النشطة" : "Active requests"}</h2></div><p className={styles.muted}>{ar ? "تظهر التفاصيل اللازمة فقط للمسؤول المخول. لا تظهر هوية صاحب الحساب." : "Only necessary request details appear to an authorized administrator. Account-owner identity is not displayed."}</p></div>
      {data?.role === "security_auditor" ? <div className={styles.empty}>{ar ? "دور المدقق يقتصر على المقاييس والاختبارات." : "The auditor role is limited to aggregate metrics and rehearsals."}</div> : !data?.queue.length ? <div className={styles.empty}>{ar ? "لا توجد طلبات تحتاج إلى معالجة." : "No requests currently need processing."}</div> : <div className={styles.queue}>{data.queue.map((item) => <article className={styles.queueCard} key={item.id}><header><div><h3>{typeLabel(item.requestType)}</h3><span className={styles.requestId}>{item.id}</span></div><span className={styles.pill}>{item.status.replaceAll("_", " ")}</span></header>{item.submissions.map((submission) => <div className={styles.details} key={submission.id}>{submission.details}<div className={styles.meta}>{submission.submissionType.replaceAll("_", " ")} · {new Date(submission.createdAt).toLocaleString(ar ? "ar-QA" : "en-QA")}</div></div>)}
        <div className={styles.adminForm}>{item.status === "under_review" && <label className={styles.field}>{ar ? "رمز السبب عند طلب معلومات أو الرفض" : "Reason code for information request or decline"}<input value={reason[item.id] ?? ""} maxLength={128} onChange={(event) => setReason((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="document_scope_unclear" /></label>}{item.status === "approved_for_manual_fulfillment" && <label className={styles.field}>{ar ? "مرجع دليل التنفيذ اليدوي" : "Manual-fulfilment evidence reference"}<input value={reference[item.id] ?? ""} maxLength={128} onChange={(event) => setReference((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="OPS-PRIV-0000" /></label>}<div className={styles.actions}>{item.status === "submitted" && <button className={styles.primary} type="button" disabled={busy} onClick={() => void act({ action: "start_review", requestId: item.id, version: item.version }, ar ? "بدأت المراجعة." : "Review started.")}>{ar ? "بدء المراجعة" : "Start review"}</button>}{item.status === "under_review" && <><button className={styles.secondary} type="button" disabled={busy || !(reason[item.id]?.trim())} onClick={() => void act({ action: "request_information", requestId: item.id, version: item.version, reasonCode: reason[item.id] }, ar ? "تم طلب معلومات إضافية." : "Additional information requested.")}>{ar ? "طلب معلومات" : "Request information"}</button><button className={styles.primary} type="button" disabled={busy} onClick={() => void act({ action: "approve_manual_processing", requestId: item.id, version: item.version }, ar ? "اعتمد للتنفيذ اليدوي." : "Approved for manual fulfilment.")}>{ar ? "اعتماد يدوي" : "Approve manually"}</button><button className={styles.danger} type="button" disabled={busy || !(reason[item.id]?.trim())} onClick={() => void act({ action: "decline", requestId: item.id, version: item.version, reasonCode: reason[item.id] }, ar ? "تم تسجيل القرار." : "Decision recorded.")}>{ar ? "عدم الموافقة" : "Decline"}</button></>}{item.status === "approved_for_manual_fulfillment" && <button className={styles.primary} type="button" disabled={busy || !(reference[item.id]?.trim())} onClick={() => void act({ action: "record_manual_completion", requestId: item.id, version: item.version, completionReference: reference[item.id] }, ar ? "تم تسجيل دليل التنفيذ اليدوي." : "Manual completion evidence recorded.")}>{ar ? "تسجيل الاكتمال اليدوي" : "Record manual completion"}</button>}</div></div>
      </article>)}</div>}
    </section>
    <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "تحقق اصطناعي" : "Synthetic assurance"}</span><h2>{ar ? "اختبار بلا آثار جانبية" : "Zero-side-effect rehearsal"}</h2></div><button className={styles.primary} type="button" disabled={busy} onClick={() => void act({ action: "run_rehearsal" }, ar ? "اكتمل الاختبار." : "Rehearsal completed.")}>{ar ? "تشغيل 18 سيناريو" : "Run 18 scenarios"}</button></div><p className={styles.muted}>{ar ? "يتحقق من الملكية والصلاحيات وتعارض الإصدارات ومنع التسليم والحذف والإغلاق والإرسال الخارجي التلقائي." : "Validates ownership, role scope, version conflicts, and the prevention of automatic delivery, deletion, closure, and external submission."}</p><div className={styles.rehearsals}>{data?.rehearsals.map((item) => <div className={styles.rehearsal} key={item.id}><b>{item.result}</b><span className={styles.meta}>{item.scenarioCount} scenarios · {new Date(item.executedAt).toLocaleString()}</span></div>)}</div></section>
  </div></main>;
}
