"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useReyatiLocale } from "@/app/components/useReyatiLocale";
import styles from "@/app/consents/consents.module.css";

type Policy = { id: string; purposeCode: string; policyVersion: number; titleEn: string; titleAr: string; summaryEn: string; summaryAr: string; noticeEn: string; noticeAr: string; status: string; reviewDecision: string | null; effectiveFrom: string; expiresAt: string | null; activatedAt: string | null; retiredAt: string | null; version: number; makerCheckerSatisfied: boolean };
type Rehearsal = { id: string; result: string; scenarioCount: number; executedAt: string };
type AdminData = { role: string; visibility: string; metrics: Record<string, number>; policies: Policy[]; rehearsals: Rehearsal[] };
const emptyDraft = { purposeCode: "care_coordination", titleEn: "", titleAr: "", summaryEn: "", summaryAr: "", noticeEn: "", noticeAr: "", effectiveFrom: "", expiresAt: "" };
const purposes: Record<string, { en: string; ar: string }> = { care_coordination: { en: "Care coordination", ar: "تنسيق الرعاية" }, family_access: { en: "Family access", ar: "وصول أفراد العائلة" }, research_participation: { en: "Research participation", ar: "المشاركة في الأبحاث" }, service_communications: { en: "Service communications", ar: "رسائل الخدمة" }, data_sharing: { en: "Purpose-limited data sharing", ar: "مشاركة البيانات لغرض محدد" } };

export default function AdminConsentsPage() {
  const [lang, setLang] = useReyatiLocale(), ar = lang === "ar";
  const [data, setData] = useState<AdminData | null>(null), [draft, setDraft] = useState(emptyDraft), [reasons, setReasons] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/admin/consents", { cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error); setData(payload.data); setError(""); } catch { setError(ar ? "تعذر تحميل حوكمة الموافقات." : "Consent governance could not be loaded."); } }, [ar]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function act(body: Record<string, unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/consents", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error); setMessage(success); setReasons({}); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : (ar ? "فشلت العملية." : "The operation failed.")); } finally { setBusy(false); } }
  function submit(event: FormEvent) { event.preventDefault(); void act({ action: "prepare_policy", ...draft, effectiveFrom: draft.effectiveFrom || null, expiresAt: draft.expiresAt || null }, ar ? "تم إعداد مسودة السياسة." : "Policy draft prepared."); }
  const purposeLabel = (value: string) => purposes[value]?.[ar ? "ar" : "en"] ?? value.replaceAll("_", " ");
  const statusLabel = (value: string) => ({ draft: ar ? "مسودة" : "Draft", pending_review: ar ? "بانتظار المراجعة" : "Awaiting review", approved: ar ? "معتمدة" : "Approved", active: ar ? "نشطة" : "Active", retired: ar ? "متقاعدة" : "Retired" }[value] ?? value);
  const ready = draft.titleEn.trim().length >= 4 && draft.titleAr.trim().length >= 4 && draft.summaryEn.trim().length >= 12 && draft.summaryAr.trim().length >= 12 && draft.noticeEn.trim().length >= 20 && draft.noticeAr.trim().length >= 20;
  return <main className={styles.adminShell} dir={ar ? "rtl" : "ltr"}><aside className={styles.side}><a href="/admin"><img src="/brand/qivaya-logo-reversed.png" alt="Qivaya" /></a><nav><a href="/admin">{ar ? "نظرة عامة" : "Overview"}</a><a className={styles.active} href="/admin/consents">{ar ? "حوكمة الموافقات" : "Consent governance"}</a><a href="/admin/audit">{ar ? "سجل التدقيق" : "Audit ledger"}</a></nav></aside><div className={styles.content}>
    <header className={styles.heading}><div><span className={styles.eyebrow}>{ar ? "حوكمة ثنائية التحكم" : "Dual-control governance"}</span><h1>{ar ? "سياسات الموافقات" : "Consent policies"}</h1><p className={styles.muted}>{ar ? "إعداد ومراجعة وتفعيل سياسات محددة الغرض مع فصل واضح بين المُعدّ والمراجع." : "Prepare, review, and activate purpose-specific policies with clear separation between maker and checker."}</p></div><button className={styles.secondary} type="button" onClick={() => setLang(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button></header>
    <div className={styles.boundary}><span className={styles.boundaryIcon}>i</span><div><b>{ar ? "التفعيل هنا لا يشغّل أي استخدام لاحق" : "Activation here does not enable downstream use"}</b><p>{ar ? "لا توجد مزامنة خارجية أو تجاوز من مقدم الخدمة أو تجديد صامت. يجب أن تعتمد الأنظمة اللاحقة قراراً منفصلاً وصريحاً قبل أي استخدام." : "There is no external synchronization, provider override, or silent renewal. Downstream systems require a separate explicit implementation decision before any use."}</p></div></div>
    {message && <p className={styles.status} role="status">{message}</p>}{error && <p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
    <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "مقاييس مجمعة" : "Aggregate posture"}</span><h2>{ar ? "نظرة عامة" : "Governance overview"}</h2></div><span className={styles.pill}>{data?.visibility.replaceAll("_", " ")}</span></div><div className={styles.metrics}>{Object.entries(data?.metrics ?? {}).map(([key, value]) => <div className={styles.metric} key={key}><b>{value}</b><span>{key.replaceAll(/([A-Z])/g, " $1")}</span></div>)}</div></section>
    {data?.role !== "security_auditor" && <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "دور المُعدّ" : "Maker workspace"}</span><h2>{ar ? "إعداد إصدار سياسة جديد" : "Prepare a new policy version"}</h2></div><p className={styles.muted}>{ar ? "يُعيّن رقم الإصدار التالي تلقائياً عند الحفظ." : "The next policy version is assigned automatically when saved."}</p></div><form className={styles.policyForm} onSubmit={submit}>
      <label className={styles.field}>{ar ? "الغرض" : "Purpose"}<select value={draft.purposeCode} onChange={(event) => setDraft((current) => ({ ...current, purposeCode: event.target.value }))}>{Object.entries(purposes).map(([value, copy]) => <option value={value} key={value}>{copy[ar ? "ar" : "en"]}</option>)}</select></label><label className={styles.field}>{ar ? "تاريخ السريان" : "Effective date"}<input type="date" value={draft.effectiveFrom} onChange={(event) => setDraft((current) => ({ ...current, effectiveFrom: event.target.value }))} /></label>
      <label className={styles.field}>English title<input maxLength={160} value={draft.titleEn} onChange={(event) => setDraft((current) => ({ ...current, titleEn: event.target.value }))} /></label><label className={styles.field}>العنوان العربي<input lang="ar" maxLength={160} value={draft.titleAr} onChange={(event) => setDraft((current) => ({ ...current, titleAr: event.target.value }))} /></label>
      <label className={styles.field}>English summary<textarea maxLength={600} value={draft.summaryEn} onChange={(event) => setDraft((current) => ({ ...current, summaryEn: event.target.value }))} /></label><label className={styles.field}>الملخص العربي<textarea lang="ar" maxLength={600} value={draft.summaryAr} onChange={(event) => setDraft((current) => ({ ...current, summaryAr: event.target.value }))} /></label>
      <label className={styles.field}>English full notice<textarea maxLength={3000} value={draft.noticeEn} onChange={(event) => setDraft((current) => ({ ...current, noticeEn: event.target.value }))} /></label><label className={styles.field}>الإشعار العربي الكامل<textarea lang="ar" maxLength={3000} value={draft.noticeAr} onChange={(event) => setDraft((current) => ({ ...current, noticeAr: event.target.value }))} /></label>
      <label className={styles.field}>{ar ? "تاريخ الانتهاء (اختياري)" : "Expiry date (optional)"}<input type="date" value={draft.expiresAt} onChange={(event) => setDraft((current) => ({ ...current, expiresAt: event.target.value }))} /></label><div className={styles.actions}><button className={styles.primary} type="submit" disabled={busy || !ready}>{ar ? "حفظ المسودة" : "Save draft"}</button></div>
    </form></section>}
    <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "دورة حياة محكومة" : "Governed lifecycle"}</span><h2>{ar ? "سجل السياسات" : "Policy register"}</h2></div><p className={styles.muted}>{data?.role === "security_auditor" ? (ar ? "يقتصر دور المدقق على المقاييس والاختبارات." : "The auditor role is limited to aggregate metrics and rehearsals.") : (ar ? "يجب أن يكون المراجع شخصاً مختلفاً عن المُعدّ." : "The checker must be a different administrator from the maker.")}</p></div>
      {!data?.policies.length ? <div className={styles.empty}>{ar ? "لا توجد سياسات في السجل." : "No policies are in the register."}</div> : <div className={styles.queue}>{data.policies.map((policy) => <article className={styles.queueCard} key={policy.id}><header><div><span className={styles.eyebrow}>{purposeLabel(policy.purposeCode)}</span><h3>{ar ? policy.titleAr : policy.titleEn}</h3><span className={styles.requestId}>{policy.id} · v{policy.policyVersion}</span></div><span className={styles.pill}>{statusLabel(policy.status)}</span></header><div className={styles.policyCopy}><div><b>{policy.titleEn}</b><p>{policy.summaryEn}</p></div><div dir="rtl"><b>{policy.titleAr}</b><p>{policy.summaryAr}</p></div></div><div className={styles.meta}>{ar ? "السريان" : "Effective"}: {new Date(policy.effectiveFrom).toLocaleDateString()} {policy.expiresAt ? `· ${ar ? "الانتهاء" : "Expires"}: ${new Date(policy.expiresAt).toLocaleDateString()}` : ""} · {ar ? "فصل الأدوار" : "Maker-checker"}: {policy.makerCheckerSatisfied ? (ar ? "مكتمل" : "satisfied") : (ar ? "بانتظار الإكمال" : "pending")}</div>
        {["pending_review", "active"].includes(policy.status) && <label className={styles.field}>{ar ? "رمز سبب الإرجاع أو التقاعد" : "Return or retirement reason code"}<input value={reasons[policy.id] ?? ""} onChange={(event) => setReasons((current) => ({ ...current, [policy.id]: event.target.value }))} maxLength={128} placeholder="policy_scope_update" /></label>}
        <div className={styles.actions}>{policy.status === "draft" && <button className={styles.primary} type="button" disabled={busy} onClick={() => void act({ action: "submit_for_review", policyId: policy.id, version: policy.version }, ar ? "أرسلت للمراجعة." : "Sent for review.")}>{ar ? "إرسال للمراجعة" : "Submit for review"}</button>}{policy.status === "pending_review" && <><button className={styles.primary} type="button" disabled={busy} onClick={() => void act({ action: "approve_policy", policyId: policy.id, version: policy.version }, ar ? "تم اعتماد السياسة." : "Policy approved.")}>{ar ? "اعتماد كمراجع" : "Approve as checker"}</button><button className={styles.secondary} type="button" disabled={busy || !reasons[policy.id]} onClick={() => void act({ action: "return_policy", policyId: policy.id, version: policy.version, reasonCode: reasons[policy.id] }, ar ? "أعيدت للمُعدّ." : "Returned to maker.")}>{ar ? "إعادة للمُعدّ" : "Return to maker"}</button></>}{policy.status === "approved" && <button className={styles.primary} type="button" disabled={busy} onClick={() => void act({ action: "activate_policy", policyId: policy.id, version: policy.version }, ar ? "تم تفعيل السياسة فقط." : "Policy activated only.")}>{ar ? "تفعيل السياسة" : "Activate policy"}</button>}{policy.status === "active" && <button className={styles.danger} type="button" disabled={busy || !reasons[policy.id]} onClick={() => void act({ action: "retire_policy", policyId: policy.id, version: policy.version, reasonCode: reasons[policy.id] }, ar ? "تم تقاعد السياسة." : "Policy retired.")}>{ar ? "تقاعد السياسة" : "Retire policy"}</button>}</div>
      </article>)}</div>}
    </section>
    <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>{ar ? "تحقق اصطناعي" : "Synthetic assurance"}</span><h2>{ar ? "اختبار بلا آثار جانبية" : "Zero-side-effect rehearsal"}</h2></div><button className={styles.primary} type="button" disabled={busy} onClick={() => void act({ action: "run_rehearsal" }, ar ? "اكتمل الاختبار." : "Rehearsal completed.")}>{ar ? "تشغيل 20 سيناريو" : "Run 20 scenarios"}</button></div><p className={styles.muted}>{ar ? "يتحقق من الملكية وفصل الأدوار وتعارض الإصدارات والانتهاء ومنع التجديد الصامت والتجاوز والمزامنة والتفعيل اللاحق التلقائي." : "Validates ownership, maker-checker separation, version conflicts, expiry, and prevention of silent renewal, override, synchronization, and automatic downstream activation."}</p><div className={styles.rehearsals}>{data?.rehearsals.map((item) => <div className={styles.rehearsal} key={item.id}><b>{item.result}</b><span className={styles.meta}>{item.scenarioCount} scenarios · {new Date(item.executedAt).toLocaleString()}</span></div>)}</div></section>
  </div></main>;
}
