"use client";

import { useState } from "react";

type Tab="plans"|"eligibility"|"enrollment"|"privacy";
const plans=[
  {name:"Reyati Plus",members:176,allowance:"QAR 4,000",family:"Included",status:"Active"},
  {name:"Reyati Essential",members:66,allowance:"QAR 2,000",family:"Not included",status:"Active"},
  {name:"Executive Care",members:6,allowance:"QAR 8,000",family:"Included",status:"Draft"},
];
const roster=[
  ["AM","Aisha M.","EMP-1058","Finance","Reyati Plus","Ready"],
  ["FK","Fahad K.","EMP-1059","Operations","Reyati Essential","Ready"],
  ["LN","Layla N.","EMP-1060","Consulting","—","Needs review"],
  ["HS","Hamad S.","EMP-1061","Consulting","Reyati Plus","Ready"],
];

export default function PartnerProgram(){
  const [lang,setLang]=useState<"en"|"ar">("en");const [tab,setTab]=useState<Tab>("plans");const [drawer,setDrawer]=useState<"plan"|"rule"|null>(null);const [notice,setNotice]=useState("");const [plan,setPlan]=useState(0);const ar=lang==="ar";
  const flash=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),2500)};
  return <main className={`program-shell ${ar?"arabic":""}`} dir={ar?"rtl":"ltr"}>
    <aside className="program-sidebar"><a className="partner-brand" href="/"><img src="/brand/reyati-logo-reversed.svg" alt="Reyati"/><span>{ar?"مزايا الشركاء":"Partner benefits"}</span></a><div className="program-org"><span>AC</span><div><b>Atlas Consulting</b><small>{ar?"مساحة عمل صاحب العمل":"Employer workspace"}</small></div></div><nav><a href="/partner"><span>◫</span>{ar?"نظرة عامة":"Overview"}</a><a href="/partner"><span>◉</span>{ar?"الأعضاء":"Members"}<i>248</i></a><a href="/partner"><span>Q</span>{ar?"التمويل":"Funding"}</a><a href="/partner"><span>▤</span>{ar?"الفواتير":"Invoices"}</a><a className="active" href="/partner/program"><span>⚙</span>{ar?"إعداد البرنامج":"Programme setup"}</a></nav><div className="program-privacy"><span>♙</span><p><b>{ar?"حدود الخصوصية":"Privacy boundary"}</b>{ar?"لا تكشف قواعد البرنامج استخداماً طبياً فردياً.":"Programme rules never reveal individual medical use."}</p></div><div className="program-links"><a href="/journeys">◇ {ar?"جميع المسارات":"All journeys"}</a><a href="/support">? {ar?"دعم الشركاء":"Partner support"}</a></div></aside>
    <section className="program-main"><header className="program-top"><div><span>2026 {ar?"سنة المزايا":"BENEFIT YEAR"}</span><b>{ar?"١ يناير – ٣١ ديسمبر":"1 Jan – 31 Dec"}</b></div><div><button onClick={()=>setLang(ar?"en":"ar")}>{ar?"English":"العربية"}</button><a href="/notifications">●</a><span>SA</span></div></header><div className="program-workspace">
      <div className="program-heading"><div><p>{ar?"تصميم وإدارة البرنامج":"PROGRAMME DESIGN & CONTROL"}</p><h1>{ar?"إعداد برنامج المزايا":"Benefits programme setup"}</h1><span>{ar?"أدر الخطط والأهلية والتسجيل دون الوصول إلى بيانات صحية شخصية.":"Manage plans, eligibility, and enrollment without access to personal health data."}</span></div><button onClick={()=>setDrawer("plan")}>＋ {ar?"إنشاء خطة":"Create plan"}</button></div>
      <div className="program-status"><span>✓</span><p><b>{ar?"برنامج 2026 نشط":"2026 programme is active"}</b>{ar?"248 عضواً مؤهلاً عبر خطتين نشطتين. كل التغييرات محاكاة آمنة.":"248 eligible members across 2 active plans. Every change is safely simulated."}</p><i>{ar?"تمت المراجعة 31 يوليو":"REVIEWED 31 JUL"}</i></div>
      <div className="program-tabs">{(["plans","eligibility","enrollment","privacy"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="plans"?(ar?"الخطط والمزايا":"Plans & benefits"):x==="eligibility"?(ar?"قواعد الأهلية":"Eligibility rules"):x==="enrollment"?(ar?"التسجيل والقائمة":"Enrollment & roster"):(ar?"الخصوصية والحوكمة":"Privacy & governance")}</button>)}</div>
      {tab==="plans"&&<><section className="program-metrics">{[["◇","2",ar?"خطط نشطة":"Active plans"],["◉","248",ar?"عضواً مشمولاً":"Covered members"],["Q","QAR 612k",ar?"تمويل سنوي":"Annual funding"],["↗","73%",ar?"تفعيل الحساب":"Account activation"]].map(x=><article key={x[2]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></article>)}</section><section className="plans-grid">{plans.map((p,i)=><article key={p.name} className={plan===i?"selected":""} onClick={()=>setPlan(i)}><div className={`plan-logo p${i}`}>R</div><i className={p.status.toLowerCase()}>{p.status}</i><h2>{p.name}</h2><p>{ar?"رصيد رعاية سنوي مرن":"Flexible annual care allowance"}</p><div className="allowance"><span>{ar?"لكل موظف":"Per employee"}</span><b>{p.allowance}</b></div><dl><div><dt>{ar?"الأعضاء":"Members"}</dt><dd>{p.members}</dd></div><div><dt>{ar?"تغطية الأسرة":"Family coverage"}</dt><dd>{p.family}</dd></div><div><dt>{ar?"الفترة":"Period"}</dt><dd>Jan–Dec 2026</dd></div></dl><button onClick={e=>{e.stopPropagation();setDrawer("plan")}}>{ar?"تعديل الخطة":"Edit plan"} →</button></article>)}</section><section className="plan-boundary"><span>ⓘ</span><div><b>{ar?"ما الذي تموله الخطة":"What the plan funds"}</b><p>{ar?"تحدد الخطة الرصيد والخدمات المؤهلة. لا يرى صاحب العمل الخدمة أو مقدم الرعاية أو التشخيص للفرد.":"Plans define balance and eligible categories. Employers never see an individual’s service, provider, or diagnosis."}</p></div><a href="/support">{ar?"سياسة الخصوصية":"Privacy policy"}</a></section></>}
      {tab==="eligibility"&&<section className="rules-layout"><div className="rules-card"><div className="section-head"><div><h2>{ar?"قواعد الأهلية النشطة":"Active eligibility rules"}</h2><p>{ar?"تطبق بالترتيب على قائمة الموارد البشرية.":"Applied in order to the HR roster."}</p></div><button onClick={()=>setDrawer("rule")}>＋ {ar?"إضافة قاعدة":"Add rule"}</button></div>{[["01","Employment status is Active","All active employees","248 matches","Reyati Essential"],["02","Grade is Director or above","Leadership grades","42 matches","Reyati Plus"],["03","Tenure is 12 months or more","Established employees","134 matches","+ QAR 500"],["04","Family benefit is elected","Optional dependant cover","71 matches","Family included"]].map(r=><article className="rule-row" key={r[0]}><span>{r[0]}</span><div><b>{r[1]}</b><small>{r[2]}</small></div><i>{r[3]}</i><strong>{r[4]}</strong><button onClick={()=>flash(ar?"تم فتح القاعدة التجريبية":"Prototype rule opened")}>•••</button></article>)}</div><aside className="rule-preview"><p>{ar?"معاينة النتيجة":"OUTCOME PREVIEW"}</p><div className="rule-ring"><span><b>248</b><small>{ar?"مؤهل":"eligible"}</small></span></div><dl><div><dt>{ar?"مؤهل تلقائياً":"Auto-eligible"}</dt><dd>242</dd></div><div><dt>{ar?"يحتاج مراجعة":"Needs review"}</dt><dd>6</dd></div><div><dt>{ar?"غير مؤهل":"Not eligible"}</dt><dd>12</dd></div></dl><div className="rule-alert"><span>!</span><p><b>{ar?"6 سجلات ناقصة":"6 incomplete records"}</b>{ar?"تاريخ البدء أو الدرجة مفقود.":"Start date or grade is missing."}</p></div><button onClick={()=>setTab("enrollment")}>{ar?"مراجعة الاستثناءات":"Review exceptions"} →</button></aside></section>}
      {tab==="enrollment"&&<><section className="enrollment-steps">{[["1",ar?"رفع القائمة":"Roster uploaded","✓"],["2",ar?"التحقق من البيانات":"Data validated","✓"],["3",ar?"مراجعة الأهلية":"Review eligibility","current"],["4",ar?"تأكيد التسجيل":"Confirm enrollment",""]].map((x,i)=><div key={x[0]}><article className={x[2]==="✓"?"done":x[2]==="current"?"current":""}><span>{x[2]==="✓"?"✓":x[0]}</span><b>{x[1]}</b></article>{i<3&&<i>→</i>}</div>)}</section><section className="roster-card"><div className="section-head"><div><h2>{ar?"معاينة التسجيل":"Enrollment preview"}</h2><p>{ar?"راجع التعيينات قبل إرسال الدعوات.":"Review assignments before invitations are sent."}</p></div><div><button onClick={()=>flash(ar?"تم إعداد نموذج القائمة":"Roster template prepared")}>⇩ {ar?"النموذج":"Template"}</button><button onClick={()=>flash(ar?"تمت محاكاة الرفع":"Upload simulated")}>↑ {ar?"رفع قائمة":"Upload roster"}</button></div></div><div className="roster-table"><header><span>{ar?"الموظف":"Employee"}</span><span>{ar?"القسم":"Department"}</span><span>{ar?"الخطة":"Assigned plan"}</span><span>{ar?"الحالة":"Status"}</span><span/></header>{roster.map(r=><article key={r[2]}><div><span>{r[0]}</span><p><b>{r[1]}</b><small>{r[2]}</small></p></div><span>{r[3]}</span><strong>{r[4]}</strong><i className={r[5]==="Ready"?"ready":"review"}>{r[5]}</i><button>›</button></article>)}</div><footer><span><b>3</b> {ar?"جاهز":"ready"}</span><span><b>1</b> {ar?"يحتاج مراجعة":"needs review"}</span><button onClick={()=>flash(ar?"تم تأكيد تسجيل تجريبي لـ 3 أعضاء":"Prototype enrollment confirmed for 3 members")}>{ar?"تأكيد 3 أعضاء":"Confirm 3 members"}</button></footer></section></>}
      {tab==="privacy"&&<section className="privacy-layout"><article className="privacy-principles"><div className="section-head"><div><h2>{ar?"حدود بيانات صاحب العمل":"Employer data boundary"}</h2><p>{ar?"ما يمكن لفريق المزايا رؤيته وما يبقى خاصاً.":"What your benefits team can see—and what stays private."}</p></div><span>♙ {ar?"مطبق":"ENFORCED"}</span></div><div className="boundary-columns"><section><h3>✓ {ar?"يمكنك الاطلاع على":"You can access"}</h3><ul><li>{ar?"حالة الأهلية والخطة":"Eligibility and plan status"}</li><li>{ar?"الرصيد الممول المتبقي":"Remaining funded balance"}</li><li>{ar?"استخدام إجمالي مجهول الهوية":"Anonymous aggregate utilization"}</li><li>{ar?"الفواتير والتسويات":"Invoices and reconciliation"}</li></ul></section><section><h3>× {ar?"لن تتمكن من الاطلاع على":"You cannot access"}</h3><ul><li>{ar?"التشخيصات أو السجلات الطبية":"Diagnoses or medical records"}</li><li>{ar?"الخدمات أو مقدمي الرعاية للفرد":"Individual services or providers"}</li><li>{ar?"مواعيد الزيارات أو الملاحظات":"Visit dates or encounter notes"}</li><li>{ar?"بحث الموظف أو رسائله":"Employee searches or messages"}</li></ul></section></div></article><aside className="governance-card"><h2>{ar?"ضوابط الحوكمة":"Governance controls"}</h2>{[["Minimum aggregate group","10 members"],["Employer admin access","3 people"],["Access review cadence","Every 90 days"],["Data retention","7 years"],["Last privacy review","31 Jul 2026"]].map(x=><div key={x[0]}><span>✓</span><p>{x[0]}<b>{x[1]}</b></p></div>)}<button onClick={()=>flash(ar?"تم إعداد تقرير الحوكمة":"Governance report prepared")}>⇩ {ar?"تنزيل تقرير الحوكمة":"Download governance report"}</button></aside></section>}
    </div></section>
    {drawer&&<div className="program-drawer-layer" onMouseDown={e=>e.target===e.currentTarget&&setDrawer(null)}><aside className="program-drawer"><button className="drawer-x" onClick={()=>setDrawer(null)}>×</button><p>{drawer==="plan"?"PLAN CONFIGURATION":"ELIGIBILITY LOGIC"}</p><h2>{drawer==="plan"?(ar?"تعديل خطة المزايا":"Edit benefits plan"):(ar?"إضافة قاعدة أهلية":"Add eligibility rule")}</h2><span>{ar?"كل التغييرات محاكاة وآمنة.":"All changes are safely simulated."}</span>{drawer==="plan"?<><label>{ar?"اسم الخطة":"Plan name"}<input defaultValue={plans[plan].name}/></label><div className="drawer-grid"><label>{ar?"الرصيد السنوي":"Annual allowance"}<input defaultValue={plans[plan].allowance}/></label><label>{ar?"تغطية الأسرة":"Family coverage"}<select defaultValue={plans[plan].family}><option>Included</option><option>Not included</option></select></label></div><label>{ar?"وصف للموظف":"Employee-facing description"}<textarea defaultValue="A flexible annual care allowance for eligible services in the Reyati network."/></label></>:<><label>{ar?"حقل الموظف":"Employee field"}<select><option>Employment status</option><option>Grade</option><option>Department</option><option>Tenure</option></select></label><div className="drawer-grid"><label>{ar?"المعامل":"Operator"}<select><option>is equal to</option><option>is one of</option></select></label><label>{ar?"القيمة":"Value"}<input defaultValue="Active"/></label></div><label>{ar?"النتيجة":"Outcome"}<select><option>Reyati Essential</option><option>Reyati Plus</option><option>Not eligible</option></select></label></>}<div className="drawer-note"><span>♙</span><p><b>{ar?"لا تستخدم بيانات صحية":"No health data in rules"}</b>{ar?"تعتمد الأهلية على بيانات العمل فقط.":"Eligibility uses employment data only."}</p></div><div className="drawer-actions"><button onClick={()=>setDrawer(null)}>{ar?"إلغاء":"Cancel"}</button><button onClick={()=>{setDrawer(null);flash(ar?"تم حفظ التغيير التجريبي":"Prototype change saved")}}>{ar?"حفظ":"Save change"}</button></div></aside></div>}
    {notice&&<div className="program-toast"><span>✓</span>{notice}</div>}
  </main>
}
